### ISSUE TITLE
Follow the CSS coding standard

### ISSUE THREAD

**Issue by elboletaire** [sachinchoolur/lightGallery#100]
You are using names for your classes that are not following none of the most used standards...

- http://primercss.io/guidelines/#examples
- http://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml?showone=ID_and_Class_Name_Delimiters#ID_and_Class_Name_Delimiters
- https://make.wordpress.org/core/handbook/coding-standards/css/
- https://github.com/necolas/idiomatic-css#4-format

This is a bit annoying because I follow the basic standard of naming classes and ids with hypens and every time I need to style one of your plugins' classes I need to check the code to see how is it written.

If this is a pain for you, tell me, and I'll do a PR with these changes.

PS: Yes, I've copied exactly the same issue for both lightSlider and lightGallery. Both should be fixed in my oppinion.

**Comment by sachinchoolur** [comment]
Thanks for the links. 
I am working on lightGallery version 1.2. I will try to follow these standards.
It would be helpful if you could do a pull request for the current version.
