### ISSUE TITLE
Can't resolve 'lightgallery/react' in 2.0.0 release

### ISSUE THREAD

**Issue by Jeonghyun-Kim** [sachinchoolur/lightGallery#1002]
## Description

error - ./components/core/LightGallery.tsx:12:55
Module not found: Can't resolve 'lightgallery/react'

### Steps to reproduce

npm install lightgallery@latest

### Expected result

- with 2.0.0-beta.3 release (previously used)
![image](https://user-images.githubusercontent.com/18566690/118443909-6e798f80-b727-11eb-9270-a267fb6ff2b4.png)

### Actual result

- with 2.0.0 release
![image](https://user-images.githubusercontent.com/18566690/118443820-53a71b00-b727-11eb-850b-d7b202f53806.png)

**Comment by Jeonghyun-Kim** [comment]
Are you planning or trying to extract react/vue package?

**Comment by sachinchoolur** [comment]
Hey @Jeonghyun-Kim ,

No. Due to some unexpected build problems, lightGallery React, Angular, and Vue.js builds were not included in the previous release. 
Sorry for the inconvenience.  Please use version 2.0.1

https://github.com/sachinchoolur/lightGallery/releases/tag/2.0.1

**Comment by Jeonghyun-Kim** [comment]
@sachinchoolur  Wow, it’s new just before. I'll try it out.
