### ISSUE TITLE
Uncaught TypeError: Cannot read property 'contains' of null  at HTMLDivElement

### ISSUE THREAD

**Issue by glassesUSA** [sachinchoolur/lightGallery#1004]
## Description

lightgallery.ts:1836 Uncaught TypeError: Cannot read property 'contains' of null
    at HTMLDivElement.<anonymous> (lightgallery.ts:1836)
(anonymous) @ lightgallery.ts:1836

The plugin will not let me click on anything on the page or click on the lightbox elements themselves to open them

**Comment by sachinchoolur** [comment]
Hey @glassesUSA,

Thank you for reporting this issue. 
Looks like lightGallery is not initialized properly. Could you please share the HTML and JavaScript code that you are using to initialize lightGallery?

**Comment by glassesUSA** [comment]
JS:

`        insertScript = document.createElement("script");
        insertScript.src = 'https://cdn.jsdelivr.net/npm/lightgallery@2.0.1/lightgallery.umd.min.js'
        document.head.appendChild(insertScript)
        let q = setInterval(() => {
            if (typeof lightGallery != undefined) {
                clearInterval(q)
                lightGallery(document.querySelector('.freebiesBanner img'), {
                    selector: 'this',
                    container: document.querySelector('.bannerScroll')
                    // enableSwipe: false,
                    // enableDrag: false
                });
            }
        }, 200);`


HTML:

` <div class="bannerScroll">
                    <div class="freebiesBanner" data-src="E-Cards 1.png">
                        <img src="E-Cards 1.png" alt="">
                    </div>
                    <div class="freebiesBanner" data-src="./E-Cards 2.png">
                        <img src="./E-Cards 2.png" alt="">
                    </div>
                    <div class="freebiesBanner" data-src="./E-Cards 3.png">
                        <img src="./E-Cards 3.png" alt="">
                    </div>
                    <div class="freebiesBanner" data-src="./E-Cards 4.png">
                        <img src="./E-Cards 4.png" alt="">
                    </div>
                    <div class="spacingEnd"></div>
                </div>`

**Comment by sachinchoolur** [comment]
Could you please remove the container option and try initializing it the following way?

lightGallery(document.querySelector('.bannerScroll'), {
    selector: '.freebiesBanner',
    enableSwipe: false,
});

If this doesn't work for you, please update the [codepen demo](https://codepen.io/sachinchoolur/pen/qBrbbNQ) with your HTML markup and share it with me.

I'll fix the issue and send you back

**Comment by glassesUSA** [comment]
So it works perfectly fine on codepen for some reason but not in the live.

**Comment by sachinchoolur** [comment]
Are you getting any other errors on the console?
Also, please make sure the HTML elements are available at the time of initialization

**Comment by glassesUSA** [comment]
`    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.10.0/css/lightgallery.min.css"
        integrity="sha512-gk6oCFFexhboh5r/6fov3zqTCA2plJ+uIoUx941tQSFg6TNYahuvh1esZVV0kkK+i5Kl74jPmNJTTaHAovWIhw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />`

This seems to be the issue

**Comment by glassesUSA** [comment]
Changing the css to point to the jsdelivr version fixed it. It seems that the cdnjs links are outdated and no longer working

**Comment by sachinchoolur** [comment]
Awesome. Thanks 

Yes, somehow the latest version is not updated on cdnjs 
Works fine on jsdelivr and all other cdns - https://cdn.jsdelivr.net/npm/lightgallery@2.0.1/css/lightgallery-bundle.css
