### ISSUE TITLE
Installing v2 license message

### ISSUE THREAD

**Issue by ddrury** [sachinchoolur/lightGallery#1005]
## Description

Browser debug console giving message 
`lightGallery: 0000-0000-000-0000 license key is not valid for production use`

### Steps to reproduce

I'm attempting to install using Laravel webpack.mix.js to combine all 3rd party npm packages into two files (vendor.js & vendor.css)

In package.json I add ` "lightgallery": "^2.0.1", `in the list of dependencies
In vendor.js I found that a normal` "Import lightgallery"` resulted in browser console message 
> llightGallery is not defined 

so I ended up by adding `window.lightGallery = require('lightgallery/lightgallery.umd.js');` 

### Expected result

Lightgallery should open when clicking an image

### Actual result

Browser debug console giving message as above and lightgallery not opening

### Additional context

This is an upgrade from lightgallery.js and is using a dynamic collection of images

**Comment by sachinchoolur** [comment]
Hey @ddrury,

The console message shouldn't block lightGallery from opening. It will disappear when you pass a valid license key via settings - https://www.lightgalleryjs.com/docs/settings/#licenseKey

Yes, if you are not using the ES6 module, you can use the UMD file.

Could you please share your HTML and JavaScript code that you are using to initialize lightGallery? 

CodePen demos - https://codepen.io/collection/BNNjpR

**Comment by ddrury** [comment]
Hm, two steps forward - one back. I'd missed the call to openGallery, but now I get the message
`Uncaught TypeError: current.openGallery is not a function`
here is my code
```
    let x = lightGallery(current, {
      plugins: [lgZoom],
      dynamic:   true,
      dynamicEl: collection,
    });

    console.log(x);
    current.openGallery(0);
```
The console.log x shows

>  Object { lgOpened: false, index: 0, plugins: [], lGalleryOn: false, lgBusy: false, ....

**Comment by sachinchoolur** [comment]
It should be x.openGallery(0)
https://www.lightgalleryjs.com/demos/dynamic-mode/

**Comment by ddrury** [comment]
Doh, I'm an idiot!!!
