### ISSUE TITLE
Some scss files have been renamed

### ISSUE THREAD

**Issue by ddrury** [sachinchoolur/lightGallery#1006]
## Description

node_modules/lightgallery/scss/lightgallery-core && node_modules/lightgallery/scss/lightgallery contain the following lines

```
@import 'lg-variables';
@import 'lg-mixins';
@import 'lg-fonts';
@import 'lg-theme-default';
```

however, these files have been renamed by prefixing with an underscore

**Comment by sachinchoolur** [comment]
Hey @ddrury ,

This is how it works in scss
> You can create partial Sass files that contain little snippets of CSS that you can include in other Sass files. This is a great way to modularize your CSS and help keep things easier to maintain. A partial is a Sass file named with a leading underscore. You might name it something like _partial.scss. The underscore lets Sass know that the file is only a partial file and that it should not be generated into a CSS file. Sass partials are used with the @use rule.

You don't have to use `_` while importing partial Scss

**Comment by ddrury** [comment]
Hm, I learn't something new - sorry for wasting your time

**Comment by sachinchoolur** [comment]
It's ok. Thank you so much for all your contributions so far
