### ISSUE TITLE
Browser warning - for info

### ISSUE THREAD

**Issue by ddrury** [sachinchoolur/lightGallery#1007]
## Description

Firefox Browser debug console shows the following warning on gallery open (not reported on Chrome or Edge)

`Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (1002238 px). Occurrences of will-change over the budget will be ignored.`

See https://stackoverflow.com/questions/56025536/will-change-memory-consumption-is-too-high-firefox-issue for a possible resolution

**Comment by sachinchoolur** [comment]
Thank you for reporting this. 

This might be related to image size. I'll take a look and get back to you.

**Comment by sachinchoolur** [comment]
The issue has been fixed in version [2.1.8](https://github.com/sachinchoolur/lightGallery/commit/090965acf74f96e15fcea2546b85ecb5c9ac5293). Thank you for reporting this
