### ISSUE TITLE
Justified gallery view for v2?

### ISSUE THREAD

**Issue by jengalas** [sachinchoolur/lightGallery#1008]
Is there a justified gallery view for version 2 of lightGallery (without jQuery)? Any suggestions on how best to implement one? Thanks.

**Comment by sachinchoolur** [comment]
Hey @jengalas,
I could not find any justified gallery-like plugin without jQuery dependency. 
The concept to integrate lightGallery with any other plugin is simple. If the plugin modifies any HTML tag, you need to wait until it finishes the DOM update. 

If you know any plugin similar to the justified gallery I can guide you to implement it with lightGallery .

**Comment by jengalas** [comment]
I could not find one either. I'll see what I can come up with, and will let you know if I need some help. Thank you for your excellent work!
