### ISSUE TITLE
Lightgallery v2 - first thoughts

### ISSUE THREAD

**Issue by ddrury** [sachinchoolur/lightGallery#1009]
Congratulations - a nice module, compact & fast.

A couple of things I miss from v1 (or at least I can't find them)

- The ability to continuously zoom for eack click of the button.
- The ability to turn on/off the thumbnail toolbar on the fly (including the `showThumbByDefault `option).

but other than that all good

**Comment by sachinchoolur** [comment]
Thanks for the feedback. 

- The first option is available in v2 too. https://www.lightgalleryjs.com/docs/settings/#actualSize
You can use  setting [showZoomInOutIcons](https://www.lightgalleryjs.com/docs/settings/#showZoomInOutIcons) to enable zoom in and zoom out icons.
By default, the [actualSize](https://www.lightgalleryjs.com/docs/settings/#actualSize) option is enabled. So, you'll have to disable it or change the icons using `actualSizeIcons` [setting](https://www.lightgalleryjs.com/docs/settings/#actualSizeIcons) to disable duplicate zoom icons.
Here is the codepen demo - https://codepen.io/sachinchoolur/pen/wvJgLKM

- `toggleThumb` option is still available.  but `showThumbByDefault` has been removed. toggle thumbnails icon has been moved to the tolbar. And it will be difficult for the users that thumbnails are available but it is hidden. But I'm ok to add `showThumbByDefault` option if we get more requests.

**Comment by dbrabyn** [comment]
+1 for showThumbByDefault

**Comment by keerankb** [comment]
Hey @sachinchoolur,

Currently, my requirement is, I need to display the `toggleThumb` button on toolbar menu, & at the same time I don't want to display my thumbnails by default, only if I clicked on **toggleThumb** icon then only I should be able to see all the thumbnail images. (by default the thumbnails should be hidden, till I click on that **toggleThumb** icon from toolbar )

I am trying to achieve this scenario by the below configuration -

**allowMediaOverlap: true,
toggleThumb: true,
thumbnail: false,**

And the output I am getting is, if I set `thumbnail` to `false`, & `toggleThumb` to `true`, then neither the **toggleThumb** icon is visible, nor the **thumbnails** are visible in `lg-component` section.

So, Can you please explain me how I can achieve this ?
