### ISSUE TITLE
Callback access to local variables such as index and settings

### ISSUE THREAD

**Issue by markaschneider** [sachinchoolur/lightGallery#101]
I'm using lightGallery to display images.  When calling lightGallery(), I pass in dynamicEl (an array of hashes).  Alongside each image, I want to display data such as who uploaded the image, when it was uploaded, and possibly comments (similar to what Facebook currently does).

In the dynamicEl hashes, along with the attributes lightGallery looks for, I'm including extra data such as an image's database id.  When a user navigates to a slide, in my onSlideBefore callback function, I want to use that id to look up the image's data and comments.  When onSlideBefore is called, if it could know the index that lightGallery is processing, I could do what I want.

Is there a way to access the index from a callback function such as onSlideBefore?

Thanks

**Comment by sachinchoolur** [comment]
Hi,
With default functionality it is not possible but you achieve this by updating lightGallery.js line number 658.
just pass index in the onSlideBefore callback function
``` javascript
// settings.onSlideBefore.call(this, plugin);  to
settings.onSlideBefore.call(this, plugin, index);
```
Here is the demo http://jsfiddle.net/sachin377/p1aw7utk/14/

**Comment by markaschneider** [comment]
Thank you for responding and being so helpful.   I also wound up needing access to the settings (so I could access dynamicEl).  As a suggestion, for those of us who are building extensions similar to what I’m building, would you consider including index and settings as parameters in all of the callbacks in a future build?

Thanks again,
Mark

**Comment by sachinchoolur** [comment]
Hi,
I am working on lightGallery version 1.2. Once it is done will be able to access all the variables and functions of lightGallery from outside
