### ISSUE TITLE
Custom icons

### ISSUE THREAD

**Issue by glassesUSA** [sachinchoolur/lightGallery#1010]
## Summary

Allow us to define custom icons for the different buttons

**Comment by sachinchoolur** [comment]
You can change the next and previous buttons as shown in the demo - https://www.lightgalleryjs.com/demos/methods/

Toolbar icons can be easily replaced by CSS. Either you can replace the font icons or use any image as background images. 

If you want to use inline SVG icons, you can replace them using lightGallery events and methods as used in the [demo](https://www.lightgalleryjs.com/demos/methods/)

```js
const $galleryContainer = document.getElementById("gallery-container");

// Custom close icon
const closeIcon = `<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
<title>cancel-circle</title>
<path d="M16 0c-8.837 0-16 7.163-16 16s7.163 16 16 16 16-7.163 16-16-7.163-16-16-16zM16 29c-7.18 0-13-5.82-13-13s5.82-13 13-13 13 5.82 13 13-5.82 13-13 13z"></path>
<path d="M21 8l-5 5-5-5-3 3 5 5-5 5 3 3 5-5 5 5 3-3-5-5 5-5z"></path>
</svg>`;

$galleryContainer.addEventListener("lgInit", () => {
  const $lgCloseIcon = document.querySelector(".lg .lg-close");
  $lgCloseIcon.insertAdjacentHTML("beforeend", closeIcon);
});

lightGallery($galleryContainer);
```

```css
.lg-close::after {
    content: ''
}
```

Codepen demo  - https://codepen.io/sachinchoolur/pen/LYWxJQb

Please let me know if you have any questions

**Comment by Pixelous** [comment]
Hi @sachinchoolur 

`const $lgCloseIcon = document.querySelector(".lg .lg-close");`

not working for me so I use

`const lgCloseIcon = pluginInstance.$toolbar.selector.querySelector(".lg-close");`

instead.

In regards to nav buttons no need to use **lgAfterOpen** event and disabling default controls as here https://www.lightgalleryjs.com/demos/methods/

So I ended up with this code:

```js
$galleryContainer.addEventListener("lgInit", () => {
  // Close icon
  const closeIcon = "close svg here";
  const lgCloseIcon = pluginInstance.$toolbar.selector.querySelector(".lg-close");
  lgCloseIcon.insertAdjacentHTML("beforeEnd", closeIcon);

  // Prev icon
  const prevIcon = "prev svg here";
  const lgPrevIcon = pluginInstance.$content.selector.querySelector(".lg-prev");
  lgPrevIcon.insertAdjacentHTML("beforeEnd", prevIcon);

  // Next icon
  const nextIcon = "next svg here";
  const lgNextIcon = pluginInstance.$content.selector.querySelector(".lg-next");
  lgNextIcon.insertAdjacentHTML("beforeEnd", nextIcon);
});
```
