### ISSUE TITLE
lightgallery on click image page refresh in nuxt

### ISSUE THREAD

**Issue by tarangshah19** [sachinchoolur/lightGallery#1015]
In Nuxt On click of image page refresh gallery not get open when i get data dynamically (Axios call) it give me this issue

**Comment by tarangshah19** [comment]
issue

**Comment by sachinchoolur** [comment]
Hey @tarangshah19,

At present, the Vue version does not update itself based on data change. 
You need to destroy and re-initiate lightGallery when the data gets changed. 
Or you can call the `updateSlides` method 

Resources 
- https://www.lightgalleryjs.com/demos/update-slides/
- https://www.lightgalleryjs.com/docs/methods/
- https://www.lightgalleryjs.com/demos/infinite-scrolling/

This is planned for the next version. I'll try to publish it ASAP

**Comment by tarangshah19** [comment]
thank you for replaying but now its showing 

Cannot read property 'addEventListener' of undefined 

code

mounted() {
    let el = document.getElementById('lightgallery');
      lightGallery(el);
     window.lightGallery(document.getElementById('lightgallery')).addEventListener('click', function() {
     el.insertAdjacentHTML('beforeend', this.gallery);
     window.lgData[el.getAttribute('lg-uid')].destroy(true);
     lightGallery(el);
   }, false);
    this.getMedia();
  },
  methods:{
    getMedia() {
      this.$axios
        .$get(
          process.env.BASE_URL + "/getgalleryMediaNew/6062cf8f2adcee001bbc2dae/Image",
          {
            timeout: 120000,
          }
        )
        .then((resp) => {
          this.gallery = resp;
          console.log(this.gallery)
        })
    }
  }

**Comment by sachinchoolur** [comment]
Hey @tarangshah19 ,

I see some issues with your code. I'll try to provide a stackblitz demo by today EOD

**Comment by tarangshah19** [comment]
ok i am waiting for your reply 

thank you

**Comment by tarangshah19** [comment]
Hello Any update for issue?

**Comment by sachinchoolur** [comment]
Here is the demo - https://stackblitz.com/edit/lightgallery-vue-update-slides

```js
<template>
    <button v-on:click="updateSlides">Add new image</button>
    <lightgallery
        :settings="{ speed: 500, plugins: plugins }"
        :onInit="onInit"
        :onBeforeSlide="onBeforeSlide"
    >
        <a
            v-for="item in items"
            :key="item.id"
            :data-lg-size="item.size"
            className="gallery-item"
            :data-src="item.src"
        >
            <img className="img-responsive" :src="item.thumb" />
        </a>
    </lightgallery>
</template>

<script>
import Lightgallery from 'lightgallery/vue';
import lgZoom from 'lightgallery/plugins/zoom';
let lightGallery: any = null;
export default {
    name: 'App',
    components: {
        Lightgallery,
    },
    watch: {
        items(newVal, oldVal) {
            this.$nextTick(() => {
                lightGallery.refresh();
            });
        },
    },
    data: () => ({
        plugins: [lgZoom],
        items: [
            {
                id: '1',
                size: '1400-933',
                src:
                    'https://images.unsplash.com/photo-1542103749-8ef59b94f47e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1400&q=80',
                thumb:
                    'https://images.unsplash.com/photo-1542103749-8ef59b94f47e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80',
                subHtml: `<div class="lightGallery-captions">
                <h4>Photo by <a href="https://unsplash.com/@dann">Dan</a></h4>
                <p>Published on November 13, 2018</p>
            </div>`,
            },
            {
                id: '2',
                size: '1400-933',
                src:
                    'https://images.unsplash.com/photo-1473876988266-ca0860a443b8?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1400&q=80',
                thumb:
                    'https://images.unsplash.com/photo-1473876988266-ca0860a443b8?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80',
                subHtml: `<div class="lightGallery-captions">
                <h4>Photo by <a href="https://unsplash.com/@kylepyt">Kyle Peyton</a></h4>
                <p>Published on September 14, 2016</p>
            </div>`,
            },
            {
                id: '3',
                size: '1400-932',
                src:
                    'https://images.unsplash.com/photo-1588953936179-d2a4734c5490?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1400&q=80',
                thumb:
                    'https://images.unsplash.com/photo-1588953936179-d2a4734c5490?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=240&q=80',
                subHtml: `<div class="lightGallery-captions">
                <h4>Photo by <a href="https://unsplash.com/@jxnsartstudio">Garrett Jackson</a></h4>
                <p>Published on May 8, 2020</p>
            </div>`,
            },
        ],
    }),
    methods: {
        onInit: (detail) => {
            lightGallery = detail.instance;
        },
        updateSlides: function () {
            this.items = [
                ...this.items,
                {
                    id: '4',
                    size: '1400-933',
                    src:
                        'https://images.unsplash.com/photo-1609902726285-00668009f004?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1400&q=80',
                    thumb:
                        'https://images.unsplash.com/photo-1609902726285-00668009f004?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=240&q=80',
                    subHtml: `<div class="lightGallery-captions">
                <h4>Photo by <a href="https://unsplash.com/@bruno_adam">Bruno Adam</a></h4>
                <p>Published on January 6, 2021</p>
            </div>`,
                },
            ];
            lightGallery.refresh();
        },
        onBeforeSlide: () => {
            console.log('calling before slide');
        },
    },
};
</script>
<style lang="css">
@import url('https://cdn.jsdelivr.net/npm/lightgallery@2.1.0-beta.1/css/lightgallery.css');
@import url('https://cdn.jsdelivr.net/npm/lightgallery@2.1.0-beta.1/css/lg-zoom.css');
body {
    margin: 0;
}
.gallery-item {
    margin: 5px;
}
</style>


```

**Comment by sachinchoolur** [comment]
Forgot to mention in my last comment - 
```lightGallery.refresh()``` is avaiable only since version [2.1.0-beta.1](https://www.npmjs.com/package/lightgallery/v/2.1.0-beta.1
)

**Comment by tarangshah19** [comment]
How to Use lightgallery@2.1.0-beta.1 uisng NPM?

**Comment by sachinchoolur** [comment]
`npm install lightgallery@2.1.0-beta.1`

**Comment by tarangshah19** [comment]
Thank you for supporting me but i am getting error of 
render function or template not defined in component: lightgallery 
I am Using Nuxt

my code
<template>
  <div class="demo-gallery">













    <lightgallery
      :settings="{ speed: 500, plugins: plugins }"
      :onInit="onInit"
      :onBeforeSlide="onBeforeSlide"
    >
      <a
        v-for="gallery in gallery"
        :key="gallery.url._id"
        :data-src="gallery.url.mediaUrl"
        className="gallery-item"
        :data-sub-html="gallery.url.uploadedAt">
      >
        <img className="img-responsive" :src="gallery.url.mediaUrl" />
      </a>
    </lightgallery>
  </div>
</template>

<script>
import Lightgallery from 'lightgallery/vue';
import lgZoom from 'lightgallery/plugins/zoom';
let lightGallery = null;
// import 'lightgallery.js';
// import 'lightgallery.js/dist/css/lightgallery.css';
// import 'lg-zoom.js'
// import 'lg-autoplay.js'
// import 'lg-fullscreen.js'
// import 'lg-hash.js'
// import 'lg-pager.js'
// import 'lg-share.js'
// import 'lg-thumbnail.js'
// import 'lg-video.js'
export default {
  //Import lightgallery
  name: 'HelloWorld',
  components: {
    Lightgallery,
  },
  data(){
    return{
      plugins: [lgZoom],
      gallery:[]
    }
  },
  watch: {
    gallery(newVal, oldVal) {
      this.$nextTick(() => {
        lightGallery.refresh();
      });
    },
  },
  mounted() {
   // let $a = document.getElementById("lightgallery");
   //
   //  window.lightGallery($a, {
   //    thumbnail: true,
   //    animateThumb: true,
   //    counter: true,
   //    download: true,
   //    dynamic: true,
   //    //thumbnail: true,
   //    subHtmlSelectorRelative: true,
   //  });
   //
   //  $a.data('lightgallery').destroy(true);
   //
   //  $a.lightGallery();
    // To destroy
    this.getMedia();

  },
  methods:{
    onInit: (detail) => {
      lightGallery = detail.instance;
    },
    getMedia() {
      this.$axios
        .$get(
          process.env.BASE_URL + "/getgalleryMediaNew/6062cf8f2adcee001bbc2dae/Image",
          {
            timeout: 120000,
          }
        )
        .then((resp) => {
          this.gallery = resp;
          console.log(this.gallery)
        })
      lightGallery.refresh();
    },
    onBeforeSlide: () => {
      console.log('calling before slide');
    },
  }
}
</script>


<style scoped>
#set{
  display: flex;
  justify-content: center;
}
ul li a.img{
  width: 200px;
  height: 200px;
  padding: 10px
}
body {
  background-color: #152836;
  color: #eee;
  font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif
}

.small {
  font-size: 11px;
  color: #999;
  display: block;
  margin-top: -10px
}

.cont {
  text-align: center;
}

.page-head {
  padding: 60px 0;
  text-align: center;
}

.page-head .lead {
  font-size: 18px;
  font-weight: 400;
  line-height: 1.4;
  margin-bottom: 50px;
  margin-top: 0;
}

.btn {
  -moz-user-select: none;
  background-image: none;
  border: 1px solid transparent;
  border-radius: 2px;
  cursor: pointer;
  display: inline-block;
  font-size: 14px;
  font-weight: normal;
  line-height: 1.42857;
  margin-bottom: 0;
  padding: 6px 12px;
  text-align: center;
  vertical-align: middle;
  white-space: nowrap;
  text-decoration: none;
}

.btn-lg {
  border-radius: 2px;
  font-size: 18px;
  line-height: 1.33333;
  padding: 10px 16px;
}

.btn-primary:hover {
  background-color: #fff;
  color: #152836;
}

.btn-primary {
  background-color: #152836;
  border-color: #0e1a24;
  color: #ffffff;
}

.btn-primary {
  border-color: #eeeeee;
  color: #eeeeee;
  transition: color 0.1s ease 0s, background-color 0.15s ease 0s;
}

.page-head h1 {
  font-size: 42px;
  margin: 0 0 20px;
  color: #FFF;
  position: relative;
  display: inline-block;
}

.page-head h1 .version {
  bottom: 0;
  color: #ddd;
  font-size: 11px;
  font-style: italic;
  position: absolute;
  width: 58px;
  right: -58px;
}

.demo-gallery > ul {
  margin-bottom: 0;
  padding-left: 15px;
}

.demo-gallery > ul > li {
  margin-bottom: 15px;
  width: 180px;
  display: inline-block;
  margin-right: 15px;
  list-style: outside none none;
}

.demo-gallery > ul > li a {
  border: 3px solid #FFF;
  border-radius: 3px;
  display: block;
  overflow: hidden;
  position: relative;
  float: left;
}

.demo-gallery > ul > li a > img {
  -webkit-transition: -webkit-transform 0.15s ease 0s;
  -moz-transition: -moz-transform 0.15s ease 0s;
  -o-transition: -o-transform 0.15s ease 0s;
  transition: transform 0.15s ease 0s;
  -webkit-transform: scale3d(1, 1, 1);
  transform: scale3d(1, 1, 1);
  height: 100%;
  width: 100%;
}

.demo-gallery > ul > li a:hover > img {
  -webkit-transform: scale3d(1.1, 1.1, 1.1);
  transform: scale3d(1.1, 1.1, 1.1);
}

.demo-gallery > ul > li a:hover .demo-gallery-poster > img {
  opacity: 1;
}

.demo-gallery > ul > li a .demo-gallery-poster {
  background-color: rgba(0, 0, 0, 0.1);
  bottom: 0;
  left: 0;
  position: absolute;
  right: 0;
  top: 0;
  -webkit-transition: background-color 0.15s ease 0s;
  -o-transition: background-color 0.15s ease 0s;
  transition: background-color 0.15s ease 0s;
}

.demo-gallery > ul > li a .demo-gallery-poster > img {
  left: 50%;
  margin-left: -10px;
  margin-top: -10px;
  opacity: 0;
  position: absolute;
  top: 50%;
  -webkit-transition: opacity 0.3s ease 0s;
  -o-transition: opacity 0.3s ease 0s;
  transition: opacity 0.3s ease 0s;
}

.demo-gallery > ul > li a:hover .demo-gallery-poster {
  background-color: rgba(0, 0, 0, 0.5);
}

.demo-gallery .justified-gallery > a > img {
  -webkit-transition: -webkit-transform 0.15s ease 0s;
  -moz-transition: -moz-transform 0.15s ease 0s;
  -o-transition: -o-transform 0.15s ease 0s;
  transition: transform 0.15s ease 0s;
  -webkit-transform: scale3d(1, 1, 1);
  transform: scale3d(1, 1, 1);
  height: 100%;
  width: 100%;
}

.demo-gallery .justified-gallery > a:hover > img {
  -webkit-transform: scale3d(1.1, 1.1, 1.1);
  transform: scale3d(1.1, 1.1, 1.1);
}

.demo-gallery .justified-gallery > a:hover .demo-gallery-poster > img {
  opacity: 1;
}

.demo-gallery .justified-gallery > a .demo-gallery-poster {
  background-color: rgba(0, 0, 0, 0.1);
  bottom: 0;
  left: 0;
  position: absolute;
  right: 0;
  top: 0;
  -webkit-transition: background-color 0.15s ease 0s;
  -o-transition: background-color 0.15s ease 0s;
  transition: background-color 0.15s ease 0s;
}

.demo-gallery .justified-gallery > a .demo-gallery-poster > img {
  left: 50%;
  margin-left: -10px;
  margin-top: -10px;
  opacity: 0;
  position: absolute;
  top: 50%;
  -webkit-transition: opacity 0.3s ease 0s;
  -o-transition: opacity 0.3s ease 0s;
  transition: opacity 0.3s ease 0s;
}

.demo-gallery .justified-gallery > a:hover .demo-gallery-poster {
  background-color: rgba(0, 0, 0, 0.5);
}

.demo-gallery .video .demo-gallery-poster img {
  height: 48px;
  margin-left: -24px;
  margin-top: -24px;
  opacity: 0.8;
  width: 48px;
}

.demo-gallery.dark > ul > li a {
  border: 3px solid #04070a;
}
</style>

in package .js 
"lightgallery": "^2.1.0-beta.1",

**Comment by tarangshah19** [comment]
Hello any solution for my issue ?

**Comment by sachinchoolur** [comment]
https://www.lightgalleryjs.com/docs/vue/ is not compactable with vue 2. 

But you can try creating your own component with lightGallery 2 as shown https://github.com/sachinchoolur/lightgallery.js/issues/60

If you face any issues, please please share a stackblitz demo with what you have.

**Comment by tarangshah19** [comment]
Hello i have created on project using axios call please see and let me know where i am doing mistake 

https://codesandbox.io/s/dawn-shadow-k7jf3?file=/src/App.vue

**Comment by sachinchoolur** [comment]
Here is the updated working demo - https://codesandbox.io/s/morning-framework-13dw5?file=/src/App.vue

Hope you'll be able to make out the differences. 
Note: fonts are not loading properly in the demo. But I think that is the issue of loaders. should work fine with your app

There is a change in the template as well. I removed unwanted `<a>` tag
```vue
<li
        v-for="gallery in gallery"
        :key="gallery.id"
        :data-src="gallery.url"
        :data-sub-html="gallery.title"
      >
        <img class="img-responsive" :src="gallery.thumbnailUrl" />
 </li>

```

Let me know if you have any questions

**Comment by tarangshah19** [comment]
Thank you so much for supporting issue is resolved 

Thanks
