### ISSUE TITLE
License collision

### ISSUE THREAD

**Issue by Vadiok** [sachinchoolur/lightGallery#1018]
As I understand from the text of license, if I'm using your gallery at commercial website, I should purchase a commercial license.
But if I fork your library I can publish my fork under the GNU GPL v3 and use this fork in commercial website without purchasing license from you.
Is my explanation correct?

**Comment by Vadiok** [comment]
Sorry, I think it'll be correct to move this question from Issues to Discussion

**Comment by sachinchoolur** [comment]
No. Forking an open-source software project does not change the ownership of copyrights in the source code that was formed from the original project. 

From the [GNU docs](https://www.gnu.org/licenses/gpl-faq.html#GPLRequireSourcePostedPublic)
> If you release the **modified version to the public** in some way, the GPL requires you to make the modified source code available to the program's users, under the GPL.

Please read  - https://www.gnu.org/licenses/gpl-3.0.html#section5
