### ISSUE TITLE
Console warning about a license key

### ISSUE THREAD

**Issue by oliworx** [sachinchoolur/lightGallery#1022]
## Description

Console warning: 
_lightGallery: 0000-0000-000-0000 license key is not valid for production use_

### Steps to reproduce

Open https://www.kurmis.com/gallery/a/2020-08-Schleissheim.html in Google Chrome and watch the browser console

### Expected result

No console warning is generated

### Actual result

Console warning: 
_lightGallery: 0000-0000-000-0000 license key is not valid for production use_

### Additional context

I downloaded the zip file from GitHub, so no npm or build tool involved.

**Comment by sachinchoolur** [comment]
Hey @oliworx,

If you are using lightGallery for commercial projects, you need to purchase a commercial license
to get the license key. For projects that are compatible with GPLv3 license,
please contact us for getting a license key at contact@lightgalleryjs.com.

https://www.lightgalleryjs.com/license/

https://www.lightgalleryjs.com/docs/settings/#licenseKey

Please let me know if you have any questions

**Comment by oliworx** [comment]
I am using lightGallery on my personal homepage only, so it is not a commercial project.

**Comment by sachinchoolur** [comment]
But you need to make sure that your website is open-sourced and compatible with the GPLv3 license to get a free license key.

If you want to keep your source code proprietarily, you need a commercial license. 

Please contact me at contact@lightgalleryjs.com. I'll try to help you
