### ISSUE TITLE
is not working on nextJs SSR

### ISSUE THREAD

**Issue by violabg** [sachinchoolur/lightGallery#1024]
does it support SSR?
I'm trying to use it with NextJs and getting
window is not defined

**Comment by sachinchoolur** [comment]
Hey @violabg ,

For now please use nextjs dynamic-import with no SSR.
https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr


```jsx
const LightGallery = dynamic(() => import('lightgallery/react'), {
	ssr: false,
});

<LightGallery mode='lg-fade'>...</LightGallery>

```
Here is the demo - https://stackblitz.com/edit/lightgallery-with-nextjs

lighGallery core module uses few global functions. So I don't have a clear solution at the moment

**Comment by violabg** [comment]
Cool, thank you very much.

**Comment by BjoernRave** [comment]
would be cool if this would be supported without the workaround

**Comment by yacoob** [comment]
FWIW, I saw similar problems with gridsome and nuxt. Is there a bug which is generic (not about a specific framework) and talks about what needs to be done in order for lightgallery to work properly with ssr? I was able to get things working with gridsome, currently playing (and failing) with nuxt, and it'd be good to have a single issue here to collate workarounds.
