### ISSUE TITLE
Dynamic option typed as false instead of boolean on d.ts file

### ISSUE THREAD

**Issue by berkayyildiz** [sachinchoolur/lightGallery#1027]
## Description
When try to add dynamic option and set true it warns that it is set to false.

### Steps to reproduce
Create an empty ts project, install lightgallery via npm, try to init gallery as most basic.
```
import lightGallery from "lightgallery";

const el = <HTMLElement>document.getElementById("gallery");
let gallery = lightGallery(el, {
  dynamic: true,
  dynamicEl: []
});
````
[Code Sandbox Examle](https://codesandbox.io/s/vibrant-tereshkova-b3ibf?file=/src/index.ts)

### Expected result

I should be able to set dynamic:true

### Actual result

It gives type error

### Additional context
There is not.

**Comment by sachinchoolur** [comment]
Hey @berkayyildiz,

This was fixed a couple of days ago in 2.1.0 beta release. 

Just published 2.1.0 stable version. Please upgrade
