### ISSUE TITLE
Content security policy collides with insertAdjacentHTML and innerHTML

### ISSUE THREAD

**Issue by chrillek** [sachinchoolur/lightGallery#1029]
## Summary

I'm using a locally hosted ightGallery and a content security policy relying on the sha256 fingerprint for it. This works ok in that the browser _loads_ the code. However, it barfs at the usage of insertAdjacentHTML and assigning to innerHTML in two places. According to the info on the net, inserting HTML directly into a website is (now?) considered unsafe, so it collides with the CSP. 

### Basic example
What Firefox says: Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("style-src"). 4 LG_bundle.fd467ecc63601e9b41f5b38b72ab76983b6803574f8338cc8c50bcfc541181d1.js:315:23
(Sorry for the German, it basically says that the settings of the page have blocked loading an inline resource). The 
The lines in question are those:
```
lgQuery.prototype.html = function (html) {
            if (html === undefined) {
                if (!this.firstElement) {
                    return '';
                }
                return this.firstElement.innerHTML;
            }
            this._each(function (el) {
                el.innerHTML = html;
            });
            return this;
        };
        lgQuery.prototype.append = function (html) {
            this._each(function (el) {
                if (typeof html === 'string') {
                    el.insertAdjacentHTML('beforeend', html);
```
### Motivation

Content security policies are considered good practice, so it should be possible to use them with lightGallery.

**Comment by sachinchoolur** [comment]
Hey @chrillek ,

Sorry, I missed this issue. I'll look into this in detail and get back to you

**Comment by chrillek** [comment]
No worries. Just let me know if you need more detail.

**Comment by seitsu** [comment]
@chrillek: Is there a workaround to use lightGallery with CSP? Or how did you solve that?

**Comment by chrillek** [comment]
Sorry, I didn't notice your post (seems to be the rule with this issue ;-) Anyway: I doubt that it's possible to use a reasonable CSP at the moment with lightgallery. The problem are the three calls to `innerHTML` and similar functions. Those are considered unsafe _style_ settings because the html could contain an inline style.

The only way to stop Chrome et from barfing at the CSP is by setting `unsafe-inline` which kind of contradicts the whole _idea_ of a CSP. So someone would have to refactor `LGQuery.prototype.html` and `LGQuery.prototype.load` and the code calling them to do The Right Thing(tm).
