### ISSUE TITLE
Purpose of using `data-src` instead of `a href` attributes

### ISSUE THREAD

**Issue by elboletaire** [sachinchoolur/lightGallery#103]
I've just hallucinate how are you treating the main images in lightGallery.

In your documentation you say to mount galleries this way:

```html
<ul id="lightGallery">
  <li data-src="img/img1.jpg">
    <img src="img/thumb1.jpg" />
  </li>
  <li data-src="img/img2.jpg">
    <img src="img/thumb2.jpg" />
  </li>
  ...
</ul>
```
But the videos example is as follows:

```html
<ul id="video">
    <li data-src="http://www.youtube.com/watch?v=eKG08z85DtY"> 
      <a href="#">
        <img src="img/Pigloo.jpg" />
      </a> 
    </li>
  ...
</ul>
``` 
The questions
------------------

- Why do you use, sometimes the `a` tag, and why there are sometimes where you don't use it??
- Also, why are you using the `data-src` attribute instead of using the proper `href` attribute from the a (if pressent)??

Thanks in advance :)

**Comment by sachinchoolur** [comment]
Hi,
* In the video example `a` tag is not required. It was added by mistake. There is no specific markup for lightGallery. If you want you can follow your own markup. the only thing is you have to specify your  custom selector while initiating gallery.
* User can use different  tags including `div li span` for creating lightGallery markup not only anchor tag.
    Using html5 data-* attribute also semantic and we can use with any tag. So i feel this approach is better than targeting a particular html tag  

**Custom markup example**
``` html
<div id="lightgallery">
    <div>
        <div class="custom-selector" data-src="img1.jpg">
            <img src="thumb1.jpg" />
        </div>
    </div>
    <div>
        <div>
            <div class="custom-selector" data-src="img2.jpg">
                <img src="thumb2.jpg" />
            </div>
        </div>
    </div>
    <div class="custom-selector" data-src="img3.jpg">
        <img src="thumb3.jpg" />
    </div>
</div>
```
``` javascript
$('#lightgallery').lightGallery({
    selector: '.custom-selector'
});
```

**Comment by elboletaire** [comment]
Thanks :smile:

**Comment by elboletaire** [comment]
Hey @sachinchoolur the `selector` option does not allow me to set a link (`a`) to use its `href` attribute :\

One of my questions was 'why do you force us to use the data-src attribute' and taking a look to the code I see there's no other way, as you don't check for an `href` attribute:

https://github.com/sachinchoolur/lightGallery/blob/master/light-gallery/js/lightGallery.js#L359

```js
var $this = this;
var i, j, l = $children.length - index;
var src;

if (settings.preload > $children.length) {
    settings.preload = $children.length;
}
if (settings.mobileSrc === true && windowWidth <= settings.mobileSrcMaxWidth) {
    if (settings.dynamic) {
        src = settings.dynamicEl[index].mobileSrc;
    } else {
        src = $children.eq(index).attr('data-responsive-src');
    }
}

// Fall back to use non-responsive source if no responsive source was found
if (!src) {
    if (settings.dynamic) {
        src = settings.dynamicEl[index].src;
    } else {
        src = $children.eq(index).attr('data-src');
    }
}
```

So, I ask again... Why do you force us to use the `data-src` attribute? It does not follow any standard... 

Instead of using custom `data` params, why not to use the default and usual params, like the `href` attribute from an `a` or the new HTML5 `srcset` attribute (?):

http://demosthenes.info/blog/944/Responsive-Images-For-Retina-Using-HTML5s-srcset

**Comment by sachinchoolur** [comment]
First of all data-* is a part of html5 and is also semantic. [http://www.w3schools.com/](http://www.w3schools.com/tags/att_global_data.asp) , [developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_data_attributes)
If we use href instead of data-src we need to force user to use anchor tag with their markup.
If we use data-* attribute user can use whatever markup they want 
ex
``` html
<div>
    <div data-src="larger-imag.jpg"></div>
    <div data-src="larger-image1.jpg"></div>
</div>
<ul>
    <li data-src="larger-image.jpg"></li>
    <li data-src="larger-image1.jpg"></li>
<ul>
<div>
    <a href="#" data-src="larger-image.jpg"></a>
    <a href="#" data-src="larger-image1.jpg"></a>
</div>
```
So i think there is no issue with standards. But if using anchor tag and href makes better impact on SEO we can consider using it. 
What do you think? is there any other major advantage if we use anchor tag with href?

**Comment by elboletaire** [comment]
Yes, using `data-src` is semantic too but I was referring to the SEO impact, as you said.

By default I would check for an `href` attribute and, in case we can't find it, then I would fallback to use the `data-src` attribute.

I also said that the `srcset` could also be used as an alternate `data-responsive-src` (if no `srcset` was found, then fallback to `data-responsive-src`) but there's no need to do nothing with the `srcset` as, if it has been defined, the browser will be the one who'll change the src of the image based on the pixel density or the screen width.

**Comment by elboletaire** [comment]
@sachinchoolur could you please open again this issue or the issue #107 so we can continue talking about this. If it's closed usually means that has been resolved, which is not the case.

I've finally solved this issue by manually adding the `data-src` before executing the lightGallery plugin:

```js
$("article section.body figure").each(function() {
    var image = $(this).find('img'),
        link = $(this).find('a');

    image.attr('data-src', link.attr('href'));

    link.lightGallery();
});
```

Anyway, I think that the default behavior should be search for a standard SEO-friendly tag/attribute (which is the common used way...) as it's `a`.

**Comment by sachinchoolur** [comment]
Hi,
I will use href attribute in the next version with data-src fallback.

Thanks.

**Comment by elboletaire** [comment]
:+1: :smile:

**Comment by sachinchoolur** [comment]
Hi,
I have released version 1.2 with this feature..

**Comment by elboletaire** [comment]
:+1:

**Comment by isilsh** [comment]
sorry i'm new to this, I've been struggling now for many hours trying to get lightgallery to work inside a masonry layout, its working well with the data-src attribute, but not with the href, i was hoping to implement the aforementioned solution but i'm not having much success, hoping somebody could help me out? thank you so much--- http://codepen.io/ilsh/pen/eZrBNm- the lightgallery works only on the last two items (not working on codepen but on my computer) i'd like to have the hrefs working for SEO purposes thank you.
