### ISSUE TITLE
Provide an api to open gallery without html

### ISSUE THREAD

**Issue by VladStepanov** [sachinchoolur/lightGallery#1035]
## Summary

It would be cool, if API would have a method, that takes an array of slides and opens a gallery with them.
Something like in glightbox https://github.com/biati-digital/glightbox/blob/master/README.md#lightbox-options

### Basic example

```js
lightGallery.open([
  { src: '...' },
  { src: '...' }
])
```

### Motivation

Sometimes we don't have access to HTML(for example they are deep in a components tree)

**Comment by sachinchoolur** [comment]
lightGallery requires a DOM element for customEvents to work. But you can attach lightGallery to `body` or any other available HTML tags. 

``` js
const dynamicGallery = lightGallery(document.body, {
    dynamic: true,
    dynamicEl: [
        {
            src: 'img/1.jpg',
            thumb: 'img/thumb-1.jpg',
            subHtml: '<h4>Image 1 title</h4><p>Image 1 descriptions.</p>',
        },
        {
            src: 'img/2.jpg',
            thumb: 'img/thumb-2.jpg',
            subHtml: '<h4>Image 2 title</h4><p>Image 2 descriptions.</p>',
        },
        {
            src: 'img/3.jpg',
            thumb: 'img/thumb-3.jpg',
            subHtml: '<h4>Image 3 title</h4><p>Image 3 descriptions.</p>',
        },
    ],
});

dynamicGallery.openGallery();
```

Demo -https://www.lightgalleryjs.com/demos/dynamic-mode/

Once initialized you can modify the items using the `refresh` method
Demo - https://www.lightgalleryjs.com/demos/dynamic-mode/#load-more-slides

Let me know if you face any issues

**Comment by VladStepanov** [comment]
@sachinchoolur Thanks! Didn't find that in docs
