### ISSUE TITLE
lightGallery is not defined in version 2.X

### ISSUE THREAD

**Issue by rickgoemans** [sachinchoolur/lightGallery#1036]
## Description

I've had some issues with version `^1.10.0` not displaying the icons (next, previous, close, fullscreen, zoom, etc.) so I've decided to update to version `2.X` (in my case `2.1.2`). I've noticed that the way it is initialized changed from:
```
$(".lightGallery").lightGallery({
    // options
});
```

To:
```
lightGallery(document.getElementById('lightgallery'), {
    // options
});
```

But when I try to execute it I get the following error:
```Uncaught ReferenceError: lightGallery is not defined```

My 

### Steps to reproduce

I've done this:

`npm i lightgallery --save-dev`

in my javascript file:

```
require('lightgallery/lightgallery.min')

lightGallery(document.getElementsByClassName('lightGallery'), {
   // options
});
```

### Expected result

lightGallery should initialize a gallery viewer.

### Actual result

lightGallery does not initialize a gallery viewer due not being able to find the `lightGallery` function.

### Additional context

Im using `Laravel mix` and  `webpack` to combine the assets to a single minified file and prefer to use `jQuery` but plain js is fine aswell.

**Comment by rickgoemans** [comment]
The issue related to the icons not displaying the icons is solved (by using the sass files and correcting the `$lg-path-fonts` variable, but I still wonder why version `2.X` does not work for me.

**Comment by sachinchoolur** [comment]
Hey @rickgoemans ,

This is happening because somehow `require` is unable to resolve the module. 

Could you please try with 
```
require('lightgallery')
```
0r 
```
require('lightgallery/lightgallery.es5')
```

**Comment by rickgoemans** [comment]
Ok, the error is gone but the lightGallery is still not being used (clicking the image opens the full image). I've changed it now to:

```
import lightGallery from 'lightgallery';
import lgFullscreen from 'lightgallery/plugins/fullscreen';
import lgVideo from 'lightgallery/plugins/video';
import lgThumbnail from 'lightgallery/plugins/thumbnail';
import lgZoom from 'lightgallery/plugins/zoom';

$(function () {
  lightGallery(document.getElementById('lightGallery'), {
    licenseKey: "0000-0000-000-0000",
    mode: 'lg-slide',
    plugins: [
      lgFullscreen,
      lgThumbnail,
      lgVideo,
      lgZoom,
    ],
  });
});
```

And my HTML is:
```
<div class="lightGallery" id="lightGallery">
  <a href="{{ $media->getUrl() }}">
    <img src="{{ $media->getUrl(\App\Support\Enums\MediaConversions::THUMBNAIL) }}" alt="TODO" loading="lazy">
  </a>
</div>
```

Any suggestions?

**Comment by sachinchoolur** [comment]
Nice. Please make sure that `document.getElementById('lightGallery')` is available when you call `lightGallery`

**Comment by rickgoemans** [comment]
I tried that by adding a `console.log('El: ', document.getElementById('lightGallery'))` and that resolves to the correct element. So I don't think that's the point.

**Comment by sachinchoolur** [comment]
Ok. Could you please share the whole code? or a minimal demo? It is very difficult to debug without seeing the actual code

**Comment by sachinchoolur** [comment]
Also, please make sure that the CSS files are properly loaded. 
Once initialized, if you are able to see `.lg-container` in the DOM, this could be the CSS issue

**Comment by rickgoemans** [comment]
I've got it fixed, my problem was that I was using a class selected before switching to version 2.X and started using the id selector. But since I had multiple lightGallery id's on the page it would initialize. I've changed it to:
```
document.querySelectorAll('.lightGallery').forEach((lightGalleryElement) => {
  lightGallery(lightGalleryElement, {
    // options
  }
});
```
It is now all fixed, thanks for the support and consider this issue resolved.
