### ISSUE TITLE
lg-zoom image shifting

### ISSUE THREAD

**Issue by TheUnsleepingAlchemist** [sachinchoolur/lightGallery#1038]
## Description

The image is shifted under certain circumstances

### Steps to reproduce

1. Open any image from [demo](https://codepen.io/sachinchoolur/pen/poebzpV)
2. Zoom in that image
3. Move a little bit
4. Use the button to change the image without zoom out
5. Zoom in again

### Expected result

The image should be placed in the middle of the screen

### Actual result

The image is placed on the right side of the screen

### Additional context

After step 5, image gets `data-x="NaN"` and `data-y="NaN"` for some reason

**Comment by sachinchoolur** [comment]
Hey @TheUnsleepingAlchemist ,

Thank you for pointing this out. I can confirm this is a bug. Hopefully, I'll be able to push a fix buytomorrow

**Comment by sachinchoolur** [comment]
Hey @TheUnsleepingAlchemist ,
The issue has been fixed https://github.com/sachinchoolur/lightGallery/commit/6fa95ea617920d23b8a99df82857515fec73d503

Please upgrade to version 2.1.3
