### ISSUE TITLE
Icons are not rendered

### ISSUE THREAD

**Issue by aitormendez** [sachinchoolur/lightGallery#1039]
## Description
Icons of buttons (arrows, close, magnifying glass, etc) are not shown.

![Captura de pantalla 2021-06-06 a las 12 31 29](https://user-images.githubusercontent.com/2788577/120921287-48f6fa80-c6c3-11eb-88fe-1a60bac004b6.png)

### Steps to reproduce
JS:

https://github.com/aitormendez/test/blob/main/web/app/themes/sage/resources/scripts/app.js

```javascript
import lightGallery from 'lightgallery';

let galerias = document.getElementsByClassName('lightbox');

for (let i = 0; i < galerias.length; i++) {
  galerias[i].id = 'gal' + i;
  lightGallery(document.getElementById('gal' + i), {
    selector: 'a',
  });
}
```

CSS:
https://github.com/aitormendez/test/blob/main/web/app/themes/sage/resources/styles/app.scss#L7

`@import "~lightgallery/scss/lightgallery-bundle.scss";`

### Test site:
http://test.e451.net/2021/06/06/hello-world/

### Additional context
Sage 10 WordPress starter theme

**Comment by sachinchoolur** [comment]
Hey @aitormendez ,

Looks like the fonts and images are not fetching from the correct path. 
For now, try configuring font and image path in scss variable
```scss
$lg-path-fonts: 'https://cdn.jsdelivr.net/npm/lightgallery@2.1.2/fonts';
$lg-path-images: 'https://cdn.jsdelivr.net/npm/lightgallery@2.1.2/images';
```
in https://github.com/aitormendez/test/blob/main/web/app/themes/sage/resources/styles/app.scss#L7

```scss
@import 'tailwindcss/base';
@import 'common/global';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';

$lg-path-fonts: 'https://cdn.jsdelivr.net/npm/lightgallery@2.1.2/fonts';
$lg-path-images: 'https://cdn.jsdelivr.net/npm/lightgallery@2.1.2/images';

@import "~lightgallery/scss/lightgallery-bundle.scss";
```

I'll investigate and get back you

**Comment by sachinchoolur** [comment]
@aitormendez ,

Based on the [discussion](https://github.com/sass/sass/issues/1015), it looks like either you need to copy the lightGallery fonts and images folder to your project or use any plugins like https://github.com/bholloway/resolve-url-loader when you import scss from `node_modules`

Please re-open if you think this needs to be managed from the library itself

**Comment by aitormendez** [comment]
I'm not sure what the cause is, so I'll keep the issue closed. Just in case:

Sage 10 has Laravel mix, wich includes reosolve-url-loader.

https://github.com/JeffreyWay/laravel-mix/blob/master/package.json#L136

**Comment by sachinchoolur** [comment]
Maybe it's worth checking with the sage team as well
