### ISSUE TITLE
Place caption directly below image?

### ISSUE THREAD

**Issue by jengalas** [sachinchoolur/lightGallery#1041]
Is there a way I can place the caption directly below the image rather than in the bottom bar? I have images of different heights and I would like to offset the caption relative to the bottom of each image, rather than have it relative to the bottom of the viewport.

**Comment by sachinchoolur** [comment]
Hey @jengalas,

At present, this is not possible. The problem with this approach is, you need to wait until the image is fully loaded to display the captions. Otherwise, you won't get the image dimensions. 

I'll try to create a plugin and share it in few days

**Comment by jengalas** [comment]
Thank you! A plugin would be great. 

The only workaround I could come up with for the existing setup would be to use media queries and adjust the padding based on viewport height, which is obviously only approximate and not very elegant.
