### ISSUE TITLE
Inline gallery : restrict key bindings to container

### ISSUE THREAD

**Issue by saqimtiaz** [sachinchoolur/lightGallery#1042]
When there is an inline gallery on a page, the event listeners for the arrow keys for navigation capture the keys no matter where in the document the event is fired. This is problematic if you have a `textarea` on the same page as an inline gallery for example. 

Could we add an option for a DOM node to which the event listeners for the navigation keys should be attached? Alternatively an option which when `true`, attaches the event listeners for inline galleries to the container element passed via the container option.

**Comment by sachinchoolur** [comment]
Hey @saqimtiaz ,

Thank you for reporting this issue. But, attaching the event listeners to the container element won't work if the element is not focused. 

So I think the best solution would be skipping the navigation if the input or text area element has focus.

What do you think?

**Comment by saqimtiaz** [comment]
From a UX perspective I can think of several scenarios where it makes sense that an inline gallery should only respond to events fired when it has focus:

- a textarea, input or contenteditable div has focus.
- there are multiple inline galleries on the same page.
- there are other features on the same page that want to use the same keys to trigger their own events.

So I think having an option to attach event listeners to the container element is needed. 

Also, try to skip navigation depending on which element has focus is likely to be error prone. For example, there are HTML/WYSIWYG editors that might be included on a page and need the arrow keys not to be trapped but they do no use textareas on input elements or even contenteditable. See for example the CodeMirror/ProseMirror libraries.
