### ISSUE TITLE
Srcset segments will be converted to html attributes

### ISSUE THREAD

**Issue by amkdev** [sachinchoolur/lightGallery#1043]
I have a normal a-tag including an image:
`<a href="img/1-375.jpg" class="image" data-srcset="img/1-375.jpg 375w, img/1-480.jpg 480w, img/1-757.jpg 757w" data-lg-id="b4bb6ad8-67f3-41e7-b6d6-0934f8fab841">
<img src="img/1-375.jpg" class="w-full rounded">
</a>`

in the lightGallery I get
`<picture class="lg-img-wrap">
<img srcset="img/1-375.jpg" 375w,="" img="" 1-480.jpg="" 480w,="" 1-757.jpg="" 757w="" class="lg-object lg-image" data-index="1" src="img/1-375.jpg">
</picture>`

Looks like the slashes causing problems. 

Any ideas? 

Similar errors happen with data-responsive or data-sources.

Im using lightGallery 2.1.3 and working with a laravel mix enviroment (twig, scss, webpack)

**Comment by sachinchoolur** [comment]
Thanks for pointing this out. I can reproduce this with `data-srcset`. But not with `data-responsive` and `data-sources.`
Can you please confirm?

Pushing a fix in few mins for `data-scset`

**Comment by amkdev** [comment]
wow - thanks for the lightning-fast response

using the data-responsive and data-sources attributes results in a different wrong attribute generation. maybe a side effect?

**Comment by sachinchoolur** [comment]
Data-responsive does not create new attributes in lightGallery. It just picks up the correct image based on the viewport 
Could you please share the generated HTML markup?

**Comment by sachinchoolur** [comment]
Just published version 2.2.4 with the fix.

**Comment by amkdev** [comment]
Ah ok - seems you are right - I was wrong with responsvie and sources

Ok - here my real world html :)

**item's html**
`
<div class="item mb-8 filter drop-shadow-t1">
<a href="/imager/photos/india-2014/01-New%20Delhi/India%202014%20-%20New%20Delhi%20001_12b33ae7038fb1576bfc5405faf4c2f5.jpg" class="image" data-sources="[{&quot;srcset&quot;: &quot;/imager/photos/india-2014/01-New%20Delhi/India%202014%20-%20New%20Delhi%20001_c0bf55fd39d66696731f8e213bbf4aae.jpg 1600w,/imager/photos/india-2014/01-New%20Delhi/India%202014%20-%20New%20Delhi%20001_f20b974524d3fa816598f84679a6a0b7.jpg 1024w,/imager/photos/india-2014/01-New%20Delhi/India%202014%20-%20New%20Delhi%20001_12b33ae7038fb1576bfc5405faf4c2f5.jpg 768w,/imager/photos/india-2014/01-New%20Delhi/India%202014%20-%20New%20Delhi%20001_b87209e2d3a29fc59864b4fb2d0bd1e0.jpg 380w&quot;}]" data-lg-id="2c4589a5-50fb-4e10-acf0-6f28ebe0f4f4">
<img src="/imager/photos/india-2014/01-New Delhi/India 2014 - New Delhi 001_b87209e2d3a29fc59864b4fb2d0bd1e0.jpg" class="w-full rounded">
</a>
</div`

**lightGallery:**
data-srcset
`<picture class="lg-img-wrap"> <img srcset="/imager/photos/india-2014/01-New%20Delhi/India%202014%20-%20New%20Delhi%20001_c0bf55fd39d66696731f8e213bbf4aae.jpg" 1600w,="" imager="" photos="" india-2014="" 01-new%20delhi="" india%202014%20-%20new%20delhi%20001_f20b974524d3fa816598f84679a6a0b7.jpg="" 1024w,="" india%202014%20-%20new%20delhi%20001_12b33ae7038fb1576bfc5405faf4c2f5.jpg="" 768w,="" india%202014%20-%20new%20delhi%20001_b87209e2d3a29fc59864b4fb2d0bd1e0.jpg="" 380w="" class="lg-object lg-image" data-index="1" src="/imager/photos/india-2014/01-New%20Delhi/India%202014%20-%20New%20Delhi%20001_12b33ae7038fb1576bfc5405faf4c2f5.jpg"></picture>`

data-responsive:
`<picture class="lg-img-wrap"> <img class="lg-object lg-image" data-index="1" src="/imager/photos/india-2014/01-New%20Delhi/India%202014%20-%20New%20Delhi%20001_c0bf55fd39d66696731f8e213bbf4aae.jpg"></picture>`

data-sources
`<picture class="lg-img-wrap"> <source srcset="/imager/photos/india-2014/01-New%20Delhi/India%202014%20-%20New%20Delhi%20001_c0bf55fd39d66696731f8e213bbf4aae.jpg 1600w,/imager/photos/india-2014/01-New%20Delhi/India%202014%20-%20New%20Delhi%20001_f20b974524d3fa816598f84679a6a0b7.jpg 1024w,/imager/photos/india-2014/01-New%20Delhi/India%202014%20-%20New%20Delhi%20001_12b33ae7038fb1576bfc5405faf4c2f5.jpg 768w,/imager/photos/india-2014/01-New%20Delhi/India%202014%20-%20New%20Delhi%20001_b87209e2d3a29fc59864b4fb2d0bd1e0.jpg 380w"><img class="lg-object lg-image" data-index="1" src="/imager/photos/india-2014/01-New%20Delhi/India%202014%20-%20New%20Delhi%20001_12b33ae7038fb1576bfc5405faf4c2f5.jpg"></picture>`

**Comment by sachinchoolur** [comment]
Looks good to me. 👍🏻

**Comment by amkdev** [comment]
now the src attribute gets the srcset

`<picture class="lg-img-wrap" style="transform: translate3d(0px, 0px, 0px);" data-x="0" data-y="0"> <img class="lg-object lg-image" data-index="1" src="/imager/photos/india-2014/01-New%20Delhi/India%202014%20-%20New%20Delhi%20001_c0bf55fd39d66696731f8e213bbf4aae.jpg 1600w,/imager/photos/india-2014/01-New%20Delhi/India%202014%20-%20New%20Delhi%20001_f20b974524d3fa816598f84679a6a0b7.jpg 1024w,/imager/photos/india-2014/01-New%20Delhi/India%202014%20-%20New%20Delhi%20001_12b33ae7038fb1576bfc5405faf4c2f5.jpg 768w,/imager/photos/india-2014/01-New%20Delhi/India%202014%20-%20New%20Delhi%20001_b87209e2d3a29fc59864b4fb2d0bd1e0.jpg 380w" data-scale="1" style="transform: scale3d(1, 1, 1);"></picture>`

**Comment by amkdev** [comment]
sorry my fault
