### ISSUE TITLE
Vertical position of the prev/next controls "incorrect" - not centered

### ISSUE THREAD

**Issue by amkdev** [sachinchoolur/lightGallery#1045]
I know - this could be probably fixed by some additional css by myself but ... ;) 

if thumbnails are activated and `allowMediaOverlap:false`, the prev/next controls are not vertically centered to the picture area. This looks not so nicely.

_Currently, I will try to expand the size of the prev/next controls area to the full height of the screen (and 15% width left/right) for easier use. forcing the user to click on small prev/next to come to the next picture is not the best usability imho (even if there are other possibilities to navigate like swipe and so on)._

**Comment by amkdev** [comment]
I figured out that it simply should possible to move the buttons into `.lg-inner` ... looks like no negative side effects happen.

**Comment by sachinchoolur** [comment]
Fixed in - https://github.com/sachinchoolur/lightGallery/releases/tag/2.2.0-beta.3
Sorry for the delay
