### ISSUE TITLE
Angular: lightGallery not working

### ISSUE THREAD

**Issue by dassmilytier** [sachinchoolur/lightGallery#1050]
Sry to bother you again. I have problems to figure out how to get lightgallery with angular 12 working.
I followed the steps in the docs and incorporated some of the issue fixed found on github

HTML:
`
<lightgallery [settings]="settings" [onInit]="galleryOnInit" id="animated-thumbnails">
      <a *ngFor="let image of (images | async); let i = index; trackBy: trackByFn" [attr.href]="image.downloadURL"
         class="gallery-item">
        <img *ngIf="!!image.thumbs && image.thumbs['256']" [attr.src]="image.thumbs['256']?.url"
             class="img-responsive"/>
      </a>
    </lightgallery>
`

TS:
`
settings: LightGallerySettings = {
    licenseKey: 'XXX',
    counter: false,
    download: false,
    plugins: [Zoom, Video, Thumbnail],
    animateThumb: true,
    thumbnail: true,
  };
  private lightGallery!: LightGallery;

  galleryOnInit(detail: InitDetail): void {
    this.lightGallery = detail.instance;
  }
`

SCSS:
`
@import '~lightgallery/scss/lightgallery';
@import '~lightgallery/scss/lg-zoom';
@import '~lightgallery/scss/lg-video';
@import '~lightgallery/scss/lg-thumbnail';
`

I exptected that the images would be displayed in a thumbs gallery. Additionally I expected that the Gallery would show up if I select an image.
Unfortunately this does not happen. The images are loaded full screen outside Angular, as if the lightgallery would not be present at all.

As I created a demo project prior, I tried it there and the lightbox is showing as expected. So it does not seem to be a angular related topic nor a bug within lightgallery rather then my stupidity to get it to work,

Anyway I would appreciate If you could have a look what I am missing. Thanks in advance.

**Comment by sachinchoolur** [comment]
Are you getting any errors on the console? Could you please record and share a shoer video?

Also, try to get a very basic demo working with static HTML markup and without any settings.

**Comment by dassmilytier** [comment]
Hi. Just to give you an update:
My problem sem to be raising from the async image retrieval. As soon as the DOM will be manipulated after the gallery is initialized, the gallery component does not hook into the link elements, which totally makes sense.
Howerver, I am not able to refresh the gallery manually, as the gallery element always returns undefined.

Thanks for your reccomendation to use a minimal project, which i did, working up until I found the root cause of the problem: https://github.com/dassmilytier/lightgallery-ng12-compiler-error

In general, wouldn't it be better, if the gallery would observe the template and automatically refresh on dom changes?
Unfortunately i spend quite some time on this component and finally had to drop it in my project to go on.
However, I would like to get it working and understand, where I took the wrong path/had a wrong understanding.

**Comment by sachinchoolur** [comment]
Hey @dassmilytier,
I'm sorry to hear that.

lightGallery does not refresh the slides automatically - https://www.lightgalleryjs.com/docs/angular/#updating-slides
Maybe I need to improve the documentation 

> Howerver, I am not able to refresh the gallery manually, as the gallery element always returns undefined.

This is more of a JavaScript problem. this context was bound to the lightGallery element, not to the `AppComponent` 
You can use arrow functions to get the correct context. 

```js
galleryOnInit = (detail: InitDetail): void => {
    this.lightGallery = detail.instance;
};
```

Here is the demo - https://stackblitz.com/edit/lightgallery-angular-update-slides

I've also downloaded and fixed the problems in your repo. 

Here are the changes 
- app.component.html
```html
<lightgallery [settings]="settings" [onInit]="galleryOnInit">
    <a *ngFor="let image of images  | async"  [attr.href]="image.downloadURL">
        <img src="{{ image.downloadURL }}" />
      </a>
</lightgallery>

```
- app.component.ts
```ts
import { AfterViewInit, Component, ViewChild, ViewEncapsulation } from '@angular/core';
import Zoom from "lightgallery/plugins/zoom";
import Video from "lightgallery/plugins/video";
import { InitDetail } from "lightgallery/lg-events";
import { LightGallery } from "lightgallery/lightgallery";
import { LightGallerySettings } from "lightgallery/lg-settings";
import Thumbnail from "lightgallery/plugins/thumbnail";
import { BehaviorSubject } from "rxjs";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class AppComponent implements AfterViewInit {
  title = 'lightgallery-ng12-compiler-error';

  settings: LightGallerySettings = {
    counter: false,
    download: false,
    plugins: [Zoom, Video, Thumbnail],
    animateThumb: true,
    thumbnail: false
  };
  images = new BehaviorSubject<{ downloadURL: string }[]>([]);
  @ViewChild('lightgallery')
  lightGallery!: LightGallery;
  private needRefresh = false;
  delay = async (ms: number) => new Promise(res => setTimeout(res, ms));

  async ngAfterViewInit(): Promise<void> {

    await this.delay(2000);
    this.images.next(
      [
        {
          downloadURL: '/assets/images/Bild1.png',
        },
        {
          downloadURL: '/assets/images/honda-civic-tourer-11.jpg',
        }
      ]
    );
    this.images.subscribe(async images => {
      this.needRefresh = true;
    })
  }

  ngAfterViewChecked(): void {
    if (this.needRefresh) {
      this.lightGallery.refresh();
      this.needRefresh = false;
    }
  }

  galleryOnInit = (detail: InitDetail): void => {
    this.lightGallery = detail.instance;
  };
}
```
