### ISSUE TITLE
Flash of unstyled content

### ISSUE THREAD

**Issue by robfaas** [sachinchoolur/lightGallery#1051]
When opening the demo, there always is a flash of unstyled content. Is there a way to prevent this from happening?

**Comment by sachinchoolur** [comment]
Ideally, this should not happen. Are you talking about the toolbar icons?
It would be great if you could record and share a short video?

**Comment by robfaas** [comment]
Ofcourse: https://www.anothersite.nl/lightgallery.mp4
At loading and at reloading you can see the FOUC. I have Windows 10, it happens in FireFox, Chrome and Edge. Also on iPad with Safari browser.

**Comment by sachinchoolur** [comment]
Thanks for the video. Actually, that is not part of the lightGallery. 
It is a separate javascript library called Justified-Gallery which I'm using on the demo website. https://miromannino.github.io/Justified-Gallery/

You can take a look at the demo if you want to implement justified gallery with lightgallery - https://codepen.io/sachinchoolur/pen/poebzpV

Please let me know if you have any questions

**Comment by robfaas** [comment]
Ah! So only the lightbox part of the demo is the lightGallery. I was under the impression that also the justified thumbs were part of the lightGallery script. 
The codepen gives nu FOUC, so it must be something else on the demo website that causes the FOUC.

**Comment by sachinchoolur** [comment]
Yes. Closing the issue as it is not an actual lightGallery problem.

I'll try to improve the demo website. I think it can be fixed by adding `opacity:0` to the thumbnails and removing it once the justifiedGallery rendering is completed
