### ISSUE TITLE
Sourcemap not found - lg-zoom.es5.js.map

### ISSUE THREAD

**Issue by amkdev** [sachinchoolur/lightGallery#1054]
Sorry if this is my fault ...

I'm using webpack / laravel mix and I got always a 404 about the missing lg-zoom.es5.js.map 

`DevTools failed to load SourceMap: Could not load content for http://amk2021photo.local:3000/js/photo/lg-zoom.es5.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

it's only one I got from lightGallery. 

I import the zoom plugin just like the others. 

I'm using laravel mix / webpack. 

Any idea?

**Comment by amkdev** [comment]
That was probably a webpack problem ... I had to explicitly disable the generation of sourcemaps in production mode. still strange. Sorry.

**Comment by sachinchoolur** [comment]
Yes, it doesn't look like a lightGallery problem. 
Closing the issue. Please re-open if required
