### ISSUE TITLE
Dynamic mode for angular component

### ISSUE THREAD

**Issue by definitely-unique-username** [sachinchoolur/lightGallery#1058]
## Summary
Please provide dynamic mode for angular component

### Basic example
https://www.lightgalleryjs.com/demos/dynamic-mode/

### Motivation
Consistent API for js frameworks

**Comment by sachinchoolur** [comment]
Hey @definitely-unique-username,

Dynamic mode is already available with angular version.
Just created a stackblitz demo for you https://stackblitz.com/edit/lightgallery-angular-dynamic-mode?file=src%2Fapp%2Fapp.component.ts

Please  let me know if you have any questions

**Comment by definitely-unique-username** [comment]
Hi @sachinchoolur,

That's cool! Could you update the docs? It's not obvious that angular component has this feature.

**Comment by sachinchoolur** [comment]
Sure, I'll add a demo and update documentaion
