### ISSUE TITLE
Angular component not possible to change settings after init

### ISSUE THREAD

**Issue by definitely-unique-username** [sachinchoolur/lightGallery#1059]
## Description

It's not possible to change settings after component init

### Steps to reproduce
1. Create component
2.  Try to change settings

### Expected result
Component changes according to new settings

### Actual result
Nothing changes

### Additional context

Angular component has pretty poor architecture. It's an antipattern in angular world to pass callback as input, use outputs instead. Also you can use ngOnChanges hook to track input changes

```
  ngAfterViewChecked(): void {  // <= consider to use AfterViewInit hook
        if (!this.lgInitialized) {
            this.registerEvents();
            this.LG = lightGallery(
                this._elementRef.nativeElement as HTMLElement,
                this.settings,
            );
            this.lgInitialized = true;
        }
    }
```

**Comment by vinricardo** [comment]
### Possible alternative
You can try removing the logic that is inside the hook and adding a simple console.log(), to check if the function is being called, if so, we will need more code to help you, because it will be related to your code in you!

**Comment by definitely-unique-username** [comment]
Code sample is from your codebase not mine

**Comment by sachinchoolur** [comment]
Hey @definitely-unique-username ,

Please let me know your use case. I'll try to find a solution

**Comment by definitely-unique-username** [comment]
Hey @sachinchoolur,

My use case is to use one lightGallery component and has possibility to change settings at any time

**Comment by sachinchoolur** [comment]
Ok, Currenlty, it is not possible to change the settings when gallery is opened.  
Otherwise, it is possible with a minor tweak. Please let know if this is sufficiant, I'll try to provide a demo today itself
