### ISSUE TITLE
Wrong button gets disabled on first and last images in gallery (Previous instead of Next)

### ISSUE THREAD

**Issue by dbrabyn** [sachinchoolur/lightGallery#1060]
## Description

The Next button on the first image in the slideshow is getting the 'disabled' class and attribute. And the Previous button on the last image is getting the 'disabled' class and attribute.

![CleanShot 2021-06-25 at 15 07 38@2x](https://user-images.githubusercontent.com/6307031/123474051-6a168100-d5c7-11eb-9e54-2fa051601427.jpg)

### Steps to reproduce

Basic instance with loop: false and lgHash plugin

### Expected result

The Previous button on the first image should be disabled, not the Next button. And vice versa on the last image.

**Comment by sachinchoolur** [comment]
Hey @dbrabyn,

It works fine for me. Which version of lightGallery are you using? 
Could you please share the JavaScript code that you are using to initialize lightGallery?

**Comment by dbrabyn** [comment]
v 2.1.5

Here is a screen grab as the code format ticks are messing with the ticks in the code (possibly not the most precise terms ;))

![CleanShot 2021-06-26 at 18 00 37](https://user-images.githubusercontent.com/6307031/123526880-bb4a7180-d6a8-11eb-89cc-d98c8a0c3995.jpg)

**Comment by sachinchoolur** [comment]
Thanks. I'm able to reproduce the issue now. I'll push a fix by tomorrow.
If required, please remove `hideControlOnEnd: true` for now

**Comment by sachinchoolur** [comment]
Hey @dbrabyn,
Just released version 2.1.6 with the fix.

**Comment by dbrabyn** [comment]
Thanks.

Possible css issue: I think the opacity: .5 of .disabled (line 47) is getting overridden by the opacity: 1 of .lg-show-in .lg-next, .lg-show-in .lg-pager-outer, .lg-show-in .lg-prev, .lg-show-in .lg-toolbar (line 364)

**Comment by sachinchoolur** [comment]
Thank you for reporting this. I'll update you once it is fixed

**Comment by sachinchoolur** [comment]
Fixed in version 2.1.7
