### ISSUE TITLE
Evenly zoom - advanced zoom of portrait/landscape images on landscape/portrait screens

### ISSUE THREAD

**Issue by amkdev** [sachinchoolur/lightGallery#1061]
I'm using for my image exports from lightroom always a 1:1 pixel ratio for max dimensions so that a portrait image will be for instance 2400 in height and a landscape image 2400 in width max.

So my portrait images in lightGallery appearing very "huge" in zoomed view, while landscape images followes (of course) the dekstop screen itself and appearing only a little zoomed (e.g. 1920x1080 vs 1300x2400 vs 2400x1300).

How could this be optimized?

I have the idea that lighGallery could check the width and height dimension and if he recognized a portrait image, it switches the height and width internally for the zoom calculation. In this way portrait images would be zoomed less ... if I'm not wrong.

The same behavior would be useful on mobile, where the screen is in portrait mode and images appear "bigger" in landscape mode.

**Comment by sachinchoolur** [comment]
Thanks for the suggestions.

**Comment by amkdev** [comment]
A scale value per image via a data attribute would be interesting. Since I use Twig and have the dimensions of all images in the template, I could implement some logical things, I think. :)
