### ISSUE TITLE
Video element is not rendered

### ISSUE THREAD

**Issue by definitely-unique-username** [sachinchoolur/lightGallery#1062]
## Description

Video element is not rendered when used dynamic mode with angular component.

### Steps to reproduce

Use lg with video items in dynamic mode.

### Expected result

It should render video element.

### Actual result

Video not rendered.

### Additional context

[example](https://stackblitz.com/edit/lightgallery-angular-dynamic-mode-gwec9u?file=src%2Fapp%2Fapp.component.ts)

**Comment by sachinchoolur** [comment]
Hey, 

Here is the demo - https://stackblitz.com/edit/lightgallery-angular-dynamic-mode-video-slides?file=src/app/app.component.ts

You need to include [video plugin](https://www.lightgalleryjs.com/docs/settings/#video-plugin) - I think I forgot to mention it on the demo page. 

``` js
import lgVideo from 'lightgallery/plugins/video';

settings = {
    counter: false,
    dynamic: true,
    dynamicEl: this.items,
    plugins: [lgZoom, lgThumbnail, lgVideo]
};
```

```css
@import url('https://cdn.jsdelivr.net/npm/lightgallery@2.0.0-beta.4/css/lg-video.css');
```


Please let me know if you face any issues
