### ISSUE TITLE
hideControlOnEnd option seems not to work

### ISSUE THREAD

**Issue by amkdev** [sachinchoolur/lightGallery#1065]
Left right buttons won't be hidden on gallery's very start and end.

**Comment by sachinchoolur** [comment]
Fixed in version 2.1.7

**Comment by amkdev** [comment]
maybe I'm doing something wrong, but neither that the buttons are disabled nor that they disappear. loop is false and hideControlOnEnd is true. strange. :(

**Comment by sachinchoolur** [comment]
You need to disable slideEndAnimation too - https://www.lightgalleryjs.com/docs/settings/#slideEndAnimation

Sorry for the confusion, I'll update the docs

**Comment by amkdev** [comment]
Of course, you have to know that ... ;) Thanks!
