### ISSUE TITLE
lack of draggablity in zoomed view / portion of the image not reachable (after zoom in by double click)

### ISSUE THREAD

**Issue by amkdev** [sachinchoolur/lightGallery#1067]
if an image in zoomed view is equal or smaller to viewport in height or width it's not possibly to drag it in that direction. a nice function if you in only zoom in to the centered origin of the image, so the image's width or height is fully visible.

But lightGallery offers to create a dedicatied zoom origin via double click. This stands in contradiction with the limitation of above mentioned draggablity.

In this way the user sometimes can’t reach all parts of the image. he can only move up and down or left or right. Big parts of the image could stay outside the viewport and can’t be moved in. the user have to zoom out and zoom in again.

On double click/double tap this limitation of draggablity should be removed. 

this is a usability bug. would be nice to see a fix soon.

**Comment by amkdev** [comment]
double clicking on the very left/right on a image here in codepen (were the height of the viewport is reduced) is a good example. the images are only dragable up and down ... 

https://codepen.io/sachinchoolur/pen/wvJgLKM

**Comment by sachinchoolur** [comment]
Thank you for reporting this issue
FIxed in https://github.com/sachinchoolur/lightGallery/commit/67e56e392565c1cd43b7bf5c5f616dd9b5af29c0
It Will be available in the next version
