### ISSUE TITLE
License warning even after adding key.

### ISSUE THREAD

**Issue by theopaolo** [sachinchoolur/lightGallery#1068]
## Description
Even after adding inside the configs of the script the license key I bought a couple of weeks ago I'm still getting a warning inside the console telling me that: lightGallery: 0000-0000-000-0000 license key is not valid for production use.

### Steps to reproduce
Sorry but that mean sharing my license key.... 

lightGallery(lg, {
            plugins: [lgZoom, lgThumbnail, lgFullscreen],
            licenseKey : "my license",
            speed: 50,
            exThumbImage: 'data-external-thumb-image',
            download : false,
            fullScreen : true
});

### Expected result

No more warning

### Actual result

Keep getting warning

### Additional context

I'm also using barba.js and loading the lg script inside a hook... maybe there's something that don't play well there.

**Comment by sachinchoolur** [comment]
Hope the issue is resovled

**Comment by BregtDeLange** [comment]
How was this solved? How can the licensekey be private for production?

**Comment by gusmoe** [comment]
Hello, I am having the same problem.  Valid license key added into init call.

Console reporting the following regardless of whether I put a valid license key or no key, or any key.

`lightGallery: 0000-0000-000-0000 license key is not valid for production use`

Thanks

**Comment by sachinchoolur** [comment]
Hey @gusmoe,

Currently, you need to pass the license key wherever you call lightGallery. I'll add an option to set it only once in the next major release.

Please check the call stack using dev tools and make sure the license key is properly passed via settings 

Hey @BregtDeLange, license key is not private, even if someone gets the license key, they won't get your information about you

**Comment by gusmoe** [comment]
Hi, thanks for the reply.

The only call I have is in the initialization function of *lightGallery.*

Example license key below.

const $dynamicGallery = document.getElementById('dynamic-gallery-demo');
const dynamicGallery = lightGallery($dynamicGallery, {
    licenceKey: '12345_example',
    dynamic: true,
    dynamicEl: [

It seems to be behaving like it hasn't loaded the licenseKey correctly
from the code location below.

[image: image.png]


If I replace the default here with the license key (or any key for
that matter), the error in the console seems to go away.


[image: image.png]


Any thoughts?  Is it validating the license key at all?

**Comment by sachinchoolur** [comment]
Oops! it is `licenseKey` not `licenceKey`. 

https://www.lightgalleryjs.com/docs/getting-started/#initialize-lightgallery

**Comment by gusmoe** [comment]
Haha wow, apologies I am Australian/US we spell differently and actually thought I'd searched for both.  Thanks, sorry about that.

Still curious though if I put ANY key the warning disappears.
