### ISSUE TITLE
More slide transition possibilites: Slide blends instead of slide left/right animation

### ISSUE THREAD

**Issue by amkdev** [sachinchoolur/lightGallery#1075]
Would be really nice to have the possibility that images won't slide in and out but simply fade from one to another. 

It can be a bit exhausting to look at many pictures if there is always an animation in between.

**Comment by sachinchoolur** [comment]
Fade transition is already available 
Demo - https://www.lightgalleryjs.com/demos/transitions/

```js

lightGallery(document.getElementById('container'), {
    mode: 'lg-fade',
});

```

**Comment by amkdev** [comment]
Sorry ... Thanks for the hint.

_*RTFM, Alex!*_ ;)
