### ISSUE TITLE
I hava a problem in using lightGallery for Vue2

### ISSUE THREAD

**Issue by ElanYoung** [sachinchoolur/lightGallery#1077]
Now I have a paging component. When I click the next page, I click the picture, and the lightGallery on the previous page is not closed

version:"lightgallery": "^2.1.5"

Code snippet:

[![R6VdNn.png](https://z3.ax1x.com/2021/07/02/R6VdNn.png)](https://imgtu.com/i/R6VdNn)

**Comment by ElanYoung** [comment]
in vue2 and lightgallery's version is 2.1.5

how to sovle this problem

**Comment by ElanYoung** [comment]
handlePreview method is not require

I forgot to delete it

**Comment by sachinchoolur** [comment]
Hey @ElanYoung ,

Could you please answer the following questions?

- When you go to the next page, is the previous page still visible?
- Are you navigate to the next page when lightGallery is in the open state?

Would you be able to record a short video of the issue and share it?

Also, could you please try calling the `refresh()` method when the new set of photos are fetched

Vue 3 demo - https://stackblitz.com/edit/lightgallery-vue-update-slides (line number 32)

**Comment by ElanYoung** [comment]
> Hey @ElanYoung ,
> 
> Could you please answer the following questions?
> 
> * When you go to the next page, is the previous page still visible?
> * Are you navigate to the next page when lightGallery is in the open state?
> 
> Would you be able to record a short video of the issue and share it?
> 
> Also, could you please try calling the `refresh()` method when the new set of photos are fetched
> 
> Vue 3 demo - https://stackblitz.com/edit/lightgallery-vue-update-slides (line number 32)

i will try it, thank you !
