### ISSUE TITLE
Thumbnails Navigation not working

### ISSUE THREAD

**Issue by luckyadirake** [sachinchoolur/lightGallery#1078]
I cant get thumbnails navigation to work. I am opening the gallery in dynamic mode with json file

`   var dynamicGallery = lightGallery($dynamicGalleryToggle, {
                            dynamic: true,
                            plugins: [lgThumbnail, lgHash],
                            addClass: 'header-grid-gallery-modal',
                            enableThumbDrag: true,
                            enableThumbSwipe:true,
                            dynamicEl: galleryList,
                            mobileSettings:{
                                controls:true,
                                showCloseIcon:true,
                                download: false,
                            } 
                        });`

There is no console error

I have already included plugins files in my js bundle

**Comment by sachinchoolur** [comment]
This could be some issues with `dynamicEl` format.
Could you please share the `galleryList ` sample json?

**Comment by luckyadirake** [comment]
I think i found the issue, i was using jquery Element to pass through $dynamicGalleryToggle and it wasn't properly utlizing all the other plugins as well..

So my workaround is to use vanilla js selector

Thanks alot you can close this

**Comment by sachinchoolur** [comment]
Thanks for the update.
