### ISSUE TITLE
Shop online 

### ISSUE THREAD

**Issue by Eman32star** [sachinchoolur/lightGallery#1079]
Hello,

Most of the examples I have found load images related to the initial thumbnails shown on the page. I would like to load a set of images related only to the thumbnail clicked. For example I have 3 cats, one brown, black and white. When the user clicks on the white cat, I don't want to see a gallery of the 3 cats shown initially. I would like to load let's say 6 images related to the white cat.

Hope that made sense.

TIA

_Originally posted by @swstyles in https://github.com/sachinchoolur/lightGallery/discussions/1071_

**Comment by Eman32star** [comment]
Shop online store

**Comment by Eman32star** [comment]
[https://boutiqueeqet.com/index.php?route=common/home](https://boutiqueeqet.com/index.php?route=common/home) 
![Uploading 320C3EF3-766D-4C3C-99CD-E40F707AC36C.jpeg…]()

**Comment by sachinchoolur** [comment]
hey @Eman32star,

If you are looking for an example, you can take a look at the link mentioned in https://github.com/sachinchoolur/lightGallery/discussions/1074

Please let me know if you need any help from my side
