### ISSUE TITLE
ACF Gallery + lightGallery | data-src is not provided on slide | Image not showing inside modal

### ISSUE THREAD

**Issue by a-blomberg** [sachinchoolur/lightGallery#1084]
## Description
I'm using Advanced Customs Fields Pro to create a gallery on our site which is using Bootstrap 5 and using lightGallery as the modal solution. Everything is working to output the thumbnails and when you click on them the modal is activated, the data-sub-html is displaying BUT the image is not showing in the main modal window. The errors i'm seeing in the console are: 

> lightgallery.ts:995 lightGallery :- data-src is not provided on slide item 1. Please make sure the selector property is properly configured. More info - http://sachinchoolur.github.io/lightGallery/demos/html-markup.html

Here is my code in my template file:

```
<div class="gallery-container d-flex align-items-center justify-content-center" id="gallery-container">
	<?php $gallery_images = get_sub_field( 'gallery' ); ?>	
	<?php if ( $gallery_images ) :  ?>		
		<?php foreach ( $gallery_images as $gallery_image ): ?>
			<div class="col-6 col-sm-4 col-md-3 mb-3">
				<a data-lg-size="1200-1200" class="gallery-item" data-src="<?php echo esc_url( $gallery_image['sizes']['medium'] ); ?>" data-sub-html="<?php echo esc_attr( $gallery_image['alt'] ); ?>">
					<img class="img-fluid img-thumbnail" src="<?php echo esc_url( $gallery_image['sizes']['medium'] ); ?>" alt="<?php echo esc_attr( $gallery_image['alt'] ); ?>" />
				</a>
			</div>
		<?php endforeach; ?>
	<?php endif; ?>
</div>
```

I'm not sure why the images would display as the thumbnails but the same code snippet won't display inside the modal window? Any ideas are greatly appreciated; thanks!

**Comment by sachinchoolur** [comment]
Hey @a-blomberg,

Try setting `.gallery-item` as the selector - https://www.lightgalleryjs.com/demos/html-markup/

```js
lightGallery(document.getElementById('gallery-container'), {
    selector: '.gallery-container',
});
```
Please let me know if you face any issues

**Comment by a-blomberg** [comment]
Thanks so much for your help! After some tinkering this was the solution that worked:

**TEMPLATE CODE**
```
<div class="gallery-container d-flex align-items-center justify-content-center" id="gallery-container">
	<?php $gallery_images = get_sub_field( 'gallery' ); ?>		
	<?php if ( $gallery_images ) :  ?>		
		<?php foreach ( $gallery_images as $gallery_image ): ?>
			<div class="col-6 col-sm-4 col-md-3 mb-3">
				<a data-lg-size="1200-1200" class="gallery-item" data-src="<?php echo esc_url( $gallery_image['sizes']['large'] ); ?>" data-sub-html="<?php echo esc_attr( $gallery_image['alt'] ); ?>">
					<img class="img-fluid img-thumbnail" src="<?php echo esc_url( $gallery_image['sizes']['medium'] ); ?>" alt="<?php echo esc_attr( $gallery_image['alt'] ); ?>" />
				</a>
			</div>
		<?php endforeach; ?>
	<?php endif; ?>
</div>
```

**JAVASCRIPT**
```
<script>
	lightGallery(document.getElementById('gallery-container'), {
		selector: '.gallery-item',
	});
</script>
```

thanks for the help!!
