### ISSUE TITLE
Ionic/Angular app - not working

### ISSUE THREAD

**Issue by Mihaildimitrov** [sachinchoolur/lightGallery#1088]
Hi all,

I have Ionic/Angular app (latest version)
![Screenshot 2021-07-11 at 15 07 12](https://user-images.githubusercontent.com/16749450/125194396-d648e400-e259-11eb-969e-a2b5dd6dd4f5.png)
![Screenshot 2021-07-11 at 15 08 50](https://user-images.githubusercontent.com/16749450/125194433-ee206800-e259-11eb-88c7-b7161d425eda.png)

and I got an error when import  { LightgalleryModule } from 'lightgallery/angular';

see attached screenshtos

please help me with that  :)

**Comment by sachinchoolur** [comment]
Hey, 

Could you please try with the latest version of lightGallery?

**Comment by Mihaildimitrov** [comment]
hey @sachinchoolur  same with 2.1.8 :|

**Comment by sachinchoolur** [comment]
Oh, could you please try with version 2.2.0-beta.0 as well?
Sorry for the confusion.

**Comment by Mihaildimitrov** [comment]
yes give me 2 min

**Comment by Mihaildimitrov** [comment]
@sachinchoolur  I don't know how to thank you :)
It's working now I just tested with Angular example from the docs.

you are the best!

THANK YOU !!!
