### ISSUE TITLE
lgShare - google Lighthouse  

### ISSUE THREAD

**Issue by Rar9** [sachinchoolur/lightGallery#1089]
How to fix these google lighthouse issues when using the lgShare?

Add `rel="noopener"` or `rel="noreferrer"` to any external links to improve performance and prevent security vulnerabilities. Learn more.

Links to cross-origin destinations are unsafe

Warnings:
Unable to determine the destination for anchor (<a id="lg-download-1" target="_blank" aria-label="Download" download="" class="lg-download lg-icon">). If not used as a hyperlink, consider removing target=_blank.
Unable to determine the destination for anchor (<a class="lg-share-facebook" target="_blank">). If not used as a hyperlink, consider removing target=_blank.
Unable to determine the destination for anchor (<a class="lg-share-twitter" target="_blank">). If not used as a hyperlink, consider removing target=_blank.
Unable to determine the destination for anchor (<a class="lg-share-pinterest" target="_blank">). If not used as a hyperlink, consider removing target=_blank.

as well as

Uncrawlable Links
--
Download<a id="lg-download-1" target="_blank" aria-label="Download" download="" class="lg-download lg-icon">
Facebook<a class="lg-share-facebook" target="_blank">
Twitter<a class="lg-share-twitter" target="_blank">
Pinterest<a class="lg-share-pinterest" target="_blank">

**Comment by sachinchoolur** [comment]
Hey @Rar9,

`rel="noopener"` has been added to all share links. This will be available in the next release.

Sorry for the delay

**Comment by Rar9** [comment]
> Hey @Rar9,
> 
> `rel="noopener"` has been added to all share links. This will be available in the next release.
> 
> Sorry for the delay 

Any time frame for next version? 
Where do find change?

**Comment by sachinchoolur** [comment]
It is available in version [2.2.0-beta.5](https://github.com/sachinchoolur/lightGallery/releases/tag/2.2.0-beta.5)

**Comment by Rar9** [comment]
Updated, to beta 5 but still not liked by lighthouse. 

What am I doing wrong for drupal? 

https://www.asset-trade.de/en/universal-machine-centres/hermle-c50-u-mt-5-axis-machine-centre-millturn-123-06081640

**Comment by Rar9** [comment]
![Lighthouse download](https://user-images.githubusercontent.com/2239608/129928852-c0746378-d9dc-46c5-b2d8-b1d60cc4ff4c.png)

looks like LG Download is still not 100%

**Comment by sachinchoolur** [comment]
Thanks for reporting this.

Links with target="_blank"  implies rel=noopener by default. I'll update it in the next version

**Comment by Rar9** [comment]
Please update this in your next version as well to fix all lighthouse issues

**Comment by z0lo13** [comment]
> next issue links are now not Crawable when i try current beta 5 :-( ![link are not crawable](https://user-images.githubusercontent.com/2239608/131187609-469bacc3-f71a-48ec-8dce-2db17914c79d.png)

@Rar9 
has this been fixed?

**Comment by Rar9** [comment]
I believe so, but have not checked lately on Google lighthouse, as im fighting performance issues currently.

**Comment by z0lo13** [comment]
@Rar9 it was not. I will open a new issue.
