### ISSUE TITLE
Safari Video Controls not working

### ISSUE THREAD

**Issue by niklasp** [sachinchoolur/lightGallery#1097]
## Description

In safari 14.1 on MAC OS Catalina the video controls are not working. When trying to click the controls instead of selecting the video position / dragging the video seek control, the slide is dragged. In Firefox and chrome it is working.

**Comment by sachinchoolur** [comment]
Thank you for reporting this issue. Just released version [`2.2.0-beta.2`](https://github.com/sachinchoolur/lightGallery/releases/tag/2.2.0-beta.2) with the fix.

This update disables the dragging capability on HTML videos like all other supported video types.
