### ISSUE TITLE
can't close lightgallery on mobile

### ISSUE THREAD

**Issue by imkoma** [sachinchoolur/lightGallery#1098]
lightgallery can't be closed on mobile devices - the close button is not visible and clicking on the background does nothing. Esc key works but is not an option on mobile devices.

Tested with Google Chrome / Windows and Google Chrome / Android

https://www.lightgalleryjs.com/demos/thumbnails/
![chrome-dev-tools-moto-g4](https://user-images.githubusercontent.com/7037573/126871308-070d81cc-9c58-422c-908c-0ed21173334f.jpg)

**Comment by sachinchoolur** [comment]
The close button is disabled on mobile devices. Users can swipe down to close the gallery.
If you want, you can enable it by updating the `mobileSettings` 
Docs - https://www.lightgalleryjs.com/docs/settings/#mobileSettings

```js
lightGallery(document.getElementById('gallery'),{
  mobileSettings: { 
    controls: false, 
    showCloseIcon: true,
    download: false, 
  }
})
```

**Comment by imkoma** [comment]
ok thanks, i missed the mobileSettings
