### ISSUE TITLE
Support for custom links

### ISSUE THREAD

**Issue by HybridSolutions** [sachinchoolur/lightGallery#110]
Hi,

Suppose I show a caption over my image on hover event with two links, beeing one of the links for showing the image. How can I do this since lightGallery automatically creates the links for me?

With Facebox this would be easy as this:
```
<a class="zoom-icon fancybox" title="My title" rel="gallery" href="myfullimage.jpg">Zoom in image</a>
```
Your examples don't cover such an example so I don't know if this is even possible.

Thank you!

**Comment by sachinchoolur** [comment]
HI, Your question is not perfectly clear to me. 
Do you want to use same markup like `<a class="zoom-icon fancybox" title="My title" rel="gallery" href="myfullimage.jpg">Zoom in image</a>`.  It would be helpful if you could provide an example for your markup

Thanks.

**Comment by HybridSolutions** [comment]
Hi,

sorry for not being clear enough. If you take a look at fancybox usage, you'll see that you can with one call to the script, instantiate infinite galleries. The trick is on the rel keyword that specifies to which gallery the image will be attached to. Also, you can have the gallery item as an a tag but that I've seen that I can do with the selector option :). How would you do to instantiate multiple galleries on a page?

**Comment by sachinchoolur** [comment]
Hi,
You can initiate multiple galleries with single call
ex:
``` html
<ul id="light-gallery">
  <li data-src="img/img1.jpg">
    <img src="img/thumb1.jpg" />
  </li>
  <li data-src="img/img2.jpg">
    <img src="img/thumb2.jpg" />
  </li>
</ul>
<ul id="light-gallery">
  <li data-src="img/img3.jpg">
    <img src="img/thumb3.jpg" />
  </li>
  <li data-src="img/img4.jpg">
    <img src="img/thumb4.jpg" />
  </li>
</ul>
```
``` javascript
$('.light-gallery').lightGallery();
```
> how can I update the gallery with that filtering info ?

After filter you can just destroy the gallery and re-initiate it.
ex:
``` javascript
var gallery =  $('.light-gallery').lightGallery();
// after filter
gallery.destroy();
gallery =  $('.light-gallery').lightGallery();
```

**Comment by HybridSolutions** [comment]
Multiple galleries is not working when using custom selector. Also, tried to use the destroy method, but when i try to open the filtered image, i get the black overlay with nothing else. I tried to use without custom selector as well with the same result. 

Here's the code i'm using:

```
<ul class="lightGallery2 row isotope-grid">
      <li data-src="demo_photos/photo1.jpg" class="isotope-item 2012 col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <img src="demo_photos/photo1.jpg" class="img-responsive" alt="">
      </li>
      <li data-src="demo_photos/photo2.jpg" class="isotope-item 2013 col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <img src="demo_photos/photo2.jpg" alt="" class="img-responsive">
      </li>
    </ul>
```

In the filtering function, i'm calling this:

```
$container.isotope({ filter: filterValue });         
            $container.isotope('updateSortData').isotope();
            
            gallery.destroy();
            gallery = $(".lightGallery2").lightGallery({        
                //selector:'.hotlink'
            });
```

i tested that the gallery variable was not null and that it returned the gallery object.

Can you please test this out, because i really like your plugin but I need it to work with Isotope :(

Thank you, once again!

**Comment by sachinchoolur** [comment]
Hi,
Could you please provide a jsfiddle demo for your setup.. I will try to fix from my side..

**Comment by HybridSolutions** [comment]
Hi, you can download a working example from here. This example has two galleries, both with isotope applied. As you will see, LightGallery is not opening the images and is also ignoring the filtered items even after a destroy.

http://gofile.me/2B2vF/Huz1qzfK

**Comment by HybridSolutions** [comment]
Hi!
did, you manage to check my demo?

**Comment by sachinchoolur** [comment]
Hi,
I am really sorry. I missed your message completely..
The link is inactive now. could you do it once again?

**Comment by HybridSolutions** [comment]
Sure,

here it is: http://gofile.me/2B2vF/LzG55jRs

**Comment by sachinchoolur** [comment]
Hi,
Gallery works fine. The problem is when you filter images isotope is just hiding the images they are not removing images from the dom.

So you can just select only visible item as selector.
``` javascript 
var gallery =  $(".gallery").lightGallery({        
    selector:'.hotlink:visible',
    exThumbImage: 'data-exthumbimage'
}); 

// After filtering 

gallery.destroy();                                    
gallery = $(".gallery").lightGallery({                        
    selector:'.hotlink:visible',
    exThumbImage: 'data-exthumbimage'
});

Please let me know if you need the updated files..

**Comment by HybridSolutions** [comment]
Hello,

That worked great! The issue I mentioned about multiple galleries using a class as a selector is the one mentioned here https://github.com/sachinchoolur/lightGallery/issues/103

This doesn't happen when you use unique id's instead of common css classes for the gallery container. For now, what do you suggest to be able to still use a common css class for all the galleries?

Thank you :)

**Comment by akumarmail99** [comment]
Hi,
I really need your help. i want to use LightGallery with Isotope and its working properly without filter but when i am using filter lightgallery is not implementing filter, its showing all images but i want only filtered images. According to given comments  above it should work......May i doing mistake please correct it my js code is given bellow.


$(document).ready(function(){
	
	
	$(window).load(function(){
		var $container = $('.portfolioContainer');
		$container.isotope({
			filter: '*'
			
	});	
		
	var gallery = $('#lightgallery').lightGallery({
		selector:'.hotlink:visible',
		exThumbImage: 'data-exthumbimage'
	});
	
	$('.portfolioFilter1').on('change',function(){      
 
        var selectorss = this.value;
        $container.isotope({
            filter: selectorss
         });
         return false;
    }); 
	
		gallery.destroy();                                    
		gallery = $("#lightgallery").lightGallery({                        
		selector:'.hotlink:visible',
		exThumbImage: 'data-exthumbimage'
	});

	});

});
