### ISSUE TITLE
Data attribute for download URL not working as documented

### ISSUE THREAD

**Issue by raoulb** [sachinchoolur/lightGallery#1105]
Setting `data-download-url` on an individual `div` element to any URL does work and sets the download link as expected.

However, trying to disable/hide the download button for some images via `data-download-url="false"` does not work but instead sets an URL like `example.org/false`.

The [documentation](https://www.lightgalleryjs.com/docs/attributes/#data-download-url%0a) tells me that this should work:

> Pass false if you want to hide the download button.

and would indeed be very useful for me.

I'm using the released version 2.1.8 of lightGallery.

**Comment by sachinchoolur** [comment]
The issue has been fixed in version 2.2.0-beta.4. Download button will be disabled if `data-download-url="false"`. Hiding the download button might cause flickering effect while navigating to another slide.

**Comment by raoulb** [comment]
Works as expected now. Thanks.
