### ISSUE TITLE
Documentation of lgContainerResize event seems to be off

### ISSUE THREAD

**Issue by raoulb** [sachinchoolur/lightGallery#1106]
The [documentation of the lgContainerResize](https://www.lightgalleryjs.com/docs/events/#lgContainerResize
) event seems to be wrong and does not really make sense for me.
But I noticed that the text is a literal copy of the [documentation for lgAfterAppendSubHtml](https://www.lightgalleryjs.com/docs/events/#lgAfterAppendSubHtml) which is odd.

**Comment by sachinchoolur** [comment]
Done. Thank you for reporting this.
