### ISSUE TITLE
Option to disable top menu bar

### ISSUE THREAD

**Issue by raoulb** [sachinchoolur/lightGallery#1108]
Have a configuration option to disable/hide the "top menu bar" instantaneously and permanently.
I could not find a combination of [showBarsAfter](https://www.lightgalleryjs.com/docs/settings/#showBarsAfter) and [hideBarsDelay](https://www.lightgalleryjs.com/docs/settings/#hideBarsDelay) which does this.
Additionally, if [allowMediaOverlap](https://www.lightgalleryjs.com/docs/settings/#allowMediaOverlap) is `false`, it would be nice to extend the image all the way to the top boundary.

If this is already possible, I could not figure out how. In that case an example in the documentation would be great.

**Comment by sachinchoolur** [comment]
Currently, It is not possible to disable the top menu bar with the settings. 

But as mentioned in https://github.com/sachinchoolur/lightGallery/issues/1107, you can easily update it via CSS

Let me know if you need a demo
