### ISSUE TITLE
Event on gallery maximization

### ISSUE THREAD

**Issue by raoulb** [sachinchoolur/lightGallery#1109]
Have an event to hook into the maximization/minimization of an inline/full gallery.

There is the method [toggleMaximize](https://www.lightgalleryjs.com/docs/methods/#toggleMaximize) available for plug-ins but I *think* I have no way to react to this toggle without writing a custom plugin.

In the larger picture, one important use case would be to be able to reconfigure the gallery on this toggle. (If that is even possible from within such an event.) For example, an inline gallery usually has `hash: false` but when maximized, a setting of `hash: true` might be more appropriate.

**Comment by raoulb** [comment]
> But, it is not possible to re-configure a few settings such as `hash`.

Ok, hmm, meh :-/

> In my opinion, using hash plugin with inline gallery does not make much sense as the gallery could be anywhere on the page.

Well, yes. Not for a gallery in minimized/inline "mode". But once a user hits the maximize button, the gallery will become 
maximized/full-window sized. And in that state *I think* the `hash` stuff would make perfect sense. That is the reason why I would like to turn the `hash` functionality/plugin on/off if a gallery is maximized/minimized.

The issue might be that loading such an URL with slide parameters does not reopen the gallery in maximized mode :-/
If this is your point, then probably your are right ...

**Comment by sachinchoolur** [comment]
Yes, that is my point. The main purpose of the hash plugin is to provide an option to open a specific gallery and slide based on URL params.
