### ISSUE TITLE
Customization for download attribute

### ISSUE THREAD

**Issue by raoulb** [sachinchoolur/lightGallery#1110]
Provide an option (preferably via a `data-` attribute) to configure the [download](https://github.com/sachinchoolur/lightGallery/blob/master/src/lightgallery.ts#L393) attribute of the `a` tag.

The MDN documentation states: ["Defining a value suggests it as the filename"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download). This would for example be useful in combination with static site generators like `Hugo` which generate highly technical filenames for images going through their processing pipeline.

**Comment by sachinchoolur** [comment]
Hey @raoulb ,

You can provide the download URL via `data-download-url` attribute 
Docs - https://www.lightgalleryjs.com/docs/attributes/#data-download-url%0a


I'll address all other issues you reported by tomorrow.

**Comment by raoulb** [comment]
Hi @sachinchoolur ,

Thanks for the reply. I don't think this is exactly what I meant. Please let me explain a bit more.

Imagine the following situation: I have a slide in the gallery showing an image loaded from `https://example.org/aengeiw8.png`.
If I want to provide a huge high-res version for download, I'd set the `data-download-url` to for example `https://example.org/aengeiw8_highres.png`. Assume further I have no control over the exact URLs and especially the ugly file names.

Now, if a user clicks that download button, the browser will (depending on preferences and some restrictions of course) save the file as `aengeiw8_highres.png` somewhere on the users machine.

The [download](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download) attribute (of the `a` tag) would allow me to provide a proposal for the browser which file name it could use locally. This in a way independent of the source URL (which as mentioned I have no control over). I could for example take part of the image caption or whatever sensible text I may have around.

The lightgallery code [already has](https://github.com/sachinchoolur/lightGallery/blob/master/src/lightgallery.ts#L393) the `download` attribute, but without a value assigned. The original feature request proposes an easy way to optionally assign a custom value to this attribute. (Easy means here without adding my own custom js or jquery etc.)


> I'll address all other issues you reported by tomorrow. Sorry for the delay

Great, thanks. Take your time.

BTW: It would be awesome if this (given that you decide to implement it) and #1105 made it into the upcoming 2.2 release. But if it is too late for that now as you already have a beta-3 out I can totally understand, too.

**Comment by sachinchoolur** [comment]
Thanks for the detailed explanation. Yes, this is definitely a missing feature. 

Value for download attribute is now included in version 2.2.0-beta.4 
https://www.lightgalleryjs.com/docs/attributes/#data-download%0a

**Comment by RohanNegiUI** [comment]
Hi @sachinchoolur ,

Could you expose a public method that will call a callback function at the click of the download button?
<img width="53" alt="image" src="https://user-images.githubusercontent.com/90025980/186375189-525f2633-6221-495f-bab7-ce298a6e3d8b.png">
