### ISSUE TITLE
Picture tag

### ISSUE THREAD

**Issue by MarkHTML** [sachinchoolur/lightGallery#1112]
Following your codepen examples it appears that the picture tag codepen is a duplicate of srcset codepen.

For example no picture tag is found in the picture tag demo https://codepen.io/sachinchoolur/pen/wvJWBOM

**Comment by sachinchoolur** [comment]
Picture tag is automatically created in lightGallery based on the input 
Docs - https://www.lightgalleryjs.com/demos/responsive/

**Comment by MarkHTML** [comment]
Thank you for explaining that, really appreciate this awesome plugin!
