### ISSUE TITLE
Suggestions for accessibility improvement

### ISSUE THREAD

**Issue by nastradalus** [sachinchoolur/lightGallery#1115]
Hello! Lightgallery is a really good library but it is available with the keyboard with a few exceptions. We’d like to add these features to Lightgallery to make it more accessible:

1) Add auto focus on modal window content after opening it. In the current version, you need to tab to page bottom to get to modal window content.

2) Add focus lock to the page part covered by modal window when it is open. In the current Lightgallery version you can tab key to follow the links outside the modal window. These links are invisible to user, so there is no point in interacting with them http://joxi.ru/5mdbbveiaqzYNA

3) Containers with preview images should be buttons or should use role and tabindex attributes http://joxi.ru/p27qqbVsnLzpDr. They should be focusable as these are interactive elements.

4) Add aria attributes to images preview containers for better recognition by screen readers. In the current version of Lightgallery, all main buttons have aria attributes except for the preview images containers http://joxi.ru/5mdbbveiaqznNA.

**Comment by sachinchoolur** [comment]
Hey @nastradalus,

Thank you for the suggestions. 1 and 2 are regressions. 
I'll try to push a fix soon

**Comment by carasmo** [comment]
Yes, 1 and 2 are necessary. I am having to revert back to FancyBox to get this project done. On another note, re buttons in the toolbar in another comment today, I used CSS to accomplish.

**Comment by ericstroo** [comment]
Bumping this. Keyboard experience should follow: 
https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html

**Comment by sachinchoolur** [comment]
Sorry for the late response. This has been fixed in the version [2.5.0-beta.3](https://github.com/sachinchoolur/lightGallery/releases/tag/2.5.0-beta.3)

Thank you for being so patient

**Comment by sachinchoolur** [comment]
You can use the option [trapFocus](https://www.lightgalleryjs.com/docs/settings/#trapFocus) the behaviour
