### ISSUE TITLE
Preview images not appearing

### ISSUE THREAD

**Issue by HybridSolutions** [sachinchoolur/lightGallery#112]
When you use the Selector option, thumbnails path are set to undefined. Full images are opened correctly by the plugin, but the thumbnails don't get loaded. Don't worry about the isotope stuff :)

![capture](https://cloud.githubusercontent.com/assets/8672899/7009977/1f85a26e-dc96-11e4-8b55-1e0f2b8513ff.JPG)

```
<ul id="lightGallery" class="gallery isotope-grid">
        <li class="isotope-item"> 
        	<figure>
            	<img src="../demo_photos/photo1.jpg" alt="">
        		<figcaption>
          			<div class="caption-content text-center">                    	
                        <a href="#" class="hotlink" data-src="../demo_photos/photo1.jpg"><i class="fa fa-pencil fa-2x"></i></a>
                    </div>          			
      		</figure>
        </li>
        <li class="isotope-item"> 
        	<figure>
            	<img src="../demo_photos/photo1.jpg" alt="">
        		<figcaption>
          			<div class="caption-content text-center">                    	
                        <a href="#" class="hotlink" data-src="../demo_photos/photo1.jpg"><i class="fa fa-pencil fa-2x"></i></a>
                    </div>          			
      		</figure>
        </li>
        <li class="isotope-item"> 
        	<figure>
            	<img src="../demo_photos/photo2.jpg" alt="">
        		<figcaption>
          			<div class="caption-content text-center">                    	
                        <a href="#" class="hotlink" data-src="../demo_photos/photo2.jpg"><i class="fa fa-pencil"></i></a>
                    </div>          			
      		</figure> 
        </li>
        <li class="isotope-item"> 
        	<figure>
            	<img src="../demo_photos/photo3.jpg" alt="">
        		<figcaption>
          			<div class="caption-content text-center">                    	
                        <a href="#" class="hotlink" data-src="../demo_photos/photo3.jpg"><i class="fa fa-pencil fa-2x"></i></a>
                    </div>          			
      		</figure> 
        </li>
    </ul>	
        
    <script>	
$(document).ready(function(){
    
    $("#lightGallery").lightGallery({        
        selector:'.hotlink'
    });

});
</script>
```

**Comment by sachinchoolur** [comment]
Hi,
You can use `exThumbImage` setting

Name  | Expected | Default | Description
------------ | -------------|------------ | -------------
exThumbImage | string or false | false | If you want to use external image for thumbnail, add the path of that image inside "data-" attribute and set value of this option to the name of your custom attribute.

Ex:
``` html
<ul id="lightGallery" class="gallery isotope-grid">
        <li class="isotope-item"> 
            <figure>
                <img src="../demo_photos/photo1.jpg" alt="">
                <figcaption>
                    <div class="caption-content text-center">                       
                        <a data-exthumbimage="externalThumb.jpg" href="#" class="hotlink" data-src="../demo_photos/photo1.jpg"><i class="fa fa-pencil fa-2x"></i></a>
                    </div>                      
            </figure>
        </li>
</ul>
```
``` javascript
$("#lightGallery").lightGallery({        
    selector:'.hotlink',
    exThumbImage: 'data-exthumbimage'
});

**Comment by HybridSolutions** [comment]
ok, but why don't you use the data-src instead? Having to repeat the same path on the same element doesn't make much sence. Don't you get the thumbnail from the data-src when a custom selector isn't being used?

**Comment by dubaksk** [comment]
@HybridSolutions I was dealing with the same problem when using custom selector and agree with you. It's repeating data attribute. But this seems to be the only workaround so far.

**Comment by sachinchoolur** [comment]
Hi,
All the thumbnails will be created while opening the gallery. If we use data-src (full size image ) as thumbnail we need to load all the big size images at a time. lightGallery uses lazy loading to improve performance. so if we load all the big size images together there is no point of setting lazy load feature.
And re-sizing big images into small size doesn't give you good user experience also.
So i believe providing separate images for thumbnails is the good practice..
