### ISSUE TITLE
Git tag for 2.2.0-beta.4 on wrong commit

### ISSUE THREAD

**Issue by raoulb** [sachinchoolur/lightGallery#1120]
The git tag `2.2.0-beta.4` currently is placed on the commit [9e02e5ace41ddac92e79c403ab84c8e359298979](https://github.com/sachinchoolur/lightGallery/commit/9e02e5ace41ddac92e79c403ab84c8e359298979) but I *think* it should be on the following one, [9b2e316de12a11d094e0a3fce3fa2fff95805f61](https://github.com/sachinchoolur/lightGallery/commit/9b2e316de12a11d094e0a3fce3fa2fff95805f61) which updates the files in `dist/*`.

This leads to a wrong [prerelease](https://github.com/sachinchoolur/lightGallery/releases/tag/2.2.0-beta.4) zip file where the `package.json` still says:
```
  "name": "lightgallery",
  "version": "2.2.0-beta.3",
```

At least the `beta.2` and `beta.3` tags were placed on the commits called "build: ...". The `beta.1` tag might be one commit to late.

**Comment by sachinchoolur** [comment]
Oh, Thank you for reporting this. 
The issue won't happen if you are using NPM as the files are packaged from the local folder. 
For now, if you are not using npm, please use the files from https://github.com/sachinchoolur/lightGallery/tree/v2.2.0/dist

I think I can not update the release files manually on GitHub.
