### ISSUE TITLE
Videos do not play, thumbnail expands then nothing plays just a blank screen.

### ISSUE THREAD

**Issue by reelfunky** [sachinchoolur/lightGallery#1124]
```
<head>


<link type="text/css" rel="stylesheet" href="js/lightgallery/css/lightgallery.css" />

<!-- lightgallery plugins -->
<link type="text/css" rel="stylesheet" href="js/lightgallery/css/lg-zoom.css" />
<link type="text/css" rel="stylesheet" href="js/lightgallery/css/lg-thumbnail.css" />



<script src="./js/jquery/jquery-3.6.0.min.js"></script>
<script src="./js/foundation/foundation.js"></script>

<script src="js/lightgallery/lightgallery.umd.js"></script>
<script src="js/lightgallery/plugins/video/lg-video.umd.js"></script>
<script src="js/lightgallery/plugins/thumbnail/lg-thumbnail.umd.js"></script>


</head>




<style>
body {
  padding: 40px;
  background-image: linear-gradient(#e8f0ff 0%, white 52.08%);
  color: #0e3481;
  min-height: 100vh;
}

.header .lead {
  max-width: 620px;
}


</style>



<div id="gallery-videos-demo">
    <!-- YouTube Video --->
    <a
        data-lg-size="1280-720"
        data-src="https://www.youtube.com/watch?v=JPX8g8ibKFc"
        data-poster="https://img.youtube.com/vi/JPX8g8ibKFc/maxresdefault.jpg"
        data-sub-html="<h4>Visual Soundscapes - Mountains | Planet Earth II | BBC America</h4><p>On the heels of Planet Earth II’s record-breaking Emmy nominations, BBC America presents stunning visual soundscapes from the series' amazing habitats.</p>"
    >
        <img
            width="300"
            height="100"
            class="img-responsive"
            src="https://img.youtube.com/vi/JPX8g8ibKFc/maxresdefault.jpg"
        />
    </a>

 
</div>


<script>

$(document).foundation();

lightGallery(document.getElementById('gallery-videos-demo'));

</script>
```

**Comment by reelfunky** [comment]
![image](https://user-images.githubusercontent.com/42388897/128949643-798fc086-a72f-4dfb-bdb9-97e004d32e8d.png)

**Comment by sachinchoolur** [comment]
hey @reelfunky,

You need to include `lgVideo` plugin via plugin setting.

```js
lightGallery(document.getElementById('gallery-videos-demo'), {
    plugins: [lgVideo],
});
```
Docs - https://www.lightgalleryjs.com/docs/getting-started/#initialize-lightgallery

On the video page demo, I forgot to include plugins in the sample code. I'll update the docs

**Comment by reelfunky** [comment]
Hi @sachinchoolur 

I have put the lgvideo line into the page but unfortunatley it still does the same thing.

I have purchased a license which i haven't applied yet, does the license need appying for it to work?

I have created a test page, can you please take a look and see where the issue is, ive kept the code very simple to trouble 




<head>


    <link type="text/css" rel="stylesheet" href="js/lightgallery/css/lightgallery.css" />
    
    <link type="text/css" rel="stylesheet" href="js/lightgallery/css/lg-zoom.css" />
    <link type="text/css" rel="stylesheet" href="js/lightgallery/css/lg-thumbnail.css" />

    <script src="./js/jquery/jquery-3.6.0.min.js"></script>
    <script src="./js/foundation/foundation.js"></script>

    <script src="js/lightgallery/lightgallery.umd.js"></script>
    <script src="js/lightgallery/plugins/video/lg-video.umd.js"></script>
    <script src="js/lightgallery/plugins/thumbnail/lg-thumbnail.umd.js"></script>
    <script src="js/lightgallery/plugins/autoplay/lg-autoplay.umd.js"></script>

</head>




<style>
    body {
        padding: 40px;
        background-image: linear-gradient(#e8f0ff 0%, white 52.08%);
        color: #0e3481;
        min-height: 100vh;
    }

    .header .lead {
        max-width: 620px;
    }
</style>


<div id="gallery-videos-demo">
    
    <a data-lg-size="1280-720" data-src="https://www.youtube.com/watch?v=_d68Kd2C0zM" data-poster="https://img.youtube.com/vi/_d68Kd2C0zM/maxresdefault.jpg" data-sub-html="<h4>Video 1</p>">
        <img width="300" height="100" class="img-responsive" src="https://img.youtube.com/vi/_d68Kd2C0zM/maxresdefault.jpg" />
    </a>
    <a data-lg-size="1280-720" data-src="https://www.youtube.com/watch?v=jVl-g3-6hpQ" data-poster="https://img.youtube.com/vi/jVl-g3-6hpQ/maxresdefault.jpg" data-sub-html="<h4>Video 2</p>">
        <img width="300" height="100" class="img-responsive" src="https://img.youtube.com/vi/jVl-g3-6hpQ/maxresdefault.jpg" />
    </a>
</div>



<script>
    lightGallery(document.getElementById('gallery-videos-demo'), {
        plugins: [lgVideo]
    });
</script>

**Comment by reelfunky** [comment]
Hi @sachinchoolur 

I applued the [lgvideo] line to the script but unfrtunaltey the issue is still there.

I have created a test page where you can see the issue.

Can you take a look please?

[](https://factsandthings.com/test.php)

I have purchased a license but haven't applied it yet , could that be the problem?

**Comment by sachinchoolur** [comment]
No, you don't have to apply license key for this to work.

Looks like you haven't included the video module css

Try including https://factsandthings.com/js/lightgallery/css/lg-video.css and let me know the result

**Comment by reelfunky** [comment]
OK. That has fixed it!
Many thanks for your quick response, it works great, very much appreciated.
