### ISSUE TITLE
Missing freeMove option.

### ISSUE THREAD

**Issue by rahulsingh321** [sachinchoolur/lightGallery#1135]
Hi @sachinchoolur 
Thanks for such great library. 

While working with lightgallery, I realised that there is no option to swipe/slide images with no limit. Just like we have option `freeMove - Enable free move(no limit) while swipe or drag` in jquery lightslider. (http://sachinchoolur.github.io/lightslider/settings.html)

Can we add the same option here too? or its already there if I missed.  It will be really helpful.

Thank you.

**Comment by sachinchoolur** [comment]
Hey @rahulsingh321,

Sorry for the late response. Yes, freeMove is enabled by default in lightGallery. 
There is no specific setting available for `freeMove`. But when `loop` is set to `false`, `freeMove` is automatically enabled
