### ISSUE TITLE
Close icon missing on iPhone

### ISSUE THREAD

**Issue by wiwi-websolutions** [sachinchoolur/lightGallery#1138]
## Description

Describe the issue that you're seeing.
**Close icon missing on iPhone, tested on Safari and Firefox. Test devices:
iPhone 12 Pro Max
iPhone X
Iphone Xs Max**

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to
a demo project if possible, this makes your issue _much_ easier to diagnose
(seriously).
**Create a lighbox and open it on an iPhone, the close icon will be missing.**

### Expected result

What should happen?
**The close icon show be shown, so users can close the lightbox the same as iPad and Desktop.**

### Actual result

What happened.
**The close icons is not shown on iPhone.**

### Additional context
Used code:
```
lightGallery(document.getElementById('lightgallery'), {
    plugins: [lgZoom, lgThumbnail],
    selector: '.lightbox-item',
});
```

Desktop:
![desktop](https://user-images.githubusercontent.com/72225750/130957545-88c993a7-d19a-4885-9473-8cfabae89170.PNG)

iPhone:
![iPhone](https://user-images.githubusercontent.com/72225750/130957573-4d52fbec-6a57-44c9-89d6-7c4422f3118f.jpg)

**Comment by sachinchoolur** [comment]
Hey @wiwi-websolutions,

The close icon is disabled on mobile devices by default as users have the option to swipe down and close the gallery
If you want you can enable to by passing custom settings for mobile devices 

https://www.lightgalleryjs.com/docs/settings/#mobileSettings


```js
lightGallery(document.getElementById('lightgallery'), {
    plugins: [lgZoom, lgThumbnail],
    selector: '.lightbox-item',
    mobileSettings: { 
        controls: false, 
        showCloseIcon: true,
        download: false, 
    }
});

```

**Comment by wiwi-websolutions** [comment]
> 
> 
> Hey @wiwi-websolutions,
> 
> The close icon is disabled on mobile devices by default as users have the option to swipe down and close the gallery
> If you want you can enable to by passing custom settings for mobile devices
> 
> https://www.lightgalleryjs.com/docs/settings/#mobileSettings
> 
> ```js
> lightGallery(document.getElementById('lightgallery'), {
>     plugins: [lgZoom, lgThumbnail],
>     selector: '.lightbox-item',
>     mobileSettings: { 
>         controls: false, 
>         showCloseIcon: true,
>         download: false, 
>     }
> });
> ```

Hi @sachinchoolur ,

Thanks for the quick response, this indeed solves the problem. Must've missed it in the docs :)

Have a great day!
