### ISSUE TITLE
Youtube Autoplay

### ISSUE THREAD

**Issue by barcadictni** [sachinchoolur/lightGallery#1140]
https://github.com/sachinchoolur/lightGallery/blob/3c26be8ad66ee4d33248b1882ddb1f77edda5873/src/plugins/video/lg-video.ts#L222

I am trying to autoplay youtube videos(without the poster image) but I couldn't. I was checking the request and I noticed that the autoplay param is set to 0 by default. Is there any option to verify the autoplay within the youTubePlayerParams settings?

Thank you

**Comment by sachinchoolur** [comment]
Hey @barcadictni,
There was an issue with autoplay when the poster is not provided. This has been resolved now. 
Please use version [2.3.0-beta](https://github.com/sachinchoolur/lightGallery/releases/tag/2.3.0-beta)

Let me know if you face any issues

**Comment by barcadictni** [comment]
All is working as expected, thanks @sachinchoolur
