### ISSUE TITLE
Vimeo URL error when adding vimeoPlayerParams

### ISSUE THREAD

**Issue by barcadictni** [sachinchoolur/lightGallery#1143]
Hi @sachinchoolur,

I think you're missing a '?' before adding the vimeoPlayerParams, Could you take look, please?

https://github.com/sachinchoolur/lightGallery/blob/7f92f26a54b41a3fc1923abb3a445037316708aa/src/plugins/video/lg-video.ts#L216

**Comment by sachinchoolur** [comment]
Thank you for pointing this out. Yes, I can reproduce the issue.
I'll push a fix ASAP

**Comment by sachinchoolur** [comment]
Hey @barcadictni,

Please use version [2.3.0-beta.1](https://github.com/sachinchoolur/lightGallery/releases/tag/2.3.0-beta-1) and let me know if  the issue persists

**Comment by barcadictni** [comment]
Fixed. Thank you
