### ISSUE TITLE
Mixed content Uncaught TypeError

### ISSUE THREAD

**Issue by Ada-Si** [sachinchoolur/lightGallery#1146]
## Description

There is an error in browser console when lgZoom plugin is involved within mixed content gallery e.g. [here](https://www.lightgalleryjs.com/demos/mixed-contents/).

### Steps to reproduce

On the given [page](https://www.lightgalleryjs.com/demos/mixed-contents/) start by clicking on the thumbnail which refers to a video i.e. for example second thumbnail (the one with mountains) and close the gallery by clicking on the modal backdrop then the Error occurs. If you start by clicking on the thumbnail which refers to an image the error doesn't occur.

### Expected result

There shouldn't be such error ;-)

### Actual result

There is an error in browser console:
`Uncaught TypeError: Cannot read properties of undefined (reading 'height')
    at Zoom.getDragAllowedAxises (main.8c76dde68619f36d25683faa67b6d27fea8592b5a7caa58214a90cb04a9a42b7b7b2dab58c873ff0610142aca3c782aa693282d1792b2ba6946a07e104fbfdd2.js:3444)
    at HTMLDivElement.<anonymous> (main.8c76dde68619f36d25683faa67b6d27fea8592b5a7caa58214a90cb04a9a42b7b7b2dab58c873ff0610142aca3c782aa693282d1792b2ba6946a07e104fbfdd2.js:4125)
Zoom.getDragAllowedAxises @ main.8c76dde68619f36d25683faa67b6d27fea8592b5a7caa58214a90cb04a9a42b7b7b2dab58c873ff0610142aca3c782aa693282d1792b2ba6946a07e104fbfdd2.js:3444
(anonymous) @ main.8c76dde68619f36d25683faa67b6d27fea8592b5a7caa58214a90cb04a9a42b7b7b2dab58c873ff0610142aca3c782aa693282d1792b2ba6946a07e104fbfdd2.js:4125`

**Comment by sachinchoolur** [comment]
Thank you for reporting this issue

FIxed in version [2.2.1](https://github.com/sachinchoolur/lightGallery/releases/tag/2.2.1)
