### ISSUE TITLE
Cannot read properties of null (reading 'contains')

### ISSUE THREAD

**Issue by MrTilllus** [sachinchoolur/lightGallery#1150]
The plugin will not let me click on anything on the page or click on the lightbox elements themselves to open them

Uncaught TypeError: Cannot read properties of null (reading 'contains')
    at HTMLDivElement.<anonymous> (lg.js:2116)
(anonymous) @ lg.js:2116

i imported the js files of the dist folder for js

js
`lightGallery(document.getElementById('lightgallery'), {});`

html
`
<div id="lightgallery" class="gallery lightgallery px-0">
			<figure class="gallery-item gallery-item-1" data-src="/images/photo-1516464174449-3fc3cc40525f.jpeg"
				data-sub-html="<span class='fw-light text-dark fs-7'>MW 302605</span><span class='fs-7 text-dark'> - Bildname</span>">
				<img src="/images/photo-1516464174449-3fc3cc40525f.jpeg" alt="image-1"
					class="gallery-image rounded rounded-3">
			</figure>
			<figure class="gallery-item gallery-item-2" data-src="/images/photo-1613934060684-595db1d4c93f.jpeg"
				data-sub-html="<span class='fw-light text-dark fs-7'>MW 302605</span><span class='fs-7 text-dark'> - Bildname</span>">
				<img src="/images/photo-1613934060684-595db1d4c93f.jpeg" alt="image-2"
					class="gallery-image rounded rounded-3">
			</figure>
			<figure class="gallery-item gallery-item-3" data-src="/images/photo-1625447956229-40bad977175c.jpeg"
				data-sub-html="<span class='fw-light text-dark fs-7'>MW 302605</span><span class='fs-7 text-dark'> - Bildname</span>">
				<img src="/images/photo-1625447956229-40bad977175c.jpeg" alt="image-3"
					class="gallery-image rounded rounded-3">
			</figure>
			<figure class="gallery-item gallery-item-4" data-src="/images/photo-1625447956229-40bad977175c.jpeg"
				data-sub-html="<span class='fw-light text-dark fs-7'>MW 302605</span><span class='fs-7 text-dark'> - Bildname</span>">
				<img src="/images/photo-1625447956229-40bad977175c.jpeg" alt="image-4"
					class="gallery-image rounded rounded-3">
			</figure>
			<figure class="gallery-item gallery-item-5" data-src="/images/photo-1523206710245-44d89036b2c0.jpeg"
				data-sub-html="<span class='fw-light text-dark fs-7'>MW 302605</span><span class='fs-7 text-dark'> - Bildname</span>">
				<img src="/images/photo-1523206710245-44d89036b2c0.jpeg" alt="image-5"
					class="gallery-image rounded rounded-3">
			</figure>
		</div>
`

i saw issue #1004 but it did not helped

**Comment by sachinchoolur** [comment]
Looks like an issue with loading CSS files - https://www.lightgalleryjs.com/docs/getting-started/#include-css-and-javascript-files

Please make sure that the CSS files are properly loaded

**Comment by MrTilllus** [comment]
oh yes i thought about again and i was using the scss files of the old lightgallery sorry

**Comment by Chidicrypto** [comment]
I have a similar issue in a chrome extension, when a button is clicked a new window opens, strangely when a button in the new window is clicked an error from a code in the script file is highlighted in the chrome extension developer
document.head.innerHTML += '<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />';
//document.getElementById("total").innerHTML="Loading Items...";

Uncaught TypeError: Cannot read properties of null (reading 'contains')

window.addEventListener('click', function(e){   
  if (document.getElementById('clicker').contains(e.target)){
    window.searched=""
    goto()
  } 
  else{
   window.searched // Clicked outside the box
  }

even when I navigate to github, this error piles up in chrome developer with github as the window url
