### ISSUE TITLE
lightGallery :- data-src is not provided

### ISSUE THREAD

**Issue by Pixelous** [sachinchoolur/lightGallery#1157]
Hi,

**lightGallery :- data-src is not provided on slide item 1. Please make sure the selector property is properly configured. More info - https://www.lightgalleryjs.com/demos/html-markup/**

But what id I do not want to use src attribute on my markup just srcset only?

Can you please fix it?

**Comment by sachinchoolur** [comment]
Hey @Pixelous,

Are you saying that you are not using `src` as fallback image?

Could you please share your HTML markup? I'll take a look at get back to you

**Comment by Pixelous** [comment]
@sachinchoolur I am sorry, I have set up 

`selector: '.item'`

This helped.

Yes I do not using `src` as fallback image, looks all modern browsers support this.

By the way can you replace loading spinner and font icons with svg?

**Comment by sachinchoolur** [comment]
Related to https://github.com/sachinchoolur/lightGallery/issues/1162
