### ISSUE TITLE
backgroundColor and margin depend on Medium zoom plugin

### ISSUE THREAD

**Issue by Pixelous** [sachinchoolur/lightGallery#1158]
Hi,

I noticed `backgroundColor` and `margin` options depend on Medium zoom plugin.

What if I want to change overlay background color, margin but do not want to use Medium zoom plugin?)

Can you please fix it?

Also can you please rename Medium zoom to something else unbranded? Maybe Animated zoom plugin?

**Comment by sachinchoolur** [comment]
Hey, 

lightGallery core plugin does not have inbuilt options to change the background color and margin. But you can take a look at the medium-zoom plugin to see how it can be implemented. 

https://github.com/sachinchoolur/lightGallery/blob/master/src/plugins/mediumZoom/lg-medium-zoom.ts

it is a very minimal plugin created as per the request of one of our users. Mostly for the demonstration purpose. 

I'm closing the issue. Let me know if you any assistance from my side
