### ISSUE TITLE
Content loaded dynamically into iframes gets cropped

### ISSUE THREAD

**Issue by usuario17** [sachinchoolur/lightGallery#116]
Hello,
I am trying to configure a dynamic gallery, but when I load iframe content dynamically, it gets cut off. They are html files I reference locally with flash components inside.

The height should be automatic (at least on a window big enough) so there is no cutting off. If the content is too long or wide, and the screen size is not big enough, I understand that there would be a scroll bar.

Can you please show me how to do this properly? -- Thank you very much, excellent product!

Below is my code format:

<div id="gal1">Proyecto 1</div>

<script type="text/javascript">
 $(document).ready(function() {

    $('#gal1’).click(function(e){
        $(this).lightGallery({

            counter: true,
            showThumbByDefault: false,
            thumbnail: false,
            closable: false,
            loop: true,
            addClass: 'miClase',

            dynamic:true,
            html:true,
            mobileSrc:true,
            dynamicEl:[
                {"src”:”img1.png"},
                {"iframe":"true","src":"../contenido/doc1.html"},
                {"src":"img7.jpg"},
                {"iframe":"true","src":"../contenido/doc2.html"},
                {"iframe":"true","src":"../contenido/doc3.html"},
            ]
        }); 
    }) 

  });
</script>

![issue](https://cloud.githubusercontent.com/assets/12100883/7321705/1168476a-eaa4-11e4-8a42-6a164154043f.png)
![code all](https://cloud.githubusercontent.com/assets/12100883/7321749/57aac7ac-eaa4-11e4-9d12-38fa954ab89e.png)

**Comment by sachinchoolur** [comment]
Hi,
It would be helpful if you could provide a jsfiddle demo or a screenshot of your gallery to get a better idea.

*If your issue is with responsive videos...* 
LightGallery has no control over the content inside iframe. You are responsible for that.
Here is a good article about how to create responsive videos. https://css-tricks.com/NetMag/FluidWidthVideo/Article-FluidWidthVideo.php

**Comment by usuario17** [comment]
Hello Sachin,
Not a problem at all! I have uploaded a test area:
Proyecto 2 is the gallery with iframes and flash
http://aivweb.es/v/demo/

Changing the padding below got me the extra space I needed, but it seems to make all iframe windows the same size (I now have extra white space), as opposed to resizing based on content. I can live with this, but I would like to know if I set up the dynamic gallery correctly for iframes that contain HTML docs with flash files as content.

#lg-slider .video {
    padding-bottom: 76%;
    /*padding-bottom: 56.25%;*/
}

Thank you very much!

**Comment by usuario17** [comment]
Just for clarification:  
I would like to know if I set up the dynamic gallery correctly for IMAGES AND for IFRAMES that contain HTML docs with flash files as content.
Within the same gallery, I may have a mix of plain images and iframes.
Thanks again!

**Comment by sachinchoolur** [comment]
Hi,
Yes. What you are doing is correct.
Actually lightGallery is meant for image video galleries. I just added iframe support as an addon.
When iframe is true whatever url you pass inside `src` will be added into video container.
If you are not using videos you can change `padding-bottom` It does not effect anywhere else.
You can change it according to your flash iframe proportion.
But i recommend you to add a new class into lightGallery and change the padding-bottom
So it won't effect another if you use multiple galleries with videos 
``` javascript

$('#gal2').click(function(e){
    $(this).lightGallery({
        addClass:'has-flash-cont'
    }); 
}); 
```
``` css
.has-flash-cont #lg-slider .video {
    padding-bottom: 76%;
    /*padding-bottom: 56.25%;*/
}
```
