### ISSUE TITLE
Warning about license key

### ISSUE THREAD

**Issue by andrei-lus** [sachinchoolur/lightGallery#1161]
Hey there! I was trying to check out and test the plugin. I entered the 0000-0000-000-0000 license key, but I got the following console warning:
`lightGallery: 0000-0000-000-0000 license key is not valid for production use`

I'm not using it for production, I just wanted to look how it works. I use the lightgallery.umd.js file, not .min.js

I copied everything from github and moved some files. The head part is:
`<link type="text/css" rel="stylesheet" href="lightGallery/css/lightgallery.css" />
        <link type="text/css" rel="stylesheet" href="lightGallery/css/lg-zoom.css" />
        <link type="text/css" rel="stylesheet" href="lightGallery/css/lg-thumbnail.css" />
        <script src="lightGallery/lightgallery.umd.js"></script>
        <script src="lightGallery/plugins/lg-thumbnail.min.js"></script>
        <script src="lightGallery/plugins/lg-zoom.min.js"></script>
    	<script src="https://cdn.jsdelivr.net/npm/less@4.1.1"></script>
        <script type="text/javascript">
            window.onload = function () {
                lightGallery(document.getElementById('lightgallery'), {
                    plugins: [lgZoom, lgThumbnail],
                    speed: 500,
                    licenseKey: '0000-0000-000-0000'
    	        });
            }
        </script>`

File paths are correct, I'm completly sure.

`<div id="lightgallery">
        		<a href="assets/img1.jpg">
        			<img src="assets/img1.jpg" />
        		</a>
        		<a href="assets/img2.jpg">
        			<img src="assets/img2.jpg" />
        		</a>
                <a href="assets/img3.jpg">
        			<img src="assets/img3.jpg" />
        		</a>
        		<a href="assets/img4.jpg">
        			<img src="assets/img4.jpg" />
        		</a>
                <a href="assets/img5.jpg">
        			<img src="assets/img5.jpg" />
        		</a>
        	</div>`

Sorry for not using PasteBin here

**Comment by sachinchoolur** [comment]
Hey @andrei-lus,

You can safely ignore this warning for non-production use. 
Once you purchase a license you'll receive the license key via email.
If you pass it via settings the warning will disappear

**Comment by andrei-lus** [comment]
Thank you for the fast answer. It didn't work at all. Through some time it started. I don't know what kind of error it was but... now it works
