### ISSUE TITLE
supportLegacyBrowser

### ISSUE THREAD

**Issue by Pixelous** [sachinchoolur/lightGallery#1164]
Hi,

Can you please drop **supportLegacyBrowser** to make the plugin less heavy please?

**Comment by sachinchoolur** [comment]
At the moment, this is used only for adding support to `srcset` attribute via picturefill library
If true lightGallery will show a warning message to include picturefill library. that's it.

Removing `supportLegacyBrowser` option will not reduce the size of the plugin much. 
It will be removed in the next major version when we drop IE 11 support.
