### ISSUE TITLE
No close and download button on mobile devices

### ISSUE THREAD

**Issue by MaksTrader** [sachinchoolur/lightGallery#1168]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to
a demo project if possible, this makes your issue _much_ easier to diagnose
(seriously).

### Expected result

What should happen?

### Actual result

What happened.

**Comment by MaksTrader** [comment]
Hi. Please help. The close and download button is missing on mobile devices.
I add
![Screenshot_1](https://user-images.githubusercontent.com/47728504/134790431-0f18a2a6-94d6-42e0-be3c-573843d45c70.png)
ed

but it not working for me.

i use \dynamikaweb\lightgallery\LightGallery::widget([ in Yii2.

How can I show the close button in the upper right corner?

Thank you.

**Comment by MaksTrader** [comment]
Yes. I use
/**
 * lightgallery | 2.2.1 | September 4th 2021
 * http://www.lightgalleryjs.com/
 * Copyright (c) 2020 Sachin Neravath;
 * @license GPLv3
 */

**Comment by sachinchoolur** [comment]
This works fine for me. could be the issue with the widget that you are using. 
It would be helpful to debug the issue  if you could provide a demo URL

**Comment by MaksTrader** [comment]
Greetings. Thank you for your reply. Here's a working site https://worldtokenwall.com. Please? open the image in the upper left corner.  On mobile.

**Comment by MaksTrader** [comment]
You are right, it looks like the widget does not use these optio
![Screenshot_8](https://user-images.githubusercontent.com/47728504/134869013-2a25c68c-d9ac-464f-a132-6d916b2029fb.png)
ns

**Comment by sachinchoolur** [comment]
Yes, I think you should report this issue to them.
Even if I provide a workaround that could break in the upcoming versions.

let me know if you need any other assistance from my side

**Comment by MaksTrader** [comment]
Thank you. Your advice was very helpful. 

Made an additional js file like this, 

$("map-conteiner").lightGallery({
    mobileSettings: [{
        controls: true,
        showCloseIcon: true,
        download: false
    }]
})

added it to Widget Assets 

![Screenshot_9](https://user-images.githubusercontent.com/47728504/134878345-3e972512-6a11-4a06-92fb-d81c4f641f38.png)


and everything worked.

The question can be closed.
