### ISSUE TITLE
Can't close lightGallery

### ISSUE THREAD

**Issue by TobGr** [sachinchoolur/lightGallery#1169]
Hi!

When I click on the close button or outside of the image I get the following error: 
`Uncaught TypeError: r.scrollTo is not a function at jquery.min.js:2`

![image](https://user-images.githubusercontent.com/37364758/134880364-67d1b604-8947-4f9b-9e63-877aefd324d5.png)

Tested: Chrome / Safari / FireFox

**Comment by sachinchoolur** [comment]
Hey @TobGr,
Which version of lightGalelry are you using? Since version 2.x lightGalelry does not require jQuery to work

**Comment by TobGr** [comment]
v1.3.7

**Comment by sachinchoolur** [comment]
ligthGallery 1.x is no longer maintained. Please upgrade to 2.x
https://github.com/sachinchoolur/lightGallery/releases/tag/2.0.0

or if you want to use 1.x consider upgrading to version https://github.com/sachinchoolur/lightGallery/releases/tag/1.9.0

**Comment by sachinchoolur** [comment]
Closing the issue. 
Let me know if you need any other assistance from my side.
