### ISSUE TITLE
"The file or directory could not be found." when trying to load a youtube video

### ISSUE THREAD

**Issue by erikbue** [sachinchoolur/lightGallery#117]
I believe I've copied the instructions/code exactly as presented, but am getting the error mentioned in the title. I get the following error in the Chrome Inspector Panel as well:

GET file://www.youtube.com/embed/y_pyBeQPmzw?autoplay=1&rel=0&wmode=opaque net::ERR_FILE_NOT_FOUND

I'm not too familiar JS so I could definitely be doing something wrong, but any assistance would be great, thanks!

**Comment by boynet** [comment]
did you put "http://" before the youtube url?

**Comment by erikbue** [comment]
yeah, my code looks like this:

    <div id="video">
        <div data-src="http://www.youtube.com/watch?v=y_pyBeQPmzw"> 
        <a href="#">
            <div id="link" class="mainText" data-toggle="modal" data-target="#myModal">Check out the video!&nbsp;<i class="fa fa-arrow-right"></i></div>
        </a> 
     </div>
 </div>`

**Comment by erikbue** [comment]
also, the error posted above "GET file://www.youtube.com/embed/y_pyBeQPmzw?autoplay=1&rel=0&wmode=opaque net::ERR_FILE_NOT_FOUND" also shows

    (anonymous function) @ jquery.min.js:4
    b.fn.extend.domManip @ jquery.min.js:4
    b.fn.extend.prepend @ jquery.min.js:4
    (anonymous function) @ lightGallery.js:380

**Comment by boynet** [comment]
the bug is from here: https://github.com/sachinchoolur/lightGallery/blob/master/light-gallery/js/lightGallery.js#L278 basicly you see it just because you run it in your computer.. if you upload the code to server its should work fine, anyway you can fork and edit this line if you want

**Comment by erikbue** [comment]
thanks for the info! so this is my first post ever on GitHub, and honestly I don't even know what it means to fork something. Is there something I need to edit in the JS file so that I can preview it on my computer? Or do I just continue working and assume it will work when it's live?

**Comment by boynet** [comment]
you can edit this line in your js file, but dont forget in the future if you update to new version to change the line again..

about fork: https://help.github.com/articles/fork-a-repo/

**Comment by erikbue** [comment]
The line in my JS file already matches what you posted. Am I missing something? Thanks for your help/patience!

**Comment by boynet** [comment]
in the line can you see this ````src="//www.youtube.com/embed/'```` ? so put http: before the // so it will look like this: ````src="http://www.youtube.com/embed/'```` now save your file and use that file in your site, and in the future if you update your plugin to news version just remember to update that line again

**Comment by erikbue** [comment]
You are awesome, I really appreciate the help!

**Comment by sachinchoolur** [comment]
Hi,
This will work fine if you run your demo in any local server like wamp-serve or http-server.
And i think it is not necessary  to change from `src="//www.youtube.com/embed/'` to `src="http://www.youtube.com/embed/'` because if we use first method browser will automatically request the url with appropriate protocol.
For ex: If the browser is viewing the page through HTTPS it will request for for `src="https://www.youtube.com/embed/'` otherwise it will request for `src="http://www.youtube.com/embed/'.`
According to my knowledge if you add `http`: in source you may get error when you use gallery on a secure (https) website.

Thank you @boynet for your support..

**Comment by boynet** [comment]
@sachinchoolur you are right :) the problem is with a lot of other scripts, when using cordova\phonegap the protocol is always file:// I think we can move from // to protocol detection or some option to force some protocol

**Comment by q2apro** [comment]
I ran into the same issue. I think lightGallery should at least state in the dev console something like "Youtube videos will only work on your server." - Then it's clear to every developer. Thx.
