### ISSUE TITLE
Video not playing with video.js

### ISSUE THREAD

**Issue by andrepetrini** [sachinchoolur/lightGallery#1172]
Hi there,
I'm trying to use LightGallery with Video.Js for a few days now, but I'm not being able to play the videos.
When I use the [lgVideo] plugin, it works fine, but as soon as I change to video.js, the video doesn't play.
And I need to use Video.js because the video format is .master.m3u8, which is only supported by video.js.
I created a codepen with my code:
https://codepen.io/andr-petrini/pen/rNwPMYE

Thank you

**Comment by sachinchoolur** [comment]
Hey @andrepetrini,

Thanks for the codepen demo - 
You need to include the lightGallery video plugin even if you use videojs


```js
lightGallery(document.getElementById('gallery-container'), {
   plugins: [lgVideo],
   videojs: true,
   videojsOptions: {
        muted: true,
    },
 });
```

**Comment by andrepetrini** [comment]
Wow, it worked. Thank you so much, Sachin.
Just as feedback, this line is missing from the documentation. Maybe it could be a good idea to add there too.
Anyway, great work with this plugin. Thank you

**Comment by sachinchoolur** [comment]
Yes, you are right, I found that yesterday. Already made the changes locally.
<img width="852" alt="Screenshot 2021-09-29 at 9 48 43 AM" src="https://user-images.githubusercontent.com/6586706/135202595-2996d997-0a0e-479e-8af1-18c863a147fd.png">
