### ISSUE TITLE
React, links to images in child components

### ISSUE THREAD

**Issue by July-** [sachinchoolur/lightGallery#1173]
I'm trying to add lightGallery to a page where every item is a separate component. Is it possible?

This is how my simplified code looks (and lightGallery is not working there):
```
<LightGallery
	speed={500}
	plugins={[lgZoom]}
	selector=".gallery-item">
		{chatHistory.list.map(function (item) {
			return (<Message message={item} key={item.id} />)
		})}
</LightGallery>
```

And in child component:
```
<div className="message">	
	{message.previewUrl && <div className="message-image">
		<a href={message.attachmentUrl} className="gallery-item"><img src={message.previewUrl} /></a>
	</div> }
	<div className="message-text">
		{message.text}
	</div>
</div>
```

**Comment by sachinchoolur** [comment]
Hey @July-,
This works fine for me. 
Here is the working demo - https://stackblitz.com/edit/lightgallery-react-1c8h7h?file=index.tsx

Please share a little more information about the error that you are getting

**Comment by July-** [comment]
I got a real reason why my code didn't work. I didn't call refresh method after getting data from api endpoint. Now it works, thank you.
