### ISSUE TITLE
data-sub-html / captions / custom HTML not displaying in dynamic galleries

### ISSUE THREAD

**Issue by cbracco** [sachinchoolur/lightGallery#118]
Hi there,

Great plugin! I'm running into an interesting issue while trying to append captions to images using the `data-sub-html` attribute and the `dynamic` option at the same time. I think I have followed the instructions correctly.

Here is a fiddle that demonstrates my scenario: [http://jsfiddle.net/msbvspke](http://jsfiddle.net/msbvspke)

I'm not sure why, but the content inside `data-sub-html` never gets inserted into the `.lg-slide` element. Any help or guidance here is greatly appreciated.

Cheers!
Chris

**Comment by sachinchoolur** [comment]
Hi,
If you are using dynamic mode you have to pass all the options via dynamicEl. You can use `sub-html` to pass the captions 

Please check the updated jsfiddle http://jsfiddle.net/sachin377/msbvspke/2/
Let me know if you have any queries..

**Comment by cbracco** [comment]
Ah, that would explain it. Haha. Thank you for the clarification! It's working perfectly now.
