### ISSUE TITLE
Mousewheel Navigation for FF/IE

### ISSUE THREAD

**Issue by syedabdulbaqi** [sachinchoolur/lightGallery#1182]
Mousewheel navigation in lightgallery v2 is not working for Firefox and Internet Explorer. It used to work in v1.
I understand v2 doesn't use jQuery, but do you have any plans for implementing mousewheel navigation in v2 for FF and IE?

**Comment by sachinchoolur** [comment]
Yes, It is not tested on IE. I'll test it on all devices and browsers before the release
