### ISSUE TITLE
Thumbnail Slider on iPhone iOS 15 Safari not working properly

### ISSUE THREAD

**Issue by LBI-ecx** [sachinchoolur/lightGallery#1186]
When sliding back/forth, sliding stucks

- to reproduce this, slide multiple times to see all images on in the thumbnails back and forth sliding stucks/jumps at random stages.
- issue does not appear in Firefox
- issue also appears on DEMO site https://www.lightgalleryjs.com/demos/thumbnails/

**Comment by LBI-ecx** [comment]
Do you already have a plan when the next release will come out?

Best regards

**Comment by sachinchoolur** [comment]
Oops!.. I forgot to update you. 

This was an issue with the Safari browser and fixed in the next minor release itself. 
Is this still happening for you?

**Comment by LBI-ecx** [comment]
I can't reproduce it anymore. Thank you!
