### ISSUE TITLE
Pulling in inline content into an iframe

### ISSUE THREAD

**Issue by 36lpi** [sachinchoolur/lightGallery#119]
Hello,

Great plugin! Very smooth... I was wondering if there's anyway to pull inline content into an iframe? I have a hidden div on the page, and I want to display it within an lightGallery iframe. If so, how does that mark-up look?

Thanks,
Corey

**Comment by sachinchoolur** [comment]
Hi,
Currently it is not possible. You have to customize lightGallery to pull inline content into iframe.
This stackoverflow answer might be helpful http://stackoverflow.com/questions/4199458/specifying-content-of-an-iframe-instead-of-the-src-to-a-page
