### ISSUE TITLE
Allow download button to go to URL rather than downloading the html file

### ISSUE THREAD

**Issue by robjbrain** [sachinchoolur/lightGallery#1205]
## Summary

When you set "data-download-url" to a html web page the browser requests that you download the HTML page, presumably because somewhere in the JS a download header is given (although I couldn't find exactly where this happened in code)

I'm requesting that a download is not always forced and you can redirect to a page instead.

### Basic example

Sometimes you would want the download button to go to a specific page, e.g. a product page for the product shown in the image, or where you choose a windows/mac version or whatever.

It would make sense to me to not download if the it's HTML response. If it's not possible to detect the content type, there should perhaps be an setting of whether to simply redirect or to download.

### Motivation

Right now there is no way to link to another page from an image. In my particular case i'm looking to use the download button to link to another page.

Alternatively we could have a feature that uses a prop such as "data-goto-url" possibly with a link icon rather than a download icon?

**Comment by sachinchoolur** [comment]
Hey @robjbrain,

Thanks for the suggestions. I think it will be a little hard to convince users that, you need to pass some URL via `data-download-url` to open this link in a new tab. 

But you can easily achieve this using lightGallery events.

- Pass `download: false,` via settings to hide the existing download icon
- Add a custom link to the toolbar, if you want the same looks and feel of the download icon, you can use the existing classname
- Change the download URL on `lgAfterSlide` event 

```js

const $galleryContainer = document.getElementById("gallery-container");

const customLink = `<a target="_blank" id="lg-custom-link" class="lg-download lg-icon"></a>`;

$galleryContainer.addEventListener("lgInit", () => {
  const $toolbar = document.querySelector(".lg .lg-toolbar");
  $toolbar.insertAdjacentHTML("beforeend", customLink);
});

let pluginInstance = null;

$galleryContainer.addEventListener("lgAfterSlide", (event) => {
  const { index } = event.detail;
  document
    .getElementById("lg-custom-link")
    .setAttribute("href", pluginInstance.galleryItems[index].downloadUrl);
});

pluginInstance = lightGallery($galleryContainer, {
  speed: 500,
  download: false,
  plugins: [lgZoom]
});


```

Here is the working demo - https://codepen.io/sachinchoolur/pen/MWvqpVB

let me know if you face any issues
