### ISSUE TITLE
Using lightGallery w/ Swup

### ISSUE THREAD

**Issue by nickpish** [sachinchoolur/lightGallery#1206]
Hi, I realize this question is a bit out of scope w/ respect to lightGallery itself, but I figured I'd ask to see if anyone might have any insight: I'm trying to integrate lightGallery with the page transition library [Swup](https://swup.js.org/), and I'm running into an issue that seems to derive from the use of the Zoom plugin. Given that Swup uses a primary container element to swap in content via Ajax rather than actually reloading the whole page, one must initialize (and destroy) plugins using [Swup events](https://swup.js.org/events). Using some helpful code I found in this forum, I'm doing the following to initialize and destroy a lightGallery instance:

```
const galleries = {};

const initGallery = (id, settings) => {
    galleries[id] = lightGallery(document.getElementById(id), settings);
}
const destroyGallery = (id) => {
    galleries[id].destroy();
}

// lightGallery settings
const lgSettings = {
    // plugins: [lgThumbnail, lgZoom] --> using the Zoom plugin seems to break Swup
    plugins: [lgThumbnail],
    selector: '.artwork a',
    thumbnail: true,
}

// initialize lightGallery on page load
if (document.querySelector('#gallery')) {
    initGallery('gallery', lgSettings);
}

// initialize lightGallery on swup event contentReplaced
document.addEventListener("swup:contentReplaced", function() {
    if (document.querySelector('#gallery')) {
        initGallery('gallery', lgSettings);
    };
});

// destroy lightGallery instance on swup event willReplaceContent
document.addEventListener("swup:willReplaceContent", function() {
    if (document.querySelector('#gallery')) {
        destroyGallery('gallery');
    }
});

```

Interestingly, everything above works fine when navigating between pages **except** for when I've included the Zoom plugin- for whatever reason, when the Zoom plugin is activated, Swup seems to break when navigating away from the page with lightGallery- the container goes blank, and the page hangs and must be reloaded. I'm wondering if there's anything specific with the Zoom plugin that might be causing a conflict and inhibiting the Swup page transition behavior? Am I incorrectly initializing or destroying the plugin instance or should I use a different method? Any help here is most appreciated, as the zoom functionality is critical for this project. This is how I'm initializing Swup, btw:

```
// swup init
const swup = new Swup({
    containers: ["#genesis-content"],
    linkSelector: 'a[href^="'+ document.location.origin +'"]:not([data-no-swup]):not([href*=".jpg"]), a[href^="//"]:not([data-no-swup]), a[href^="#"]:not([data-no-swup]),a[xlink\\:href]',
    cache: false,
    plugins: [
        new SwupBodyClassPlugin(),
        new SwupProgressPlugin(),
    ],
});
```

**Comment by sachinchoolur** [comment]
Hey @nickpish,

Your code looks good to me. The issue could be because of some CSS conflicts 

If you could provide a demo URL, I'll try to find figure out the issue

**Comment by nickpish** [comment]
Hi @sachinchoolur - thanks so much for taking a look; I believe I've found the culprit after hours of troubleshooting. As described on [this Swup support page](https://swup.js.org/other/common-issues), by default Swup looks as at *all* elements with a `class*="swup-transition-"` and lo and behold the Zoom library makes use of such an element! Hence, when navigating away from the gallery page, Swup is waiting for a transition to end on that element, which of course won't happen, so it hangs the page load altogether. Fortunately, changing the default `animationSelector` fixes the issue so, in short, nothing to do with lightGallery itself. Given that many plugins, UI frameworks, etc. make use of such classes, the Swup folks would probably be well advised to use a different class name as their default :) Perhaps this thread can save someone else the hours it took me to finally realize what was going on!

**Comment by sachinchoolur** [comment]
Thank you for the detailed explanation. I'm glad you figured it 👍🏻
