### ISSUE TITLE
images/loading.gif is missing?

### ISSUE THREAD

**Issue by chrispcb** [sachinchoolur/lightGallery#1207]
Hi,

I installed your great plugin (2.3.0) from yarn or npm but there isn't dist or images directory. (project is a simple php web site, js, html, css)

In lg-comments.css, lightgallery-bundle.css, lightgallery-core.css, lightgallery.css files (scss and min) there is a css class with:
`background: url("../images/loading.gif") no-repeat scroll center center #fff;`

There is a 404 when use a video for exemple.

Did I miss my install?

**Comment by sachinchoolur** [comment]
Are the icons loading correctly? Please make sure the loading.gif exists in the directory.
If the issue persists please try loading CSS from any CDN - https://www.jsdelivr.com/package/npm/lightgallery

**Comment by chrispcb** [comment]
@sachinchoolur after install, there is not images directory and loading.gif images.

**Comment by sachinchoolur** [comment]
Sorry for the late reply. Were you able to solve the issue?

If not, please share the screenshot of the lightGallery files in the directory

**Comment by chrispcb** [comment]
this is a screenshot of the lightGallery files in the director:
![Capture d’écran 2021-11-30 200349](https://user-images.githubusercontent.com/10771054/144117412-ae1bab48-2d87-4e5a-9870-5d350f8e087a.png)

**Comment by sachinchoolur** [comment]
Oh, that's strange. How did you install lightGallery?

**Comment by chrispcb** [comment]
I install lightGallery with yarn or npm. Same results.
If I dowload package on https://www.jsdelivr.com/package/npm/lightgallery there is a image directory.
But it is easier to use npm for updating. Why is it different?

**Comment by sachinchoolur** [comment]
Sorry for the late reply. There shouldn't be any difference.  Could you please try installing on a fresh project?

**Comment by Anvarmirzo** [comment]
the problem is still relevant

**Comment by Anvarmirzo** [comment]
> the problem is still relevant

I found the reason, check for the presence of the $lg-path-images variable, if you have it in your files, try deleting it, since this variable itself is used inside the library, and you overwrite it, thereby changing the path to the file

**Comment by DimpleReenaM** [comment]
gif images are not working in angular lightgallery which plugins or variables have to use
