### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'offsetHeight')

### ISSUE THREAD

**Issue by acancerouscake** [sachinchoolur/lightGallery#1208]
Hey guys, 

I've been struggling to make this work in a react project. Trying to recreate the thumbnail gallery javascript demo. I get this error once the thumbnails are loaded and I select an image. I'm fairly new to react, so any help would go a long long way.

<img width="1039" alt="Screen Shot 2021-11-12 at 5 31 04 pm" src="https://user-images.githubusercontent.com/32236800/141501375-44f373d6-6e88-4186-8b8e-7e6f154587c5.png">

import React,  { useCallback, useEffect, useState } from 'react';
import LightGallery from 'lightgallery/react';

// import styles
import 'lightgallery/css/lightgallery.css';
import 'lightgallery/css/lg-zoom.css';
import 'lightgallery/css/lg-thumbnail.css';

// import plugins if you need
import lgThumbnail from 'lightgallery/plugins/thumbnail';
import lgZoom from 'lightgallery/plugins/zoom';
import lgRotate  from 'lightgallery/plugins/rotate';
import lightGallery from 'lightgallery';
import { template } from '@babel/core';

const Portfolio = () => {
  const galleryImgDataGroup1 = [
    {
        id: '1',
        size:"2400-3600",
        src: require('../assets/images/portfolio/album1/1.jpg').default,
        thumb: require('../assets/images/portfolio/album1/thumbs/1.jpg').default,
        subHtml: `<div class="lightGallery-captions">
        <h4>Photo by <a href="">Garrett Jackson</a></h4>
        <p>Published on May 8, 2020</p></div>`
    },
    {
        id: '2',
        size: "2400-3600",
        src: require('../assets/images/portfolio/album1/2.jpg').default,
        thumb: require('../assets/images/portfolio/album1/thumbs/2.jpg').default,
        subHtml: `<div class="lightGallery-captions">
        <h4>Photo by <a href="">Garrett Jackson</a></h4>
        <p>Published on May 8, 2020</p></div>`
    }];
    
  const [items, setItems] = useState(galleryImgDataGroup1);

  const onInit = () => {
    console.log('lightGallery has been initialized');
  };  
    
  return (
      <LightGallery onInit={onInit} plugins={[lgThumbnail, lgZoom, lgRotate ]} mode="lg-fade" speed={500} elementClassNames="animated-thumbnails">
        {items.map((item) => {
          return (
            <div key={item.id} className="gallery-item">
              <a href={item.src} data-lg-size={item.size}>
                <img className="img-responsive" src={item.thumb} alt={item.subHtml} /> 
              </a>
            </div>
          )})
          }
      </LightGallery>
  );
};

export default Portfolio;

**Comment by nnguyen52** [comment]
each of your subHtml must start with <a href=''> tag.  you can not use any other tag for a wrapper.

**Comment by nnguyen52** [comment]
each of your subHtml must be wrapped by  **_a tag_** like this
`<a href='your big image'> 
<img src='your thumbnail image'/>
</a>`

**Comment by sachinchoolur** [comment]
Hey @acancerouscake,

Found a couple of issues with your markup. Please use the below markup and let me know if the issue persists 

```jsx
<LightGallery onInit={onInit} plugins={[lgThumbnail, lgZoom, lgRotate ]} mode="lg-fade" speed={500} elementClassNames="animated-thumbnails">
        {items.map((item) => {
          return (
            <a  key={item.id} className="gallery-item" href={item.src} data-lg-size={item.size} data-sub-html={item.subHtml} >
                <img className="img-responsive" src={item.thumb}  /> 
              </a>
          )})
          }
      </LightGallery>
```

**Comment by acancerouscake** [comment]
> Hey @acancerouscake,
> 
> Found a couple of issues with your markup. Please use the below markup and let me know if the issue persists
> 
> ```js
> <LightGallery onInit={onInit} plugins={[lgThumbnail, lgZoom, lgRotate ]} mode="lg-fade" speed={500} elementClassNames="animated-thumbnails">
>         {items.map((item) => {
>           return (
>             <a  key={item.id} className="gallery-item" href={item.src} data-lg-size={item.size} data-sub-html={item.subHtml} >
>                 <img className="img-responsive" src={item.thumb}  /> 
>               </a>
>           )})
>           }
>       </LightGallery>
> ```

This fixed it for me, thanks for the swift help guys!

**Comment by sachinchoolur** [comment]
Great. Please note that lightGallery does not refresh slides automatically when data changes 
You need to call the refresh method to update the gallery 
docs - https://www.lightgalleryjs.com/docs/react/#updating-slides
