### ISSUE TITLE
Gallery height and width not working?

### ISSUE THREAD

**Issue by anthony0579** [sachinchoolur/lightGallery#1211]
Core height and width settings don't seem to do anything. 

Usage:
height: '400px',
width: '400px'

Gallery is still 100% of viewport width and height.

**Comment by sachinchoolur** [comment]
Hey @anthony0579,

Really sorry for the delayed response. And thank you for pointing this issue. 

Height and Width settings have been removed since version 2.2.0 - https://github.com/sachinchoolur/lightGallery/releases/tag/2.2.0
But, I forgot to update the documentation. 

I'll update it ASAP
