### ISSUE TITLE
Zooming does not take object-fit into consideration

### ISSUE THREAD

**Issue by HitomiTenshi** [sachinchoolur/lightGallery#1212]
## Description

If an image is resized and `object-fit: contain` or `object-fit: cover` is used, the zoom effect stretches the images as if `object-fit` is not applied.

### Steps to reproduce

https://user-images.githubusercontent.com/7304212/142077819-85860890-f97d-442b-840a-9a4884800e6e.mp4

### Environment

-   Browser and version - Chrome latest
-   OS - Win10
-   lightGallery version - latest

### Additional context

Reproducible on demo page: https://www.lightgalleryjs.com/demos/thumbnails/

**Comment by sachinchoolur** [comment]
Hey @HitomiTenshi,

Yes, currently, it is not possible. But, I'm thinking of adding an option to pass the dimensions via `data-attribute`.
