### ISSUE TITLE
Recalculate height of lg-sub-html based on content?

### ISSUE THREAD

**Issue by nickpish** [sachinchoolur/lightGallery#1216]
Hi, I'm using the `subHtmlSelectorRelative` option to pull caption info from a `.full-caption` div for each gallery item, and my issue is that the height of `.lg-sub-html` seems to be calculated based on the caption content of the first item, such that if a subsequent item has a longer caption (i.e. taller element) it will overlay the image as the container element's height is fixed. I'm wondering if it's possible to have the caption container height recalculated based on the content of the current item? Thanks for any assistance here.

**Comment by sachinchoolur** [comment]
Hey @nickpish,

You can use the setting `defaultCaptionHeight` to set an appropriate height for the caption. 
If we change the height of the captions dynamically based on content, it will reside the images too. 
You need to maintain a stable height for smooth transitions. 

But, I get your point and I'll try to improve the experience if possible

**Comment by nickpish** [comment]
Hi @sachinchoolur - ok, thanks, that makes sense. I realize the image sizes would vary to fit the different caption heights, which would be undesirable. So I guess I'd just need to set a `defaultCaptionHeight` that's tall enough to accommodate the longest/tallest caption. Thanks!
