### ISSUE TITLE
Adds `position: relative` to body and breaks layout

### ISSUE THREAD

**Issue by andreialecu** [sachinchoolur/lightGallery#1218]
## Description

I've been recently testing lightGallery in a next.js project and noticed that it breaks the page layout because it seems to add `position: relative` to the body tag, which doesn't play well with the rest of the page.

Additionally, it leaves it there forever so when navigating to further pages, it will also break them. Next.js navigation works client-side, by replacing the html.

This can be seen here: https://github.com/sachinchoolur/lightGallery/blob/59b292ff2894b8732967eef805a02d92769a0ec1/src/lightgallery.ts#L365

Why is position relative being added? I tested without it for a bit, by toggling it off via Chrome Developer tools, and I didn't notice any issues.

### Environment

-   lightGallery version - 2.3.0

**Comment by andreialecu** [comment]
I think this was supposed to only be added for custom container elements, and not for the body.

Seems it was added in this commit: https://github.com/sachinchoolur/lightGallery/commit/1d097ecfb91b7eb103c8877fe28b5090bb530439

**Comment by sachinchoolur** [comment]
Merged. Thank you so much for your contribution

**Comment by sachinchoolur** [comment]
Hey @LufoX11,

You can safely upgrade to version [2.4.0-beta.0](https://github.com/sachinchoolur/lightGallery/releases/tag/2.4.0-beta.0)
It is pretty stable and no issues reported so far.
