### ISSUE TITLE
Add zoom support

### ISSUE THREAD

**Issue by gthvidsten** [sachinchoolur/lightGallery#122]
It would be nice to be able to zoom the fullscreen images.

**Comment by d61helix** [comment]
if you're talking about touch zoom on mobile devices, just remove e.preventDefault(); in 
 enableTouch: function () as follows:

```javascript
$('body').on('touchmove.lightGallery', function (e) {
                        var orig = e.originalEvent;
                        endCoords = orig.targetTouches[0];
                        //disable to enable zoom
						/*e.preventDefault();*/
                    });
```

**Comment by gthvidsten** [comment]
I'm talking about both desktop versions and touch devices.
There should be an option on lightGallery to do this and not have to add other code.

**Comment by sachinchoolur** [comment]
Hi,
I have added zoom support in lightgallery version 1.2.
Please check..
