### ISSUE TITLE
Full screen videos not working on Safari OSX

### ISSUE THREAD

**Issue by homeworkclubco** [sachinchoolur/lightGallery#1220]
## Description

When making the videos in a gallery fullscreen, the video doesn't seem to load or work. It seem to happen for all video types (Vimeo, YouTube, HTML5).

From my testing the issue is specific to OSX Safari. Mobile and other browsers are unaffected.

Issue can be seen here - https://www.lightgalleryjs.com/demos/video-gallery/

Issue found on Safari Version 15.1 (17612.2.9.1.20)

**Comment by sachinchoolur** [comment]
Thank you for reporting this issue. 
Yes, I can reproduce it. I'll try to resolve the issue ASAP

**Comment by sachinchoolur** [comment]
Looks like css `will-change` property is causing the issue. I'll push a fix after testing it properly

**Comment by homeworkclubco** [comment]
Thank you, Sachin!

**Comment by sachinchoolur** [comment]
Could you pelase use the version `2.4.0-beta.0` and try again?
