### ISSUE TITLE
openGallery() error from ajax request page

### ISSUE THREAD

**Issue by deva-max** [sachinchoolur/lightGallery#1221]
## Summary

openGalley() not open from ajax request page 

Brief explanation of the feature.
 var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
      document.getElementById("demo").innerHTML = this.responseText;
    }
  };
  xhttp.open("GET", "gallery.php", true);
  xhttp.send();

the output of the page while i am hit the group gallery header image  not opening

**Comment by sachinchoolur** [comment]
Can you try calling `refresh` function after updating gallery HTML? 

https://www.lightgalleryjs.com/docs/methods/#refresh
