### ISSUE TITLE
Dynamic mode support for Angular

### ISSUE THREAD

**Issue by thombrink** [sachinchoolur/lightGallery#1222]
## Summary

I saw the option to dynamicly load the lightgallery, but no option to call openGallery on the LightgalleryComponent in Angular.
Could this function be added to the component?

### Basic example

const lg = new LightgalleryComponent();
lg.openGallery();

### Motivation

We would like to load the whole gallery once and dynamicly repopulate the items based on a button/link click.

**Comment by sachinchoolur** [comment]
Hey @thombrink,

Here is the demo of calling `openGallery` in Angular

https://stackblitz.com/edit/lightgallery-angular-dynamic-mode

Let me know if you face any issues

**Comment by thombrink** [comment]
Thanks @sachinchoolur for the quick and detailed response! 

I was overlooking the `instance` property, provided in the `onInit` call. 

It's all working great now!

**Comment by DimpleReenaM** [comment]
Dynamic inline light gallery takes the whole component view to display. It is not able to be an inline element. How to do that
