### ISSUE TITLE
license key is not valid for production use  at LG

### ISSUE THREAD

**Issue by mamadfar** [sachinchoolur/lightGallery#1234]
I have this problem, actually it's a warning but I don't like to appear in console
How can i fix that?!
![lightgalery](https://user-images.githubusercontent.com/60744057/146647246-3d8d8d0d-6eee-4bc0-b2fc-f6d12664c394.png)

**Comment by sachinchoolur** [comment]
Hey @mamadfar,
Once you purchase a lightGallery license, you'll get the license key via email 

Docs : https://www.lightgalleryjs.com/license/
https://www.lightgalleryjs.com/docs/settings/#licenseKey

If your project is GPLv3, please contact me at contact@lightgalleryjs.com to get a license key

**Comment by darkkatarsis** [comment]
@sachinchoolur Is there any way to load licenseKey ones as global in react/node env ?
