### ISSUE TITLE
When I click on the previous button on my mobile, the gallery closes but I am redirected to the second last page (instead of last page)

### ISSUE THREAD

**Issue by VoltolRL** [sachinchoolur/lightGallery#1239]
Hi, 

When I click on the previous button on my mobile, the gallery closes but I am redirected to the second last page (instead of last page)

### Steps to reproduce

    * On mobile go to https://www.google.com/
    * Search for lightGallery
    * Click on https://www.lightgalleryjs.com/
    * Click on an image in the gallery to open the light box
    * Click on the previous button of your mobile
    KO ->I am not redirected to the last page (https://www.lightgalleryjs.com/) but to the second last page (google search)
    Expected -> The light box closes and I stay on the last page (https://www.lightgalleryjs.com/)

### Environment
-  Google chrome
-  Android
-  lightGallery version 2.1

**Comment by sachinchoolur** [comment]
@VoltolRL,

That is how the hash plugin works currently. It doesn't modify the browser history.
But, we've already got a few feature request for the same and will be implementing it soon 

Closing this issue as duplicate https://github.com/sachinchoolur/lightGallery/issues/1014

**Comment by VoltolRL** [comment]
Thanks @sachinchoolur for the explanations.
