### ISSUE TITLE
Long captions are displayed as one single line

### ISSUE THREAD

**Issue by gthvidsten** [sachinchoolur/lightGallery#124]
Having a long caption on an image makes it go "out of bounds". The caption is displayed as one really long line with the remainder falling outside the right side of the browser.
This is fixed by adding the following style to the stylesheet for the page the lightGallery is in:

    #lg-gallery .lg-slide .custom-html {
        white-space: normal;
    }

**Comment by sachinchoolur** [comment]
Hi,
I have fixed this issue in version 1.2

Thanks ..
