### ISSUE TITLE
Svelte/Sveltekit support

### ISSUE THREAD

**Issue by dylancl** [sachinchoolur/lightGallery#1240]
## Summary

Add out-of-the-box support for Svelte and optionally Sveltekit

### Basic example

N/A

### Motivation

Svelte is rising in popularity, and I feel like this awesome library should support it. Currently there aren't any other lightbox libraries that support Svelte/Sveltekit, so the community really needs a great package like this.

**Comment by jnsprnw** [comment]
In case anyone wants to use this in Svelte/Sveltekit, here is a quick snippet of how I got it to work with Svelte 4 and SvelteKit 1.21.0:

```svelte
<script>
  import lightGallery from 'lightgallery';
  import 'lightgallery/css/lightgallery.css';
  import { onMount } from 'svelte';

  let buttonGallery;
  let gallery;

  onMount(() => {
    gallery = lightGallery(buttonGallery, {
      dynamic: true,
      dynamicEl: arrayWithImages
    });
  });

  function launchGallery(index = 0) {
    if (gallery) {
      gallery.openGallery(index);
    }
  }
</script>

<button
  bind:this={buttonGallery}
  on:click={() => launchGallery()}
>
  Show gallery from start
</button>

<button on:click={() => launchGallery(2)}>
  Start with specific image in gallery
</button>
