### ISSUE TITLE
Inline-Galery / missing icon + justify

### ISSUE THREAD

**Issue by krungle-mataman** [sachinchoolur/lightGallery#1242]
## Summary
Hello, i am using the inline galery (like the examples in the codepen [https://codepen.io/sachinchoolur/pen/zYZqaGm] (without bootstrap) and i am missing the icons (f.e. next/prev ) and the images are not centered.
Where do i have to declare this  ?

### Basic example
https://codepen.io/sachinchoolur/pen/zYZqaGm

### Motivation

Just experementing with the libaries!

thanks

**Comment by sachinchoolur** [comment]
Hey @krungle-mataman,

There might be some issues with loading CSS

Do you have a link that I can take a look?
If not, please share a screenshot of the gallery

**Comment by xXFulgoreXx** [comment]
I am having the same issue. The gallery opensup with the right format including the images. The controlls are there but invisible. It seems that it cannot find the Icons. I have no errors, also the path to the font folder seems right. I am using the lightslider in combination with the lightGallery. 

CSS:
- lightgallery-bundle.css
- lightslider.css
JS:
-lightgallery.umd.js
-lightslider.js
-lightgallery.js
currently not in use but there are also:
- lg-fullscreen.umd.js
- lg-thumbnail.umd.js
- lg-zoom.umd.js
fonts:
- lg.svg
- lg.ttf
- lg.woff
- lg.woff2

thanks

**Comment by krungle-mataman** [comment]
upp..no help ?

**Comment by sachinchoolur** [comment]
Please share your website URL. I'll take a look and get back to you ASAP

Meanwhile, please try loading the CSS from any [CDN](https://www.jsdelivr.com/package/npm/lightgallery?path=css) to make sure that it is not an issue with the font path
