### ISSUE TITLE
lighthouse error for passive event

### ISSUE THREAD

**Issue by KinG-InFeT** [sachinchoolur/lightGallery#1243]
## Description

![image](https://user-images.githubusercontent.com/193969/151336110-8d42cd66-ebcf-4de5-91aa-f3c8c928309e.png)

### Steps to reproduce

run lighthouse

### Environment

-   Browser and version - Chrome latest version
-   OS - Ubuntu
-   lightGallery version - 2.3.0

**Comment by sachinchoolur** [comment]
Thank you for reporting this. We still need to call preventDefault in some cases. But, I'll try to use passive events wherever possible

**Comment by KinG-InFeT** [comment]
yes, task currently active

**Comment by KinG-InFeT** [comment]
yes, task currently active

**Comment by KinG-InFeT** [comment]
U

**Comment by KinG-InFeT** [comment]
yes, task currently active

**Comment by KinG-InFeT** [comment]
currently active

**Comment by aljabr** [comment]
please any update regarding to this issue?

it's annoying warning messages and I think it will help from performance side.

thank you.

**Comment by gokin4u** [comment]
same here.

**Comment by KinG-InFeT** [comment]
yes, task currently active
