### ISSUE TITLE
Issue when double clicking on an image to zoom in

### ISSUE THREAD

**Issue by ADDISON74** [sachinchoolur/lightGallery#1244]
I am using a desktop monitor (1920 x 1080 px) and Google Chrome 97.0.4692.99 (64-bit) as browser. Here are the steps to reproduce this issue:

1) Maximize your browser window and visit this link https://www.lightgalleryjs.com/demos/thumbnails/

2) Open the first demo (Animated thumbnails). Click on a thumbnail at the bottom then double click on the image for zooming in. The image will zoom but it is not centered in the middle of the screen. Double click to zoom out. Click again on thumbnail and double click, in my case the image zooms in in a different position.

Please note if I use the zoom icon from top right the image fits as expected both sides.

It is obvious that it is easier to double click the image than to go up for each of them to press the zoom icon. Those who double click will get annoyed (my case) when they find that the images are not centered in relation to the edges of the screen, with random positions. You should add the action from the zoom icon to double click too.

Here are two screenshots and see the width of the sides

![screenshot](https://user-images.githubusercontent.com/8360474/151410648-e3276231-e91e-40fc-a38f-3ac43527f039.png)

![screenshot-2](https://user-images.githubusercontent.com/8360474/151411196-754ba69b-a160-4008-80b1-b7df78744bcc.png)

**Comment by ADDISON74** [comment]
Better analyzing the issue in the case of very large images in size, when double click is executed, the position of the mouse pointer counts because that area will be focus. Just double click more to the left and more to the right and see how the image moves to both sides. For this reason the black left-right background does not have the same width. If the image gets bigger it could overlap the black background and then it wouldn't be an issue. That depends on the zoom value.

**Comment by sachinchoolur** [comment]
Hey @ADDISON74,

Thank you for the suggestion. But this is intentionally implemented this way after so much user feedback and iteration.

When someone double click/tap on the photo to zoom in, they usually want the photo to be zoomed in from the clicked position. lightGallery always tries to keep the clicked portion as close as possible to the mouse pointer.

But, I got your point, and I'll keep this issue open for some time. If we get more positive feedback, we can incorporate your suggestion

**Comment by ADDISON74** [comment]
As you stated it is not a code error but a feature request. It could be solved with a new option, for example even if I double-click in a certain area to enlarge the image from the center. There may also be an option for the zoom level to overlap the black side edges.

Thank you for your work. I'm evaluating lightGallery for the first time to replace Photoswipe. So far I think I've found what I was looking for.
