### ISSUE TITLE
Error produced when speed is less than startAnimationDuration

### ISSUE THREAD

**Issue by multiwebinc** [sachinchoolur/lightGallery#1245]
## Description

When the zoom plugin is enabled and `speed` is less than `startAnimationDuration`, the following error occurs when clicking on one of the images to open the gallery:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'offsetHeight')
    at Zoom.getImageSize (lg-zoom.ts:180:44)
    at Zoom.setZoomEssentials (lg-zoom.ts:285:32)
    at HTMLDivElement.<anonymous> (lg-zoom.ts:628:26)
    at lgQuery.trigger (lgQuery.ts:303:27)
    at lightgallery.ts:1635:27
```

Here's what I use to initialize the plugin
```
lightGallery(document.getElementById('someId'), {
    plugins: [
        lgAutoplay,lgFullscreen,lgThumbnail,lgZoom
    ],
    speed: 299,
    startAnimationDuration: 300,
});
```

The same error also occurs, even if `speed` is greater than `startAnimationDuration`, if you open the gallery and quickly close it with the <kbd>Esc</kbd> key.

**Comment by sachinchoolur** [comment]
Thank you for reporting this issue. I hope it is not a blocker for you as you can adjust both values

**Comment by vanbosse** [comment]
We're experiencing the same issue when pressing the `Esc` key. Is there any progress on the matter. Can we help?
