### ISSUE TITLE
Buttons should have title attributes

### ISSUE THREAD

**Issue by multiwebinc** [sachinchoolur/lightGallery#1246]
For example,

```html
<button id="lg-actual-size-1" type="button" aria-label="View actual size" class="lg-zoom-in lg-icon"></button>
```

Add title attribute:

```html
<button id="lg-actual-size-1" type="button" aria-label="View actual size" title="View actual size" class="lg-zoom-in lg-icon"></button>
```

This will allow users to know what the buttons do by hovering their mouse over them.

**Comment by sachinchoolur** [comment]
I think a few sets of people don't like the default title style. 

But, if you wish, you can easily add a title to all buttons 

```js
$galleryContainer.addEventListener("lgInit", (event) => {
  const pluginInstance = event.detail.instance;

  // Note attr and find are not jQuery methods
  // These are utility methods provided by lightGallery
  const $toolbar = pluginInstance.$toolbar;
  $toolbar.find(".lg-close").attr("title", "Close Gallery");
  $toolbar.find(".lg-download").attr("title", "Download Image");
});

```

Here is the demo - https://codepen.io/sachinchoolur/pen/RwjoLdO

**Comment by multiwebinc** [comment]
@sachinchoolur Yeah, I agree. I don't always like the default titles, especially when you want them to show up immediately or add HTML to them, but I think they would work fine in this case. Either way, they're still better than nothing and very easy to implement.
