### ISSUE TITLE
S3 Integration

### ISSUE THREAD

**Issue by truedeity** [sachinchoolur/lightGallery#1247]
## Summary

I would like to be able to supply configurations for an S3 bucket e.g. AWS S3, Digital Ocean Spaces (S3 Compliant) 

Should be able to specify a folder on the S3 bucket of videos or photos

Display a video gallery of the files (videos, photos) 

### Basic example

Include a basic example or links here.

### Motivation

S3 Buckets are necessary for cost effective storage there doesn't appear to be any existing library that allows you to seamlessly create a video or photo gallery from an S3 bucket.

**Comment by sachinchoolur** [comment]
Hey @truedeity,

Thank you for the suggestion. Maybe we can consider building a lightGallery plugin to make the integration easier.

But I think it will be too restrictive if people want to customize thumbnails of the gallery or make any customization.

Are you facing any difficulties in integrating with S3?

**Comment by truedeity** [comment]
> Hey @truedeity,
> 
> 
> 
> Thank you for the suggestion. Maybe we can consider building a lightGallery plugin to make the integration easier.
> 
> 
> 
> But I think it will be too restrictive if people want to customize thumbnails of the gallery or make any customization.
> 
> 
> 
> Are you facing any difficulties in integrating with S3?
> 
> 
> 
> 


Well I wanted to have a personal website with a video gallery.  I was looking for something that would be convenient rather than implementing it from the ground up.
