### ISSUE TITLE
multiple galleries in LightGallery v2

### ISSUE THREAD

**Issue by snote** [sachinchoolur/lightGallery#1248]
I am trying to access multiple Galleries through a menu.
The menu should be overlayed over the galleries and switch
between the galleries. A click on a gallery button must
first close the previously opened gallery and at the same time
open the new one.
The opening is working but not the closing...
I tried with destroying but I can't figure out how to
set the code correctly.
snote

here is an example:
https://codepen.io/snote/pen/eYepEve

**Comment by sachinchoolur** [comment]
Hey @snote,

Here is the working demo  - https://codepen.io/lightGallery/pen/jOabJvO

You need to close the other galleries before opening new one by calling `galleryInstance.closeGallery()`

**Comment by snote** [comment]
Thanks so much!
Also for the whole gallery. Great!

**Comment by snote** [comment]
I updated to V2 but some js is not recognizing the new gallery.
On opening/closing the galleries, the class of a menu ("menu-back") item needs to change.

This is the old code:
	$(" #Gal1ery-1, #Gallery-2, ...").on({		
		'onBeforeOpen.lg': function(event) {
                $("body").addClass("menu-back");
               
            },
            'onBeforeClose.lg': function(event) {
                $("body").removeClass("menu-back");
                
            }
        })

**Comment by sachinchoolur** [comment]
Sorry for the delayed response. 

Events have been renamed in v2. Please follow the docs and let me know if you face any issues.

Docs - https://www.lightgalleryjs.com/docs/events/#lgBeforeClose

**Comment by snote** [comment]
My old setup was initiating the lightgallery via JS
like:
lightGallery(document.getElementById('gallery1'));

The html markup was:

 <div id="gallery1" > <a href="#" class="link"
data-responsive="images/home-best-of/004-375.jpg 375, images/home-best-of/004-480.jpg 480, images/home-best-of/004-800.jpg 800"
data-src="images/home-best-of/004-1600.jpg"
data-download-url="images/doku/full.jpg" 
data-sub-html="<h3>text</h3>
                     </a>   </div>  ">  

Now in dynamic mode the sources seem to have been marked in the JS section like:

 dynamicEl: [
    {
    src:
        "images/home-best-of/004-1600.jpg",
      thumb:
        "images/home-best-of/004-375.jpg",
       
     
      subhtml: `<div class="lightGallery-captions">
                    <h3>txt </h3>   
                    <p>Published on September 14, 2016</p>
                </div>`
            },

This works fine, but I want my images to have responsive.
In your docs I can only find responsive html markup and the dynamic
example is only the one above.

I tried to add the dynamic variables you listed in your docs like:

responsive: 'images/home-best-of/002-375.jpg 375, images/home-best-of/002-480.jpg 480, images/home-best-of/002-800.jpg 757.
or:
download-url="images/doku/full.jpg"
but nothing is working...

Can you please give me an example of the responsive setup in dynamic mode.

Thanks,

STEPHAN
