### ISSUE TITLE
Keyboard shortcuts doesn't work when on a video

### ISSUE THREAD

**Issue by gthvidsten** [sachinchoolur/lightGallery#125]
When having used the arrow keys on the keyboard to navigate to a (YouTube) video in the gallery, the arrow keys no longer work.
When on the video page pressing the left arrow key causes the video to rewind. Pressing the right arrow key causes the video to skip forward. Expected behavior is to go the next image in the gallery.

Somewhat related to #21

**Comment by sachinchoolur** [comment]
Hi,
I have added poster images for videos in new version.. even though if the focus is on playing video we cannot control slide via keyboard shortcuts ..
