### ISSUE TITLE
Links are not Crawable Error in Lighthouse

### ISSUE THREAD

**Issue by z0lo13** [sachinchoolur/lightGallery#1250]
## Description
Similar to #1089 

![image](https://user-images.githubusercontent.com/23143958/152578437-f59801cf-8856-4e66-b0fd-40cc8100669c.png)

### Steps to reproduce

Do the Lighthouse test on any page with lightgallery

### Environment

-   Browser and version - Chrome
-   OS - MacOs
-   lightGallery version - 4.0.0

### Additional context
Running on Nuxt

**Comment by sachinchoolur** [comment]
Once the gallery markup is constructed, the href attribute is dynamically added based on each slide. That is why the warning is appearing.

I don't have any straightforward solution for this now. If you have any suggestions, please let me know.
