### ISSUE TITLE
Cannot read properties of undefined (reading '__slideVideoInfo')

### ISSUE THREAD

**Issue by gamestap99** [sachinchoolur/lightGallery#1253]
<img width="724" alt="Screen Shot 2022-02-13 at 22 35 03" src="https://user-images.githubusercontent.com/43195138/153760653-4e5959b9-2d63-4408-b6b8-9e392b16570d.png">

I have a problem. Can you help me, please?

**Comment by sachinchoolur** [comment]
Hey @gamestap99,

Could you please post the code you use to initialize lightGallery?
In case if you are using dynamic mode and opening using `openGallery` method, is you use the index beyond available slides, you might get this issue

**Comment by gamestap99** [comment]
> Hey @gamestap99,
> 
> Could you please post the code you use to initialize lightGallery? In case if you are using dynamic mode and opening using `openGallery` method, is you use the index beyond available slides, you might get this issue

thanks for your answer
