### ISSUE TITLE
Image shown offscreen

### ISSUE THREAD

**Issue by dijkermans** [sachinchoolur/lightGallery#1254]
Hi,

Lightgallery sometimes doesn't show the image. It opens normally but without the image.

![01](https://user-images.githubusercontent.com/33194795/153909591-a73038c2-9d1b-4f98-ae80-ef652ab47b05.jpg)
https://www.lightgalleryjs.com/demos/thumbnails/

The inline css was in one case: "transform: translate3d(1572.45px, 0px, 0px) scale3d(1, 1, 1);" which means the image was shown off screen. I changed it to translate3d(0, 0, 0) and then the image became visible.

My workaround isn't ideal because it affects the dragging/swiping behaviour but it always shows the image  the right way:

.lg-css3.lg-slide.lg-use-css3 .lg-item.lg-current {

    transform: translate3d(0, 0, 0) !important;

}

It's difficult to reproduce the issue but what I do is this:

I open image 3 of the main gallery. Good. Close. I open image 7. Good. Close. I open image 8. Good. Close. I open 8 again. It may go wrong.

Also sometimes more images are shown at once; the second image may move horizontally when moving the mouse, like you're dragging/swiping, but I'm not.
![02](https://user-images.githubusercontent.com/33194795/153909629-84605913-e8dc-429a-8a61-37cfe098559d.jpg)

I'm using below settings but it also happens here: https://www.lightgalleryjs.com/demos/thumbnails/

lightGallery(document.getElementById('slider'), {
	speed: 500,
	download: false,
	counter:false,
	selector: '.element-item-link',
	swipeToClose:false,
});

lg 2.4.0. / win10 / chrome 98.0.4758.82 + Edge 98.0.1108.50

**Comment by dijkermans** [comment]
It also happens on your demos, like this one: https://www.lightgalleryjs.com/demos/thumbnails/
![01](https://user-images.githubusercontent.com/33194795/153909591-a73038c2-9d1b-4f98-ae80-ef652ab47b05.jpg)
Also sometimes more images are shown at once;
![02](https://user-images.githubusercontent.com/33194795/153909629-84605913-e8dc-429a-8a61-37cfe098559d.jpg)

**Comment by dijkermans** [comment]
My quick fix isn't ideal because it affects the dragging/swiping behavior.

> .lg-css3.lg-slide.lg-use-css3 .lg-item.lg-current {
> 
> transform: translate3d(0, 0, 0) !important;
> }

**Comment by sachinchoolur** [comment]
Thank you for reporting this issue. I think this is happening when you close and open gallery in short interval. 
This won't be an issue in real world. I'll try to reproduce it from my side and push a fix in the next version

**Comment by dijkermans** [comment]
Hi, thanks so much. Yes it happens with a short interval. Looks like it's easier to reproduce when you throttle the CPU with the devtools:

![throttle](https://user-images.githubusercontent.com/33194795/154797421-41126a72-62f4-4398-b939-8386d6c04126.jpg)
