### ISSUE TITLE
Add zoom and pan function

### ISSUE THREAD

**Issue by ttangsz** [sachinchoolur/lightGallery#126]
It would be very useful to be able to zoom(mousewheel) and pan(mouse down & move) fullscreen images, especially when we browsing a huge image, such as complex flow diagram, or svg images.

**Comment by scooterlord** [comment]
+1

**Comment by sachinchoolur** [comment]
Hi, 
I have included zoom support in version 1.2 please check..

**Comment by Egor-Chib** [comment]
Thanks for the nice gallery. And zoom option is very handy.
We concentrate on presenting single images. Very large ones. And zoom option is very handy. However: we need to allow user to see other parts of zoomed images, not only center part. Is there way for the user to move large images allow them to see not only center part?
Pan (mouse down & move) function would be really handy.
Also, as we only presenting single images, would be nice if we could do zoom on mouse wheel. Is there way for this?
