### ISSUE TITLE
Rendering iframes in a sandbox

### ISSUE THREAD

**Issue by denisiko** [sachinchoolur/lightGallery#1273]
Currently there seems to be no possibility to protect against malicious code when lightgallery renders content inside an iframe. E.g. potentially dangerous Javascript code inside a PDF file or other scripts or embedded content which make use of security gaps.

There is a very handy HTML attribute for iframes: `sandbox`. With the value of this attribute you can whitelist a lot of stuff an iframe has access to like form submissions, executing scripts, showing popups etc.

It would be nice to be able to tell lightgallery that it should set this attribute on a slide item with wanted values.

What do you think? I would be happy to propose a Pull Request if there is interest.

**Comment by sachinchoolur** [comment]
Sure, maybe we can add a setting for iframe attributes
