### ISSUE TITLE
Toolbar icon issues (actual size button, zoom in button)

### ISSUE THREAD

**Issue by DBadke** [sachinchoolur/lightGallery#1274]
Two issues with the icons in the toolbar:

1) The icon for the Actual Size toggle button is the same as for the Zoom In button. This is caused by an error in lg-zoom.umd.js (line 45):

```
    var zoomSettings = {
            ...
            zoomIn: 'lg-zoom-in',
            zoomOut: 'lg-zoom-out', 

```
should be:

```
    var zoomSettings = {
            ...
            zoomIn: 'lg-actual-size',
            zoomOut: 'lg-actual-size', 

```

2) When the image has been zoomed out to its minimum size, the Zoom Out button is shown as disabled (icon is dimmed). The same should be true of the Zoom In button when the image is zoomed to the maximum size (i.e. actual size).

David

**Comment by sachinchoolur** [comment]
Thank you for reporting this issue.
1) This is intentional. if you want to use the actual size icons instead of zoom in/out icons, you can change it via settings 
2) Yes, this looks like an issue. I'll push a fix ASAP

**Comment by DBadke** [comment]
1. OK. I didn't notice the actualSizeIcons setting.
