### ISSUE TITLE
Question - is it possible to get videojs working without including it into the HTML document via script tag?

### ISSUE THREAD

**Issue by marexandre** [sachinchoolur/lightGallery#1275]
Hi,

I'm trying out React version of lightGallery and ideally wanted to have all imports in one place like the example below rather then needing to include script or link tags into the HTML document, is this possible? Or are there any plans on potentially enabling something similar?

```js
import LightGallery from "lightgallery/react";
import lgVideo from "lightgallery/plugins/video";

import videojs from "video.js";

import "lightgallery/css/lightgallery.css";
import "video.js/dist/video-js.css";

function CoolGallery() {
  return (
    <LightGallery
      plugins={[lgVideo]}
      videojs={videojs}
      ...
    >
      ....
    </LightGallery>
  );
}
```

Are there any other suggestions?

**Comment by sachinchoolur** [comment]
Currently, this is not possible. But it is an excellent suggestion. I'll try to include it in the next version 

You can directly import using  `import "video.js";.`

But it is still global 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#import_a_module_for_its_side_effects_only

**Comment by sachinchoolur** [comment]
Okay, I'll include the changes you requested in the next release.
