### ISSUE TITLE
Inline Video Question

### ISSUE THREAD

**Issue by patarstar7** [sachinchoolur/lightGallery#1276]
Hi 👋 

Is there a way to add a video as a thumbnail and have it autoplay? Also any approach to potentially control the video inline before going into the lightbox itself? 

```javascript
<LightGallery
  plugins={[lgVideo]}
  videojs={videojs}
  ...
>
  <div id="animated-thumbnails">
    <a href="img/img1.jpg">
      <img src="img/thumb1.jpg" />
    </a>
    <a href="img/img2.jpg">
      // Video here
    </a>
    ...
  </div>
</LightGallery>
```

**Comment by sachinchoolur** [comment]
Hey @patarstar7,

Do you mean the thumbnails inside the lightGallery? Currently, it is not possible.

But, you have complete control over the thumbnails markup outside the gallery. You should be able to use video as thumbnails in this case. 

Regarding the [playsinline](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-playsinline) attribute, 
You can pass any video attribute as shown in the below example. 

```html
<a
        data-lg-size="1280-720"
        data-video='{"source": [{"src":"/videos/video1.mp4", "type":"video/mp4"}], "attributes": {"preload": false, "playsinline": true, "controls": true}}'
        data-poster="/images/demo/youtube-video-poster.jpg"
        data-sub-html="<h4>'Peck Pocketed' by Kevin Herron | Disney Favorite</h4>"
    >
        <img
            width="300"
            height="100"
            class="img-responsive"
            src="/images/demo/youtube-video-poster.jpg"
        />
    </a>
```

Demo - https://www.lightgalleryjs.com/demos/video-gallery/#video-autoplay

Let me know if you have any more questions
