### ISSUE TITLE
Group all images matched by selector to make one gallery

### ISSUE THREAD

**Issue by vestaxpdx** [sachinchoolur/lightGallery#128]
Hi, 
Amazing plugin by the way.
Is it possible to create the gallery by matching multiple images that may be sprinkled over a blog post perhaps. Similar to how lightbox grabs all matched images to create one gallery. I have images spread about in various html structures. Would be great if you could click one, then they are collected and made into your awesome gallery.
Thanks,

**Comment by sachinchoolur** [comment]
Hi,
I have release lightgallery version 1.2.
[Here](http://sachinchoolur.github.io/lightGallery/demos/html-markup.html) you can get more information about supported html markups..
If you face any difficulty please let me know..

**Comment by vestaxpdx** [comment]
Awesome thanks!!!

**Comment by spanwair** [comment]
why there is not the same markup written for vanilla
