### ISSUE TITLE
Is there any way to add a plugin dynamically on init ?

### ISSUE THREAD

**Issue by K20** [sachinchoolur/lightGallery#1282]
Hello, 

I'm trying to add a plugin dynamically from event (We use a modular solution where there's a standard lightgallery for everyone and where plugins can change some context).

Is there a way on lightgallery init to add a plugin ? I've tried by adding a plugin through lgInit event but plugin wasn't loaded : 

`event.detail.instance.plugins.push(globalThis["lgJPlatformDebug"])`

**Comment by sachinchoolur** [comment]
Yes, it is possible. 

lightGallery plugins have a method called onInit which will be automatically called when lightGallery is initialized 

Docs - https://www.lightgalleryjs.com/docs/creating-plugins/#plugin-structure

You can also refer to any of the simple lighGallery plugins such as [fullscreen](https://github.com/sachinchoolur/lightGallery/blob/master/src/plugins/fullscreen/lg-fullscreen.ts) or [hash](https://github.com/sachinchoolur/lightGallery/blob/master/src/plugins/hash/lg-hash.ts)

And if you want to perform any actions later, you can make use of lightGallery events 
demo - https://github.com/sachinchoolur/lightGallery/blob/master/src/plugins/hash/lg-hash.ts#L29

If you still face any issues, please let me know your actual usecase. I'll suggest a solution
