### ISSUE TITLE
Importing scss bundle styles not working with webpack

### ISSUE THREAD

**Issue by janwidmer** [sachinchoolur/lightGallery#1287]
## Description

Hi there, I am trying to get started with lightgallery. As soon as I import the scss file `lightgallery-bundle.scss` though, I get an error.

### Steps to reproduce

1. Create a new webpack based project (e.g. by using https://github.com/Wanderduene/quickstart-webpack)
2. Add `lightgallery` as dependency
3. Add `@import 'lightgallery/scss/lightgallery-bundle.scss';` as import in a scss file
4. Import that scss file into your main js file
5. Start dev build

### Environment

-   Browser and version - Chrome 100
-   OS - Mac Monterey (Mac M1)
-   lightGallery version - 2.4.0

### Additional context

Error Message:
```
ERROR in ./node_modules/lightgallery/scss/lightgallery-bundle.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/lightgallery/scss/lightgallery-bundle.scss)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(1:4) /Users/janwidmer/private-projects/lightgallery/node_modules/lightgallery/scss/lightgallery-bundle.scss Unknown word

> 1 | // This files contains lightGallery and all plugins
    |    ^
  2 | 
  3 | // Example For white theme
 @ ./node_modules/css-loader/dist/cjs.js!./src/demo.css 4:0-148 8:26-59
 @ ./src/demo.css 8:6-98 22:17-24 26:7-21 58:25-39 59:36-47 59:50-64 63:6-73:7 64:54-65 64:68-82 70:42-53 70:56-70 72:21-28 83:0-68 83:0-68 84:22-29 84:33-47 84:50-64 61:4-74:5
 @ ./src/index.js 2:0-20

webpack 5.71.0 compiled with 1 error in 552 ms
```

As I use the mentioned webpack quick start plugin, which has setup a scss loader, the error message seems a little bit weird to me..

**Comment by massprogressive** [comment]
@import '~lightgallery/scss/lightgallery-bundle.scss';

Hope this helps.

**Comment by janwidmer** [comment]
@massprogressive leads to a similiar error:

```
ERROR in ./src/patterns/cms/gallery/css/gallery.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

**Comment by massprogressive** [comment]
@janwidmer The repo you are using for webpack configured to manage only *.css files.
`
import 'lightgallery/css/lightgallery-bundle.css';
`
If you want manage *.scss files in your project check out link:
[(https://webpack.js.org/loaders/sass-loader/)]

**Comment by janwidmer** [comment]
@massprogressive I just used that repo for demonstration purposes to be able to quickly demonstrate the error.. My normal setup is using a different stack which is perfectly working for scss files normally..

With my "normal" stack, I get this (I am guessing similiar) error:

```
ERROR in ./src/patterns/cms/gallery/css/gallery.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (/Users/janwidmer/private-projects/daetwiler/re-center/workspace/wp-content/themes/ww-re-center/node_modules/webpack/lib/NormalModule.js:469:19
```

**Comment by janwidmer** [comment]
@massprogressive please find the attached demo stack where you can see the error:

1. run `npm i` 
2. run `npm run dev`
3. see the error

[Archive.zip](https://github.com/sachinchoolur/lightGallery/files/8502233/Archive.zip)

**Comment by janwidmer** [comment]
@massprogressive my bad, my webpack stack did not have the loader enabled for the icon font and the error message of webpack was quite missleading.. it works correctly.
