### ISSUE TITLE
Passive listeners for better scrolling performance

### ISSUE THREAD

**Issue by darkkatarsis** [sachinchoolur/lightGallery#1292]
## Summary

Hi, Is it possible for a script that listens for a scroll event to run in passive mode? Tests in page speed each time suggest that the current solution is not the best and blocks rendering of the page.

<img width="1012" alt="Screenshot 2022-04-21 at 15 11 26" src="https://user-images.githubusercontent.com/24244919/164491803-bb6be34f-2eb1-4d61-8d91-5e711d6a4b33.png">

### Basic example
`document.addEventListener('touchstart', onTouchStart, {passive: true});`
https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=lr

### Motivation

- Better performance
- Better indexing of pages by google

**Comment by sachinchoolur** [comment]
Closing as duplicate -  #1292

Thank you for reporting this.
