### ISSUE TITLE
Where are the Wordpress settings?

### ISSUE THREAD

**Issue by sveloo** [sachinchoolur/lightGallery#1293]
I've just installed the Wordpress plugin version of this plugin. How do I access the settings? I can't seem to do anything and there isn't any link from the gallery either. Is there a guide for the Wordpress version of this plugin available?

**Comment by sachinchoolur** [comment]
Hey @sveloo,

Here is the screenshot -

<img width="1100" alt="Screenshot 2022-04-22 at 8 16 03 PM" src="https://user-images.githubusercontent.com/6586706/164738296-1c756375-78ab-4214-9002-fe4720f6546f.png">

let me know if you have any more questions.

**Comment by sveloo** [comment]
Hey Sachin,

The LightGallery menu option does not appear for me even after installing
the plugin?


Kind regards,

*Sanny Veloo*
Founder & Lead Developer
Edu360

*Website:* www.edu360.com.au
*Mobile:* +61 481 829 998



*Delivering web-based solutions for education since 2011.*

**Comment by sveloo** [comment]
Attaching a screenshot to show that after installation I still don't see
the Light Gallery options in the menu?
[image: sachin-reply.png]

Kind regards,

*Sanny Veloo*
Founder & Lead Developer
Edu360

*Website:* www.edu360.com.au
*Mobile:* +61 481 829 998



*Delivering web-based solutions for education since 2011.*

**Comment by sveloo** [comment]
Hey Sachin,

I think I'm gonna try something else instead. Can you give me a refund?
This plugin isn't working for me.

Kind regards,

*Sanny Veloo*
Founder & Lead Developer
Edu360

*Website:* www.edu360.com.au
*Mobile:* +61 481 829 998



*Delivering web-based solutions for education since 2011.*

**Comment by sveloo** [comment]
Actually sachin,

I'm gonna try to implement your JS version. Can you transfer my license
across from the plugin to JS version?

Kind regards,

*Sanny Veloo*
Founder & Lead Developer
Edu360

*Website:* www.edu360.com.au
*Mobile:* +61 481 829 998



*Delivering web-based solutions for education since 2011.*

**Comment by sachinchoolur** [comment]
I just replied to you via email. 

There was an issue with the instructions sent to you after purchasing the PRO plugin. 

You need to install both FREE and PRO plugins. 

1) Install the free lightGallery WordPress plugin - https://wordpress.org/plugins/lightgallerywp/
2) Install the lightGallery PRO plugin without uninstalling the free version 

That is why the setting is not appearing. 

If you'd like to use the JS version, please purchase a new license and send me an email. I'll give you a full refund for the WP plugin. 


Let me know if you have any questions

**Comment by sveloo** [comment]
Hi Sachin,

Ah got it! No worries. I've got it to work really well with the JS version
and using ACF to build the gallery. I think I might just stick with the JS
version instead.

Ill buy the license for the JS version and send that email when I do,

Thanks! The plugin you've built is GREAT!!!!!

Kind regards,

*Sanny Veloo*
Founder & Lead Developer
Edu360

*Website:* www.edu360.com.au
*Mobile:* +61 481 829 998



*Delivering web-based solutions for education since 2011.*
