### ISSUE TITLE
data-sub-html not loaded

### ISSUE THREAD

**Issue by villesalomaki** [sachinchoolur/lightGallery#130]
I'm probably missing something, but I cannot get the data-sub-html loaded. It is not displaying on top of the picture. See my fiddle: http://jsfiddle.net/w9uuodh5/

**Comment by sachinchoolur** [comment]
Hi,
Sorry for the delayed response.
Lightgallery just add the html what you proved inside data-sub-hmtl attribute...
Adding style for your custom html is your responsibility..

I have included default style for captions in new version.. Please check
