### ISSUE TITLE
how create Storie mode?

### ISSUE THREAD

**Issue by luizalmeida77** [sachinchoolur/lightGallery#1302]
I want to use videos (html5) and images in my gallery, I would like something similar to the instagram "story", with autoplay, pause, etc.
How do I make autoplay wait and display the entire video before moving on to the next one?
Would you have an example? Preferably in vue.js

**Comment by sachinchoolur** [comment]
Hey @luizalmeida77,

Yes, it is possible. lightGallery automatically navigates the next slide once the HTML5 video reaches the end.

Demo - https://stackblitz.com/edit/lightgallery-vue 
Please check the last slide
