### ISSUE TITLE
Image does not stop

### ISSUE THREAD

**Issue by CRC32EX** [sachinchoolur/lightGallery#1304]
### PC
- The image moves even if release the mouse button.
https://user-images.githubusercontent.com/25629617/167848851-ff6a60f5-4a48-4bb9-8565-8dbe9aa3deb7.mp4

### Android
- The image moves even if release the touch.
https://user-images.githubusercontent.com/25629617/167986834-6ad842bf-e1c1-444c-a49f-2ab576b72eb4.mp4

### Steps to reproduce
1. Open URL<br>https://www.lightgalleryjs.com/demos/thumbnails/#lg=nature&slide=1
2. Zoom in
3. Drag & Release
4. The image moves even if you release the mouse button (or touch)

### Note
This is inertia?
If this is not bug, how can i disable it?

**Comment by sachinchoolur** [comment]
Thank you for reporting this issue.  This happens only if drag and hold images without releasing the click. 
I'll improve this in the next version
