### ISSUE TITLE
Hugo/Go Modules and Version Tags

### ISSUE THREAD

**Issue by writeonlycode** [sachinchoolur/lightGallery#1311]
## Summary

Hugo uses Go Modules to fetch 3rd party repositories and import them to be used in the Hugo project. But Go Modules look for tags in the form "v2.4.0" instead of "2.4.0" to fetch the latest version. The last tag in this form is v1.1.3, which is wildly outdated. Any chance that you can add tags in the form "v2.4.0" (maybe in addition to the current format?) so Hugo/Go Modules can fetch the correct latest version?

### Motivation

LightGallery is much used in Hugo websites, and Hugo Modules is the preferred way to manage outside dependencies, so it would be nice if they worked well together.

**Comment by sachinchoolur** [comment]
Hey @writeonlycode,

Thank you for reporting this issue. 

According to [SEMVER](https://semver.org/#is-v123-a-semantic-version), prefixing v with the version tag is not a good practice. 

Do you have any other resources that can help us make a decision?
