### ISSUE TITLE
Implementing comments in Angular

### ISSUE THREAD

**Issue by emadd** [sachinchoolur/lightGallery#1312]
I was hoping you could shed some light on how we might implement comments using the Angular components?  We would like to replace the comments area with our own plugin.

**Comment by sachinchoolur** [comment]
Hey @emadd,

Are you planning to implement your own comment system or existing solutions like FaceBook or Disqus comments ?

**Comment by emadd** [comment]
@sachinchoolur Any chance you could enlighten me?  I'm currently achieving custom commenting via iframes, but it make me feel really dirty.  :)
