### ISSUE TITLE
React lightgallery doesn't render icons

### ISSUE THREAD

**Issue by brunouber** [sachinchoolur/lightGallery#1314]
## Description

We're considering buying a license for lightgallery, but at moment we've a problem with the icons: it looks like the icon font is not loaded.

### Steps to reproduce

```
import LightGallery from 'lightgallery/react';

// import styles
import 'lightgallery/css/lightgallery.css';
import 'lightgallery/css/lg-zoom.css';
import 'lightgallery/css/lg-thumbnail.css';

// import plugins if you need
import lgThumbnail from 'lightgallery/plugins/thumbnail';
import lgZoom from 'lightgallery/plugins/zoom';

function Gallery() {
    const onInit = () => {
        console.log('lightGallery has been initialized');
    };
    return (
        <div className="App">
            <LightGallery
                onInit={onInit}
                speed={500}
                plugins={[lgThumbnail, lgZoom]}
            >
                <a href="img/img1.jpg">
                    <img alt="img1" src="img/thumb1.jpg" />
                </a>
                <a href="img/img2.jpg">
                    <img alt="img2" src="img/thumb2.jpg" />
                </a>
                ...
            </LightGallery>
        </div>
    );
}
```

We tried to render the above `Gallery` component (copy/pasted from [lightgallery react documentation](https://www.lightgalleryjs.com/docs/react/)).

The url of the page in which we render the component is `localhost/foo/bar/baz`.

The gallery renders fine. When we click one of the image, the gallery opens full screen, and font are loaded from `localhost/foo/fonts/lg.woff2?io9a6k`.

Are we doing something wrong?

### Environment

-   Browser and version : all
-   OS : macos
-   lightGallery version : 2.4.0

**Comment by sachinchoolur** [comment]
Hey @brunouber,

This could be an issue with your build system. Might need to tweak CSS loader config. 

Let me know if you are using Create React App or similar tools. I'll try reproducing the issue from my side

**Comment by brunouber** [comment]
Hi @sachinchoolur 

Thanks for the feedback.
It was indeed the build system - we had to set `url: true` in the css-loader option.
