### ISSUE TITLE
Why does "exThumbImage" loads all images at once?

### ISSUE THREAD

**Issue by q2apro** [sachinchoolur/lightGallery#132]
I just posted some info on my video gallery over here: https://github.com/sachinchoolur/lightGallery/issues/131

Now I see that it works but when I open a video I see that **all thumbs** get loaded. These are more than 100, and in size: 9 MB.

How could I do a lazy load or a subsequential preload here?

**Comment by sachinchoolur** [comment]
Hi,
Currently this feature is not available.
I will let you know if i add this feature..
