### ISSUE TITLE
Cannot read properties of undefined (reading 'offsetHeight') on next.js

### ISSUE THREAD

**Issue by ashadul-mridha** [sachinchoolur/lightGallery#1326]
when fetch data from api and load show error message Cannot read properties of undefined (reading 'offsetHeight') on onclick in next.js but it work fine on local data.

**Comment by sachinchoolur** [comment]
Hey @ashadul-mridha,

Thank you for reporting the issue. Is the error stopping the gallery from opening, or are you seeing any issues with any of the gallery functionalities

**Comment by ashadul-mridha** [comment]
This error shows when I open the gallery. 

This error appears when I fetch the data through API.

**Comment by ashadul-mridha** [comment]
The problem was solved after changing the data-src attribute of <a></a> tag.. sorry it's my mistake.
