### ISSUE TITLE
Thumbnail class attribute

### ISSUE THREAD

**Issue by bkno** [sachinchoolur/lightGallery#1329]
## Summary

A way to specify a thumbnail class, or an automated media type class when populating entries through the `dynamicEl` attribute.

### Basic example

```
  'video' => '{..data..}',
  'thumb' => '..url..'
  'thumb_class' => 'video'
```
Alternatively, the output for the thumbnails has not just one class `lg-thumb-item` but a second one such as `lg-thumb-item-type-video`.

### Motivation

This would enable thumbnails to be styled differently based on media type. For example, in my use case I need to add a video icon over the video thumbnails in the CSS, but currently there is not a way to target just video thumbnails that I could see.

**Comment by sachinchoolur** [comment]
Hey @bkno,

This is a great suggestion. I'll include it in version 2.5.1
