### ISSUE TITLE
Thumbnail position problem

### ISSUE THREAD

**Issue by q112664** [sachinchoolur/lightGallery#1330]
In the case of more pictures, there will be a position error

<img  src="https://raw.githubusercontent.com/q112664/du/main/QQ%E5%9B%BE%E7%89%8720220627193335.png" />

**Comment by sachinchoolur** [comment]
Hey @q112664,

By default, lightGallery maintain the active thumbnails on the center of the page. 
Based o the screen size, the last image might not be completely visible. 

You can change this behavior by using the option `alignThumbnails`

Docs - https://www.lightgalleryjs.com/docs/settings/#thumbnails-plugin
