### ISSUE TITLE
On smartphone, we lose the display without thumbnail at each change of slide

### ISSUE THREAD

**Issue by VoltolRL** [sachinchoolur/lightGallery#1331]
Hello,

## Description
On smartphone when I click on the icon to remove the thumbnails and I go to the next slide the thumbnails come back. On desktop, the thumbnails do not come back.

### Steps to reproduce
On smartphone, open a lightbox
Click on the icon to remove the thumbnails.
Go to the next slide
=> KO the thumbnails come back

**Comment by sachinchoolur** [comment]
Hey @VoltolRL,

Thank you for reporting this issue. I'll push a fix in the next version
