### ISSUE TITLE
Thumbnail Not Working In IOS

### ISSUE THREAD

**Issue by akshayrathodar** [sachinchoolur/lightGallery#1334]
its working fine in Android and web but when you try to open thumbnail trey in IOS only one image displayed and it streched too much that creates  designing issue . let me share screen shot so we will get overview 

![WhatsApp Image 2022-07-06 at 4 23 38 PM](https://user-images.githubusercontent.com/51874167/177483459-4da896ff-3028-4b92-ba79-1a762f425440.jpeg)

its thumbnail trey related issue , hope i will get solution ASAP .

**Comment by sachinchoolur** [comment]
Hey @akshayrathodar,

Really sorry for the delayed response. This could be due to CSS conflict between your website and lightGallery.
Is it possible to share the website URL?
