### ISSUE TITLE
Getting Black screen after clicking the image/video

### ISSUE THREAD

**Issue by neerajnaswa** [sachinchoolur/lightGallery#1335]
Getting Black screen after clicking the image/video.Using this code:

`<div>
      <Head>
        <title>Create Next App</title>
      </Head>
      <h1>Lightgallery video loading test</h1>
      <div className="">
        <LightGallery
          onInit={onInit}
          plugins={[lgThumbnail, lgVideo]}
          mode="lg-fade"
          onHasVideo={(detail) => {
            console.log('detail', detail);
          }}
        >
          {(videos || []).map((video) => {
            return (
              <div
                key={video._id}
                className="gallery-item cursor-pointer"
                data-video={`{"source": [{"src": "${video.fileUrl}", "type":"video/mp4"}], "attributes": {"preload": false, "playsinline": true, "controls": true}}`}
                data-poster="https://www.lightgalleryjs.com/images/demo/html5-video-poster.jpg"
              >
                <Image src={randomImg} height={100} />
              </div>
            );
          })}
        </LightGallery>
      </div>
    </div>`

<img width="358" alt="Capture1" src="https://user-images.githubusercontent.com/47140686/177832682-1a57c3e0-657b-4db4-a3a0-18c72fe585de.PNG">

![image](https://user-images.githubusercontent.com/47140686/177832215-061ad3d3-0832-4ad4-bfef-0f59b8c32d94.png)
<img width="713" alt="Capture" src="https://user-images.githubusercontent.com/47140686/177832341-330e2637-e5df-4cbe-9929-e4a4c2889b14.PNG"

**Comment by sachinchoolur** [comment]
Hey @neerajnaswa,

Is it possible to provide a stackblitz demo?
