### ISSUE TITLE
non-0 left margin on body breaks zoom from origin effect

### ISSUE THREAD

**Issue by Lex-2008** [sachinchoolur/lightGallery#1338]
## Description

When a body has non-0 left margin set, "zoom from origin" effect misses the original image by this amount.

### Steps to reproduce

1. open an example codepen: https://codepen.io/sachinchoolur/pen/poebzpV
2. in "CSS" block, add this style to body: `margin: 100px;`
3. wait for lower block to reload :-)
4. click an image to open the gallery
5. close the gallery

You will see that the image "zooms out" and "zooms in" to a slightly wrong position - I believe it's 100px to the left.

### Environment

-   Browser and version - MS Edge (Chrome) 103, Firefox 102
-   OS - Linux (KDE on Manjaro)
-   lightGallery version - hmm, I guess it's 2.0.0-beta.3 on codepen, but I reproduced it locally with version 2.5.0.

**Comment by sachinchoolur** [comment]
Thanks, @Lex-2008!

I will add a fix in the next version.
