### ISSUE TITLE
Download button vertical alignment problem

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1339]
## Description

The Download button vertical alignment is incorrect

### Steps to reproduce

I exported the lightBox [codepen demo example](https://codepen.io/sachinchoolur/pen/poebzpV) and replaced all CDN links by modules from the  lightgallery | 2.5.0 | June 13th 2022 distribution., see [this demo gallery](https://www.andrewolff.nl/MyLightGalleryDemo_noCDN/).
If you open a slide page you see that the download button is shifted upwards.
You see it correctly in the original CodePen demo which uses CDN links.

I could correct it with the followin CSS code:

`#lg-download-1 {
    margin-top: 10px;
}`

or with
`.lg-toolbar .lg-icon {
    margin-top: 0px;
}`

Is there an error in the distributed version?

**Comment by sachinchoolur** [comment]
<img width="346" alt="Screenshot 2022-08-03 at 3 23 12 PM" src="https://user-images.githubusercontent.com/6586706/182580069-ec1ec12f-eb2b-44e1-b6ff-2d366c63623b.png">

Please remove the margin applied for button element. It should work fine

**Comment by acwolff** [comment]
@sachinchoolur you are correct, sorry to bother you with this!
