### ISSUE TITLE
How to set the video window to 4:3 instead 16:9?

### ISSUE THREAD

**Issue by q2apro** [sachinchoolur/lightGallery#134]
From my testing I think all videos loaded are 16:9. However, my videos are 4:3 (640 px * 480 px).

How can I change the video size?

In the [docs](http://sachinchoolur.github.io/lightGallery/settings.html) I only found `videoMaxWidth`...

**Comment by q2apro** [comment]
The issue could be solved with the answer to the question: How to set the video size (width and height) with lightGallery?

**Comment by q2apro** [comment]
Seems that I cannot even set the iframe size using: 

	$("iframe").attr("width", "200");

or

	$("iframe").width(200);

No effect on the screen.

**Comment by q2apro** [comment]
All right, I could solve this by changing the **CSS** only, width from 100% to 70% and left from 0% to 15% so that the video is still centered:

    #lg-slider .video .object {
        width: 70% !important;
        height: 100% !important;
        position: absolute;
        top: 0px;
        left: 15%;
    }

However, I also have few videos that are 16:9. Now the question is how I can assign different video size classes to them?!

**Comment by q2apro** [comment]
I am one step closer to the solution:

In HTML I add the class "widescreen" to the selector element that triggers the video box of lightGallery. 

Then I use:

**CSS:**

	#lg-slider .video .object {
		width: 70% !important;
		height: 100% !important;
		position: absolute;
		top: 0px;
		left: 15%;
	}
	.widescreenclass {
		width: 100% !important;
		height: 100% !important;
		position: absolute;
		top: 0px;
		left: 0;
	}

**JS:**
		onOpen: function(el) { 
			checkForWidescreen(el);
		},

		function checkForWidescreen(el) { 
			// console.log(el);
			// console.log(el[0].innerHTML);
			if( *** check for class .widescreen ***) {
				$('#lg-slider .video .object').addClass('widescreenclass');
				$('#lg-slider .video .object').removeClass('object');
			}
		}

*** How can I find out if the element that is bound to the video has class ".widescreen"?

**Comment by q2apro** [comment]
This is my latest solution - it feels not "proper" but works in Firefox and Chrome: 

**1. HTML**

	<li id="li_X01" class="vitem xtr odd">
		<span class="lesson">Tutorial</span>
		<a class="popup2 widescreen" href="#" data-src="//www.youtube.com/watch?v=_OSjWC93gVI" data-exthumbimage="thumbs/X01.png" data-sub-html="#X01">
			<img src="thumbs/X01.png">
		</a>
		<div class="descr">
			Dies ist ein kurzes Tutorial ...
			<div class="custom-html">					
				<span class="iswidescreen"></span>
			</div>
		</div>
	</li>


**2. CSS**

	/* for 4:3 videos format */
	#lg-slider .video .object {
		width: 70% !important;
		height: 100% !important;
		position: absolute;
		top: 0px;
		left: 15%;
	}
	/* for 16:9 videos format */
	.widescreenclass {
		width: 100% !important;
		height: 100% !important;
		position: absolute;
		top: 0px;
		left: 0;
	}

**3. JS**

		$('#videoliste').lightGallery({
			preload:0, // saves bandwidth for videoload
			thumbnail: false,
			exThumbImage: 'data-exthumbimage',
			selector: '.popup2',
			videoAutoplay: true,
			lang: { allPhotos: 'Alle freien Videos' }, 
			youtubePlayerParams: {
				enablejsapi:1,
				showinfo:1,
				wmode: 'opaque',
				modestbranding:1,
				iv_load_policy:1,
				rel:0,
				vq:'large',
			},
			onSlideNext: function(el) { 
				pauseAllYoutube();
				checkForWidescreen(el);
			},
			onSlidePrev: function(el) { 
				pauseAllYoutube();
				checkForWidescreen(el);
			},
			onSlideBefore: function(el) { 
				pauseAllYoutube();
				checkForWidescreen(el);
			},
			onSlideAfter: function(el) { 
				pauseAllYoutube();
				checkForWidescreen(el);
			},
			onOpen: function(el) { 
				checkForWidescreen_onopen(el);
			},
		});
		
		function pauseAllYoutube() { 
			$('iframe[src*="youtube.com"]').each(function() {
				var iframe = $(this)[0].contentWindow;
				iframe.postMessage('{"event":"command","func":"pauseVideo","args":""}', '*');
			}); 
		}

		function checkForWidescreen_onopen(el) { 
			var html = (el['context']['activeElement'].outerHTML);
			if (html.indexOf('widescreen') > -1) {
				// wait 1s so that video content gets loaded, then change video size
				setTimeout(function() { 
					$('#lg-slider .video .object').addClass('widescreenclass');
					$('#lg-slider .video .object').removeClass('object');
				}, 500);
			}
		}
		function checkForWidescreen(el) { 
			// get customhtml of current element
			var customhtml = $('.lg-slide.current').find('.custom-html').html();
			console.log(customhtml);
			if (customhtml.indexOf('iswidescreen') > -1) {
				$('#lg-slider .video .object').addClass('widescreenclass');
				$('#lg-slider .video .object').removeClass('object');
			}
		}

**Comment by sachinchoolur** [comment]
Hi,
You can use `videoMaxWidth` for defining the width of the video and change the padding-bottom of `.lg-vodeo` in (new version) for changing the height of the video..

``` css
.lg-outer .lg-video {
    height: 0;
    overflow: hidden;
    padding-bottom: 56.25%; // for 16:9 videos
    position: relative;
    width: 100%;
}
```
