### ISSUE TITLE
How to update the slideShowInterval?

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1340]
I am new here and try to use the lightGallery library with the following code.
I initialize the gallery at the end of the $(document).ready(function() by calling a function  initLightGallery():

```
var viewtime = 5000;

const lg = document.getElementById("thumbsgallery");

let plugin = null;

function initLightGallery() {

    console.log("initLightGallery");
    plugin = lightGallery(lg, {       
            autoplayFirstVideo: false,
            slideShowInterval: viewtime,
            speed: 500,
        }
    )
}
```

This works OK as you can see in [this test album](https://andrewolff.jalbum.net/LG__JustifiedGallery/)

The slide show interval time is fetched from the variable viewtime which is copied to the setting slideShowInterval in the initLightGallery function which is called only once if you open the album.
However you can change the interval time by clicking the settings button in the upper right corner of the index page with the combo box after the text 'Viewing time'. If you close the settings window by clicking the close button, the contents of variable viewtime  is updated.
My question is:
Which code should I use the new value if I open the lightbox?
Is that possible to do that in the event onBeforeOpen?

The next code failed:
```
lg.addEventListener('lgBeforeOpen', (event) => {
    slideShowInterval: viewtime,
    console.log('onBeforeOpen');
});
```

**Comment by sachinchoolur** [comment]
You need to destroy the current lightGallery instance and re-initiate it after changing the `viewtime ` value

```js
var viewtime = 5000;

const lg = document.getElementById("thumbsgallery");

let plugin = null;

function initLightGallery() {

    console.log("initLightGallery");
    plugin = lightGallery(lg, {       
            autoplayFirstVideo: false,
            slideShowInterval: viewtime,
            speed: 500,
        }
    )
}


// after changing viewtime
plugin.destroy();
initLightGallery()
```

Let me know if you face any issues

**Comment by acwolff** [comment]
Thanks for your quick response, but sadly your solution does not work. 
After I click the close button of the settings window, the lightbox in no longer opened if I click on a thumbnail.

You can try it yourself with [the test album](https://andrewolff.jalbum.net/LG__JustifiedGallery/).

Is it not possible to update a parameter in an event, for instance the  lgAfterOpen event?

**Comment by sachinchoolur** [comment]
Ok, Please follow the second method. 

It is not currently possible to pass parameters via events to the gallery. It is one-way communication.

Using the destroy method is the best option to re-initialize ligthGallery with new settings.

You can change any settings this way.
