### ISSUE TITLE
No sound for videos

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1343]
If I run the codepen [lightGallery videos](https://codepen.io/sachinchoolur/pen/ExXxqPe) example on my Windows 10 PC or my iPad, I hear no sound. 

For the first youtube video I can switch on the sound with the load-speaker icon in the leftrlower corner, but I like to hear the sound automatically, as is the case if I play it directly on the youtube site by clicking the download button.

For the second Vimeo video I hear no sound and I see no button to switch the sound on. But if I click the download button, I hear the sound of that video. Only on my iPhone I see shortly a sound button.

Also in my own [test album](https://andrewolff.jalbum.net/LG__JustifiedGallery/) I hear no sound the YouTube and Vimeo videos, only the local mp4 videos play sounds.

Is this a bug or should I use special code to hear the video sound tracks?

**Comment by sachinchoolur** [comment]
Most environments don't allow you to autoplay videos without any user interaction. It depends on many scenarios, OS, and browsers.

Only practical way to autoplay video is by muting the audio. 

You can read more about this from the following link - https://www.lightgalleryjs.com/demos/video-gallery/#video-autoplay

Let me know if you have any questions

**Comment by acwolff** [comment]
Thanks again for your quick response and your awsome library!

The autoplay function works fine, even on my iPad and iPhone as you can see in [my test album](https://andrewolff.jalbum.net/LG__JustifiedGallery/), only the sound does not start.

**Comment by sachinchoolur** [comment]
Closing as resolved

**Comment by acwolff** [comment]
> Closing as resolved

??? The problem is not solved, there is no sound!
