### ISSUE TITLE
Problem with auto-played videos in slide-shows

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1344]
If a slide show is active and a video is started automatically, there is a problem with videos which have a longer play time as the slide-show interval. You can test this in [my lightGallery test album](https://andrewolff.jalbum.net/LG__JustifiedGallery/).

If the video play time is longer as the slide-show time interval, the video is replaced by the sext slide at the end of the slide-show interval.

This is incorrect, the slide-show should stop until the end of the video or until the video is stopped by the user and continue next to the next slide.

Could you please implement this?

**Comment by sachinchoolur** [comment]
This is not possible at the moment. And it requires some effort to implement.

I'll consider adding if we get more requests
