### ISSUE TITLE
Settings  loop and  hideControlOnEnd do not work correctly

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1347]
## Description

With setting
            loop: false
            hideControlOnEnd: true,
a slideshow continues after the last slide to the first slide and at the last slide the next slide button is not hidden

### Steps to reproduce

To see it start a slideshow with [my test album](https://andrewolff.jalbum.net/LG_JustifiedGallery/)

### JS code that you use to initialize lightGallery.

```js
const lg = document.getElementById("thumbsgallery");

let plugin = null;

function initGallery() {
    console.log("initGallery");
    plugin = lightGallery(lg, {       
            autoplayFirstVideo: true,
            autoplayVideoOnSlide: true,
            slideShowInterval: viewtime,
            loop: false,
            hideControlOnEnd: true,
            speed: 500,
            pager: false,
            getCaptionFromTitleOrAlt: false,
            appendSubHtmlTo: ".lg-sub-html", // caption onder image
            mode: transeffect,
            allowMediaOverlap:  false,
            download: true,
            thumbnail: true,
            toggleThumb: true, 
            showCloseIcon: true, 
            plugins: [
            lgZoom, 
            lgFullscreen,
            lgAutoplay,
            lgThumbnail,
            lgHash,
            lgVideo
            ],
            mobileSettings: {
              controls: true, 
            }
        }
    )
};

```

### Sample HTML markup

```html
<div id="thumbsgallery" class="thumbs-jg" >

<a class="gallery-item" id="s0"
 href="slides/Vecht_121027_1156.jpg" 
data-lg-size="1920-1440"
data-sub-html= 'Start aan de Grote Esweg.'>
<img     src="thumbs/Vecht_121027_1156.jpg"
  width="160" height="120" alt="1: Vecht_121027_1156<br>Start aan de Grote Esweg." title="1: Vecht_121027_1156<br>Start aan de Grote Esweg." />
</a>

<a class="gallery-item" id="s1"
 href="https://private-sharing.wistia.com/medias/mwhrulrucj"  data-lg-size="1920-1080"
 data-iframe="true"
data-sub-html= 'Wistia video in iframe'>
<img     src="thumbs/private-sharing.wistia.com-119.jpg"
  width="213" height="120" alt="2: private-sharing.wistia.com-119<br>Wistia video in iframe" title="2: private-sharing.wistia.com-119<br>Wistia video in iframe" />
</a>
</div>
```

### Environment

-   Browser and version -  Google Chrome Versie 103.0.5060.134 (Officiële build) (64-bits)
-   OS -  Windows 10
-   lightGallery version -  2.5.0 | June 13th 2022

**Comment by sachinchoolur** [comment]
Looks like it is working fine on your website.

If you don't want the animation after reaching the first/last slide, you can turn off this by using the option `slideEndAnimation`

**Comment by acwolff** [comment]
> Looks like it is working fine on your website.

Sorry, @sachinchoolur I don't understand how you can say that!

Your documentattion says:

hideControlOnEnd 	boolean	false
If true, prev/next button will be hidden on first/last image.

But if I go to the [last slide of my test album](https://andrewolff.jalbum.net/LG_JustifiedGallery1/#lg=1&slide=34), I still see the next arrow button!
