### ISSUE TITLE
How detect an active slideshow and to stop the slideshow?

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1349]
If the viewer clicks a special button like the 'Show /HideEXIF data (camera settings)' and a slideshow is active, this slideshow should be paused so that the viewer can read all information and the information is not removed by the next slide.
See [this example album](https://andrewolff.jalbum.net/LG_JustifiedGallery/) to see why I need this information.

To implement this I need next information:

1. How can I detect whether a slideshow is active?
2. If the slide show is active, which code should I use to pause the slideshow?

Thanks in advance for your information!

Is there also an function to continue the slideshow after it is paused?

**Comment by sachinchoolur** [comment]
Hey @acwolff,

At the moment, option to start and stop autoplay programmatically is not possible.

**Comment by acwolff** [comment]
> At the moment, option to start and stop autoplay programmatically is not possible.

OK, but is there also no way to see whether a slide show (or video) is playing?
It would be nice if I could listen to an event if the slide show / video is started and another event if it is stopped.

Anyhow, thanks for your answer and your awsome library!
