### ISSUE TITLE
How to pass an attribute to each video object in lightgallery? OR: Access `data-sub-html` from within `el`?

### ISSUE THREAD

**Issue by q2apro** [sachinchoolur/lightGallery#135]
I am proceeding with this issue https://github.com/sachinchoolur/lightGallery/issues/134 and just need to know how I can pass a "flag" to the video object. 

Say we have this HTML: 

	<li id="li_X01" class="vitem xtr">
		<span class="lesson">Tutorial</span>
		<a class="popup2 widescreen" href="#" data-src="//www.youtube.com/watch?v=_OSjWC93gVI" data-exthumbimage="thumbs/X01.png">
			<img src="/thumbs/X01.png" />
		</a>
	</li>

And I want to check on all lightgallery navigation event callbacks (or open event) if the widescreen class is present. 

I could also imagine to pass "widescreen" like that: 

		<a data-videosize="widescreen" class="popup2 widescreen" href="#" data-src="//www.youtube.com/watch?v=_OSjWC93gVI" data-exthumbimage="thumbs/X01.png">

How would I then read-in the `data-videosize` attribute from within the event callbacks? 

---

I could also use the `data-sub-html` and search "widescreen" within this string. But how can I access `data-sub-html` from within `el`?

**Comment by sachinchoolur** [comment]
Hi,
In new version you can access all variables of lightgallery via object data attribute..
All the gallery elements will be store in $items.. You can refer the code bellow and let me know if you have any doubts..
ex: 
``` html
<ul id="lg">
    <li data-videosize="widescreen" id="li_X01" class="vitem xtr">
       <span class="lesson">Tutorial</span>
        <a class="popup2 widescreen" href="#" data-src="//www.youtube.com/watch?v=_OSjWC93gVI" data-exthumbimage="thumbs/X01.png">
            <img src="/thumbs/X01.png" />
        </a>
    </li>
<ul>
```
``` javascript

  var $lg = ('#lg');
   $lg.lightGallery();
   $lg.on('onBeforeSlide.lg', function(event, prevIndex, index) {
        console.log($methods.data('lightGallery').$items.eq(index).attr('data-videosize'))
   });
```
