### ISSUE TITLE
How to add a function to the slide image click event?

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1353]
If you use a  transition like lg-rotate, you see this transition if you start a slide show or if you click the next / previous arrow button.
 However if you use on a mobile device a left or right swipe, you don't see the transition as you can see in [my test album](https://andrewolff.jalbum.net/LG_JustifiedGallery1/).

So my first question is:

Is it possible to show also with swipes transitions?

Because the arrow buttons are on mobile devices are very small or even absent, I tried to use the click function for the image to get a transition to the next slide:

```
lg.addEventListener('lgAfterOpen', (event) => {
    document.querySelector('#lg-inner-1').addEventListener('click', function() {
        plugin.goToNextSlide();
    });
});
```

This works, but I have a problem if I click in the area outside the image.
To prevent that I added setting 

     closeOnTap: false,

But of course I can now no longer close the lightbox by clicking in the area outside the image. 

So my second question is:

What argument should I use in the querySelector to select only the image?

**Comment by sachinchoolur** [comment]
No, at the moment, it is not possible. 

But, yes, you can increase the size of the next and previous buttons. 

By default, next and previous buttons are invisible on mobile devices 
You can enable them by using the option [`mobileSettings`](https://www.lightgalleryjs.com/docs/settings/#mobileSettings)
