### ISSUE TITLE
Thumbnails plugin image in bottom bar not have alt

### ISSUE THREAD

**Issue by hapo-hoangnh** [sachinchoolur/lightGallery#1354]
i want add alt in Thumbnails image when popup show. is this possible?

**Comment by sachinchoolur** [comment]
Hey @hapo-hoangnh,

May I know the usecase? Alt tag is already applied for the main images.
Do you want to set different alt tags for thumbnails?

**Comment by hapo-hoangnh** [comment]
@sachinchoolur yes, i want set different alt tags for thumbnails  in bottom bar.
also, there is a bug when using Infinite scrolling and the Thumbnail plugin. Every time load more, all thumbnails will be loaded again.
Example: Infinite scrolling in page 10 will reload all Thumbnail images from page 1 to page 10
that consumes a lot of bandwidth.
