### ISSUE TITLE
How to get the caption in the lgBeforeSlide event?

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1356]
I did implement your side panel implementation for the slide caption, see [this album](https://andrewolff.jalbum.net/LG_JustifiedGallery1/), but your example shows an empty side panel if there is no caption.

So I like to hide the side panel if the caption length is 0. To implement this, I have to fetch the caption in the lgBeforeSlide event.

I tried this:

```
lg.addEventListener('lgBeforeSlide', (event) => {
    const { index, prevIndex } = event.detail;
    slide_index = index;
    console.log('onBeforeSlide: slide_index, prevIndex=' + slide_index, prevIndex);
    console.log(this.dataset.sub-html);
    emptyCaption= (this.dataset.sub-html.length === 0)
    refreshSidePanel(emptyCaption);
});
```

but that does not work, so my question is:

How to get the caption in the lgBeforeSlide event?

**Comment by sachinchoolur** [comment]
Yes, you can access `galleryItems` via plugin instance and get the subHTML value.

```js
const lg = document.getElementById('gallery')
let gallery;

lg.addEventListener('lgBeforeSlide', (event) => {
    const { index } = event.detail;
    const caption = gallery.galleryItems[index].subHtml;
});
gallery = lightGallery(lg)

```

**Comment by acwolff** [comment]
Yes @sachinchoolur that works perfect, see [my test album](https://andrewolff.jalbum.net/LG_JustifiedGallery1/) where you can see that the side panel is removed if there is no caption.

Thanks again for your help!
