### ISSUE TITLE
How to dynamically populate gallery with VUE 3 composition api

### ISSUE THREAD

**Issue by allaghi** [sachinchoolur/lightGallery#1357]
Hello ,
Have a nice day,
I am wondering how can I populate dynamically gallery using  vue 3 composition api

Thanks in advance.

**Comment by TMadzi** [comment]
Did you have any luck?

**Comment by allaghi** [comment]
> Did you have any luck?
> 

Not yet

**Comment by IthJ** [comment]
Hey there! I was able to get it working with Composition API and wanted to share a step-by-step solution that worked for me. Hopefully, it works for you too:

**Install and Import:** After installing, import the Lightgallery component directly like this: import Lightgallery from 'lightgallery/vue/LightGalleryVue.umd.js';

**Template Usage:** Include the Lightgallery component in your template. Wrap your nuxt-img component with a div element.

**Data Source:** Ensure you set the data-src attribute on the div or whichever child element you plan to use within Lightgallery.

**Image Source:** Make sure to set the src attribute of the a tag and the img tag. These should point to the location of the images you intend to display.

Code Example: 
```
<script>
import Lightgallery from 'lightgallery/vue/LightGalleryVue.umd.js';
... Code to retrieve your images here ...
const onBeforeSlide = (detail) => {
  const {index, prevIndex} = detail;
  console.log(index, prevIndex);
};
</script>
<template>
     <Lightgallery
          :onBeforeSlide="onBeforeSlide"
      >
        <div v-for="image in GalleryImages" class="pb-1" :key="image.id"
             :data-src="<link to your image here>">
          <a :href="<link to your image here>">
            <nuxt-img
                :id="image.id"
                :src="<link to your image here>"
                :alt="image.name"
            />
          </a>
          <p v-if="image.description" class="text-md lg:text-2xl py-2 text-left">
            {{ image.description }}
          </p>
        </div>
      </Lightgallery>
</template>
```

If you're still having issues, I'd recommend understanding the console errors that Lightgallery throws to get your setup working right. Best of luck!
