### ISSUE TITLE
Bug: thumbs div stays static (does not animate) when auto is set and when using dynamicEl.

### ISSUE THREAD

**Issue by steveunit** [sachinchoolur/lightGallery#136]
Only discovered this when I added more images than can fit in the browser window.

Now, if I set auto (play) and start LightGallery on the 10th image, it will load with the 10th thumb close to the centre. The next thumb is highlighted when the next image is called, but the thumbs row stays static, until the thumb for the current image can't be seen because it is beyond the right edge of the browser window.

I fixed this by adding the following code to the end of the slide function, on or around line 750.

    if ($gallery.hasClass('open')) {
        $this.animateThumb(index);
    }

I am passing an index to LightGallery for the start image.

Is there a better fix?

Thanks for the plugin.

**Comment by steveunit** [comment]
I had better point out that I am using dynamicEl and setting an index for each thumb.

**Comment by sachinchoolur** [comment]
Hi,
I have release lightgallery version 1.2.0
I have completely re-written the plugin .. Please check this issue and re-open if it exists in new version also ..

**Comment by gudies** [comment]
please my gallery does not slide automatically ..please help


$('#man').on('click', function (e) {
        e.preventDefault();

        //$("#pk").click();
        $("#pv").click();

       // loadKay().play()

        $lg = $(this).lightGallery({
            mode: 'fade',
            speed: 400, //ms'
            dynamic: true,
            thumbnail: true,
            animateThumb: true,
            showThumbByDefault: true,
                auto: false,
                loop: true,
               pause: 2000,
            dynamicEl: [
                {
                    "src": 'images/2.jpg',
                    'thumb': 'images/2.jpg',
                },
                {
                    "src": 'images/3.jpg',
                    'thumb': 'images/3.jpg',
                },
                {
                    "src": 'images/5.jpg',
                    'thumb': 'images/5.jpg',
                },{
                    "src": 'images/0.jpg',
                    'thumb': 'images/0.jpg',
                },
            ]

                
        })

        $lg.on('onCloseAfter.lg', function (event) {
            stopPlackBack()//stop();
        });
