### ISSUE TITLE
React 18 Compatibility 

### ISSUE THREAD

**Issue by fnej** [sachinchoolur/lightGallery#1364]
## Description
I was wondering if the gallery works with React 18, since it's not working for me.

**Comment by sachinchoolur** [comment]
Hey @fnej,

Yes, there was an issue with react 18 strict mode. 

This has been fixed in version [2.6.0-beta.2](https://github.com/sachinchoolur/lightGallery/releases/tag/2.6.0-beta.2)

**Comment by seanhealy** [comment]
Nice to see this fixed! Any idea when it will hit a proper release?
