### ISSUE TITLE
How can I open an image zoomed to actual size?

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1365]
For panoramic pictures, I like to open the image in such a way that the viewer can pan immediately through the panorama, so it should be displayed at its maximum size.

Is this possible?
If yes what code should I use to get this done?

**Comment by SantoshKumarRavi** [comment]
when I **click** to the download icon on **top right side**, it moves to the new window. when **linking** _on button click events_ on the image to the download icon leads the image open in new window.

**Comment by acwolff** [comment]
But I want to open the image zoomed in the Lightbox, not in a new window.

**Comment by acwolff** [comment]
This code works:

```
lg.addEventListener('lgAfterSlide', (event) => {    
    $('#lg-actual-size-1').trigger("click");
});
```
but only if the image is selected as next slide,  it is not working if you open it from the thumbnail on the index page.
