### ISSUE TITLE
Not working with Next.js

### ISSUE THREAD

**Issue by moayadcodes** [sachinchoolur/lightGallery#1367]
## Description

I installed lightGallery with Next.js but the lightbox doesn't open when I click to open it. I see there is a warning in the console that says license key is not valid, but I am not using it on a live website, I am testing locally.

### Steps to reproduce

- Install Next.js and lightGallery
- Add lightGallery to page as per docs

### Code

```jsx
import LightGallery from 'lightgallery/react';
import 'lightgallery/css/lightgallery.css';

export default function TestPage() {
  const projects = [...];

  return (
    <LightGallery selector=".project-button">
      <div>
        {projects.map((project) => (
          <button key={project.id} className="project-button" type="button" data-src={project.src}>
            <figure>
              <div>
                <Image src={project.thumb} alt="" layout="fill" />
              </div>
              <figcaption>{project.desc}</figcaption>
            </figure>
          </button>
        ))}
      </div>
    </LightGallery>
  );
}
```

### Environment

-   Browser and version - Chrome 104.0.5112.81
-   OS - Windows 10
-   Next.js version - 12.2.4
-   lightGallery version - 2.5.0

**Comment by sachinchoolur** [comment]
Hey @moayadcodes,

Which version of React are you using? 
if you're using React 18 with strict mode, please use lightGallery version [2.6.0-beta.2](https://github.com/sachinchoolur/lightGallery/releases/tag/2.6.0-beta.2)

It is safe to use in production. Will be releasing a stable version in a few days

**Comment by moayadcodes** [comment]
That fixed it for me. I am using React 18. Is there an ETA for when v 2.6 will be released?

**Comment by sachinchoolur** [comment]
By this weekend

**Comment by ecosse3** [comment]
Does lightgallery support SSR with Next.js and optimizations via Next Image Component?
