### ISSUE TITLE
Setting alignThumbnails is not working

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1369]
## Description

The alignment of the thumnails via setting  alignThumbnails : "left", or "alignThumbnails : right", is not working.
The thumbnails are always positioned below the slide image.

### Steps to reproduce

See codepen  https://codepen.io/acwolff/full/WNzaOba

**Comment by sachinchoolur** [comment]
These options will work only if the width of all thumbnails combined is less than the gallery's width.

**Comment by sachinchoolur** [comment]
I'll update the docs

**Comment by acwolff** [comment]
@sachinchoolur I thought that "left" means _**Thumbnails vertical at the left side of the lightbox**_ but that is apparantly incorrect.
