### ISSUE TITLE
Bug: next thumb/image will always be at index 1 when auto is set and when using dynamicEl.

### ISSUE THREAD

**Issue by steveunit** [sachinchoolur/lightGallery#137]
I set an index for each thumb when using dynamicEl. If auto (play) is set, LightGallery will load with the correct image and highlighted thumb. The next image is always the image with index == 1. A possible fix for this is to reset the index value in the init function. 

I replaced line 87:

    index = 0;

with:

    if (settings.index) {
        index = settings.index;
    } else {
        index = 0;
    }

which seems to do the trick. Is there a better fix?

Thanks for the plugin.

**Comment by sachinchoolur** [comment]
I have release lightgallery version 1.2.0
Please check this issue and re-open if it exists in new version also ..
