### ISSUE TITLE
What is parameter scale doing?

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1370]
I tried various values for setting 'scale', but I see no effect at all  if I click the zoom button or do a double click.

What is this setting doing, what should I see if I change the value?

I use setting  **actualSize: true,**  is that the reason that I see no effect?

**Comment by sachinchoolur** [comment]
If you turn on `showZoomInOutIcons`, lightGallery will display additional zoom-in and zoom-out buttons. `scale` option is for setting up the zoom value for these two buttons. 

I'll update the docs.

**Comment by acwolff** [comment]
Ok thanks for your explanation.
