### ISSUE TITLE
Next / previous button not working with overlapping caption.

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1371]
## Description

If the caption panel is so large that it overlaps the Next and Previous button ,
you can no longer use these buttons to go to the next or previous slide.
### Steps to reproduce
To see this bug open codepen https://codepen.io/acwolff/full/NWYOaPp

There is an easy fix:

```
.lg-next,
.lg-prev {
    z-index: 1100;   /* r
}
```

but I think the core software should fix this.

**Comment by sachinchoolur** [comment]
Fixed in version 2.6.0
