### ISSUE TITLE
Please implement also slide transitions if swipes are used

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1372]
Normally I hide the next / previous arrow buttons on a mobile device, but if I do that with the LightGallery lightbox, you will never see slide transitions, because these are absent if you use swipes to go to the next image.

So my request is:

Please implement also slide transitions if swipes are used on mobile devices.

**Comment by sachinchoolur** [comment]
Slide transition works on mobile devices. Could you please share a video of the issue?

**Comment by acwolff** [comment]
@sachinchoolur I don't think you need a video, just open [this codepen](https://codepen.io/acwolff/pen/MWVzMPN) on a mobile device.
If I open it with my iPhone and swipes to the next image, I see a slide transition if I do the same action with theright arrow button I see a rotate transition.

**Comment by sachinchoolur** [comment]
At the moment, only the slide transition works with swipe action. Other transition effects work only by pressing the controls or using keyboard navigation.
