### ISSUE TITLE
error opening an image or WEBP file

### ISSUE THREAD

**Issue by EnzoRimapa** [sachinchoolur/lightGallery#1374]
## Description

I try to open an image or WEBP file but the program does not open the file, it is as if I opened the program independently without any file.

### Environment

- WINDOWS 11

**Comment by sachinchoolur** [comment]
Hey @EnzoRimapa,

Please provide an isolated codepen demo or share the HTML and JavaScript code that you use to initialize lightGallery

**Comment by EnzoRimapa** [comment]
@sachinchoolur 
hello I am using the version for windows computer
