### ISSUE TITLE
Sometimes gallery fails to activate

### ISSUE THREAD

**Issue by hudvin** [sachinchoolur/lightGallery#1375]
I am trying to add lightGallery to my site (github pages, jekyll based) - <http://localhost:4000/2022-08-17/random-gallery>
Sometimes gallery just doesn't work. Grid of images is shown, but nothing happens if i click on image. Sometimes I have to refresh 5-10 times to get it work. No errors in log.
My observations:
1) I have AdBlock and Ghostery installed
2) I have GA code on page.

Chrome(Ubuntu):
If I disable Ghostery, lightgallery works almost always.
It also works better in incognito mode.

Firefox(Ubuntu): 
doesn't work in most cases. No extension are installed.

Brave(Android): seems ok.

Looks like this behavior somehow related to Ghostery and GA code.

**Comment by hudvin** [comment]
Looks like

  .on("jg.complete", function () 

is not called sometimes.

**Comment by sachinchoolur** [comment]
Hey @hudvin,

Please share the JavaScript and HTML code that you use to initialize lightGallery.

**Comment by hudvin** [comment]
oh, sorry. I posted localhost url :D Here is it https://vadym.bartko.me/2022-08-17/random-gallery

Code from that page:

    <script>
    
    
    jQuery("#animated-thumbnails-gallery")
      .justifiedGallery({
        captions: false,
        lastRow: "nojustify",
        rowHeight: 220,
        margins: 5,
        waitThumbnailsLoad: true
      })
      .on("jg.complete", function () {
        alert("done")
        window.lightGallery(
          document.getElementById("animated-thumbnails-gallery"),
          {
    
    
            galleryId: "nature",
            plugins: [lgThumbnail, lgFullscreen],
    
            toggleThumb: true,
            allowMediaOverlap: true,
    
            fullScreen: true,
    
      	    showCloseIcon: true,
      	    download: false,
    
            mobileSettings: {
              controls: false,
              showCloseIcon: false,
              download: false,
              rotate: false
            }
    
          }
        );
      });
    
    </script>

**Comment by sachinchoolur** [comment]
I tested this on multiple devices and browsers, and it works fine for me.

It could be the issue with the AdBlocker you are using. Which is not in our hands :(
