### ISSUE TITLE
SrcSets in a dynamic mode structure

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1376]
I could implement SrcSets for an album with a thumbnails index page, see https://github.com/sachinchoolur/lightGallery/issues/1359

However now I like to implement that album without an index page by using a dynamic mode structure.

How should I translate this

```
<a class="gallery-item" id="s0" 
 href="slides/Vecht_121027_1156.jpg"
data-lg-size= "720-540-720, 1440-1080-1440, 1440-1080-1440, 2880-2160-2880, 3024-4032"
 data-srcset="slides/Vecht_121027_1156-4032w.webp 4032w,slides/Vecht_121027_1156-2880w.webp 2880w,slides/Vecht_121027_1156-1440w.webp 1440w,slides/Vecht_121027_1156.jpg 1440w,slides/Vecht_121027_1156-720w.webp 720w" 
 data-sub-html= 'Comment 1'>
<img     src="thumbs/Vecht_121027_1156.jpg"
  width="213" height="160" alt="Comment 1" title="Comment 1" />
</a>

```
in a dynamic mode element?

I tried this:

```
var items = [
    {
  subHtml: '<strong>Title -1</strong><br>Comment 1<br>Keywords:&nbsp;Almelo, Erfgoedroute',
        responsive: "slides/Vecht_121027_1156-4032w.webp 4032w,slides/Vecht_121027_1156-2880w.webp 2880w,slides/Vecht_121027_1156-1440w.webp 1440w,slides/Vecht_121027_1156.jpg 1440w,slides/Vecht_121027_1156-720w.webp 720w"
    },
    {
        subHtml: '<strong>Title - 2</strong><br><audio controls autoplay  title=" ROYALTY FREE MUSIC by BENSOUND "  data-id="a1" controlsList="nodownload"><source src="slides/03%20-%20Allegro.mp3"> </audio><br>Example of an added audio clip<br>Check the check-box <br>&#39;Start the music automatically&#39; on the &#39;Music&#39; settings tab, <br>if the music should start automatically on a PC.<br>Keywords:&nbsp;Erfgoedroute, Vecht',
        responsive: "slides/Vecht_121027_1205-2_130930_1355-2923w.webp 2923w,slides/Vecht_121027_1205-2_130930_1355-2063w.webp 2063w,slides/Vecht_121027_1205-2_130930_1355-1032w.webp 1032w,slides/Vecht_121027_1205-2_130930_1355.jpg 1032w,slides/Vecht_121027_1205-2_130930_1355-516w.webp 516w"

    },
    {
        subHtml: '<strong>Bibliotheek</strong><br>Library <a href="javascript:toggleMore()"><div class="triggerMoreInfo" >more info>></div></a><div onClick="javascript:toggleMore()" id="c2" class="moreInfo"><h1>The Library</h1>The architect has tried to counteract the rigorous design of the former Town Hall, which is oblique with this playful building. <br><br>The building has two parts. The largest space of the building lies like a fish body along the Beacon. It is an elongated section that follows the curvature of the tail. A smaller space is like a fiery fish tail along the Touwbaan. The building&#39;s main façade is largely built of ultramarine blue glass just like the northern headland. The roofing is made of zinc.</div><br>Keywords:&nbsp;Almelo, Erfgoedroute',
        responsive: "slides/170814-133457_Erfgoedroute-4320w.webp 4320w,slides/170814-133457_Erfgoedroute-2880w.webp 2880w,slides/170814-133457_Erfgoedroute-1440w.webp 1440w,slides/170814-133457_Erfgoedroute.jpg 1440w,slides/170814-133457_Erfgoedroute-720w.webp 720w"
    },

```
But this shows the same  first image on both my large monitor and on my iPhone.

**Comment by acwolff** [comment]
I replaced 'responsive' by 'srcset' and now it works!!

I think a lot is missing in the documentation!

**Comment by acwolff** [comment]
> Also, please make sure that the image loaded on your iPhone is larger than the screen resolution.
My iPhone properties:
screen.width 390
screen.height: 844
window.devicePixelRatio: 3

Please give me advice:
I use too a srcset for the thumbs, how can I indicate that?

**Comment by sachinchoolur** [comment]
At the moment, lightGallery thumbnails don't support responsive images as they are already low in size.

Could you please make sure the `1440x1080` size image is resized if you open it directly on a webpage(without lightGallery)

And looks like the link you've shared is not working.  please provide an isolated codepen demo if possible.

**Comment by acwolff** [comment]
@sachinchoolur  sorry for the wrong link, [this is the test album](https://andrewolff.jalbum.net/LG_CarouselSrcSet).

For the first slide image, the next images are available:

Vecht_121027_1156.jpg                 1440x1080
Vecht_121027_1156-720w.webp       720x540
Vecht_121027_1156-1440w.webp 1440x1080 (this is resized on my 2560x1440  monitor, so that the full height is used)
Vecht_121027_1156-2880w.webp 2880x2160
Vecht_121027_1156-4032w.webp 4032x3024

and the next code is used:

```
var items = [
  {
    subHtml: '<span class= "title">Comment 1</span>',
    src: 'slides/Vecht_121027_1156.jpg', 
    srcset: "slides/Vecht_121027_1156-4032w.webp 4032w,slides/Vecht_121027_1156-2880w.webp 2880w,slides/Vecht_121027_1156-1440w.webp 1440w,slides/Vecht_121027_1156.jpg 1440w,slides/Vecht_121027_1156-720w.webp 720w", 
    sizes:  "720-540-720, 1440-1080-1440, 1440-1080-1440, 2880-2160-2880, 3024-4032",
    thumb: 'thumbs/Vecht_121027_1156.jpg' 
  }, 

```  
The test album shows the used dimensions in the middle of the image.

The first image displayed on a iPhone 13 Pro is 
in landscape mode 2.0: 3840X2880 (WebP) and
in portrait mode 1.0: 1920X1440 (WebP)

The iPhone 13 pro: screen.width	390, screen.height:	844, Pixel-ratio: 3,
so in landscape mode a width of 2532 pixels and
in portrait mode a width of	1170 pixels
You see the image of the first higher width is selected.

The first image displayed on my 2560x1440 PC monitor is 
in landscape mode 2.0: 2880x2169 (WebP).

My monitor: screen.width 1707, screen.height: 960, Pixel-ratio: 1.5,
so in landscape mode a width of 2560 pixels.
So also here the image of the first higher width is selected.

This looks all correct, do you agree?
