### ISSUE TITLE
Nuxt 3 Error  require is not defined

### ISSUE THREAD

**Issue by j-brand** [sachinchoolur/lightGallery#1379]
## Description

Im trying to unse lighGallery inside a Vue Component with Nuxt 3 rc8
First i got a error that it is not possible to import a whole directory 
(e.g. the thumbnail plugin directory)
`import lgThumbnail from "lightgallery/plugins/thumbnail";`

error:

`Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/workspaces/blackbeetle-frontend__new/node_modules/lightgallery/plugins/thumbnail' is not supported resolving ES modules imported from /workspaces/blackbeetle-frontend__new/.nuxt/dist/server/server.mjs
Did you mean to import lightgallery/plugins/thumbnail/lg-thumbnail.umd.js?`

Then i tried to transpile lightgallery in nuxt.config.js. then i got this error: 

`[nuxt] [request error] [unhandled] [500] require is not defined in ES module scope, you can use import instead`

Lightgallery uses "require" to require "vue". I think this is not allowed in ES Modules.

### Steps to reproduce

1.) Install Nuxt3 rc8 
2.) Import LighGallery into a component
3.) add a lightgallery component

### Environment
-   Nuxt 3 rc 8
-   lightGallery version 2.5

Is it possible to fix this issue somehow?

**Comment by ManasMadrecha** [comment]
`require` is not accepted in Vite.

**Comment by ManasMadrecha** [comment]
.

**Comment by ManasMadrecha** [comment]
.

**Comment by ManasMadrecha** [comment]
.
