### ISSUE TITLE
How to set iframe size in lightgallery to the iframe's content?

### ISSUE THREAD

**Issue by q2apro** [sachinchoolur/lightGallery#138]
I am loading a website within an iframe, this iframe contains videos in different widths. 

I need lightGallery to dynamically resize the iframe to its content. 

Is this already implemented? I only found `videoMaxWidth:'100%',` and do not see how I could use this in this context. 

Probably it needs some jquery, here could be a starting point: http://stackoverflow.com/q/9162933/1066234

**Comment by sachinchoolur** [comment]
Hi,
Sorry for the delayed response..
We can not access cross domain iframe content using javascript..

Closing the issue..
