### ISSUE TITLE
Video poster image disappears on an iPhone

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1380]
If you open the 4th image in [the lightGallery videos codepen](https://codepen.io/sachinchoolur/pen/ExXxqPe) on an iPhone, the poster is only shortly visible, wherafter it disappears:

![NoPosterImageLR](https://user-images.githubusercontent.com/8150784/186958887-a5b92136-a550-4c9a-8406-fc334fb861db.jpg)

It is working without problems on an iPad and on a Windows 10 PC.

**Comment by sachinchoolur** [comment]
IOS prevents video autoplay in some scenarios. Adding "playsinline": true as an HTML video attribute solves the issue.

```html
<a data-lg-size="1280-720" data-video='{"source": [{"src":"https://www.lightgalleryjs.com/videos/video1.mp4", "type":"video/mp4"}], "attributes": {"preload": false, "controls": true, "playsinline": true}}' data-poster="https://www.lightgalleryjs.com/images/demo/html5-video-poster.jpg" data-sub-html="<h4>'Peck Pocketed' by Kevin Herron | Disney Favorite</h4>">
    <img class="img-responsive" src="https://www.lightgalleryjs.com/images/demo/html5-video-poster.jpg" />
  </a>
```

Docs - https://www.lightgalleryjs.com/demos/video-gallery/#video-autoplay

**Comment by acwolff** [comment]
@sachinchoolur thanks for your reply.

Setting "playsinline": true, does not remove the black page on an iPhone in my case, as you can see in [my test album](https://andrewolff.jalbum.net/TestVimeoYouTubeVideos_LG/).

I think both the [fancyBox](https://andrewolff.jalbum.net/TestVimeoYouTubeVideos_FB/) and [photoSwipe](https://andrewolff.jalbum.net/TestVimeoYouTubeVideos_PS/) libraries do handle videos better and easier!
