### ISSUE TITLE
can someone help me on how to use specifically the inline gallery, please?

### ISSUE THREAD

**Issue by lucas24-dot** [sachinchoolur/lightGallery#1385]
## Summary

Brief explanation of the feature.

### Basic example

Include a basic example or links here.

### Motivation

Why are we doing this? What use cases does it support? What is the expected
outcome?

**Comment by sachinchoolur** [comment]
Codepen demo - https://codepen.io/sachinchoolur/pen/zYZqaGm

If you face any issues, please share a codepen demo with what you have. I'll fix the issues and send it back to you

**Comment by lucas24-dot** [comment]
![Screenshot (81)](https://user-images.githubusercontent.com/83312739/187852882-57171fe4-ec06-4a5d-841d-709d00d0564a.png)

I'm request to know how to use this inline gallery, after introducing the container as indicated in the docs, it detaches the css.
Other demos are working fine apart from the inline gallery on my pc.

Can help me with the inline gallery file only, please?

**Comment by lucas24-dot** [comment]
![Screenshot (82)](https://user-images.githubusercontent.com/83312739/187860424-729b55c9-e2cb-4b99-935e-8f993675b1c1.png)

I am trying to do every thing right , please help me with the inline gallery file only.

**Comment by lucas24-dot** [comment]
I don't understand why the plugin is not responding yet i have connected every file best as i know.

**Comment by lucas24-dot** [comment]
Hello, would you please help me with the inline gallery plugin only?
The others are working well apart from inline gallery.

**Comment by lucas24-dot** [comment]
@sachinchoolur/lightGallery, help me with the index file of the inline
gallery only. Thank you in advance.

**Comment by acwolff** [comment]
What do you mean with:
> , it detaches the css.
please give a link to your gallery.

The in-line gallery works fine as you can see in [my example album](https://andrewolff.jalbum.net/LG_Carousel/)
