### ISSUE TITLE
grayed zoom icon

### ISSUE THREAD

**Issue by djuj** [sachinchoolur/lightGallery#1387]
Hi,

After opening an image from a gallery, I click on the zoom icon to enlarge it, then I go to another image in the gallery (next or previous) and there I find the zoom icon grayed out and inactive. The double click in the image still manages the zoom and seems to reactivate the icon.
You can test it at the first gallery in this page : https://www.lightgalleryjs.com/
Same thing with FF, Chrome or Safari.

Thanks
Djuj

**Comment by sachinchoolur** [comment]
Hey @djuj,

Thank you for reporting this issue. 
Fixed inversion 2.6.1
