### ISSUE TITLE
What is the relativeCaption plugin?

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1389]
@sachinchoolur, today I fetched your new version 2.6.0. 

This distribution contains a relativeCaption plugin folder.

I can't find any documentation about this plugin.

Please tell me where I can find the documentation or explain it here and if possible give a code example.

Thanks for your awsome library!

**Comment by sachinchoolur** [comment]
Relative caption plugin is used to place captions right below the image based on the image dimension. It is not officially documented.
