### ISSUE TITLE
Zoom plugin and download Bug

### ISSUE THREAD

**Issue by JimChristian21** [sachinchoolur/lightGallery#1393]
1. I included the lgZoom plugin but after the render the button is not working.
2. When I click the download button it will be open to a new windows and not downloaded on my browser.

**Comment by sachinchoolur** [comment]
Hey @JimChristian21,

1) Zoom button will be disabled if the actual size of the image is less than the screen size
2) Download Image option works fine on all browsers that support HTML5 download attribute. 
You can also provide your own download URL via `data-download-url`

Docs - https://www.lightgalleryjs.com/docs/settings/#download

**Comment by sachinchoolur** [comment]
There was an issue with the zoom button. This has been fixed in version 2.6.1
