### ISSUE TITLE
Dynamic Mode

### ISSUE THREAD

**Issue by romy2012** [sachinchoolur/lightGallery#1397]
Dynamic Mode  hideControlOnEnd set true invalid.

**Comment by sachinchoolur** [comment]
`hideControlOnEnd` option will be ignored if `loop` or `slideEndAnimation` is set to true

Updated docs - https://www.lightgalleryjs.com/docs/settings/#hideControlOnEnd

**Comment by romy2012** [comment]
Thanks,but invalid.

        lgContainer.addEventListener('lgAfterSlide', (event) => {
            const { index, prevIndex } = event.detail;
            if(index==0){
                $('#lg-prev-1').addClass('disabled');
            }else{
                $('#lg-prev-1').removeClass('disabled');
            }

            if(index==inlineGallery.galleryItems.length-1){
                $('#lg-next-1').addClass('disabled');
            }else{
                $('#lg-next-1').removeClass('disabled');
            }

        });
