### ISSUE TITLE
What to do when Youtube videos have no maxresdefault image?

### ISSUE THREAD

**Issue by LeviticusMaximus** [sachinchoolur/lightGallery#1401]
## Description

Certain Youtube Videos simply don't have a maxresdefault image.

So, the video plays OK but does not have the initial poster image. 

How can I make a fallback to other poster images if there is a 404 on the requested maxresdefault?

**Comment by sachinchoolur** [comment]
Hey @LeviticusMaximus,

At the moment, lightGallery does not automatically find suitable poster images. 

You need to provide them manually via the `data-poster` attribute.

**Comment by sachinchoolur** [comment]
You can maybe try fetching the poster before providing it to lightGallery and fallback to the low-quality poster or a default poster if the `maxresdefault` is not available

**Comment by farzher** [comment]
i realize this is mostly a problem with youtube but can you put in some kind of fix for this? maybe have lightgallery automatically try other thumbnails if maxresdefault.jpg doesn't exist? sddefault.jpg seems like a good fallback. (sddefault.jpg is higher quality than hddefault.jpg, don't ask me why)

this looks so dumb 
![image](https://github.com/sachinchoolur/lightGallery/assets/1005136/df949431-74e8-43ef-ad0e-095f76c0a361)

**Comment by pjar** [comment]
For me the thumbnail is not picked up by passing either as `poster` key for dynamicEl nor by using `data-poster` on the element itself.
