### ISSUE TITLE
Zoom button issue

### ISSUE THREAD

**Issue by VyaraDurcheva** [sachinchoolur/lightGallery#1403]
We are using the latest 2.6.0 version of lightGallery. When clicking twice zoom button the image is scaled and stuck on its scaled position, also zoom button cannot be clicked again. This happen on mobile and desktop. Also I saw that the same issue is happening on lightGallery example that is given on its website. When clicking zoom button without any delay or faster twice the button is blocked and the image stuck on scaled position.

**Comment by sachinchoolur** [comment]
Thank you for reporting this issue. 

Fixed in version 2.7.0.
