### ISSUE TITLE
Question on the license key?

### ISSUE THREAD

**Issue by michaelt05** [sachinchoolur/lightGallery#1404]
I just purchase a Team license and got the license code. This license code is to be on the javascript. My question is what stopping  another person from internet view my site source code and grab my license number and used it on their own site?

**Comment by sachinchoolur** [comment]
Hey @michaelt05,

Thank you for supporting lightGallry development. 

The license key is valid only if you've purchased a license. 

The license agreement between us is what gives you the athority to use lightGallery. Not the license key. 

Hope it is clear. Let me know if you have any questions

**Comment by michaelt05** [comment]
@sachinchoolur  So what if someone view source code my my site and copy the license key to use on his/her own site?
