### ISSUE TITLE
Problem with centering images in IE11 & IE10

### ISSUE THREAD

**Issue by redworx** [sachinchoolur/lightGallery#141]
I have a problem. i used your slider, but in IE11 and IE10 the main images are not centered and the thumbnail bar is hidden...

I dont know why, because in your demo its working...

In IE9 its centered but ALL elements are hidden ...

any hints?

**Comment by sachinchoolur** [comment]
Hi,
That could be some issue with your css.
Could you please provide your website url if it is live?
