### ISSUE TITLE
Pinch to zoom bug in Inline Gallery

### ISSUE THREAD

**Issue by VyaraDurcheva** [sachinchoolur/lightGallery#1414]
Pinch to zoom bug in Inline Gallery
We are using version 2.6 of lightGallery and we have issue with pinch to zoom. When you pinch to zoom in Inline Gallery then the picture is zoomed and then automatically zoomed out. The same problem is visible even in lightGallery website with examples that are given. It happens both on iOS and Android. There is no issue with pinch to zoom on Thumbnail Gallery, if that could help for resolving the issue. Thank you!

**Comment by sachinchoolur** [comment]
Hey @VyaraDurcheva,

On the demo page, the inline gallery uses responsive images (Small sized images on mobile devices)

And if you zoom beyond the image's actual size, the images will zoom out to the largest possible size when you release your fingers.
