### ISSUE TITLE
Custom player params do not work for Youtube

### ISSUE THREAD

**Issue by StNimmerlein** [sachinchoolur/lightGallery#1417]
When using lightGallery to play YouTube videos they are automatically muted. Passing `{youTubePlayerParams: {mute: 0}}` as settings does not work since the additional params are attached to the url in the wrong order.

We use lightGallery productively with a license and need our videos not to be muted.

https://github.com/sachinchoolur/lightGallery/pull/1396 solves this problem. Could you either merge this or fix it yourself so that in a future release we can use the library to our full satisfaction?

**Comment by sachinchoolur** [comment]
Hey @StNimmerlein,

I'll look into the issue. For now, you can directly pass the mute option via the URL 
Example - `//www.youtube.com/watch?v=egyIeygdS_E&mute=0`

**Comment by StNimmerlein** [comment]
Hi,

thanks for the reply. We provided the video url in the form of `https://youtube-nocookie.com/embed/egyIeygdS_E` and here the parameter did not work when we tried it.
However, it seems like lightGallery ignores the `youtube-nocookie`-part completely and renders a normal youtube iframe for the id in the url.
So at the moment we could just use the usual youtube link instead of youtube-nocookie since it makes no difference in the outcome. And in that case your workaround works :-)

**Comment by sachinchoolur** [comment]
Hey @StNimmerlein,

Both issues are resolved in version [2.7.1-beta.0](https://github.com/sachinchoolur/lightGallery/releases/tag/2.7.1-beta.0) release 

- [Correct player params order](https://github.com/sachinchoolur/lightGallery/commit/0a6f93b7dd65f0f495fb5f6245500bedc359f4d9)

- [youtube nocookie support](https://github.com/sachinchoolur/lightGallery/commit/d5b7faf69a73cfe2d8e855ab3b679f38c562ff56)

Let me know if you face any issues
