### ISSUE TITLE
Open gallery using a buttton

### ISSUE THREAD

**Issue by bessaleh** [sachinchoolur/lightGallery#1418]
## Summary

Thanks for this good feature offred by your library.
I would like to open the gallery in fullscreen mode using a button as like as the event when I click on an image. Is there a way to do that please ?

### Basic example
There is my code:

`<LightGallery
          mode="lg-fade"
          index={fullScreenIndex}
          appendSubHtmlTo=".lg-item"
          plugins={[lgZoom, lgThumbnail]}
        >
        {
          gallery.map((image: string, index: number) => {
            return (
            <a key={index} className="gallery-item" data-src={image} data-sub-html="-">
              <img src={image} alt="image" />
            </a>
            )
          })
        }
      </LightGallery>`
      
      <button onClick={() => openGallery()}></button

**Comment by bessaleh** [comment]
I solved it in that post 
https://stackoverflow.com/questions/74183491/display-gallery-using-a-button/74218906#74218906

**Comment by sachinchoolur** [comment]
Here is the solution without using `ref`

Demo - https://stackblitz.com/edit/lightgallery-react-y8jegn?file=index.tsx

```tsx
function App() {
  const [lgInstance, setLgInstance] = useState(null);
  const onInit = ({ instance }) => {
    setLgInstance(instance);
  };
  const openGallery = () => {
    lgInstance.openGallery();
  };
  return (
    <div className="App">
      <button onClick={openGallery}>Open gallery</button>
      <LightGallery elementClassNames="custom-wrapper-class" onInit={onInit}>
        <a
          data-lg-size="1406-1390"
          className="gallery-item"
          data-src="https://images.unsplash.com/photo-1581894158358-5ecd2c518883?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1406&q=80"
          data-sub-html="<h4>Photo by - <a href='https://unsplash.com/@entrycube' >Diego Guzmán </a></h4> <p> Location - <a href='https://unsplash.com/s/photos/fushimi-inari-taisha-shrine-senbontorii%2C-68%E7%95%AA%E5%9C%B0-fukakusa-yabunouchicho%2C-fushimi-ward%2C-kyoto%2C-japan'>Fushimi Ward, Kyoto, Japan</a></p>"
        >
          <img
            className="img-responsive"
            src="https://images.unsplash.com/photo-1581894158358-5ecd2c518883?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=240&q=80"
          />
        </a>
      </LightGallery>
    </div>
  );
}
```

**Comment by digvan** [comment]
@sachinchoolur that solution creates infinite loop when you call setLgInstance(instance);
