### ISSUE TITLE
how to open the gallery from link

### ISSUE THREAD

**Issue by bfmramalho** [sachinchoolur/lightGallery#142]
I would like to make the `<ul>` that contains the images hidden, and then lunch the gallery from a link.
Is this possible?

**Comment by bfmramalho** [comment]
I found a work around:
`<a id="open">Open Gallert</a>
<ul id="lightGallery">
  <li data-src="img/img1.jpg">
      <img src="img/thumb1.jpg" />
  </li>
  <li data-src="img/img2.jpg">
      <img src="img/thumb2.jpg" />
  </li>
</ul>`
and
`$('#lightGallery').lightGallery();
$("#open").click(function () {
    $('ul#lightGallery li:first').click();
});`

Maybe there's another way to do this, but this works fine

**Comment by clintongreen** [comment]
Good idea, best one I've seen so far.

**Comment by carasmo** [comment]
Thank you, this helped a lot!
