### ISSUE TITLE
closeOnTap does not work when rotate plugin enabled

### ISSUE THREAD

**Issue by balporig** [sachinchoolur/lightGallery#1422]
## Description

Closing when tapping on black space around the image does not work when rotate plugin enabled

### JS code that you use to initialize lightGallery.

```js
lightGallery(document.getElementById('lightgallery'), {
       closeOnTap: true,
        plugins: [
            lgRotate
        ],
});
```

### Sample HTML markup

```html
<div id="lightgallery">
    <a href="img/img1.jpg" data-lg-size="1600-2400">
        <img alt=".." src="img/thumb1.jpg" />
    </a>
</div>
```

### Environment

-   Browser and version - Firefox 106.0.2, Chromium 107.0.5304.87
-   OS - all
-   lightGallery version - 2.7.0

### Additional context

Could be related to #1405

**Comment by BringerOfTheDawn** [comment]
isSlideElement() is missing selector for rotate wrapper **.lg-img-rotate**
