### ISSUE TITLE
v.2.7.0 Zoom doesn't work when 'dynamic' option is true

### ISSUE THREAD

**Issue by kohakubaibai** [sachinchoolur/lightGallery#1432]
There are two galleries in page, so I don't use ID for selector.

const $dynamicGallery = $('[data-js-id="open-popup"]');
    const dynamicGallery = lightGallery($dynamicGallery, {
      dynamic: true,
      dynamicEl: [
          {
              src: 'assets/images/recommend/1-1-1.jpg'
          },
          {
              src: 'assets/images/recommend/1-1-2.jpg'
          },
          {
              src: 'assets/images/recommend/1-1-3.jpg'
          }
      ],
      download: false,
      actualSize: false,
      plugins: [lgZoom],
      zoom: true,
      showZoomInOutIcons: true
    });
    $dynamicGallery.on('click', function(e){
      e.preventDefault();
      dynamicGallery.openGallery();
    });

and...Zoom is not working...
I have included zoom plugin and write settings, but it still not work...

**Comment by sachinchoolur** [comment]
Hey  @kohakubaibai,

Please provide a CodePen demo of the problem. 

You can fork the below CodePen and make the changes - https://codepen.io/sachinchoolur/pen/VwpYagE
