### ISSUE TITLE
Disabling controls bug

### ISSUE THREAD

**Issue by Morjodrom** [sachinchoolur/lightGallery#144]
First, thank you for both light plugins, they're great!
There is a bug In lightGallery while disabling controls:
*TypeError: $prev is undefined* on line ```$prev.after('<a class="cl-thumb"></a>');```
I called:
```
$("body").lightGallery({
	selector: ".overlay",
	controls: false,
	enableTouch: false,
	enableDrag: false
});
```
So, controls property to false ruins the plugin

**Comment by sachinchoolur** [comment]
Hi,
Thank you for pointing this out. I have fixed this issue... Please check.
