### ISSUE TITLE
Methods and useState throw React component into loop or re-render

### ISSUE THREAD

**Issue by chris-at-lemon** [sachinchoolur/lightGallery#1448]
## Description

If I use any method (onInit, onBeforeClose, etc) to set a state my component either gets thrown into an infinite loop or it rerenders entirely, depending on method. 

onInit throws the component into an infinitel loop if I have a setState inside it.

This was not a problem with React 16 with LG 2.3. I have not found a workaround in React 18, LG 2.7

### Steps to reproduce

Working demo:

https://codesandbox.io/s/lightgallery-23-zf78it

Not working demo:

https://codesandbox.io/s/lightgallery-27-tbxl1p
(I have commented out the setState )

This severly limits on how I can integrate the LG with the rest of my App, is there a workaround?

Happy new year :)

**Comment by gijsbotje** [comment]
Having the same issue after upgrading to 2.7.1 from 2.5.0.
Also tried using a ref, but it won't call the functions from the instance, ie. the `openGallery()` function won't open the gallery.

**Comment by gijsbotje** [comment]
@sachinchoolur could you take a look at this?

**Comment by erik-stephens** [comment]
@sachinchoolur Please keep this on your radar.  I'm having to resort to a klunky workaround (eg use global variable).  Thanks!

**Comment by erik-stephens** [comment]
Stalebot, get outta here.
