### ISSUE TITLE
Close button on mobile views NEEDS to be optionally persistent.

### ISSUE THREAD

**Issue by Alphablank1111** [sachinchoolur/lightGallery#1465]
I think the usability and UX is kind of flawed, my users are confused when on mobile displays because there isn't an obvious close pattern. the header is still there but all the secondary controls are hidden, which does make sense, but the close button should be persistent, this is a UX standard! How do I go about making the close button persistent?

**Comment by GastonZalba** [comment]
Enable it using [mobileSettings](https://www.lightgalleryjs.com/docs/settings/#mobileSettings)

**Comment by Alphablank1111** [comment]
> Enable it using [mobileSettings](https://www.lightgalleryjs.com/docs/settings/#mobileSettings)

I've tried all of that, it doesn't seem to work properly using the react plugin. There's nothing in the documentation about mobileSettings within the react plugin.

**Comment by PatrickGTR** [comment]
Has anyone found a solution to this?

I've tried enabling mobileSettings options unfortunately I'm still unable to see a close icon on mobile view.

**Comment by MageCloudTeam** [comment]
Same issue. Tried hideControlOnEnd: false, but it's not helping

**Comment by PatrickGTR** [comment]
> Same issue. Tried hideControlOnEnd: false, but it's not helping

Hi, we've recently fixed our issue. Check your elements z-index is not higher than lighGallery's z-index.

Hope this helps!
