### ISSUE TITLE
Youtube videos not working...

### ISSUE THREAD

**Issue by sirturin** [sachinchoolur/lightGallery#147]
Is there a known issue with Youtube videos not playing? I have tried it with Vimeo and it works just fine but youtube links just come up blank. Any help would be appreicated. Thank you

**Comment by SeanWilliamson707** [comment]
I'm having the same problem as well.

**Comment by sirturin** [comment]
For the record I just want to make it known that the issue was a matter of working locally versus uploading the files to the server. Once I uploaded the files to my server the Youtube videos worked! I don't know why the youtube videos didn't work when I was making edits locally and vimeo did work but that is irrelevant now. @SeanWilliamson707  if you're having the same problem try uploading to your server and testing them online first

**Comment by sachinchoolur** [comment]
Hi,
it will work fine if you run it via a webserver locally, such as wamp, xampp, http-server etc..

**Comment by SeanWilliamson707** [comment]
Awesome @sirturin! Thanks for the update. I just went with Vimeo like your first suggestion said and everything was fine. Also @sachinchoolur I'll give that a shot when I update my site. :)
