### ISSUE TITLE
Zoom problem

### ISSUE THREAD

**Issue by bgomes90** [sachinchoolur/lightGallery#1477]
Hello!
When i click to zoom the image, the zoom starts at top left, not at center.
It occurs in firefox (linux and windows) and chrome (windows).
Can you fix this, or help me?
Thank you.

**Comment by sachinchoolur** [comment]
Is it happening on lightGallery website as well?

Could you please share a recording, if possible?

**Comment by bgomes90** [comment]
yeah, of course!
website and mobile phone has the same problem

https://user-images.githubusercontent.com/13823899/222863476-23dfa228-8ba4-4bd8-a7ad-9056b0d8262f.mp4

**Comment by hoseinseyedinejad** [comment]
@sachinchoolur Is there any way we can help you fix the feature of step-by-step zoom beyond 100%? It's really important for our users. We've upgraded to the latest version to use SwipeToClose feature but unfortunately, we've lost zooming beyond 100%.

**Comment by tevfikkdurmus** [comment]
Hello, were you able to solve the problem? Could you please help me?
