### ISSUE TITLE
Pager hover preview should keep original image ratio

### ISSUE THREAD

**Issue by AtzeBK** [sachinchoolur/lightGallery#1481]
Hi, 
ain't it possible to use the same thumbnail script logic for lgPager previews (hovering over the pager icons) in .lg-pager-thumb-cont as with the generated thumbnails from lgThumbnail? 
The reason why is: the pager previews using a static size of 120x83px which, of course, won't keep the picture ratio. The previews are looking quite bad. 
On the other hand, the thumbnails automatically created by lgThumbnail are perfectly scaled and the overflow is hidden by keeping the original image ratio. 
I would appreciate if this is implemented to lgPager as well.

**Comment by sachinchoolur** [comment]
Could you please share a screenshot of the pagers? 

This can be easily done by using CSS `object-fit` property

**Comment by AtzeBK** [comment]
Thanks in advance! object-fite: cover; did the trick! 

`  .lg-pager-thumb-cont {
    background-color: #fff;
    color: #fff;
    bottom: 100%;
    height: 83px;
    left: 0;
    margin-bottom: 20px;
    margin-left: -60px;
    opacity: 0;
    padding: 5px;
    position: absolute;
    width: 120px;
    border-radius: 3px;
    will-change: transform, opacity;
    @include transitionCustom(opacity 0.3s ease 0s, transform 0.3s ease 0s);
    @include translate3d(0, 5px, 0);

    img {
      width: 100%;
      height: 100%;
      object-fit: cover;
    }
  }`

Before:
![image](https://user-images.githubusercontent.com/17429601/223768092-13f3fb04-433c-4c9a-ae1b-95c10718edee.png)

After:
![image](https://user-images.githubusercontent.com/17429601/223768204-927eeeb0-5c4f-4638-b67b-9539f64a93a9.png)
