### ISSUE TITLE
NextJS (ReactJS) + LightGallery: Showing "Failed to load content..." & Unable To Properly Import LightGallery CSS

### ISSUE THREAD

**Issue by sgrobert** [sachinchoolur/lightGallery#1483]
## Description

Hi there. I'm currently faced with two issues and sincerely hope your team may help assist me in resolving them. Thanks!:

---

1. The default import CSS file method for ReactJS doesn't seem to work: `import "lightgallery/css/lightgallery-bundle.css";`, which seems to be causing the odd display layout on my UI. I also read up on this https://github.com/sachinchoolur/lightGallery/issues/1150 but the solution did not resolve my issue.

![Screenshot 2023-03-12 at 8 39 55 AM](https://user-images.githubusercontent.com/759805/224518093-4edc72b9-7855-4ef1-bc7e-f653ad4ac801.png)

---

2. On an attempt to click on the image, an error message `Failed to load content...` appears and I'm unsure what it means nor have an reference on how to help resolve it.

![Screenshot 2023-03-12 at 8 47 04 AM](https://user-images.githubusercontent.com/759805/224518151-82e82374-ec38-4d22-9b5e-9008bd0efde9.png)

---

### Steps to reproduce

I have taken a code reference from the default React Demo (https://stackblitz.com/edit/lightgallery-react?file=index.tsx).

**Replication Repo:** https://stackblitz.com/edit/nextjs-tdridw?file=pages/index.js 

The only think I can think of that may affect the css config is `TailwindCSS`, of which I have also imported it into the replication repo as well.

![Screenshot 2023-03-12 at 8 33 44 AM](https://user-images.githubusercontent.com/759805/224518454-bc5631ae-1ec6-44de-b174-addb3eac8a26.png)

![Screenshot 2023-03-12 at 8 33 56 AM](https://user-images.githubusercontent.com/759805/224518456-c91298e9-bfe3-453f-9fe1-440cdaa9849c.png)

### JS code that you use to initialize lightGallery.

```js

None. Using ReactJS template from https://www.lightgalleryjs.com/docs/react/ 

```

### Sample HTML markup

```html

<LightGallery
   mode="lg-fade"
   speed={500}
   plugins={[lgThumbnail, lgZoom]}
>
  ...
</LightGallery>

```

### Environment

- Browser and version - Chrome / Brave [Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (arm64)](https://brave.com/latest/)
- OS - macOS Ventura 13.2.1 (22D68)
- lightGallery version - "^2.7.1"
- next: "^13.2.4"
- react: "^18.2.0"
- tailwindcss: "^3.2.7"

**Comment by sachinchoolur** [comment]
Hey @sgrobert,

Sorry for the late reply. There is an additional div inside the component which is causing the issue 

```tsx
<LightGallery
          mode="lg-fade"
          speed={500}
          plugins={[lgThumbnail, lgZoom]}
        >
          <div id="lightgallery-gallery">
```

Remove element with id `lightgallery-gallery` and everything should work fine 


Here is the updated stackblitz - https://stackblitz.com/edit/nextjs-zufrkb?file=pages%2Findex.js

**Comment by ebbadullah** [comment]
I’m using LightGallery with React and Bootstrap to show uploaded videos/images inside a grid.
Videos open in the modal but give the error:

"Oops! Failed to load content."

It happens only on videos (MP4). The videos are playable inline (in <video> tag), but LightGallery popup fails.

<img width="1350" height="642" alt="Image" src="https://github.com/user-attachments/assets/8a9bd291-ee88-4dfc-956c-066f13e1883a" />

<img width="607" height="501" alt="Image" src="https://github.com/user-attachments/assets/67449a38-2e38-43aa-a00c-32cbd3915476" />

**Comment by nk9** [comment]
This should be a new issue. And please, please [use details tags](https://gist.github.com/scmx/eca72d44afee0113ceb0349dd54a84a2)! Super-long comments make threads a challenge to read, especially on mobile.
