### ISSUE TITLE
After zoom-in image becomes disproportionate

### ISSUE THREAD

**Issue by dewebeloper** [sachinchoolur/lightGallery#1484]
I have implemented lightgallery in Angular 12 app.
Pretty much all works, except after zoom-in (click on zoom-in icon) images is loaded in full size but then after that becomes disproportionate because get inline style width and height.

You can see issue on [https://veilbalie.dewebeloper.com/test-1-1](https://veilbalie.dewebeloper.com/test-1-1), if you click on any of wine bottle images.

Any thoughts how I can fix this issue?

**Comment by sachinchoolur** [comment]
Sorry for the late reply. I looked into your website and everything seems to be working fine for me.

Could you please share a screenshot of the issue?

**Comment by dewebeloper** [comment]
Hi, thanks for reply.
I had to remove lgzoom from app, so that is why works fine.
But now I restored previous version with issue. You can check on same link.
