### ISSUE TITLE
Background audio 

### ISSUE THREAD

**Issue by iappstudio112** [sachinchoolur/lightGallery#1491]
## Summary
We need to Play audio in entire Background 
Brief explanation of the feature.

### Basic example
10 Photos and Have one mp3 to play a loop in background.
Include a basic example or links here.

is there are option for this ?

**Comment by sachinchoolur** [comment]
lightGallery does not support audio files at the moment. But, Since you want to use it in the background, you play the audio file programmatically play using lightGallery events. 


```js

lg.addEventListener('lgBeforeOpen', () => {
    var audio = new Audio('audio_file.mp3');
    audio.play();
});
```
