### ISSUE TITLE
Inconsistent / failing zoom

### ISSUE THREAD

**Issue by bradjste** [sachinchoolur/lightGallery#1494]
## Description

The lg-zoom plugin (angluar) does not work on many images I place in the gallery.

Here is a stackblitz forked from the  [updating slides](https://www.lightgalleryjs.com/docs/angular/#updating-slides) example: 
https://stackblitz.com/edit/lightgallery-angular-update-slides-gkkubp?file=src/app/app.component.ts

and here is just the stackblitz app:
https://lightgallery-angular-update-slides-gkkubp.stackblitz.io/

As you can see here, the zoom only works with the child image (via unsplash) provided in the official example. It appears there are additional requirements regarding image size / metadata that I am missing here, though I haven't seen any mention of them in the documentation so far.

I have found that it does appear to work marginally when the browser viewport size is smaller than the width of the image, however this requires smooshing the browser to unreasonable sizes.

**Comment by sachinchoolur** [comment]
Are you referring to the zoom animation that occurs when opening the gallery or the zoom-in functionality accessed by clicking the zoom-in icon?

If it is about the initial zoom animation, you must specify the actual image size using the `data-lg-size` attribute. 

Docs - https://www.lightgalleryjs.com/docs/settings/#zoomFromOrigin

If your question concerns the zoom-in feature accessed via the zoom icon, please note that LightGallery currently does not support zooming beyond the actual size of the image. This functionality will be introduced in the upcoming release.

https://github.com/sachinchoolur/lightGallery/commit/f691d0096a4ee00641e1a3be22d4101e715f3ff3
