### ISSUE TITLE
iframe in mobile view unable be closed

### ISSUE THREAD

**Issue by weiseek** [sachinchoolur/lightGallery#1495]
## Description

iframe window unable be closed at mobile view. Also tried on your iframe demo page. Doesn't happen on simulator. But get issue on real phone.

### Steps to reproduce

<button
    class="btn btn-success btn-lg mrb50"
    data-iframe="true"
    id="open-website"
    data-src="https://tack.one/"
    data-iframe-title="All new time tracking. Greater insight."
>
    Open website
</button>
```

### Environment

iPhone and Android

### Additional context

**Comment by sachinchoolur** [comment]
Thank you for reporting this issue. 

The close button is disabled on mobile by default. You can enable them by using the below code 

```js
var options = {
    mobileSettings: {
        controls: false,
        showCloseIcon: true,
        download: false
    }
};

$('#lightgallery').lightGallery(options);
```

I'll update the demo
