### ISSUE TITLE
HTML5 Videos Not Pausing while navigating to Prev/Next

### ISSUE THREAD

**Issue by phpso10** [sachinchoolur/lightGallery#1496]
## Description

This issue is when you use HTML5 Videos.
Preview: 

https://user-images.githubusercontent.com/20170373/234333619-4bb932c4-f7fe-474e-b8d7-c2188ef94755.mov

all thumbnails and videos show as expected, but videos play automatically  behind when you move to next or previous slide.
It doesn't matter whether you manually pause and move to the next slide. Expectation is video to pause automatically when you move to next or previous slide.
 I need some event so I can call on $dynamicGalleryVideos.addEventListener('lgHasVideo', (event) => { 
// Pause my current video -> What I need to use??? how can I trigger pauseVideo?
});

### JS code that you use to initialize lightGallery.
var initialarrayVideos=
    [
      {
          src:
            "https://images.unsplash.com/photo-1535953267280-5fd672f9bfa3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OTh8fHBhdHRlcm58ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60",
          thumb:
            "https://images.unsplash.com/photo-1535953267280-5fd672f9bfa3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OTh8fHBhdHRlcm58ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60",
          subHtml: `<div class="lightGallery-captions">
                    <h4>IMAGE</h4>
                    <p>IMAGE</p>
                </div>`
        },
      { video: {"source": [{"src":"___comp___video___f0ff6e02-5923-447f-91e1-6ec4fdf068eb.mp4”, "type":"video/mp4"}], "attributes": {"preload": false,"controls":true}}, thumb: "___thumb___video___f0ff6e02-5923-447f-91e1-6ec4fdf068eb____9999____0000000000.jpeg", subHtml: "f0ff6e02-5923-447f-91e1-6ec4fdf068eb"},
      { video: {"source": [{"src":"___comp___video___f0ff6e02-5923-447f-91e1-6ec4fdf068eb.mp4”, "type":"video/mp4"}], "attributes": {"preload": false,"controls":true}}, thumb: "___thumb___video___f0ff6e02-5923-447f-91e1-6ec4fdf068eb____9999____0000000000.jpeg", subHtml: "f0ff6e02-5923-447f-91e1-6ec4fdf068eb"},
      { video: {"source": [{"src":"___comp___video___f0ff6e02-5923-447f-91e1-6ec4fdf068eb.mp4”, "type":"video/mp4"}], "attributes": {"preload": false,"controls":true}}, thumb: "___thumb___video___f0ff6e02-5923-447f-91e1-6ec4fdf068eb____9999____0000000000.jpeg", subHtml: "f0ff6e02-5923-447f-91e1-6ec4fdf068eb"}
  ]

 dynamicGalleryVideos = window.lightGallery($dynamicGalleryVideos, {
  dynamic: true,
  plugins: [ lgVideo, lgThumbnail],
  dynamicEl: initialarrayVideos });

### Sample HTML markup
```
<button type="button" class="btn btn-success" id="dynamic-gallery-videos">Launch
Video</button>
```

### Environment 
- Chrome Browser
-   OS - Mac
- lightgallery | 2.1.7 | July 1st 2021

**Comment by sachinchoolur** [comment]
Hey @phpso10,

lightGallery already handles play and pause when you navigate to different slides. 

Could you please provide a codepen demo where I can reproduce the issue?

**Comment by phpso10** [comment]
Hi Sachin -
you are right - when we display controls, we can pause and play - but when
you don't display Controls on filepond id tag, then have to do manually.
But I think I will figure out. Thank you so much for your help.

Also, can you please check if you have provided me the license key before?
I vaguely remember you sharing some website link to download/view the
license key - if not, I will purchase.
-Venkat

**Comment by phpso10** [comment]
Hi Sachinchool,
are you available for hire? I need some help with your library to customize
for my website.
It is almost the same thing - but need some tweaks on JS. Let me know if
you can tweak like how it is shown on https://foofr.com
and the price you need to get done.
(I am unable to get dynamic AJAX calls from nodeJS using your library)
-Venkat
