### ISSUE TITLE
Not reload list dynamic when using method refresh in useEffect

### ISSUE THREAD

**Issue by gamestap99** [sachinchoolur/lightGallery#1499]
![Screenshot 2023-05-08 at 23 06 16](https://user-images.githubusercontent.com/43195138/236873770-88b2f14e-64c3-4246-a8da-ea9f07240f35.png)
![Screenshot 2023-05-08 at 23 04 51](https://user-images.githubusercontent.com/43195138/236873407-f0bbd454-1b69-4d79-97f7-f2bd33d96b31.png)

I using package version: ^2.7.1 in Chorme v112.0.5615.137
Framework: Nextjs v13.4.1, reactjs v18.2.0

**Comment by sachinchoolur** [comment]
Could you please share a Stackblitz demo where I can reproduce the issue? 

Here is the working demo -https://stackblitz.com/edit/lightgallery-react-update-slides?file=index.tsx

**Comment by Dangtrungphu** [comment]
Do you have example for React.Compoent?
