### ISSUE TITLE
lightGallery doesn't show alt-tags

### ISSUE THREAD

**Issue by tobiasschmitz-prev** [sachinchoolur/lightGallery#1501]
## Description

Image alt-tags will not take over in lightgallery. 
`getCaptionFromTitleOrAlt ` is set to `true` and if i set a title to the image tag it will be rendered as a alt-tag in the gallery.

**Comment by maxray** [comment]
Yeah I have been searching to see if I was missing something, surely alt tags are needed on thumbnails etc.
