### ISSUE TITLE
 Lightgallery Inline videos not working?

### ISSUE THREAD

**Issue by pedrolpz99** [sachinchoolur/lightGallery#1502]
## Description

I have a doubt if it is possible to use the inline lightgallery with videos, I reviewed the codepen of the demo and tried to replicate it in my code but it didn't work for me, am I forgetting to put something or why is it not seen on my page?
I am using React "16.8.6" and lightgallery "2.7.1"

of this codepen support me https://codepen.io/sachinchoolur/pen/NWajJwM?editors=0010

What could be happening, am I forgetting something? I tried several versions of lightgallery and it didn't work for me:
https://codesandbox.io/s/hungry-firefly-mwz3y0?file=/src/App.js

```js
import React, { useState, useRef, useEffect } from "react";
import styled from "styled-components";
import lightGallery from "lightgallery";

import "lightgallery/css/lightgallery.css";
import "lightgallery/css/lg-zoom.css";
import "lightgallery/css/lg-thumbnail.css";

import lgVideo from "lightgallery/plugins/video";
import lgThumbnail from "lightgallery/plugins/thumbnail";


const MyGallery = () => {
  const lgContainerRef = useRef(null);
  useEffect(() => {
    const inlineGallery = lightGallery(lgContainerRef.current, {
      container: lgContainerRef.current,
      dynamic: true,
      plugins: [lgVideo, lgThumbnail],
      dynamicEl: [
        {
          src: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
        }
      ]
    });

    inlineGallery.openGallery();

    return () => {
      lgContainerRef.current.destroy();
    };
  }, []);


  return (
    <>
    <div style={{ paddingBottom: "45%" }} ref={lgContainerRef}></div>
    </>
  );
};

export default MyGallery;

```

### Environment

-   Browser and version - Firefox 112.0.2 (64-bit)
-   OS - Linux - Ubuntu 22.04.2 LTS
-   lightGallery version -  "2.7.1"

**Comment by sachinchoolur** [comment]
You need to import video plugin css file.

`import "lightgallery/css/lg-video.css";`
