### ISSUE TITLE
Incorrect aria-label text

### ISSUE THREAD

**Issue by ddrury** [sachinchoolur/lightGallery#1506]
## Description

Using lightGallery 2.7.1
Wrong text for aria-label

### Steps to reproduce

Open lightGallery, inspect the zoom out button, the aria-label has the text "Zoom in"
I think the error is in src/plugins/zoom/lg-zoom.ts about line 66

**Comment by Wiiolis** [comment]
I'll fix it 🤚

**Comment by ddrury** [comment]
This is not v1 as the bot has labelled it!!

**Comment by ddrury** [comment]
Please reopen
