### ISSUE TITLE
Cannot close lightGallery by clicking on backdrop with rotate plugin enabled

### ISSUE THREAD

**Issue by ddrury** [sachinchoolur/lightGallery#1509]
## Description

[Animated thumbnails demo ](https://www.lightgalleryjs.com/demos/thumbnails/#animated-thumbnails) also displays problem 

### Steps to reproduce

Goto demo as  above open image and try to close by clicking on backdrop

### Environment

-  firefox 113.0.2
-   OS - windows 11 22H2
-   lightGallery version - 2.7.2-beta.0 but no idea of demo page

**Comment by Benzuhaus** [comment]
Taking a look at the source code of the page it looks like the setting for "closable" is set to "!1" which means "false", so this function has been disabled. By default, if you don't add "closable:false" to the settings, the gallery can be closed, as the default value is "true":

"If false user won't be abel to close the gallery at all
This is useful for creating inline galleries."
https://www.lightgalleryjs.com/docs/settings/

**Comment by ddrury** [comment]
not stale

**Comment by ddrury** [comment]
please reopen
