### ISSUE TITLE
Controls not showing

### ISSUE THREAD

**Issue by VascoVisser** [sachinchoolur/lightGallery#151]
I seem to have an issue with the controls. When configuring with lightGallery with `controls: true` the controls are not showing, but no errors. When configuring with `controls:false` the following error occurs:

```TypeError: $prev is undefined1 lightGallery.js:439:20```

Using jquery v1.11.3 (is this version supported?)

**Comment by sachinchoolur** [comment]
Hi,
I have fixed this issue... Please check.

**Comment by VascoVisser** [comment]
Hi Sachin,

The small controls on the bottom show up now and the error is gone, great work! 

One thing I notice is that the big left/right control arrows that used to be there regardless of thumbnails are no longer present. Is this something done on purpose? is there a config option to get those arrows back?
