### ISSUE TITLE
Jquery supported?

### ISSUE THREAD

**Issue by repairmant** [sachinchoolur/lightGallery#1510]
lightGallery v1 supported jquery but I dont see anything about it in v2. Does v2 support jquery or is that something that's still in the works?

**Comment by sachinchoolur** [comment]
Hey @repairmant,

lightGallery v2 does not require jQuery to work. If you want to use jQuery with lightGalelry v2, it is still possible 


```js
 lightGallery($('#lightgallery')[0], {
        plugins: [lgZoom, lgThumbnail],
        licenseKey: 'your_license_key',
        speed: 500,
        // ... other settings
    });
```
