### ISSUE TITLE
Make it possible to overwrite the download behaviour

### ISSUE THREAD

**Issue by KirioXX** [sachinchoolur/lightGallery#1513]
## Summary

It would be great if we could overwrite the download function to pass a custom function that could directly download the file.
This will also enable that we can refresh a signed url for private files.

### Basic example

```js
<LightGallery
                onInit={onInit}
                speed={500}
                plugins={[lgThumbnail, lgZoom]}
                onDownload={(imgData) => customDownload(imgData)}
            >
                <a href="img/img1.jpg">
                    <img alt="img1" src="img/thumb1.jpg" />
                </a>
                <a href="img/img2.jpg">
                    <img alt="img2" src="img/thumb2.jpg" />
                </a>
                ...
            </LightGallery>
```

### Motivation

For security purposes we have to sign our image urls, this breaks the download at the moment because the signing token is only valid for a specific timeframe. Also has the service that we use for storing images a way to directly download a file that we could use.

**Comment by sachinchoolur** [comment]
Hey @KirioXX,

You can remove the existing download button and add your custom button using lightGalery events. 


``` js

// Use `lg-download lg-icon` classnames to make it look like download button
const customButton = `<button type="button" aria-label="Custom download" id="lg-custom-button" class="lg-download lg-icon"></button>`;

$galleryContainer.addEventListener("lgInit", (event) => {
  const pluginInstance = event.detail.instance;

  // Note append and find are not jQuery methods
  // These are utility methods provided by lightGallery
  const $toolbar = pluginInstance.outer.find(".lg-toolbar");
  $toolbar.append(customButton);
  document.getElementById("lg-custom-button").addEventListener("click", () => {
    console.log("custom button click", pluginInstance.index);
  });
});

lightGallery($galleryContainer, {
  // Disable default download button
  download: false
});


```

Demo - https://codepen.io/sachinchoolur/pen/XWaNZeq


If you already have custom download URLs, instead of the above method, you can directly pass the link via `data-download-url` attribute 

https://www.lightgalleryjs.com/docs/attributes/#data-download-url%0a

Let me know if you face any issues

**Comment by KirioXX** [comment]
Thank you very much for the quick response @sachinchoolur.

The button works but is there a way to get some information about the currently open image?
Could I even set custom data-* attributes that I could then use in the button press 
or would I have to update the listener every time the image changes to make that possible?
