### ISSUE TITLE
License key use and protection

### ISSUE THREAD

**Issue by tjk911** [sachinchoolur/lightGallery#1516]
Hello,

We're looking to purchase a license for our organization but before we do - what's to stop someone from copying our license? There was a similar question asked last year that was closed without resolution: #1404

**Comment by sachinchoolur** [comment]
Hey @tjk911,

It is ok even if someone gets your license key. It is invalid without a license agreement. 

The license agreement between You and me is ultimately what governs the use of the library. 
The license key is simply a means of identifying the purchase and does not have a direct impact on the license agreement. So even if someone stole your license key, it wouldn't affect you in any way. 

Let me know if you need any more information from my side

**Comment by Johoseph** [comment]
If this is the case, and only the actual agreement matters, then why do we need to specify the `licenseKey` prop on the Gallery component at all?

Your documentation clearly states a license is required for commercial use - it seems superfluous to need to add this `licenseKey` prop that essentially does nothing but silence a console warning.

**Comment by sachinchoolur** [comment]
Adding the license key via settings helps us validate the purchase when needed. We are building a tool that scraps the source code of any website and finds out the javascript library usage. 

This helps us validate the purchase without making a network call. 

You can see a WIP public version here - https://www.libstracker.com/
