### ISSUE TITLE
360 Degree Viewer for Products

### ISSUE THREAD

**Issue by rimmeh8** [sachinchoolur/lightGallery#1523]
## Summary

An 360° Product Viewer would be cool

### Basic example

Something like this:
https://codyhouse.co/demo/360-degrees-product-viewer/index.html

**Comment by Gar1606** [comment]
I could really use an integration of the above 360 degree viewer. Even a way to dynamically add a completely html entry so I can try to apply turntable.js. I love lightgallery but now I have the problem that I have to add a 360 product viewer and currently I can't seem to get it to work. Any help would be greatly appreciated.
