### ISSUE TITLE
Cannot override muted param with Vimeo video

### ISSUE THREAD

**Issue by dev-newvisibility** [sachinchoolur/lightGallery#1524]
The comment says that Vimeo gives priority to the last parameter when duplicates are found, but this doesn't seem to be true anymore.

https://player.vimeo.com/video/347119375?muted=0&muted=1
https://player.vimeo.com/video/347119375?muted=1&muted=0

https://github.com/sachinchoolur/lightGallery/blob/cfc9a403ec5d0ee1b73103d7250827dc89cf2ba2/src/plugins/video/lg-video-utils.ts#L86

**Comment by mattparlane** [comment]
I just stumbled across this issue, it also affects the autoplay parameter. Any chance of getting this PR merged?
