### ISSUE TITLE
Desktop mouse-wheel zoom / Double tap - pinch-zoom for mobile

### ISSUE THREAD

**Issue by scooterlord** [sachinchoolur/lightGallery#154]
First of all thanks for your wonderful plugin! I have been looking all over for the past week for what your plugin does! 

I saw the preview of v1.2 and it's exactly what I am looking for except the mouse-scroll / double-tap and pinch-zoom functioality for mobile devices. It's what people expect when using mobile!

Looking forward to your answer for implementation!

**Comment by sachinchoolur** [comment]
Hi,
You can use zoom +/- icons for changing the zoom value of the image..
I will add double-tap and pinch-zoom for the mobile devices soon..
Could you please add this in the [comment](http://sachinchoolur.github.io/lightGallery/#comments) section as a feature request. So i can work on new features according to the up votes..

Thanks..

**Comment by thdoan** [comment]
For anyone interested in adding double-tap support while we wait for the official feature to be released, here's my quick patch to lg-zoom.js v1.2.9:

1. Insert this code directly below `'use strict';`:

  ```
  // Double-tap event support
  // Source: https://gist.github.com/attenzione/7098476
  $.event.special.doubletap = {
    bindType: 'touchend',
    delegateType: 'touchend',
    handle: function(event) {
      var handleObj  = event.handleObj,
          targetData = $.data(event.target),
          now        = new Date().getTime(),
          delta      = targetData.lastTouch ? now - targetData.lastTouch : 0;
      if (delta < 350 && delta > 30) {
        targetData.lastTouch = null;
        event.type = handleObj.origType;
        ['clientX', 'clientY', 'pageX', 'pageY'].forEach(function(property) {
          event[property] = event.originalEvent.changedTouches[0][property];
        })
        // Let jQuery handle the triggering of "doubletap" event handlers
        handleObj.handler.apply(this, arguments);
      } else {
        targetData.lastTouch = now;
      }
    }
  };
  ```

2. Replace this line:
  ```
  $image.dblclick(function(event) {
  ```
  with this:
  ```
  $image.on('dblclick doubletap', function(event) {
  ```

**Comment by sammyaxe** [comment]
Mouse wheel zoom would be super useful
