### ISSUE TITLE
Lazyload images and google?

### ISSUE THREAD

**Issue by musicjunk** [sachinchoolur/lightGallery#1550]
Hello, I only know the version 1 of lightgallery. Now in Version 2 there is a lazyload function included, I think.
Normaly common or older lazyload technics causes that google does not list and crawl the images.
I would be interested to know how it works with the included lazyload of lightbox v2? Does it work with SEO?
Can't find it in the docs.

Has anybody experiences with it?
THX

**Comment by sachinchoolur** [comment]
Hi @musicjunk,

lightGallery only lazy loads the slides within lightGallery (Virtual slides). 

You've full control over the thumbnails, and they can be loaded however you want. Hope this answers the questions
