### ISSUE TITLE
include other html?

### ISSUE THREAD

**Issue by comtronix** [sachinchoolur/lightGallery#157]
Thanx for the 1.2 version! 

"Lightgallery custom-html property lets you to include any kind of html in to the lightbox. " 
Is this allready posible?
http://sachinchoolur.github.io/lightGallery/demos/comment-box.html

**Comment by sachinchoolur** [comment]
Yes it is possible. Here is the demo http://sachinchoolur.github.io/lightGallery/demos/captions.html

**Comment by comtronix** [comment]
Is it posible to put an external html/php script in the column like FB comments plugin does?

**Comment by sachinchoolur** [comment]
Currently it is not possible. but you can preload external comments in a hidden div and load into lightgallery by giving the id or classname of your hidden div inside data-sub-html attribute..

If you have any feature suggestion please post it in the [comment](http://sachinchoolur.github.io/lightGallery/#comments) section..
