### ISSUE TITLE
Thumbnails don't function in Firefox 41

### ISSUE THREAD

**Issue by smartcorestudio** [sachinchoolur/lightGallery#158]
http://sachinchoolur.github.io/lightGallery/demos/ - if you open it in FF41 - you'll see the thumbnails, but hothing will happen on thumbnail click. Tested on desktop without touchscreen in Windows 10, Firefox 41. In Chrome and Edge everything is OK. Maybe it's a Firefox bug, I wrote about it in Bugzilla

**Comment by comtronix** [comment]
I use FF 41B to, but works fine here.

**Comment by smartcorestudio** [comment]
@comtronix 
Thank you for reply. I had to reset my Firefox (from the troubleshooting section) to make it work
