### ISSUE TITLE
Switchiing to ESBUILD for angular project showing error

### ISSUE THREAD

**Issue by Saqib92** [sachinchoolur/lightGallery#1587]
## Description
I am switching my Angualr project from weback to ESBuild. and it is throwing error. 

### Steps to reproduce

@import 'lightgallery/scss/lightgallery';

```
src/global.scss:482:18:
[ng]       482 │   background: url("../images/loading.gif") no-repeat scroll cente...
[ng]           ╵                   ~~~~~~~~~~~~~~~~~~~~~~~
[ng] 
[ng]   Preprocessor stylesheets may not show the exact file location of the error.

```

### Additional context

Issue in scss font and images variables. 
After editing manually inside node_modules scss in fotn.scss removed variables and added `../fonts/fontname.ttf` it is working.

**Comment by Saqib92** [comment]
any updates?

**Comment by gzeeel** [comment]
Hi, I'm having the same issue, using Angular v17 and and switching to @angular-devkit/build-angular:browser-esbuild generates this error

![image](https://github.com/sachinchoolur/lightGallery/assets/56316342/a4d9e678-022c-4c15-8488-870157740c36)

**Comment by m-marxxs** [comment]
+1

**Comment by m-marxxs** [comment]
Quick workaround here:

`styles.css`
<img width="322" alt="image" src="https://github.com/sachinchoolur/lightGallery/assets/137128750/aaf1e548-0d84-4f25-8ad2-034168a41215">

And copy from /node_modules/lightgallery/ the folders fonts and images into your angular project assets folder:
<img width="422" alt="image" src="https://github.com/sachinchoolur/lightGallery/assets/137128750/903a3a06-4ca1-41f8-b084-1298cde5e689">

Hope it helps whoever reach this issue.

**Comment by vTodorov** [comment]
+1
