### ISSUE TITLE
Limit zoom factor to actual image size

### ISSUE THREAD

**Issue by smartcorestudio** [sachinchoolur/lightGallery#159]
I think it will be useful to have an ability to limit zoom factor to actual image size. I think a very common usecase for using zoom is not to get blurry upscaled images, but to look at the picture, which is bigger than the screen size, at its actual size (100%, without upscale/downscale)

**Comment by sachinchoolur** [comment]
Hi,
You can double-click on the image to see its actual size. Use zoom plus/minus icon to increase/decrease the zoom value. you can change `scale' value from the settings.. Please post your opinion in the [comment](http://sachinchoolur.github.io/lightGallery/#other-projects) section. So we can decide it according to the up votes..

**Comment by silviaball** [comment]
double-click on the image to see its actual size is not a solution :(

**Comment by danf14** [comment]
Just add:
`var $image = _this.core.$outer.find('.lg-current .lg-image');
            if (scale > $image[0].naturalWidth/$image[0].width) {
                scale = Math.max($image[0].naturalWidth/$image[0].width);
            }`

to callScale at line 117 in zoom.js
