### ISSUE TITLE
Samsung GalaxyTab /  nav. elements not visible

### ISSUE THREAD

**Issue by KlausKerava** [sachinchoolur/lightGallery#16]
Hi,

I Noticed, that close button on the right hand corner and the navigation buttons on the bottom are not visible on Samsung GalaxyTab / Default browser

**Comment by iamqijian414** [comment]
Hi @tammo0 
Sorry to trouble you that I have an issue.When use LightGalley ,it seems work not ok in Android phone.
it will destroy when enableTouch in one seconds.Did you meet same issue?
