### ISSUE TITLE
Question: Can lg support double-click event to trigger  'choosen'  status?

### ISSUE THREAD

**Issue by shawnye** [sachinchoolur/lightGallery#160]
How can I `choose` an image in gallery when double-clicking it using lg? Something like android gallery does

Thank you!

**Comment by sachinchoolur** [comment]
Could you please explain what you mean by `choosen`. Currently when you doubleclick on image it will display in its actual size..

**Comment by shawnye** [comment]
I `choose`  some images togather for further operation , such as deleting, making note, etc

**Comment by hightman** [comment]
I think it is a good idea that toggle state between zoom-in and actual size when double-click the image.

**Comment by smartcorestudio** [comment]
Maybe it's better to add a checkbox in data-sub-html block (see more here: http://sachinchoolur.github.io/lightGallery/demos/captions.html) for selecting images?
Yes, it's very convenient to toggle between zoom states on doubleclick, although I think many users don't know about this possibility.

**Comment by sachinchoolur** [comment]
@shawnye Currently this feature is not available. But you can try something like what @smartcorestudio suggested..

**Comment by shawnye** [comment]
Thank you! I will try.
