### ISSUE TITLE
Type Definitions Missing for lgMediumZoom Plugin Options in TypeScript

### ISSUE THREAD

**Issue by Andyradall** [sachinchoolur/lightGallery#1607]
<h2>Description</h2>
<p>When using <code>lightGallery</code> with the <code>lgMediumZoom</code> plugin in a SvelteKit project, specifying plugin-specific settings such as <code>backgroundColor</code> for <code>lgMediumZoom</code> results in a TypeScript error. This is because the <code>backgroundColor</code> property does not exist in the type <code>Partial&lt;LightGalleryAllSettings&gt;</code>, indicating that the type definitions do not currently support <code>lgMediumZoom</code> plugin options.</p>

<h3>Steps to reproduce</h3>
<ol>
    <li>Initialize <code>lightGallery</code> in a Svelte component with the <code>lgMediumZoom</code> plugin.</li>
    <li>Attempt to set the <code>backgroundColor</code> option within the <code>lgMediumZoom</code> plugin options.</li>
    <li>TypeScript error occurs indicating that <code>backgroundColor</code> does not exist in type <code>Partial&lt;LightGalleryAllSettings&gt;</code>.</li>
</ol>
<p>Unfortunately, I cannot provide a live demo project, but I have included the relevant JS code and sample HTML markup below.</p>

<h3>JS code that you use to initialize lightGallery</h3>
<pre><code>import { onMount } from 'svelte';
import lightGallery from 'lightgallery';
import 'lightgallery/css/lightgallery.css';  
import 'lightgallery/css/lg-medium-zoom.css';
import lgMediumZoom from 'lightgallery/plugins/mediumZoom';

onMount(() => {
    const articleElement = document.querySelector('.attachLightGallery');
    
    if (articleElement instanceof HTMLElement) {
        lightGallery(articleElement, {
            plugins: [lgMediumZoom],
            selector: '.zooming-white-bg',
            licenseKey: 'A7D7BC77-424B-4F41-9D39-CC54DE0C34AC',
            backgroundColor: 'rgba(255,255,255, .985)',
            margin: 104,
            scale: 2,
            zoom: true,
            mediumZoom: true,
            closeOnScroll: true,
            closeOnTap: true, 
            zoomFromOrigin: true,
        });
    }
});
</code></pre>

<h3>Sample HTML markup</h3>
<pre><code>&lt;div class="attachLightGallery"&gt;
    &lt;!-- Images to be zoomed with lgMediumZoom --&gt;
&lt;/div&gt;
</code></pre>

<h3>Environment</h3>
<ul>
    <li>Browser and version: Arc 1.33.0 (Chromium-based)</li>
    <li>lightGallery version: "^2.8.0-beta.1" and tested with "2.7.2" as well</li>
    <li>SvelteKit version: "^2.5.0"</li>
</ul>

<h3>Additional context</h3>
<p>The issue seems to stem from incomplete type definitions for <code>lightGallery</code> settings, particularly when trying to configure options for plugins like <code>lgMediumZoom</code>. This makes it challenging to use <code>lightGallery</code> in TypeScript projects where type safety is a concern, especially in SvelteKit applications.</p>

**Comment by bytesandbots3** [comment]
@Andyradall , Thanks for highlighting the issue with lightGallery and the lgMediumZoom plugin in TypeScript! It seems we missed the types for plugin-specific options like backgroundColor, margin, mediumZoom ..etc . 
Here's a quick fix you can try: extend LightGalleryAllSettings to include the missing properties:


```js
import 'lightgallery';

declare module 'lightgallery' {
    interface LightGalleryAllSettings {
        backgroundColor?: string;
        // Include any other plugin-specific settings here
    }
}
```

This workaround will help you avoid TypeScript errors for now. We're on it, and we'll include the complete types in our next release.
