### ISSUE TITLE
Thumbnail Demo problem

### ISSUE THREAD

**Issue by karaambaa** [sachinchoolur/lightGallery#161]
First of all thank you for your amazing work!

The JavaScript Code for Gallery without animated thumbnails is the wrong one.
It says: $('#aniimated-thumbnials').lightGallery({ thumbnail:true }); 
While it should say: $('#aniimated-thumbnials').lightGallery({ thumbnail:true, animateThumb: false, showThumbByDefault: false}); 

I would have added a pull request, but don't know where the html files are...

**Comment by sachinchoolur** [comment]
Hi,
Thank you for pointing this out. Html files are in the [gh-pages](https://github.com/sachinchoolur/lightGallery/tree/gh-pages) branch.
I'd really if you could submit a pull request for this..

Thanks.
