### ISSUE TITLE
Chrome on Ipad OS 16.6 doesn't display Next/Prev/Close buttons

### ISSUE THREAD

**Issue by nicolasbinet** [sachinchoolur/lightGallery#1617]
## Description

On iPad 16.6, Chrome 123.0.6312 doesn't display Next, Prev and Close buttons, and some others.

### Steps to reproduce

We have the same problem that your dynamic demo is having.
Go to [https://www.lightgalleryjs.com/demos/dynamic-mode/](https://www.lightgalleryjs.com/demos/dynamic-mode/)
Click on Launch gallery

**Not Working on Chrome**
![iPad Os 16 6 Chrome](https://github.com/sachinchoolur/lightGallery/assets/867710/13fe8582-2f03-4ac3-8ed9-4f0990483c1a)

**Working on Safari**
![iPad Os 16 6 Safari](https://github.com/sachinchoolur/lightGallery/assets/867710/7240cbaa-0ef4-4c51-9257-8dea78dc8bbe)

### JS code that you use to initialize lightGallery.

N/A

### Sample HTML markup

N/A

### Environment

-   Browser and version - Chrome 123.0.6312
-   OS - iPad 16.7.7
-   lightGallery version - 2.7.2

**Comment by nicolasbinet** [comment]
@sachinchoolur Can you have a look at this problem.
This doesn't seem to be normal that the button don't appear without any specific configuration.
Thanks for your help.

**Comment by mdh** [comment]
@nicolasbinet same here on iphone 15 latest ios in Safari. Were you able to fix this?

**Comment by mdh** [comment]
For anyone ending up here, you just need to set `mobileSettings: { controls: true, showCloseIcon: true, download: true, }`
