### ISSUE TITLE
amd module ?

### ISSUE THREAD

**Issue by Olegatro** [sachinchoolur/lightGallery#162]
What is meant module in description? I don't see module system. Do you will add amd module ?

**Comment by sachinchoolur** [comment]
Lightgallery is divided into small modules, such as thumbnails, full screen, zoom, etc.
So you don't have to include unwanted code in your document. Include only relevant modules..
It is easy to create your own modules. [Here](http://sachinchoolur.github.io/lightGallery/docs/plugin-api.html) you can find basic structure of lightgallery module.
