### ISSUE TITLE
Suggestion: hidden prev & next buttons on mobile device.

### ISSUE THREAD

**Issue by hightman** [sachinchoolur/lightGallery#164]
I think that almost everyone has accepted that switch images via swipe actions, and never by clicking button.

Further, I also hope to hide all other content except image on mobile devices until tap the screen.

**Comment by hightman** [comment]
That is a simple modification for `lightGallery.js` at L256:
```js
        if (this.s.controls && this.$items.length > 1 && !this.isTouch) {
```

**Comment by sachinchoolur** [comment]
Hi,
We can hide controls by passing `controls: false` via settings.
``` javascript
// Detect touch screen devices 
var isTouch = 'ontouchstart' in window || navigator.msMaxTouchPoints;

// Hide controls if isTouch is true 
$('#lightgallery').lightGallery({
    controls: isTouch ? false : true
});
```

**Comment by hightman** [comment]
OK, this is a good solution, but the code can be simplfy to:
```js
{
  controls: ('ontouchstart' in document)
}
```

**Comment by sachinchoolur** [comment]
:+1:
