### ISSUE TITLE
Problems with opening videos from YouTube.

### ISSUE THREAD

**Issue by AndreyOzeev** [sachinchoolur/lightGallery#1646]
## Description
I encountered the following problem. When opening a YouTube video in a popup, errors appear in the console as shown in the screenshot. 

![XAXTdXY5MC](https://github.com/sachinchoolur/lightGallery/assets/45318750/1bfec1f5-b229-4261-aa03-dc4ca2cdf3bb)

After 15-30 seconds, the video eventually loads, but I would prefer not to have such a long loading time.

### Steps to reproduce

The problem is also observed in the demo at https://www.lightgalleryjs.com/demos/video-gallery/ with the first video featuring a bird.

### Environment

-   Browser and version - Chrome 126,0.6478.127
-   OS - Windows 11 Pro
-   lightGallery version - version as in the demo.

**Comment by nastradalus** [comment]
I believe this issue is still relevant and should not be closed. It's important to keep it open until the author or someone else confirms that the problem has been resolved. The issue might be closed automatically due to inactivity, but it's still an ongoing concern.
