### ISSUE TITLE
HTML5 Video Renders Not Working From Hosted mp4

### ISSUE THREAD

**Issue by jsnow1390** [sachinchoolur/lightGallery#1648]
## Description

When rendering html5 videos from lightGallery from something hosted the gallery for that item ends up being just a black screen for each item. Locally I've gotten one video to load but nothing in succession. Unsure if this problem is just for react or not.

### Steps to reproduce
1. Create a LightGallery component
2. Add more then one mp4 video element to the gallery 
3. Wait for the black screen while scrolling

### JS code that you use to initialize lightGallery.
``` javascript
<LightGallery
                    mode={'lg-slide-circular'}
                    container={galleryContainer}
                    autoplay={false}
                    onInit={onInit}
                    plugins={[lgVideo, zoom]}
                    closable={false}
                    showMaximizeIcon={true}
                    slideDelay={400}
                    appendSubHtmlTo={'.lg-item'}
                    dynamic={true}
                    dynamicEl={content}
                    hash={false}
                    download={false}
                    elementClassNames={'inline-gallery-container'}
                    autoplayFirstVideo={false}
                >
                </LightGallery>

const content = [
        {
            video: {
                source: [{
                    src: 'https://www.lightgalleryjs.com/videos/video1.mp4',
                    type: 'video/mp4'
                }],
                attributes: {
                    preload: 'metadata',
                    controls: true,
                    playsInline: true,
                    muted: true,
                    defaultMuted: true,
                    disablePictureInPicture: true,
                    controlsList: 'nodownload'
                }
            }
        },
        {
            video: {
                source: [{
                    src: 'https://www.lightgalleryjs.com/videos/video1.mp4',
                    type: 'video/mp4'
                }],
                attributes: {
                    preload: 'metadata',
                    controls: true,
                    playsInline: true,
                    muted: true,
                    defaultMuted: true,
                    disablePictureInPicture: true,
                    controlsList: 'nodownload'
                }
            }
        },
        {
            video: {
                source: [{
                    src: 'https://www.lightgalleryjs.com/videos/video1.mp4',
                    type: 'video/mp4'
                }],
                attributes: {
                    preload: 'metadata',
                    controls: true,
                    playsInline: true,
                    muted: true,
                    defaultMuted: true,
                    disablePictureInPicture: true,
                    controlsList: 'nodownload'
                }
            }
        },
        {
            video: {
                source: [{
                    src: 'https://www.lightgalleryjs.com/videos/video1.mp4',
                    type: 'video/mp4'
                }],
                attributes: {
                    preload: 'metadata',
                    controls: true,
                    playsInline: true,
                    muted: true,
                    defaultMuted: true,
                    disablePictureInPicture: true,
                    controlsList: 'nodownload'
                }
            }
        }
];
```

### Additional context
Locally I can get the first video to load but nothing else. 
When dubugging the code I'm noticing things failing in `getVideoHtml()` where it is looking for 
`var videoInfo = this.core.galleryItems[index].__slideVideoInfo || {};` Only one of them listed above is getting that __slideVideoInfo added to it. The others seem to be undefined? Additionally the index always seems to be 0 which doesn't seem right 

 "lightgallery": "^2.7.2",

https://github.com/user-attachments/assets/8cb1578b-6bd3-4524-b6fb-8a3d1e27afe1

**Comment by jsnow1390** [comment]
I'll just reopen it if it goes stale. Maybe eventually it'll get looked at

**Comment by digitalaffinity-au** [comment]
I'm getting the same problem with mp4

**Comment by jsnow1390** [comment]
Comment bump. I'll just reopen it if it goes stale. Maybe eventually it'll get looked at

**Comment by brian-stoker** [comment]
perhaps a better chance is the v1 label wasn't there.. this is clearly v2.. i was able to repro this when i created content with only the video objects as you have.. i get a different issue which is what i was looking for a solution for when i include poster, thumb, and subHtml alongside the video object like:

` {
    poster: 'https://cenv-public.s3.amazonaws.com/normal-guy.png',
    thumb: 'https://cenv-public.s3.amazonaws.com/normal-guy.png',
    subHtml: `<h4>Normal Guy</h4><p>by Chase, Anthony, and Brian Stoker</p>`,
    video: {
      sources: [
        { src: 'https://cenv-public.s3.amazonaws.com/normal-guy.mov', type: 'video/quicktime' },
      ],
      attributes: {
        preload: 'metadata',
        controls: true,
        playsInline: true,
        muted: true,
        defaultMuted: true,
        disablePictureInPicture: true,
      },
    },
  }`
