### ISSUE TITLE
Bug: crash in quick swipe when current or preload images are not fully loaded in iOS safari.

### ISSUE THREAD

**Issue by hightman** [sachinchoolur/lightGallery#165]
I open the following demo URL in my iPhone 6plus.
<http://sachinchoolur.github.io/lightGallery/demos/index.html>

Then I fast continuous swipe the gallery, the safari may crash. It seems the preload images still not fully loaded, and more number of images in gallery.

I know this question is more difficult to debug, but it is easy to reproduce.

**Comment by sachinchoolur** [comment]
Hi,
Is this just closing the gallery or completely crashing the browser? 
It works just fine in my android phone. 
Any help with this issue would be much appreciated because i don't have an iphone to test this issue..

**Comment by hightman** [comment]
Both cases can happen, but more just re-open the page automatically and show a abnormal shutdown tip at the page top.

I think it is not a simple problem about javascript code, It only occurred when there are more images,  such as greater than 15.

I had tried to debug by connecting iPhone to Safari on Mac, but all informations are erased after crash.

**Comment by sachinchoolur** [comment]
I believe this is because of css animations. Could you please pass `useLeft: true` via settings and test this once again. So lightgallery will use left property instead of translate for animations

**Comment by hightman** [comment]
Unfortunately, when I set the option `useLeft` to `true`, almost 100% crash during swipe left.

> Note: This case happens in more images, I use 20 image to test.

**Comment by vestaxpdx** [comment]
I have also been getting crashes on iOS 8 and beta 9 on iPad and iPhone where the browser completely reloads. Some with less than 10 images. The overall swiping seems to be very laggy for some reason. Android I have never had an issue.

The message is `A problem occurred with this web page so it was reloaded`

**Comment by maarcin** [comment]
Same as #152

**Comment by philippebarbosa** [comment]
Hi all,
i'm facing the same problem on my website, gallery crash when using iOs 8.4.1 on iPhone 6Plus. `useLeft` doesn't fix anything..

**Comment by jochienabuurs** [comment]
Please try the following setting:

    useCSS: false,

**Comment by sachinchoolur** [comment]
https://github.com/sachinchoolur/lightGallery/issues/188#issuecomment-150906371
