### ISSUE TITLE
mode:Slide causes multiple images to show in lightGallery

### ISSUE THREAD

**Issue by macsupport** [sachinchoolur/lightGallery#166]
It seems "Slide" should be "lg-slide" in mode options?

**Comment by sachinchoolur** [comment]
Yes. You have to use `lg-slide` for slide transition.
[Here](http://sachinchoolur.github.io/lightGallery/demos/transitions.html) is the demo for multiple transitions

**Comment by macsupport** [comment]
Yes, but you list Slide under mode options not lg-slide. My initial point.

**Comment by sachinchoolur** [comment]
Oh, thank you pointing this out..
I have updated the docs..
