### ISSUE TITLE
Thumbnails not over the image but under it

### ISSUE THREAD

**Issue by smartcorestudio** [sachinchoolur/lightGallery#167]
I think we can 2 major scenarios using thumbnails:
1) If thumbnail are hidden by default (`showThumbByDefault: false`) it seems logical that we have thumbnail container over the image
2) But if thumbnails are visible by default we have to hide it if we want to see the bottom part of the image and the caption. It can be annoying, and I had to add some extra paddings to image container in css to make thumbnails not overlap the image. It works (see picture 1), but the only small problem is that if user hide thumbnails, image height doesn't change (see picture 2). The solution here can be to add some class which adds bottom padding to image container when the thumbnails are visible and to remove this class when the thumbnails are hidden.
![2015-08-30 10_49_23- 100](https://cloud.githubusercontent.com/assets/2891792/9566253/fc3c61ba-4f06-11e5-85de-0b55f6a2122d.png)
![2015-08-30 10_49_23- 100](https://cloud.githubusercontent.com/assets/2891792/9566269/56b81594-4f07-11e5-8dc7-beb4dff14df9.png)

What do you think about it& Is it a good idea or not?

**Comment by hightman** [comment]
In fact, I think it does not matter.
It is strongly recommended that you set the option `showThumbByDefault` to false, the effect is better.

**Comment by smartcorestudio** [comment]
@hightman why do you recommend this?

**Comment by sachinchoolur** [comment]
Hi,
You can use `.lg-thumb-open` class for this purpose. It is already available.
``` css
.lg-thumb-open .lg-img-wrap {
    padding-bottom: 100px;
}
