### ISSUE TITLE
Error when trying to Play Vimeo or YouTube Videos

### ISSUE THREAD

**Issue by vestaxpdx** [sachinchoolur/lightGallery#175]
Hi,

Simply the best light gallery plugin out there. Amazing work!

I am facing an odd issue. Maybe I have missed something obvious but here goes.

Basically the gallery loads up fine, but when I go to press play on either vimeo or youtube video the video never gets loaded. Firebug throws the following error:

```
TypeError: a is undefined
..."data-html"),!a&&c)return{html5:!0};var d=a.match(/\/\/(?:www\.)?youtu(?:\.be|be...
```

My HTML markup is:

```
<a href="https://www.youtube.com/watch?v=SF2s7BKa2Ww" class="lightgallery" data-poster="my_image.jpg">
       <img src="some_image.jpg" />
</a>
```

I am using the latest lightgallery-all.min.js and setting up the plugin as follows:

```
$('body').lightGallery({
        selector: '.lightgallery',
        download: false
});
```

Any ideas? Everything else works fine it is literally when trying to actually play video in the gallery.

**Comment by sachinchoolur** [comment]
Hi,
This could be issue with selector.
If you want to open gallery from single tag you can just pass `selector:'this'` via settings.
``` javascript
$('.lightgallery').lightGallery({
        selector: 'this'
});
```
Please let me know if you still face any difficulty..

**Comment by vestaxpdx** [comment]
Hmm using your suggestion still does not work. This time the gallery opens but nothing happens when you try and press play. No errors in firebug too.

Sorry I was not clear with my situation, I have an array of images and videos with class `'.lightgallery'` so using your suggestion only shows one picture/video at a time when you click on it.

I use the following as it collects them all up into a gallery when you click on any picture/video with the `.lightgallery` class.

I have tried with just one video in case it was because of the mix of images and video, but still the same error happens

```
$('body').lightGallery({
        selector: '.lightgallery',
        download: false,
        exThumbImage: 'data-lg-thumb',
});
```

````
<a class="lightgallery" href="full_image.jpg" data-lg-thumb="thumb_image.jpg" data-sub-html="My Caption">
       <img src="some_image.jpg" />
</a>
<a href="https://www.youtube.com/watch?v=SF2s7BKa2Ww" class="lightgallery" data-poster="my_image.jpg">
       <img src="some_image.jpg" />
</a>
...
````

**Comment by sachinchoolur** [comment]
did you include lg-video.js in your document?
It would be helpful if you could provide a jsfiddle demo for your setup..

**Comment by vestaxpdx** [comment]
Ok after a lot of debugging. I finally got it working as I saw by running the non min version of `lightgallery-all.js` it was throwing this error.

```
TypeError: src is undefined
var youtube = src.match(/\/\/(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=|embed...
```
So by adding data-src="" to the link tag with the video in it started working.
```
<a data-src="https://www.youtube.com/watch?v=SF2s7BKa2Ww" class="lightgallery" data-lg-thumb="thumb_image.jpg" data-poster="my_image.jpg">
   <img src="some_image.jpg" />
</a>
```
I was using your example here: http://sachinchoolur.github.io/lightGallery/demos/videos.html which only shows using the href, but it seems your code ignores href for videos?

At least it's working now :)

**Comment by cyberwani** [comment]
I face the same issue and solved as per @vestaxpdx's step.

**Comment by sachinchoolur** [comment]
The issue has been fixed..
Thanks..

**Comment by cyberwani** [comment]
Thanks @sachinchoolur :smile:
