### ISSUE TITLE
Esc key does not close gallery if thumbs are active

### ISSUE THREAD

**Issue by slantchev** [sachinchoolur/lightGallery#176]
Is this the intended behavior? I removed the test for the thumbs being open in my local copy, and Esc now closes the gallery as expected (when enabled).

**Comment by sachinchoolur** [comment]
Hi,
I have fixed this issue. On first escape key press lightgallery will close it's thumbnails and gallery will be closed on second escape key press if thumbnail is already opened. Otherwise gallery will be closed on first escape key press..

**Comment by cfxd** [comment]
Hi there, on the latest build with a simple `lightGallery()` init the escape key has no effect unless I manually close the thumbnail gallery.

**Comment by svetozarsadecky** [comment]
Esc button wont close the gallery on first esc keypress if thumbnails are enabled and toggle is false. 
I can only guess that there is a way to remove the necessity to double press esc for the gallery to close. 
Else it is not a very good design choice to force users not being able to change this behaviour.

**Comment by sachinchoolur** [comment]
@svetozarsadecky,
Making this configurable would be a minimal change. I can add it in the next version
