### ISSUE TITLE
Image Captions (sub-html) not showing when toggleThumb is false

### ISSUE THREAD

**Issue by AlexRieger** [sachinchoolur/lightGallery#177]
When you set toogleThumb (misspelled btw.) to false then you'll never get to see the Caption because the lg-sub-html class div sits behind the lg-thumb-outer class div.
This is because lg-sub-html has a fixed position and bottom 0. Bottom should be the height of lg-thumb-outer to fix it.

**Comment by AlexRieger** [comment]
Not to be too negative: Besides that I love version 1.2! <3

**Comment by vestaxpdx** [comment]
Hi,

I came across this issue too. I dealt with it by using the following CSS/JS

CSS
```
.lg-sub-html{
bottom: 100px;
}
```
JS
```
$(document).on('click', '.lg-toogle-thumb', function()
    {
        if($('.lg-sub-html').css('bottom') == '0px')
        {
            $('.lg-sub-html').animate({bottom: '100px'}, 'slow');
        }
        else
        {
            $('.lg-sub-html').css('bottom', '0px');
        }    
    });
```

It would be cool if you could do a pure CSS solution where it always sits on top of the thumbs.

**Comment by smartcorestudio** [comment]
Nearly the same issue was already decribed here: https://github.com/sachinchoolur/lightGallery/issues/167

**Comment by vestaxpdx** [comment]
Cool, doh didn't notice the lg-thumb-open class!

**Comment by AlexRieger** [comment]
Using Extra-CSS for .lg-open-thumb .lg-sub-html and .lg-thumb-open .lg-img-wrap solved my problem. But shouldn't this be standard css when toggleThumb is false? If you can't hide the thumbnails why put content behind it?

**Comment by sachinchoolur** [comment]
Hi guys,
I have added the above css provided by @smartcorestudio if `toggleThumb` is false and `animateThumb` is true.
