### ISSUE TITLE
Use Native Scrolling for Touch Devices on Thumbnails

### ISSUE THREAD

**Issue by vestaxpdx** [sachinchoolur/lightGallery#178]
Hi,

If you set  `enableThumbSwipe: false` and use the following CSS the thumb scrolling is WAY smoother than the JS method.

```
.lg-thumb-outer {
 overflow-x: auto !important;
-webkit-overflow-scrolling: touch !important;
}
```

However this breaks the animation of the thumb position and clicking a thumb does not go to that gallery image. It sort of tracks but it's all out of line if you scroll loads then start going through the gallery it does not return to the active thumb.

In my opinion there is no need for enableThumbSwipe option, the JS it creates is no way near as smooth as just using native scrolling for the device.

Can this be added so the thumbs still track correctly with `-webkit-overflow-scrolling: touch`?

**Comment by scooterlord** [comment]
+1

**Comment by NathanWalker** [comment]
+1  I may be able to help look into this one. I'm working on a couple bug fixes for `dynamic` mode at moment. May look into this over the next week as well.

**Comment by vestaxpdx** [comment]
Hi any update on this? Would be great to have :)
