### ISSUE TITLE
TypeError: src is undefined

### ISSUE THREAD

**Issue by comtronix** [sachinchoolur/lightGallery#180]
Image popup is not showing, the screen blackouts, hangs and getting error:

TypeError: src is undefined
var youtube = src.match(/\/\/(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=|embed...
lightgallery.js (line 395, col 12)

Used code:
```
<ul id="grid">
    <li>
        <figure>
            <a href=\"http://www.website.com/albums/".$row['AlbumFolder']."/".$row['Filename']."\" data-sub-html=\"<h4>title</h4><p>information</p>\">
                <img src=\"{$row["Thumb"]}\" />
            </a>
        </figure>
    </li>
</ul>

$('#grid').lightGallery();

**Comment by vestaxpdx** [comment]
Are you trying to play a video? If so you need to add data-src with the video URL to the A tag as well for video to work.

https://github.com/sachinchoolur/lightGallery/issues/175

**Comment by comtronix** [comment]
No video, just image

**Comment by sachinchoolur** [comment]
Hi,
By default `data-src/href` attribute should be provided to the direct child elements.So either you can provide `data-src/href` attribute for the `li` or change the selector object via settings

``` javascript
$('#selector1').lightGallery({
    selector: 'li a '
})
```
