### ISSUE TITLE
Strange zoom behaviour in Firefox

### ISSUE THREAD

**Issue by smartcorestudio** [sachinchoolur/lightGallery#182]
Don't know how to explain, maybe this video can do it better: http://youtu.be/6f70bKlFtN0?hd=1
Everything is OK in Chrome. Tested on this page: http://sachinchoolur.github.io/lightGallery, Firefox 41, Windows 10, 1600х900

**Comment by sachinchoolur** [comment]
Hi,
Thanks for the video. The issue has been fixed.
