### ISSUE TITLE
Videos that contain underscores and other special characters error on load

### ISSUE THREAD

**Issue by commanderZiltoid** [sachinchoolur/lightGallery#183]
When including videos that contain underscores or special characters they error out. For example the following two links cause the error in the attached image (when i noticed the underscore was causing an issue I attempted to substitute url encoded character):

//www.youtube.com/watch?v=QV2aIzzg_ZI
//www.youtube.com/watch?v=QV2aIzzg%5FZI
![lightgallery_video_error](https://cloud.githubusercontent.com/assets/8580531/9768599/55b999d4-56ea-11e5-845f-b5a235f98596.png)

While these links work as expected:
//www.youtube.com/watch?v=oHMT5grGkKo
//www.youtube.com/watch?v=zI8X4twpgMc

**Comment by commanderZiltoid** [comment]
This issue is due to line 395 of lightgallery.js. The regex does not allow for underscores or percentage signs. I changed this:

var youtube = src.match(/\/\/(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=|embed\/)?([a-z0-9\-]+)/i);

To this:

var youtube = src.match(/\/\/(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=|embed\/)?([a-z0-9\-\_\%]+)/i);

**Comment by sachinchoolur** [comment]
Hi,
The issue has been fixed in 1.2.4..
Thank you for bringing this up.. :+1:
