### ISSUE TITLE
Constrain slideshow to a specific div

### ISSUE THREAD

**Issue by hiralatcal** [sachinchoolur/lightGallery#185]
How do I constrain the slideshow to launch inside a specific element. I'm adding a bunch of widgets on a page and I'd like to auto start the slideshow within a widget (div).

Thanks in advance.

**Comment by sachinchoolur** [comment]
Hi,
You can try appending the lightgallery [templates](https://github.com/sachinchoolur/lightGallery/blob/master/src/js/lightgallery.js#L280) and [backdrop] (https://github.com/sachinchoolur/lightGallery/blob/master/src/js/lightgallery.js#L249) into your div instead of body.
