### ISSUE TITLE
video full screen is not working on chrome 

### ISSUE THREAD

**Issue by essaomar** [sachinchoolur/lightGallery#186]
when you click html5 video to go full screen in chrome its not working and displays this warning in the console: 
"requestFullscreen() is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details."

and the video js its says 
'webkitMovementX' is deprecated. Please use 'movementX' instead.
video.js:9 'webkitMovementY' is deprecated. Please use 'movementY' instead.

can you pls take a look.
thanks

**Comment by essaomar** [comment]
actually its every video in the demo site its not going into fullscreen even the youtube ones its seems the lightgralley iframe is not allowing it properly and this behavior is only in chrome i have tested firefox and edge and they are fine.

**Comment by uakhan** [comment]
Yes, I noticed that as well.

Then I discovered this:

lightgallery.css | line:751
.lg-css3.lg-use-css3 .lg-item {
  will-change: transform, opacity;
}

Removing above fixed it for me on chrome, not tested anywhere else.

**Comment by essaomar** [comment]
thank you so much, uakhan. that fixed for me too,

**Comment by MarcosBL** [comment]
Saved me, thank you !
