### ISSUE TITLE
Browser crashes on iOS 8.4.1 when opening lightgallery with more then +- 30 images

### ISSUE THREAD

**Issue by jochienabuurs** [sachinchoolur/lightGallery#188]
I've created a lightgallery with some images for testing purposes.
See: http://codepen.io/jochemnabuurs/pen/bVpgzV

When limiting the gallery to 5 images it works perfect. At +- 15 images, it gets a bit laggy, and more than +- 30 images makes the browser crash.

Tested on iPhone 5 and iPad 2 (both with iOS 8.4.1), using Safari and Chrome.

On a Samsung Galaxy tab 4 with Android 5.0.2, chrome doesn't crash but it also doesn't respond.

My best guess is that there is a memory leak somewhere but so far I couldn't pinpoint the issue.

**Comment by jochienabuurs** [comment]
I saw this issue is already present under https://github.com/sachinchoolur/lightGallery/issues/102

Still relevant...

**Comment by jochienabuurs** [comment]
And also present under https://github.com/sachinchoolur/lightGallery/issues/114

I applied the fix that is described in there, and that solved the problem.

**Comment by gurumark** [comment]
I could not find useCSS option in lightgallery.js

**Comment by jochienabuurs** [comment]
@gurumark, the #114 fix is for an older version. Have you tried the following setting:

    useLeft: true

**Comment by jochienabuurs** [comment]
@sachinchoolur to shine some light on the underlying issue: 
http://stackoverflow.com/questions/17824060/ios-safari-runs-out-of-memory-with-webkit-transform

As far as i can tell, two situations can cause the crash:
- the width and amount of thumbnails
- the width and preload of the main image

they both have a direct effect on the translate3d() x-axis value of its container and can cause the the container to exceed the limit mentioned in the article.

**Comment by sachinchoolur** [comment]
Hi @jochienabuurs,
It is clear that the issue is with css transform. Could you please test this once again with settings ```startClass: '', useLeft: true.```So Lightgallery will avoid the zoom animation while opening each image.

Please let me know if there are any improvements. Otherwise as you suggested i will have to change the structure of lightgallery and keep only three images/videos at a time inside the gallery..

**Comment by MattXcz** [comment]
Still craching on iPad mini ios 8.4.1 and iPhone 4S with iOS9 (tried useLeft: true, useCSS: false)
can you fix this bug ?

**Comment by sachinchoolur** [comment]
Thanks @MattXcz,
I don't have an ipad to check this issue.. Could you please check this once again with `startClass: '', useLeft: true`. Also please disable thumbnails and pager options..

**Comment by MattXcz** [comment]
still craching... but only on iPad, on iPhone 4S it works.

**Comment by jsieber-aca** [comment]
Chrome on Android is crashing for me as well for galleries with more than 20 images. Using the following settings including a smaller image defined in the data-responsive-src attribute.
$("#lightGallery").lightGallery({
                        startClass: '',
                        thumbnail:false,
                        animateThumb: false,
                        showThumbByDefault: false,
                        download: false,
                        hideControlOnEnd: true,
                        loop: false, 
                        useLeft: true,
                        autoplay: false,
                        autoplayControls: false,
                        fullScreen: false,
                        zoom: false,
                        mobileSrc : true
                    });

**Comment by sachinchoolur** [comment]
Hi,
The issue has been fixed. Please use the latest version of lightgallery.
I have checked this issue on iphone6 (iOS v9.0.2) and works fine with more than 500 images..
![img-20151025-wa0009](https://cloud.githubusercontent.com/assets/6586706/10715025/807f213c-7b2c-11e5-84f8-fbabe719e1b6.jpg)
