### ISSUE TITLE
Sub-html dynamic variable gives error

### ISSUE THREAD

**Issue by gurumark** [sachinchoolur/lightGallery#189]
I think Javascript does not line '-' in variable names and gives identifier error. It should be subHtml.

Secondly, there should be an option to use a "selector" for captions instead of unique identifier for caption div. For example div.caption for all captions. The plugin code should select the block under <img> to switch to the right caption.

**Comment by sachinchoolur** [comment]
Hi,
I have updated the docs. It was a typo :)
Currently selector for captions feature is not available. I will let you know if i include this feature..
