### ISSUE TITLE
Problem when use video gallery with only one video

### ISSUE THREAD

**Issue by amon81** [sachinchoolur/lightGallery#190]
Hi, i've found this problem when in the gallery is present only one movie.
The video player doesn't start. The problem is risolved for me append after call lightgallery plugin with a trigger
$('#lightgallery').on('onAfterOpen.lg',function(){
				    	 setTimeout(function () {
				    		$('.lg-video').on('click',function(){
				    			$('#lightgallery').trigger('onSlideClick.lg');
				    		});
				    	}, 50);
		            } );
With one movie you don't run method "enableDrag" etc that contains the trigger on EventCustom "onSlideClick.lg"

**Comment by sachinchoolur** [comment]
Hi,
Thank you for pointing this out. The issue has been fixed..

**Comment by essaomar** [comment]
we have a problem yet here, the one video will play but not pause it when you click pause button or click inside the video. and every browser is the same. so can you guys take look your code and help with pause event. thanks
