### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Tharickahamed** [sachinchoolur/lightGallery#191]
Including social share option?

**Comment by sachinchoolur** [comment]
Hi, 
Currently i don't have a demo for this. But you can try including the buttons inside data-html attribute..

**Comment by srjlulla** [comment]
You can use https://www.addthis.com sharing tools. 

Add 

```
<script type="text/javascript">
// always refresh on URL change
window.addEventListener("hashchange", function () {
  addthis.layers.refresh();
});
</script>
```

before the </body> tag to make sure that URLs are relevant. If you want to show sharing icons only in the lightbox, add the following to your CSS:

```
body > div > div#at-share-dock {
    visibility: hidden;    
}

body.lg-on > div > div#at-share-dock {
    visibility: visible;    
}
```
