### ISSUE TITLE
Image margin/padding asymmetrical

### ISSUE THREAD

**Issue by sterrier** [sachinchoolur/lightGallery#192]
When the image displayed is larger than the browser window, there is a 10px margin on the left of the image and 0px on the right. From what I understood in the css, it should be 5px on each side.

Great work! Thanks

![2015-09-23_105457](https://cloud.githubusercontent.com/assets/14801789/10041056/9db3d978-61e1-11e5-8444-ed4468f6c11d.png)

**Comment by sachinchoolur** [comment]
Hi,
Thank you for pointing this out..
I have fixed this issue..
