### ISSUE TITLE
Social share button

### ISSUE THREAD

**Issue by bohdanafanasyev** [sachinchoolur/lightGallery#196]
Greetings, is there a way to add a social share button to the link of the page with gallery or any desired link to be shared inside the gallery?

**Comment by willianrodrigues** [comment]
Adding a share button would be great.

**Comment by srjlulla** [comment]
You can use https://www.addthis.com sharing tools. 

Add 

```
<script type="text/javascript">
// always refresh on URL change
window.addEventListener("hashchange", function () {
  addthis.layers.refresh();
});
</script>
```

before the </body> tag to make sure that URLs are relevant. If you want to show sharing icons only in the lightbox, add the following to your CSS:

```
body > div > div#at-share-dock {
    visibility: hidden;    
}

body.lg-on > div > div#at-share-dock {
    visibility: visible;    
}
```

**Comment by sachinchoolur** [comment]
Ya sure. I will add it when i get time.

**Comment by Kirstenbr** [comment]
Hi Sachin,
I too am looking for this feature and have sent you an email... I see you have it incorporated for the .js version...  would it be very difficult to add it to the jquery version?

This plugin looks really great (still tweaking the settings) and the only thing lacking that would make it really fantastic is the social media sharing!  Thanks,  Kirsten

**Comment by HamzaAbdullahMoh** [comment]
I believe it would be a great idea, **lg-share.js** and some options to tweak it.

**Comment by sachinchoolur** [comment]
Hi Guys,
I've added share module.
[GitHub:](https://github.com/sachinchoolur/lg-share) https://github.com/sachinchoolur/lg-share
[Demo:](http://sachinchoolur.github.io/lightGallery/demos/share.html) http://sachinchoolur.github.io/lightGallery/demos/share.html
[Docs:](http://sachinchoolur.github.io/lightGallery/docs/api.html#lg-share) http://sachinchoolur.github.io/lightGallery/docs/api.html#lg-share

**Comment by MatrixOfDeath** [comment]
Is there a way to add Linkdin to this lg-share plugin ?
