### ISSUE TITLE
problems with gallery

### ISSUE THREAD

**Issue by schel4ok** [sachinchoolur/lightGallery#200]
I have problem with the code below. Every link is working separately, but there is no gallery functional - it is not possible to switch images in lightbox mode.
Maybe there is special option that I need to enable.

~~~
<div class="links">
	<a href="/img/furnitura/T-102-12-dwg.jpg" class="dwg"><i class="fa fa-pencil"></i> Чертежи</a>
	<a href="/img/furnitura/T-102-12-dwg-2.jpg" class="dwg">Чертежи</a>
	<a href="/img/furnitura/T-102-12-dwg-3.jpg" class="dwg">Чертежи</a>
</div>
~~~

~~~
$('.dwg').lightGallery({
    selector: 'this'
});
~~~

**Comment by sachinchoolur** [comment]
Hi,
In this situation no need to set any custom selector property. [Here](http://sachinchoolur.github.io/lightGallery/demos/html-markup.html) you can find more details about custom selectors..

You can use the following code..
``` javascript 
$('.links').lightGallery();
```
