### ISSUE TITLE
URL simbol  youtube, bug

### ISSUE THREAD

**Issue by bibi-babi** [sachinchoolur/lightGallery#202]
I wanted to report a bug I found.
using a url where the video ID all'iterno contains a "_". The video does not load.
IDs with a _ inside are unusual, but may be generated due to a particular name in the video uploaded.

eg video url problem:  
https://youtu.be/_F5U3vwO2KM

I do not know what the problem is, but I will alert you to security.

through the gallery,
by Barbara

**Comment by MarcosBL** [comment]
That ID isn't there anymore, but I can confirm same happened to me today with https://www.youtube.com/watch?v=y4al_-D2iLk

I'm loooking into it

**Comment by bibi-babi** [comment]
I'm sorry, the plugin has been cleared for compatibility issues with plugins. however, any video with " _ "
while " - " there are problems.

**Comment by MarcosBL** [comment]
Fixed in 1.2.4 as per https://github.com/sachinchoolur/lightGallery/issues/183

**Comment by sachinchoolur** [comment]
Hi,
Sorry for the delayed response. The issue has already been fixed. Please use latest version of lightgallery..
