### ISSUE TITLE
Autplay dosn't work on Safari 9

### ISSUE THREAD

**Issue by urre** [sachinchoolur/lightGallery#205]
Hi,

I can't get autoplay working in Safari 9 when using HTML5 video. I made this codepen http://codepen.io/urre/pen/YyxEPO

**Comment by srowatt** [comment]
try adding this after you initialise the lightgallery
```javascript
var $video = $('#vid');
$video.on('canplaythrough', function() {
   this.play();
});
```

**Comment by sachinchoolur** [comment]
Related to https://github.com/sachinchoolur/lightGallery/issues/347
