### ISSUE TITLE
Multiple Galleries

### ISSUE THREAD

**Issue by bartoloffm** [sachinchoolur/lightGallery#209]
I tried to create 2 dynamic galleries as follows:

HTML:
<button class="btn" id="btn-moxshow">Launch Gallery I</button>
<button class="btn" id="btn-pixshow">Launch Gallery II</button>

JS:
$('#btn-pixshow').on('click', function(){
	$(this).lightGallery({
		dynamic: true,
		dynamicEl: pictures
	});    
});

$('#btn-moxshow').on('click', function(){
	$(this).lightGallery({
		dynamic: true,
		dynamicEl: videos
	});     
});

where 'pictures' and 'videos' are 2 arrays of objects.

Now something strange happens when I do as follow:
1. I open the 1st gallery = all works perfectly;
2. I close the 1st gallery and open the 2nd gallery = again all works fine;
3. I close now the 2nd gallery and open the 1st gallery again = here is the problem, the gallery will open but it will show only the loading gif!?

Could you help me please with this? I would be very greatful! Anyway amazing stuff, I thank you for that!

**Comment by CJEdgerton** [comment]
I had the same issue, see <a href="http://sachinchoolur.github.io/lightGallery/docs/api.html#lg-hash">this section of the docs</a>. You need to add a galleryId to each gallery.

<pre>
<code>
$('#btn-pixshow').lightGallery({
dynamic: true,
dynamicEl: pictures,
galleryId: 1
});

$('#btn-moxshow').lightGallery({
dynamic: true,
dynamicEl: videos,
galleryId: 2
});
</code>
</pre>

**Comment by bartoloffm** [comment]
I overlloked at that part, but now it works perfectly, thank you so much for your help, very nice!

**Comment by shamw4r** [comment]
When i get images with ajax its give me error " TypeError: a is undefined " But if i add hard code link of images like this in  "   dynamicEl:[{"src": "mlphotos/imgs/564d982d2bed1_kosta.jpg","thumb": "mlphotos/imgs/564d982d2bed1_kosta.jpg",}] "  Then its working fine, 

-> But i want to load images with ajax below are my code

Below are my code help me what is the issue here??

$.ajax({
		url: "ajax_viewlarge_click" ,
		type: 'POST',
		dataType:"json",
		success: function(data) {
			//-------------------------
			dynamicphoto = '';
			for (var i = 0; i < data.length; i++) {
				dynamicphoto += '{"src": "'+data[i]+'","thumb": "'+data[i]+'",},';
			}
			$.getScript($('#baseUrl').val()+"/application/layouts/scripts/themes/trailblazer/js/lg/lightgallery.min.js", function( datas, textStatus, jqxhr ) {
				var pictures = "["+dynamicphoto+"]";
				$(this).lightGallery({
					dynamic: true,
					html:true,
					dynamicEl:pictures
				});
			});
		},
		error: function(e) {
			console.log("Server failure! Is the server turned off?");
		}
	});
