### ISSUE TITLE
Pause youtube videos when changing slide

### ISSUE THREAD

**Issue by alias1** [sachinchoolur/lightGallery#21]
Not 100% if this is already possible by an option, but I noticed on the demo's that youtube videos keep playing in the background when you click next/prev.

This can be controlled with the [Youtube JS API](https://developers.google.com/youtube/js_api_reference) / [this stackoverflow post](http://stackoverflow.com/questions/8667882/how-to-pause-a-youtube-player-when-hiding-the-iframe), and could easily be manually added into the onSlideBefore / onSlideNext / onSlidePrev handlers, though it feels like something that would be good to support by default with an option.

Thoughts?

**Comment by kowalski90** [comment]
This feature would indeed be very useful. Those less savvy internet users just assume that by clicking on another video, the previous one playing will stop playing, just like it's happening on YouTube. 

Another option would be to start the video automatically once clicked from the thumbnail, or when clicking next/previous arrows.

Please consider this. Thank you!

**Comment by HybridSolutions** [comment]
Any development on this issue? Thanks :)

**Comment by q2apro** [comment]
Jumping into the train as well. LightGallery is great, but this missing feature is "confusing" to users. Everybody assumes that the other video stops automatically when navigating to the new one.

**Comment by q2apro** [comment]
If you are not using `videoAutoplay:true` then you can use this workaround to stop the videos: 

	$(document).ready(function() {
		$('#videoliste').lightGallery({
			videoAutoplay: false,
			onSlideNext: function() { 
				$('iframe[src*="youtube.com"]').each(function() {
					var src = $(this).attr('src');
					$(this).attr('src', '');
					$(this).attr('src', src);
				});
			}
		});
	});

If `videoAutoplay:true` then the first video will start immediately again after the `src` has been assigned again.

**Comment by q2apro** [comment]
Okay, here is a clean implementation that pauses all youtube videos if previous or next is clicked. It works with `videoAutplay:true` as well: 

	$(document).ready(function() {
		$('#videolist').lightGallery({
			videoAutoplay: true,
			youtubePlayerParams: {
				enablejsapi:1,
			},
			onSlideNext: function(el) { 
				pauseAllYoutube();
			},
			onSlidePrev: function(el) { 
				pauseAllYoutube();
			}
		});
		
		function pauseAllYoutube() { 
			$('iframe[src*="youtube.com"]').each(function() {
				var iframe = $(this)[0].contentWindow;
				iframe.postMessage('{"event":"command","func":"pauseVideo","args":""}', '*');
			}); 
		}
	});

Hope that helps.

**Comment by nuggit** [comment]
That works well. Thanks q2apro!

**Comment by HybridSolutions** [comment]
@q2apro The second code you provided is not working :( Checked console and no errors. Do I need any additional script since you are using enablejsapi:1?

Thanks!

**Comment by q2apro** [comment]
Just open a jsfiddle, you will see it works. Maybe you have another version of the script? Or some other code of yours is interfering.

**Comment by sachinchoolur** [comment]
Hi guys,

I have included this feature in the [new version](http://sachinchoolur.github.io/lightgallery1.2/demos/videos.html). It is almost ready and i will be releasing it soon.

Thanks.

**Comment by HybridSolutions** [comment]
Looks awesome @sachinchoolur ! Looking forward for the final release!

**Comment by sachinchoolur** [comment]
Hi guys,

Finally i have released version 1.2 with this feature..
