### ISSUE TITLE
Preventing click to open lightGallery gallery unless an image is the active item in a carousel

### ISSUE THREAD

**Issue by macsupport** [sachinchoolur/lightGallery#210]
I have been able to do this with other lightboxes but having trouble with getting it to work in lightgallery. I have a carousel that moves an image to center position when it is clicked and when doing so, the parent is given a "current" class and when it is not centered, the current class is removed. I still want all the images to load as a gallery, not single images but have only the centered, current image open on click since the carousel has the click function that moves the image to center position.
 I have set up LG to be the lightbox with the following code and also set a click function to prevent opening unless the parent has a class of current. So far, no luck, every clicked image opens in the LG lightbox. Is there a way to do this with LG?

```
$('a.lg').lightGallery({
selector: 'this'
});
$('#coverflow').on('click', '.item:not(.current) a.lg', function (e) {
e.preventDefault();
e.stopPropagation();
});
```

**Comment by kursusHC** [comment]
Hi, 

I guess on solution would be to use [Dynamic Mode](http://sachinchoolur.github.io/lightGallery/demos/dynamic.html) so you could add/remove images from the array along with your carousel events.

**Comment by saidaLachgar** [comment]
**You can easily add in your css :**

 `.item.current { pointer-events: none; }`

> This will prevent any clicks on the element
