### ISSUE TITLE
Zooming on pinch

### ISSUE THREAD

**Issue by manouman** [sachinchoolur/lightGallery#211]
Hi, it's possible to zoom an image using the pinch gesture without clicking the zoom button?

**Comment by boynet** [comment]
+1

**Comment by bjarnef** [comment]
+1

I like this gallery, but the zoom functionality via buttons and pinch zoom are lacking a bit and not working as well as pinch zoom on http://photoswipe.com/

However lightGallery has other benefits and is easier to implement.

**Comment by YellowLabIT** [comment]
+1 
yes would be great!

**Comment by daykkin** [comment]
+1

**Comment by thristov78** [comment]
+1

**Comment by lunchev** [comment]
+1

**Comment by piemme74** [comment]
+1

**Comment by sachinchoolur** [comment]
Hi Guys,

The basic functionality is already done - https://sachinchoolur.github.io/lg-comment/demos/methods.html

Will be released in version 2.0

**Comment by piemme74** [comment]
Hi, there is a problem with this, version. If you check your page at https://sachinchoolur.github.io/lg-comment/demos you can see that when you click on an image it is not loaded, and the if you go to the next one with arrow or swipe everything goes ok. but the first one is never shown (I have this problem also on my website).
Thanks

**Comment by piemme74** [comment]
Hi, there is a problem with this, version. If you check your page at
https://sachinchoolur.github.io/lg-comment/demos you can see that when you
click on an image it is not loaded, and the if you go to the next one with
arrow or swipe everything goes ok. but the first one is never shown (I have
this problem also on my website).
Thanks

2018-03-07 14:32 GMT+01:00 Sachin N <notifications@github.com>:

**Comment by sachinchoolur** [comment]
Hey @piemme74,

Version 2.0 is still under development. The problem you pointed out is a known issue. You need to change some settings to make this work.

**Comment by piemme74** [comment]
Hi!
Which settings do I have to change?
Thanks a lot

p.s. what you are doing is a great great job!!!!! thanks!!!!

Il 11/Mar/2018 11:38, "Sachin N" <notifications@github.com> ha scritto:

**Comment by sachinchoolur** [comment]
You need to set zoomFromImage: false. Please don not use the demo version for production. It has few known issues

**Comment by ZubeeDoo** [comment]
is it possible to reduce the features (like i don't want the download or share icons to be displayed) ?

**Comment by sachinchoolur** [comment]
Yes, it is possible. Docs - https://sachinchoolur.github.io/lightGallery/docs/api.html

``` js
$('#lightgallery').lightGallery({
    share: false,
    download: false
});
```

**Comment by stephansperling** [comment]
Hi! Is there any estimate/date, when version 2.0 will be released and this issue closed?

**Comment by msfs1992** [comment]
> Hi Guys,
> 
> The basic functionality is already done - https://sachinchoolur.github.io/lg-comment/demos/methods.html
> 
> Will be released in version 2.0

The zoom method is not updated into the package: https://github.com/sachinchoolur/lightGallery

**Comment by smbowler** [comment]
Hello! Any idea when the pinch zoom and/or V2 will be released? Thanks!

**Comment by alexeichemenda** [comment]
@sachinchoolur are you still working on the project and is the pinch to zoom still planned in 2.0? When do you think that release will happen?

Hat tip for the high quality lib - it's amazing and has helped me on numerous projects, so thank you! 
Is there anywhere I can donate?

**Comment by mariomurrent-softwaresolutions** [comment]
Any updates on this?

**Comment by khaledDiZ** [comment]
hello , any good news ?

**Comment by mariomurrent-softwaresolutions** [comment]
> hello , any good news ?

Actually not :( I moved to lightbox2

**Comment by khaledDiZ** [comment]
> > hello , any good news ?
> 
> Actually not :( I moved to lightbox2

and ? what was your experience with it ? do you recommend it ?

**Comment by mariomurrent-softwaresolutions** [comment]
> > > hello , any good news ?
> > 
> > 
> > Actually not :( I moved to lightbox2
> 
> and ? what was your experience with it ? do you recommend it ?

I can recommend it - switching to it is not that hard :)

**Comment by khaledDiZ** [comment]
> > > > hello , any good news ?
> > > 
> > > 
> > > Actually not :( I moved to lightbox2
> > 
> > 
> > and ? what was your experience with it ? do you recommend it ?
> 
> I can recommend it - switching to it is not that hard :)

that's good , thank you
