### ISSUE TITLE
Gallery with 2 images slides images in wrong direction

### ISSUE THREAD

**Issue by evvvritt** [sachinchoolur/lightGallery#213]
Hi, thanks for developing this plugin.

When I have galleries with just 2 images the sliding animation is using the opposite direction than with 3+. I thought this might be something related to looping the slideshow but it has the same behavior un-looped.

Any advice is appreciated!

```
$('.lightbox-gallery').lightGallery({
            speed:800,
            loop:true,
            thumbnail:false,
            closable:true,
            hideBarsDelay:2000,
            download:false,
        });
```

**Comment by evvvritt** [comment]
In fact, the demo you provide in the current release (v1.2.6) exhibits the same behavior. However, another site I built using v1.1.5 slides correctly, as does your github.io site though I'm not sure which version it is using...

**Comment by elenista** [comment]
Same problem here! And it happens whether the loop is disabled or not. Are you planning to fix the issue?

**Comment by mariusschulz** [comment]
@sachinchoolur If I'm not mistaken, the bug lies within these two `if` statements: https://github.com/sachinchoolur/lightGallery/blob/b02e1d26a4e2da223e4cf1463b04152b631d14b4/src/js/lightgallery.js#L791-L799

Would you mind taking a look?

**Comment by vercas** [comment]
Still happening on 1.2.21

**Comment by artursopelnik** [comment]
+1

**Comment by chrisdeeming** [comment]
+1

**Comment by srajaee** [comment]
+1

**Comment by whimsicaldreamer** [comment]
Which commit to use?

**Comment by carol-braileanu** [comment]
+1, still having this issue

**Comment by sachinchoolur** [comment]
Hi Guys,
Finally, the issue has been fixed. Please use the latest version of lightGallery

Thank you so much for your patience
