### ISSUE TITLE
external images are not loading on the lightbox

### ISSUE THREAD

**Issue by d1a8lo24** [sachinchoolur/lightGallery#214]
So I just found that when you want to use external images using the script. you will get an error. 
I use a CDN for saving external assets like images.

Anyway if your images have the http: or https: you will get freeze on the lightbox so nothing is loading and the error from firebug is undefine variable "src".

Meaning that somewhere on the script the source to the image is not being caught correctly.

I was able to by pass this by removing the http or https and just //cdn.to.image.jpg

Which is fine but in realty you should be able to use the http just in case some old browsers don't know what to do with the //.

I hope this gets fix on your next release.

**Comment by sachinchoolur** [comment]
Hey @d1a8lo24 ,
Apologies for the delay. :disappointed: 
It is not an issue of lightGallery. Users must load their assets with the appropriate protocol. As you pointed out using // is a good workaround because then the browser will automatically request the URL with the appropriate protocol.
