### ISSUE TITLE
img ALT attribute

### ISSUE THREAD

**Issue by maxisix** [sachinchoolur/lightGallery#215]
There's no way to copy the ALT attribute from the thumbnail img to the big Slide image ?

**Comment by kursusHC** [comment]
Hi, 

This is more of a JS/jQuery question. You could use the onBeforeOpen event, or put in directly in your markup.

**Comment by bart** [comment]
Same question here. Isn't it possible to pass it by data attributes like data-title and data-alt to the big image?

**Comment by abnersajr** [comment]
Today is possible to make a subtitle using the attribute _data-sub-html_ on link.
Soon as possible I will make possible using ALT which alternative.

**Comment by MatrixOfDeath** [comment]
I'm interested about this issue to pass the alt attribute
