### ISSUE TITLE
Protocol https with Vimeo URL

### ISSUE THREAD

**Issue by sylchat** [sachinchoolur/lightGallery#219]
Mixed Content: The page at 'https://....' was loaded over HTTPS, but requested an insecure resource 'http://player.vimeo.com/video/1084537?autoplay=1&api=1'. This request has been blocked; the content must be served over HTTPS.

The bug is there, I think : 
/src/js/lg-video.js line : 232

**Comment by abnersajr** [comment]
@sylchat sorry for the delay. But now is fixed, the vimeo embed will detect the current page protocol to serve the embed right  :+1: 
Feel free to create other issue if solution not right.
