### ISSUE TITLE
[Android] Vimeo FullScreen

### ISSUE THREAD

**Issue by qduvalcasus** [sachinchoolur/lightGallery#220]
Hi,

I found a problem with the gallery with a vimeo's movie on Android phone.
The gallery works fine, i have the vimeo video but when i press play, the video enter on fullscreen mode and start playing but she is not visible on screen.

I tryed to watch an embed video and it works fine. The problem is only with lightGallery.

I have the same problem on demo's page : http://sachinchoolur.github.io/lightGallery/demos/videos.html
http://imgur.com/95weHhN

**Comment by sachinchoolur** [comment]
Works fine for me. Please re-open if the issue persists
