### ISSUE TITLE
Thumbnails not working in Chrome with Touch Screen

### ISSUE THREAD

**Issue by smonge** [sachinchoolur/lightGallery#225]
Thumbnails are not working in Chrome with Touch Screen. But if you touch any thumbnail, then you can use mouse click to change image or video.

**Comment by lamarmiller96** [comment]
I've discovered this as well.  At first I thought thumbnails weren't working at all in Chrome (I have a touchscreen) but I hadn't even tried to touch a thumbnail.  Once you touch one, then you can use mouse click as would be expected.

**Comment by cazacugmihai** [comment]
I'm also having this issue with the latest versions of `lightGallery` and `lg-thumbnail`.

**Comment by deconstruction** [comment]
Confirm. Thumbnail mouse click doesnt work on Chrome on touchscreen laptop.

**Comment by mangakid** [comment]
Still an issue, did anyone figure out a workaround?

**Comment by JonasBlahut** [comment]
Same problem happens with Chromium (Iron) 58 on Ubuntu 16.04. Works on touch, but fails with mouse. Also, scrolling still fails even after touching a thumbnail, and when scrolling using touch, clicking them breaks again.

**Comment by sachinchoolur** [comment]
Hey Guys,

The issue has been fixed. Please use the latest version of lightGallery and it's modules.

Sorry for the delay :(
