### ISSUE TITLE
Download link present for YouTube/Vimeo videos

### ISSUE THREAD

**Issue by pollutionlake** [sachinchoolur/lightGallery#226]
When viewing a YouTube video, download link is visible on the upper right. Clicking it causes the browser to download watch.htm. Similar behavior with Vimeo videos. I would suggest hiding the download link for videos altogether.

Can view this behavior in the demos:
http://sachinchoolur.github.io/lightGallery/demos/videos.html

For images, it would be nice to be able to disable the download link on a per-item basis (maybe using a "data-" flag)?

Thanks for the plugin!

**Comment by kursusHC** [comment]
Hi, 

Indeed, except it just get me to the video page when I click. 

You could use the [onBeforeSlide event](http://sachinchoolur.github.io/lightGallery/docs/api.html#events) to check every time if $('.lg-current .lg-video') exists, and hide/show $('#lg-download') accordingly.

**Comment by sachinchoolur** [comment]
Hi guys,
The issue has been fixed in v1.2.11. You can pass `data-download-url="false"` for hiding download icon for any particular slide.

**Comment by pollutionlake** [comment]
Nice! Thanks!
