### ISSUE TITLE
Automatically load thumbnail images for youtube links

### ISSUE THREAD

**Issue by alias1** [sachinchoolur/lightGallery#23]
According to [stackoverflow](http://stackoverflow.com/questions/2068344/how-do-i-get-a-youtube-video-thumbnail-from-the-youtube-api) you can get the default thumbnail icon for a Youtube video with:

`http://img.youtube.com/vi/<insert-youtube-video-id-here>/default.jpg`

This would be a cool feature to support by default (especially for the 'dynamic' option) As it currently is, if you don't manually set the thumbnail it just shows as a broken image.

**Comment by sachinchoolur** [comment]
I have included this feature in lightgallery version 1.2..
