### ISSUE TITLE
Direct link display glichy icons

### ISSUE THREAD

**Issue by gregfr** [sachinchoolur/lightGallery#232]
When opening a page with the direct link (containing the #), such as http://...#lg=1&slide=0, the top line icons are display weirdly:

![image](https://cloud.githubusercontent.com/assets/361582/11355743/aeba8f5e-9257-11e5-883d-54dc04fb29ff.png)

They are ok when opening on click.

(lg 1.2.6 via cdn)

**Comment by sachinchoolur** [comment]
Issue has been fixed
