### ISSUE TITLE
Prev/next with iframe

### ISSUE THREAD

**Issue by gregfr** [sachinchoolur/lightGallery#233]
I'm using the iframe feature, like this:

```
$('LI').lightGallery({
                selector: 'this',
                iframeMaxWidth: '1000px',
                download: false,
                zoom: false
            });
```

When opening, the top-left counter show "1/1", is it possible to have navigation, as it's provided for pictures?

thanks

**Comment by sachinchoolur** [comment]
Since there is only one item in the gallery, navigation arrows are useless. That is why it is removed.
