### ISSUE TITLE
iframe height and width

### ISSUE THREAD

**Issue by gregfr** [sachinchoolur/lightGallery#234]
I'm opening an iframe with

```
iframeMaxWidth: '1000px'
```

however the html is like:

```
    <div class="lg-video-cont" style="max-width: 855px;">
```

why 855px? how are width and height computed?

thanks

**Comment by clintongreen** [comment]
Hi @gregfr did you figure this out yet? I'm having the same issue.

**Comment by inluxc** [comment]
I having the same problem, i used the videoMaxWidth, instead of the iframeMaxWidth and now i want to change the height of the iframe area and not so easy, it should be and iframeHeight.

**Comment by sachinchoolur** [comment]
Hey Guys,
The issue has been fixed. Please use the latest version of video plugin.
