### ISSUE TITLE
Image aligns to right when inheriting CSS text-align property

### ISSUE THREAD

**Issue by dloewen** [sachinchoolur/lightGallery#236]
If CSS text-align is not set to `left` in the containing page, lightGallery opens to show the image aligned off the screen, to the right.

I experienced this when `text-align: center` was set on the page's `body` element.

Suggested fix: add `text-align: left;` to the `.lg-outer` selector.

**Comment by vladikoff** [comment]
Also seeing this issue with 
```
* {
  text-align: center;
}
```

**Comment by sachinchoolur** [comment]
Hey Guys,

The issue has been fixed. Please use the latest version of lightGallery.
