### ISSUE TITLE
how add icon like ,button share of facebook 

### ISSUE THREAD

**Issue by khanhnam99** [sachinchoolur/lightGallery#240]
![how](https://cloud.githubusercontent.com/assets/575720/11608551/139df35c-9b9f-11e5-9487-4087547bc32b.JPG)
![capture22222](https://cloud.githubusercontent.com/assets/575720/11608441/ae8ff350-9b9b-11e5-8201-f755412131cb.JPG)

how add icon like ,button share of facebook

box red
please help me!

thanks

**Comment by rmaddox** [comment]
Absolutely, most important part is sharing, and share button is missing.

**Comment by rodrigoprobst** [comment]
Hello There!

I'm trying to place the share button, just achieve that by placing the facebook div inside the description part. but i need to reload the page to view the button, and when I select another image, same thing. Facebook button is not showing and I need to reload the page to be showed.

Sorry for bad english!

Here is code:

`<?php 
	$tipos = explode("-", $_GET['tipo']);
    $tipo = $tipos[sizeof($tipos)-1]; 
    $sSql = "SELECT * FROM Evento WHERE CodEvento = $tipo";
    $qQry = $cBanco->Query($sSql);
    $oRow1 = $cBanco->FetchObject($qQry);
    $i = 0;
?>
<div class="container" id="container">
	<div class="col-md-12">
		<h2 id="titulo"><?php echo $oRow1->Titulo ?></h2>
        <div class="about-us-two">
            <div class="demo-gallery">
                <ul id="lightgallery" class="list-unstyled grid row">
                    <div class="grid-item col-md-3 col-sm-4 col-xs-6" data-src="<?php echo $Browser->getURL() ?>media/dados/eventos/<?php echo $oRow1->ArqImagem ?>" data-sub-html="<h4><?php echo $oRow1->Titulo ?></h4><p><div class='fb-share-button' data-href='<?php echo substr($Browser->getURLCompleta(),20) ?>#lg=1&slide=<?php echo $i ?>' data-layout='button' data-mobile-iframe='true'></div></p>">
                        <a href="">
                            <img class="img-responsive thumbnail" src="<?php echo $Browser->getURL() ?>media/dados/eventos/<?php echo $oRow1->ArqImagem ?>">
                        </a>
                    </div>
                    <?php 
                        $sSql = "SELECT * FROM EventoFoto WHERE CodEvento = $tipo";
                        $qQry = $cBanco->Query($sSql);
                        while($oRow = $cBanco->FetchObject($qQry)){
                    ?>
                    <div class="grid-item col-md-3 col-sm-4 col-xs-6" data-src="<?php echo $Browser->getURL() ?>media/dados/eventos/<?php echo $oRow->ArqImagem ?>" data-sub-html="<h4><?php echo $oRow1->Titulo ?></h4><p><div class='fb-share-button' data-href='<?php echo substr($Browser->getURLCompleta(),20) ?>#lg=1&slide=<?php echo $i++ ?>' data-layout='button' data-mobile-iframe='true'></div></p>">
                        <a href="">
                            <img class="img-responsive thumbnail" src="<?php echo $Browser->getURL() ?>media/dados/eventos/<?php echo $oRow->ArqImagem ?>">
                        </a>
                    </div>
                    <?php 
                        }
                    ?>
                </ul>
            </div>
        </div>
	</div>
</div>

<script>
	$(function() {
 		$('.grid').masonry({
		  // options
		  itemSelector: '.grid-item',
		  columnWidth: 0
		})
	});
</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.6";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>`

**Comment by rodrigoprobst** [comment]
Hello There!

I'm trying to place the share button, just achieve that by placing the facebook div inside the description part. but i need to reload the page to view the button, and when I select another image, same thing. Facebook button is not showing and I need to reload the page to be showed.

Sorry for bad english!

Here is code:

![image](https://cloud.githubusercontent.com/assets/8580266/14528464/e65e86de-0225-11e6-9d74-2b63fe94d3dd.png)

**Comment by srjlulla** [comment]
You can always use https://www.addthis.com sharing tools. 

Add 

```
<script type="text/javascript">
// always refresh on URL change
window.addEventListener("hashchange", function () {
  addthis.layers.refresh();
});
</script>
```

before the </body> tag to make sure that URLs are relevant. If you want to show sharing icons only in the lightbox, add the following to your CSS:

```
body > div > div#at-share-dock {
    visibility: hidden;    
}

body.lg-on > div > div#at-share-dock {
    visibility: visible;    
}
```

**Comment by sachinchoolur** [comment]
Hi Guys,
I've added share module.
[GitHub:](https://github.com/sachinchoolur/lg-share) https://github.com/sachinchoolur/lg-share
[Demo:](http://sachinchoolur.github.io/lightGallery/demos/share.html) http://sachinchoolur.github.io/lightGallery/demos/share.html
[Docs:](http://sachinchoolur.github.io/lightGallery/docs/api.html#lg-share) http://sachinchoolur.github.io/lightGallery/docs/api.html#lg-share
