### ISSUE TITLE
Download button for video

### ISSUE THREAD

**Issue by tulsadome** [sachinchoolur/lightGallery#241]
The download button doesn't work for videos. Is there a way to work around this or fix it? If I could manipulate lightGallery in the DOM with jQuery I can think of any easy fix but it seems it isn't possible to do that.

**Comment by sachinchoolur** [comment]
HI,
You have to provide separate download url for html5 videos.. Please check download setting for more information. http://sachinchoolur.github.io/lightGallery/docs/api.html
