### ISSUE TITLE
Hash plugin bug

### ISSUE THREAD

**Issue by luzik** [sachinchoolur/lightGallery#242]
When plugin is turned on it affect browser history, so after browsing images and closing lightGallery plugin, pressing browser back button do nothing !
Maybe you should use replaceState() instead of pushState() ? ..or better remove history entries on lightGallery close.

**Comment by Phoenix404** [comment]
Are u running lightgallery with server  or as normal ? normal : c://path_to_file_.html

**Comment by luzik** [comment]
http server

**Comment by kursusHC** [comment]
+1 behavior is kind of unexpected when clicking back button. Note that `window.location.hash` is used instead of History API (for compatibility reasons I presume). 

What you be great in my opinion is "pushing" the first hash, and replacing it on slide change, so that back button would still display original page (instead of previous site). @sachinchoolur would you be interested in a PR ? Any advice ?

**Comment by Positic** [comment]
my decision (lg-hash.js):

/* fix hash
        // Change hash value on after each slide transition
        _this.core.$el.on('onAfterSlide.lg.tm', function(event, prevIndex, index) {
            window.location.hash = 'lg=' + _this.core.s.galleryId + '&slide=' + index;
        });
*/
		window.location.hash = 'lg=' + _this.core.s.galleryId + '&slide='+_this.core.$outer.find('.lg-current').index(); // fix hash

**Comment by gauravmak** [comment]
@Positic will your fix solve this issue? #352  (3rd comment)

**Comment by Positic** [comment]
@gauravmak, сomment this (а то хуйни какой-то понаписали с этими хешами..):

/*
        // Reset to old hash value
        if (this.oldHash && this.oldHash.indexOf('lg=' + this.core.s.galleryId) < 0) {
            window.location.hash = this.oldHash;
        } else {
            if (history.pushState) {
                history.pushState('', document.title, window.location.pathname + window.location.search);
            } else {
                window.location.hash = '';
            }
        }
*/

**Comment by gauravmak** [comment]
@Positic with that change, lightgallery variables aren't being removed from url upon closing it. And, back button is taking to previous image url as well, if available. My concern is to completely remove (or not save) image view urls in browser history so that back button takes to previous page.
Take a note that I am using v1.2.14 currently.

**Comment by Positic** [comment]
@gauravmak - thank you! New version:

// *****************************************
        // Change hash value on after each slide transition
        /*
        _this.core.$el.on('onAfterSlide.lg.tm', function(event, prevIndex, index) {
            window.location.hash = 'lg=' + _this.core.s.galleryId + '&slide=' + index;
        });
        */
        if(window.location.hash.indexOf('lg=') <0){
          window.location.hash = 'lg=' + _this.core.s.galleryId + '&slide='+_this.core.$outer.find('.lg-current').index(); // fix hash
		}
// *****************************************
// *****************************************

/*
        // Reset to old hash value
        if (this.oldHash && this.oldHash.indexOf('lg=' + this.core.s.galleryId) < 0) {
            window.location.hash = this.oldHash;
        } else {
            if (history.pushState) {
                history.pushState('', document.title, window.location.pathname + window.location.search);
            } else {
                window.location.hash = '';
            }
        }
*/
        if(window.location.hash.indexOf('lg=')>=0)
			window.history.go(-1);
// *****************************************

**Comment by sachinchoolur** [comment]
Hey Guys,
The issue has ben fixed. Please use the latest version of lg-hash plugin

**Comment by M-Husein** [comment]
Please, change this behavior with History API
