### ISSUE TITLE
Enhancement: Add Rotate Button while viewing images

### ISSUE THREAD

**Issue by atulagrwl** [sachinchoolur/lightGallery#245]
Several of images which we link are rotated and it should be rotated to view properly.

**Comment by kursusHC** [comment]
Hi, 

Not sure if this would be a useful feature. Why don't you rotate your pictures in the first place ?

**Comment by r0bbie** [comment]
I'd also hugely welcome this feature. Often times when importing images taken from my phone they are not rotated correctly. Being able to quickly rotate them clockwise/anti-clockwise by 90 degrees within the image previewer when flicking through is very helpful and time-saving.

As a new lightGallery user I'm so far very impressed, and this ostensibly seems to be the only feature holding it back slightly from being the obvious go-to cross-platform lightweight image viewer (at least for me).

**Comment by tomfat** [comment]
I second that
> Several of images which we link are rotated and it should be rotated to view properly.

**Comment by gregfr** [comment]
Exactly what I was about to ask for :-)

**Comment by luozt** [comment]
![image](https://cloud.githubusercontent.com/assets/6123916/21469710/358f276e-ca9d-11e6-80bf-e20f332bae46.png)

I also need this rotating button! It is really useful to view pictures!

Right now my project just needs this and I just had to add rotate button by myself and customized the lightGallery.js. But I found that rotating and zooming are not compatible becasue of the css style `transform-origin`.  Rotating needs to set `transform-origin: 50% 50%` but zooming had set `transform-origin: 0 0`.

I hope this feature could be added next update.

**Comment by lerit** [comment]
+1

**Comment by newhuan** [comment]
also need this, thank you.

**Comment by IsaacGutierrez** [comment]
I need this feature!

**Comment by ASKnn** [comment]
+1

**Comment by Herod** [comment]
+1

**Comment by dongchenglong** [comment]
hope v2

**Comment by kirya-dev** [comment]
Plugin https://github.com/sachinchoolur/lightgallery.js/issues/104

**Comment by sachinchoolur** [comment]
Rotate option is now available in version 1.8.0 and above. 
https://sachinchoolur.github.io/lightGallery/#lg=1&slide=1
Thank you for your patience
