### ISSUE TITLE
Backdrop opening is not animated [Fix included]

### ISSUE THREAD

**Issue by kursusHC** [sachinchoolur/lightGallery#246]
Hello and thanks for this nice gallery. 

I noticed that the fade animation on the backdrop opening is not applied whatever the delay set with 'backdropDuration'. 

According to this [SO answer](http://stackoverflow.com/a/20938849) some (most) bowsers skip the animation for efficiency purpose. The linked solution, by forcing a redraw before applying the "in" class, solves the problem. 

See kursusHC/lightGallery/@fc2dbbfa3f69f7fd97c76519f2ff363553890be7

Thanks

**Comment by makshh** [comment]
@sachinchoolur are you OK with that fix? I think it works good.

**Comment by sachinchoolur** [comment]
Hey guys,
The issue has been fixed.
