### ISSUE TITLE
Zoom doesn't work when 'dynamic' option is true

### ISSUE THREAD

**Issue by thdoan** [sachinchoolur/lightGallery#247]
I get the following error when setting both 'zoom' and 'dynamic' to true:

`Uncaught TypeError: c.core.$items.eq is not a function`

FIX: Change `_this.core.$items.eq(index).attr('data-width')` to `$(_this.core.$items).eq(index).attr('data-width')` in line 120 of lg-zoom.js.

This seems to solve the JS error, but zoom still doesn't work with `dynamic: true` option.

**Comment by kursusHC** [comment]
Hi, 

Zoom does work with Dynamic mode, could you please post some code in a fiddle ?

**Comment by thdoan** [comment]
@kursusHC sure, here you go: http://codepen.io/thdoan/pen/ZQWKEW

**Comment by sachinchoolur** [comment]
@thdoan,
Thank you for pointing this out.. The issue has been fixed..

@kursusHC , Thank you very much for all your contributions so far.. I have been quite busy lately. Not even getting time to look at the issue.. Hope you will continue to support the project.. :+1:

**Comment by thdoan** [comment]
Thanks for the quick fix, guys! :+1:  For reference, how would we reference the zoom image source in `dynamicEl`? It would be nice to be able to specify a `zoom` property.

**Comment by sachinchoolur** [comment]
Oh forgot to mention.. 
When you doubleclick on the image it will be zoomed to it's actual pixel. For normal zoom-in, zoom-out you can use the top buttons. If you know the actual size of the image it is better to pass it via data-width attribute. For dynamic gallery you can use `width` key. If you don't know the actual size of the image no need to pass anything lightgallery will try to find it's actual size. But keep in mind some old browsers don't support `naturalWidth` property. So i would prefer the first method.. 
``` javascript
dynamicEl: [
    {
        src: 'path-to-image/image.jpg',
        width: 1600
    }
]
```

**Comment by kursusHC** [comment]
@sachinchoolur You're welcome, glad to contribute to such a nice project !

**Comment by thdoan** [comment]
@sachinchoolur Thanks for the info on zooming. The issue that I'm experiencing is that when the zoomed images are large (e.g., 1MB), then the gallery will take a long time to load since it's actually loading the zoomed image (`dynamicEl.src`) for the preview image as well.

When not using the dynamic option, lightGallery uses `$('a > img').attr('src')` as the preview image source and `$('a').attr('href')` as the zoomed image source. It would be nice to replicate this when using the dynamic option by introducing a `zoom` property for the zoomed image source; then we can use the `src` property for the preview image source. I hope that makes sense.

**Comment by rochapablo** [comment]
https://github.com/sachinchoolur/lightGallery/issues/291
