### ISSUE TITLE
multiple lightgalleries on one page

### ISSUE THREAD

**Issue by floriko** [sachinchoolur/lightGallery#249]
I cannot get multiple light galleries on one page working. I am not sure whether is is a bug or simply not supported?

Can you call multiple light galleries on one page?

http://stackoverflow.com/questions/34106608/multiple-justified-image-grid-galleries-custom-lightbox-call-markup-with-lig

**Comment by chelseanderby** [comment]
I'm not sure if this is exactly what you mean so let me know if it's something different but I had a similar problem for awhile where it was 'buggy' (by fault of my markup) and having multiple gallery's didn't quite work properly. But if it's the same problem I had, you can do this with the 'galleryId' attribute like so (you have some leeway on your html markup):

```html
<div id="dogs">
    <a ...>
        <img ...>
    </a>
</div>
...
```

```javascript
<script>
$(document).ready(function() {
    $("#cats").lightGallery({
        galleryId: 1,
        ... 
    });
    $("#dogs").lightGallery({
        galleryId: 2,
        ...
    });  
});
</script>
```

**Comment by abnersajr** [comment]
LightGallery supports multiple galleries. If you can initiate much as you need with id, although I recommend to use a common class, like _.gallery_ 
So every wrapper with that class will be an independent gallery.
