### ISSUE TITLE
Height Issues (px vs. % - for calculating 'top' attribute of .lg container)

### ISSUE THREAD

**Issue by chelseanderby** [sachinchoolur/lightGallery#251]
Hi Sachin,

First off, I just wanted to let you know I think you have a fantastic project going on with lightGallery. After recently extensively going through a lot of other lightbox options out there that had plenty of fundamental flaws, I'm really pleased with lightGallery.

Since my issue report is so long, you may want to skim it so here's a quick summary:

In 'lightGallery.js' - the 'top' variable for '.lg' is being miscalculated in certain circumstances
    -Editing % values for height(/width) instead of using default '100%' or a 'px' value
    -Using a web framework such as Flask to render pages (still not sure why this affects it)

So I'll preface this issue by saying I am not a web developer by any stretch of the imagination (more of a hardware person with programming experience) so if you see any questionable things in my html/css/js, call me out on it, I'm certainly no expert in this. I suppose this reasoning is why this 'issue' report will be fairly long as I can't identify what the problem is and I can't really provide a jsfiddle example of the issue. I have been working on this issue almost non-stop the past couple of days and while I think I've troubleshooted it enough to figure out where the problem is happening, I honestly have no idea how to fix it with my limited knowledge.

So I decided that I wanted to embed my captions onto the picture itself for aesthetic and functional reasons(larger area to click out of picture). After looking through the documentation itself and not finding any default attributes to embed it (please correct me if I'm wrong), I decided to start hacking a solution together. At this point, I noticed that an example page on your website had embedded captions so I decided to try to model my work after that.

http://sachinchoolur.github.io/lightGallery/demos/fixed-size.html

At this point I realized that it was probably a css attribute that was changing the location of the caption so I examined the page and I found a reasonable way of doing that with the following css:

``` css
.lg-outer .lg-sub-html{position:absolute;}
```

Thinking that this would solve my issues (and using the same js as the 'fixed-size' example), I applied the changes and unfortunately found that while the caption did embed in the image, the img container dropped to the bottom rather than being centered in the page. So I did some more investigating. First I exchanged all css and js files between my code and your example and tested all the external files I was using and was able to verify that all the code I was using was working and was not interfering with the embedded captions css. At this point, I discovered something rather odd; in your example, you assign width and height fixed px value (ie. 'fixed-size). When I changed this to % values, the img container dropped to the bottom of the page and was no longer centered, similar to the problem I was having before with my code.

Now at this point, it's worth mentioning that I am using a framework for my website, Flask. While it's a little complex, Flask renders my files in roughly this fashion: I have a base.html file that is jinja2 formatted that imports all css, js, and renders the frame of my website. Then I have content pages such as 'index.html' that extend 'base.html' and are essentially the specific content to each specific page.

So naturally, I realized something. My flask default page settings mirrored your example with % width/height (in the custom js of loading lightGallery) instead of px, while your default page worked completely fine. So I figured, hmm, maybe flask is messing up lightGallery somehow with the settings (at this point I will also clarify, lightGallery with flask works absolutely fine when I do not make the above mentioned changes). So I extracted my flask webpages and put it in a static file. Surprise, surprise, it worked exactly like your example, ie. flask is somehow affecting my lightGallery when I make changes to the width/height attributes from the default '100%' values in lightGallery.js.

Now at this point, I was thinking maybe flask is the culprit here but then I remembered that when I modified your example (which obviously was a static example) with a % width/height, it had the same problem, the img container slid to the bottom of the page instead of being centered in the middle of the screen. So I figured that was a little curious. I fired both examples up in Firebug and found something odd. The '.lg' div was being appended with a massive number for a 'top' style that was pushing the container to the bottom of the page. I tried hard coding 'top' values in my pages for the styles but it kept getting overwritten.

So I turned to 'lightGallery.js' and found the possible areas of concern:

``` javascript
        // For fixed height gallery
        _this.setTop();
        $(window).on('resize.lg orientationchange.lg', function() {
            setTimeout(function() {
                _this.setTop();
            }, 100);
        });
```

``` javascript
    // For fixed height gallery
    Plugin.prototype.setTop = function() {
        if (this.s.height !== '100%') {
            var wH = $(window).height();
            var top = (wH - parseInt(this.s.height, 10)) / 2;
            var $lGallery = this.$outer.find('.lg');
            if (wH >= parseInt(this.s.height, 10)) {
                $lGallery.css('top', top + 'px');
            } else {
                $lGallery.css('top', '0px');
            }
        }
```

So I noticed this 'top' style was being affected by the height variable. And this is where I'm lost, I don't really know how to correct it since I really don't know javascript. All I know is a correctly computed value of 'top' centers the image. I realized this methods are for fixed height but they affect the 'top' value for all pop-ups. And since I found two correlated separate issues with the second snippet, one with using modified % height/width values with a static page and one by using px or % height/width with a web framework, I think there's a fundamental flaw in this calculation, I just don't know how to correct it.

I really tried to get around this problem in css but I couldn't figure it out. For example, I was able to move the image centered by using:

``` css
.lg-outer .lg-item, .lg-outer .lg-img-wrap {
  position: fixed;
}
```

but this doesn't help me move .lg-sub-html because .lg-sub-html is sub of .lg, not .lg-img-wrap so because of .lg wayward movement south (because of large value of 'top'), .lg-sub-html's 'absolute' position of .lg is way south of .lg-img-wrap. And since I can't affect do an accurate calculation of 'top for .lg I can't move that. Making .lg-sub-html of .lg-img-wrap could theoretically work but I have no idea how to do that in javascript.

Again, sorry for my extremely long issue report but I felt it was the only way I could really portray the problem. Any help is greatly appreciated!

**Comment by d6233** [comment]
+1

**Comment by sachinchoolur** [comment]
Hey @chelseanderby ,

I'm really sorry for the delayed response. Since the issue was reported long back, I hope you must have found the solution. If not, please summarize your problems and re-open the issue.

**Comment by klihelp** [comment]
+1 I was looking a solution within the project.

**Comment by BipBipChris** [comment]
Hello,

it's now 2019 and i just found your great plugin, so I started to use it.
In my case I applied a height to the parameters, but with percentage, and I had to modify the code because one more time the function gave me a wrong inline style.
So I opened the file and found a workaround, so here it is:

 ```
 `// For fixed height gallery
    Plugin.prototype.setTop = function () {
        if (this.s.height !== '100%') {
            var wH = window.innerHeight;
            // height  settings with percent
            if(this.s.height.indexOf('%')) {
              var top = (100 - parseInt(this.s.height,10))/2;
              var lGallery = this.outer.querySelector('.lg');
              lGallery.style.top = top + '%';
            } else {
              var top = (wH - parseInt(this.s.height, 10)) / 2;
              var lGallery = this.outer.querySelector('.lg');
              if (wH >= parseInt(this.s.height, 10)) {
                  lGallery.style.top = top + 'px';
              } else {
                  lGallery.style.top = '0px';
              }
            }
        }
    `};``
```

as far fo the toolbar position, I modified the CSS too, just like chelseanderby:

```
.lg-toolbar {
  z-index: 1082;
  left: 0;
  position: fixed;
  top: 0;
  width: 100%;
  background-color: rgba(0, 0, 0, 0.45);
}
```

Anyway, thanks a lot - this plugin ROCKS ;-)
