### ISSUE TITLE
Dynamic mode - set Events once for all

### ISSUE THREAD

**Issue by kursusHC** [sachinchoolur/lightGallery#253]
I use dynamic mode to launch the gallery on multiple buttons. The only way I've found to make events work is to embed them in the click function every time. I was wondering if there was a better way, ie setting them once for all outside the click function : 

```
$('.button').on('click', function() {
  gallery =  $(this).lightGallery({
  dynamic: true,
  dynamicEl: galleryArray
})

gallery.on('onAfterOpen.lg',function(event){
// Do stuff
});

});
```

**Comment by sachinchoolur** [comment]
Hey @kursusHC,
The following code should work fine.
``` js
$('.button').on('click', function() {
  $(this).lightGallery({
    dynamic: true,
    dynamicEl: galleryArray
  })
})
$('.button').on('onAfterOpen.lg',function(event){
// Do stuff
});
```
