### ISSUE TITLE
How to Make a Manual Call? 

### ISSUE THREAD

**Issue by oompt** [sachinchoolur/lightGallery#255]
I can't seem to find how to call the plugin manually with javascript. 

Is that possible? Thanks.

**Comment by kursusHC** [comment]
Hello, 

What do you mean by "calling manually" ? 

You can can have a look at the Dynamic mode demo here if that's what you're looking for : http://sachinchoolur.github.io/lightGallery/demos/dynamic.html

If not please post a code example.

**Comment by oompt** [comment]
That's what I was looking for. Thanks.
