### ISSUE TITLE
dual licensing?

### ISSUE THREAD

**Issue by splitbrain** [sachinchoolur/lightGallery#256]
Hi I'm considering to use this project in a GPL Version 2 licensed project unfortunately GPLv2 and Apache aren'T compatible. Is there any chance to have lightGallery (dual) licensed with a compatible license (GPL 2, LGPL, MIT, BSD, ...)?

**Comment by loorlab** [comment]
+1

**Comment by rprieto** [comment]
Hi @sachinchoolur, what's your thoughts on that?

I have the same problem in reverse, open-source projects licensed under MIT/Apache cannot upgrade from version 1.2 to 1.3 due to the switch to GPL. Would you consider also having a dual GPL/MIT license for non-commercial projects?

**Comment by loorlab** [comment]
Licensing and freedom are complicated, in the current scenario is crazy.

**Comment by rprieto** [comment]
Agreed, and gets very tricky with `npm`: anyone who depended on `1.x.x` or `^1.0.0` (npm default, means any version up to the next breaking change) is now in breach of license without changing anything.

**Comment by rprieto** [comment]
Another option is to add the following official GPL exemption to the existing license: http://www.gnu.org/licenses/gpl-faq.html#WMS To quote: 

> As a special exception to the GPL, any HTML file which merely makes function calls to this code, and for that purpose includes it by reference shall be deemed a separate work for copyright law purposes. [...]

Which means merely calling `lightgallery` from a website does not constitute derivative work. I'm not sure what it means for programs bundling the code as an `npm` dependency. Just thinking out loud, I'm not a lawyer :)

**Comment by sachinchoolur** [comment]
Hi @rprieto ,
Please sent me an email at sachi77n@gamil.com with your project details. I'll try to help you.
