### ISSUE TITLE
Duplicate entries in the lightbox

### ISSUE THREAD

**Issue by Goldjan** [sachinchoolur/lightGallery#257]
Hi,
if I have two links that point to the same element, they are counted twice. Short explanation: I have a video and link the title AND the image of the video. Light Gallery counts entries twice and I have 10 entries, instead of 5 (at 5 videos).

Here's my script:
`$("body").lightGallery({
        selector: $("body").find("[rel^='lightbox']"),
        thumbnail: false
    });
`

I need a unique identifier.
So I gave the link an ID.

``` html
<div class="row">
    <div class="col-xs-12 col-sm-4">
        <a class="box-pad" href="https://www.youtube.com/watch?v=Oy03Twngcjo" rel="lightbox[2265]">
            <img src="http://img.youtube.com/vi/Oy03Twngcjo/mqdefault.jpg" class="img-responsive">
        </a>
  </div>
  <div class="col-xs-12 col-sm-8">
        <a href="https://www.youtube.com/watch?v=Oy03Twngcjo" rel="lightbox[2265]">
            Industrie 4.0: Diskussionsrunde mit Dr. Georg Ullmann (IPH) 
        </a>
    </div>
</div>
```

How can I light gallery teach that the links lead to the same destination?

**Comment by kursusHC** [comment]
Hi, 

Lightgallery doesn't mind to add two items with the same destination (it can be useful). In your call you're telling it to take care of every element with rel="lightbox", and that's what it does. 

You can either remove rel="lightbox" from one of your item, or put both of them in a new parent and select it with the 'selector' option.

**Comment by Goldjan** [comment]
Is there another solution? Unfortunately, I need both links.

**Comment by kursusHC** [comment]
I you wrap your two items in a new tag and link it to lightgallery it should work as expected (but it won't be pretty). Or you can use [Dynamic mode](http://sachinchoolur.github.io/lightGallery/demos/dynamic.html) and launch the gallery programmatically.

**Comment by Goldjan** [comment]
Wrapping two items in a new tag doesn't work for me.
I now have even given each link pair an ID. I can not solve about it?

**Comment by kursusHC** [comment]
Don't forget to use the 'selector' option. Post a jsfiddle if you need more help.
