### ISSUE TITLE
Adjusting thumbnail image crop CSS: object-fit

### ISSUE THREAD

**Issue by ghost** [sachinchoolur/lightGallery#262]
I get to a better way to view thumbnail images of any size with right proportional using [CSS: object-fit](http://caniuse.com/#feat=object-fit)
`.lg-outer .lg-thumb-item img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}`

I came to his fix when I figured one of my images is not shown with right proportional size (stretched). Hope I might contributed.

**Comment by swrobel** [comment]
@ihabovich thanks for this!

**Comment by kursusHC** [comment]
Another fix would be : 

```
.lg-outer .lg-thumb-item img {
 height: auto;
}

Maybe support is wider than [object-fit](http://caniuse.com/#feat=object-fit). 
```

**Comment by mauricemeyer** [comment]
I just created a pull request [https://github.com/sachinchoolur/lightGallery/pull/341](url) for this issue. It uses _object-fit: cover;_ as it is supported by almost all browsers and looks slightly better than _height: auto;_ (as automatic height can lead to situations where the thumbnail is not fully covered).

The only downside is that in unsupported browsers, the images are still distorted.

**Comment by sachinchoolur** [comment]
Closing as the PR has already been merged.
