### ISSUE TITLE
click only works after tap

### ISSUE THREAD

**Issue by lesarnott** [sachinchoolur/lightGallery#265]
First off - very nice product!  I came across an issue that happens on a laptop with a touch screen.  This tested the same with your online demos.  If I click on a filmstrip thumbnail nothing happens.  If I first finger tap on a filmstrip thumbnail I can then use mouse clicks all the time.

Also, I can finger swipe the photos and the film strip (after first clicking) but I cannot do the same with a mouse grab - not sure if that is supposed to work, jut letting you know.

btw "thumbnials"  typo in Doc:

```
Plugin dependency
You need to include thumbnials plugin (lg-thumbnail.js) in your document to use the following options.
```

Thanks,
Les Arnott
les@qw.com

**Comment by lesarnott** [comment]
A suggestion - I often find that people don't always understand what is "obvious" and I usually put in tool tips on the icons (eg full screen, download, toggle thumbnails), because it's so easy.  

    <span  class="lg-toogle-thumb lg-icon" title="show/hide thumbnails">

**Comment by lesarnott** [comment]
"Plugin dependency
You need to include thumbnials plugin (lg-thumbnail.js) in your document to use the following options."

As I said, I'm testing with your online demo "http://sachinchoolur.github.io/lightGallery/demos/" and that has lg-thumbnail.js included

**Comment by lesarnott** [comment]
Hi, any progress on this?

**Comment by rubb3rfunk** [comment]
Hi, I came across the same issue. Any way to fix this??

**Comment by lesarnott** [comment]
Sorry, I never got a reply to my follow up requests...


On 5/3/2016 7:59 PM, rubb3rfunk wrote:

Hi, I came across the same issue. Any way to fix this??

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub 
<https://github.com/sachinchoolur/lightGallery/issues/265#issuecomment-216730569>




---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by rubb3rfunk** [comment]
I am debugging the lg-thumbnail.js and in line 72-84, I believe the condition for animateThumb setting is in other way around.

>             if (this.core.s.animateThumb) {
                if (this.core.s.enableThumbDrag && !this.core.isTouch && this.core.doCss()) {
                    this.enableThumbDrag();
                }
                if (this.core.s.enableThumbSwipe && this.core.isTouch && this.core.doCss()) {
                    this.enableThumbSwipe();
                }
                this.thumbClickable = false;
            } else {
                this.thumbClickable = true;
            }

it currently assigns false when animateThumb is set to true (by default so) but this should be true, and if I swap these around, it works.

**Comment by sachinchoolur** [comment]
Hey Guys,
The issue has been fixed. Please use the latest version(1.6.0) of lightGallery and its modules.
