### ISSUE TITLE
Make asset paths configurable

### ISSUE THREAD

**Issue by hctom** [sachinchoolur/lightGallery#266]
It would be great to have the font path configurable. This makes it much easier to integrate this cool library into another pre-defined project directory structure.

**Comment by hctom** [comment]
See #267 for a fix

**Comment by hctom** [comment]
I just saw, the image path isn't configurable as well... so I will update the pull request with a variable for that one, too

**Comment by sachinchoolur** [comment]
Thank you @hctom
