### ISSUE TITLE
Bring the Text Overlay Towards the Bottom

### ISSUE THREAD

**Issue by larrybyeo** [sachinchoolur/lightGallery#268]
Right now, the lightGallery has it so that the text overlay (where it says 1 out of however many photos) , along with the zoom, download, and close icons, are at the top of the gallery.  Is there any way to move it towards the bottom, and place it right above the gallery of images located at the bottom of the screen?  The one icon that I would like to remain at the top right would be the close icon, as people are used to seeing it up there.  Thanks!

**Comment by kursusHC** [comment]
Hi, 

You can play with the absolute positioning of `.lg-toolbar`, maybe replace `top` with `bottom` in your CSS file. The close button (`.lg-close`) is nested inside it, so you will need to move it outside `.lg-toolbar` in the JS file and absolute position it to top/right.
