### ISSUE TITLE
lightgallery use inside flickity sider

### ISSUE THREAD

**Issue by kucsatax** [sachinchoolur/lightGallery#270]
First of all sorry for my english. I use flickity slider to show images in a slideable thumbnail gallery. In the flickity slider in the slides there are 'a' tags (a.thumb) which i use to work with lightgallery (selector: '.thumb'). 

My problem is the following: If i try to drag the slider the lightgallery always show up with the picture which on i started to drag the slider.
Id like to work the lightgallery only on a single click on any '.thumb' element, but not if i drag the slider to move left or right.

**Comment by sachinchoolur** [comment]
Closing old support questions.
