### ISSUE TITLE
Double-tap doesn't zoom into area that was tapped

### ISSUE THREAD

**Issue by thdoan** [sachinchoolur/lightGallery#271]
Thanks for adding double-tap support. However, in Chrome for Android 4.4 when you double-tap, it doesn't zoom into the area that was tapped. You can reproduce the issue here:

http://codepen.io/thdoan/full/gPgKVz/

I'm currently using my own quick fix -- this is the way it's supposed to work:

http://codepen.io/thdoan/full/KVaBpj/

**Comment by sachinchoolur** [comment]
Thank you for pointing this out. The issue has been fixed..

**Comment by thdoan** [comment]
Great, thanks for the quick fix!
