### ISSUE TITLE
Issue with close,prev,next icons

### ISSUE THREAD

**Issue by farazch** [sachinchoolur/lightGallery#276]
I successfully configured lightgallery in my project. However, when i click on thumbnail and big image comes up , prev, next, close icons not showing properly. Infact strange characters are showing. This can be viewed on page : http://agentpet.com/lightgallery/lg.html . Please help me out whats wrong in it ?

**Comment by cb4603** [comment]
@farazch i do have the same problem here. Do you have any progress in your project ?

**Comment by abnersajr** [comment]
I tested on Windows 7 Chrome and Firefox last and is working fine your link.
LightGallery have a custom font, what you see is unicode of icon because the font wasn't loaded right.
Check your console log to see if your browser is not blocking font load.

Topic is closed. If other reason create another.

**Comment by AnvarPK** [comment]
i have the same issue in iphone and ipade, it s working fine in windows

**Comment by jshapi05** [comment]
Apologies for the amateur questions here, but I just installed an have little boxes showing for all the icons. I'm working with Shopify, and have installed the base css and js files. Is it required that the font files be installed in order for the icons to show?

**Comment by sachinchoolur** [comment]
Hey @jshapi05 ,
I don't have experience with Shopify. You have to follow the same folder structure to get the fonts work. If it is possible, loading CSS files from [CDN](https://www.jsdelivr.com/projects/lightgallery) would be the best option I think.

Otherwise, you have to upload files individually and override font path via CSS.

**Comment by jshapi05** [comment]
Thanks! Since I only needed the very basic symbols, I was able to overwrite the CSS with what I needed.

**Comment by acmanica** [comment]
Hello. I just install the plugin but no shows any icons(next, prev, fullscreen). Only blank squares are shown. I am using Ruby on Rails. Do I need to do an extra configuration or something? Thanks

**Comment by acmanica** [comment]
> Thanks! Since I only needed the very basic symbols, I was able to overwrite the CSS with what I needed.

Hello can you post your solution?. I have the same problem

**Comment by sachinchoolur** [comment]
Hey @acmanica,

Sorry for the late response.
Please make sure that you have included the fonts folder in the same directory as CSS. 

If the issue persists, please try loading the CSS directly from CDN
https://www.jsdelivr.com/package/npm/lightgallery?path=css

**Comment by miguelgbl** [comment]
@sanjay-gh do you solved it? I am having same problem only in mobile devices (I am using CDN too)

**Comment by arieaditya** [comment]
> In my device Close, prev, next icons do not **append** properly in Lightgallery I use the CDN link in my project the problem only mobile devices

I think this can be done by adding `mobileSettings` props in your LightGallery component since by default the icon will not appear on the mobile.
Ref: [https://www.lightgalleryjs.com/docs/settings/#mobileSettings]

`
<LightGallery
    ...
    mobileSettings={{
        showCloseIcon: true,
        controls: true,
    }}
>
   {*list of photos*}
</LightGallery>
`
