### ISSUE TITLE
How to position "custom-html" (caption) on top?

### ISSUE THREAD

**Issue by q2apro** [sachinchoolur/lightGallery#278]
After updating from 1.1.5 to 2-latest the caption bar is shown on the bottom instead on top, I would like to get it back to the top. Is there any new option? Or do I have pure CSS?

Furthermore the counter/download bar on top is new, I have to remove this.

Thanks for any tip.

**Comment by superbiche** [comment]
You should use the `appendSubHtmlTo` option to tell explicitly where the caption should be inserted.
And if it's still inserted after, maybe prepending a new container with the `onSlideItemLoad.lg`event and using as a target for `appendSubHtmlTo` would do the trick.

**Comment by sachinchoolur** [comment]
Closing old support questions.
