### ISSUE TITLE
Needs to be wrapper for module loader

### ISSUE THREAD

**Issue by connorjburton** [sachinchoolur/lightGallery#280]
Currently if you ```npm install lightgallery``` then try to ``` require('lightgallery') ```

It fails, the JS needs be wrapped in

```
;(function(factory) { // eslint-disable-line no-extra-semi
    'use strict';
    if (typeof define === 'function' && define.amd) {
        // AMD
        define(['jquery'], factory);
    } else if (typeof module !== 'undefined' && module.exports) {
        // CommonJS
        module.exports = factory(require('jquery'));
    } else {
        // Global
        factory(jQuery);
    }
})(function($) {
   //plugin here
});
```

However, this will mean jQuery will need to be added as a dependency in package.json

Then simply doing ``` require('lightgallery') ``` will expose the plugin to ```jQuery``` which means the final code would be:

```
var $ = require('jquery');
require('lightgallery');

$('.element').lightGallery();
```

**Comment by connorjburton** [comment]
See this gist for what I had to do to get it working as above:

https://gist.github.com/connorjburton/546f94ebf7f11cdcbca9

**Comment by sk29110** [comment]
I installed current version of lightGallery with npm but still broken after import into my application
import $ from 'jquery';
import GalleryLight from 'lightgallery';

$('#mygallery').lightGallery(); //lightGallery is not function

**Comment by kp25** [comment]
@sk29110 Try looking at the gist mentioned by @connorjburton; 
Gist works fine 👍

**Comment by JSteunou** [comment]
@sachinchoolur Your lib still does not work with AMD/CommonJS and that obvious why

You're exposing `$` to context while using variable `jQuery` to IIFE

see https://github.com/sachinchoolur/lightGallery/blob/master/dist/js/lightgallery.js#L19
and https://github.com/sachinchoolur/lightGallery/blob/master/dist/js/lightgallery.js#L1337

So unless you have a global variable `jQuery` this cannot work.

**Comment by sachinchoolur** [comment]
Hi Guys,
I've added support for AMD,CommonJS, and ES6 modules.
@JSteunou I've updated the code.  Could you please verify?

**Comment by JSteunou** [comment]
Yep, that's good. But I would go further and drop that IIFE, you do not need it anymore as your main section is inside an UMD IIFE

**Comment by sachinchoolur** [comment]
I added that to avoid jshint warning `Use the function form of "use strict".`
