### ISSUE TITLE
namespace "group" class as "lg-group"

### ISSUE THREAD

**Issue by marcvangend** [sachinchoolur/lightGallery#285]
Currently, the JS creates elements with `class = "group"` and the CSS contains rules for the `.group` selector. This is very unfortunate because "group" is a very common word. All class names except "group" are namespaced with "lg-". Collisions with other elements with classname "group" are likely to happen, and when it does, you will find lightGallery messing with your layout.

Can you please rename all occurences of the "group" class name to "lg-group"?

**Comment by abnersajr** [comment]
Of course, soon as possible I will make this change.

**Comment by sachinchoolur** [comment]
Hey @marcvangend ,

The issue has been fixed. Please use the latest version of lightGallery

**Comment by marcvangend** [comment]
Excellent, thank you.
