### ISSUE TITLE
IOS/IPad Crash on 50+ images

### ISSUE THREAD

**Issue by itbeyond** [sachinchoolur/lightGallery#286]
I have been using lightGallery with great success so firstly thanks. On one of our sites I have noticed that if there is more than 50 images on a page and lightGallery is called IOS/IPads crash with a page has caused the browser to crash and the page reloads. YOu can easily see this occur on this page http://www.exploroz.com/Members/82/1/2016/The_Art_of_Exploring_-_Instinctive_or_Learned_.aspx if you click to open any image it will crash on IOS/IPad - if you open any page in this area with up to 50 images it seems to be ok nut this one at 51 crashes all iPads tested from very old to current iPad Air 2 devices. Same code 25 images on this page http://www.exploroz.com/Members/82.875/7/2015/Man_vs_Wild___Ningaloo_-_Part_4.aspx works fine with no problems.

I understand/believe there is some memory limit to the amount of memory used on IOS devices but wonder if this is the problem and if there is a resolution.

**Comment by sachinchoolur** [comment]
Hey @itbeyond ,

The issue has been fixed. Please use the latest version of lightGallery
