### ISSUE TITLE
onCloseAfter does not work for Iframe

### ISSUE THREAD

**Issue by zaheedk** [sachinchoolur/lightGallery#288]
Hi Sachin,

I have recently started using your lightgallery plugin in one of my projects to serve up pages using iframe with lightgallery. Everything works fine except the function of onCloseAfter does not trigger. I am not sure if this function is supported for iframes?

Following is my code

$("#addlistingevent").lightGallery({
            selector: 'this',
            iframeMaxWidth: '80%',
            iframeMaxHeight: '80%',
            onCloseAfter: function (event) {
                alert('onCloseAfter : Executes immediately once Colorbox is closed;');
                parent.location.reload(true);
            }
        });

Any guidance/help is much appreciated.

Thanks
Zaheed

**Comment by kursusHC** [comment]
Hi, 

Events are meant to be used this way : 
```
    var $lg = $('#lightgallery');

    $lg.lightGallery({
      //init gallery with params 
    });

    $lg.on('onCloseAfter.lg',function(event){
      console.log('working');
    });
```

On a side note be careful with location.reload, I can't think of a case where it's a good idea.
