### ISSUE TITLE
Zoom Plugin Array Issue

### ISSUE THREAD

**Issue by cillosis** [sachinchoolur/lightGallery#291]
I'm using dynamic images in a light gallery like this:

```
$(document).on('click', '.btn-view-photos', function(e) {
    e.preventDefault();
    var files = JSON.parse($(this).attr('data-images'));
    if (files.length > 0) {
        var srcset = [];
        for (i = 0; i < files.length; i++) {
            srcset.push({
                'src': files[i].replace(/\/64\//, '/640\/'),
                'thumb': files[i],
                'subHtml': 'Photo #' + (i + 1),
                'width': 640
            });
        }
        $(this).lightGallery({
            dynamic: true,
            dynamicEl: srcset
        });
    }
});
```

This works fine, but with the **lg-zoom** plugin, double clicking a photo throws an error on line 120:

> Uncaught TypeError: _this.core.$items.eq is not a function

Tracing it down, it is because `$items` is not a jquery object -- it is a normal Javascript array. For the time being, I was able to create a quick and dirty code snippet to get past this by adding an `eq()` method to the Array object prototype.

```
Array.prototype.eq = function(index) {
    if (this[index] !== undefined) {
        return $(this[index]);
    } else {
        return null;
    }
}
```

This probably isn't a good way to handle it, but I have code in production that is throwing errors so this fix is the best I can do under short time notice. 

I'd submit a PR, but I'm not quite sure if this is an issue in the core library or if it is an issue with the plugin (or maybe me just doing it wrong?). Just wanted to bring it to your attention if you get some free time and know a quick fix. Thanks for the awesome library!

**Comment by kursusHC** [comment]
Hi,

Could you show your html or better post a fiddle ? From the top of my head I think the error is due to the unconventional way you are populating the array.

**Comment by rochapablo** [comment]
Hey!

I was having quite the same problem...

Using the dynamic option the zoom wasn't working. So I've just loaded the _libs_ and every thing start to work.

```
"lightgallery-all.min.js"
"picturefill.min.js"
```

**Comment by perezgarrym** [comment]
also for me here is my code 
```
$.ajax({
				  	url: "images/prenup/",
				  	success: function(data){
					    var dynamicPics = [];

					    $(data).find("a:contains(.jpg)").each(function(){
					        // will loop through 
					        var images = $(this).attr("href");
					        var imgObj ={
						            "src": 'images/prenup/'+images,
						            'thumb': 'images/prenup/'+images
						        };
						    dynamicPics.push(imgObj);
					    });
					    //load gallery
					    $("#prenup-gallery").lightGallery({
					        dynamic: true,
					        fullScreen: false,
					        dynamicEl: dynamicPics
					    });
				  	}
				});
```

**Comment by sachinchoolur** [comment]
Closing old support questions.
