### ISSUE TITLE
Move image zoom (drag-drop ) bug only on firefox

### ISSUE THREAD

**Issue by bibi-babi** [sachinchoolur/lightGallery#295]
drag-drop control or mouse hand icon does not work in the version of firefox.
while chrome working properly.
The problem is when you zoom in on a picture and you can not move to see the various parts magnified.

**Comment by kursusHC** [comment]
Hi, 

Zoom and pan function does work with Firefox 44 Linux on the [demo page](http://sachinchoolur.github.io/lightGallery/demos). Please post some code to get more help.

**Comment by Thyme1152** [comment]
It doesn't work with v47.0.1 on Mac, including on the demo page.

**Comment by bassambarham** [comment]
Hi

Doesn't work on Windows 10 Firefox 49.0.1 as well.

**Comment by xrat** [comment]
Same here, Firefox 53 (on Ubuntu but I am pretty sure that does not matter). Trying to drag/pan/move the zoomed image does not work. Firefox immediately uses its internal function that allows to drag-n-drop images onto other tabs, into other windows etc.

**Comment by xrat** [comment]
Uhm, just tried it again, same Firefox 53, same O/S, and now it works perfectly. No idea what's going on. Sorry for the noise.
