### ISSUE TITLE
How to open a traditional gallery ( not dynamic ) by clicking a button?

### ISSUE THREAD

**Issue by daniel-inacio** [sachinchoolur/lightGallery#298]
I can not do something this way

**Comment by kursusHC** [comment]
Hi, 

You can trigger a click with jQuery : 

```
$('#mybutton').on('click', function() {
   $('.first-item).trigger('click');
});
```

**Comment by sachinchoolur** [comment]
Hi @kursusHC,
Once again thank you for your support.. :+1: 
Would you be interested in joining to this project as a collaborator?

**Comment by daniel-inacio** [comment]
Yes i can.







------------------------------
Daniel Inácio
(16) 9280-7747
/daniel.inacioo <http://www.facebook.com/daniel.inacioo>
@iiinacio <https://twitter.com/iiinacio>
------------------------------

2016-02-17 14:28 GMT-02:00 Sachin N <notifications@github.com>:

**Comment by kursusHC** [comment]
Hi @sachinchoolur thanks for the proposal, I don't have a lot of free time but I'd be glad to help !

**Comment by sachinchoolur** [comment]
@kursusHC I can understand. I have added you to this project as a collaborator. Hope you will continue to support the project.
Thank you
