### ISSUE TITLE
destroy is not working

### ISSUE THREAD

**Issue by surfNicolas** [sachinchoolur/lightGallery#300]
Hi,
thanks for using your lightgallery. First I used it only for images and videos. Now I use it for iframes. this is my html with jQuery: 
<img data-iframe="true" data-src="/DataListing.php?popup=1&datadefID=9&datadefmode=3&type=resource&searchform=inputform&searchkeyname=parentresID&searchdispname=parentresIDdisplay&clientID=8&myses_loggedin=1" id="parentresID_search" class="iconinput" src="/pic/icon_search.png" alt="Suchen" title="Suchen">

<script>$('#parentresID_search').lightGallery({selector:'this'});</script>

The lightGallery opens and shows my website. I press a button and want to close the lightgallery:

```
var lg=$('#parentresID_search');
lg.lightGallery();
lg.data('lightGallery').destroy(true);
```

I get the error message: lg.lightGallery is not a function

Is it a problem in my code or a problem with the iframes?

Greeting and thanks in advance
Klaus Eisert

**Comment by kursusHC** [comment]
Hi, 

Close button is supposed to work with iframes. The link to your code is broken, can you update it ?

**Comment by Dimalolzet** [comment]
It happens when gallery is not initialized. You should check it.

```
if (lg.data('lightGallery'))
    lg.data('lightGallery').destroy(true);
```
