### ISSUE TITLE
Destroy method - scroll to top problem

### ISSUE THREAD

**Issue by ZsharE** [sachinchoolur/lightGallery#303]
Hi,

I have a problem using this plugin when i try to destroy and reinitialize the plugin.
Example: http://sachinchoolur.github.io/lightGallery/demos/methods.html

Step 1: Click on an image, then close it.
Step 2: Scroll a little bit down and press "Append new item".

Problem: It will scroll to top, but if you skip the first step everything works fine.
I'm using it with infinite scroll and is very annoying.

Any suggestion ? Thanks !

**Comment by kursusHC** [comment]
Hi, 

Indeed. Waiting for a fix you can disable the scrollTop function when closing the gallery (as you may have noticed gallery is destroyed when appending a new item). Just comment out this line in the destroy method (around line 1230) : 

```
// $(window).scrollTop(_this.prevScrollTop);
```

**Comment by ZsharE** [comment]
Thanks a lot !
