### ISSUE TITLE
Image link and text link, both should link to same gallery

### ISSUE THREAD

**Issue by benjipnz** [sachinchoolur/lightGallery#304]
I'm glad I've found lightGallery as it does everything I was after in a Lightbox (especially the full-screen features). My one issue I'm having is that I need to have a small image and a text link, both wrapped in their own < a href > but both pointing at the exact same filename. So in other words, the user can click on either the small image or a "Click here to expand image" text link.

I have got around any issues by having two different selectors, with my code roughly as follows:

```
<div id="lightgallery"><a href="/Giant_Image_1.jpg" class="lightgallery-slide-item"><img src="/Small_Image_1.jpg" /></a></div>
<div class="lightgallery2"><div class="slider-controls-expand"><a href="/Giant_Image_1.jpg" class="lightgallery-slide-expand"><i class="fa fa-expand"></i></a></div></div>

<div id="lightgallery"><a href="/Giant_Image_2.jpg" class="lightgallery-slide-item"><img src="/Small_Image_2.jpg" /></a></div>
<div class="lightgallery2"><div class="slider-controls-expand"><a href="/Giant_Image_2.jpg" class="lightgallery-slide-expand"><i class="fa fa-expand"></i></a></div></div>
```

``` javascript
        $("#lightgallery").lightGallery({
            galleryId: 1,
            selector: '.lightgallery-slide-item',
            download: false
        });

        $(".lightgallery2").lightGallery({
            galleryId: 2,
            selector: '.lightgallery-slide-expand',
            download: false
        });
```

However, the problem is now that the text link doesn't seem to recognise the other text links, so when I click the text link to open the lightGallery, it thinks there is only one image in total and doesn't give me the forward/back stuff. If I click the small image though, it works perfectly.

I'm hoping I've just coded the selectors incorrectly or something easy like that.

Any help would be hugely appreciated!

**Comment by kursusHC** [comment]
Hi, 

The selector used for LightGallery has to be the container of all your items, as seen on the [basic demo](http://sachinchoolur.github.io/lightGallery/demos/). So your html can't work, since every gallery container (#lightgallery and .lightgallery2) has only one child each time. So the result you got is perfectly normal. On a side note be careful not to use twice the same id as it can easily break a lot of things ! 

So you have two solutions : 

1- Proper markup
Hard to help you on this since we don't know what the result should be like, but basically you can put everything you want in a gallery item, and bind the click on it : 

```
<div id="lightgallery">
	<a href="/Giant_Image_1.jpg" class="lightgallery-slide-item">
		<img src="/Small_Image_1.jpg" />
		<p><i class="fa fa-expand"> Click to expand</p></i>
	</a>
	<a href="/Giant_Image_2.jpg" class="lightgallery-slide-item">
		<img src="/Small_Image_2.jpg" />
		<p><i class="fa fa-expand"> Click to expand</p></i>
	</a>
	<a href="/Giant_Image_3.jpg" class="lightgallery-slide-item">
		<img src="/Small_Image_3.jpg" />
		<p><i class="fa fa-expand"> Click to expand</p></i>
	</a>
</div>
<script>
    $("#lightgallery").lightGallery({
            selector: '.lightgallery-slide-item'
        });
</script>
``` 
This should work. 

2- Use [Dynamic mode](http://sachinchoolur.github.io/lightGallery/demos/dynamic.html) 
Most likely the easier solution. Populate the array with your data and use the index option to open the correct slide: 
``` 
<div id="lightgallery">
	<a class="item" data-slide="1">
		<img src="/Small_Image_1.jpg" />
		<p><i class="fa fa-expand"> Click to expand</p></i>
	</a>
	<a class="item" data-slide="2">
		<img src="/Small_Image_2.jpg" />
		<p><i class="fa fa-expand"> Click to expand</p></i>
	</a>
	<a class="item" data-slide="3">
		<img src="/Small_Image_3.jpg" />
		<p><i class="fa fa-expand"> Click to expand</p></i>
	</a>
</div>
<script>
    $(".item").on('click', function(){
     var slideID = $(this).attr('data-slide');
     $("#lightgallery").lightGallery({
               dynamic: true,
               dynamicEl : myArray,
               index : slideID
        });
   });
</script>
```

**Comment by benjipnz** [comment]
Perfect, thank you so much. Option 1 seems to be doing the trick. The only issue is that since the whole DIV is now wrapped in an A tag, I'm losing the hover effects I had on the text and icon (since the browser is, correctly, interpreting the whole thing as a link). I don't suppose there's a way around that?

**Comment by benjipnz** [comment]
One last question. I have image captions which are fairly long and which include other links. These captions sit below the images and therefore fall between the anchor tags as demonstrated in kursusHC's "Option 1 - Proper markup" above. The issue seems to be that these links are breaking the container's link (and obviously it's poor form to have links within links). Any suggestions what I could do to prevent this?

I would be happy to have the secondary links only clickable when the gallery is opened (so when they are showing as just the captions before the user clicks to initiate lightGallery, the links are muted, however when viewing the large image they are clickable) but obviously including them as part of the 'data-sub-html' is breaking things because it's output just the same.

**Comment by benjipnz** [comment]
Hi kursusHC,

I ended up going the dynamic route so feel free to ignore the above (sorry!).
