### ISSUE TITLE
On Android devices ONLY thumbs are broken images

### ISSUE THREAD

**Issue by bdairy** [sachinchoolur/lightGallery#311]
Dear, and thanks for the great library.

I have a problem that the thumbs are not working on android browsers, and works everywhere else.. I am talking only about when we add thumbs in the HTML,,, if we used the API in dynamic mode it works,, and the problem happens only on android devices. works nice on iOS,, also in chrome developer mode.

**Comment by sachinchoolur** [comment]
Closing old support questions.
