### ISSUE TITLE
selectWithin Feature

### ISSUE THREAD

**Issue by eppak** [sachinchoolur/lightGallery#313]
There is a way to make a global gallery on items nested more than one leve? Now the gallery is done in this way:

```
<ul id="gallery">
<li><a>IMG</a>
...
</ul>

```

I want to make a grid with tw bootstrap like:

```
<div class="container" id="gallery">

<div class="row">
<div class="col-md-3"><a>IMG</a></div>
<div class="col-md-3"><a>IMG</a></div>
<div class="col-md-3"><a>IMG</a></div>
<div class="col-md-3"><a>IMG</a></div>
</div>

<div class="row">
<div class="col-md-3"><a>IMG</a></div>
<div class="col-md-3"><a>IMG</a></div>
<div class="col-md-3"><a>IMG</a></div>
<div class="col-md-3"><a>IMG</a></div>
</div>

</div>
```

is possible?

**Comment by kursusHC** [comment]
Not tested but did you try using the Selector option ? Like 

```
    $('#lightgallery').lightGallery({
        selector: '.col-md-3'
    }); 
```

In this case add another class so you don't have to use the Boostrap one (in case you change it later). Also just so you know your grid would still work as intended without the extra row markup, like 

```
<div class="container" id="gallery">

<div class="row">
<div class="col-md-3"><a>IMG</a></div>
<div class="col-md-3"><a>IMG</a></div>
<div class="col-md-3"><a>IMG</a></div>
<div class="col-md-3"><a>IMG</a></div>
<div class="col-md-3"><a>IMG</a></div>
<div class="col-md-3"><a>IMG</a></div>
<div class="col-md-3"><a>IMG</a></div>
<div class="col-md-3"><a>IMG</a></div>
</div>

</div>
```

**Comment by sachinchoolur** [comment]
More  info - http://sachinchoolur.github.io/lightGallery/demos/html-markup.html

**Comment by nk9** [comment]
When I use the `selector setting` as suggested, the links are behaving like actual links. When I click the thumbnails, instead of the lightGallery UI coming up, the click causes a new page load of the full image at the link in the `<a>` tag.
