### ISSUE TITLE
Can I call this from react component?

### ISSUE THREAD

**Issue by sk29110** [sachinchoolur/lightGallery#315]
https://egghead.io/lessons/react-using-react-with-the-fullcalendar-jquery-plugin

I added lightGallery to my react component based on this tutorial, however it always said lightGallery is not function. 

How can make use this in react component?

`
import LightGallery from 'lightgallery';

componentDidMount: functino(){
    var galleryConainer = $(this.refs.gallerySection.getDOMNode());
    galleryContainer.lightGallery();
}`

**Comment by barczaG** [comment]
yo

this is how i integrated this plugin to react:
the important part is componentDidMount and componentDidUpdate, i hope it helps :)
```
/* global $ */
import React, {PropTypes} from 'react'
import {connect} from 'react-redux'
import _ from 'underscore'
require('lightgallery')

class Slider extends React.Component {
  static propTypes = {
    photos: PropTypes.array,
    defaultPhoto: PropTypes.string
  }

  componentDidMount () {
    if ($('#lightgallery').data('lightGallery')) $('#lightgallery').data('lightGallery').destroy(true)
    $('#lightgallery').lightGallery()
  }

  componentDidUpdate () {
    if ($('#lightgallery').data('lightGallery')) $('#lightgallery').data('lightGallery').destroy(true)
    $('#lightgallery').lightGallery()
  }

  render () {
    let {photos, defaultPhoto} = this.props
    photos = photos || []
    photos = _(photos).without(defaultPhoto)
    photos.unshift(defaultPhoto)

    return <div id='lightgallery'>
      {photos.map((photo) =>
        <a href={`http://res.cloudinary.com/szallashu/image/upload/${photo}`}>
          <img src={`http://res.cloudinary.com/szallashu/image/upload/c_fill,h_500,w_500/${photo}`} />
        </a>
      )}
    </div>
  }
}

export default connect((state) => ({...state.profile}))(Slider)
```

**Comment by yankeyhotel** [comment]
@sk29110 did you find an answer to this?

**Comment by donaldboulton** [comment]
I would like to know same issue.

**Comment by sk29110** [comment]
Just did the same like barczaG did and add facebook comment right next. It's not pretty in terms of coding :(

![screen shot 2018-09-17 at 9 06 58 pm](https://user-images.githubusercontent.com/626182/45663882-a97e1d80-babd-11e8-98be-9383599a22bb.png)
