### ISSUE TITLE
Issue about applying Lightgallery on class selector instead of ID

### ISSUE THREAD

**Issue by federone** [sachinchoolur/lightGallery#319]
hi,

thank  you very much for this amazing lightgallery.

there is an issue about applying Lightgallery on a class selector instead of ID.

here's fiddle - https://jsfiddle.net/122y9zxa/

do this:
1) click on first image - as default it will show a popup - everything works fine - and close it.
2) click on second image - same .. as default it will show a popup - again everything works fine - and close it.
3) Now click again on 1-st image - image dont loads ... only shows preloader gif ... thats the issue.
If you click close and then again open it - yes, it will show up - but problem is that it shows up only on 2-nd click....

maybe i'm doing something incorrectly?

Best Regards,
Federico

**Comment by sachinchoolur** [comment]
Please use the latest version of lightGallery
