### ISSUE TITLE
Videos don't play on Video.js demo page

### ISSUE THREAD

**Issue by goatlady** [sachinchoolur/lightGallery#320]
Referring to this demo page:
http://sachinchoolur.github.io/lightGallery/demos/html5-videos.html#video-without-poster

The videos do not play in the lightGallery when you click the play button. 

Setting the hidden video source to display:block using Firebug shows that the videos DO function, so the error is in lightGallery or in the parameters used on the page, not with Video.js.

**Comment by Harmattan322** [comment]
Any reason? Same problem...

**Comment by Harmattan322** [comment]
firstly, needed 	<script src="js/**lg-video.js**"></script> and 	<script src="js/**video.js**"></script>

**Comment by sachinchoolur** [comment]
Closing old support questions.
