### ISSUE TITLE
hash plugin is working?

### ISSUE THREAD

**Issue by sk29110** [sachinchoolur/lightGallery#323]
I am using lightGallery with my rest api app. So gallery page is mydomain/#gallery.
If I have hash on and when I click on the image it does change the url to mydomain/#/lg=1&slide=1?_k=qhecp4 then closing the dialog will put the url back to mydomain/#gallery. Because of this the gallery section gets refreshed since the url is changed. Is it how it supposed to work or this is bug?

**Comment by sandipkumbhani** [comment]
You can do hash= false as below so URL will not change

  $lg.lightGallery({
        thumbnail: true,
        **hash:false**
    });
