### ISSUE TITLE
Disqus

### ISSUE THREAD

**Issue by rafaelkowal** [sachinchoolur/lightGallery#324]
Already have any plans to support Disqus comments?

**Comment by cakama3a** [comment]
+1

**Comment by edemkecskes** [comment]
Is there any update about the Disqus integration?

**Comment by sachinchoolur** [comment]
Added to my todo list :)

**Comment by monkkkkk** [comment]
Any  update on adding Disqus?

**Comment by sachinchoolur** [comment]
https://sachinchoolur.github.io/lg-comment/demos/methods.html Will be released in version 2.0

**Comment by braindeaf** [comment]
Looks like lg-comment is running into a issues with Disqus. I just can't find the solution and it appears to be how DISQUS is reloaded. The profile and discussion are just not loaded properly in the comment box and subsequently the Community link fails to open and kills the whole interface.

Uncaught TypeError: Cannot read property 'forumsFollowing' of undefined

https://iplayred.co.uk/conventions/spiel-2019/releases#lg=1&slide=27
