### ISSUE TITLE
When destroying the lightGallery onAfterAppendSubHtml is not unregistered

### ISSUE THREAD

**Issue by sk29110** [sachinchoolur/lightGallery#326]
Even I destroy the light gallery the event is not unregistered so on the following code onAfterAppendSubHtml is called multiple times when reinitializing the lightGallery.

`if( galleryContainer.data('lightGallery')){
    galleryContainer.data('lightGallery').destroy(true);
}

galleryContainer.lightGallery({
hash: false,
addClass: 'fb-comments',
download: false,
thumbnail: false
});
galleryContainer.on('onAfterAppendSubHtml.lg', function() {
    try {
        FB.XFBML.parse();
    } catch (err) {
        $(window).on('fbAsyncInit', function() {
          FB.XFBML.parse();
         });
    }
});
`

**Comment by randomblowupSteve** [comment]
I also got this issue, does anyone has a solution for this? I use load more button to do ajax call "onAfterAppendSubHtml.lg" event, for example, after I click load more button to trigger ajax call twice, "onAfterAppendSubHtml.lg" would be implemented twice.

**Comment by awplige** [comment]
I am also looking for this issue.
Added load more button, newly generated image HTML markup not working opening into the lightbox.
Any help appreciated.

Thanks
