### ISSUE TITLE
thumbContHeight and position of subHtml

### ISSUE THREAD

**Issue by sokai** [sachinchoolur/lightGallery#327]
Hey!

I wish the bottom position of the caption class (`.lg-sub-html`) is calculated with dependencies of the height of the thumbnail container (if the option `thumbContHeight` is used/set).

ATM `.lg-sub-html` is defined with `bottom: 100px;` in [lightgallery.css#L338](https://github.com/sachinchoolur/lightGallery/blob/1.2.16/src/css/lightgallery.css#L338).
So if I set `thumbContHeight` (because I only provide thumbs with 40px height) there will be a gap between the caption and the thumbs container and I have to set  `bottom: 60px;` in my local stylesheet (which IMHO is not programmatically …).

Thanks a lot and best regards! :-)

**Comment by artursopelnik** [comment]
+1

**Comment by artursopelnik** [comment]
Hi @sokai . Here is my workaround for that case:

```javascript
var slider = $('.gallery');
var options = {
thumbnail: true,
thumbContHeight: 88
}

gallery.lightGallery(options).on('onAfterOpen.lg', function () {
                $('.lg-outer.lg-pull-caption-up.lg-thumb-open .lg-sub-html').css('bottom', options.thumbContHeight);
            });
```

**Comment by sokai** [comment]
Thx @artursopelnik !
