### ISSUE TITLE
LightGallery on openlayers3 with geojson 

### ISSUE THREAD

**Issue by Brian393** [sachinchoolur/lightGallery#328]
Hello -

I am using LightGallery in OpenLayers3 to display sequences of images that are accessed by clicking on a marker with geojson file behind it. It works perfectly for the images, but I can't figure out how to get a youtube video to display. My geojson for the image gallery looks like this:

{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "Name": "Indiana Harbor",
"images":[

        {"src": "Galleries/IndianaHarbor/1.JPG",
	"subHtml": "Anthropocene landscape: Indiana Harbor and Ship Canal"}
] }, 
"geometry": { "type": "Point", "coordinates": [ -87.4501, 41.6618 ] } }
]
}

What should I put in place of the .jpg to get a video? I have tried everything I can think of!

Thanks, Brian

**Comment by sachinchoolur** [comment]
Hi,
I have never worked with openlayers3. But to get video instead of image you can use the video url from youtube address bar.
I would suggest you to ask this question on stackoverflow. Someone who has experience with openlayers3 might help you.
