### ISSUE TITLE
Zoom 100% and no more

### ISSUE THREAD

**Issue by bartoszmalec** [sachinchoolur/lightGallery#329]
Any one know how to allow zooming only to 100% and not more?

It is not good to look on the pixels.

Thanks for any help.

**Comment by sachinchoolur** [comment]
Hi,
You can double click on the images to see the actual size of the images. Any way i will add an icon on the toolbar for zooming images to it's actual size..

**Comment by sachinchoolur** [comment]
Hi,
I have added an icon on the toolbar to view the actual size of the image(100%). 
Please use the latest version

**Comment by bartoszmalec** [comment]
Thank you @sachinchoolur
