### ISSUE TITLE
Re-instantiate after async refreshing images

### ISSUE THREAD

**Issue by pimhooghiemstra** [sachinchoolur/lightGallery#330]
Lightgallery is working magically on pageload. 

However, we get a new series of images in the HTML (via async ajax request) when the user presses a button. After this, the lightgallery doesn't work anymore: i.e., clicking the image just shows it in a new tab.

Is it possible or do we have to take the 'dynamic' route to accomplish this?

**Comment by sachinchoolur** [comment]
Hi,
You need to destroy the gallery before adding new items..
Please refer the bellow link
http://sachinchoolur.github.io/lightGallery/demos/methods.html

**Comment by hummal** [comment]
Had the same problem and wrote a special autoReload plugin for lightgallery for my needs. 

Works like a charm

**Comment by unitedworx** [comment]
@hummal care to share your autoReload plugin? I dynamically add images to the DOM and light gallery is broken in these newly added images so would like if the gallery to auto init islet when an image is clicked!

**Comment by hummal** [comment]
Sure would I.
Created a fast repo. Its also in npm repository. 

There could be some special issues Iam not aware of. So take care!

https://github.com/hummal/lg-autoupdate

**Comment by unitedworx** [comment]
thanks for the plugin, but I still have to manually tell light gallery to reload when I modify the Dom using the "refreshItems" event right?  If so I was hoping for something for automatic :)

The blow code seems to do it for me so I dont have to tell light gallery every time I update the Dom to reaload light gallery. Although it works fine for some reason the dark black background some times shows and some times it does not. Not sure why! 

    $(".lightgallery-items").bind('DOMSubtreeModified', function() {
	$(".lightgallery-items").data('lightGallery').destroy(true);
	
	$(".lightgallery-items").lightGallery({
		selector: '.lightgallery-item',
		download: false,
		pause:2000
	});	
	
    });

**Comment by hummal** [comment]
For my plugin I had a very own reason to do it with the event. 
I bind to the before next slide event and check there how many images I have loaded. If it is near a threshold I start reloading my new images. 
So if Iam a customer I have the gallery open and if you add images while the gallery is open and destroy it then it will disappear. 
So destroying is no options for me. 

If performance is no issue for you, you also can extend the plugin by an interval check for this.core.$items.length and if it has changed -> refresh. 

I do care about performance so this was not an option.

**Comment by unitedworx** [comment]
surely I understand you use case :) it makes sense to it that way! in my case this is in the back-end not the frond end! so no worries :) I also change the images so I needed to have this working then I add images, when I delete them and when I edit them. I seems that 2 lines to code after each action solved it. although I was hoping to have lightgallery handle this itself like a previous plugin I was using(fancybox). that one didn't have a problem in my use case since it created the gallery after you clicked on one of its items!

**Comment by hummal** [comment]
Lightgallery has its own markup for the slides. This is the reason why its not working out of the box. 
fancybox just uses the markup you provide and if there are new images its done.

**Comment by unitedworx** [comment]
@hummal how to you trigger the "refreshItems" Event? I tried to get lg-autoupdate working but I couldn't :(

**Comment by hummal** [comment]
@unitedworx  first of all: Completely wrong place to talk about that. You could make an issue in my repository. Please remember.
Second: I added an example jsfiddle for you in my readme: https://github.com/hummal/lg-autoupdate
