### ISSUE TITLE
Video after click play hides or not loading at all

### ISSUE THREAD

**Issue by n0xx** [sachinchoolur/lightGallery#331]
Hi, i have a strange problem with Your gallery, on 99% pc's everything working great but on other few machines i have strange problem.

thumbnail click > gallery with video shows >  btn play click > loading.gif (1/2sec) > window with video close
or
thumbnail click > gallery with video shows >  btn play click > not loading video at all (btn not working)

Im using lightgallery-all.min.js
My setup:

```
if ($('.bazafirmgaleria').length > 0) { 
$(".bazafirmgaleria").lightGallery({
download:false,
fullScreen:false,
autoPlay:false,
autoplayControls:false,
animateThumb: true,
showThumbByDefault: true,
loadYoutubeThumbnail:1,
vimeoThumbSize:'thumbnail_large'
}); 
}
```

html:

```
<div class="box_wrapper">
<div class="bazafirmgaleria">
<a href="https://www.youtube.com/watch?v=eeTnog5RRQo" data-src="https://www.youtube.com/watch?v=eeTnog5RRQo" data-sub-html="<h4>titletitletitle</h4><p>subtitlesubtitlesubtitle</p>"  data-poster="img/_temp/img3.gif"><img src="img/_temp/img3.gif"/></a>
<a href="https://www.youtube.com/watch?v=eeTnog5RRQo" data-src="https://www.youtube.com/watch?v=eeTnog5RRQo" data-sub-html="<h4>titletitletitle</h4><p>subtitlesubtitlesubtitle</p>"  data-poster="img/_temp/img3.gif"><img src="img/_temp/img3.gif"/></a>
</div>
</div><!--end bazafirmgaleria-->

```

Not working on chrome ver. 49.0.2623.110 m

**Comment by sachinchoolur** [comment]
It works fine on my system(Same version of chrome). It would be helpful to figure out the issue if you could provide a jsfiddle demo for your setup..

**Comment by n0xx** [comment]
Thanks for answer,
I know right ? I've tested it on 14 computers and on 2 (same lenovo laptops) it's not working, on any other working like a charm.
Funny thing - picture gallery works great on all of them, only video is the issue.

I can give You whole site --> http://www.outsourcingportal.eu/pl/wizytowka-firmy/s8-sa/video

**Comment by sachinchoolur** [comment]
Your site works fine on my system
![s8 sa outsourcing portal portal wiedzy o outsourcingu](https://cloud.githubusercontent.com/assets/6586706/14290769/115fe034-fb7e-11e5-8e51-6a37ee1a7311.png)

**Comment by n0xx** [comment]
Yes i know Sanchoolur, it's working on my systems too but as i said there is two that not working:

thumbnail click > gallery with video shows > btn play click > loading.gif (1/2sec) > window with video close
or
thumbnail click > gallery with video shows > btn play click > not loading video at all (btn not working)

Do you have any idea where I can find a solution to this problem ?
Can I use this lightgallery-all.min.js or should i use separate scripts that are in "src" folder ?

**Comment by sachinchoolur** [comment]
Hi,
It works fine on both scenarios. Could you please provide a video which demonstrates your problems..

**Comment by lisaschiffli** [comment]
I think I am experiencing the same problem. Same version of Chrome running on Windows 10. The Youtube/Vimeo with Posters Demo does not work now and it did a few weeks ago. The Youtube/Vimeo without Posters Demo works. Also, the website n0xx posted does not work for me either. However, both the Demo and his website work with Firefox for me. I'm continuing to try to debug and find the cause.

**Comment by n0xx** [comment]
@sachinchoolur when i will be able to record it on those computers I will make a movie.

@lisaschiffli Those 2 computers are on windows 10 too.

**Comment by lisaschiffli** [comment]
Debugging on my project shows that it seems to work until clicking on the play video button. On Firefox, that's where "loadOnClick" is called from the if stmt around line 159 in lg-video.js. The alert I have inserted never fires on Chrome. Nothing happens when the play video button is clicked. I have disabled all chrome extensions and also tried incognito mode and it still doesn't work. I will try to put together a jsfiddle later. 

      if (_this.core.doCss() && _this.core.$items.length > 1 && ((_this.core.s.enableSwipe && _this.core.isTouch) || (_this.core.s.enableDrag && !_this.core.isTouch))) {
            _this.core.$el.on('onSlideClick.lg.tm', function() {
                var $el = _this.core.$slide.eq(_this.core.index);
                alert('calling loadOnClick');
                loadOnClick($el);
            });
        } else {  etc...

**Comment by lisaschiffli** [comment]
I think I've found the problem. Chrome is not correctly detecting touch screen devices under Windows 10. There is a flag in Chrome under chrome://flags for Enable Touch Events. By default it is set to "Automatic." There are also "Disabled" and "Enabled" options. I have a standard laptop with no touch screen; however, Chrome reports touchscreen is True. The _this.core.isTouch variable reports True in lg. If I change the flag in Chrome to "disable", the LightGallery Demo and my website both work fine. The "show-stopping" problem is that I can't require all my page visitors to set their Chrome flag to make my site work. 

Additionally, I have another Win10 laptop running Chrome that does have touch capability along with mouse usage. The lg YouTube Demo will only work by touching. The mouse does not work to click on the Play button on the video poster. On a device with both touch and mouse, either should work.

I also tested Chrome on a touch only smartphone (LG V10) and the lg Demo almost works. The video loads when you tap the play button on the poster, but the video doesn't start to play. You have to tap another play button that displays when the YouTube video is loaded. 

Specifically, in the code, when lg thinks touch is True, the mouse events don't seem to be triggering. Alerts placed in any of the $(window).on('mouse...') events don't fire when the mouse is clicked. For example, somewhere around line 1135 in lightgallery.js..
```
            $(window).on('mouseup.lg', function(e) {
                if (isMoved) {
                    isMoved = false;
                    _this.touchEnd(endCoords - startCoords);
                    _this.$el.trigger('onDragend.lg');
                } else if ($(e.target).hasClass('lg-object') || $(e.target).hasClass('lg-video-play')) {
                    alert('trigger onSlideClick.lg');
                    _this.$el.trigger('onSlideClick.lg');
                }
```
Unfortunately, I'm not sure how you resolve this. Way beyond my current jQuery and web skills. Somehow lg needs accurate info about the device capabilities: mouse, touch or both and that depends on line 100 in lightgallery.js 
```
        // To determine browser supports for touch events;
        this.isTouch = ('ontouchstart' in document.documentElement);

```

**Comment by smerriman** [comment]
This thread is over a year old, and there are various other similar ones - no mouse events work at all when the browser detects touch support. Is there ever going to be a solution to this?

**Comment by sachinchoolur** [comment]
Hey Guys,
The issue has been fixed. Please use the latest version(1.6.0) of lightGallery and its modules.
