### ISSUE TITLE
youtube video keep playing even after swipping and playing another video

### ISSUE THREAD

**Issue by javedansari2** [sachinchoolur/lightGallery#332]
hi sachin thanks for the script
Pls help me to know way out for youtube video keep playing even after swipping and keeps playing even when we click on another video so we have 2 video playing at a time
but this doesnot happen in vimeo

pls help 

thanks

**Comment by sachinchoolur** [comment]
Hi,
Is the demo site working fine for you? http://sachinchoolur.github.io/lightGallery/demos/videos.html

**Comment by abidhussainsafi** [comment]
Hi .. i cant figure out the thumbnail like in the demo for my site can you please guide ..

**Comment by abidhussainsafi** [comment]
<h1>Videos</h1>
				  <div class="demo-gallery">
					  <div id="video-gallery">
					  <a href="https://www.youtube.com/watch?v=meBbDqAXago" data-poster="http://sachinchoolur.github.io/lightGallery/static/img/videos/v-video2-cover.jpg">
					      <img src="http://sachinchoolur.github.io/lightGallery/static/img/thumb-v-v-2.jpg">
					  </a>
					  <a href="https://www.youtube.com/watch?v=meBbDqAXago" data-poster="http://sachinchoolur.github.io/lightGallery/static/img/videos/v-video2-cover.jpg">
					      <img src="http://sachinchoolur.github.io/lightGallery/static/img/thumb-v-v-2.jpg">
					  </a>
					  <a href="https://www.youtube.com/watch?v=meBbDqAXago" data-poster="http://sachinchoolur.github.io/lightGallery/static/img/videos/v-video2-cover.jpg">
					      <img src="http://sachinchoolur.github.io/lightGallery/static/img/thumb-v-v-2.jpg">
					  </a>
					  <a href="https://www.youtube.com/watch?v=meBbDqAXago" data-poster="http://sachinchoolur.github.io/lightGallery/static/img/videos/v-video2-cover.jpg">
					      <img src="http://sachinchoolur.github.io/lightGallery/static/img/thumb-v-v-2.jpg">
					  </a>
					  <a href="https://www.youtube.com/watch?v=meBbDqAXago" data-poster="http://sachinchoolur.github.io/lightGallery/static/img/videos/v-video2-cover.jpg">
					      <img src="http://sachinchoolur.github.io/lightGallery/static/img/thumb-v-v-2.jpg">
					  </a>
					  <a href="https://www.youtube.com/watch?v=meBbDqAXago" data-poster="http://sachinchoolur.github.io/lightGallery/static/img/videos/v-video2-cover.jpg">
					      <img src="http://sachinchoolur.github.io/lightGallery/static/img/thumb-v-v-2.jpg">
					  </a>
					</div>
				  </div>

**Comment by abidhussainsafi** [comment]
this is my code ... i want to display it like in the demo ...

$('#video-gallery').lightGallery({
			loadYoutubeThumbnail: true,
		    youtubeThumbSize: 'default',
		    loadVimeoThumbnail: true,
		    vimeoThumbSize: 'thumbnail_medium',
		    
		    vimeoPlayerParams: {
		        byline : 0,
		        portrait : 0,
		        color : 'A90707'     
		    }
		}); 


This is my js code ..

**Comment by sachinchoolur** [comment]
Related to https://github.com/sachinchoolur/lightGallery/issues/535
