### ISSUE TITLE
Docs: AngularJS Demo page 404

### ISSUE THREAD

**Issue by dmlb** [sachinchoolur/lightGallery#337]
http://sachinchoolur.github.io/lightGallery/demos/angularjs.html
![screen shot 2016-04-14 at 9 37 26 am](https://cloud.githubusercontent.com/assets/4835191/14529894/9168a6c4-0224-11e6-9c30-13161aa2606b.png)

**Comment by guney** [comment]
Check out issue #169. You can find an explanation about the AngularJS demo page absence there.
