### ISSUE TITLE
youtube reg exp bug

### ISSUE THREAD

**Issue by BdanB** [sachinchoolur/lightGallery#339]
Hey guys. Recently on our project we faced with a bug that video preview from youtube is broken using your plugin. So after some debugging I investigated that it match wrong video ID in it's isVideo function. Source is https://www.youtube.com/watch?v=ImZ_fqHD63A&feature=youtu.be and after matching var youtube = {0:"//www.youtube.com/watch?v=ImZ",1:"ImZ"}. Should be ImZ_fqHD63A.

![screenshot 2016-04-20 15 44 29](https://cloud.githubusercontent.com/assets/1324744/14674900/e47a4bc6-070e-11e6-8aec-646e1d70eac4.png)

**Comment by nebrot** [comment]
See #183, bug should be fixed. Use latest version or min. 1.2.4.

**Comment by BdanB** [comment]
@nebrot oh, sorry, I missed to check the latest version. Seems it works fine with 1.2.18, Thank you!
