### ISSUE TITLE
How to select multiple li images

### ISSUE THREAD

**Issue by conaris** [sachinchoolur/lightGallery#343]
Hi,

I have created this "markup" for a gallery i am making:

```
<script type="text/javascript">
                            $(document).ready(function() {
                                $(".showcase ul li").lightGallery(); 
                     });</script>
                    <div class="showcase">
                        <ul>
                        <li><a href="img/1.jpg"><img src="img/1.jpg"><p>Home</p></a></li>
                        <li><a href="img/2.jpg"><img src="img/2.jpg"></a></li>
                        <li><a href="img/9.jpg"><img src="img/9.jpg"></a></li>
                        <li><a href="img/6.jpg"><img src="img/6.jpg"></a></li>
                        <li><a href="img/3.jpg"><img src="img/3.jpg"></a></li>
                        <li><a href="img/4.jpg"><img src="img/4.jpg"></a></li>
                        <li><a href="img/5.jpg"><img src="img/5.jpg"></a></li>
                        <li><a href="img/8.jpg"><img src="img/8.jpg"></a></li>
                        </ul>
                    </div>
```

The problem with this code is when i click in any image i get 1/1 on top left of the screen so each image is treated as an individual gallery, how can i combine all the li's images in on one gallery without changing my mark up?

I used to have the same mark up without ul and li and all behave correctly but i need to include ul and li now but i can't figure this one

Thank you

![screenshot_2](https://cloud.githubusercontent.com/assets/11213118/14762688/a1125f2c-0989-11e6-897c-8495a2aea314.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/11213118/14762689/ab141f1a-0989-11e6-81e9-f75f9ae0a6a7.png)

**Comment by nebrot** [comment]
Did you try this?

`$(".showcase ul").lightGallery({selector: "a"}); `

**Comment by conaris** [comment]
no i haven't , it works, thanks for the help @nebrot
