### ISSUE TITLE
remove thumbnails

### ISSUE THREAD

**Issue by b2bstudio** [sachinchoolur/lightGallery#344]
Hi Sachin

How do I turn off thumbnails, is there a line of jQuery I can add to do this?

also does lightgallery-all.js contain all the JavaScript in one file as the name suggests?

Thanks
Andy

**Comment by sachinchoolur** [comment]
Hey @b2bstudio ,
Yes, it is possible. You just need to pass `thumbnail: false` via settings 
```js
$('lightgallery').lightGallery({
    thumbnail: false
});
```
