### ISSUE TITLE
Can I use it for jwplayer?

### ISSUE THREAD

**Issue by DickyCSharp** [sachinchoolur/lightGallery#346]
The "Youtube, Vimeo Video Gallery" plugin is pretty nice. Can I make it play on the jwplayer after clicking the thumbnails? Thank you.

ps: I don't know if I can ask this question here because this is the first time I use github.

**Comment by janrembold** [comment]
Good question, I have the same question. 

@wong1999kit did you implement JW Player in the meantime?
