### ISSUE TITLE
Play button in Safari - preload?

### ISSUE THREAD

**Issue by stellios12345** [sachinchoolur/lightGallery#347]
So it works perfectly in Chrome and IE11, or in Safari.
The play button on the image does not initiate the video in Safari, you have to then press the play button on the player. If you add videojs, the video in Safari hangs.

I experimented a bit and there seems to be some link to the preload function but I haven't managed to make this work across all browsers yet. If you leave the preload function undefined then it works fine in Safari but then Chrome hangs. Any ideas?

**Comment by haripulaparthi** [comment]
Hi Team,

I also facing the same problem. 

The play button on the image does not initiate the video in Safari, you have to then press the play button on the player. 

Please let me know how can we over this problem.

Thanks in advance.

**Comment by dorukgunes** [comment]
Any updates ?

**Comment by sachinchoolur** [comment]
Hi Guys,
As per my understanding autoplay cannot be done on iOS devices. User has to manually click on the video

**Comment by sachinchoolur** [comment]
More links : 

- http://stackoverflow.com/questions/15090782/youtube-autoplay-not-working-on-mobile-devices-with-embedded-html5-player
- http://stackoverflow.com/questions/8141652/youtube-embedded-video-autoplay-feature-not-working-in-iphone
- http://stackoverflow.com/questions/3009888/autoplay-audio-files-on-an-ipad-with-html5

Closing the issue as it is not possible to resolve. Please feel free to re-open if you guys think it is possible.
