### ISSUE TITLE
The history back button not working

### ISSUE THREAD

**Issue by szymekz** [sachinchoolur/lightGallery#352]
When you open a gallery, click few photos forward, close the gallery, and try to go to the previus page - u cant, the gallery adds some hash and nothing is happening. Try it here:

http://sachinchoolur.github.io/lightGallery/demos/hash.html

Open image > click 'next 3 times > close gallery > try to go to the previus page with chrome default back button.

**Comment by Ansif** [comment]
This is because of hash URL. You can deactivate that by : 

`jQuery(document).ready(function($) {
      $("#lightgallery").lightGallery({
      	hash: false,
      });
});`

👍

**Comment by gauravmak** [comment]
Is it possible to keep hash but not to keep history of image views? As in my case, hash is compulsory as I am using comment box feature but I don't want to open image viewer again once I click on close button and press back in the browser.

**Comment by sachinchoolur** [comment]
Related to https://github.com/sachinchoolur/lightGallery/issues/547
