### ISSUE TITLE
Toolbar becoming visible when on fullscreen

### ISSUE THREAD

**Issue by Tashows** [sachinchoolur/lightGallery#356]
I realised that when on fullscreen mode the toolbar dissapears normally, but then reappears once you move two images either direction. Is this behavior expected? In my honest opinion it would make more sense for the toolbar to not come into view again, unless you move the mouse. I find it kind of distracting if you just want to enjoy the images. I also think the toolbar should go away when on slideshow mode and come back up when the user exits fullscreen (esc) or moves the mouse.

Not a major issue, but a setting to toggle that kind of behavior would be useful. Great work by the way!

**Comment by jmbelloteau** [comment]
bump ! totally agree and didn't found a solution yet :( !

**Comment by Tashows** [comment]
Just realised something. I have two displays in my pc. If I move the mouse outside the browser area (since it's fullscreen, that means put the mouse to the second display), then the toolbar never reappears. It's like after moving two images left or right, it re-tracks if the mouse cursor is over the photo and activates the toolbar.
