### ISSUE TITLE
Safari on IPad keeps crashing when gallery opened

### ISSUE THREAD

**Issue by ChrisLNOF** [sachinchoolur/lightGallery#36]
Hi,

The gallery is pretty cool and easy to use. I have an issue though when trying to use it in Safari on an iPad. Every time I open the gallery the gallery pops up for a second then the browser closes completely.

What have I missed?

...a bit more information here: 

I have multiple galleries showing using relations to match them, so:

```
    $('#rel1').lightGallery({rel:true});
    $('#rel2').lightGallery({rel:true});
    $('#rel3').lightGallery({rel:true});        
    $('#rel4').lightGallery({rel:true});
     ....ect
```

then the galleries as follows:

 < ul id="rel1" data-rel="imageGallery1">< li .......etc
 < ul id="rel2" data-rel="imageGallery1">< li........etc 

  < ul id="rel3" data-rel="imageGallery2"><li .......etc
  < ul id="rel4" data-rel="imageGallery2"><li........etc 

  and so on...... this works fine on desktops and iPhone so I assume the code is ok.

Thanks,
Chris

**Comment by richoid** [comment]
I'm having the same problem. http://leeannbrookfineart.com/recent-work-2/environments/

**Comment by q2apro** [comment]
Sounds like a memory issue with the ipad.
