### ISSUE TITLE
Support for 2 fingers pinch to zoom

### ISSUE THREAD

**Issue by kachurun** [sachinchoolur/lightGallery#363]
I forked it for our project, but the core functionality is support for two-fingers image scale. 
I did it, if you're interested, look here
https://github.com/kachurun/lightGallery

The code is full of Russian comments, because it is made for internal use.
I`m sorry about that.

**Comment by fabianmarz** [comment]
@kachurun - Could you please provide a PR? Also please comment your source code in english. So everybody is able to understand :)

**Comment by sachinchoolur** [comment]
Hey guys,

I've already implemented pinch to zoom option and will be released in version 2.0
Thank you for your support.

Related to https://github.com/sachinchoolur/lightGallery/issues/211

**Comment by craigmatthew412** [comment]
@sachinchoolur Any idea of a rough ETA when V2.0 will be released?

**Comment by mariomurrent-softwaresolutions** [comment]
> I forked it for our project, but the core functionality is support for two-fingers image scale.
> I did it, if you're interested, look here
> https://github.com/kachurun/lightGallery
> 
> The code is full of Russian comments, because it is made for internal use.
> I`m sorry about that.

Can you please provide a statement what exactly did you change? :)
