### ISSUE TITLE
Font awesome icons

### ISSUE THREAD

**Issue by Studioartcz** [sachinchoolur/lightGallery#364]
Hi,

how can i change font, icons to font awesome?

thanks

**Comment by Izopi4a** [comment]
+1

**Comment by abnersajr** [comment]
if you look `.css` files you will see the `font-family 'lg'` used and some classes like font-awesome. Search this and change by **Font Awesome** font and replace the _pseudo-selectors_ content which you want.

**Comment by PhilJ88** [comment]
Here u go
[lightgallery.zip](https://github.com/sachinchoolur/lightGallery/files/405135/lightgallery.zip)

**Comment by Studioartcz** [comment]
It's bad solution if i use this as lib via bower.

**Comment by PhilJ88** [comment]
well, here it is again for those not hung up
[lightgallery.zip](https://github.com/sachinchoolur/lightGallery/files/405350/lightgallery.zip)
