### ISSUE TITLE
Vertical captions and hide/show button

### ISSUE THREAD

**Issue by lmanzurv** [sachinchoolur/lightGallery#371]
Hi, is there any way we can have a way of configuring the plugin to have the captions positioned on the right/left vertically (like the image)?

![screen shot 2016-06-09 at 21 18 57](https://cloud.githubusercontent.com/assets/3003634/15952587/d8744494-2e87-11e6-8d7c-1793b0ca73f2.png)

Another thing, is there any way to have a button on the toolbar that allows to hide/show the captions?

Regards!

**Comment by vincent3569** [comment]
Hi
Tkanks for this powerfull light gallery script !!

I add a suggestion on this issue:
Actualy controls can be hidden by the option `hideBarsDelay`
It would be a nice improvement to add a option to allow hide caption after a delay: caption is shown when a new image is shown, and is hidden after a delay and then caption is shown agin on the next/previous picture.

**Comment by dcalise** [comment]
@vincent3569 you can do this with a simple css change:
```
// for idle state
.lg-toolbar, .lg-prev, .lg-next, .lg-sub-html {
  opacity: 1;
  @include transitionCustom(transform 0.35s cubic-bezier(0, 0, 0.25, 1) 0s, opacity 0.35s cubic-bezier(0, 0, 0.25, 1) 0s, color 0.2s linear);
}

.lg-hide-items {
  .lg-prev {
    opacity: 0;
    @include translate3d(-10px, 0, 0);
  }

  .lg-next {
    opacity: 0;
    @include translate3d(10px, 0, 0);
  }

  .lg-toolbar {
    opacity: 0;
    @include translate3d(0, -10px, 0);
  }

  .lg-sub-html {
    opacity: 0;
    @include translate3d(0, 10px, 0);
  }
}
```

in _lg-theme-default.scss, add `.lg-sub-html` to the existing styles for .`lg-hide-items`
