### ISSUE TITLE
backdropDuration

### ISSUE THREAD

**Issue by developer-lindner** [sachinchoolur/lightGallery#373]
The following should be changed:

line 345 (lightgallery.js)
`$('.lg-backdrop').addClass('in');
        setTimeout(function() {
            _this.$outer.addClass('lg-visible');
        }, this.s.backdropDuration);`

to:

`setTimeout(function() {
            _this.$outer.addClass('lg-visible');
            $('.lg-backdrop').addClass('in');
        }, this.s.backdropDuration);
`

I tried to change the smoothness of the gallery opening & closing and encountered that it just works for the closing. After changing the lines of code it works for both ways as expected!

Works now nicely if someone wants to transition between 
`$backdrop-color: rgba(0, 0, 0, 0.0)`
and 
`$backdrop-color-in: rgba(0, 0, 0, 0.8)`

inside of the .in class in scss for example...

Thanks for this awesome plugin!

**Comment by sachinchoolur** [comment]
Hey @developer-lindner,
Thank you for pointing this out. The issue has been fixed.
