### ISSUE TITLE
z-index on controls

### ISSUE THREAD

**Issue by FDiskas** [sachinchoolur/lightGallery#377]
There is z-index on controls.

```
.lSAction>a
```

Its to big. Please update this to something like **1**

**Comment by chrispcb** [comment]
Please add z-index option to choose any value.
For exemple, there is a issue with boostrap modal (z-index: 1050). LightGallery overlay is under bootsrap modal.

**Comment by sachinchoolur** [comment]
You can change `z-index` value of controls by changing the scss variables 
http://sachinchoolur.github.io/lightGallery/docs/api.html#sass
