### ISSUE TITLE
Single click/tap to hide data-sub-html

### ISSUE THREAD

**Issue by ghost** [sachinchoolur/lightGallery#378]
I am suggesting an option to hide/show data-sub-html on click or tapping the current active image. I thought it be might easy to code since JQuery.dblclick() event is used in zoom plugin to see the actual size of the image. While JQuery.click() event is not used why we dont`t reserve such feature for.

I am not JS geek so I won`t give a hand in that. SORRY :(

**Comment by RonaldPK** [comment]
You could use the `onSlideClick` event.

```
$lg = $(strSelector);
$lg.lightGallery(oOptions);
$lg.on('onSlideClick.lg', doToggle);

function doToggle(e) {
	$('.lg-outer').toggleClass('lg-hide-items');
	var curVal = $('.lg-sub-html').css('visibility');
	$('.lg-sub-html').css('visibility', curVal == 'hidden' ? 'visible' : 'hidden');
}
```
(Untested code...)

**Comment by skakraze5** [comment]
I was interested in similar functionality, but found the code above had some odd-ness w/ clicking around while using the zoom plugin. So I decided to add that same toggle feature as a toolbar item. If I was more familiar with making plugins, I would have gone that route. But the code below seems to do the trick. 

```
$lg = $(strSelector);
$lg.lightGallery(oOptions);
$lg.on('onAfterOpen.lg',function(event){
   $('.lg-toolbar').append('<a class=\"lg-icon\" href=\"javascript:toggleCaption()\">CC</a>');
});

function toggleCaption() {
   var curVal = $('.lg-sub-html').css('visibility');
   $('.lg-sub-html').css('visibility', curVal == 'hidden' ? 'visible' : 'hidden');
}

```

I'd be up for suggestions on how to make this type of feature better/cleaner.

**Comment by AndresSanzG** [comment]
> You could use the `onSlideClick` event.
> 
> ```
> $lg = $(strSelector);
> $lg.lightGallery(oOptions);
> $lg.on('onSlideClick.lg', doToggle);
> 
> function doToggle(e) {
>     $('.lg-outer').toggleClass('lg-hide-items');
>     var curVal = $('.lg-sub-html').css('visibility');
>     $('.lg-sub-html').css('visibility', curVal == 'hidden' ? 'visible' : 'hidden');
> }
> ```
> 
> (Untested code...)

I tested it, and it works! 💃

**Comment by AndresSanzG** [comment]
And I tested the second solution you give us. But I made some changes to improved it. 
I will use blah where you can put the name you need.

HTML:

           <div class="blah-info" style="display: none">
                    <h4>Whatever</h4>
                    <p>Bla bla blah</p>
             </div>

             <div id="blah1" class="blah-info-added" style="display:none">
                        <h4 class="ns">Title Blah 1</h4>
            </div>

             <div id="blah2" class="blah-info-added" style="display:none">
                        <h4 class="ns">Title blah 2</h4>
                        <p class="ns">Blah blah blah 2</p>
            </div> 

            <div id="blah3" class="blah-info-added" style="display:none">
                        <h4 class="ns">Title blah 3</h4>
                        <p class="ns">Blah blah blah 3</p>
            </div>


            <div id="blah" class="figure">
                      <a href="../img/01.jpg" data-sub-html="#blah1">
                                <img src="../img/01-thumb.jpg" />
                                <div class="title-hover">
                                    <h3>Propuesta WPT 2014</h3>
                                </div>
                      </a>
                       <a href="../img/02.jpg" style="display: none" data-sub-html="#blah2">
                                <img src="../img/02-thumb.jpg" />
                      </a>
                      <a href="../img/03.jpg" style="display: none" data-sub-html="#blah3">
                                <img src="../img/03-thumb.jpg" />
                      </a>
             </div>

<-- JS - JQUERY-->

$lg = $('#blah');
$lg.lightGallery();
$lg.on('onAfterOpen.lg',function(event){
   $('.lg-toolbar').append('<a class=\"lg-icon\" href=\"javascript:toggleCaption()\">&#9432</a>');
    insertCaption();
});

//Insert the info I want to change for all text
function insertCaption(){ $('.blah-info-added').append($('.blah-info')); }

//Change one for other
function toggleCaption() {
    var curVal = $('.ns').css('display');
    $('.ns').css('display', curVal == 'none' ? 'block' : 'none');

    var lgVal = $('.blah-info').css('display');
   $('.blah-info').css('display', lgVal == 'none' ? ' block' : 'none');   
}

I hope this will help you. 
P.D: This &#9432 is a ascii code that it's a info icon.
