### ISSUE TITLE
Print Image light gallery

### ISSUE THREAD

**Issue by faboc** [sachinchoolur/lightGallery#379]
i wanna print my image in lightgallery. 

May i print image in lightgallery ?

How to manage toolbar at top? 

i wanna insert icon print too.

Thx

**Comment by sachinchoolur** [comment]
Hi,
There is no default setting to add new icons to toolbar. But you can fork the repo and customize it for your requirement. 

Here is the demo for adding new icon to toolbar. 
``` javascript
if (this.s.download) {
    this.$outer.find('.lg-toolbar').append('<a id="lg-download" target="_blank" download class="lg-download lg-icon"></a>');
}
```
