### ISSUE TITLE
lightgallery.js:455 Uncaught TypeError: this.$items.eq is not a function

### ISSUE THREAD

**Issue by Omniferum** [sachinchoolur/lightGallery#381]
https://github.com/sachinchoolur/lightGallery/commit/e70d78cad305bbb66b11f3cdca881ed50ee33239

The above build provides this error:
lightgallery.js:455 Uncaught TypeError: this.$items.eq is not a function
Plugin.addHtml @ lightgallery.js:455
(anonymous function) @ lightgallery.js:787

**Comment by sachinchoolur** [comment]
Hi,
It works fine for me. Please use latest version and let me know if the issue persists..

**Comment by Omniferum** [comment]
Used: https://github.com/sachinchoolur/lightGallery/commit/514c34ba72e6e5ca8d5284b2b30e6dd0edf4604c

lightgallery.js:459 Uncaught TypeError: this.$items.eq is not a function
Plugin.addHtml @ lightgallery.js:459
(anonymous function) @ lightgallery.js:789

I haven't made any changes to my site code. Was a simple drop replace upgrade.

**Comment by Omniferum** [comment]
https://github.com/sachinchoolur/lightGallery/commit/b50434b47eeaa26bb2c3622715c083fdd7bea8fa fixes the problem.

**Comment by sachinchoolur** [comment]
Thank you for reporting this issue . 
Just release v1.2.21 with the fix.

**Comment by cph2** [comment]
Hi, 

I downloaded the latest and receive the same error. Was something perhaps inadvertently reverted?

Thanks,
Cheryl

**Comment by sachinchoolur** [comment]
Hey @cph2,
Could you please provide a jsfiddle demo which demonstrates the issue?

**Comment by dayomu** [comment]
@sachinchoolur I have the same issue. This is the demo pen: https://codepen.io/cheryomuhina/pen/veKrJx.

**Comment by sachinchoolur** [comment]
Hey @dayomu,
The issue is related to https://github.com/sachinchoolur/lightGallery/issues/581. At present share plugin doesn't work with dynamic mode. FOr current use, either you can disable the dynamic mode or the share plugin. It is a major issue and will be fixed in the next release
