### ISSUE TITLE
Auto play for YouTube/Vimeo videos does not work correctly

### ISSUE THREAD

**Issue by lmanzurv** [sachinchoolur/lightGallery#382]
When I add videos from YouTube or Vimeo, I set the autoplay param for each to 1 but it does not work, it only works for Vimeo. URLs set the param autoplay twice (one in 0 and one in 1), which works for Vimeo but not for YouTube.

My code is 

```
$('#lightbox-video-{{ instance.id }}').lightGallery({
    selector: '.lightbox-vid',
    zoom: false,
    fullScreen: false,
    vimeoPlayerParams: { autoplay: 1 },
    youtubePlayerParams: { autoplay: 1 }
});
```

Urls for the videos get rendered like this:
![screen shot 2016-06-28 at 10 18 57](https://cloud.githubusercontent.com/assets/3003634/16421204/ceafcbf4-3d19-11e6-9b79-504833d30d5a.png)
![screen shot 2016-06-28 at 10 20 16](https://cloud.githubusercontent.com/assets/3003634/16421240/eecc4624-3d19-11e6-99b3-10eb11d0ac5b.png)

**Comment by Leapfrognz** [comment]
Yes Im getting this also.
line 248 on lg-video.js:         var autoplay = 0;
It should respect whatever is sent through in the player params object. Perhaps the author had something else in mind here, such as passing autoplay outside of the player params object, but never finished it off?

**Comment by lmanzurv** [comment]
I had to do a workaround. Basically, on opening of a YouTube video, I replace the URL to remove the first autoplay. I don't do it for Vimeo because it doesn't affect the autoplay behaviour.

```
var $video = $('#lightbox-video-{{ instance.id }}');
...
$video.on('onAfterOpen.lg', function(event) {
    var $embedVideo = $('.lg-outer .lg-inner .lg-video-object');
    var url = $embedVideo.attr('src');
    if(url.indexOf('youtube') !== -1) {
        url = url.replace('autoplay=0&', '');
        $embedVideo.attr('src', url);
    }
});
```

**Comment by sachinchoolur** [comment]
I think autoplay should not be passed via player params. If you pass `{autoplay: 1}` via player params all the videos inside the gallery will start playing together. Maybe as @Leapfrognz suggested, we can add an option to control autoplay from settings. 
lightGallery automatically enables autoplay for the first video if the poster doesn't exist. but there is no option to control remaining videos autoplay.

**Comment by lfolco** [comment]
Is it possible to have it auto play when you advance to the next video?

**Comment by joomlabeat** [comment]
is this fixed?
