### ISSUE TITLE
TypeError: src is undefined at lightgallery.js (line 415, col 13)

### ISSUE THREAD

**Issue by aniket27** [sachinchoolur/lightGallery#384]
When I'm clicking on image it is showing total black page & in console i get this error

```
TypeError: src is undefined at lightgallery.js (line 415, col 13)
var youtube = src.match(/\/\/(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=|embed...
```

here is the html part

```
<div id="images">
`<a href="//cdn.example.com/post/image/<?php echo $userimg; ?>"> <img id="imgr" src="https://cdn.example.com/post/image/<?php echo $userimg; ?>"></a>`
</div>
```

The above html part is in php while loop it means id will get duplicated, is there a better way? & please solve the issue

**Comment by franata** [comment]
http://stackoverflow.com/questions/32338947/light-gallery-match-error

**Comment by sachinchoolur** [comment]
Hope the above answer fixes the issue.

Thank u @franata
