### ISSUE TITLE
Responsive vertical center buttons

### ISSUE THREAD

**Issue by svkmedia** [sachinchoolur/lightGallery#386]
Hi I suggest to change style of prev and next buttons so they are vertical centre also on small resolutions:

`.lg-actions .lg-next, .lg-actions .lg-prev {
    top: 0;
    bottom: 0;
    height: 61px;
    margin: auto;
}`

**Comment by sachinchoolur** [comment]
Hey @svkmedia ,
The current approach works fine on small resolutions as well. Please re-open the issue if it doesn't work for you.
