### ISSUE TITLE
Hashtag Icon Replication Bug

### ISSUE THREAD

**Issue by anteksiler** [sachinchoolur/lightGallery#387]
You can see the issue here:
http://twofold.fuelthemes.net/collection/collection-2/

Please open the first image, which will change the url. After that, refresh the page. Now the icons are replicated.

**Comment by a1studmuffin** [comment]
I'm facing a similar issue at the moment (site offline so can't provide a working demo). I believe I may have tracked down the issue though. In lightgallery.js v1.2.21 on line 159 the line `$('body').addClass('lg-on');` needs to be moved down a line so it's outside the `setTimeout` function. That way the check against 'lg-on' on line 171 works as expected. Fixed the issue for me anyway, hope that helps!

**Comment by inlikealion** [comment]
That fix works for me, too @a1studmuffin! thanks for sharing it.

**Comment by anteksiler** [comment]
@sachinchoolur Could you integrate this as a hot fix?

**Comment by abnersajr** [comment]
Offcourse I will make this hotfix guys ;)

**Comment by abnersajr** [comment]
Generating the build :+1:

**Comment by abnersajr** [comment]
@anteksiler could you update and test if it's working right now?

**Comment by anteksiler** [comment]
@abnersajr Yeap, it fixes the bug :)

**Comment by a1studmuffin** [comment]
Awesome, thanks guys! :D
