### ISSUE TITLE
How to dynamically open the gallery ?

### ISSUE THREAD

**Issue by br3ach3r** [sachinchoolur/lightGallery#388]
I'm trying to hide the all gallery pictures and just use another picture as the album cover and when you click on the the gallery should open up. And also i'm dynamically adding the images to the gallery as well. when i click on the album cover the gallery show up but the background is not black it's transparent.and then if i close the gallery and then again click on the album cover the gallery opens up fine with the black background.

here's a screenshot..

![capture](https://cloud.githubusercontent.com/assets/17039566/16619730/07664c9a-43ad-11e6-81d0-e8885c83c4ce.JPG)

**Comment by ALTELMA** [comment]
How did you do about this?
I will find solution to open gallery from other button.

**Comment by sachinchoolur** [comment]
Hey @br3ach3r ,
Sorry for the delayed response. It seems like the issue with your code. Since it is an old ticket, I hope you must have found the solution. Please re-open if the issue persists
