### ISSUE TITLE
onCloseAfter why fires once?

### ISSUE THREAD

**Issue by rorc** [sachinchoolur/lightGallery#389]
I am add right panel to `<body>` with `onAfterOpen.lg` and i need destroy it all time with `onCloseAfter.lg`.
Therefore if i open gallery in second time, i cant destroy my panel...

As lightGallery do not hide body scroll, i want to hide all time body scroll with  `onAfterOpen.lg` through `body { overflow: hidden }` and restore it with `onCloseAfter.lg`...

**Comment by sachinchoolur** [comment]
Hey @rorc ,
It works fine for me.  Demo- http://codepen.io/anon/pen/qryYoJ
Please re-open if the issue persists
