### ISSUE TITLE
How load thumbnail youtube ?

### ISSUE THREAD

**Issue by Enzo-bianchi** [sachinchoolur/lightGallery#394]
Hi, 

I have a little issue, i try to enable generation of thumbnail from video like youtube
i loaded this on my page

```
<script src="{{ asset('/js/lightgallery-all.min.js') }}"></script>
<script src="{{ asset('/js/lg-thumbnail.min.js') }}"></script>
<script type="text/javascript">
$(document).ready(function() {
      $("#lightgallery").lightGallery({
            thumbnail:true,
            loadYoutubeThumbnail: true,
            youtubeThumbSize: 'default',

      }); 
});
</script>
```

But on the documentation i didn't read something about how we integrate the video 
We need a `img` element ? because only the `a` not working
Thanks :)

**Comment by mhrnik** [comment]
Here, I did work around of it.
Markup:
 <a href="[youtube-video-url]">                                                                 
      <img src="http://img.youtube.com/vi/" +[youtube-videoi-id] + "/default.jpg")">
  </a>

for youtube-video-id, you can get it from url like:
 (youtube-video-url).split('v=')[1]

**Comment by sachinchoolur** [comment]
Hi @Enzo-bianchi,
lightGallery loads thumbnails only inside the gallery. If you want to load youtube thumbnails outside the gallery, you can follow @mhrnik's approach
