### ISSUE TITLE
Hiding or disallowing the fullscreen in youtube

### ISSUE THREAD

**Issue by advantageweb** [sachinchoolur/lightGallery#396]
I went through all of the JS files and I could not figure out how to disable fullscreen in the plugin. Please help! Great plugin btw!

**Comment by SANTOSHKVNSP** [comment]
Hi @abnersajr  ,
Can I work and fix this enhancement ?

**Comment by sachinchoolur** [comment]
Hi Guys,
This option is already available. you just need to pass `fs:0` in `youtubePlayerParams` setting

``` javascript
$('#lightgallery').lightGallery({
    youtubePlayerParams: {
      fs: 0
    }
});
```

Demo: http://codepen.io/anon/pen/MJGMQd
YouTube API: https://developers.google.com/youtube/player_parameters
Docs: http://sachinchoolur.github.io/lightGallery/docs/api.html#lg-video

BTW: @SANTOSHKVNSP shoot me an email @ sachi77n@gmail.com if you'd like to contribute
