### ISSUE TITLE
Opacity requires Sass

### ISSUE THREAD

**Issue by paul-hansen** [sachinchoolur/lightGallery#397]
Our project doesn't use Sass. It would be nice if we could specify the background opacity as an option passed to lightGallery(). I know I can just add css:

```
.lg-backdrop{
    opacity:0.8 !important;
}
```

Everywhere we use it, but it isn't quite as elegant as just passing it as a parameter. And something about having to use !important just rubs me wrong.

I know it's a small thing and kinda nit-picky but it shouldn't be too much effort and it would be appreciated.

**Comment by abnersajr** [comment]
If your comment get 20 thumbs up I implement this.

**Comment by sachinchoolur** [comment]
Hey @paul-hansen ,

Since it is very easy to achieve via CSS, I'd like to keep it as it is.
But, if we get more requests to add a setting for backdrop opacity, I'll consider adding it in the future.
