### ISSUE TITLE
cannot download slide image under Android

### ISSUE THREAD

**Issue by pumbac** [sachinchoolur/lightGallery#398]
after coparing so many gallery plugins , I found lightGallery the most feasible solution for our product.

recently, I found that the download icon cannot work with mobile phones. 

and with ios, i can just taphold the slide image and safari will detect the image and pop up the 'save' menu.

but there is no reaction under Android with the same operation.

how to solve this?

**Comment by davidrope** [comment]
We have the same problem, did you solve it?

**Comment by sachinchoolur** [comment]
By default, download URL will be taken from data-src/href attribute but it supports only for modern browsers. If you want cross-browser compatibility, you can provide your own download-url via data-download-url. 
Browser-support: http://caniuse.com/#feat=download
Docs: http://sachinchoolur.github.io/lightGallery/docs/api.html
