### ISSUE TITLE
Uncaught TypeError: Cannot read property 'modules' of undefined

### ISSUE THREAD

**Issue by KomalDivate** [sachinchoolur/lightGallery#399]
Error at line number 449
$.fn.lightGallery.modules.Thumbnail = Thumbnail;

in lg-thumbnail

**Comment by CrashyBang** [comment]
Hey @KomalDivate what was the issue?

**Comment by sachinchoolur** [comment]
@CrashyBang,
Make sure that you have included lightgallery.js before lg-thumbnails.js

**Comment by subooom** [comment]
![image](https://user-images.githubusercontent.com/18305059/67182163-48322780-f3fe-11e9-8a0f-1237618b1e27.png)
I have done that but it's still throwing the error. Please Help. The lightgallery is working but the pulgins do not show up.
![image](https://user-images.githubusercontent.com/18305059/67182197-58e29d80-f3fe-11e9-82d2-1353af688331.png)

**Comment by subooom** [comment]
Okay, I managed to solve the problem when i used everything from inside `lightgallery.js/demo/js/` folder, instead of downloading the plugins manually.
