### ISSUE TITLE
Adding width and height depending on browser

### ISSUE THREAD

**Issue by semaf** [sachinchoolur/lightGallery#400]
Is there a way to add width and height as it is preferred for SEO?

**Comment by sachinchoolur** [comment]
Demo: http://sachinchoolur.github.io/lightGallery/demos/fixed-size.html

**Comment by semaf** [comment]
Meant to the <img> tag by javascript. Not inside the javascript

**Comment by sachinchoolur** [comment]
Hey @semaf ,
I'm sorry, At present, this is not possible.
