### ISSUE TITLE
Method "onSlideClick.lg" does not trigger when only 1 image in gallery

### ISSUE THREAD

**Issue by julie10** [sachinchoolur/lightGallery#401]
Hello,

I am not sure if this a bug or a normal feature, but the "onSlideClick" method does not trigger itself when you click a slide that is alone in a gallery. 

https://jsfiddle.net/julie404/30yLdoje/1/
I apologize since it is my first jsFiddle, it may be not very well done (also, English is not my first language!).

If this is not a bug, I didn't find a way to detect click on a single image gallery neither.

**Comment by sachinchoolur** [comment]
Hey @julie10,
The issue has been fixed. Please use the latest version of lightGallery
