### ISSUE TITLE
Facing a problem when ajax response is recieved lightgallery does not works

### ISSUE THREAD

**Issue by proud2myindia** [sachinchoolur/lightGallery#405]
@sachinchoolur 
Below is my javascript call ajax
function show_image(ph_id,al_id)
{

    var xmlhttp=new XMLHttpRequest();
    xmlhttp.onreadystatechange=function() {
        if (xmlhttp.readyState==4 && xmlhttp.status==200) {
			//alert(xmlhttp.responseText);
			
            document.getElementById("show_img").innerHTML=xmlhttp.responseText;
        }
    }
    xmlhttp.open("GET","../show_images?ph_id="+ph_id+"&al_id="+al_id,true);
    xmlhttp.send();
}

<div id="lightgallery">
                       
						<div class="col-md-12 img-sh" data-responsive="images/1-375.jpg 375, images/1-480.jpg 480, images/1.jpg 800" data-src="../gallery_image/<?php echo $row_like['gallery_image']; ?>" data-sub-html="<h4>Fading Light</h4><p>Classic view from Rigwood Jetty on Coniston Water an old archive shot similar to an old post but a little later on.</p>">
						<img src="../gallery_image/<?php echo $row_like['gallery_image']; ?>" class="img-responsive" alt="" style="height:100%">
						</div>

before ajax calling lightbox works fine but after getting response text lightbox does not open 

Please help I am getting frustrated

**Comment by RichieMcMullen** [comment]
Same issue here.

**Comment by proud2myindia** [comment]
I got solution  Richie
you just call the lightbox function again in your ajax after displaying your ajax response...it will works

**Comment by sachinchoolur** [comment]
Hi Guys,
You have to destroy the gallery before re-initiating it.
Demo : http://sachinchoolur.github.io/lightGallery/demos/methods.html
