### ISSUE TITLE
Unable to get the thumbnail behavior as described in the demos

### ISSUE THREAD

**Issue by marmistrz** [sachinchoolur/lightGallery#408]
I created a small gallery

```
                <div class="gallery">
                    <a href="gallery/010.jpg"><img src="gallery/thumb/010.jpg"/></a>
                    <a href="gallery/020.jpg"><img src="gallery/thumb/020.jpg"/></a>
                    <a href="gallery/030.jpg"><img src="gallery/thumb/030.jpg"/></a>
                    <a href="gallery/040.jpg"><img src="gallery/thumb/040.jpg"/></a>
                    <a href="gallery/050.jpg"><img src="gallery/thumb/050.jpg"/></a>
                    <a href="gallery/060.jpg"><img src="gallery/thumb/060.jpg"/></a>
                    <a href="gallery/070.jpg"><img src="gallery/thumb/070.jpg"/></a>
                    <a href="gallery/080.jpg"><img src="gallery/thumb/080.jpg"/></a>
                    <a href="gallery/090.jpg"><img src="gallery/thumb/090.jpg"/></a>
                    <a href="gallery/100.jpg"><img src="gallery/thumb/100.jpg"/></a>
                </div>
```

Initialized it with jQuery:

```
(function($) {
    $(function() {
        var $gallery = $('.gallery');
        $gallery.lightGallery({
            download: false,
            thumbnail: true
        });
    });
})(jQuery);
```

Unfortunately, nothing happens on hover (in the demo: a zoom effect and a zoom icon), as presented in the demo.

**Comment by marmistrz** [comment]
I thought about the wrong thumbnails. I thought about the thumbnails in the `div` and `lg-thumbnail.js` is all about the thumbnails in the viewer.

Please state clearly, that the thumbnails outside the viewers are not created with lightGallery but with Justified Gallery.

**Comment by tylerecouture** [comment]
Dang, I was trying to figure out how to get this pre-thumbnail gallery behavior also.  Did you figure it out?  I'm also using lightGallery, but can't figure it out beyond the automatic caption.

**Comment by sachinchoolur** [comment]
justifiedGallery is used to create the thumbnails on lightGallery demo page  - http://miromannino.github.io/Justified-Gallery/

**Comment by andrea-de** [comment]
this doesn't make any sense. the lightGalley demo page is not using lightGallery?
