### ISSUE TITLE
HTML5 Video Implementation broken

### ISSUE THREAD

**Issue by Eneuman** [sachinchoolur/lightGallery#411]
Hi!
First I want to say thank's for a great JS module.
Unfortunately I have found that the current HMTL5 Video implementation is not going to work because of som Microsoft BS.

IE11 and Edge does not honor the preload video tag and instead download the entire video (in the background, without showing it to the user), and MS has said that they are not going to change this behavior.

This means that if you add some html5 video tags to your page, all those video files are going to get downloaded (in full) to the user in the background even if he/she does not want to look at them.

I think the HTML5 implementation needs to change so that a video tag is created dynamically, when the user want to play the file, and only a thumbnail picture is shown.

**Comment by sachinchoolur** [comment]
Hey @Eneuman ,

Thank you for the information. This issue will be addressed when I fix https://github.com/sachinchoolur/lightGallery/issues/496
