### ISSUE TITLE
 Justified Gallery breaks lightGallery (or vice versa)

### ISSUE THREAD

**Issue by marmistrz** [sachinchoolur/lightGallery#412]
Cross-reporting: https://github.com/miromannino/Justified-Gallery/issues/186

**Comment by sachinchoolur** [comment]
Try to initialize lightGallery on justifiedGallery `jg.complete` event. That is how it works onlightGallery demo page 

``` js
        var $lg= $('#lightgallery');
        $lg.justifiedGallery().on('jg.complete', function() {
            $lg.lightGallery();
        });

```
