### ISSUE TITLE
Please need help with files and buttons on image gallery

### ISSUE THREAD

**Issue by adpatel111** [sachinchoolur/lightGallery#413]
Please help. I love this plugin for an image gallery but I am having issues with the gallery. 
1) When i open the gallery the  exit button/next and prev arrows are not there.
2)  Some of images overlap each other when I switch images in the gallery. 
3) I am getting Get: File not found for the loading.gif, fonts/lg.woff?n1z373 and fonts/lg-ttfn1z373.  I see those files in my master folder and put them in my directory but it does not seem to work. Any help would be awesome.

**Comment by mdod** [comment]
Do you have these files in a folder named fonts located in your main folder?

https://github.com/sachinchoolur/lightGallery/blob/master/dist/fonts/lg.ttf and https://github.com/sachinchoolur/lightGallery/blob/master/dist/fonts/lg.woff

**Comment by adpatel111** [comment]
Thank for responding back. I really like this plugin. I put the whole fonts and image folder in my main folder and now it seems to be working. I guess what I was doing wrong was putting those specific files in my folder instead the whole folder. 

Thank you so much.

**Comment by mdod** [comment]
Yeah, no problem.
If you want, you can change the file paths and folders around. I've just found it easier to keep everything the way it is by default.
