### ISSUE TITLE
comment box on mobile device

### ISSUE THREAD

**Issue by Daltonmedia** [sachinchoolur/lightGallery#414]
I love the commentbox sidebar feature, but it's kind of unusable since on mobile devices it hides the image (which is the core functionality of this script). Apart from that, wonderful work. Thanks.

**Comment by eduardoborges** [comment]
Yes, please :/

**Comment by mavoIn** [comment]
yes yes yes :D

**Comment by M-Husein** [comment]
Please Add This. Thanks :)

**Comment by UksusoFF** [comment]
@sachinchoolur any news here?
