### ISSUE TITLE
Getting actual / current image

### ISSUE THREAD

**Issue by uestla** [sachinchoolur/lightGallery#415]
Is there any way to get the current visible image?

Now I'm achieving this with `hash` plugin active and parsing the index from URL hash:

``` js
var actual = null;
var gallery = $('...');
var images = $('li a', gallery);

var lg = gallery.lightGallery({
    hash: true
});

lg.on('onAfterOpen.lg onAfterSlide.lg', function (event, index) {
    var m = /slide=(\d+)/.exec(location.hash); // parse slide index from #hash

    if (m) {
        actual = images.eq(m[1]).attr('href'); // save link href if matched
    }
});
```

**Comment by sachinchoolur** [comment]
Hey @uestla ,

`onAfterSlide.lg` event already provides the current index.

``` js
$lg.on('onAfterSlide.lg', function (event, prevIndex, index) {
      alert(index)
});
```

Docs: http://sachinchoolur.github.io/lightGallery/docs/api.html#events

**Comment by uestla** [comment]
Oh I was using 2nd argument as `index`, not as `prevIndex`.

My bad, sorry and thank you very much! :-)
