### ISSUE TITLE
sometimes not able to play video... showing properly in gallery

### ISSUE THREAD

**Issue by sufiiiyan** [sachinchoolur/lightGallery#417]
hi
sometimes not able to play videos on slide..... not sure what is going on can you please help what is missing or to remove
in firebug in inspect if i remove lg-outer class i able to click and play video
here is my code
`var finalArray = [];`

`lightObjVid.iframe = true;
                            lightObjVid.src = newObj[i].url;
                            lightObjVid.thumb = newObj[i].imgurl;
                            finalArray.push(lightObjVid);`

`(elm).lightGallery({
                            dynamic: true,
                            dynamicEl: finalArray,
                            hideControlOnEnd: true,
                            counter: false,
                            closable: false,
                            counter: false,
                            download: false,
                            startClass: '',
                            thumbnail:true,
                            enableSwipe: false,
                            enableDrag: false,
                            loop: false,
                            slideEndAnimatoin: true,
                            preload: 2,
                            videojs: true,
                            addClass: '',
                            mousewheel: false,
                            showAfterLoad: true,
                            youtubePlayerParams: {
                                modestbranding: 1,
                                showinfo: 0,
                                rel: 0,
                                controls: 0
                            },
                            vimeoPlayerParams: {
                                byline : 0,
                                portrait : 0,
                                color : 'A90707'     
                            },
                                loadYoutubeThumbnail: true,
                            youtubeThumbSize: 'default',
                            loadVimeoThumbnail: true,
                            vimeoThumbSize: 'thumbnail_medium',
                        });`

**Comment by Juventino96** [comment]
1+

**Comment by sachinchoolur** [comment]
Hey @sufiiiyan,

It seems like the problem is not with lightGallery. Since it is an old issue, I hope you must have solved it. 
Please provide your website URL and re-open the issue if it persists
