### ISSUE TITLE
First click go to next image not working with trigger

### ISSUE THREAD

**Issue by nkforeg** [sachinchoolur/lightGallery#418]
hi,
i have a problem
first click go to next image/prev image in the first load not working with trigger('click')

here is my code
https://jsfiddle.net/yjy5jgoq/

**Comment by franszo** [comment]
I have the same problem

**Comment by nkforeg** [comment]
@franszo "did you sorted somehow" - what do you mean?

**Comment by achintverma** [comment]
@nkforeg Try $lg.children('a').first().trigger('click');

**Comment by franszo** [comment]
Done the same , worked

**Comment by nkforeg** [comment]
@achintverma, @franszo: it works, thank you all :)
