### ISSUE TITLE
Uncaught TypeError: $(...).lightGallery is not a function

### ISSUE THREAD

**Issue by hemantsinghi** [sachinchoolur/lightGallery#419]
Getting Uncaught TypeError: $(...).lightGallery is not a function error, even though using the CDN links.

**Comment by SANTOSHKVNSP** [comment]
Even I am having the same issue

**Comment by hemant7420** [comment]
Thanks for the reply.I am getting this error when I am attaching the gallery to a popup div.
Regards,
Hemant Singhi

On 10-Aug-2016, at 8:04 PM, SANTOSHKVNSP <notifications@github.com<mailto:notifications@github.com>> wrote:


Even I am having the same issue

**Comment by SANTOSHKVNSP** [comment]
Can you check the jquery version you are using? Mine was a jquery version issue

**Comment by hemant7420** [comment]
Ohh okay. Thank you.

On 12-Aug-2016, at 5:35 PM, SANTOSHKVNSP <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you check the jquery version you are using? Mine was a jquery version issue

**Comment by abnersajr** [comment]
Probably the error is being caused by the way of you was calling the content. Try to initiate the lightgallery after popup open, in a a popup callback like afterOpen something like this.
And if you are using ajax to this you have to initialize after the ajax was loaded.
