### ISSUE TITLE
Getting black screen and broken controls when I put the images in divs or as list items

### ISSUE THREAD

**Issue by steven410** [sachinchoolur/lightGallery#423]
Testing out using this and had no issues with my images sitting in a <div> like so:

`<div id="lightgallery">
    <a href="images/img_0459.jpg">
      <img class="img-responsive" src="images/img_0461.jpg" />
    </a>

```
<a href="images/img_0459.jpg">
  <img class="img-responsive" src="images/img_0461.jpg" />
</a>

</div>`
```

but if I tried putting the images in their own <div> so they could be styled, then clicking on an image would bring up a black lightbox where none of the controls worked, I couldn't even use esc to close it. 

My code looks like this:
`<div id="lightgallery">
    <div class="someclasses">
    <a href="images/img_0459.jpg">
      <img class="img-responsive" src="images/img_0461.jpg" />
    </a>
    </div>
    <div class="someclasses">
    <a href="images/img_0459.jpg">
      <img class="img-responsive" src="images/img_0461.jpg" />
    </a>
    </div>
    </div>`

The same issue happened when the images where list items:
`<ul id="lightgallery">
    <li class="someclasses">
    <a href="images/img_0459.jpg">
      <img class="img-responsive" src="images/img_0461.jpg" />
    </a>
    </li>
    <li class="someclasses">
    <a href="images/img_0459.jpg">
      <img class="img-responsive" src="images/img_0461.jpg" />
    </a>
    </li>
    </ul>`

Why does having the images in a div or li not work? I need to be able to style to images so they are properly sized and placed.

**Comment by ramtml** [comment]
it will work? could you please provide a js fiddle demo??
