### ISSUE TITLE
Wrapping <img> with <div>

### ISSUE THREAD

**Issue by ohpyupi** [sachinchoolur/lightGallery#429]
Hi. I would love to thank to author who made and share this awesome plugin! I have been using and they were just nice for me. However, I came up with a problem that if I wrap <img> with <div> the lightgallery takes forever loading image.

Here is my code example,

```
<div id='lightgallery'>
    <div class='I WANT THIS GUY!'>
        <a href='path to image'>
        <img src='path to thumbnail image'></img>
        </a>
    </div>
</div>
```

Is there anyone who can help me solving this problem?

**Comment by catwiththreehats** [comment]
I ran into the same question yesterday. According to the documentation it is possible to pass a selector when initializing the lightgallery ( [documentation link](http://sachinchoolur.github.io/lightGallery/docs/api.html#passing-options) ) .

I think in your case you could just pass a selector searching for the 'a' tags inside the gallery. This would look like this:

`        $("#lightgallery").lightGallery({
            selector: 'a'
        }); 
`

**Comment by ohpyupi** [comment]
Thanks @catwiththreehats for your help!
Actually I also solve that problems with my own solution. I seemed like lightgallery is figuring out the image gallery with href tag on a children elements of $('#lightgallery'). **That means if any element under $('#lightgallery') has href tag that says the path of images, it will work fine. Thus,  I put href attribute in div tag!** 

Interestingly, I solve the problem with the code below!

```
<div id='lightgallery'>
    <div class='I WANT THIS GUY!' href='THIS HREF TAG ON DIV SOLVED MY PROBLEM!'>
        <img src='path to thumbnail image'></img>
    </div>
</div>
```

Thanks again @catwiththreehats. Obviously, I will try to use your solution later time!
