### ISSUE TITLE
Using sprites instead of different images for thumbnails

### ISSUE THREAD

**Issue by ifig** [sachinchoolur/lightGallery#430]
I was wondering if there is a way to use a sprite to load faster the gallery instead of thumbnails? 
The only problem when I try that is that when the viewer is opened, the thumbnails can't be found because they are part of the sprite. 

EDIT : 

Another possibility : did anyone manage to use lazy loading to display the gallery?

**Comment by sachinchoolur** [comment]
At present, lightGallery doesn't support sprite images for thumbnails. And it already uses the lazy loading for main images. By default, lightGallery loaded only 3 images. Remaining images will be loaded as you navigate to other slides.
