### ISSUE TITLE
Lightgallery takes href instead of data-src for the image

### ISSUE THREAD

**Issue by Daltonmedia** [sachinchoolur/lightGallery#432]
Hey there,

Can someone help me out on this one.
I have a fiddle with my markup here : [https://jsfiddle.net/y8kL871v/2/](https://jsfiddle.net/y8kL871v/2/) 

For some reason the data-src is ignored in my markup. things are data-sub-html work perfectly though.
It takes the usual href as the source for the image. I don't want that, because I want the original link to stay where it is (for non javascript users and other usecases).

If I add the attributes to the div containing everything (in my case '.gallery-media-cover') and use that one as a selector, everything works, but this leaves me the rest of the div to be a trigger too, and I don't want that, since I have some extra links in that div.

I'm puzzled here.

**Comment by Daltonmedia** [comment]
I now tried to use the actual image as a selector (that one has no href), and again I provide a data-src to the big image, but now it takes the default src tag as the image to load in the lightbox instead of the data-src

**Comment by abnersajr** [comment]
The problem is that you have href link and data-src in same attribute.  I really don't understand what you are trying to do with href to link and data-src with an image.
href have preference than data-src if you have the two attributes

**Comment by Daltonmedia** [comment]
I'd like to have the original page to stay there (for bookmarking, non-javascript users,..) but if on the page I'd like regular clicks just to go to the pop-up where only the image is.

**Comment by abnersajr** [comment]
Ok, I understood more or less. 
For me this is quite confused. Try to explain better.

**Comment by Daltonmedia** [comment]
If the user has JavaScript disabled, or he opens the image in a new browsertab, he will open just an image file. This is ok when the image opens in the lightgallery, but in the case of a new tab, or without JavaScript, I want him to go to a default href, which has a full html page with the image.
