### ISSUE TITLE
iframe with dynamic mode behaves different in chrome

### ISSUE THREAD

**Issue by glasreiniger07** [sachinchoolur/lightGallery#435]
At first: thank you for this outstanding gallery!

I  use the iframe feature to display i.e. PDFs via google docs and other things. It works like a charm with Firefox, but Chrome(Desktop/android) sometimes doesn't load the content, even if there is not much to load. Often only the second frame emerges, sometimes nothing at all.
Seems like a timing Issue to me?

I was able to reproduce the behavior in a reduced setup: [fiddle](https://jsfiddle.net/2Lzte0qf/2/)
On Chrome I see nothing in the gallery, but Firefox works fine.

It would be nice to get a hint if its me doing wrong or where to investigate further to nail the issue down.

Cheers!

**Comment by sachinchoolur** [comment]
Your fiddle works fine for me. (checked multiple times). Please re-open if the issue persists
