### ISSUE TITLE
Better way to close the lighbox modal on mobile

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [sachinchoolur/lightGallery#439]
**Only by tiny X is very very old approach** (ANTI Fitts's Law each time to get to the edge of the screen) of galleries (by swipe down for example - by "back" button of the phone). 

This lightgallery look so **2016** (native) but this "close" idea is from **2000** (90% of the users i test my site on mobile - try to close this gallery in 3-4 ways "dont make me think" and lastly find this X button).

Please fix this issue :(

*\* Fitts's Law: The Importance of Size and Distance in UI Design

**Comment by Siton-Systems** [comment]
Example her: 
**swipeClose	true	bool	swipe up or down to close gallery**

http://www.andrerinas.de/simplelightbox.html

**Comment by smbowler** [comment]
Hello! Just checking in to see if this was ever addressed. Finding the same issue with my users. Love lightgallery! thank you!
