### ISSUE TITLE
Download not working in ie

### ISSUE THREAD

**Issue by mail2venkat** [sachinchoolur/lightGallery#440]
When we click on download button, image is not get downloaded in ie, have researched and got to know that download attribute is not supported in ie; is they any alternative way to achieve this functionality in ie please help

**Comment by sachinchoolur** [comment]
Hi,
IE does not support download attribute. But, you can pass custom download url via `data-download-url` attribute  http://sachinchoolur.github.io/lightGallery/docs/api.html#attributes
