### ISSUE TITLE
local HTML5/mp4 video not playing in chromium / webkit browser

### ISSUE THREAD

**Issue by fodiator** [sachinchoolur/lightGallery#441]
Hi,
I have a light gallery (V 1.2.22") which nicely plays some short local mp4-videos with firefox. Unfortunately in chrome / webkit browser the gallery loads and videoplayer-controls are displayed but videos do not start (progressbar rotates forwever) 
There is no error indication in debugging console. 
I just found out, that your own HTML5 demo at http://sachinchoolur.github.io/lightGallery/demos/html5-videos.html shows the same bug. (tested with chromium Version 51.0.2704.79 Ubuntu 16.04 (64-bit)

Kind regards

**Comment by scdemanett** [comment]
The issue is Chromium doesn't support MP4 so you need a WEBM source as well to work in Chromium. This is not a bug but rather just the way Chromium is going, dropping support for MP4.
