### ISSUE TITLE
Is is possible to add audio?

### ISSUE THREAD

**Issue by Mahopacs** [sachinchoolur/lightGallery#443]
I would like to create a responsive image gallery with thumbnails, when the thumbnail is clicked it will be displayed in a modal/lightbox with an audio file being played.  When the modal/lightbox is closed the audio file will stop playing and the image gallery of thumbnails is again displayed.

Is this possible?  I did not see anything about playing an audio file.

**Comment by vitoravale** [comment]
i think it's possible with video.js and <audio> tag. 

see: [Html5 video gallery with videojs](http://sachinchoolur.github.io/lightGallery/demos/html5-videos.html#video-without-poster) and [Video.js 4.9 - Now <audio> can join the party!](http://blog.videojs.com/Video-js-4-9-Now-can-join-the-party/)

**Comment by sachinchoolur** [comment]
Hey @Mahopacs ,
lightGallery is not fully compactable with audios. But, as @vitoravale suggested, you can use videoJs for current use.

**Comment by elisent** [comment]
Hi,

Any update on when will this become part of the core of lightgaller ?

Thanks!

**Comment by Sathishchary** [comment]
I am searching for the this, how to implement audio with light gallery?

**Comment by stempora** [comment]
I managed to implement audio using the example here: 

[https://sachinchoolur.github.io/lightGallery/demos/html5-videos.html](url)

For customisation i used this player [plyr](https://plyr.io/)

**Comment by intsfanatic** [comment]
In case anyone is wondering, if its possible to add audio. I added the same way you would add video. I used the same markup used here http://sachinchoolur.github.io/lightGallery/demos/html5-videos.html#video-without-poster and  changed type to audio/mpeg. It seemed to work, not sure if it´s valid though.
