### ISSUE TITLE
how to hide zoomIn button

### ISSUE THREAD

**Issue by jksenthilraja** [sachinchoolur/lightGallery#444]
hi guys 

I don't need zoomIn button for one screen but i need this one another screen  then how to  handle this one.

**Comment by webbieram** [comment]
try to do it with media query

**Comment by jksenthilraja** [comment]
That is based on index value.
Eg: i need zoom only for first image other image no need...

**Comment by sachinchoolur** [comment]
You can get the current index on `onBeforeSlide.lg` event. 

http://sachinchoolur.github.io/lightGallery/docs/api.html#events
http://sachinchoolur.github.io/lightGallery/demos/events.html
