### ISSUE TITLE
HTML structure for Automatically loading thumbnails

### ISSUE THREAD

**Issue by katoner** [sachinchoolur/lightGallery#446]
hi and thanks for your work.

the script is up and running but I can not manage to make the thumbnails load automatically for youtube and vimeo.

I have lg-thumbnail.js included.
I also have this at the end of my body:

```
<script type="text/javascript">
    $('#video-thumbnails').lightGallery({
    loadYoutubeThumbnail: true,
    youtubeThumbSize: 'default',
    loadVimeoThumbnail: true,
    vimeoThumbSize: 'thumbnail_medium',
}); 
</script>
```

what HTML structure should I use to load my thumbnails please? I do not see that specific info on your demo page https://sachinchoolur.github.io/lightGallery/demos/videos.html

thanks!!!

**Comment by sachinchoolur** [comment]
Hi,
Here is the demo for videos with 'Automatically load thumbnails'. http://codepen.io/sachinchoolur/pen/XNavPP

**Comment by katoner** [comment]
thanks for the reply. On that page it shows the images are linked to jpgs hosted on your site, not "loading automatically"? :

`data-poster="http://sachinchoolur.github.io/lightGallery/static/img/videos/y-video2-cover.jpg">
        <a href="">
          <img class="img-responsive" src="http://sachinchoolur.github.io/lightGallery/static/img/thumb-v-y-2.jpg">
          <div class="demo-gallery-poster">
            <img src="http://sachinchoolur.github.io/lightGallery/static/img/play-button.png">`

**Comment by sachinchoolur** [comment]
It loads only thumbnails inside the gallery. lightGallery does not have control over the thumbnails on your page.
![lightgallery videos](https://cloud.githubusercontent.com/assets/6586706/20695624/76537406-b613-11e6-9286-b9cbecc4ab09.png)

**Comment by katoner** [comment]
got it!! thank you
