### ISSUE TITLE
Missing Fullscreen icon with Safari

### ISSUE THREAD

**Issue by penatuna** [sachinchoolur/lightGallery#450]
I'm missing fullscreen icon with Safari browser. I can see it in all the other browsers (IE, FF, Chrome). Is this a known problem and is there a workaround?

**Comment by sachinchoolur** [comment]
Hi,
It works fine for me. Could you please post a screenshot of your gallery?

**Comment by penatuna** [comment]
Here it is with **Firefox**:
![lightgallery_firefox](https://cloud.githubusercontent.com/assets/18713159/18910396/7abf58a2-8580-11e6-82d5-2fc8ef00e624.png)

And here with **Safari**:
![lightgallery_safari](https://cloud.githubusercontent.com/assets/18713159/18910416/9028ee1a-8580-11e6-9c8d-3e370a68bc0a.png)

Tested with Safari 5.1.7 (PC) and Iphone SE (cant remember the version of Safari. I can find it out if necessary).

**Comment by sachinchoolur** [comment]
I am currently on vacation. I can not test it on safari now. 
Could you please run the following code on safari to check fullscreen browser support.

``` javascript
// check fullscreen browser support
  if (!document.fullscreenEnabled && !document.webkitFullscreenEnabled &&
     !document.mozFullScreenEnabled && !document.msFullscreenEnabled) {
           alert('Your browser does not support fullscreen mode!')
     }
```

**Comment by penatuna** [comment]
It gives this "Your browser does not support fullscreen mode!" alert. 

Is there any way to get it to work? If it's too much hassle, i completely understand.

FYI: With Safari, the Youtube videos work great in full screen.

**Comment by sachinchoolur** [comment]
Sorry for the delay. So Safari 5.1.7 does not support fullscreen mode. :)
