### ISSUE TITLE
New License

### ISSUE THREAD

**Issue by macsupport** [sachinchoolur/lightGallery#451]
So to use commercially for one project with all modules it's $59 and for Unlimited it is $285? More than I expected.

**Comment by sachinchoolur** [comment]
Hi @macsupport ,
I was also thinking about this :) I got few other emails too regarding the pricing.

I've updated the price. Now you don't need to purchase separate license for each lightgallery modules. Once you purchase a lightgallery commercial license you can use all lightgallery modules for free.

**Comment by macsupport** [comment]
Appreciated. Thanks!!

**Comment by makshh** [comment]
Hi,

Is it possible to use lightGallery plugin in for example Bootstrap theme which will be sold on the market?

I've read UpLabs license:

"Use in stock or template or other form of distribution
You may never use the product on its own or as part of a larger stock project."

**Comment by sachinchoolur** [comment]
Hi @makshh, 

Sorry that line is not very clear. 

You can use lightGallery "as part" of another product (which can be sold on marketplaces), but it can't be a copy of lightGallery, or lightGallery can't be the main component of the product.
