### ISSUE TITLE
TypeError: $(...).lightGallery is not a function

### ISSUE THREAD

**Issue by HamzaAbdullahMoh** [sachinchoolur/lightGallery#452]
I am using the **dynamic mode** through the **anchor tag** and I get this error in the console:

`TypeError: $(...).lightGallery is not a function`
`<anonymous>                                                                                  gallery.js:2`
`m.event.dispatch()                                                                      jquery.min.js:3`
`m.event.add/r.handle()                                                               jquery.min.js:3`

please bear in mind I am not a pro with JavaScript!!

**Comment by sachinchoolur** [comment]
Make sure that you have included lightgallery.js in your document.

You can refer dynamic mode demo [here] (https://jsfiddle.net/sachi77/sabgjobj/)

**Comment by HamzaAbdullahMoh** [comment]
I already did and directly before it!!

**Comment by HamzaAbdullahMoh** [comment]
this is the code
https://jsfiddle.net/hamzaabdullahmoh/c4quqf0v/#&togetherjs=qz2kFk037N

**Comment by HamzaAbdullahMoh** [comment]
Wooooooooooo Haaaaaa I finally solved it, and the problem was maybe with local version I have!!
When I switched to the cdnjs version it worked PERFECT!!!
