### ISSUE TITLE
Add Light Gallery to JSDEILVR and CDNJS

### ISSUE THREAD

**Issue by HamzaAbdullahMoh** [sachinchoolur/lightGallery#453]
Please someone add the main library and the sub ones to https://www.jsdelivr.com and https://cdnjs.com, CDNJS lacks of the sub libraries like lg-thumbs.min.js and others.

**Comment by sachinchoolur** [comment]
Hi,
All lightGallery plugins are available on https://www.jsdelivr.com/?query=lightgallery
