### ISSUE TITLE
Errors with jQuery No Conflict Mode

### ISSUE THREAD

**Issue by nash-ye** [sachinchoolur/lightGallery#454]
Not all websites are using the $ alias for jQuery, the WordPress websites for an example. Please review this great library with the no conflict mode, and use the official 'jQuery' variable instead of.

**Comment by sachinchoolur** [comment]
Thank you for pointing this out.
 I've fixed the issue. Please use the latest version

**Comment by lfolco** [comment]
Can you explain how to enable this? I don't see anything in the docs.
