### ISSUE TITLE
LightGallery compatible with echo.js

### ISSUE THREAD

**Issue by X-rapido** [sachinchoolur/lightGallery#455]
您好，很高兴能使用到这么强大的lightGallery插件，在之前的项目中也都经常使用，非常的棒，目前在项目中遇到了一个问题一直困扰着我，所以想请教一下。
项目中使用的图片懒加载echo.js支持，再使用lightGallery时，就会发生lightGallery展示图片不显示，不兼容的问题。
在之前的项目中用到的懒加载是lozyload.js貌似就没有这种问题，也许是echo.js的懒加载规则与其他懒加载规则不同所导致的，所以请问一下，您有什么样的好办法，可以让lightGallery来支持echo.js？

**Comment by sachinchoolur** [comment]
lightgallery should work fine with echo.js. Please provide a jsfiddle demo if you are still having trouble with echo.js
