### ISSUE TITLE
Strange error in production t.data is not a function

### ISSUE THREAD

**Issue by donBigote** [sachinchoolur/lightGallery#458]
I am using lightGallery in a rails app. It is working fine in development, but in production I am seeing this error: 

`Uncaught TypeError: t.data is not a function`

When I click a thumbnail, it just reloads the page instead of opening the gallery.

**Comment by sachinchoolur** [comment]
Do you mean the minified versions of lightGallery? If yes, it works fine for me. Please check the codepen demo http://codepen.io/anon/pen/zKEvVG

Otherwise, it might be some issues with your app. Make sure that you are calling lightgallery.js before its plugins.

**Comment by donBigote** [comment]
yes, i used the minified version of lightGallery. It works fine in development. I agree that it must be something with my app. I was just wondering if anyone had ever seen that particular error and what it might mean so that I could figure out what isn't being loaded correctly in my production environment. Or if it meant that my links were set up incorrect in my html.

**Comment by Broodja** [comment]
Have kinda similar issue. The reason of my issue is file generated by UglifyJs from actual .min file that is broken (I used [UglifyJS online](https://skalman.github.io/UglifyJS-online/) to verify it)
Don't know whether it's a problem of lightgallery or uglifyjs.

**Comment by luckynumberslevin** [comment]
For information I add the same problème with the version 1.2.22 of lightGallery. Upgrade to the version 1.3.7 solved the problem.

**Comment by billym** [comment]
I got the same error. It was uglfier in rails messing up the min file. Just use the non min file to fix it. Ugfier will min it.
