### ISSUE TITLE
Hide navigation arrows on mobile only?

### ISSUE THREAD

**Issue by touto123** [sachinchoolur/lightGallery#459]
Is it possible to hide the arrows when using a mobile device? At the moment, the arrows are on top of the image on small devices so I'd prefer if they'd just be hidden. Many thanks!

**Comment by sachinchoolur** [comment]
You can use setting `controls:false` to hide the navigation arrows.

```javascript 
$('#lightgallery').lightGallery({
    controls: $(window).width() >= 768
 });
```
