### ISSUE TITLE
Video MP4 Issue

### ISSUE THREAD

**Issue by rafasegat** [sachinchoolur/lightGallery#460]
Hi,

Great library.

I'm using your library on my Wordpress plugin, but the video MP4 is not working.

Take a look.(bottom page there is videos examples)

http://instagramwordpress.rafsegat.com/

When click does not open the video. In Chrome sometimes works and sometimes not, also for Mozilla and IE.

Can you support me?!

Thanks
Raf

**Comment by sachinchoolur** [comment]
You are using different versions of lightGallery CSS and javascript.
Version lightgallery-all.min.js on your website is  v1.2.22. I couldn't find which version of lightgallery.css you are using, but I'm sure that it is not v1.2.22.
Please use the latest version of lightGallery (Both JS and CSS). It will work fine.

**Comment by rafasegat** [comment]
Thanks sachin for your response.

Im not able to find script with all features and and latest version.

Can you send me the link?

Thanks
Raf

**Comment by sachinchoolur** [comment]
All plugins are separate packages now. You can install the plugins using bower or npm

#### Bower 
``` sh
$ bower install lightgallery lg-thumbnail lg-video lg-pager lg-hash lg-autoplay lg-fullscreen lg-share lg-video
```

#### NPM
``` sh
$ npm install lightgallery lg-thumbnail lg-video lg-pager lg-hash lg-autoplay lg-fullscreen lg-share lg-video
```

Or you can directly download from [github repositories](https://github.com/sachinchoolur/lightGallery#built-in-modules)

**Comment by rafasegat** [comment]
Still not working I have no idea how to fix it.

I already followed all instructions on docs.

:/

Thanks
Raf
rafsegat.com
