### ISSUE TITLE
Bullets showing with the demo code.

### ISSUE THREAD

**Issue by mindspies** [sachinchoolur/lightGallery#461]
I use the script with the demo code in the lightgallery-master folder.

It works very well but there is a dot before every picture, on every browser except Chrome.

Do you know a way to remove those dots, or do you have other demo codes I can use to remove those dots.

Thanks.

**Comment by sachinchoolur** [comment]
Just add the following lines of  CSS into your document. 
``` css
ul {
    list-style-type: none;
}
```

**Comment by mindspies** [comment]
Thank you so much.
