### ISSUE TITLE
Confused about licensing

### ISSUE THREAD

**Issue by smerriman** [sachinchoolur/lightGallery#462]
When I visited the lightgallery site recently, it said it was 100% free for personal and commercial use, so I used it on a website for a business I was creating.

Now it says a license is 'appropriate' for commercial use. Does this mean if I want to use lightgallery on any website I have to purchase a license? How exactly is that enforced given it is free and open source? (Very rare for any website to not have some minor commercial aspect, even if there is no direct selling involved). 

Given the version I downloaded was free for all use,  I presume I am able to continue to use that version for free anywhere I like - you couldn't just require every website that uses it to suddenly start paying when it was described as free.

**Comment by smerriman** [comment]
According to http://stackoverflow.com/a/1661327/707225, it sounds like the open-source GPL license provided actually means you can use it anywhere you like, any only need the commercial license if you require support or need a license if it's incompatible with your own business model.

**Comment by sachinchoolur** [comment]
Hi,
lightGallery version 2.x It is completely free to use for personal projects, as well as commercial based projects. But you need to purchase a commercial license if you want use lighGallery version 3.0 or higher for commercial use.

**Comment by sachinchoolur** [comment]
FYI: You can always use GPL software in commercial based projects. But you must make the source code of the project available for the users.

**Comment by Jesperanza** [comment]
Excuse my ignorance of licensing, but would i need to buy a license in the following situation?

I mange several dozen websites for a company and we would like to use this script on each site.

**Comment by sachinchoolur** [comment]
Hey @Jesperanza,

Yes, you need to buy a license to use lightGallery on those websites. As you need to use the script on multiple sites, the extended commercial license would be the appropriate license.

let me know if you have any queries
