### ISSUE TITLE
License

### ISSUE THREAD

**Issue by robertimes** [sachinchoolur/lightGallery#463]
What is the difference between this plugin and the other one called "lightgallery.js" which does not require purchase of a commercial license? 

The plugins are identical, why is one free and one not?

Free version:
https://sachinchoolur.github.io/lightgallery.js/

Paid version:
http://sachinchoolur.github.io/lightGallery/

**Comment by penatuna** [comment]
Both have commercial licence. I guess that lightgallery.js is straight javascript version and lightGallery needs jQuery library to work.

**Comment by sachinchoolur** [comment]
Yes exactly. :)

**Comment by robertimes** [comment]
Well, thanks for clarifying and also for changing the "lightgallery.js" page header to reflect this because it was free to use commercially under Apache yesterday. Anyway, the plugin is worth the money, will purchase a developer license. Just wanted to ask if RTL is working properly, though.
Thanks!
