### ISSUE TITLE
video loading problems

### ISSUE THREAD

**Issue by llllllb** [sachinchoolur/lightGallery#466]
Hi, I am having some issues with the plugin. 

I have a lightgallery with two html5 videos, and 3 images. I have my gallery set up as on the demo page: http://sachinchoolur.github.io/lightgallery1.2/demos/html5-videos.html except some have images.

Previously, despite setting the videos to "preload="none", both videos were autoplaying when I clicked on the first one (so their sound overlapped). I have been poking around on the forums and trying different versions of the plugin, including the most recent one from your gitHub page. now, nothing is working at all. I'm totally confused as to what is going wrong, and would really appreciate a little help!

My page is here: http://dgrahamburnett.net/gallery-OLD.html
and all the code should be visible.

thanks for your help,
Leah

**Comment by sachinchoolur** [comment]
Hi,
Sorry for the delayed response.
I think it is not an issue with lightGallery. 
First of all, you are using different versions of lightgallery.js and css. Use latest versions of lightgallery.js and lightgallery.css
Secondly, load your javascript files at the bottom of the page and initiate lightGallery once dom is ready.
``` javascript 
$(document).ready(function() {
  $('#lightgallery').lightGallery();
});
```


Let me know if you need any further explanation.
