### ISSUE TITLE
Feature Request - New Methods

### ISSUE THREAD

**Issue by dbudde** [sachinchoolur/lightGallery#469]
I was wondering if you would be willing to add in public methods for:
- show
- hide
- showBar
- hideBar
- showCaption
- hideCaption

It would be a nice to have a little more control over these items.

**Comment by jfeust** [comment]
+1. 

I'd love on mobile to be able to tap the picture and hide the bars/captions/button until I tap the picture again.  If that couldn't be part of lightGallery proper, I could implement it with these methods.
