### ISSUE TITLE
Urgent! Base64 Decoded Image Support

### ISSUE THREAD

**Issue by mehmetalidumlu** [sachinchoolur/lightGallery#471]
Hi,
Is not it support base64 decoded image string?

**Comment by sachinchoolur** [comment]
Hi,
I'm sorry, I didn't understand your question properly. What is the difference between Base64 Decoded image and a normal image? I guess you want to use base 64 encoded image string with lightgallery. In that case, you can directly pass the image string via data-src attribute.
