### ISSUE TITLE
Zoom and other functionalities icon not showing

### ISSUE THREAD

**Issue by AllenCarlanz** [sachinchoolur/lightGallery#472]
Hi there,
I love lightGallery features so much! I'm just wondering why the zoom in/zoom out feature/icon is not present in my lightbox popup? If you'll check the upper right part it's missing. I'm really sorry in advance for the inconvenience.

![screen shot 2016-10-12 at 11 03 06 pm](https://cloud.githubusercontent.com/assets/11757269/19315398/119e5714-90d0-11e6-89b0-66c991762c07.png)

Here's my code
<img width="985" alt="screen shot 2016-10-12 at 11 04 57 pm" src="https://cloud.githubusercontent.com/assets/11757269/19315465/5817de86-90d0-11e6-95ae-8cb9fdf3b44b.png">

Thanks,
Allen

**Comment by sachinchoolur** [comment]
You have to include lg-zoom.js in your document.
https://github.com/sachinchoolur/lg-zoom
