### ISSUE TITLE
On iOS(iPad, iPhone) not playing videos

### ISSUE THREAD

**Issue by hiphoptime** [sachinchoolur/lightGallery#473]
Hi, i am opening gallery on demo page and go to next/previous video, then YouTube stop working (it is impossible to re-press the play). Only YouTube.
http://sachinchoolur.github.io/lightGallery/demos/videos.html
Desktop & Android 4.4.4 works fine, but not iOS. (iPad- 9.1, iPhone 5S - 10.0.2)

How to fix it?

**Comment by hiphoptime** [comment]
P.S.
Only YouTube and only if video without poster

**Comment by sachinchoolur** [comment]
It works fine for me. You have to click on the play icon to resume the videos. And make sure that your captions are not hiding the play icon

**Comment by noveweb** [comment]
On iOS Chrome and Safari video not working. On android working fine.

**Comment by BeyondspaceTeam** [comment]
> It works fine for me. You have to click on the play icon to resume the videos. And make sure that your captions are not hiding the play icon

That is an issue I'd like to ask about, how can we set up dynamic caption height for each slide. If the grid gallery has different caption content, there is chance the subhtml over the play button
https://www.lightgalleryjs.com/demos/video-gallery/ when click on the last video and navigate away, other caption cover the bottom of the video

Thanks
![image](https://user-images.githubusercontent.com/90233168/132972897-444778ab-4ccb-46ce-96ca-7987b71923da.png)
