### ISSUE TITLE
Open gallery from other button?

### ISSUE THREAD

**Issue by ALTELMA** [sachinchoolur/lightGallery#474]
I will finding solution for click button and open gallery and integrated from lightslider
I not sure It's possible to do like this.

Anyone can suggestion?
Thanks

**Comment by sachinchoolur** [comment]
Hi,
#### Method 1: 
Use lightGallery dynamic mode 
Demo : http://sachinchoolur.github.io/lightGallery/demos/dynamic.html

#### Method 2: 
Trigger click event with jQuery :
``` javascript
$('#mybutton').on('click', function() {
   $('.first-item').trigger('click');
});
```

**Comment by giangphoton** [comment]
Hi Sachin,

I tried to trigger click event with jQuery using Method 2 you mentioned above but it didn't work. Please review my code.

I have a Zoom icon with id "zoom-btn":
`          <div class="zoom-btn">
            <span class="fa fa-search" aria-hidden="true">
          </div>`

For the script:
`  <script>
  lightGallery(document.getElementById('lightgallery'));

  $(document).ready(function() {
    $('#zoom-btn').on('click', function() {
      $('#item1').trigger('click');
    });
  });
  </script>`

I clicked on the button and it didn't run. Please give me some suggestions.

Thanks,
Giang

**Comment by fhdalikhan** [comment]
> 
> 
> Hi Sachin,
> 
> I tried to trigger click event with jQuery using Method 2 you mentioned above but it didn't work. Please review my code.
> 
> I have a Zoom icon with id "zoom-btn":
> ` <div class="zoom-btn"> <span class="fa fa-search" aria-hidden="true"> </div>`
> 
> For the script:
> ` <script>
> lightGallery(document.getElementById('lightgallery'));
> 
> $(document).ready(function() {
> $('#zoom-btn').on('click', function() {
> $('#item1').trigger('click');
> });
> });
> </script>`
> 
> I clicked on the button and it didn't run. Please give me some suggestions.
> 
> Thanks,
> Giang

You have a class name zoom-btn not an id, to reference a class use $('.zoom-btn') and for id use $('#zoom-btn') jquery selector.

**Comment by bhideghety-SPC** [comment]
@surfer77 having this works on the 1st gallery group, but not on the 1ns.
I debugged it, the 2nd gallery groups 1st list-item get's the click event, yet not opening.
But it's enough to comment the 1st group and it works.
