### ISSUE TITLE
Is it possible to load multiple video in single div

### ISSUE THREAD

**Issue by KarthikDev81** [sachinchoolur/lightGallery#476]
Hi Sachin,
Thanks for this plugin. You made my day awesome man! 
`<div id="video01" style="display:none;" controls>
                	<video class="lg-video-object lg-html5 video-js vjs-default-skin" controls preload="none">
                          <source src="video.mp4" type="video/mp4" />
                    </video>
                </div>`
If I have more than 100 videos means, how can i generate this code... For More than 100 times?? Or else I need the same container for all the videos 'ONCLICK'.

Thanks in advance,
Karthik N

**Comment by sachinchoolur** [comment]
Hi Karthik,

Currently, it is not possible to load multiple video in single div.
You can either pass id or class name of your hidden div which contain the video via data-html attribute or directly pass the video html via data-html attribute.

Demo : http://sachinchoolur.github.io/lightGallery/demos/html5-videos.html
