### ISSUE TITLE
Make lightgallery same page

### ISSUE THREAD

**Issue by ALTELMA** [sachinchoolur/lightGallery#477]
I already integrated lightslider+lightgallery everything ok and I use new lightgallery to open gallery for new button with dynamic option.

It's possible to set current slide for both gallery?
I mean when I open gallery A [lightslider+lightgallery] and go to slide 7
After that I open gallery B [lightgallery with dynamic option] and should go to slide 7

Now start at slide 1

Please suggestion or help me.

**Comment by ALTELMA** [comment]
I found solution

`
var $lg = $(this).lightGallery({
     dynamic: true,
     dynamicEl: $galleryJson,
});
$lg.data('lightGallery').index = $currentSlide;
`

**Comment by sachinchoolur** [comment]
Hi,
sorry for the delayed response. Instead of the above code, you can directly pass `index` while initializing lightGallery

``` javascript
    $(this).lightGallery({ 
        dynamic: true, 
        dynamicEl: $galleryJson, 
        index: $currentSlide;
    })
```

**Comment by ALTELMA** [comment]
Nope, thanks. I will do it. ;)
