### ISSUE TITLE
Clicking zoom in keeps reverting to center

### ISSUE THREAD

**Issue by andrewf10** [sachinchoolur/lightGallery#479]
Hi,

This is a fantastic lightroom plugin but I have one question about the zoom part of it. If someone could help me it'd be greatly appreciated.

If I zoom in, then pan to some part of the image and then click the "zoom in" button again, the zoom part does work but the image moves back to the center. Is there any way to hold the current position after the "zoom in" button is clicked?

Thanks

**Comment by sachinchoolur** [comment]
Hey @andrewf10,

At present, this feature is not available. Watch the repository, I'll include this feature when I get time

**Comment by MickL** [comment]
Is this implemented already? :)

**Comment by sachinchoolur** [comment]
No, Not yet. Planing for version 2.0

**Comment by digiiitalmb** [comment]
Is this done or no?
