### ISSUE TITLE
Where are plugins like lg-fullscreen?

### ISSUE THREAD

**Issue by robiningelbrecht** [sachinchoolur/lightGallery#480]
In version 1.2.x there were a number of plugins located at dist/js. Where have they gone in version 1.3?
![image](https://cloud.githubusercontent.com/assets/203894/19588369/85bdf71c-9765-11e6-8889-f4d38aef4fc2.png)

**Comment by sachinchoolur** [comment]
Sorry for the delayed response, All plugins are moved to separate repositories since version 1.3.
https://github.com/sachinchoolur/lightGallery#built-in-modules
