### ISSUE TITLE
Html5 videos keep playing after slide event

### ISSUE THREAD

**Issue by fendorio** [sachinchoolur/lightGallery#481]
Only tested this on Android Chromium (Crosswalk). 

Using Html5 videos if I play a video and then slide to another video the former video keeps playing in the background. 

Is this a bug or is there a config option / event handler i'm not seeing in the docs to prevent this behaviour?

**Comment by sachinchoolur** [comment]
@fendorio,
It works fine for me. Which version of Android/Chromium do you use?

**Comment by Hakihiro** [comment]
Same problem on chrome desktop (Version 54.0.2840.99 m)

**Comment by sachinchoolur** [comment]
I use the same version and it works fine. Could you, please check the demo website on chrome? http://sachinchoolur.github.io/lightGallery/demos/html5-videos.html
