### ISSUE TITLE
How to add Mp4 videos in gallery dynamically?

### ISSUE THREAD

**Issue by amrapalideore** [sachinchoolur/lightGallery#482]
hi,

I am creating dynamic gallery for images and videos but i am unable to add mp4 videos dynamically.
Help me with this issue.

**Comment by sachinchoolur** [comment]
You can use the bellow format to add html5 videos. 
``` javascript
$('#lightgallery').lightGallery({
  dynamic: true,
  dynamicEl: [{
    thumb: '../static/img/thumb-1.jpg',
    html: '<video class="lg-video-object lg-html5" controls preload="none"><source src="../static/videos/video1.mp4" type="video/mp4">Your browser does not support HTML5 video</video>'
    }]
})
```
Docs: 
https://sachinchoolur.github.io/lightGallery/docs/api.html#dynamic
https://sachinchoolur.github.io/lightGallery/demos/html5-videos.html

**Comment by amrapalideore** [comment]
Thank you...it got worked

**Comment by aviatix** [comment]
Basically it also worked for me. But unfortunately all videos start playing immediately. Tested on Chrome and Firefox.
My configuration string looks like this:

`
$('#lightgallery').lightGallery({
  dynamic: true,
  dynamicEl: [{
'html': '<video class="lg-video-object lg-html5" controls="controls" preload="none" autostart="false" autoplay=""><source src="[(${video.link})]" type="video/mp4">Your browser does not support HTML5 video</video>'
 }]
})
` 

I also fiddled around with setting autostart or autoplay to different values. Is it html5 that starts this video or also lightGallery interfering here somehow?

Thanks for you help

**Comment by aviatix** [comment]
Ok - I found it out myself. If you provide a poster/thumbnail-images this issue is solved!
