### ISSUE TITLE
Licence Issue

### ISSUE THREAD

**Issue by simran2017** [sachinchoolur/lightGallery#483]
Today i purchase LightGallery Plugin and after downloading the plugin i found only two files "lightgallery.js" and "lightgallery.min.js". while i was expecting this will also support .js files such as "lg-share.js" i want to use SHARE with teh gallery and after purchase i cant find "lg-share.js". one "https://sachinchoolur.github.io/lightGallery/" it doesnt mention about other support files which is misleading if one wants to use all feature of teh plugin mentioned on there website.

I read other post regarding license which also confuse further as some license is required for version 3 & above and when i checked in "lightgallery.js" it is mentioned "lightgallery - v1.3.5 - 2016-09-30". Please advice do we have to purchase additional license for other features such as share feature etc.. if not then from where i can download this support files such as "lg-share.js", "lg-pager.js" etc...

**Comment by sachinchoolur** [comment]
Hi,
I'm sorry, I'll update the docs. All lightGallery plugins are separate packages now. https://github.com/sachinchoolur/lightGallery#built-in-modules
You can either directly download from respective GitHub repositories or using package managers such as bower or npm

You don't have to purchase separate license for that, It is free if you have a lightGallery license. 

Please let me know if you need any further information.
