### ISSUE TITLE
Videos and picture in the same gallery?

### ISSUE THREAD

**Issue by jeromax2** [sachinchoolur/lightGallery#485]
Hello,
it seems videos doesn't work if i put local videos (not remote like youtube) and pictures in the same gallery. Is it a mistake that i did ?
How can a display local videos and pictures under the same gallery like that : 
&lt;div&nbsp;style="display:none;"&nbsp;id="video1"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;video&nbsp;class="lg-video-object&nbsp;lg-html5"&nbsp;controls&nbsp;preload="none"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;source&nbsp;src="projet001.mp4"&nbsp;type="video/mp4"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Your&nbsp;browser&nbsp;does&nbsp;not&nbsp;support&nbsp;HTML5&nbsp;video.
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/video&gt;
&lt;/div&gt;
&lt;div&nbsp;id="lightgallery"&gt;
    &lt;a&nbsp;href="#"&nbsp;data-poster="v_projet001.jpg"&nbsp;data-html="#video1"&nbsp;title="Film"&gt;&lt;img&nbsp;src="v_projet001.jpg"&gt;&lt;/a&gt;
    &lt;a&nbsp;href="v_20151115_1320-DSC_1709.Challenge.de.La.Pirouette.jpg"&nbsp;title="Coucou"&gt;&lt;img&nbsp;src="v_20151115_1320-DSC_1709.Challenge.de.La.Pirouette.jpg"&gt;&lt;/a&gt;
&lt;/div&gt;

&lt;script&nbsp;type="text/javascript"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$(document).ready(function()&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$("#lightgallery").lightGallery({
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    &nbsp;mode:&nbsp;'lg-slide',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    &nbsp;preload:&nbsp;2,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    &nbsp;showAfterLoad:&nbsp;false,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    &nbsp;thumbnail:&nbsp;false,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    &nbsp;fullscreen:&nbsp;true
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;});&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;});
&lt;/script&gt;

Thanks you very much :-)

**Comment by sachinchoolur** [comment]
Hi,
Sorry for the delayed response. Just remove href attribute from the  video  anchor tag . It will work fine.
``` html
<div id="lightgallery">
<a data-poster="v_projet001.jpg" data-html="#video1" title="Film"><img src="v_projet001.jpg"></a>
<a href="v_20151115_1320-DSC_1709.Challenge.de.La.Pirouette.jpg" title="Coucou"><img src="v_20151115_1320-DSC_1709.Challenge.de.La.Pirouette.jpg"></a>
</div>
```

> `data-src` and 'href' should not be provided when you use html5 videos
