### ISSUE TITLE
IE8 issue: Zoom icons and fullscreen icon do not display in the demo

### ISSUE THREAD

**Issue by breezern** [sachinchoolur/lightGallery#488]
Hi there,
I have downloaded the zip file form this link: [Download ZIP](https://github.com/sachinchoolur/lightGallery/archive/master.zip).And then i opened the demo.But there are different results in Firefox and IE 8. Zoom icons and fullscreen icon do not display in IE8.
![firefox](https://cloud.githubusercontent.com/assets/8090132/20055199/fe762108-a51a-11e6-80d5-77b9dd7d855c.jpg)
![ie8](https://cloud.githubusercontent.com/assets/8090132/20055204/ffc35242-a51a-11e6-8ded-4a22d3a8f15c.jpg)

There is a related issue: #216 

Thanks,
breezern.

**Comment by sachinchoolur** [comment]
Hi,
lightGallery zoom plugin does not work in IE8 as it uses css3 transform. I'll Update the docs.
