### ISSUE TITLE
html5 video example with comment box / ignored dimensions for preview

### ISSUE THREAD

**Issue by ulfw** [sachinchoolur/lightGallery#489]
### example for html5 video with comment box

I use the lightGallery with the comment box on the right side.
Could you please provide an example for videos with comment box? It seems to be working different from usage with an image.

### dimensions and aspect ratio for videos and preview images
The poster that is used for video preview is not displayed in the correct dimensions and the aspect ratio is ignored. 
If a poster or video is smaller than the viewport (window size - comment box size) they are stretched to the full width and height of the parent element. The should be fixed.

Or are there options to modify display width and height of a video and his preview?

**Comment by sachinchoolur** [comment]
Thank you for pointing this out! I've fixed the issue. Please use latest version
