### ISSUE TITLE
Cycle2 slideshow and lightGallery

### ISSUE THREAD

**Issue by raxan** [sachinchoolur/lightGallery#490]
Hi,
I have issue using http://jquery.malsup.com/cycle2/ and lightGallery.

In some case I use normal setup of cycle2 for example:

https://jsfiddle.net/2ab7cwog/

And this work fine.

But when I use progressive example, this: http://jquery.malsup.com/cycle2/demo/progressive.php

https://jsfiddle.net/hg2p81h1/4/

Then there is issue, not all images are added in lightgallery.

I use setTimeout but this should be increase to high value when there are many images.

I would like to know if possible for you make an example of this.

Thanks!!

**Comment by sachinchoolur** [comment]
Hi,
It is because newly added images are not indexed by lightGallery. Try the bellow code. 
``` javascript
$(document).ready(function() {
  var $lg = $( '#lightGallery');
  $lg.lightGallery();
  $lg.on( 'cycle-update-view', function( event, opts ) {
    $lg.data('lightGallery').destroy(true);
    $lg.lightGallery(); 
  });
  $lg.on( 'onBeforeOpen.lg', function() {
       $('.cycle-slideshow').cycle('pause');
    });
  $lg.on( 'onBeforeClose.lg', function() {
     $('.cycle-slideshow').cycle('resume');
  });
});
```
Here is the working demo https://jsfiddle.net/sachi77/hg2p81h1/5/

**Comment by raxan** [comment]
Thanks for your reply, I much appreciate.
Just after posting this issue, I was able to make it work using dinamic load, this:
http://sachinchoolur.github.io/lightGallery/demos/dynamic.html

By using below code:

```js
		    $('body').on('click', 'a.dinamicLightGallery', function() 
		    {
		        $(this).lightGallery({
		            dynamic: true,
		            dynamicEl: window.dinamicElementForLightGallery
		        });
		    });
```

Works fine, so I will keep this solution.

Many thanks!
