### ISSUE TITLE
currentPagerPosition not working

### ISSUE THREAD

**Issue by parkersweb** [sachinchoolur/lightGallery#492]
Hi @sachinchoolur 

Just a quick question about the currentPagerPosition option in the thumbail plugin; either I've misunderstood what it does, or it's not working in the current version.

I *think* it should alter the alignment of the thumbnails so that the selected thumbnail appears at the left, center or right of the screen - but it doesn't seem to do anything? There's an amended example of the sample codepen to show you what I mean:

http://codepen.io/parkersweb/pen/mOPZGj

Thanks!

Andrew

**Comment by parkersweb** [comment]
Ah - looking at the code it looks like it only changes the alignment if current thumbnail is off-screen - so it pre-supposes that the number of thumbnails is greater than the screen width.

Is there any way to center the thumbnails for all cases?

**Comment by sachinchoolur** [comment]
Yes, You are right. It works only if thumbnails are greater than the screen width.

But you can easily center the thumbnails block by adding the following CSS code into your document 
``` css
.lg-outer .lg-thumb-outer {
  text-align: center;
}
.lg-outer .lg-thumb  {
  display: inline-block
}
```
Demo : http://codepen.io/anon/pen/NbrMyG

**Comment by parkersweb** [comment]
@sachinchoolur ah - thanks!
