### ISSUE TITLE
Feature Request: Custom Slide ID with hash plugin

### ISSUE THREAD

**Issue by tompratt** [sachinchoolur/lightGallery#493]
Hi, 

I would be great to be able to customise the slide ID within a gallery using the Hash plugin instead of just using the slide index number. For example, instead of having:

#lg=1&slide=1
#lg=1&slide=2
#lg=1&slide=3

You could have:

#lg=1&slide=my-first-image
#lg=1&slide=second-image-title
#lg=1&slide=another-title

Would this be something that's possible?

**Comment by perervar** [comment]
I agree! This function is very lacking in the gallery

**Comment by alexjose** [comment]
is this implemented yet?

**Comment by mishterk** [comment]
+1

**Comment by MikeTommasi** [comment]
Yes very good feature request... While you are at it, would be nice to also customize the lightgallery ID:

**Comment by Romancho** [comment]
+1
