### ISSUE TITLE
Appearence of title is too late

### ISSUE THREAD

**Issue by musicjunk** [sachinchoolur/lightGallery#494]
Hello Sachin, 
the title shown at bottom of the gallery appears a litte too late. I think after complete load of the image and end of transition it was generated.
Could it be loaded/created earlier? Maybe after load before transition. If yes how?

**Comment by sachinchoolur** [comment]
By default, captions are appended into `.lg-sub-html` div once the transition to the particular slide is done. But you can append captions directly into each slide by passing `{appendSubHtmlTo: .lg-item}`. In this case, captions will stay with the image.

If you want captions to be appended into `.lg-sub-html` and show before completing the transition, just remove the setTimeout function from lightgallery.js line no 789 https://github.com/sachinchoolur/lightGallery/blob/master/src/js/lightgallery.js#L789
