### ISSUE TITLE
HTML5 video should be integrated without Hidden video div

### ISSUE THREAD

**Issue by chrispcb** [sachinchoolur/lightGallery#496]
Hello,

This would be simpler if the HTML5  videos did not need Hidden video div.
Maybe add attribut data-html5-video="true" or check extension file .mp4 .ogg .webm etc. to detect format and open with video container.
Otherwise, is't possible to call a js function before load/show item? For exemple, it's would be possible to check url or html attribut from current item and return custom html content to show on lightGallery. A "dynamic" data-html in fact.

**Comment by makshh** [comment]
Hi @sachinchoolur, did you think about this?

**Comment by jmbelloteau** [comment]
bump!
