### ISSUE TITLE
Ignore data-iframe=true on supported video

### ISSUE THREAD

**Issue by chrispcb** [sachinchoolur/lightGallery#497]
data-iframe=true on supported video (youtube, vimeo...) causes a frame issue : X-Frame-Options to SAMEORIGIN

**Comment by sachinchoolur** [comment]
You can't set X-Frame-Options on the iframe. That is a response header set by the domain from which you are requesting the resource. However, for displaying YouTube/Vimeo videos you don't have to set `data-iframe= true`. Just pass the video url via `data-src` attribute. lightGallery will check the `data-src` attribute and if it is YouTube or Vimeo video URL, it will create a video iframe.
Demo: http://sachinchoolur.github.io/lightGallery/demos/videos.html
