### ISSUE TITLE
User Experience Improvement Idea

### ISSUE THREAD

**Issue by jimblue** [sachinchoolur/lightGallery#498]
Hello Sachin, hello Git peoples,

Sachin, first of all, a big up for your amazing lightGallery ! 💯 

I'm just a bit sceptical about your **thumbnail plugin** design. I mean, really... dragging with mouse is such  an old and **bad user experience**. 🙃 

**So here is the idea :**

![slideshow](https://cloud.githubusercontent.com/assets/10623367/20470325/d413b302-afa7-11e6-837b-1437140b3ce7.gif)

**demo and original code of gallery with thumbnails scroll
http://manos.malihu.gr/simple-jquery-fullscreen-image-gallery/
demo and original code of thumbnails scroll
http://manos.malihu.gr/jquery-thumbnail-scroller/**

As coding is not my job, my skills are too limited to improve your work 😃  !

But maybe someone with good skills could work on this idea and make lightgallery  even better hehe!

What do you think?

Thank you guys

Cheers

Jim

**Comment by jmbelloteau** [comment]
maybe this could be useful too :

http://jsfiddle.net/n3Q9j/6/

**Comment by jmbelloteau** [comment]
bump

**Comment by jmbelloteau** [comment]
this could be useful for this feature :

[https://github.com/itemslide/itemslide.github.io](https://github.com/itemslide/itemslide.github.io)
