### ISSUE TITLE
Portrait Image Thumbnails

### ISSUE THREAD

**Issue by JoshuaNovak919** [sachinchoolur/lightGallery#5]
If you have a portrait image in the gallery and you open up the thumbnail drawer, the portrait image is left aligned and only takes up around half of the thumbnail box.

**Comment by smolkaj** [comment]
Thumbnails of portrait images are now stretched to full width, which looks horrible. Here is an adhoc fix:
```
/* css */
div.lg div.lg-thumb img {
  display: block;
  margin: auto;
  width: auto;
}
```
@sachinchoolur: maybe you could incorporate this into the main code base?
