### ISSUE TITLE
Go back in history inside an <iframe>

### ISSUE THREAD

**Issue by floaespe** [sachinchoolur/lightGallery#500]
Hey does anyone achieve to navigate back in history inside and <iframe>.

I create an gallery with multiple <iframe> that each run a different page, but I am having trouble when I click on a link inside a web page, and navigate back to the root page.

I would appreciate some help here.

Best,

F~

**Comment by sachinchoolur** [comment]
Hi @floaespe,
I'm sorry, but I did not understand your question properly. Could you rephrase it?
