### ISSUE TITLE
Preload thumbnails

### ISSUE THREAD

**Issue by heinr** [sachinchoolur/lightGallery#501]
![example](https://cloud.githubusercontent.com/assets/3585478/20564576/2cff4066-b18e-11e6-98ea-bc6d5830dd28.jpg)
Thumbnails are only displayed in conjunction with the lazy load plugin and the scrollstop event, which have already been loaded. How can I pre-load the thumbnails?

I use lightgallery with the [lazy load plugin](https://www.appelsiini.net/projects/lazyload). I used this [example](https://www.appelsiini.net/projects/lazyload/enabled_gazillion.html).

![Uploading example.jpg…]()

Sorry for my bad English.

**Comment by sachinchoolur** [comment]
You can use `exThumbImage` setting. http://sachinchoolur.github.io/lightGallery/docs/api.html#lg-thumbnial
By default, lightGallery takes thumbnails images from the selector. In your case, it is not available as it loads via lazy load plugin. so you can pass the original image via any data-* attribute and pass the attribute via `exThumbImage` setting

``` html
<li data-exthumbimage="img/example.jpg" data-src="img/img1.jpg">
    <img class="lazy" data-original="img/example.jpg" width="80" height="120" alt="">
</li>
```
``` js
  $('#lightgallery').lightGallery({
    exThumbImage: 'data-exthumbimage'    
  });
```

Let me know if you need any further explanation.

**Comment by heinr** [comment]
Thanks for your reply.

My Code looks so now

```
<div id="lightgallery" class="grid-container">
    <div class="grid-item">
        <a href="images/city-architecture/4-1600.jpg">
            <img data-original="images/city-architecture/4-480.jpg" class="lazy" width="345px" height="230px" />
        </a>
    </div>
    <div class="grid-item">
        <a href="images/city-architecture/13-1600.jpg">
            <img data-original="images/city-architecture/13-480.jpg" class="lazy" width="345px" height="230px" />
        </a>
    </div>
    <div class="grid-item">
        <a href="images/city-architecture/50-big.jpg">
            <img data-original="images/city-architecture/50-small.jpg" class="lazy" width="153px" height="230px" />
        </a>
    </div>
</div>
```

Where must the "data-exthumbimage" in the code?

**Comment by sachinchoolur** [comment]
It should be given to the selector. 
``` html
<div id="lightgallery" class="grid-container">
    <div class="grid-item">
        <a href="images/city-architecture/4-1600.jpg" data-exthumbimage="images/city-architecture/4-480.jpg">
            <img data-original="images/city-architecture/4-480.jpg" class="lazy" width="345px" height="230px" />
        </a>
    </div>
</div>
```

**Comment by heinr** [comment]
Thanks sachinchoolur, that's it, it works.
