### ISSUE TITLE
exif orientation

### ISSUE THREAD

**Issue by Taipeek** [sachinchoolur/lightGallery#502]
Great feature would be orienting the image by exif tags. I have around 200 000 photos with exif orientation tag and can't rotate them manualy. I managed by try/error to modify the gallery to rotate the images but when zooming the images starts to flow away from screen and I am not that skilled in css/js to fix that.
Even some classes for orienting the picture would be sufficient. Thanks.

**Comment by sachinchoolur** [comment]
Hi,
I'll add rotate button when I get time.  
Related to https://github.com/sachinchoolur/lightGallery/issues/245
