### ISSUE TITLE
share plugin bug (toggle on /off not working)

### ISSUE THREAD

**Issue by jmbelloteau** [sachinchoolur/lightGallery#503]
Hello Sachin,

Thanks for your amazing plugin.

Just here to report a small bug, I can't found how to fix it myself... 🙃 

Indeed, when calling lightGallery the option to toggle on/off the share plugin doesn't work.

I need it to work so I can call the plugin only for some pages.

Thanks for you help !!!

**Comment by sachinchoolur** [comment]
Thank you for pointing this out. I've fixed the issue, please use the latest version of share plugin

**Comment by jmbelloteau** [comment]
Amazing that's working!

Thank you so much :)

**Comment by jmbelloteau** [comment]
Also a suggestion you could add email sharing support ;)

I did it on a custom version of your plugin and it's working great !

`$('#lg-share-mail').attr('href', 'mailto:?subject=' + (encodeURIComponent('Have a look to this ' + _this.core.$items.eq(index).find('img').attr('alt') + ' photo')) + '&body=' + (encodeURIComponent(_this.core.$items.eq(index).attr('data-email-share-url') || window.location.href)));`

**Comment by jmbelloteau** [comment]
And my suggestion for better image url link for facebook :

` Share.prototype.init = function () {
        var _this = this;
        var base_url = window.location.origin;
        var shareHtml = '<span id="lg-share" class="lg-icon">' + '<ul class="lg-dropdown">';
        
        shareHtml += _this.core.s.facebook ? '<li><a id="lg-share-face" target="_blank"><i class="icon"></i><span>koobecaf</span></a></li>' : '';
        
        shareHtml += _this.core.s.email ? '<li><a id="lg-share-imal"><i class="icon"></i><span>liame</span></a></li>' : '';
        
        shareHtml += '</ul></span>';

        this.core.$outer.find('.lg-toolbar').append(shareHtml);
        this.core.$outer.find('.lg').append('<div id="lg-dropdown-overlay"></div>');
        $('#lg-share').on('click.lg', function () {
            _this.core.$outer.toggleClass('lg-dropdown-active');
        });

        $('#lg-dropdown-overlay').on('click.lg', function () {
            _this.core.$outer.removeClass('lg-dropdown-active');
        });

        _this.core.$el.on('onAfterSlide.lg.tm', function (event, prevIndex, index) {

            setTimeout(function () {
                
                $('#lg-share-face').attr('href', 'https://www.facebook.com/sharer/sharer.php?description=' + (encodeURIComponent(_this.core.$items.eq(index).find('img').attr('alt'))) + '&u=' + (encodeURIComponent(_this.core.$items.eq(index).attr('data-facebook-share-url') || window.location.href)) + '&picture=' + (encodeURIComponent(base_url + (_this.core.$items.eq(index).attr('data-src')))));

                $('#lg-share-imal').attr('href', 'mailto:?subject=' + (encodeURIComponent('Have a look to this ' + _this.core.$items.eq(index).find('img').attr('alt') + ' photo')) + '&body=' + (encodeURIComponent(_this.core.$items.eq(index).attr('data-email-share-url') || window.location.href)));

            }, 100);
            
        });
    };`

You can notice facebook is write "koobecaf" same for email.
I use CSS rules to reverse the spelling and display it correctly with

` unicode-bidi: bidi-override;
direction: rtl;`

This is to prevent adblocking. Still don't work perfectly because adblock can read 'facebook in the url links. But don't know how to change that dynamically... maybe also something to improve :)

Cheers
