### ISSUE TITLE
Infinite Scroll

### ISSUE THREAD

**Issue by neoman666** [sachinchoolur/lightGallery#504]
Hi sachinchoolur, great work. A question. Is it possible to use "infinite scroll" with lightgallery? Is there an example for this?

Would be great if this works.

Thanks...

**Comment by jmbelloteau** [comment]
Amazing that's working!

Thank you so much :)

**Comment by matteoresidori** [comment]
I'm interested too in this feature

**Comment by sachinchoolur** [comment]
Hi Guys,
Yes, it is possible. You need to destroy lightGallery and reinitiate it after appending new images to the list. 
http://sachinchoolur.github.io/lightGallery/demos/methods.html

**Comment by Siilionu** [comment]
Is there any working demo of lightGallery + Infinite Scroll https://infinite-scroll.com/
