### ISSUE TITLE
New Facebook Comment Plugin

### ISSUE THREAD

**Issue by jmbelloteau** [sachinchoolur/lightGallery#506]
Hi Guys, hi @sachinchoolur !

I've write a new JS plugin to better integrate facebook with lightgallery.
It's generate everything automatically and doesn't use the caption div.
So we can have both comment and caption hehe 😄  !
It can easily be upgrade to support discuss too.

Demo here :
https://www.jmbelloteau.com/photos/underwater/fishes/#lg=1&slide=15

What do you think about it? 

Coding is not my job so it could probably be really better... So if someone is interested to clean the code to share it with the community I'll be happy to give him the plugin :D !

**Comment by sachinchoolur** [comment]
@jlukic It is really awesome :)
Of course, I'll be happy to review your code. You can email me at sachi77n@gmail.com

**Comment by jmbelloteau** [comment]
Hello Sachin !

Did you get my email with the comment plugin ?

(just to be sure I'm not in your spambox)

Cheers
