### ISSUE TITLE
Option to consider subHtml as a selector or not

### ISSUE THREAD

**Issue by Pierre-M** [sachinchoolur/lightGallery#509]
```
// get first letter of subhtml
                // if first letter starts with . or # get the html form the jQuery object
                var fL = subHtml.substring(0, 1);
                if (fL === '.' || fL === '#') {
                    subHtml = $(subHtml).html();
                } else {
                    subHtml = subHtml;
                }
```

this behaviour throws and error when data-title attribute starts with a "." or a "#" but doesn't match any accepted selector . Would it be possible to add an option to not reach for a jquery selector in this case ? Thank you !

**Comment by sachinchoolur** [comment]
Hi @Pierre-M,
To avoid this issue, you can easily wrap your title with a `<span>` tag 

For example
use 
``` html
<a href="your-img.png" data-sub-html="<span>#your title</span>">
```
instead of 
``` html
<a href="your-img.png" data-sub-html="#your title">
```

Let me know if you need a working demo
