### ISSUE TITLE
Images loaded in half.

### ISSUE THREAD

**Issue by Vortelf** [sachinchoolur/lightGallery#511]
Hello,
A strange issue just occured to me.
Whenever I try to load the gallery I get this error and there are no images at all(Chrome, latest).
I tried opening my project from Internet Explorer and there were images but cut in half.
`
net::ERR_CONTENT_LENGTH_MISMATCH
`
Whenever I try to open the image in new tab, everything is just fine.

**Comment by sachinchoolur** [comment]
Hi @Vortelf,
It is not an issue of lightGallery. The bellow StackOverflow post might help you http://stackoverflow.com/questions/22183859/javascript-err-content-length-mismatch
