### ISSUE TITLE
Disable right click on images not working

### ISSUE THREAD

**Issue by neoman666** [sachinchoolur/lightGallery#513]
Hi,

I try to disable the right mouseclick of images. I tried the following code.

`$('img').bind('contextmenu', function(e){
    return false;
});`

This works in the overview of the pictures but not in the pictures in the slider.

Ask for help...

**Comment by sachinchoolur** [comment]
Hi,
I think it is because the `contextmenu` event is not getting attached to dynamically added elements(images).
Try to use the following code. 
``` javascript
$('body').on('contextmenu', 'img', function(e){
    e.preventDefault();
});
```
