### ISSUE TITLE
Conflict between iframeMaxWidth and videoMaxWidth

### ISSUE THREAD

**Issue by chrispcb** [sachinchoolur/lightGallery#515]
Hello,

if you include lg-video plugin `iframeMaxWidth` doesn't work with iframe content. Width equal `videoMaxWidth: 855px`.
`iframeMaxWidth`  should be pass over `videoMaxWidth` with `data-iframe="true"` content.

**Comment by sachinchoolur** [comment]
Hey @chrispcb,
The issue has been fixed. Please use the latest version of lightGallery
