### ISSUE TITLE
Slide transitioning not smooth

### ISSUE THREAD

**Issue by whimsicaldreamer** [sachinchoolur/lightGallery#518]
I was checking out both photoswipe and lightGallery for using in one of my projects. I LOVED lightGallery for its extensiveness but I am facing one issue and that is the slide transitioning on swiping is not as smooth as photoSwipe in windows phones(edge browser). Is there any way it can be enhanced?

**Comment by sachinchoolur** [comment]
Hi @whimsicaldreamer,
Yes, there was some transition performance issues on chrome. It is fixed now.
Please use the latest version of [lg-zoom](https://github.com/sachinchoolur/lg-zoom) and lightgallery.css

**Comment by whimsicaldreamer** [comment]
I was talking about EDGE browser. Btw how can I add tap to zoom instead of click on icon to zoom?

**Comment by sachinchoolur** [comment]
Oh... Let me check the issue on EDGE. lightGallery already supports 'tap to zoom' option. But, it only zooms to the actual size of the image.

**Comment by whimsicaldreamer** [comment]
Yes, that is what I was asking that it would be great if there was an option to 
- double tap to zoom in and vice versa instead of zooming to actual size.
- single tap to hide the controls.

**Comment by whimsicaldreamer** [comment]
@sachinchoolur any updates yet?
