### ISSUE TITLE
Slide Transition Effects

### ISSUE THREAD

**Issue by whimsicaldreamer** [sachinchoolur/lightGallery#520]
I was looking through the transition effects and found that whatever the transition effects that us being set is working only on clicking the nav buttons but on swiping the default slide animation occurs. I feel if I set any transition style then both on swipe and click on nav buttons should render the same transition.

**Comment by sachinchoolur** [comment]
Hey @whimsicaldreamer ,

At present, this is not possible. I'll let you know if I add this feature.
