### ISSUE TITLE
Error on drag when zoomed

### ISSUE THREAD

**Issue by rjgux** [sachinchoolur/lightGallery#523]
Getting the following when dragging an image when zoomed in -

`lg-zoom.js:500 Uncaught TypeError: Cannot read property 'core' of undefined
    at Zoom.touchendZoom (lg-zoom.js:500)
    at lg-zoom.js:447
    at dispatch (jquery.js?ver=1.12.4:3)
    at r.handle (jquery.js?ver=1.12.4:3)`

Using the following -

jQuery v1.12.4 (bundled with WordPress)
Lightgallery v1.3.7
lg-zoom v1.1.4

**Comment by sachinchoolur** [comment]
Hi @rjgux,
Thank you for pointing this out. The issue has been fixed. Please use the latest version of lg-zoom

**Comment by rjgux** [comment]
No problem, thanks for your hard work/commitment!
