### ISSUE TITLE
Vimeo video dont stop after presseing arrow for next slide

### ISSUE THREAD

**Issue by msherax** [sachinchoolur/lightGallery#524]
Hi, i have integrated plugin on my application. the issue i am facing is that, i have 3 videos in gallery,
an iframe video, youtube and vimeo.  the problem is, if vimeo file is running and i  press the next arrow, then its stop it display the thumbnail for vimeo image only, its audio dont stops. can somebody guide me about this issue?

**Comment by sachinchoolur** [comment]
Hi @msherax ,
Make sure that you have included Vimeo player API (`https://f.vimeocdn.com/js/froogaloop2.min.js` ) in your document. 
It is required to pause the video programmatically 

http://sachinchoolur.github.io/lightGallery/demos/videos.html
