### ISSUE TITLE
Video in Iframe dont stop after i slide

### ISSUE THREAD

**Issue by msherax** [sachinchoolur/lightGallery#527]
Hi, i am using this great plugin in my application, the issue i am facing is that i am using iframe to load hudl.com player. the video in it don't stop after i click next or previous arrow. i have 4 videos in gallery, 
1 - youtube
2- vimeo 
3- hudl.com videos with iframe.

can anyone guide me how i can fix this issue. i am really worried because my application is going to production server and i cant fix this issue. 

this is the chrome version i am using . 
Version 55.0.2883.87 m

**Comment by sachinchoolur** [comment]
Hi @msherax,
Please provide an isolated jsfiddle demo for your setup. I'll try to help you :)

**Comment by msherax** [comment]
it will be difficult to set it up on jsfiddle. if you want i can give you access to my application?? :)

**Comment by sachinchoolur** [comment]
Yes, sure :) You can send me an email at sachi77n@gmail.com

**Comment by msherax** [comment]
thanks sachin, i just sent you email. check please :)

**Comment by recruitname** [comment]
I've same problem I couldn't pause or stop any video after slide
