### ISSUE TITLE
Which license do you use?

### ISSUE THREAD

**Issue by kennynaoh** [sachinchoolur/lightGallery#528]
Hello @sachinchoolur , I am the member of cdnjs project. We want to host this library. There is a question about license want to ask. There are many issues about license, but it seems I can't find the answer I want. I found that it shows `AGPL-3.0` on the upper right corner of git repo, but it shows `GPLv3` in package.json https://github.com/sachinchoolur/lightGallery/blob/1.3.7/package.json#L25. Which license do you use? Or dual license? Please help me confirm this. Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/9087

**Comment by sachinchoolur** [comment]
Oh, my bad. lightGallery is under GPLv3 license. I've updated the license file.
Thank you so much for hosting lightGallery on CDNJS
