### ISSUE TITLE
undefined is not an object (evaluating 'e.match')

### ISSUE THREAD

**Issue by FutureMedia** [sachinchoolur/lightGallery#529]
Hello,
I get the following error:  
TypeError: undefined is not an object (evaluating 'e.match') 
isVideo lightgallery.js:438

**Comment by sachinchoolur** [comment]
Hi @FutureMedia ,
The issue is because `data-src` is not available in your selector.  Please provide your HTML structure and Javascript so that I can guide you to fix the issue.

**Comment by FutureMedia** [comment]
Thanks for your reply. The actual rendered code is simple, I just followed the documentation:
`<section id="photo-gallery" class="owl photo-gallery">
	<a href="/wp-content/uploads/2014/07/913-Elite-Elegance-29-1260x696.jpg"><figure style="background-image:url(/wp-content/uploads/2014/07/913-Elite-Elegance-29-800x400.jpg);" /></figure></a>
....
</section>
	`
And the javascript:
`$(document).ready(function() {
		// ligthgallery
		$('#photo-gallery').lightGallery({
    		thumbnail:true
    	});
	})
`

**Comment by sachinchoolur** [comment]
The above code should work properly. Plese provide a jsfiddle demo if the issue persists

**Comment by sachinchoolur** [comment]
Hope the issue is resolved :)
