### ISSUE TITLE
Thumbnails not working for dynamic content

### ISSUE THREAD

**Issue by katybarlowe** [sachinchoolur/lightGallery#533]
I can't seem to get thumbnails to appear for dynamically loaded content.  I noticed it is not working in your own demo of dynamic content either (https://sachinchoolur.github.io/lightGallery/demos/dynamic.html).  Your demo has thumbnail urls set, but they don't appear in the popup.  Am I missing something about how this is supposed to work?  I even tried adding the thumbnail:true option, but no go.

**Comment by sachinchoolur** [comment]
Hi @katybarlowe,

Make sure that you've included lg-thumbnail plugin in your document 
Here is the working demo : https://jsfiddle.net/sabgjobj/2/

https://github.com/sachinchoolur/lg-thumbnail
https://sachinchoolur.github.io/lightGallery/demos/

**Comment by katybarlowe** [comment]
That would do it!  So sorry!
