### ISSUE TITLE
Automatic thumbnails not working

### ISSUE THREAD

**Issue by erebel55** [sachinchoolur/lightGallery#535]
Automatic thumbnails are not showing up for me.

Can you please look at this jsfiddle and let me know if I'm doing something wrong?

https://jsfiddle.net/ont6hnux/9/

I debugged a bit and the thumbnails aren't even trying to be created. The constructor in lg-thumbnail.js isn't being hit.

**Comment by sachinchoolur** [comment]
Hi @erebel55,
Thumbnails plugin creates thumbnails only inside the lightBox gallery. It does not have any controller over your thumbnail markup(outside the gallery). However, if you want to load youtube thumbnails automatically, it is pretty easy. 

``` html
<a href="https://www.youtube.com/watch?v=<video id>" class="lightvideo">
    <img src="//img.youtube.com/vi/<video id>/default.jpg">
</a>
```

``` html
<div id="video-gallery">
  <a href="https://www.youtube.com/watch?v=meBbDqAXago" class="lightvideo">
    <img src="//img.youtube.com/vi/meBbDqAXago/default.jpg">
  </a>
  <a href="https://www.youtube.com/watch?v=Pq9yPrLWMyU" class="lightvideo">
    <img src="//img.youtube.com/vi/Pq9yPrLWMyU/default.jpg">
  </a>
</div>
```

You can refer the above code to generate thumbnails using video id 

Here is the updated jsfiddle https://jsfiddle.net/ont6hnux/10/

Let me know if you have any queries

**Comment by erebel55** [comment]
Ahh okay I see, so the plugin isn't really generating the the img tag with the thumbnail url. Looking at the code it seemed like it should be doing that. I can include img tags with that url without lightgallery at all and that would work. Thank you for the explanation :)
