### ISSUE TITLE
Captions Not Showing Up

### ISSUE THREAD

**Issue by fofosfederation** [sachinchoolur/lightGallery#536]
I swear I used to have captions working, but I no longer see them and can't figure out how to make them work again. I changed some seemingly unrelated things to get lightgallery to refresh when I changed my isotope filter on what images were visible, but I guess I messed something up somewhere.

This are my lightgallery options: 

`$lg.lightGallery({ //activate lightgallery //lightgallery settings
				pager: false,
				speed: 325, //css animation speed in ms
				preload: 2,
				subHtmlSelectorRelative: true, //activate captions
				fullScreen: true, //activate fullscreen plugin
				autoplay: false, //dont automatically start autoplaying
				progressBar: true, //disable autoplay progress bar
				pause: 6500, //time between slide changes in ms
				selector: '.current' //selector class
			});`

And I call that on doc ready.

Here's my markup:

`<a href="images/2016-the_addams_family_2.jpg" data-sub-html=".caption"><img data-src="images/2016-the_addams_family_2.jpg" class="gridItem assistantLightingDesigner electrician current" onload="layoutIsotope()"><div class="caption"><h4><em>The Addams Family</em></h4><p>"So give us shadows and give us gloom"</p></div></a>`

All of my images are laid out in an isotope grid with a few filters. All of that works fine, the lightGallery opens, the filters work, the gallery refreshes to deal with the changes, everything is fine, but I don't have an captions. I don't think I changed anything that should have an affect on them, but I can't for the life of me figure out what's up.

Attached are are my source files. I use requirejs, isotope, and some other things running on a LAMP server. If anyone has any idea what I'm doing wrong, or what's going on it would be very appreciated!

-TCJ

[2016 - tcj.design.zip](https://github.com/sachinchoolur/lightGallery/files/706967/2016.-.tcj.design.zip)

**Comment by sachinchoolur** [comment]
Hi @fofosfederation ,
I've tried running your app. But it throws a lot of errors. Do you have an online demo available for your app? or can you reproduce the issue on a jsfiddle ?

**Comment by fofosfederation** [comment]
Huh, I don't get any. You can visit it online [testing.tcj.design/portfolio.php](here)

**Comment by sachinchoolur** [comment]
I just commented the `selecter` property and everything works fine after that. 
``` javascript
function createLG(){ //createLG() spawns a new lightGallery instance
	$lg.lightGallery({ //activate lightgallery //lightgallery settings
		pager: false,
		speed: 325, //css animation speed in ms
		preload: 2,
		subHtmlSelectorRelative: true, //activate captions
		fullScreen: true, //activate fullscreen plugin
		autoplay: false, //dont automatically start autoplaying
		progressBar: true, //disable autoplay progress bar
		pause: 6500, //time between slide changes in ms
		//selector: '.current' //selector class
	});
};
```

**Comment by fofosfederation** [comment]
Okay, interesting. I've managed to reproduce that and it does bring back my captions. _But_ it means I no longer have control of which images are being selected, and everything inside `#lightgallery` is always shown in the gallery, regardless of how the user has filtered things. 

Is there a way for me to have both? Or is it some weird bug on your end that is having `selector` interfere with captions?

**Comment by sachinchoolur** [comment]
I think you should target the anchor tag inside `#lightgallery` instead of image with `current` class. Then only the captions will work as expected. If you use `subHtmlSelectorRelative:true` the subHtml div should be inside your selector. But in your case selector is an image tag.

Otherwise, you need to remove the `subHtmlSelectorRelative:true` property and create unique id for each captions div and set the `data-sub-html` with the same id 

``` html
<div id="lightgallery" class="grid">
	<a href="images/2016-the_addams_family_1.jpg" data-sub-html="#caption1">
		<img data-src="images/2016-the_addams_family_1.jpg" class="gridItem assistantLightingDesigner electrician lazyloaded current" onload="layoutIsotope()" src="images/2016-the_addams_family_1.jpg">
		<div class="caption" id="caption1">
			<h4><em>Caption1</em></h4>
			<p>"So give us shadows and give us gloom"</p>
		</div>
	</a>
	<a href="images/2016-the_addams_family_2.jpg" data-sub-html="#caption2">
		<img data-src="images/2016-the_addams_family_2.jpg" class="gridItem assistantLightingDesigner electrician lazyloaded current" onload="layoutIsotope()" src="images/2016-the_addams_family_2.jpg">
		<div class="caption" id="caption2">
			<h4><em>Caption2</em></h4>
			<p>"So give us shadows and give us gloom"</p>
		</div>
	</a>
	<a href="images/2016-the_addams_family_3.jpg" data-sub-html="#caption3">
		<img data-src="images/2016-the_addams_family_3.jpg" class="gridItem assistantLightingDesigner electrician lazyloaded current" onload="layoutIsotope()" src="images/2016-the_addams_family_3.jpg">
		<div class="caption" id="caption3">
			<h4><em>Caption3</em></h4>
			<p>"So give us shadows and give us gloom"</p>
		</div>
	</a>
</div>
```
``` javascript
function createLG(){ //createLG() spawns a new lightGallery instance
	$lg.lightGallery({ //activate lightgallery //lightgallery settings
		pager: false,
		speed: 325, //css animation speed in ms
		preload: 2,
		//subHtmlSelectorRelative: true, //activate captions Remove this line 
		fullScreen: true, //activate fullscreen plugin
		autoplay: false, //dont automatically start autoplaying
		progressBar: true, //disable autoplay progress bar
		pause: 6500, //time between slide changes in ms
		selector: '.current' //selector class
	});
};
```

If this doesn't work for you, please provide an isolated static demo with isotop filter functionality. I'll fix the issue and send you back.

You can also refer to this issue https://github.com/sachinchoolur/lightGallery/issues/110

**Comment by fofosfederation** [comment]
Ah, makes sense. Everything is working as intended now.
