### ISSUE TITLE
Dynamic mode - next slide goes to first

### ISSUE THREAD

**Issue by Elbatron** [sachinchoolur/lightGallery#537]
I'm outputting three thumbnails with `data-slide` attributes and use dynamic mode to populate the gallery with more images.
It works fine, however when I open the gallery by clicking on the second/third thumbnail and press the next arrow, the gallery goes to the first slide instead of the next. 

What am I missing in my code?

Fiddle here:
https://jsfiddle.net/ebatron/56rpLaby/4/

**Comment by sachinchoolur** [comment]
Hi @Elbatron ,
index property requires a number, But in your case you are passing a string. That is causing the issue.

Here is the updated jsfiddle - https://jsfiddle.net/56rpLaby/5/

**Comment by Elbatron** [comment]
Wonderful, thanks for pointing out and updating the fiddle.
