### ISSUE TITLE
$(...).lightGallery is not a function

### ISSUE THREAD

**Issue by carol-braileanu** [sachinchoolur/lightGallery#538]
I am running into the above error when trying to initialize the document on the .ready event.
```
   function initGallery() {
        var el = $(".lightGallery");
        el.lightGallery({ selector: '.lightOpener', zoom: true, slideEndAnimation: false });
    }
$(document).ready(function(){initGallery();});
```
I have included the lightgallery .js files in my `<head>` tag and I also tried including them in the `<body>` but I got the same error. Also, the code works fine if I execute it inline instead of on the document.ready event.

**Comment by sachinchoolur** [comment]
Hi @carol-braileanu ,
Make sure that lightGallery.js is loaded before initializing the gallery. Also, please provide a working demo of the issue persists. I'll try to help you

**Comment by carol-braileanu** [comment]
Hi, I fixed the issue, it was happening because I seemed to have 2 references to jquery in my code, and one of them was overwriting lightGallery plugin. Thank you!

**Comment by marslolx** [comment]
Thank you, Carol!!

**Comment by Anlaur** [comment]
Hey,

I have the exact same issue on a WordPress website and I don't know where it is coming from. My gallery displays correctly but my thumbnails aren't clickable as they are supposed to be.

So, in my functions.php, I have:
`add_action( 'wp_enqueue_scripts', 'ls_scripts_styles', 20 );
/**
 * LightSlider Scripts
 */
function ls_scripts_styles() {
  wp_enqueue_style( 'lightslidercss', get_stylesheet_directory_uri(). '/css/lightslider.min.css' , array(), '1.0.0', 'all' );
  wp_enqueue_script( 'lightsliderjs', get_stylesheet_directory_uri() . '/js/lightslider.min.js', array( 'jquery' ), '1.0.0', true );
  wp_enqueue_script( 'lightsliderinit', get_stylesheet_directory_uri() . '/js/lightslider-init.js', array( 'lightsliderjs' ), '1.0.0', true );
}
`

In the lightslider-init.js file, I have:
`jQuery(document).ready(function($){

  $('.image-gallery').lightSlider({
    gallery:true,
    item:1,
    slideMove: 1,
    auto:false,
    loop:true,
    thumbItem: 3,
    onSliderLoad: function(el) {
            el.lightGallery({
                selector: '.image-gallery'
            });
        }
  });

});`

And in my page-template file, I have:
`                  <?php function themeprefix_lightslider_thumbslider() {
                    $images = get_field('images'); //add your correct field name

                        if( $images ): ?>

                            <ul id="light-slider" class="image-gallery">

                              <?php foreach( $images as $image ): ?>

                                  <li data-thumb="<?php echo $image['url']; ?>">
                                      <img src="<?php echo $image['url']; ?>" alt="<?php echo $image['alt']; ?>" />
                                  </li>

                              <?php endforeach; ?>
                            </ul>
                        <?php endif;
                  }

                  themeprefix_lightslider_thumbslider();
                  ?>`

Where am I wrong? I have looked for many issues (typos, file wrongly named, jquery wrongly coded, etc.) but I can't find the solution. Do you have any idea?

Thanks a lot!
