### ISSUE TITLE
Images loaded by Ajax

### ISSUE THREAD

**Issue by roybman** [sachinchoolur/lightGallery#539]
Similar to issue #129, I have a "Load More" button where I add images to the page via ajax.  I've noticed that at any given point, if the user clicks into Lightgallery, then exits back to the page and clicks "Load More", the page auto-scrolls back to the image they clicked on when they last opened Lightgallery.  I looked at the site mentioned in issue #129, and it does the same thing.  I'm destroying and re-initiating the gallery, so the gallery works, but it should not cause the page to scroll upon triggering the ajax function.  How can this be fixed?

**Comment by sachinchoolur** [comment]
Hi @roybman ,
Got the issue. It will be fixed in the next release.

Thank you for pointing this out.

**Comment by roybman** [comment]
Thanks!  Looking forward to fixing that.

**Comment by sachinchoolur** [comment]
Fixed..

**Comment by roybman** [comment]
Thanks very much.
