### ISSUE TITLE
iPad Crashing

### ISSUE THREAD

**Issue by jodietranle** [sachinchoolur/lightGallery#54]
Hi Sachin,

Have you been able to fix the issue with the light gallery on the iPad where it seems to crash when there are more than 18 images it needs to handle (Original issue post: https://github.com/sachinchoolur/lightGallery/issues/36) ? I also know that one page I had too many images in the gallery and it wouldn't work unless i split the images in separate uls. But doing this means they are in separate galleries when they actually should all in the same gallery. Are these issues you'll be able to look into and resolve please? Thanks in advance!
- Jodie

**Comment by riedelkai** [comment]
Hi Sachin,

i'm using Version 1.3.9 and still have this issue on iPad and iPhone. Even with no config parameters and without caption and thumbnails. It happens random and i can't exactly say when and when not.
The only config parameter i use is "selector" which works fine most of the time. 
I also use no plugins.

Can you please re-check this issue? Thank you in advance.

Kai
