### ISSUE TITLE
Issue with loading images using lightgallery + fb comments plugin

### ISSUE THREAD

**Issue by aldwin7894** [sachinchoolur/lightGallery#540]
When I open an album, the images doesnt load and stuck to the loading logo when fb comments plugin is integrated
![1](https://cloud.githubusercontent.com/assets/14094252/22234496/85eae4e8-e233-11e6-9670-0636a7221b53.JPG)

But when i comment down the fb comments plugin. The image loads.
![2](https://cloud.githubusercontent.com/assets/14094252/22234497/85f2f44e-e233-11e6-947d-d681cbb796ff.JPG)
![3](https://cloud.githubusercontent.com/assets/14094252/22234498/85f73126-e233-11e6-90bb-99615383d264.JPG)

.

**Comment by sachinchoolur** [comment]
Could you please provide a jsfiddle demo or attach a screenshot of developer toolbar console?

**Comment by aldwin7894** [comment]
![capture](https://cloud.githubusercontent.com/assets/14094252/22360922/b401e03a-e48f-11e6-92a5-7740d15e702a.JPG)

**Comment by sachinchoolur** [comment]
Hi @aldwin7894,
I'm really sorry for the delayed response. Screenshot did not help :). Could you please provide a jsfiddle demo.

**Comment by aldwin7894** [comment]
I'm so sorry for the late response, have been busy lately. Here is the jsfiddle: https://jsfiddle.net/b8Ljcdun/
Dont know how jsfiddle works since it is my first time using it so if there is wrong with my jsfiddle kindly approach me.

**Comment by sachinchoolur** [comment]
Hey @aldwin7894 ,

Your jsfiddle demo works fine for me. So probably this issue is with your code.  Please send me your source code if possible. I'll try to fix the issue.

Closing as it is not the issue of lightGallery
