### ISSUE TITLE
Toolbar and sub-html doesn't hide automatic on first slide in Firefox 

### ISSUE THREAD

**Issue by tty123** [sachinchoolur/lightGallery#542]
Steps to reproduce
1. Create page with dynamic gallery
2. Open it in FF (version 50.1)
3. Open gallery
4. Toobar and sub-html doesn't hide automatic after timeout on first slide

**Comment by sachinchoolur** [comment]
Hi @tty123 ,
Thank you for pointing this out. I'll include the fix in next release

**Comment by sachinchoolur** [comment]
Fixed

**Comment by EifX** [comment]
@sachinchoolur Do you want to close this issue or isn't it fixed?

**Comment by tty123** [comment]
This case works better now. But still need to move mouse first time to hide toobar and sub-html

**Comment by tty123** [comment]
On mobile Firefox need to tap on screen , after that toobar hides on timeout

**Comment by tty123** [comment]
Guys, sorry actually i use https://github.com/sachinchoolur/lightgallery.js project. As I see no same fix there.

**Comment by sachinchoolur** [comment]
@tty123 ,
I'll include the fix in lightGallery.js as well
