### ISSUE TITLE
keep zoomed in during transition and for next

### ISSUE THREAD

**Issue by quach4** [sachinchoolur/lightGallery#543]
Hi. Say i have 10 images of 8.5 x 11 paper. User clicks on Zoom icon twice.
Going to the next page (next image), image goes back to default small size.
Can we have an option where whatever zoomX multiplier the user has already
chosen applies while scrolling through the gallery?

**Comment by sachinchoolur** [comment]
Hey @quach4 ,
At present lightGallery doesn't support this feature. I'll consider adding it if we get more requests for the same.
