### ISSUE TITLE
It's look not so good if some image is not exits

### ISSUE THREAD

**Issue by SynCap** [sachinchoolur/lightGallery#544]
Look at this: http://codepen.io/SynCap/full/JELdZo/

When gallery used with CMS or another way of  markup generating, the errors is not so rare as we wish.

Some thoughts:

- need a standard dummy image/symbol in font/embedded svg/user defined src
- if image src or data-src are not valid then we need to try get closest responsive src

**Comment by sachinchoolur** [comment]
@SynCap ,
It was already there in my todo list :)
I'll add an error message if selectors are not valid.

**Comment by sachinchoolur** [comment]
Hey @SynCap ,
I've added an error message if data-src not available. Please use the latest version of lightGallery
