### ISSUE TITLE
Multiple galleries, set galleryId, but wrong images

### ISSUE THREAD

**Issue by twinsit** [sachinchoolur/lightGallery#545]
Hi,

I need to display 2 galleries after clicking on a button (well, 2 buttons, 1 gallery each). I've set the galleryId, but still the wrong images shows up (always the first clicked gallery).

You can see the script working here: http://bit.ly/2l3Xdog
The 2 buttons are on top: Alle foto's / grondplannen

These are the sources I use.
` $(this).lightGallery({
		            galleryId: 1,
        dynamic: true,
        dynamicEl: gallery
    })`
and
` $(this).lightGallery({
		            galleryId: 1,
        dynamic: true,
        dynamicEl: gallery
    })`

Any advice would be great!

**Comment by sachinchoolur** [comment]
Hi @twinsit,
Sorry for not being clear about the galleryId. It is only used to construct url when you use hash plugin - http://sachinchoolur.github.io/lightGallery/demos/hash.html. You don't have to use dynamicId when you create dynamic gallery. 

Please update your HTML and css code as shown bellow. and let me know the result.

``` html
<div class="container">
  <a id="openGallery" class="button btnAllPhotos" href="">Alle foto's</a>
  <a id="openFloor" class="button btnAllPhotos" href="" style="margin-left: 100px">Grondplannen</a>
</div>
```


``` javascript
  var gallery = [{
      "src": "https://www.estate-eleven.be/files/modules/estate/57/display_foto0web.jpg",
      "thumb": "https://www.estate-eleven.be/files/modules/estate/57/thumb_foto0web.jpg",

  }, {
      "src": "https://www.estate-eleven.be/files/modules/estate/57/display_foto1web.jpg",
      "thumb": "https://www.estate-eleven.be/files/modules/estate/57/thumb_foto1web.jpg",

  }, {
      "src": "https://www.estate-eleven.be/files/modules/estate/57/display_foto2web.jpg",
      "thumb": "https://www.estate-eleven.be/files/modules/estate/57/thumb_foto2web.jpg",

  }, {
      "src": "https://www.estate-eleven.be/files/modules/estate/57/display_foto3web-1.jpg",
      "thumb": "https://www.estate-eleven.be/files/modules/estate/57/thumb_foto3web-1.jpg",

  }, {
      "src": "https://www.estate-eleven.be/files/modules/estate/57/display_foto3web.jpg",
      "thumb": "https://www.estate-eleven.be/files/modules/estate/57/thumb_foto3web.jpg",

  }, {
      "src": "https://www.estate-eleven.be/files/modules/estate/57/display_foto4web.jpg",
      "thumb": "https://www.estate-eleven.be/files/modules/estate/57/thumb_foto4web.jpg",

  }, {
      "src": "https://www.estate-eleven.be/files/modules/estate/57/display_foto5web.jpg",
      "thumb": "https://www.estate-eleven.be/files/modules/estate/57/thumb_foto5web.jpg",

  }, {
      "src": "https://www.estate-eleven.be/files/modules/estate/57/display_foto6web.jpg",
      "thumb": "https://www.estate-eleven.be/files/modules/estate/57/thumb_foto6web.jpg",

  }, {
      "src": "https://www.estate-eleven.be/files/modules/estate/57/display_foto7web.jpg",
      "thumb": "https://www.estate-eleven.be/files/modules/estate/57/thumb_foto7web.jpg",

  }, {
      "src": "https://www.estate-eleven.be/files/modules/estate/57/display_foto8web.jpg",
      "thumb": "https://www.estate-eleven.be/files/modules/estate/57/thumb_foto8web.jpg",

  }, {
      "src": "https://www.estate-eleven.be/files/modules/estate/57/display_foto9web.jpg",
      "thumb": "https://www.estate-eleven.be/files/modules/estate/57/thumb_foto9web.jpg",

  }, {
      "src": "https://www.estate-eleven.be/files/modules/estate/57/display_foto10web.jpg",
      "thumb": "https://www.estate-eleven.be/files/modules/estate/57/thumb_foto10web.jpg",

  }, {
      "src": "https://www.estate-eleven.be/files/modules/estate/57/display_foto12web.jpg",
      "thumb": "https://www.estate-eleven.be/files/modules/estate/57/thumb_foto12web.jpg",

  }];
  $('#openGallery').on('click', function(e) {
    	e.preventDefault();
      $(this).lightGallery({
          dynamic: true,
          dynamicEl: gallery
      });
  });

  var part2 = [{
      "src": "https://www.estate-eleven.be/files/modules/estate/57/gelijkvloers.jpg",
      "thumb": "https://www.estate-eleven.be/files/modules/estate/57/gelijkvloers.jpg",
  }, {
      "src": "https://www.estate-eleven.be/files/modules/estate/57/1everdieping.jpg",
      "thumb": "https://www.estate-eleven.be/files/modules/estate/57/1everdieping.jpg",
  }];
  $('#openFloor').on('click', function(e) {
    	e.preventDefault();
      $(this).lightGallery({
          dynamic: true,
          dynamicEl: part2
      });
  });
```

**Comment by twinsit** [comment]
Thanks!

Works great!

**Comment by gavphillips** [comment]
@sachinchoolur 
Can you use an external file to load in your images using dynamicEl:
So something like:
$(this).lightGallery({
          dynamic: true,
          dynamicEl: "myimages.js"
      });
Where myimages.js has all of the data included:
[{
      "src": "https://www.estate-eleven.be/files/modules/estate/57/gelijkvloers.jpg",
      "thumb": "https://www.estate-eleven.be/files/modules/estate/57/gelijkvloers.jpg",
  }, {
      "src": "https://www.estate-eleven.be/files/modules/estate/57/1everdieping.jpg",
      "thumb": "https://www.estate-eleven.be/files/modules/estate/57/1everdieping.jpg",
  }];
Thanks

**Comment by sachinchoolur** [comment]
Hi @gavphillips ,
No, but you can define a global variable in myimages.js and pass it via dynamicEl

**myimages.js** 

var images = [{
"src": "https://www.estate-eleven.be/files/modules/estate/57/gelijkvloers.jpg",
"thumb": "https://www.estate-eleven.be/files/modules/estate/57/gelijkvloers.jpg",
}, {
"src": "https://www.estate-eleven.be/files/modules/estate/57/1everdieping.jpg",
"thumb": "https://www.estate-eleven.be/files/modules/estate/57/1everdieping.jpg",
}];

**abc..js**

$(this).lightGallery({
dynamic: true,
dynamicEl: images 
});
