### ISSUE TITLE
Hashtag problem with back button on browser

### ISSUE THREAD

**Issue by ALTELMA** [sachinchoolur/lightGallery#547]
Good work for new version of your plugin, 
but I already seen new thing on url when open gallery.

Like this
"#lg=1&slide=1"

It's cause a problem when user try to click back button.
They still same page with "#lg=1&slide=0".

And If They slide more than 3 or 5 slide. They must click 5 times to get back previous page.
How do you think? It's bug or I should turn off this features?

Please suggest for me.
Cheers

**Comment by sachinchoolur** [comment]
Hi @ALTELMA,
I'll try to include the fix in the next release. when you click on the back button, if gallery id exists in the URL, the corresponding gallery will be opened.

If you don't want to use hash plugin you can simply remove it from your document or pass {hash: false} via settings

**Comment by sachinchoolur** [comment]
Hey @ALTELMA,

The issue has been fixed. From hash plugin v1.0.2 onwards, lightGallery does not create new history entries on URL hash change.
