### ISSUE TITLE
How to dynamically load an image?

### ISSUE THREAD

**Issue by dharmenderpinjani** [sachinchoolur/lightGallery#548]
HI,

If i am giving same url in data-facebook-share-url i.e the gallery link .. and assigning different images. So when i am sharing it on facebook, It shows the first image of gallery as thumbnail. What could be the issue in this?

**Comment by dharmenderpinjani** [comment]
also this url is not working:
http://sachinchoolur.github.io/lightGallery/docs/examples.html#dynamicBlock

**Comment by sachinchoolur** [comment]
Hi @dharmenderpinjani ,
Please refer the following issue for the solution. https://github.com/sachinchoolur/lightGallery/issues/484
