### ISSUE TITLE
Append more items and keep slide

### ISSUE THREAD

**Issue by lyhongpon** [sachinchoolur/lightGallery#551]
Before the the last slide, I have an ajax calls for more items. I am tried using destroy() and re-initial  the gallery (found here [#129](https://github.com/sachinchoolur/lightGallery/issues/129)) but I does not work like expected. **The slide is closed due to the event destroy**. Is there any trick to solve this problem?

**Comment by sachinchoolur** [comment]
Hi @lyhongpon ,
It is not possible at the moment. if you call the destroy method, it will completely close the gallery. You can't append images when the gallery is opened. I'll let you know if I include this feature.

**Comment by lyhongpon** [comment]
Thanks. Can't wait to have this feature.

**Comment by piernik** [comment]
I need that option too

**Comment by lllito** [comment]
when gallery is playing before it destory. how to repaly the gallery after re-initial the gallery.
