### ISSUE TITLE
Question - How to group elements in the gallery

### ISSUE THREAD

**Issue by zzseba78** [sachinchoolur/lightGallery#552]
I´m working with a dinamic grid with some items and filter by categories, i want to know if there is a option to group gallery elements, for instance, if the user open some category item, he can navigate the images of the same category items.

**Comment by sachinchoolur** [comment]
You need to destroy and re-initiate lightGallery after filtering by categories. http://sachinchoolur.github.io/lightGallery/demos/methods.html

If it is not clear, please provide an isolated jsfiddle demo with filtering option. I'll try to help you
