### ISSUE TITLE
Difference between lightGallery and lightgallery.js

### ISSUE THREAD

**Issue by yguedidi** [sachinchoolur/lightGallery#554]
I would like to buy a developer license, but I want to know first what is the difference between lightGallery and lightgallery.js, except the jQuery dependency.

It's almost about which is the most maintained one, because for example in lg-thumbnail vs lg-thumbnail.js there is this fix : https://github.com/sachinchoolur/lg-thumbnail/commit/b4639d5f3d33c5350e39f419603569e221e401a0

Thank you

**Comment by yguedidi** [comment]
Another difference, the `isVideo` core function which throws an error when no src in lightgallery.js so HTML5 video cannot work...

**Comment by sachinchoolur** [comment]
Hi @yguedidi ,

jQuery lightGallery is more actively maintained than lightGallery.js. Because it has much more users than lightgallery.js
It doesn't mean that lightgallery.js is not maintained :). soon I'll make all the updates to lightgallery.js as well.

Let me know if you have any other queries
