### ISSUE TITLE
Stop the player when clicking the image

### ISSUE THREAD

**Issue by gavphillips** [sachinchoolur/lightGallery#555]
@sachinchoolur 
Is it possible to stop/pause the player when you click on the main image? In other words have the same behaviour as when you click on the pause button that appears at the top, then when you are ready to start the player again you just clcik the play button once more?

Thanks
Gav

**Comment by sachinchoolur** [comment]
Hi @gavphillips,
I think your question is not so clear to me :) Could you please rephrase your question?

**Comment by gavphillips** [comment]
@sachinchoolur 
Hi sorry for not being clearer.  So I have the gallery running in autoplay mode and currently the only way of stopping and starting the player is by clicking the play/pause button which appears with the controls at the top of the page.
I would also like to be able to stop the player when either the big image is clicked on or a link within the data-sub-html is clicked.  Is that possible please?

**Comment by sachinchoolur** [comment]
At present, if `fourceAutoplay`(sorry spelling is wrong, I'll update it :)) if enabled, autoplay will be stopped when you navigate to a different slide. But' won't when a link within data-sub-html is clicked. 
But' if it an important requirement for you, maybe I can provide you a solution over the weekend.
