### ISSUE TITLE
fonts not loading from jsdelivr

### ISSUE THREAD

**Issue by dkebler** [sachinchoolur/lightGallery#556]
I am loading all of lightgallery.css from jsdeliver.  lightgallery.css loads the fonts with a relative reference.  `../fonts`
```
@font-face {
  font-family: 'lg';
  src: url("../fonts/lg.eot?n1z373");
  src: url("../fonts/lg.eot?#iefixn1z373") format("embedded-opentype"), url("../fonts/lg.woff?n1z373") format("woff"), url("../fonts/lg.ttf?n1z373") format("truetype"), url("../fonts/lg.svg?n1z373#lg") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

It looks like that should work from jsdelivr since the relative paths are the same but it doesn't

How to I get lightgallery.css to load the corresponding fonts from jsdelivr

in my head I have

    
    <link href="https://cdn.jsdelivr.net/g/lightgallery@1.3.9(css/lightgallery.min.css+css/lg-transitions.css)" rel="stylesheet">

but then when the page loads you see all the fonts never get loaded.  seems there is an extraneous `/css`

```
GET 
https://cdn.jsdelivr.net/g/lightgallery@1.3.9(css/img/loading.gif [HTTP/2.0 404 Not Found 250ms]
GET 
https://cdn.jsdelivr.net/g/lightgallery@1.3.9(css/fonts/lg.woff [HTTP/2.0 404 Not Found 571ms]
downloadable font: download failed (font-family: "lg" style:normal weight:normal stretch:normal src index:1): status=2147746065 source: https://cdn.jsdelivr.net/g/lightgallery@1.3.9(css/fonts/lg.woff?n1z373  lg-transitions.css):2:149
GET 
https://cdn.jsdelivr.net/g/lightgallery@1.3.9(css/fonts/lg.ttf [HTTP/2.0 404 Not Found 264ms]
downloadable font: download failed (font-family: "lg" style:normal weight:normal stretch:normal src index:2): status=2147746065 source: https://cdn.jsdelivr.net/g/lightgallery@1.3.9(css/fonts/lg.ttf?n1z373  lg-transitions.css):2:149
downloadable font: no supported format found (font-family: "lg" style:normal weight:normal stretch:normal src index:4) source: (end of source list)  lg-transitions.css):2:149
```

fyi loading lightgallery.js from jsdelivr too.  It's all working fine except for icons in the "viewer".

```
<!-- light gallery and modules/plugins -->
<script src="https://cdn.jsdelivr.net/g/lightgallery,lg-autoplay,lg-pager,lg-thumbnail,lg-video"></script>
```

**Comment by dkebler** [comment]
One can't use the jsdelivr resource combiner /g  url syntax and get relative paths to work.  It is not supported.  Alas you must use these separately and then the fonts load no problem.
```

    <link href="https://cdn.jsdelivr.net/lightgallery/1.3.9/css/lightgallery.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/lightgallery/1.3.9/css/transistions.min.css" rel="stylesheet">
```

**Comment by bkmod** [comment]
> 
Yes you can use just single link for your colors not being replaced, but this works amazing! Thank you for sharing this!

Single link I meant just this: <link href="https://cdn.jsdelivr.net/lightgallery/1.3.9/css/lightgallery.min.css" rel="stylesheet">
