### ISSUE TITLE
is an event emitted for click on thumb and exiting viewer? need to (un)hide a navbar

### ISSUE THREAD

**Issue by dkebler** [sachinchoolur/lightGallery#557]
On my landing page I have a section with a light gallery.  I also have a fixed navbar at the top which covers the top of the viewer and the control icons.

So does lightgallery emit events for click on a thumb (enter viewer) and exit viewer?  If so I could listen for those and change the display css for my navbar.

Alternatively if I could style the viewer not to cover the navbar and have all the navbar links close the viewer that might work as well.

@sachinchoolur Can you suggest a way(s) to resolve my issue. Thx

**Comment by dkebler** [comment]
I just changed the z-order of my navbar to be less than the lg-backdrop and that is sufficient.  I'd still like to now if lg emits events for entering/exiting the viewer.

**Comment by sachinchoolur** [comment]
Hi @dkebler ,
Yes, it is possible. Here is the complete list of lightGallery events. http://sachinchoolur.github.io/lightGallery/docs/api.html#events

I think you are looking for `onBeforeOpen.lg` and `onBeforeClose.lg`
