### ISSUE TITLE
lightSlider Integrate with lightGallery bug

### ISSUE THREAD

**Issue by rasstislav** [sachinchoolur/lightGallery#559]
**lightSlider configuration:**
- item: 3
- loop: true

**lightGallery configuration:**
- selector: '#imageGallery .lslide'

**how to reproduce:**
1. go to the last element
2. click next slide
3. this slide is clone and can not be open in lightGallery

**Comment by sachinchoolur** [comment]
Hi @rasstislav ,
Your current configuration excludes the cloned elements. Do you want to include those elements in lightGallery?

**Comment by rasstislav** [comment]
Hi @sachinchoolur,

Thank you for your response.  No, I do not want to include those elements into lightGallery, otherwise the pictures would be duplicated.

If `loop: false`, everything works fine. On the other hand, if `loop: true` and `item: >1` (more than one) -  **integrate lightSlider with lightGallery** works correcty just until the first slides does not start to appear in the end of lightslider. In this case I am not able to get into lightGallery through those elements.

**Comment by sachinchoolur** [comment]
It works fine for me. Please have a look at the demo - http://sachinchoolur.github.io/lightslider/examples.html(Integrate with lightGallery).

If the issue persists, Provide a jsfiddel demo. I'll fix the issue and send you back

**Comment by rasstislav** [comment]
Your example works fine, if `item: 1`, everything works fine... my situation is `item: 3` (more than one)

jsfiddle demo: https://jsfiddle.net/hognrwcb/

Click last thumbnail in slider and in actual view, second & third slide can not be open in lightGallery.

**Comment by sachinchoolur** [comment]
Oh Sorry. I missed `item:3` :disappointed:

At present we don't have a proper solution for this. Either we need to disable `loop` or need to set `item:1`. 
But, I'll keep looking for a remedy and I'll post it if I get it figured out.
