### ISSUE TITLE
Jquery 3 Support

### ISSUE THREAD

**Issue by elisent** [sachinchoolur/lightGallery#560]
Hi,

Any chances to add support for jquery3 in future ?

Thanks

**Comment by sachinchoolur** [comment]
It seems to be working fine for me. Not tested properly, but, I don't see any breaking changes that effects lightGallery in jQuery 3.0.  Are you getting any issue when you use lightGallery with jQuery 3?

**Comment by sachinchoolur** [comment]
Works fine with jQuery 3.0.
