### ISSUE TITLE
is it possible to use first frame of a video file as a poster for gallery elements and thumbnails?

### ISSUE THREAD

**Issue by 62mkv** [sachinchoolur/lightGallery#561]
Hi

Documentation for HTML5 video element has it that: 
`poster`: A URL indicating a poster frame to show until the user plays or seeks. If this attribute isn't specified, nothing is displayed until the first frame is available; then the first frame is shown as the poster frame.

However, if we omit "data-poster" attribute for a div, the video is:
a) autoplay when navigating into it
b) does not display video at all, just shows the img that's in `<a>` inside the div

Is this a bug with lightGallery or are we using it wrong?

**Comment by sachinchoolur** [comment]
Hi @62mkv ,
a) Yes, it is a bug. It'll be fixed in the next release. 
b) Not sure what is the issue. Could you please provide a jsfiddle demo or your website URL if it is available?

**Comment by sachinchoolur** [comment]
The issue has been fixed. Plese use the latest version of video plugin
