### ISSUE TITLE
Jumping straight a slide ...

### ISSUE THREAD

**Issue by gavphillips** [sachinchoolur/lightGallery#564]
Hi,

Is it possible to go straight to a slide from an external link.  For example, on your own site if I run this link: http://sachinchoolur.github.io/lightGallery I just see the home page.  However, if I add this /#lg=1&slide=2 it jumps straight to the second slide in the fullscreen slideshow mode.
However, when I try this on my own test I just see a list of thumbnails on a page.  Could you explain how I achieve this please.

Thanks
Gav

**Comment by sachinchoolur** [comment]
I think you are missing the hash plugin. https://github.com/sachinchoolur/lg-hash

Demo: http://sachinchoolur.github.io/lightGallery/demos/hash.html
Docs: https://sachinchoolur.github.io/lightGallery/docs/api.html#lg-hash

Please include lg-hash.js in your document and let me know the result

**Comment by gavphillips** [comment]
Hi,
Thanks for the quick reply I did check that I was using this plugin first and I definately have it included on my page.  Am I missing something else?

**Comment by sachinchoolur** [comment]
Could you please provide a jsfiddle which demonstrates your problem or your website URL if it is available?
It is very difficult to find the issue without seeing the code :pensive:
