### ISSUE TITLE
Dynamic Mode & Youtube Videos

### ISSUE THREAD

**Issue by delacrouz** [sachinchoolur/lightGallery#567]
Hi,

Is it possible to load dynamically youtube videos ? 

I tried with images and it works perfectly. I also tried with HTML5 videos and it works perfectly.
Now, I am trying to add a youtube video first in my gallery, and then images. 

What should I change in my code to do this ?

```
$('#dynamic').on('click', function() {
        $(this).lightGallery({
	    mode: 'lg-fade',
            dynamic: true,
            cssEasing : 'cubic-bezier(0.25, 0, 0.25, 1)',
            controls: true,
            download:false,
            autoplay:false,
            progressBar:false, 
            autoplayControls:false,
            pager:false,
            zoom:false,
            share:false,
	    fullscreen:true,
            dynamicEl: [{
                  thumb: './img/1.jpg',
				html: '<video class="lg-video-object lg-html5" controls preload="none"><source src="http://sachinchoolur.github.io/lightGallery/static/videos/video1.mp4" type="video/mp4">Your browser does not support HTML5 video</video>'
            }, {
                src: './img/2.jpg'
            }, {
               src: './img/3.jpg'
            }]

        })
    });
```

Thank you!

Antoine

**Comment by sachinchoolur** [comment]
Hey @delacrouz,

Yes, it is possible. Demo - http://codepen.io/sachinchoolur/pen/qryByV

Let me know if you have any other queries.

**Comment by delacrouz** [comment]
Thank you very much for your help on this issue ;-)

**Comment by bartollajos** [comment]
Hi, 
I'd like to open 1 vimeo (or youtube) video by clicking a link. 
What do I have to put in my javascript code? 
Thank you in advance...
