### ISSUE TITLE
How to stop/pause video after next slide

### ISSUE THREAD

**Issue by recruitname** [sachinchoolur/lightGallery#568]
I'm using lightgallery and I have alot of images ant vimeo videos but I couldn't pause vimeo after next slide how can I do that ?

**Comment by sachinchoolur** [comment]
Hey @recruitname ,

You need to include `https://f.vimeocdn.com/js/froogaloop2.min.js` in your document to pause Vimeo videos automatically 
Docs - http://sachinchoolur.github.io/lightGallery/demos/videos.html

**Comment by recruitname** [comment]
thanks a lot :)
