### ISSUE TITLE
AutoPlay skips first photo on slow network

### ISSUE THREAD

**Issue by CCCullens** [sachinchoolur/lightGallery#569]
Hi
I'm using the AutoPlay option with a 2 second pause. Often on slow networks, the loading animation appears and before the first photo is displayed, AutoPlay moves to the next photo. Thus skipping the first photo. Is there some way to have the time spent fetching/loading the photo not included in the AutoPlay pause time?

I tried various preload settings 1 to 3. Preload of 1 seemed worse than Preload of 3. 

Gallery options:
var lgOnClickRunThrough = $("#" + this.RunThroughID).lightGallery({
			autoplay: true,
			closable: false,
			controls: false,
			counter: false,
			download: false,
			dynamic: true,
			enableThumbDrag: false,
			fourceAutoplay: true,
			galleryId: GalleryCountID,
			hash: true,
			hideBarsDelay: 0,
			loop: false,
			mode: "lg-fade",
			mousewheel: false,
			pause: 2000, // milliseconds to wait before turning slide
			preload: 1,
			progressBar: false,
			speed: 500,
			startClass: '',
			thumbnail: false,
			zoom: false,
			dynamicEl: LGphotos
		});

Thanks for any advice,
Chane

**Comment by sachinchoolur** [comment]
Hey @CCCullens ,

Thank you for pointing this out. I don't know how I missed it :)
The issue has ben fixed. Use the latest version of [lg-autoplay plugin](https://github.com/sachinchoolur/lg-autoplay)

**Comment by CCCullens** [comment]
Amazing support, thank you!

**Comment by CCCullens** [comment]
This fix causes other problems.
The second time I invoke the gallery the "loading" spinner spins forever. That is, I launch the autoplay gallery when a button is clicked. It works great. Close the gallery, try again, and the it just loops in the loading phase forever. When I replace the JS reference back to the previous version, it does not hang forever during loading, but sometimes misses displaying the first photo.
