### ISSUE TITLE
Gallery more than one 

### ISSUE THREAD

**Issue by recruitname** [sachinchoolur/lightGallery#570]
I have product gallery on my page (same page) for example

- Casper
- Dell
- Moser
- Philips
- Rayban
- ...

these all are in the same page and and if I clicked current category (f.ex:rayban) only images of rayban should be opened

but I don't want to use different function for all category because my category can be more than one may be 40 maybe 10 and my question is is the any way to do that and how should it be my structure ?

http://codepen.io/cowardguy/pen/dvqryM

**Comment by sachinchoolur** [comment]
Hey @recruitname ,

I think the codepen demo you provided is not the actual one. Please update your demo according to your requirement or share your website URL. I'll try to help you

**Comment by recruitname** [comment]
Okey.I updated my gallery and I don't use thumbnail for my gallery I'm using a button and I opened by clicking my images on lightgallery, I have three gallery and when I clicked my button current gallery must be open but only with one function because in the future this gallery may be ten or fifty.

http://codepen.io/cowardguy/pen/mWaRGO

**Comment by sachinchoolur** [comment]
There are many ways to do this :)

Here is the updated codepen - http://codepen.io/anon/pen/qrLzvW
You can also try using the dynamic mode, instead of triggering the click manually - http://sachinchoolur.github.io/lightGallery/demos/dynamic.html
