### ISSUE TITLE
justifiedGallery + lightGallery, several galleries, only first works

### ISSUE THREAD

**Issue by aitormendez** [sachinchoolur/lightGallery#572]
Just first gallery open the lightbox. Following galleries break the page.

This is the HTML markup:

    <div class="gallery">
         <a href="img/img1.jpg">
             <img src="img/thumb1.jpg" />
         </a>
         <a href="img/img2.jpg">
             <img src="img/thumb2.jpg" />
         </a>
    </div>
    <div class="gallery">
         <a href="img/img1.jpg">
             <img src="img/thumb1.jpg" />
         </a>
         <a href="img/img2.jpg">
             <img src="img/thumb2.jpg" />
         </a>
    </div>

This is the init:

      $(document).ready(function() {
          $('.gallery').justifiedGallery({
            lastRow : 'nojustify',
            rowHeight : 100,
            margins : 3
          }).on('jg.complete', function () {
            $(".gallery").lightGallery({
              thumbnail:true
            });
          });
        });

Is it possible to get woking all galleries in a page with a generic selector (".gallery")?

**Comment by aitormendez** [comment]
UPDATE: This works for two galleries:

         $('#gallery-1').justifiedGallery({
                rowHeight : 100,
                margins : 3
          }).on('jg.complete', function () {
              $('#gallery-1').lightGallery({
                   thumbnail:true
              });
          });
          $('#gallery-2').justifiedGallery({
                rowHeight : 100,
                margins : 3
          }).on('jg.complete', function () {
               $('#gallery-2').lightGallery({
                    thumbnail:true
               });
          });

**Comment by aitormendez** [comment]
I foud the solution with each function:

         $('.gallery').each(function() {
            $(this).justifiedGallery({
              rowHeight : 100,
              margins : 3
            }).on('jg.complete', function () {
              $('.gallery').lightGallery({
                thumbnail:true
              });
            });
          }

**Comment by aitormendez** [comment]
Solved!

      $(document).ready(function(){
        $('.gallery').justifiedGallery({
          lastRow : 'nojustify',
          rowHeight : 100,
          margins : 3
        }).on('jg.complete', function(){
          $(this).lightGallery({
            thumbnail: true
          });
        });
      });

**Comment by mattmintun** [comment]
3 years old and still saved my project! Thank you @aitormendez. My issue was that with justifiedGallery + lightGallery, it was adding an empty thumbnail in the lightGallery popup at the end of the series of images. This fixed it.
