### ISSUE TITLE
Video HTML5 Not Working on Google Chrome

### ISSUE THREAD

**Issue by javic91** [sachinchoolur/lightGallery#573]
This feature works fine in firefox, but I could not make it work on Google Chrome.
This feature also does not work on lightgallery demos using Google Chrome.

**Comment by sachinchoolur** [comment]
Hey @javic91 ,
It works fine for me. Could you please share a screenshot of your video gallery?

**Comment by atulc** [comment]
Same problem here -- on Windows 10 64bit / Chrome the HTML5/YouTube/Vimeo demos do NOT work.  Works OK in FF and IE11.

Video: http://images.infolytik.com/gkXB
HAR debug: ATTACHED

[sachinchoolur.github.io (2).har.zip](https://github.com/sachinchoolur/lightGallery/files/930591/sachinchoolur.github.io.2.har.zip)

**Comment by sachinchoolur** [comment]
Hey @atulc,
Thanks for the video.
Are you using any kind of touch screen monitor? Could you please try adding a debugger on lg-videos.js line no: 153 and check ?
``` js
_this.core.$el.on('onSlideClick.lg.tm', function() {
  alert('calling')
  var $el = _this.core.$slide.eq(_this.core.index);
  loadOnClick($el);
});
```

**Comment by sachinchoolur** [comment]
The issue has been fixed. Please use the latest version(1.6.0) of lightGallery and its modules.
