### ISSUE TITLE
AutoPlay now hangs on second invoke

### ISSUE THREAD

**Issue by CCCullens** [sachinchoolur/lightGallery#574]
See: AutoPlay skips first photo on slow network #569
This fix causes other problems.
The second time I invoke the gallery the "loading" spinner spins forever. That is, I launch the autoplay gallery when a button is clicked. It works great. Close the gallery, try again, and the it just loops in the loading phase forever. When I replace the JS reference back to the previous version, it does not hang forever during loading, but sometimes misses displaying the first photo.

**Comment by CCCullens** [comment]
Followup, after running many test cases. This is what I'm seeing consistently. If it helps. Using the previous release, the first invoke of the gallery (button click) all slides, works great. On the second invoke, even on a high speed network, loading animation and first slide is skipped. Note, I expected the first invoke to show the loading animation, but it only happens on the second invoke. preload has no impact, I've tried numbers from 0 to 20

**Comment by sachinchoolur** [comment]
Hey @CCCullens ,
It works fine for me. Could you please provide an isolated jsfiddle demo which demonstrates your problem.

**Comment by CCCullens** [comment]
I'll create the jsfiddle this weekend

**Comment by CCCullens** [comment]
Here you are: https://jsfiddle.net/CCCullens/nx6tzrzq/
Usage: Click on the button, all is well, autoplays the 3 photos and closes based on onBeforeSlide.lg logic. Then, Click on the button a second time - shows the animation forever. 
If the issue is the onBeforeSlide logic, all I'm trying to do is autoplay for 1 time, then stop. 
If the jsfiddle above does not work, here is the code
```
<title>Test lightGallery autoplay</title>
<!-- Bootstrap -->

<!-- Chane extensions to bootstrap -->
<link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/lightgallery/1.3.9/css/lightgallery.css" />

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/lightgallery/1.3.9/js/lightgallery.js"></script>
<script src="https://cdn.jsdelivr.net/lg-autoplay/1.0.4/lg-autoplay.js"></script>
<script>
  var GalleryCountID = 1; 
  var lgTestGallery;
  var LGphotos = [{
    "src": 'http://sachinchoolur.github.io/lightGallery/static/img/1.jpg',
  }, {
    "src": 'http://sachinchoolur.github.io/lightGallery/static/img/2.jpg',
  }, {
    "src": 'http://sachinchoolur.github.io/lightGallery/static/img/3.jpg',
  }];

  document.addEventListener('DOMContentLoaded', () => {
    console.info('Document ready');
    $('button').on('click', function() {
      console.info('Button clicked');

      GalleryCountID++;
      lgTestGallery = $('#buttonID').lightGallery({
        autoplay: true,
        closable: false,
        controls: false,
        counter: false,
        download: false,
        dynamic: true,
        enableThumbDrag: false,
        fourceAutoplay: true,
        galleryId: GalleryCountID,
        hash: true,
        hideBarsDelay: 0,
        loop: false,
        mode: 'lg-fade',
        mousewheel: false,
        pause: 500, // milliseconds to wait before turning slide
        preload: 1,
        progressBar: false,
        speed: 200,
        startClass: '',
        thumbnail: false,
        zoom: false,
        dynamicEl: LGphotos
      });
      lgTestGallery.on('onBeforeSlide.lg', (beforeEvent, prevIndex, currIndex) => {
        console.info(`lgTestGallery - onBeforeSlide.lg - previous index: ${prevIndex} - index: ${currIndex}`);
        // stop at end of first time through
        if (prevIndex === (LGphotos.length - 1) && currIndex === 0) {
          lgTestGallery.data('lightGallery').destroy();
        } else {
          // tslint:disable-next-line:no-magic-numbers
          console.info(`Current: ${currIndex + 1}, Previous: ${prevIndex}`);
        }
      });
    });
  });

</script>

</head>

<body>
  To show that "loading" animation forever. To this. 1. Click on "Click me", after it finishes 2. Click on "Click me" again
  <button type="button" id='buttonID'>Click Me!</button>

</body>

</html>
```

**Comment by CCCullens** [comment]
Fixed, I needed to pass "true" to the destroy() api.
