### ISSUE TITLE
image slideshow only on showed image.

### ISSUE THREAD

**Issue by topo9696** [sachinchoolur/lightGallery#576]
Hello .anyone mind looking at this question that i had about this lightgallery? i have posted it here in stackoverflow. http://stackoverflow.com/questions/43197209/image-slideshow-by-group-im-using-lightgallery-by-sachinchoolur I would really gratefull if anyone can help me about this problem.

**Comment by sachinchoolur** [comment]
Hey @topo9696 ,

You need to destroy and re-initiate lightGallery after clicking on categories. 
Demo: http://sachinchoolur.github.io/lightGallery/demos/methods.html

If it doesn't work please provide a working Jsfiddle demo. I'll fix the issue and send you back

**Comment by topo9696** [comment]
Thanks for the help and fast reply. Just some question is there a way where I can set which image is the start and end.? For example if I have image gallery with 5 image(img1, img2, img3, img4, img5) in it then I have a button where I can make the slideshow start from img2 and end on img4 only. img1 and img5 will be disable.

**Comment by sachinchoolur** [comment]
You can use lightGallery selector property. Add a class to img2, img3 and img4 and use it as lightGallery selector.

``` html
<ul class="gallery">
  <li><img src="img1"><li>
  <li class="custom-selector" data-src="img-lg-2"><img src="img2"><li>
  <li class="custom-selector" data-src="img-lg-3"><img src="img3"><li>
  <li class="custom-selector" data-src="img-lg-4"><img src="img4"><li>
  <li><img src="img5"><li>
</ul>
```
``` js
$('#gallery').lightGallery({
    selector: '.custom-selector'
});
```

**Comment by topo9696** [comment]
Thanks! Im gonna try that code and let you know how it goes. By the way here is some example on the gallery Im working on it has a navigation button on the left where if user click the "room" button only picture related to room are displayed..Sorry i edited your code on codepen. https://codepen.io/sachinchoolur/pen/qNyvGW

**Comment by sachinchoolur** [comment]
Hey @topo9696 ,

Sorry for the delayed response. You need to destroy and re-initiate lightGallery after clicking on the category.

Demo: http://sachinchoolur.github.io/lightGallery/demos/methods.html

And you have to use `selector:'li:visible'` to exclude hidden gallery elements (Other categories).

``` js
$('#lightgallery').lightGallery({
     selector:'li:visible'
});
```

**Comment by sachinchoolur** [comment]
Demo: http://codepen.io/anon/pen/MpdRRX?editors=1010
