### ISSUE TITLE
Reopening AutoPlay skips first photo on slow network #569

### ISSUE THREAD

**Issue by CCCullens** [sachinchoolur/lightGallery#578]
Now that I have jsfiddle working. Photos are still being skipped.
Use: https://jsfiddle.net/CCCullens/nx6tzrzq/  

How to show that photos are still being skipped with Chrome

1. More Tools -> Developer Tools
2. In Developer Tools, in the right side three dot menu, select More Tools -> Network Conditions
3. Choose a really slow network, like Regular 2G (300ms, 250kb/s, 50kps)

Refresh the browser window - right mouse click the Browser refresh button and choose 'Empty Cache and Hard Reload'
Now click the "Click Me!" button. 3 photos should be display, I've never seen more than one photo visible. 

Note, Easy to duplicate, let me know if you need a movie. In my browser always shows - loading animation, then 1 photo, then animation then closes window (normal finish)

Note, works the second time since the browser has cached the files. Always use Chrome's Empty Cache and Hard Reload option on the Refresh command.

Sorry to keep bringing this up, but with Chrome's ability to slow network traffic and jsfiddle when I testing the 1.0.4 it does not work.  Also, if there is a way for me to workaround this by calling an magic Method in onBeforeOpen or something, I'm glad to add extra code. 

thanks
Chane

Code from jsfiddle
`<title>Test lightGallery autoplay</title>

<link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/lightgallery/1.3.9/css/lightgallery.css" />

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/lightgallery/1.3.9/js/lightgallery.js"></script>
<script src="https://cdn.jsdelivr.net/lg-autoplay/1.0.4/lg-autoplay.js"></script>
<script>
  var GalleryCountID = 1; 
  var lgTestGallery;
  var LGphotos = [{
    "src": 'http://sachinchoolur.github.io/lightGallery/static/img/1.jpg',
  }, {
    "src": 'http://sachinchoolur.github.io/lightGallery/static/img/2.jpg',
  }, {
    "src": 'http://sachinchoolur.github.io/lightGallery/static/img/3.jpg',
  }];

  document.addEventListener('DOMContentLoaded', () => {
    console.info('Document ready');
    $('button').on('click', function() {
      console.info('Button clicked');

      GalleryCountID++;
      lgTestGallery = $('#buttonID').lightGallery({
        autoplay: true,
        closable: false,
        controls: false,
        counter: false,
        download: false,
        dynamic: true,
        enableThumbDrag: false,
        fourceAutoplay: true,
        galleryId: GalleryCountID,
        hash: true,
        hideBarsDelay: 0,
        loop: false,
        mode: 'lg-fade',
        mousewheel: false,
        pause: 500, // milliseconds to wait before turning slide
        preload: 1,
        progressBar: false,
        speed: 200,
        startClass: '',
        thumbnail: false,
        zoom: false,
        dynamicEl: LGphotos
      });
      lgTestGallery.on('onBeforeSlide.lg', (beforeEvent, prevIndex, currIndex) => {
        console.info(`lgTestGallery - onBeforeSlide.lg - previous index: ${prevIndex} - index: ${currIndex}`);
        // stop at end of first time through
        if (prevIndex === (LGphotos.length - 1) && currIndex === 0) {
          lgTestGallery.data('lightGallery').destroy(true);
        } else {
          // tslint:disable-next-line:no-magic-numbers
          console.info(`Current: ${currIndex + 1}, Previous: ${prevIndex}`);
        }
      });
    });
  });

</script>

</head>

<body>
 
  <button type="button" id='buttonID'>Click Me!</button>

</body>

</html>

`

**Comment by sachinchoolur** [comment]
Hey @CCCullens,

I'm really sorry for the delayed response. The last fix works properly. Watch the demo carefully the first images(http://sachinchoolur.github.io/lightGallery/static/img/1.jpg) is always getting loaded.  But sometimes it skips the second image as the network is too slow and the pause value is very less `500ms`. 

Normally, the second image will be loaded before completing the first slide. Right now I'm closing the ticket as it is a very rare scenario and I don't want to make autoplay plugin complicated just because of this problem. Hope you understand. 

Thank you so much for your effort and time. If we get more feature requests on the same I will definitely consider adding it.
