### ISSUE TITLE
Lightbox appends URL

### ISSUE THREAD

**Issue by PradViking** [sachinchoolur/lightGallery#579]
Hi,

I'm using a Wordpress theme which uses your plugin. The issue I have is that when a user opens an image in this lightbox, it appends the URL with certain info of the image. Now if the user views several images and closes the lightbox and wishes to go back to a prev page and clicks the back button the URL of the last viewed image gets populated in the browser. This does nothing on the screen as there's a # in the URL. 

The theme dev say this change can be implemented in the theme only when you guys develop this.

scenario: 
1. User is on home page, which contains 5 albums.
2. User clicks on 1st album. this opens the album containing, lets say 50 images.
3. User clicks on 1st image which opens in lightbox and scrolls through to the last image.
4. Now user closes the lightbox and clicks on back button thinking that'll take him to home page. But this only goes back to the URL of the last image viewed without any activity on screen.

This for me is not conducive as users are left clicking the back button n number of times to go back to a prev page. I'm a photographer and this poses a major UX issue for my clients. No one wants to be clicking the back button n number of times.

I'm not a developer. I registered here to check if this possible as the theme devs gave me this github link as they use this plugin.

How do I disable the lightbox from appending the URL? I can have a friend who is a dev take a look at it.

Thanks,
Prad

**Comment by sachinchoolur** [comment]
Hey @PradViking ,

I'm really sorry for the delayed response. You an easily disable the hash plugin by passing `hash:false` via settings,
