### ISSUE TITLE
Sort plugin

### ISSUE THREAD

**Issue by JosephP91** [sachinchoolur/lightGallery#580]
Hi,
does anyone knows if there is a sort plugin to sort the images showed in the gallery? That would be awesome.

Thanks.

**Comment by sachinchoolur** [comment]
Hey @JosephP91,
To display the sorted images in the gallery you just need to destroy and re-initiate lightGallery after sorting. Demo http://sachinchoolur.github.io/lightGallery/demos/methods.html
