### ISSUE TITLE
Share not working with Dynamic data

### ISSUE THREAD

**Issue by boyzoid** [sachinchoolur/lightGallery#581]
I am loading gallery data dynamically and everything works as expected. However, when I try to add the Share module I get a JS error whenever a new image loads.

Here is the error I receive in the console:
`lg-share.js:51 Uncaught TypeError: _this.core.$items.eq is not a function at lg-share.js:51`

And here is the line of JS causing the issue

`$('#lg-share-facebook').attr('href', 'https://www.facebook.com/sharer/sharer.php?u=' + (encodeURIComponent(_this.core.$items.eq(index).attr('data-facebook-share-url') || window.location.href)));`

**Comment by boyzoid** [comment]
And.,..of course, as soon as I ask for help, I figure out a solution.

When I am returning the data from the server I was using something like this:

```
item.lightGallery({
            dynamic: true,
            dynamicEl: data,
            thumbnail:true,
            download: false,
            galleryId: item.data('id')
        })
```

Changing it to this fixed the issue

```
item.lightGallery({
            dynamic: true,
            dynamicEl: $(data),
            thumbnail:true,
            download: false,
            galleryId: item.data('id')
        })
```

**Comment by arl1nd** [comment]
Here are the fixes for [this](https://github.com/sachinchoolur/lg-share/pulls).

**Comment by sachinchoolur** [comment]
Hey @boyzoid ,
The issue has been fixed. Please use the latest version of share plugin.

@arl1nd, Once again thank you for your contribution
