### ISSUE TITLE
Autoplay internval not being reset after slide switch

### ISSUE THREAD

**Issue by arl1nd** [sachinchoolur/lightGallery#582]
Autoplay is also running for multiple images, which is useful, but if a slide is almost about to change and I manually click on the NEXT arrow, the time for the new image doesn't restart, instead it just shows for the remaining time of the last slide. So if interval is set at 4s and I click NEXT manually after 3s, the next image will just show for 1s before changing again, making is somewhat confusing for the visitor. Is it possible to disable the autoplay when clicking NEXT or PREVIOUS?

**Comment by sachinchoolur** [comment]
Hey @arl1nd,

Thank you for your feedback :)
You can disable autoplay on first user action by setting `fourceAutoplay: false`.
But, you are right, autoplay time should reset when user navigates to next/prev slides. I'll try to include this in next release.

**Comment by epicalex** [comment]
+1 for this
