### ISSUE TITLE
how can i disable drag function in mobile

### ISSUE THREAD

**Issue by david43** [sachinchoolur/lightGallery#583]
Hi,
I try to disable drag.
It work on desktop version
but it not work on mobile.
`$cycle_wrapper.lightGallery({
	enableDrag:false,
	enableThumbDrag:false,
	enableThumbSwipe:false,
	loop:false,
	enableTouch:false,
});`

**Comment by sachinchoolur** [comment]
Hey @david43 ,

Thank you for pointing this out. It is a mistake in the docs. 
You have to use `enableSwipe` instead of `enableTouch`. I'll update the docs soon

**Comment by sachinchoolur** [comment]
I've updated the docs..
