### ISSUE TITLE
Enclosing the recommended html structure in a div breaks the slideshow.

### ISSUE THREAD

**Issue by mrcomptech** [sachinchoolur/lightGallery#584]
The README.md file, line 108, states "lightgallery does not force you to use any kind of markup. you can use whatever markup you want." this is not accurate.

While this HTML markup works:

<div id="gallery4-hos" class="row">
  <div id="relative-caption" class="row">
  
    <a  class="col-md-2" href="/images/image01.jpg" 
    data-sub-html="
    <h1>{image title}</h1>
    <p class='text-center'>Desc: {image description}</p>
    <p class='text-center'>Date: {image date}</p>">
    <img src="/images/image01-thumb.jpg" /></a>
  
    <a  class="col-md-2" href="/images/image02.jpg" 
    data-sub-html="
    <h1>{image title}</h1>
    <p class='text-center'>Desc: {image description}</p>
    <p class='text-center'>Date: {image date}</p>">
    <img src="/images/image02-thumb.jpg" /></a>
  
    <a  class="col-md-2" href="/images/image03.jpg" 
    data-sub-html="
    <h1>{image title}</h1>
    <p class='text-center'>Desc: {image description}</p>
    <p class='text-center'>Date: {image date}</p>">
    <img src="/images/image03-thumb.jpg" /></a>
  
    <a  class="col-md-2" href="/images/image04.jpg" 
    data-sub-html="
    <h1>{image title}</h1>
    <p class='text-center'>Desc: {image description}</p>
    <p class='text-center'>Date: {image date}</p>">
    <img src="/images/image04-thumb.jpg" /></a>
  
    <a  class="col-md-2" href="/images/image05.jpg" 
    data-sub-html="
    <h1>{image title}</h1>
    <p class='text-center'>Desc: {image description}</p>
    <p class='text-center'>Date: {image date}</p>">
    <img src="/images/image05-thumb.jpg" /></a>
  
    <a  class="col-md-2" href="/images/image06.jpg" 
    data-sub-html="
    <h1>{image title}</h1>
    <p class='text-center'>Desc: {image description}</p>
    <p class='text-center'>Date: {image date}</p>">
    <img src="/images/image06-thumb.jpg" /></a>

  </div>
</div>

  
If this markup is only slightly modified by encasing the <a></a> in a div and moving 'class="col-md-2"' to the enclosing div like so:

<div id="gallery4-hos" class="row">
  <div id="relative-caption" class="row">
  
    <div class="col-md-2">
      <a href="/images/image01.jpg" 
      data-sub-html="
      <h1>{image title}</h1>
      <p class='text-center'>Desc: {image description}</p>
      <p class='text-center'>Date: {image date}</p>">
      <img src="/images/image01-thumb.jpg" /></a>
    </div>
      
    <div class="col-md-2">
      <a href="/images/image02.jpg" 
      data-sub-html="
      <h1>{image title}</h1>
      <p class='text-center'>Desc: {image description}</p>
      <p class='text-center'>Date: {image date}</p>">
      <img src="/images/image02-thumb.jpg" /></a>
    </div>
      
    <div class="col-md-2">
      <a href="/images/image03.jpg" 
      data-sub-html="
      <h1>{image title}</h1>
      <p class='text-center'>Desc: {image description}</p>
      <p class='text-center'>Date: {image date}</p>">
      <img src="/images/image03-thumb.jpg" /></a>
    </div>
      
    <div class="col-md-2">
      <a href="/images/image04.jpg" 
      data-sub-html="
      <h1>{image title}</h1>
      <p class='text-center'>Desc: {image description}</p>
      <p class='text-center'>Date: {image date}</p>">
      <img src="/images/image04-thumb.jpg" /></a>
    </div>
      
    <div class="col-md-2">
      <a href="/images/image05.jpg" 
      data-sub-html="
      <h1>{image title}</h1>
      <p class='text-center'>Desc: {image description}</p>
      <p class='text-center'>Date: {image date}</p>">
      <img src="/images/image05-thumb.jpg" /></a>
    </div>
      
    <div class="col-md-2">
      <a href="/images/image06.jpg" 
      data-sub-html="
      <h1>{image title}</h1>
      <p class='text-center'>Desc: {image description}</p>
      <p class='text-center'>Date: {image date}</p>">
      <img src="/images/image06-thumb.jpg" /></a>
    </div>

  </div>
</div>

The lightGallery slideshow no longer works.
Is this an issue or am I doing something incorrectly?

Another issue is if the <a></a> code sections are not enclosed within the <div></div>, as in the second example, and more than one row of images is desired, the thumbnails must all be the same size. Otherwise the thumbnails will wrap to the tallest image and not all the way at the left of the page. Normally this can be corrected by placing the following div in between rows of images:
<div style="clear: both; display: block; overflow: hidden; visibility: hidden; width: 0; height: 0;"></div>

But id this is done then again the slideshow is broken.

**Comment by sachinchoolur** [comment]
Hey @mrcomptech,

You have to use selector property when you use custom HTML structure. http://sachinchoolur.github.io/lightGallery/demos/html-markup.html

In your case, you might need to use 
```js
$('your-container').lightGallery({
    selector: 'a'
});
```

 If it doesn't work, please provide a JsFiddle demo. I'll fix the issue and send you back :)
