### ISSUE TITLE
Uncaught TypeError: Cannot read property '$items' of undefined

### ISSUE THREAD

**Issue by recruitname** [sachinchoolur/lightGallery#586]
Almost I won't sleep until I fix this issue I don't understand where is my mistake.so interesting..

I want to explain you shortly what I did.

I have cycle2 and lightgallery plugin and after I select any category from my carousel I rebuild/generate again my carousel -*if you check my example you will understand*- but after that my lightgallery became broken and  it give me a error and lightgallery doesn't work anymore after select any category

I updated my lightgallery version but nothing change but if I only use lightgallery.min.js without video.js,thumbnail.js my lightgallery is working but I need videos and thumbnail that's why I want to use with video and thumbnails

![typeerror](https://cloud.githubusercontent.com/assets/25980843/25641642/eb3318cc-2f9d-11e7-8ea3-bec78916577f.jpg)

error from my console
![capture](https://cloud.githubusercontent.com/assets/25980843/25641782/b52dddec-2f9e-11e7-9298-244cd564b0fd.jpg)

my codepen demo: http://codepen.io/cowardguy/pen/WjOEeE

**Comment by sachinchoolur** [comment]
Hey @recruitname,
I think this is the issue of cycle2 plugin. Everything works fine when I disable cycel2. http://codepen.io/anon/pen/pPdJeO?editors=1010

Maybe you can try using some other carousel instead.

**Comment by recruitname** [comment]
yes absolutely issue was about cycle2 thank you sachinchoolur:)
