### ISSUE TITLE
Feature: Drag mode like in highslide

### ISSUE THREAD

**Issue by duzun** [sachinchoolur/lightGallery#588]
Hi!
This is a great library!

It would be great to support dragging photo with no backdrop like highslide: http://highslide.com/ click on first photo.

Why? Sometimes one needs to compare two-three photos open side by side...

**Comment by sachinchoolur** [comment]
Hey @duzun ,

Thank you for your suggestion. But, lightGallery support only one image at a time. So anyway adding drag mode won't help you to compare multiple photos.

Hope you understand.
