### ISSUE TITLE
It is possible to add video as embed

### ISSUE THREAD

**Issue by recruitname** [sachinchoolur/lightGallery#589]
I'm using lightgallery my all project and it's one of the best ligtbox gallery in my opinion that's why I want to thank @sachinchoolur

This is not problem or not something like that, I know video adding as below

```
 <div class="item" 
data-src="https://vimeo.com/1084537" 
data-exthumbimage="http://sachinchoolur.github.io/lightGallery/static/img/thumb-v-y-2.jpg"
 data-id="natural" 
data-hidden="false" 
data-title="this is the video">
 <img class="lazyload" data-src="http://images.freeimages.com/images/previews/c23/cat-1396828.jpg"/>
 </div>

```

but I want to add logo on my vimeo videos and another parameters like height,width,border or something like that  for examples I want to add like this:

`<iframe src="https://player.vimeo.com/video/45461165" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
`
customize to embed

[Codepen Demo](http://codepen.io/cowardguy/pen/EmwKJg)

**Comment by sachinchoolur** [comment]
Hey @recruitname,
Thanks for the kind words. I'm glad that you like lightgGallery. :)

You can pass all supported Vimeo parameters via setting `vimeoPlayerParams`.
Demo: http://sachinchoolur.github.io/lightGallery/demos/videos.html#video-player-param
Vimeo Parameters: https://developer.vimeo.com/apis/oembed#universal-parameters

Still, if you want to use Iframe, that is also possible. You can use it in the same way how html5 videos works. 
``` js
<div style="display:none;" id="video1">
    <iframe src="https://player.vimeo.com/video/45461165" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
</div>
 
<!-- data-src should not be provided when you use html5 videos -->
<ul id="html5-videos">
  <li  data-sub-html="video caption1" data-html="#video1" >
      <img src="img/thumb1.jpg" />
  </li>
  ...
</ul>
```

But' it doesn't support features like posters or auto pause/play.

Let me know if you need a demo.

**Comment by recruitname** [comment]
thank you so so much, so can we auto pause/play using vimeo parameters ?

**Comment by sachinchoolur** [comment]
Hey @recruitname,
I'm sorry, It doesn't seem to be a good solution :disappointed:
Could you please point out what options are not possible with parameters and possible with iframe approach
https://developer.vimeo.com/apis/oembed#universal-parameters
