### ISSUE TITLE
Plugin for Infobox

### ISSUE THREAD

**Issue by neoman666** [sachinchoolur/lightGallery#594]
I am looking for a plugin, which opens a kind modal window, by button, where I can write to each image the exif data.

Is such a plugin planned for the future?

**Comment by sachinchoolur** [comment]
Hey @neoman666 ,
You can try adding the exif information via data-sub-html attribute and style it however you want. 
And you can write a simple plugin to show the popup on button click.

Plugin API - http://sachinchoolur.github.io/lightGallery/docs/plugin-api.html

Let me know if you have any questions
