### ISSUE TITLE
Lightbox Open from Anchor

### ISSUE THREAD

**Issue by machinegarethjohnsdesign** [sachinchoolur/lightGallery#596]
I wondered if it's possible to just open a Lightbox with multiple items from anchor, something like this seems to work but seems slightly hacky

```
<div id="lightgallery">
  <a href="img/img1.jpg">Test</a>
  <a href="img/img2.jpg"></a>
</div>
```

**Comment by sachinchoolur** [comment]
Hey @machinegarethjohnsdesign ,
The above code is valid and it should work fine. http://sachinchoolur.github.io/lightGallery/docs/#markup
Let me know if you have any further questions
