### ISSUE TITLE
Lightbox autoplay - only count transition time when image has loaded

### ISSUE THREAD

**Issue by karlsan** [sachinchoolur/lightGallery#597]
We use the gallery through the Kalium WordPress theme and on the whole it works great! Thanks a lot for working on this project.

One issue we are having is for a photography site where the images are quite heavy (high quality). When using lightbox mode with autoplay, on first view it often happens that an image starts to load and only shows just before the slider transitions to the next image. So if it takes 3s to load the image and transition is 4s, the image shows only very briefly.

Is it possible to introduce functionality where the slider senses when the image has loaded and only then starts to count the transition time? Or is our only option to turn of autoplay?

**Comment by sachinchoolur** [comment]
Hey @karlsan ,
The issue has already been resolved in https://github.com/sachinchoolur/lg-autoplay/commit/ea8207031e303f7b4fc7bcb2b84623d708ad99b0
Please use the latest version of [autoplay plugin](https://github.com/sachinchoolur/lg-autoplay)

**Comment by karlsan** [comment]
Hi @sachinchoolur, many thanks for your reply. I was trying to look through GitHub issues, but missed this one. That's great news. I just looked at the version shipping with the theme and it's 1.0.2, so will have to update to latest version.

Thanks for the quick reply!
