### ISSUE TITLE
HTML5 video starts playing in the background of next slide

### ISSUE THREAD

**Issue by Stefanowitsch84** [sachinchoolur/lightGallery#598]
Hello!

I have a mixed gallery with images and videos. By default the content of the next slide is preloaded. But thats a problem when the next slide is a HTML5 video.

In my case when watching an image, the video in the NEXT slide starts playing. You can hear the sound in the background and when progressing to the next slide the video is already running. 

Note: I have no autoplay attribute set in the video tag! 

If I change the "preload" option to zero it won't play - but also no content in the gallery is preloaded which is not what i want.

**Comment by sachinchoolur** [comment]
Hey @Stefanowitsch84,
The issue has been fixed. Please use the latest version of [lg-video.js](https://github.com/sachinchoolur/lg-video)
