### ISSUE TITLE
How to bind the gallery opening event to each image instead of the whole #lightGallery div?

### ISSUE THREAD

**Issue by gzmarques** [sachinchoolur/lightGallery#599]
Hi

I'd like to open the gallery only when I click an image, not anywhere on the div... Cause I'm trying to append links to remove or edit images, but whenever I click on the link, the gallery opens up!

Is there any shortcut? Because the preventDefault workarounds are kinda messy...

Thanks in advance!

**Comment by sachinchoolur** [comment]
Hey @gzmarques ,
Yes, it is possible. Set the image as a selector instead of the whole div. Here is the example of how to use selector property. If you still face any issues, please provide a jsfiddle demo with your HTML markup. I'll fix the issue and send you back
