### ISSUE TITLE
Light Gallery modified in Theme

### ISSUE THREAD

**Issue by johnbunk028** [sachinchoolur/lightGallery#600]
I'm using Light Gallery as supplied in a theme called Twofold. As such, it has been modified and the social sharing module has been removed or not added. Instead, the sharing is handled in another way. I'd like to add the sharing button back in and allow sharing from the individual gallery images. How can I accomplish this?

**Comment by sachinchoolur** [comment]
Hey @johnbunk028,

Here is the demo of lightGallery share buttons - http://sachinchoolur.github.io/lightGallery/demos/share.html
You just need to include the lg-share plugin on your document and provide necessary data-attributes.

But, If te issue is specific to the theme which you are using, I think you need to raise a support ticket to them :)
