### ISSUE TITLE
 back button of the smartphone

### ISSUE THREAD

**Issue by CodeBuilderPRO** [sachinchoolur/lightGallery#603]
Hi, how to implement the closing of the photo gallery by pressing the back button of the smartphone?

**Comment by sachinchoolur** [comment]
Hey @CodeBuilderPRO,

Thank you for pointing this out. I think this is an issue with the latest version of hash plugin. Please try using the version 1.0.1 and check. I'll try to fix the issue ASAP

**Comment by CodeBuilderPRO** [comment]
@sachinchoolur Thank you ... And where can I download it?

**Comment by sachinchoolur** [comment]
You can download hash plugin from the following repository 
Repo - https://github.com/sachinchoolur/lg-hash
Version 1.0.1 - https://github.com/sachinchoolur/lg-hash/releases/tag/1.0.1
Docs - https://sachinchoolur.github.io/lightGallery/docs/api.html#lg-hash
Demo - https://sachinchoolur.github.io/lightGallery/demos/hash.html

**Comment by CodeBuilderPRO** [comment]
@sachinchoolur Thank you! All good!

**Comment by AlejoMedina98** [comment]
Hello @CodeBuilderPRO  is this issue solved ? Im facing similar one.
If the lightGallery slider is opened, when I press the back button on mobile or pc browser, it returns last page, like window.history.back()

**Comment by MilanovicUros** [comment]
+1 For this issue, could you prioritize this please?

**Comment by annaemde** [comment]
I am using the following workaround: 

When the lightbox is opened, the current URL is pushed to the browser history:
`$(".lightbox").click(function() {
  var stateObj = { lg: "close" };
  var url = window.location.href;
  history.pushState(stateObj, "Products", url);
});`

If the back button is used on this page, the lightgallery will be closed and the user will find himself on the page where he opened the lightgallery:
`window.onpopstate = function(event) {
  $(".lg-close").click ();
}`

If the proper close button is used in the lightgallery, the superflous history entry has to be removed, therefore I have added the following lines to the closeGallery method in lightgallery.js after _this.destroy():
`// für Back Button in Lightgallery
    if (history.state !== null) {
      if (history.state.lg === "close")
	history.back();
      }
    });`

Of course it would be even better if you could avoid to manipulate the source code. Any ideas?

**Comment by AlejoMedina98** [comment]
@annaemde  Yours is a very good idea

**Comment by peamak** [comment]
Any update on this? 
This is a pretty important improvement imho…
Thanks for a great component and all your hard work!
