### ISSUE TITLE
Sharing Direct URL to Image

### ISSUE THREAD

**Issue by j0nr** [sachinchoolur/lightGallery#605]
Hello,

LOVE this LightGallery! Thank you.

But, I am trying to find a neat way to share a URL directly to a single image within a gallery. I have enabled the hash plugin, so I get a `#lg=1&slide=0` on the and of my URL...but copy/pasting this URL into another browser (as if I has just sent the link to someone via email) starts by opening the lightbox, but with no image shown and then the lightbox closes and shows the gallery view instead.

Is this behaviour as expected? If not, I will have to investigate whether its something to do with my htaccess rules...

Thanks.

Jon

**Comment by sachinchoolur** [comment]
Hey @j0nr ,
It works fine for me. Images should be visible when the shared URL is opened. Could you please share the URL? So that I can have a look at the issue.

**Comment by j0nr** [comment]
Hiya, 

Sorry that's tricky as I'm still developing it and it's behind a htpasswd protected folder... 

But as described, basically, I go to the hashed URL, but I when it first loads, the whole page is black (lightbox overlay) but then after about 1-2secs, the black overlay fades away to show the gallery underneath and the hash portion of the URL disappears. 

If it should work, then I suspect there is probably something amiss with my app somewhere so I will dig into that a bit more first. 

--
Cheers 

Jon Reynolds 

Sent from MailDroid

-----Original Message-----

**Comment by j0nr** [comment]
OK, so I believe it is the inner workings of what I am trying to o with my app that's messing it up.

Basically I load a page, then jQuery looks at the URL and does something with it to load dynamic content on the page. So if my URL contains "tags" (e.g. www.mysite.com/tag1/tag2/) it will then do an AJAX request to load dynamic gallery based on tags.

So when I go to a URL with a hash in it (e.g. www.mysite.com/tag1/tag2/#lg=1&slide=0) then the I still need to load the dynamic gallery first based on tags, BUT then somehow loadup the lightGallery lightbox on top, so if the user then closes the lightbox, the correct gallery is showing.

So in some sort of psuedo code:

    if (window.location.hash != "") { load dynamic gallery first and then display lightbox}

Any idea how to achieve this please?

**Comment by sachinchoolur** [comment]
Hey @j0nr,
Unfortunately, it is not possible without updating the core library code. If you are ok with that, you can comment lightGallery.js code from line number 
[145](https://github.com/sachinchoolur/lightGallery/blob/master/src/js/lightgallery.js#L145) to [159](https://github.com/sachinchoolur/lightGallery/blob/master/src/js/lightgallery.js#L159) and then manually check for the gallery id in the URL hash and if it exists call lightGallery with the index found from the URL.

Maybe you can write a small plugin to do this 
Plugin API - http://sachinchoolur.github.io/lightGallery/docs/plugin-api.html

Hope that helps :)

**Comment by sachinchoolur** [comment]
Closing as it not as issue of lightGallery

**Comment by j0nr** [comment]
Not sure if this is the best place to post more questions related to this...? But...

So commented out the lines you suggested stops the URL from loosing the hash...but the lightbox does not appear, even though there is a hash in the URL...Obviously it is my code not being correct, but I am creating a working dynamic gallery...it just doesn't open the lightbox until an item is clicked...

I am not a coder by profession so i am surely making mistakes with my code.

**Comment by sachinchoolur** [comment]
Once the dynamic gallery is created, you need to read the URL and if the gallery ID exists trigger click on the respective gallery. Still, if you face any issue, please share your code. I'll try to help you

**Comment by j0nr** [comment]
Thank you for the response...

hmm I get as far as detecting if hash exists in the URL, but not sure how to trigger a click on a link that has no specific id. lightGallery doesn't require me to have unique ids. 

I would love to show you my code as I hope it was ovious to you what I am doing wrong/badly. As I said I am not a professional...merely hobbyist. My block of code is big and messy and WIP...I wouldn't like to post it here....

**Comment by sachinchoolur** [comment]
You can simply trigger a click event on the particular element. For example, if the index of the item is 5
``` js
var index = 5;
$('yourGallery yourselector').eq(index).trigger('click');
```

**Comment by SOftEngrAtta** [comment]
getting same issue , i want to show image in light gallery and i am passing cloudinary url , but the black screen should be appeared . 

code : 
test.lightGallery({
    hash: true,
    galleryId: photoUrl
  });

cloudinary url : http://res.cloudinary.com/drvpex6kn/image/upload/v1507723473/a3hmwvjohpzoxxfpkjjm.png
