### ISSUE TITLE
HTML5 PICTURE tag and responsive image support?

### ISSUE THREAD

**Issue by TwoNiner** [sachinchoolur/lightGallery#606]
Any plans to support the HTML5 PICTURE tag? Right now it appears that the lightGallery script renders only an IMG tag with the src="" and srcset="" and sizes="" attributes. Does the browser still download all the images in the srcset list? Or just the appropriate one? My understanding is that PICTURE should replace the IMG tag in the rendering code.

http://sachinchoolur.github.io/lightGallery/demos/responsive.html

https://developers.google.com/web/fundamentals/design-and-ui/responsive/images

**Comment by marvin-martian** [comment]
Using picture tag should be a must have, it could also allow for alternative formats.  I like to use [webp](https://developers.google.com/speed/webp/) for supporting browsers as I get a 25-35% size reduction in jpegs. Great for mobile.

[https://developers.google.com/speed/webp/](https://developers.google.com/speed/webp/)

**Comment by luke-nehemedia** [comment]
Any plans on an update?
