### ISSUE TITLE
Mouse-Click Bug Missing in Thumbnail Plugin

### ISSUE THREAD

**Issue by TwoNiner** [sachinchoolur/lightGallery#607]
I cannot click thumbnails from within lightbox with my mouse on my desktop (Windows 8/Chrome). However, my touch screens allow me to touch thumbnails to navigate images.

**Comment by sachinchoolur** [comment]
Hey @TwoNiner,
Are you using any touch screen laptop?

**Comment by sachinchoolur** [comment]
The issue has been fixed. Please use the latest version(1.6.0) of lightGallery and its modules.

**Comment by TwoNiner** [comment]
Working now, thank you so much!

Matthew Kellerman
<matt@mattkellerman.com>
