### ISSUE TITLE
Only the main photo displaying and a button on the page which which will trigger the lightbox with all the photos

### ISSUE THREAD

**Issue by danb18** [sachinchoolur/lightGallery#610]
Hi There,

Fantastic lightbox! I am however only wanting to have the main photo displaying and a button on the page which clients can click which will trigger the lightbox with all the photos, I have searched and cannot find how to do this, also is there any lazy load or similar functionality to save image page load delays?

Many Thanks!

**Comment by sachinchoolur** [comment]
Hey @danb18,
If I understand your question correctly, you are looking for the dynamic demo - http://sachinchoolur.github.io/lightGallery/demos/dynamic.html

The following demo will help you to achieve the lazyload functionality 
http://sachinchoolur.github.io/lightGallery/demos/methods.html
