### ISSUE TITLE
Next arrow and next thumbnail not working properly. 

### ISSUE THREAD

**Issue by blairdow** [sachinchoolur/lightGallery#611]
The next arrow only works when double clicked OR when clicked twice in a row. It does not respond to the first click. the next thumbnail does not work at all on click. All other thumbnails work, but for some reason not the next sequentially. Anyone else have this issue?

**Comment by sachinchoolur** [comment]
Hey @blairdow ,
It works fine for me. Could you please provide an isolated jsfidle demo for your setup?
