### ISSUE TITLE
Lightgallery lightbox

### ISSUE THREAD

**Issue by ramanjiram** [sachinchoolur/lightGallery#613]
Hi ,

I am using lightgallery lightbox.it is very nice and cool. i have some issue when i am loding the page after lightbox opens it is showing not removing it will distrubing to my dom elements. could you please help me

**Comment by sachinchoolur** [comment]
Hey @ramanjiram ,
Could you please explain briefly how lightGallery is disturbing your dom elements? Or provide a jsfiddle wich demonstrates your issue?

**Comment by ramanjiram** [comment]
Hi @sachinchoolur ,

Thank you for your response. 

Distrubance means, once i open the lightgallery at that time i reload the page the lightgallery not closing. i need closing lightgallery after page loading.

Hope you understood my issue

**Comment by sachinchoolur** [comment]
Hey @ramanjiram,
I'm really sorry for the delayed response. If I understand the problem correctly, removing the hash plugin from the document will solve the issue. 

If the hash plugin is enabled and galleryId exists in the URL, lightGallery opens the respective slide automatically
