### ISSUE TITLE
lightGallery  and lightSlider together

### ISSUE THREAD

**Issue by pavlito** [sachinchoolur/lightGallery#614]
Hi,

Is there any code example on how to use this 2 plugins together.

Goal is to use lightSlider with thumbs, and to have ability on click to have modal dialog like in lightGallery?

**Comment by sachinchoolur** [comment]
Hey @pavlito ,
Yes, it is available. Here is the [demo](http://sachinchoolur.github.io/lightslider/examples.html). Check the example - 'Integrate with lightGallery'

Let me know if you have any queries

**Comment by pavlito** [comment]
Thanks @sachinchoolur ! 

I am having issue with playing html5 video inside modal. No console errors.
Probably markup is wrong.
![image](https://user-images.githubusercontent.com/3610827/27382324-ba5b79a0-5686-11e7-8f61-32b321ef271d.png)

`<section class="sect-activity-slider">
            
            <div style="display:none;" id="video1">
               <video class="lg-video-object lg-html5" controls preload="none">
                  <source src="http://sachinchoolur.github.io/lightGallery/static/videos/video3.mp4" type="video/mp4"> Your browser does not support HTML5 video.
               </video>
            </div>
            <div style="display:none;" id="video2">
               <video class="lg-video-object lg-html5" controls preload="none">
                  <source src="http://sachinchoolur.github.io/lightGallery/static/videos/video3.mp4" type="video/mp4"> Your browser does not support HTML5 video.
               </video>
            </div>
            <div class="row">
               <div class="panel">
                  <div class="panel-body">
                     <div class="col-md-8">
                        <ul id="imageGallery">
                           <li data-thumb="http://fakeimg.pl/800x450/" data-src="http://fakeimg.pl/1600x900/">
                              <img class="img-responsive" alt="img" src="http://fakeimg.pl/1600x900/" />
                           </li>
                           <li data-thumb="http://fakeimg.pl/800x450/" data-poster="http://fakeimg.pl/1600x900/" data-sub-html="video caption1" data-html="#video1">
                              <img class="img-responsive imageGallery__video-thumb" alt="video" src="http://fakeimg.pl/1600x900/" />
                           </li>
                           <li data-thumb="http://fakeimg.pl/800x450/" data-src="http://fakeimg.pl/1600x900/">
                              <img class="img-responsive" alt="img" src="http://fakeimg.pl/1600x900/" />
                           </li>
                           <li data-thumb="http://fakeimg.pl/800x450/" data-src="http://fakeimg.pl/1600x900/">
                              <img class="img-responsive" alt="img" src="http://fakeimg.pl/1600x900/" />
                           </li>
                           <li data-thumb="http://fakeimg.pl/800x450/" data-poster="http://fakeimg.pl/1600x900/" data-sub-html="video caption2" data-html="#video2">
                              <img class="img-responsive imageGallery__video-thumb" alt="video" src="http://fakeimg.pl/1600x900/" />
                           </li>
                           <li data-thumb="http://fakeimg.pl/800x450/" data-src="http://fakeimg.pl/1600x900/">
                              <img class="img-responsive" alt="img" src="http://fakeimg.pl/1600x900/" />
                           </li>
                           <li data-thumb="http://fakeimg.pl/800x450/" data-src="http://fakeimg.pl/1600x900/">
                              <img class="img-responsive" alt="img" src="http://fakeimg.pl/1600x900/" />
                           </li>
                           <li data-thumb="http://fakeimg.pl/800x450/" data-src="http://fakeimg.pl/1600x900/">
                              <img class="img-responsive" alt="img" src="http://fakeimg.pl/1600x900/" />
                           </li>
                           <li data-thumb="http://fakeimg.pl/800x450/" data-src="http://fakeimg.pl/1600x900/">
                              <img class="img-responsive" alt="img" src="http://fakeimg.pl/1600x900/" />
                           </li>
                           <li data-thumb="http://fakeimg.pl/800x450/" data-src="http://fakeimg.pl/1600x900/">
                              <img class="img-responsive" alt="img" src="http://fakeimg.pl/1600x900/" />
                           </li>
                           <li data-thumb="http://fakeimg.pl/800x450/" data-src="http://fakeimg.pl/1600x900/">
                              <img class="img-responsive" alt="img" src="http://fakeimg.pl/1600x900/" />
                           </li>
                           <li data-thumb="http://fakeimg.pl/800x450/" data-src="http://fakeimg.pl/1600x900/">
                              <img class="img-responsive" alt="img" src="http://fakeimg.pl/1600x900/" />
                           </li>
                           <li data-thumb="http://fakeimg.pl/800x450/" data-src="http://fakeimg.pl/1600x900/">
                              <img class="img-responsive" alt="img" src="http://fakeimg.pl/1600x900/" />
                           </li>
                        </ul>
                     </div><div class="col-md-4" style=""></div>
                  </div>
               </div>
            </div>
         </section>`

**Comment by pavlito** [comment]
And bottom thumbs are missing?

**Comment by pavlito** [comment]
Fixed this issues

**Comment by papakay** [comment]
@pavlito please how did you fix it. I'm experiencing similar issue. Thanks.

**Comment by papakay** [comment]
I found it. Please in case you have this issue make sure you add **lg-video.js** file into your page. It was not expressly stated in the example page and as long as i added **lightgallery.min.js** i thought that was it.

God be praised for the insight and direction.

**Comment by pavlito** [comment]
@papakay For missing video, markup was not properly nested.

Just include all scripts (there are multiple scripts for video, thumbs, etc).

But still i have problem with showing icon (play icon) on thumbnails for video files...

**Comment by papakay** [comment]
Thanks @pavlito
