### ISSUE TITLE
#lightGallery-next Slide-Icon doesn't display on HTC One Kitkat 4.4.3

### ISSUE THREAD

**Issue by janchrist** [sachinchoolur/lightGallery#62]
Hi

The Icon > respectively content: "\e01b"; doesn't display on one of our test mobile phones? Everything else works perfect.

Thanks Jan

**Comment by sachinchoolur** [comment]
Hi,
I totally forgot about this issue..
I have released lightgallery 1.2.. Please check the issue once again.. If still it is not working i will add png images also with font icons..
