### ISSUE TITLE
Add button - Download all

### ISSUE THREAD

**Issue by uasan** [sachinchoolur/lightGallery#622]
Hi.
Is there a plugin that adds a download button to everything, with the link specified by me?

```JS
$('#gallery').lightGallery({
     downloadAllUrl: '/gallery.zip'
});
```

Thank.

**Comment by sachinchoolur** [comment]
Hey @uasan ,
You can easily create a plugin to add the download button.
Here is the plugin API - http://sachinchoolur.github.io/lightGallery/docs/plugin-api.html

You can refer any small lightGallery plugin such as [Autoplay](https://github.com/sachinchoolur/lg-autoplay/blob/master/src/lg-autoplay.js) or [Fullscreen.](https://github.com/sachinchoolur/lg-fullscreen/blob/master/src/lg-fullscreen.js)

Let me know if you have any queries
