### ISSUE TITLE
Youtube is not running video!

### ISSUE THREAD

**Issue by oguzhansari** [sachinchoolur/lightGallery#625]
The codes are shown in the pictures below.
I'm pushing the video button.
But it does not work.

https://www.dropbox.com/s/7ybv0px5tvogcnz/20170701_130255.mp4?dl=0

![ekran alintisi3](https://user-images.githubusercontent.com/13555457/27761011-f3a79ddc-5e5c-11e7-88b2-06a6abb3d44d.PNG)
![ekran alintisi2](https://user-images.githubusercontent.com/13555457/27761012-f3c85d06-5e5c-11e7-8a93-953437855f37.PNG)
![ekran alintisi](https://user-images.githubusercontent.com/13555457/27761013-f3d65dc0-5e5c-11e7-8f1c-6d7815aa6ada.PNG)

**Comment by sachinchoolur** [comment]
Hey @oguzhansari,
I think you are missing the (lg-video plugin)[https://github.com/sachinchoolur/lg-video]. 
Docs - https://sachinchoolur.github.io/lightGallery/docs/api.html#lg-video
Demo - http://sachinchoolur.github.io/lightGallery/demos/videos.html

If it doesn't work, please provide a Jsfiddle which demonstrates the problem

**Comment by oguzhansari** [comment]
Thank you. It was caused by missing JS files.
