### ISSUE TITLE
How to use it with commonjs module format

### ISSUE THREAD

**Issue by AnixPasBesoin** [sachinchoolur/lightGallery#626]
I'd like to use this library in a way that I can bundle it with all the other modules. (I'm currently using Borwserify as a module bundler).
I'd like to avoid including any script other than the bundled one in the hml, so may I know the right way to do it? I'm expecting something like this:

```
var $ = require('jquery');
require('lightGallery')($);
// and then I'll be able to use it as if I have included it in the html tag.
$("#images").lightGallery(); 
```

**Comment by sachinchoolur** [comment]
Hey @AnixPasBesoin,
Really sorry for the delayed response. I missed the issue :(

The following code works fine for me.
```js
var $ = require('jquery');
require('lightGallery');
$("#images").lightGallery();
```
Please re-open if th problem presists
