### ISSUE TITLE
How to manage a big amount of pics ?

### ISSUE THREAD

**Issue by noelebrun** [sachinchoolur/lightGallery#627]
Hi!

lightGallery is really awesome and helped me to do a lot of cool things. My only bug issues now is managing big albums. When I have 1000 pictures, I don't want to display everything in the same page. It would be pretty bad for the UX and a weight operation for the browser if every pics are loaded by a lot of Ajax calls. 

So, there is the "Load more" Ajax solution or a complete pagination with different hash in URL.

About the first method, the issues are: the total amount of pics in the top left isn't correct, I can't force to load more and display the next pic when the user reach to last loaded pic and I'm not a big fan having to scroll a lot when you are at the bottom.

And about the second one: Same for the amount of pics in the top left, same when the user reach the last loaded pic & another big issue it that I can't override the URL hash to have a different URL by page since lg-hash is managing it.

So, users or creator of lightGallery, how are you managing this ?

Thanks!

**Comment by sachinchoolur** [comment]
Hey @noelebrun ,

> So, there is the "Load more" Ajax solution

Yes, Here is the example - http://sachinchoolur.github.io/lightGallery/demos/methods.html

Regarding the counter (Number of images. left-top)  - I'll try to add a setting for setting counter value in lightGallery version 2.0
