### ISSUE TITLE
Slide method

### ISSUE THREAD

**Issue by gonardfreeman** [sachinchoolur/lightGallery#629]
Is there any problems with slide method, or its just me?
`lightgallery.js:777 Uncaught TypeError: this.$outer.find is not a function`
and mine
`$this.lightGallery({`
	`dynamic: true,`
	`dynamicEl: createDynamicArr(path, names)`
`})`
`$this.data('lightGallery').slide(2)`

**Comment by sachinchoolur** [comment]
Hey @gonardfreeman,
Sorry for the delayed response. Could you please provide a jsfiddle which demonstrates your problem?

**Comment by evromalarkey** [comment]
I have the same problem, how do I use the slide method with dynamic mode?

**Comment by sachinchoolur** [comment]
Slide() method works only when lightGallery is open. Here is the demo - https://codepen.io/anon/pen/dRBMKx?editors=1010

Please re-open if the issue persists
