### ISSUE TITLE
Not working when ajax loaded images

### ISSUE THREAD

**Issue by beyond88** [sachinchoolur/lightGallery#633]
I have load more button. loaded images by ajax but your plugin not working for ajax loaded images. How can I fix this?

**Comment by sachinchoolur** [comment]
Hey @beyond88,
I'm really sorry for the delayed response. 
You have to destroy the current lightGallery instance and re-initiate after appending new images.
Here is the demo - http://sachinchoolur.github.io/lightGallery/demos/methods.html
