### ISSUE TITLE
Firefox issues: 'click on thumb' and 'slide with mouse' aren't working

### ISSUE THREAD

**Issue by Mons-web** [sachinchoolur/lightGallery#634]
Hi,

Clicking on a thumb doesn't work on Firefox: the clicked image isn't showing.
Dragging a picture with the mouse doesn't work either.

On Chrome everything work fine

The issues are also on the demo: https://sachinchoolur.github.io/lightgallery.js/demos/index.html

firefox 54.0.1 
macOS Sierra 10.12.1

Regards

**Comment by leotop** [comment]
slide width mouse doesn't work on firefox linux, but work with old lightGallery

**Comment by leotop** [comment]
Fix: 
$("#lightgallery").lightGallery({selector: '.gallery-item', thumbnail: true, enableDrag: true});

add enableDrag and thumbnail

**Comment by Mons-web** [comment]
Thanks for the answer @leotop but this fix doesn't work.

I am using the vanilla version of the plugin with dynamic mode:
`    document.getElementById('open-gallery').addEventListener('click', function() {
        lightGallery(document.getElementById('open-gallery'), {
          thumbnail:true,
          animateThumb: true,
          showThumbByDefault: true,
          dynamic: true,
          enableDrag: true,
          dynamicEl: <%= raw(json_array.to_json) %>
        })
    });`

enableDrag: true isn't necessary to have it wortking fine on chrome.
so this really seems to be a firefox issue

**Comment by sachinchoolur** [comment]
Hey @Mons-web ,
It works fine for me. Could you please confirm that you haven't made any core configuration changes(ex pointer events) from the `about:config` section

**Comment by Mons-web** [comment]
Hi @sachinchoolur 
I haven't made such changes in my firefox.
I asked a friend to test in his side, and everything works fine for him too, so obviously this issue is only for me! No idea what's going on..
Sorry for disturbing you :)
