### ISSUE TITLE
Click events don't work on touch-enabled devices

### ISSUE THREAD

**Issue by smerriman** [sachinchoolur/lightGallery#635]
Have been several threads where this problem was mentioned in passing but none got replies, so am opening a new one to centralise the information.

If a browser reports touch capability, all onSlideClick events (such as loading videos, etc) fail to run if you click with a mouse.

This is because the whole enableDrag code is ignored if on a touchscreen, which is the only function which passes on click events to onSlideClick.

In fact, if you turn off enableDrag in the lightgallery sections, this means click events won't work at all, regardless of touch capability.

A potential fix is (for the first bit, at least) is to remove the condition in Plugin.prototype.enableDrag, ie changing:

`if (_this.s.enableDrag && !_this.isTouch && _this.doCss()) {`

to:

`if (_this.s.enableDrag && _this.doCss()) {`

I'm not 100% sure on this, as touch devices may also send mouse events, causing some parts of the code to run twice. However, I don't think this happens, because you've added preventDefault calls to the touch events.

Whether this is the correct solution or not, this is a major bug that needs fixing, and has been around for more than a year based on other threads.

**Comment by sachinchoolur** [comment]
Hey @smerriman,
Working on it. I'll try to fix the issue within few days(Need to arrange a touchscreen laptop :P)

**Comment by sachinchoolur** [comment]
Hey @smerriman,

All the issues related to touchscreen have been fixed. Please use the latest version of lightGallery and it's modules.
