### ISSUE TITLE
Show thumbnail captions

### ISSUE THREAD

**Issue by S43534** [sachinchoolur/lightGallery#636]
Hi guys,

very great tool!

One question: Is there any chance to have individual captions below each thumbnail when using dynamic elements? How would I achieve this?

Thanks & best regards
Sebastian

**Comment by sachinchoolur** [comment]
Hey @S43534 ,
At present, No. But I'll try to add this feature in version 2.0

**Comment by donaldboulton** [comment]
Was hoping for this feature myself in the react version
