### ISSUE TITLE
How to show magnifying glass icon on hover?

### ISSUE THREAD

**Issue by kreativdenker** [sachinchoolur/lightGallery#639]
I want to show a little magnifying glass icon on hover, that the user knows, that he can open a gallery by clicking..

**Comment by sachinchoolur** [comment]
Hey @kreativdenker,
You have full control over the thumbnail markup. You can write your own HTML and CSS to do this. If you face any difficulty, please provide a jsfiddle demo with what you have so far. I'll fix the issue and send you back.
