### ISSUE TITLE
RequireJS error in Magento2

### ISSUE THREAD

**Issue by gianisimone** [sachinchoolur/lightGallery#640]
Hi,

thank you for your work, it is very useful. I want to report an issue which occurs if you use your ltest plugin version in Magento 2.1.x.
Trying to include it via RequireJS throws the following error:
```
Uncaught Error: Mismatched anonymous define() module: function (a0) {
      return (factory(a0));
    }
```

Attached there is screenshot of the full stack 
![screen shot 2017-08-11 at 19 12 28](https://user-images.githubusercontent.com/3042801/29224071-0d3920d6-7ec9-11e7-8580-0000142d9acc.png)

I hope you suggest how to solve it.
Thank you again

**Comment by sachinchoolur** [comment]
Hey @gianisimone,
I'm really sorry.  I don't have any idea how Magento works. lightGallery works well with requireJs
I'd suggest you report this to Magento team.

For your reference - 
http://requirejs.org/docs/errors.html (See the first error)
https://stackoverflow.com/questions/15371918/mismatched-anonymous-define-module

**Comment by shkodasv** [comment]
@gianisimone , did you solve the problem ?

**Comment by gianisimone** [comment]
@shkodasv , yes. Now I have it working on my Magento 2.1.x installation. I did nothing to solve this error, just upgraded Magento to 2.1.8 (and then to 2.1.9) and it works.
If this can help you I attach my requirejs-config.js file of my custom theme:
```
var config = {
    "map" : {
        "*" : {
            'lightgallery' : "js/components/lightgallery/dist/js/lightgallery.min",
            'lightgalleryzoom' : "js/components/lg-zoom/dist/lg-zoom.min"
        }
    }
};
```
And this is how I use it:

```
   <script>
        require([
            'jquery',
            'lightgallery'
        ], function ($) {
            require(["lightgalleryzoom"], function(){
                // call function to init lightgallery on single product, installed with bower and used on single product page
                $('#productImageGallery').lightGallery({
                    selector: 'a'
                });
            });
        });
    </script>
```

I hope this can help you.

**Comment by shkodasv** [comment]
@gianisimone thanks!
I implemented module like https://github.com/vmasciotta/magento2-owl-carousel for lightGallery, but it doesn't work. 
will try it now your approach

**Comment by ozgurkaragoz** [comment]
Thank you @gianisimone, it's work!
