### ISSUE TITLE
ICONS missing

### ISSUE THREAD

**Issue by nitinnix** [sachinchoolur/lightGallery#642]
![icons missing](https://user-images.githubusercontent.com/31108838/29426179-6f521df2-83a3-11e7-8ccd-76164d477cc0.JPG)

don't know what to do...

**Comment by sachinchoolur** [comment]
Hey @nitinnix,

Make sure that the font icons are on the correct path. You can also try loading CSS filed from cdnjs - https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.0/css/lightgallery.min.css

Please re-open if the issue persists
