### ISSUE TITLE
Pinterest sharing not working in demo

### ISSUE THREAD

**Issue by kenbond** [sachinchoolur/lightGallery#649]
Hi, I was trying to implement sharing based on your demo [example](http://sachinchoolur.github.io/lightGallery/demos/share.html) and the pinterest doesn't seem to work and returns this error message:
`Parameter 'image_url' (value http:../static/img/13.jpg) is not a valid URL format.`

Thanks!

**Comment by kenbond** [comment]
@sachinchoolur Feel free to downgrade or close this issue. Sharing works with my implementation, so just seems to be an issue with the demo and it's urls.

**Comment by sachinchoolur** [comment]
Hey @kenbond,
Thank you for pointing this out. It used to work with relative URL. But I think we need to provide absolute URL for Pinterest. I'll update the docs.
