### ISSUE TITLE
Comment and thumbnail position settings. 

### ISSUE THREAD

**Issue by sheroqueen** [sachinchoolur/lightGallery#650]
Any options to set the comment and thumbnail position? As like Facebook video viewer. (Thumbnail and comment at right hand side)

**Comment by sachinchoolur** [comment]
Hey @sheroqueen,
Thumbnails and comment box work well together. Plase check the below screenshot and let me know if you have any queries.
![lightgallery comment box](https://user-images.githubusercontent.com/6586706/29855078-1489719a-8d67-11e7-8a5d-ae6e50067ee9.png)
