### ISSUE TITLE
Loading lightgallery-all.min.js from ES6 module

### ISSUE THREAD

**Issue by mtx-z** [sachinchoolur/lightGallery#652]
Hey !

I'm trying to import the lightgallery-all.min.js (using Wordpress Sage template).

What is working (after yarn add all package): 
```
import "lightgallery";
import "lg-zoom";
import "lg-pager";
import "lg-thumbnail";
import "lg-share";
import "lg-fullscreen";
import "lg-pager";
```

What is not : 
```
import "lightgallery/dist/js/lightgallery-all.min";
```

Module is "can't find module". 

Any idea ? thx !

**Comment by sachinchoolur** [comment]
Hey @mtx-z,
Sorry for the delayed response. I missed your message. I'm able to import lightgallery-all.min.js. Let me know if you need a demo.

Closing the issue.

**Comment by mtx-z** [comment]
Hey @sachinchoolur, no problem. Thanks for answering. 

If you have a snippet about the module "import" part, I'd like to check it.

Thanks a lot !

**Comment by sachinchoolur** [comment]
Please shoot me an email @ sachi77n@gmail.com. I'll send you the files

**Comment by majklfly** [comment]
Not sure if it helps in any way...but you import pager twice.  :))) (And thank you, this comment helped me to implement my gallery :) )
