### ISSUE TITLE
Sharting on Pinterest doesn't work

### ISSUE THREAD

**Issue by tobto** [sachinchoolur/lightGallery#653]
Try to implement sharing, but see that sharing to Pinterest sends null info. 
Even [demo](sachinchoolur.github.io/lightGallery/demos/share.html#lg=1&slide=3) sends to Pinterest null. 

Besides, thank you for your hard work!

**Comment by sachinchoolur** [comment]
Hey @tobto,
It's related to https://github.com/sachinchoolur/lightGallery/issues/649

You need to provide absolute URL instead of relative URL in data-src attribute.

For example:

``` html
<li  data-src="../static/img/1.jpg"></li>
```
Should be 
``` html
<li  data-src="http://sachinchoolur.github.io/lightGallery/static/img/1.jpg"> </li>
```
