### ISSUE TITLE
How to add other Share?

### ISSUE THREAD

**Issue by avconsbn** [sachinchoolur/lightGallery#654]
Hi

How to add other Share?
Facebook
Twitter
GooglePlus
Pinterest
- **other Share**
- **other Share**
Thanks

**Comment by sachinchoolur** [comment]
Hey @avconsbn,
At present, lightGallery supports only the above-mentioned share options. I'm working on lightGallery v 2.0 and I'll try to include more share options.

**Comment by englishextra** [comment]
@avconsbn @sachinchoolur
definetly should be customizibale via options. otherwise the plugin is useless. 

Facebook
Twitter
GooglePlus
Pinterest

These aren't popular in my region. At all.
