### ISSUE TITLE
Timeout toggle options autohiding disable

### ISSUE THREAD

**Issue by danb18** [sachinchoolur/lightGallery#655]
Hi, I can see that you have a "setTimeout" adding a class "lg-hide-items" on the toggles when inactive for a few seconds, I am wanting to disable this as I would like these options always showing, how can I do this please?

If you can get back to me as soon as possible, it would be much appreciated! Thank You

**Comment by sachinchoolur** [comment]
Hey @danb18,

At present, there is no default setting to disable auto-hide options. However, as a workaround, you can provide larger number via `hideBarsDelay`

ex:
``` js
$('#lightgallery').lightGallery({
    hideBarsDelay: 6000000 // Controls will be hidden only after 6000000 milliseconds 
});
```

Hope that helps. I'll definitely add an option to disable auto-hide in next major release.
