### ISSUE TITLE
I am getting an error when I want to load the content dynamically

### ISSUE THREAD

**Issue by andreschmid98** [sachinchoolur/lightGallery#656]
`  $('.lightbox_thumbnail').on('click', function() {

      var gallery_json =  '[{"src": "http://localhost:8888/joos-chur.ch/wp-content/uploads/2017/08/00a81fd526d8c5db2c99db59f6c5e977ec0d883a.png","thumb": "http://localhost:8888/joos-chur.ch/wp-content/uploads/2017/08/00a81fd526d8c5db2c99db59f6c5e977ec0d883a.png",},{"src": "http://localhost:8888/joos-chur.ch/wp-content/uploads/2017/08/test-1.png","thumb": "http://localhost:8888/joos-chur.ch/wp-content/uploads/2017/08/test-1.png",},]';
      console.log(gallery_json);

      $(this).lightGallery({
          dynamic: true,
          dynamicEl: gallery_json
      })

  });`

When I write exactly the same that is stored in gallery_json directly to dynamicEl: (as object) it is working but not when I store it in the variable

**Comment by andreschmid98** [comment]
I am getting this errors:
lightgallery.js:4 lightGallery :- data-src is not pvovided on slide item 1. Please make sure the selector property is properly configured. More info - http://sachinchoolur.github.io/lightGallery/demos/html-markup.html

lightGallery :- data-src is not pvovided on slide item 2. Please make sure the selector property is properly configured. More info - http://sachinchoolur.github.io/lightGallery/demos/html-markup.html

**Comment by sachinchoolur** [comment]
Hey @andreschmid98,
Could you please provide a jsfiddle demo which demonstrates the issue?

**Comment by andreschmid98** [comment]
I got an jsfiddle here but it sais $(...).lightGAllery is no t a function (Sorry I am not very familliar with jsfiddle)
The difference between my real code and the jsfiddle is, that I load the content of the page dynamically and I am counting the id #lightbox_thumbnail{{index}} up. and I get the content for gallery_json variable from it  (this is simillar content as the variable gallery_json2 in the jsfiddle)

**Comment by andreschmid98** [comment]
I fixed the problem now (I realized that gallery_json was a string and it should have been an array of objects... and bevore the closing "]" I got a ",")
