### ISSUE TITLE
Thumbnail needed only for the preview within the gallery page, not within gallery itself

### ISSUE THREAD

**Issue by Geo86** [sachinchoolur/lightGallery#658]
Hello,

Is it possible to have a preview image only visible as preview image within my gallery page, but without being displayed within the galery once this one  is clicked ?

You can have a look at the screenshot here It's what I want to explain isn't clear.

<a href="http://www.freeimagehosting.net/commercial-photography/"><img src="http://i.imgur.com/LpzpmyE.jpg" alt="commercial photography locations"></a>

Besides this, thank you for this useful plugin.

**Comment by sachinchoolur** [comment]
Hey @Geo86,

Yes, it is possible. You just need to disable thumbnail from settings.

``` js
$('lightgallery').lightGallery({
    thumbnail: false
})
```

**Comment by Geo86** [comment]
Hello, thank you for your answer. I think I have explained incorrectly my issue. I still want the thumbnails system I just want to disable the thumbnail for the image I click within the gallery, the first one... I haven't found a way to achieve it, I guess the plugins doesn't allow this feature at the moment.
