### ISSUE TITLE
swipe does not work on the last element

### ISSUE THREAD

**Issue by andreschmid98** [sachinchoolur/lightGallery#659]
When I got (for example) 5 images and I want to slide from the 1st to the 2nd it works very good. but when I reach the end end I want to get to the first image again it is not "endless" when I want to swipe. But when I press the arrow button to the right it slides to the first image again.
My options are: 
```
        $(this).lightGallery({
            dynamic: true,
            dynamicEl: gallery_json_object  //array of objects to load images (working)
        })
```

**Comment by sachinchoolur** [comment]
Hey @andreschmid98 ,

It works fine for me. http://sachinchoolur.github.io/lightGallery/demos/dynamic.html
Could you please provide a jsfiddle which demonstrates the problem?

**Comment by sachinchoolur** [comment]
Please re-open if the issue persists
