### ISSUE TITLE
Caption options

### ISSUE THREAD

**Issue by kenbond** [sachinchoolur/lightGallery#662]
Hi, it seems like the caption at the bottom is inherently tied to the thumbnail carousel. I would like to disable the thumbnail carousel but retain the caption. Is that possible? Thanks

**Comment by sachinchoolur** [comment]
Yes, it is possible. Captions and thumbnails work independently. You just need to disable thumbnail from settings. 

``` js
$('lightgallery').lightGallery({
    thumbnail: false
})
