### ISSUE TITLE
LightGallery slide function not updating the index

### ISSUE THREAD

**Issue by Mickyfen17** [sachinchoolur/lightGallery#663]
We are using a few custom buttons to navigate the Gallery to videos, specific images etc. To do this we're using the `slide()` method passing in the index of the first media type attached to that button. The issue that we've ran into is if we are on image 2 of 15, and we click on the custom button which displays image 10 of 15, and then we click the `next` button then it will display image 3 or image 1 if we press the `previous` button.
I've got around this locally by a simple modification within the `slide()` method. But just wanted to know if this default behavior of not updating the index on `slide()` was for a reason and if there was another (preferred) way to update the current image index?
I've checked the docs and searched issues but haven't been able to pinpoint a workaround without modifying the source code locally.

**Comment by sachinchoolur** [comment]
Hey @Mickyfen17,
Thank you for pointing this out. It seems to be a bug :(
I think we should update the index within the `slide()` method as well. I'll update it in the upcoming version. 
For current use, you can set the index before you call the `slide()` method.

ex: 

``` js
var $methods = $('#methods');
$methods.lightGallery();

$('#goto-slide').on('click', function() {
  $methods.data('lightGallery').index = 2;
  $methods.data('lightGallery').slide(2);
});
```
Let me know if you have any queries

**Comment by Mickyfen17** [comment]
Hey @sachinchoolur, Glad it was a bug and not just something I had missed when reading through the documentation 😄 
For the time being, I forked the repo and just decided to alter the slide code to check the if incoming index of the slide method is the same as `_this.index` and if not then update `_this.index` with that incoming index. I've then just had to redirect our package JSON to my forked repo until the fix is within the main code.
I'm happy to create a PR with that fix if it helps you out?

**Comment by sachinchoolur** [comment]
You don't have to modify the source code. Use the below code to update the index.
``` js
$methods.data('lightGallery').index = newIndex;
```
Here is the working demo - https://codepen.io/anon/pen/LjKYQm

Please let me know if you have any questions?

**Comment by Mickyfen17** [comment]
Ok, got it. Cheers.
