### ISSUE TITLE
possible to use or mix with html-only ajax slides?

### ISSUE THREAD

**Issue by derralf** [sachinchoolur/lightGallery#665]
Is it possible to use html-only ajax slides?
Lets say I have a gallery with n images but in between some of the images (or maybe at the end) i want to show a more complex layouted slide with text, lists, columns and maybe some small images (kind of a project description or summay). I would like to load these "special" slides via ajax so i can generate the html/layout using the template engine of the cms. (slide/content shouldn't be loaded in/to an iframe). Additionally, these slides may not have a thumbnail. Would this be possible?

**Comment by sachinchoolur** [comment]
Hey @derralf,
lightGallery is designed specifically for images and videos. It doesn't support html-only ajax slides. But, It is not hard to implement. I'll try to include in version 2.0

**Comment by M-Husein** [comment]
@sachinchoolur  Waiting for version 2.0 ;)
