### ISSUE TITLE
Default wordpress gallery markup

### ISSUE THREAD

**Issue by aitormendez** [sachinchoolur/lightGallery#667]
Hi, I have installed lightgallery succesfully. To make work it I need to write a plugin with custom gallery output to match the Lightgallery needs: https://gist.github.com/aitormendez/1064b7493fe2598a20382424d908e7e1

Is it possible to get lightgallery at work with the default WP markup? (I'm not interested in the WP plugin for now). This is the default markup:

```
<div id="gallery-1" class="gallery">
  <figure class="gallery-item">
    <div class="gallery-icon">
      <a href="#">
        <img src="#">
      </a>
    </div>
  </figure>
  <figure class="gallery-item">
    <div class="gallery-icon">
      <a href="#">
        <img src="#">
      </a>
    </div>
  </figure>
</div>
```

Is it possible to initialize LG with this markup? If yes, how is the JS that I need?

Thank you!

**Comment by sachinchoolur** [comment]
Yes, It is possible. You just need to set `a` tag as the selector. 
``` js
$('.gallery').lightGallery({
    selector: 'a'
});
```
More infor about custom HTML markup - http://sachinchoolur.github.io/lightGallery/demos/html-markup.html
