### ISSUE TITLE
data-src missing just with javascript code

### ISSUE THREAD

**Issue by alvarosps** [sachinchoolur/lightGallery#668]
Hello guys, i'm having some trouble to use the plugin in my website...
It's in NodeJS(using Express and MongoDB)

```
lightgallery.js:442 lightGallery :- data-src is not pvovided on slide item 1. Please make sure the selector property is properly configured. More info - http://sachinchoolur.github.io/lightGallery/demos/html-markup.html
Plugin.isVideo @ lightgallery.js:442
Plugin.loadContent @ lightgallery.js:669
Plugin.slide @ lightgallery.js:907
Plugin.build @ lightgallery.js:232
(anonymous) @ lightgallery.js:212
dispatch @ jquery.min.js:3
q.handle @ jquery.min.js:3
undefined:1 GET http://localhost:3000/undefined 404 (Not Found)
```

keep getting this error, but if I comment my javascript
```
$("#lightgallery").lightGallery({
                thumbnail:true,
                animateThumb: false,
                showThumbByDefault: false
            });
```

the image opens, just not inside the gallery plugin...

my code(in Jade/Pug)
```
.container
            h1.my-4.text-center Galeria de imagens
            .demo-gallery
                #lightgallery.row.text-center.text-lg-left
                    each item, i in galeria
                        .col-lg-3.col-md-4.col-xs-6
                            a.d-block.mb-4.h-100(href='/img/portfolio/#{item.imagem}')
                                img.img-fluid.img-thumbnail(src='/img/portfolio/#{item.imagem}', alt='#{item.nome}')
                                .demo-gallery-poster
                                    img(src='/img/zoom.png')
```

**Comment by alvarosps** [comment]
Solved: the div `.col-lg-3.col-md-4.col-xs-6` (`<div class="col-lg-3 col-md-4 col-xs-6"><a href="" class="d-block mb-4 h-100">`) 

is the problem..I removed it and it works, but now my images are not small anymore..

**Comment by romuloinnocencio** [comment]
Guys, i'm not sure whats happening... here is my generated html:
`<div id="aniimated-thumbnials" class="list-unstyled justified-gallery"> 
   <a href="http://icsl.saolourenco.sc.gov.br/img/noticia/20190528_112557000000.jpg" title="Flic 2019">
      <img src="http://icsl.saolourenco.sc.gov.br/img/noticia/t20190528_112557000000.jpg"">							  
   </a>
</div>`

I have only one picture, but when i open lightgallery, it shows 2 thumbs... (why?)

**Comment by Gyroscope07** [comment]
> I have only one picture, but when i open lightgallery, it shows 2 thumbs... (why?)`
> here is the page, http://icsl.saolourenco.sc.gov.br/noticia/219, at bottom...

Did you figure this out? I'm having the exact same issue.

**Comment by sachinchoolur** [comment]
Hey @Gyroscope07 ,
Could you please share your HTML markup? I think this should be some issue with the selector option
