### ISSUE TITLE
Text Elements on Page Appearing Overtop of Gallery (z-index issue?)

### ISSUE THREAD

**Issue by kevmor11** [sachinchoolur/lightGallery#669]
<img width="1352" alt="screen shot 2017-09-11 at 4 02 49 pm" src="https://user-images.githubusercontent.com/25210432/30300671-c87acbb6-970a-11e7-9883-f400a65a0d39.png">

As you can see in the first screenshot I have some text elements at the top of the page. When I click on the image below to open lightGallery, the text elements still appear overtop of the gallery as you can see in the image below. I have tried editing the z-index so the text elements are below the gallery but that doesn't seem to work.

Any tips as to how I can fix this would be much appreciated, thanks.

<img width="1440" alt="screen shot 2017-09-11 at 4 03 06 pm" src="https://user-images.githubusercontent.com/25210432/30300672-c87e8d0a-970a-11e7-9d9e-c2346d0ea762.png">

**Comment by sachinchoolur** [comment]
It must be z-index issue. Could you please provide a jsfiddle demo or your website URL if available?

**Comment by kevmor11** [comment]
I've tried specifying the z-index of the P tags to be below the
lightGallery div and using !important and it doesn't seem to solve the
issue.

Looking back at it now, it is the elements that are in my header that are
causing that issue so I think that is why it is happening, regardless of
z-index.

If I comment out the header tag then it doesn't seem to happen anymore.

**Comment by kevmor11** [comment]
Oops, I forgot that I had specified the z-index of my header to 9999.

Problem solved, thanks!
