### ISSUE TITLE
Auto fullscreen not working with "hash"-plugin

### ISSUE THREAD

**Issue by dapinododiadeal** [sachinchoolur/lightGallery#670]
I wanted to open lightgallery images in fullscreen by default.
I googled and found this:
https://stackoverflow.com/questions/41187331/how-to-start-lightgallery-in-fullscreen-mode

Works great when clicking thumbnails in an image gallery.
I however found, that upon opening lightgallery-links using the "hash"-plugin (example: gallery.php#lg=1&slide=34) it does not.

Am I missing something?

**Comment by sachinchoolur** [comment]
Hey @dapinododiadeal,

It seems to be a bug. I'll look into it and get back to you as soon as I get it figure it out.

**Comment by sachinchoolur** [comment]
After doing some research, I understood that Fullscreen needs to be triggered via some user events. It can't be triggered on load. 
More info - https://stackoverflow.com/questions/14244397/fullscreen-works-onclick-but-not-onload

However, I'll keep looking for a remedy and get back to you if I get it figured out.

marking as can't fix
