### ISSUE TITLE
Previous Image showing from under the next image

### ISSUE THREAD

**Issue by afshanaman** [sachinchoolur/lightGallery#674]
When the image sizes are different, the previous image show from under the new one.

![image](https://user-images.githubusercontent.com/8959099/30518749-516d260e-9b97-11e7-9471-ff825efd06e6.png)

**Comment by sachinchoolur** [comment]
It works fine for me. There must be some issues with your CSS. It would be helpful if you could provide your website URL or source code

**Comment by afshanaman** [comment]
HTML:
```
<div id="images" class="images" v-if="meta.images && meta.images.length > 0">
            <hr>
            <h4 >Images</h4>
            <div class="imgThumbContainer" v-for="image in meta.images" :data-src="getURL(image)">
                <img  class="imgThumb" :src="getURL(image)" :alt="image.caption" v-on:click="openGallery">
            </div>
        </div>
```
CSS: 
I have not made any changes to your CSS

`
.images{
    width: auto;
    overflow-x: auto;
    overflow-y: hidden;
    white-space: nowrap;
    margin-bottom: 6px;
}
.images > img {
    max-width: 300px;
    max-height: 200px;
    display: inline-block;
    cursor: pointer;
    object-fit: cover;
}
.imgThumbContainer {
    height: 150px;
    width: 150px;
    border: 1px solid white;
    border-radius: 5px;
    display: inline-block;
    overflow: hidden;
    position: relative;
}

.imgThumb {          /* image thumbnails fitted and cropped to the 150x150 container */
    position: absolute;
    left: 50%;
    top: 50%;
    height: 100%;
    width: auto;
    -webkit-transform: translate(-50%,-50%);
    -ms-transform: translate(-50%,-50%);
    transform: translate(-50%,-50%);
    cursor: pointer;
    transition: 0.3s;
}

`

Javascript (Vue)
`
openGallery: function(){
            $('#images').lightGallery({
                selector: '.imgThumbContainer',
                controls: true,
                mode: 'slide',
                speed: 1000,
                loop: true,
                escKey: true,
                closable: false
            })
        }
`
getURL(image) returns the S3 link to the image.

**Comment by afshanaman** [comment]
Resolved it. It was the markup. I switched the markup to the following now: 

HTML:
```
<div id="images" class="images-large" v-if="meta.images && meta.images.length > 0">
                        <hr>
                        <h4 >Images</h4>
                        <div id="lightgallery">
                            <a class="imgThumbContainer" v-for="image in meta.images" :href="getURL(image)">
                                <img  class="imgThumb" :src="getURL(image)" :alt="image.caption" v-on:click="openGallery">
                            </a>
                        </div>
                    </div>
```

and the Javascript to: 

```
$('#lightgallery').lightGallery({
                closable: false
            })
```
