### ISSUE TITLE
hash-plugin bug when using base tag?

### ISSUE THREAD

**Issue by derralf** [sachinchoolur/lightGallery#675]
When using a base tag the hash plugin replaces whole url.
Lets say you use a base tag `<base href="http://my.domain.com/">`
And your gallery is on http://my.domain.com/mygallery
Then the hash plugin should update the url to something like http://my.domain.com/mygallery#lg=1&slide=0
But actually it updates the url to http://my.domain.com/#lg=1&slide=0

Browsers:
Safari 9.1.3
Chrome 60.0.3112.113 
Firefox 54.0.1

**Comment by sachinchoolur** [comment]
Hey @derralf,
Could you please use the bellow hash plugin code and test the issue?
https://raw.githubusercontent.com/poncho7rm/lg-hash/e9a9ff1609910491742464aa1aa940eacce5890c/src/lg-hash.js

**Comment by sachinchoolur** [comment]
The issue has been fixed in version 1.6.3
