### ISSUE TITLE
Mouswheel Zoom

### ISSUE THREAD

**Issue by elisafern12** [sachinchoolur/lightGallery#676]
Hello!

Im trying to disable the mousewheel pager and add a mousewheel zooming instead.
I have done both, but the mousewheel zoom does not work full version/modal of the image. It does works for regular/thumb images, but not when Im in modal mode. I used the correct class but no avail.
Is there something preventing this? 

Im using Jack Moore's Wheelzoom:
https://github.com/jackmoore/wheelzoom

Thank you!

**Comment by sachinchoolur** [comment]
Hey @elisafern12,
Please provide a jsfiddle or codepen dem with what you have so far. I'll try to fix the issue and send you back

**Comment by elisafern12** [comment]
Hey!

Here is a fork of the gallery.

You will see the first image is a standalone image, and along with the thumbnails you can zoom - but not the modal image.

https://codepen.io/alyparker/pen/zEzEwZ

Thanks a lot!

**Comment by elisafern12** [comment]
Hi @sachinchoolur,

Any luck? ;)

Thank you!

**Comment by sachinchoolur** [comment]
Hey @elisafern12,

Sorry for the delay. Here is the updated codepen demo. https://codepen.io/anon/pen/MEQBPY
It is not tested, there are chances of issues. But, hopefully, it will give you a rough idea.

Note: lightGallery lg-zoom plugin is not compatible with wheelzoom plugin. do not use lg-zoom with wheelzoom.

**Comment by elisafern12** [comment]
Hey @sachinchoolur!
Sorry to re-open this case. 

I realized that the built-in zoom option zooms the way I want (no container, panning possible etc). My only request is that the mousewheel acts the same way clicking the zoom does...I tried many things of the months but nothing really works.

Do you have a possible solution or do you so custom work?
Thanks ;)
