### ISSUE TITLE
Caption On/Off toggle

### ISSUE THREAD

**Issue by MatteoZorro** [sachinchoolur/lightGallery#677]
Hi,
The title says almost everything: is it possible to have an On/Off toggle for caption?

In my photo-blog I often use long captions to tell the story, and when seen on a phone they can easily cover half of the photo. It would be great if the user could make the caption disappear after reading. 
Thank you

**Comment by vincent3569** [comment]
I agree with this feature request because I have the same one!

**Comment by arshapro** [comment]
Hello sachinchoolur,
First, thank you for writing this great javascript module! Also, if you added this feature for toggling captions I would make use of that feature.
Best,
Alex

**Comment by MatteoZorro** [comment]
Hello everyone,
Can this help someone to make the plugin?
[](https://github.com/sachinchoolur/lightGallery/issues/420#issuecomment-258753767)

**Comment by kassi** [comment]
I am currently working on a plugin for lightgallery ("lg-info" for now) that a) toggles the title/caption on off and additionally toggles exif information on off (currently moving away from 3 state button to 2 simple buttons inside toolbar).
I wonder if it makes sense to move the caption toggle into a plugin (with extended functionality) or include it as a simple switch into lightgallery.

**Comment by grisinformatica** [comment]
May be an option like hideBarsDelay but for caption. Thanks!

**Comment by AlbertoRutigliano** [comment]
Hi! I'll show you my solution. If you want to force hiding caption bar, you can add to the lightgallery css file :
`.lg-hide-items .lg-sub-html {
  opacity: 0;
  -webkit-transform: translate3d(0, -10px, 0);
  transform: translate3d(0, -10px, 0);
}`
