### ISSUE TITLE
Endpoints of the URL disappears for dynamic gallery ( thumbnail view )

### ISSUE THREAD

**Issue by nickchauhan** [sachinchoolur/lightGallery#678]
I had implement the dynamic gallery with thumbnail view I had used the latest code v1.6.1 and included the lightgallery-all.min.js in my project but whenever I launch the gallery it appends #lg=1&slide=0 this to the url and removes my endpoints of the URL 
Eg
xyz.com/page/test-page 
after launch of the gallery on the page url becomes
xyz.com/#lg=1&slide=0

I have used following script to enable gallery
 $(#mygalleryID).lightGallery({
           dynamic: true,
           html: true,
           mobileSrc: true,
           loop:false,
          dynamicEl: imageArray
});
 
So the URL of the page gets lost.

**Comment by sachinchoolur** [comment]
Hey @nickchauhan,

Could you please use the bellow hash plugin code and test the issue?
https://raw.githubusercontent.com/poncho7rm/lg-hash/e9a9ff1609910491742464aa1aa940eacce5890c/src/lg-hash.js

**Comment by lebitphi** [comment]
@nickchauhan 
$(#mygalleryID).lightGallery({
dynamic: true,
html: true,
mobileSrc: true,
loop:false,
dynamicEl: imageArray,
hash:false

});
I have just it. You only add hash:false to your script code. 
http://giangle.lbp.website/collection/spring-summer-2017-readytoyear
