### ISSUE TITLE
Display PDFs

### ISSUE THREAD

**Issue by lougreenwood** [sachinchoolur/lightGallery#680]
Hi, Is it possible to display PDFs in the full screen view? Perhaps there's some JS plugin I can use which can render PDFs?

Thanks

**Comment by sachinchoolur** [comment]
Hey @lougreenwood,

lightGallery is designed specifically for images and videos. It doesn't support PDF. But, It is not hard to implement. I'll try to include in version 2.0

**Comment by lougreenwood** [comment]
@sachinchoolur I understand that you only intend for it to display images and video, but technically both are just kinds of visual media. Just as a PDF is.

Can we keep this issue open as a feature request for 2.0? Thanks

**Comment by sachinchoolur** [comment]
Done

**Comment by caioferracioli** [comment]
Hi, I really like LightGallery, and it's just extraordinary.
Would you like to view PDF files, any idea when this will be implemented?

**Comment by jrobinsonadrenaline** [comment]
I do this with the current version already, not an issue at all.

```jQuery
  $(this).lightGallery({
      thumbnail: false,
      zoom: false,
      fullScreen: false,
      download: false,
      hideBarsDelay: 1000,
      dynamic: true,
      dynamicEl: [{
          "iframe": "true",
          "src": "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf"
      }]
  });
```

**Comment by gpashis** [comment]
@jrobinsonadrenaline  Getting an error in console after using the above code.

> Resource interpreted as Document but transferred with MIME type application/pdf.

@sachinchoolur Does the newer version supports PDF?

**Comment by rogueathletic** [comment]
the dynamicEL: [{'iframe': !0, "src": https://linkto.pdf}] does work but looses the interactive functionality of zoom, swipe and pinch. Is there another way to format the JS to return this functionality?
