### ISSUE TITLE
FORM action results into lightgallery

### ISSUE THREAD

**Issue by TPave** [sachinchoolur/lightGallery#681]
What is the right way to open form action file results in new iframe lightgallery???
Something like: <form name="OrderFormPM" id="FormPM" action="/asp/Eshop_Send.asp"  method="post" onsubmit="return ???lightgallery???" >

**Comment by sachinchoolur** [comment]
Hey @TPave,
lightGallery is designed specifically for images and videos. It doesn't support HTML contents.
