### ISSUE TITLE
Slide/Url parameters not appended

### ISSUE THREAD

**Issue by nicolaisimonsen** [sachinchoolur/lightGallery#682]
Can't seem to figure out why there's not a linkback to the full url whenever someone uses fb-comments for tagging/linking.

For me: page#lg=16&slide=1 becomes "page?fb_action_ids=......&fb_action_types=og.comments".
In the comment box demo the parameters get appended: og.comments#lg=1&slide=0.

Would really appreciate any advice :)

**Comment by sachinchoolur** [comment]
Hey @nicolaisimonsen,
I'm sorry, I think I didn't get the problem. could you please rephrase your comment?

**Comment by nicolaisimonsen** [comment]
Hey @sachinchoolur 
I guess what I'm asking is how the commentbox demo page manages to set og:url for every slide?
For me, when using facebook object debugger: page#lg=1&slide=1 just becomes page.

**Comment by nicolaisimonsen** [comment]
I need to wake up. Isn't it likely that it's connected to this error?
Uncaught Error: Syntax error, unrecognized expression: #lg=1&slide=0
    at Function.Sizzle.error (jquery.js?ver=0.1:1463)
    at Sizzle.tokenize (jquery.js?ver=0.1:2120)
    at Sizzle.select (jquery.js?ver=0.1:2541)
    at Function.Sizzle [as find] (jquery.js?ver=0.1:864)
    at jQuery.fn.init.find (jquery.js?ver=0.1:2787)
    at new jQuery.fn.init (jquery.js?ver=0.1:2904)
    at jQuery (jquery.js?ver=0.1:75)
    at launch.js?ver=41378278f818db0693f3b2df7ac70d29:15

**Comment by nicolaisimonsen** [comment]
@sachinchoolur 
Please close this issue.
I had some canonical url scripts buried deep inside the wp installation. Found & redefined those.
It's working beautifully now, just like the demo. 
However I am still very interested in knowing how lightGallery sets og:url.

**Comment by sachinchoolur** [comment]
Hey @nicolaisimonsen ,
lightGallery doesn't set og:url. Don't have much idea how it is getting appended.
