### ISSUE TITLE
Zoomed imaged on mobile is not original size

### ISSUE THREAD

**Issue by elisafern12** [sachinchoolur/lightGallery#683]
Hello!

I realized that when we are zoom on a mobile plateform (IOS in my case), the picture is pixalated and doesnt seem to be full res. Is this normal?

Same behavior in the demo.

Thanks!

**Comment by sachinchoolur** [comment]
Hey @elisafern12 ,
At present, there is no limit for zooming. But If you want to see the actual size of the image, double tap on the image or tap on the actual size button on the top toolbar.

In the demo, we use responsive images for mobile devices. So you might not get the full resolution on mobile devices.

Please re-open the issue if you are talking about any different problem. :P
