### ISSUE TITLE
addHtml() should blank its lg-sub-html div when data-sub-html=".caption" refers to nothing

### ISSUE THREAD

**Issue by bborrel** [sachinchoolur/lightGallery#684]
**How to reproduce**

Set a gallery with 3 images the following way:
- 1st image with a <span class="caption">legend 1</span>
- 2nd image without any <span class="caption"></span>
- 3rd image with a <span class="caption">legend 3</span>

Now in the web browser, display the gallery pop-up and navigates through the items. The 2nd image will have its caption set to the previous image's legend.

**Expected behaviour**

The 2nd image's caption should be empty.

**Turnaround**

A turnaround is to provide an empty caption element, but it should be lightGallery's responsibility to reset the lg-sub-html element when data-sub-html=".caption" refers to nothing.

Thanks

**Comment by sachinchoolur** [comment]
Hey @bborrel,
It works fine for me. I followed the same steps you mentioned. But couldn't reproduce the issue. 
Could you please provide a demo which demonstrates the problem?

**Comment by bborrel** [comment]
Hi @sachinchoolur,

Here is the HTML used:
```
<div id="media-gallery-list" class="layout media-gallery-list row size-25" tabindex="-1" style="position: relative; height: 202.312px;">
<a class="col" href="/img1.jpg" data-sub-html=".caption" style="position: absolute; left: 25px; top: 0px;">
    <img src="/img1.jpg" alt="alt 1">
    <span class="caption hidden">
  caption 1
    </span>
</a>
<a class="col" href="/img2.jpg" data-sub-html=".caption" style="position: absolute; left: 352px; top: 0px;">
    <img src="/img2.jpg" alt="">
</a>
<a class="col" href="/img3.jpg" data-sub-html=".caption" style="position: absolute; left: 680px; top: 0px;">
    <img src="/img3.jpg" alt="alt 3">
    <span class="caption hidden">
        caption 3
    </span>
</a>
</div>

```
As you can read above, the 2nd image has no <span class="caption"> element. If I were to apply the turnaround it would have:
```
    <span class="caption hidden">
        
    </span>
```

**Comment by sachinchoolur** [comment]
Hey @bborrel ,
To solve the issue you can simply specify `data-sub-html=""`. Don't have to provide an empty span. lightGallery will automatically ignore the caption for slide 2.
