### ISSUE TITLE
Uncaught ReferenceError: lightGallery is not defined

### ISSUE THREAD

**Issue by Robouste** [sachinchoolur/lightGallery#686]
Hi, 

I can't use LightGallery, maybe I'm missing something but I don't know what to do.

Here is the code : 

```js
var galleryBox = document.getElementById(photosContainerId);

lightGallery(galleryBox, {
	appendSubHtmlTo: '.lg-item',
	thumbnail: false,
	selector: ".gallery-photo"
});
```

I'm using version `1.6.1`

**Comment by Robouste** [comment]
Ok I was using the jquery version of the lightGallery... so the command `bower install lightgallery` install the jquery version

**Comment by sachinchoolur** [comment]
Hey @Robouste,
It is because bower is pointing into jquery version of lightGallery and you are using pure javascript version of lightGallery.

Try `bower install lightgallery.js` instead of `bower install lightgallery`
