### ISSUE TITLE
Additional keyboard bindings

### ISSUE THREAD

**Issue by WojciechMula** [sachinchoolur/lightGallery#687]
First of all, thank you for such a great library!

It would be really nice if both spacebar and enter acted like the right arrow, i.e. move to next image. This feature might be enabled by a new configuration option.

**Comment by sachinchoolur** [comment]
Hey @WojciechMula,
This can be easily done by using lightGallery public methods.

```js
  var $lg = $("#lightgallery");
  $lg.lightGallery(});
  $(document).keypress(function(e) {
    if (e.which === 32 || e.which == 13) {
      $lg.data("lightGallery").goToNextSlide();
    }
  });
```

Let me know if you have any queries

**Comment by WojciechMula** [comment]
@sachinchoolur Thank you, that's a perfect solution. :)

**Comment by Pleizz** [comment]
> Hey @WojciechMula, This can be easily done by using lightGallery public methods.
> 
> ```js
>   var $lg = $("#lightgallery");
>   $lg.lightGallery(});
>   $(document).keypress(function(e) {
>     if (e.which === 32 || e.which == 13) {
>       $lg.data("lightGallery").goToNextSlide();
>     }
>   });
> ```
> 
> Let me know if you have any queries

any way to implement for react..?
