### ISSUE TITLE
A way to prevent image download

### ISSUE THREAD

**Issue by gnium** [sachinchoolur/lightGallery#688]
Hey guys, i've been trying to implement a function to put images as a div with background. However, needs some work to get to the point i'm looking, which is to prevent the right click and save image as.
`$("img.lg-object.lg-image").each(function(i, elem) {
                          var img = $(elem);
                          var div = $("<div />").css({
                            background: "url(" + img.attr("src") + ") no-repeat",
                            width: img.width() + "px",
                            height: img.height() + "px",
                            "vertical-align": "center",
                            "margin": "0px auto"
                          });
                          img.replaceWith(div);
                        });`

Does anybody knows if this exists in a plugin? Also this only applies on the first image, and it's not working on next slides. Any suggestion will be appreciated!

**Comment by sachinchoolur** [comment]
1) If you just wanted to prevent the download image option, you can simply prevent right click option on images .
Try the following code. (Not tested)
``` js
$('body').on('contextmenu', '.lg-image', function(e){
    e.preventDefault();
});
```
2) To make your code work for all the images, you need to listen for lightGallery `onAfterSlide.lg` event and apply the changes.
Docs - http://sachinchoolur.github.io/lightGallery/docs/api.html#events
            http://sachinchoolur.github.io/lightGallery/demos/events.html
