### ISSUE TITLE
Cannot get overlay caption / description to work

### ISSUE THREAD

**Issue by ghost** [sachinchoolur/lightGallery#69]
Hi,
Excellent plug-in you have developed, and many thanks for that!

I'd like to get a caption (e.g. title) of the image as an overlay at the bottom of each picture, but cannot get it to work. In fact, I don't see any caption at all, not even on top of the screen, as is shown in the examples.

My code:

```
<li data-src="/fotos/Foo.jpg" data-html="This is Foo">
  <a href="#"><img src="/fotos/tn_Foo.jpg"></a>
  <br>This is Foo
</li>

<script language="javascript1.2" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script language="javascript1.2" src="/js/lightGallery.min.js"></script>
<script type="text/javascript">
$(document).ready(function() { $("#lightGallery").lightGallery({ counter:true });  });
</script>
```

**Comment by musigeek** [comment]
Hey sachinchoolur, thanks so much for the plugin, it's awesome!
I was following this discussion and went to the jsfiddle to try to understand but I can't make titles/captions work there!!! I wonder what I'm doing wrong? Are they working for you still?
Thanks!

**Comment by sachinchoolur** [comment]
The above jsfiddle was using older lightgallery syntax. It has been updated in the new version 1.1.4  Here is the updated jsfiddle http://jsfiddle.net/sachin377/hg5nmj39/8/ 

Updates :-
change data-html to data-sub-html.
`html: true` in the setting is not required in the newer version

**Comment by musigeek** [comment]
Thanks so much for responding so fast. Appreciate the update.
Andrew

**Comment by gmnorris** [comment]
So how would you go about adding links within the captions? Couldn't figure out where to begin. Any help would be greatly appreciated!!

**Comment by sachinchoolur** [comment]
You can add anchor tag inside data-sub-html attribute .
Here is the demo http://jsfiddle.net/hg5nmj39/12/

**Comment by blockb** [comment]
Niether of the jsfiddles works. Can you update?
