### ISSUE TITLE
Comments demo is broken in Mobile. 

### ISSUE THREAD

**Issue by alexjose** [sachinchoolur/lightGallery#693]
Hi,

The view is broken in when Facebook comment is added. Not able to see the pic or video. Not even able to close the box.

[Comments Demo](http://sachinchoolur.github.io/lightGallery/demos/comment-box.html#lg=1&slide=0)

Please have a look.

**Comment by sachinchoolur** [comment]
Hey @alexjose,

This is just a demo to show how to implement facebook comments with lightGallery. You can easily update the css to make the demo responsive.

Send me an email a2 sachi77n@gmail.com if you want the responsive version of the demo
