### ISSUE TITLE
Angular 4 implementation

### ISSUE THREAD

**Issue by mohinithorat** [sachinchoolur/lightGallery#694]
Is there any way to implement in Angular2/4

**Comment by talalhaider** [comment]
When can you update it on NPM with angular 4 support?
I would like to use it for my app.

**Comment by sachinchoolur** [comment]
I know this thread is really old. But in case if anyone else is looking for a solution, please follow the below steps 


#### Step 1
Include jQuery in you project.

Take a look at the [StackOverflow answer](https://stackoverflow.com/questions/43934727/how-to-use-jquery-plugin-with-angular-4) for reference - 

#### Step 2
Install lightgallery package via npm

`npm install lightgallery`

Install required [plugin ](https://github.com/sachinchoolur/lightGallery#modules) (optional)

`npm install lg-zoom lg-share`


#### Step 3

Add lightgallery to the runtime global scope

 1) Add lightgallery.js and it's plugins path to the `scripts` field in the angular.json file
 
```
"scripts": [
  "node_modules/jquery/dist/jquery.min.js",
  "node_modules/lightgallery/dist/js/lightgallery.js",
  "node_modules/lg-zoom/dist/lg-zoom.js"
]
```

2) Add lightgallery.css path to the `styles` field in the angular.json file
```
"styles": [
  "node_modules/lightgallery/dist/css/lightgallery.css",
],
```

#### Step 4
Define typings for lightgallery.js

In `src/typings.d.ts` add the following line 

`declare var lightGallery: any;` 

#### Step 5

Invoke lightgallery

``` ts
ngOnInit() {
  ($('#lightgallery') as any).lightGallery();
}

```
-----------------------------

I've also created a repository with the demo. - https://github.com/sachinchoolur/lightgallery-anguar-demo
