### ISSUE TITLE
Slideshow as autoplay

### ISSUE THREAD

**Issue by fredbcode** [sachinchoolur/lightGallery#695]
The slideshow automatically fade to the next slide after the specified seconds, but there is a way to start automatically the slideshow himself ?

I mean, I click to a picture and the slideshow begins ?

**Comment by sachinchoolur** [comment]
Yes, It is possible. You just need to pass `autoplay: true` via settings

Here is the demo - https://codepen.io/anon/pen/yzmKXX

**Comment by fredbcode** [comment]
Thanks maybe I'm wrong but the documentation seems only related with videos, not pictures 

----- Mail original -----

**Comment by moncero** [comment]
fredbcode has right, the autoplay **NOT** start automatically with pictures.
