### ISSUE TITLE
Launching the gallery from an external button

### ISSUE THREAD

**Issue by dreamzsiva** [sachinchoolur/lightGallery#7]
I absolutely love this plugin, its simple to use and looks gorgeous! 
Can I launch the gallery by clicking a button which is outside the div containing the images on the same page?

<button>Click to launch gallery</button>

<ul class="lightGallery">
<li>img</li>
<li>img</li>
</ul>

thanks

**Comment by dougfabris** [comment]
Thank you so much Sachin! That worked and save me
