### ISSUE TITLE
More image extensions in one go like webp and jpg let the browser choose

### ISSUE THREAD

**Issue by Allmedialab** [sachinchoolur/lightGallery#702]
Hi Sachin,
Your beautiful Light Gallery works only on one image extension at the time jpg, webp or whatever, but what is missing is the possibility to use multiple image extensions at the same time in the html and let the browser choose jpg or webp or else.
Regards,
David

**Comment by goonydev** [comment]
Please consider this request, dev.

The plugin uses regular <img> tags, so it might be very easy to just add a fallback <img> tag so we can use webp. At the moment using webp images make the lightgallery un-usable on mobile devices for websites trying to switch to webp.

it could be used like :

data-src="first_source.jpg" data-src-fallback="second_source.jpg"

So when there is a fallback you could build a <img fallback> tag.

**Comment by Tashows** [comment]
This would be very very useful!

**Comment by TVBZ** [comment]
I agree, it's a missing feature. 
I would like to use webp and jp2 for modern browsers, and jpg as fallback for IE and other dinosaurs.

**Comment by sachinchoolur** [comment]
HTML5 picture tag is now supported in lightGallery v2 - https://www.lightgalleryjs.com/demos/responsive/
