### ISSUE TITLE
Changing Previous/Next buttons to different Icons

### ISSUE THREAD

**Issue by kevmor11** [sachinchoolur/lightGallery#703]
I've seen previous issues on this same subject, but I wasn't really able to find an answer.

Is anyone able to point me in the right place as to where the actual icons are being generated? Surely it must be CSV or an image file? But I can't seem to find it.

All I want to to is change the icon to look more minimal by removing the middle line from the arrow.

Should be easy to accomplish but I can't seem to find where the actual icon itself is generated.

**Comment by Allmedialab** [comment]
Hi,
They are in the dist>fonts folder and contain lg.eot, lg.sgg, lg.ttf and lg.woff. The fonts are linked from the top of the lightgallery.css 
With this App you can edit fonts download them and replace them:
https://icomoon.io/app/#/select
Good luck,
David

**Comment by kevmor11** [comment]
Great thanks.

Little bit confusing but I figured it out eventually.
