### ISSUE TITLE
am using angularjs framework with jQuery v2.1.3 in this application this lightgallery not working

### ISSUE THREAD

**Issue by subhashekkaluru** [sachinchoolur/lightGallery#704]
hi,

am using angularjs framework with jQuery v2.1.3 in this application this lightgallery not working
could you please guide me how to integrate this one

thank you

**Comment by sachinchoolur** [comment]
Which version of angualrJs do you use? Here is the example for 1.x - https://stackoverflow.com/questions/30220165/lightgallery-jquery-plugin-in-angularjs

I'll try to create an example for angualrJs above 2.0 by next week
