### ISSUE TITLE
Option enquiry for not autoplaying a Youtube video in light gallery

### ISSUE THREAD

**Issue by jitendersandhu** [sachinchoolur/lightGallery#707]
Hi @sachinchoolur,

First of all, thanks for an awesome plugin.

I have a use case where, i need to load a Youtube video in `lightgallery` and not `autoplay` the video, instead have the user click on the youtube play button to play the video. Is there an option currently for this or is it feasible to add an option to **not** autoplay video when loaded in `lightgallery`. Any help would be much appreciated!

Thanks,
Jitender Singh

**Comment by sachinchoolur** [comment]
Working on it. Probably by tomorrow I'll release a new version with this option.

**Comment by sachinchoolur** [comment]
Hey @jitendersandhu,
The issue has been resolved. Now you can enable/disable first videos autoplay via `autoplayFirstVideo`. Use the latest version of lg-video.js

**Comment by sachinchoolur** [comment]
Docs- http://sachinchoolur.github.io/lightGallery/docs/api.html#lg-video
