### ISSUE TITLE
Looking for code example of lightGallery with justifiedGallery that works like lightGallery demo

### ISSUE THREAD

**Issue by CCCullens** [sachinchoolur/lightGallery#708]
Hi Sachin
Can you create a complete example that implements exactly what you have on the thumbnails demo page. Including the magnifying glass icon?

thanks

**Comment by sachinchoolur** [comment]
Hey @CCCullens,
Demo - https://codepen.io/anon/pen/BmRPeb
Let me know if you have any queries

**Comment by CCCullens** [comment]
Thank you!! I'm learning CSS is powerful, thanks!
