### ISSUE TITLE
Feature Request: Support Typescript + ReactJS

### ISSUE THREAD

**Issue by developer-lindner** [sachinchoolur/lightGallery#709]
Would be nice to have lightGallery available in modern environments... maybe without jQuery dependency too ?! To use jQuery just for some markup lookups / css modifications is a bit overkill...

**Comment by sachinchoolur** [comment]
Hey @developer-lindner,
Vanilla js version of lightGallery is already available - https://github.com/sachinchoolur/lightgallery.js
I'm working on lightGallery version 2.0 and thinking of using Typescript. But not confirmed.

At present, we don't have a react component for lightGallery. But' I'll try to create when I get time (no timeline :P)

**Comment by developer-lindner** [comment]
@sachinchoolur Maybe some of could help you ?! lightgallery v2 as es6 module would be very helpful

**Comment by sachinchoolur** [comment]
lightGallery already supports es6 modules. :)

**Comment by developer-lindner** [comment]
@sachinchoolur Well it does, but it depends on jQuery :(
