### ISSUE TITLE
 Feature request: Click, then change pictures

### ISSUE THREAD

**Issue by watarumohawk** [sachinchoolur/lightGallery#71]
Hi,

I'd like to change pictures (both of next and previous) like Twitter photo gallery. 
When I click the right part of picture, next picture appears. When I click the left part of picture, previous picture appears.

I think if this feature come true,  lightGallery would be a more great plugin.

Regard

Wataru Sekiguchi

**Comment by koolleer** [comment]
My english very bad. But translate google help me.
Add this code:
in **var default = { }** add 
    **clickImage: true,**
in **Plugin.prototype.build = function(index) {}** after  **_this.slide(index, false, false);** add
    **if (_this.s.clickImage) {
        _this.clickImage();
    }**
And add
**Plugin.prototype.clickImage = function() {
    var _this = this;
    if (this.$items.length > 1) {
        $(windows).on('click.lg',function(e) {
        if ($(e.target).hasClasses('lg-object')) {
            e.preventDefault();
            _this.goToNextSlide();
        }
     });
 }
}**
If needed, it can be to switch to the left and the right.

**Comment by koolleer** [comment]
Plugin.prototype.clickImage = function() {
        var _this = this;
        if (this.$items.length > 1) {
            $(window).on('click.lg', function(e) {
                if ($(e.target).hasClass('lg-object')) {
                    e.preventDefault();
                    _this.offsetTop = e.target.offsetTop;
                    _this.offsetLeft = e.target.offsetLeft;
                    _this.offsetWidth = e.target.offsetWidth;
                    _this.clientX = e.clientX;
                    _this.center = _this.offsetLeft + (_this.offsetWidth / 2);
                    if (_this.clientX < _this.center)
                        _this.goToPrevSlide();
                    else 
                        _this.goToNextSlide();
                } 
            });
        }
    }
