### ISSUE TITLE
Go to next image on hover

### ISSUE THREAD

**Issue by mbh00** [sachinchoolur/lightGallery#710]
Hello,
This is an awesome piece of code. Great job !
I am planning to integrate this gallery in my next project. But is it possible to go to prev/next image just by thumbnail hover, or i need some customization ?

**Comment by sachinchoolur** [comment]
It is not possible by default.  But, you can easily achieve this by using lightGallery events and methods.

I've created a demo for you with basic functionality for your reference. - https://codepen.io/anon/pen/POJoRK?editors=1010

Let me know if you have any queries

**Comment by mbh00** [comment]
Thank so much.
Please another question.
If i wish to open the gallery from a button or link in html, which code show i bind to the click event?
I didn't see a method for  that
