### ISSUE TITLE
Disable specific thumbnails

### ISSUE THREAD

**Issue by WOWDS** [sachinchoolur/lightGallery#711]
Hi

Is there a way of disabling thumbnails from the slide-show and from being expandable?

I have an A-Z list of images, with the letters A to Z as images in one of the li fields. I don't need or want these images to expand when clicked or to be part of the slide-show.

![screenshot 2017-11-15 15 47 33](https://user-images.githubusercontent.com/10980516/32845324-5d519c8a-ca1c-11e7-9b0c-11ff4e6e03b5.png)

I've added php code to detect if the first 4 characters does not equal "**cap-**" (as the A to Z images are all saved as cap-a.gif, cap-b-gif etc.) if it does not equal that, display the full code that includes the **data-src=""** and **data-sub-html=""**, else it simply displays:

**`<li><img src="http://www.domainname/cap-a.gif" alt="Capital letter A"></li>`**

Doing this only means that the slide-show doesn't look for a large image, but the thumbnail can still be clicked and a blank space displays in the slide-show.

Is there a way of excluding/disabling certain images from being clicked or displaying in the slideshow?

Kindest regards
Glynn

**Comment by sachinchoolur** [comment]
Yes, It is possible by using selector property.  -http://sachinchoolur.github.io/lightGallery/demos/html-markup.html 

In your case, Try to use the following html markup and javascript
``` html
<ul id="lightgallery">
<li class="include-in-gallery"><img src="a.gif" alt="Capital letter A"></li>
<li><img src="a.gif" alt="Capital letter A"></li>
<li class="include-in-gallery"><img src="a.gif" alt="Capital letter A"></li>
</ul>
```

``` js
$('#lightgallery').lightGallery({
    // Only first and last images will be displayed in the gallery 
    selector: '.include-in-gallery'
});
```

Let me know if you have any queries
