### ISSUE TITLE
Multiple video dimension

### ISSUE THREAD

**Issue by culbrique** [sachinchoolur/lightGallery#712]
Hi !

Your plugin is great and easy to custom for images, but we can't display different video dimensions !
I saw previous posts and you say to change `videoMaxWidth` and `.lg-video`...this works for one or multiple video with same ratio, but how can I do with multiple videos with different dimensions ?

Couldn't be more efficient to add a `data-video-width` and `data-video-height` attribute ?

Please help me, I don't want to change plugin !

**Comment by sachinchoolur** [comment]
I'll try to include an option to provide custom dimensions for videos in version 2.0.
For current use, you can use the following workaround.

``` js
$(document).ready(function() {
    var $lg = $("#lightgallery");
    $lg.lightGallery();

    $lg.on("onAferAppendSlide.lg", function(event, index) {
        var $videoCont = $lg.data("lightGallery").$slide.eq(index).find(".lg-video-cont");
        setTimeout(function() {
            $videoCont.css("max-width", $lg.data("lightGallery").$items.eq(index).data("video-width") + "px");
        });
    });
});
```

Codepen Demo - https://codepen.io/anon/pen/JOLedN?editors=1010

**Comment by culbrique** [comment]
Thank you very much for your reply ! The code is working perfectly.

One last thing : if I can't adjust dynamically the padding-bottom of `.lg-video` with a `data-height` (for example) , the data-poster image is streched and the video played is shown with a black background just behind. 
This is due to the padding-bottom value that is working for all videos, so if I can't set height to my videos with your code bellow, the videos will never be framed at the right size. :/

Just try to link your code with a vertical 16:9 ratio video for example, and you'll see it
