### ISSUE TITLE
Thumbnail images: src is undefined

### ISSUE THREAD

**Issue by bcoelhonqda** [sachinchoolur/lightGallery#714]
Hi,

Without the <img> (using data-src and href) the thumbnail images is not working. Thumbnails images is undefined.
Something is missing? 

Example:
https://jsfiddle.net/a7a3ckm9/3/

**Comment by sachinchoolur** [comment]
Hey @bcoelhonqda,
By default, lightGallery takes thumbnails within the selector. In this case, you don't have an image to set as thumbnail inside the selector.

You can use setting `exThumbImage` to set custom thumbnails.
Here is the working fiddle : - https://jsfiddle.net/a7a3ckm9/4/
Docs: http://sachinchoolur.github.io/lightGallery/docs/api.html

let me know if you have any questions

**Comment by bcoelhonqda** [comment]
In the past i used "data-thumb" but now i see its different.

@sachinchoolur thanks.

**Comment by Rkvasu** [comment]
hello sir I have an issue with the light gallery can you provide a solution.
Subject:- automatically generate img="undefined" how to solve this issue can you provide be the solution.
attached screenshot:-
https://prnt.sc/26b2wkr
https://prnt.sc/26b2x01

**Comment by Rkvasu** [comment]
hello sir I have an issue with the light gallery can you provide a solution.
Subject:- automatically generate img="undefined" how to solve this issue can you provide be the solution.
attached screenshot:-
https://prnt.sc/26b2wkr
https://prnt.sc/26b2x01
@sachinchoolur
