### ISSUE TITLE
 Not allowed to navigate top frame to data URL

### ISSUE THREAD

**Issue by lakinmohapatra** [sachinchoolur/lightGallery#717]
I included base64 images . But after opening first image , its unble to opne second image on click.
Showing this error : Not allowed to navigate top frame to data URL: data:image/png;base64,

**Comment by sachinchoolur** [comment]
It works fine for me - Demo - https://codepen.io/anon/pen/EbJGgE

It must be some issue with your image. Please provide a jsfiddle demo.
