### ISSUE TITLE
Add composer support

### ISSUE THREAD

**Issue by humbkr** [sachinchoolur/lightGallery#719]
Hello,

It would be really useful for php devs to have composer support.

I had a small issue when I tried for example to install a Drupal module based on this plugin, https://www.drupal.org/project/lightgallery, where manually referencing lightGallery repository was mandatory in order to make the install work with composer.
This is not very straitforward for new devs.

You will have publish a composer package on packagist.org: https://packagist.org/about

**Comment by fabianmarz** [comment]
There is [https://asset-packagist.org](https://asset-packagist.org/package/search?query=lightgallery&platform=bower%2Cnpm) available. There is no need to create a `composer.json` for this module. [Here](https://lightning.acquia.com/blog/round-your-front-end-javascript-libraries-composer) is a short article about how to use asset packagist in your Drupal composer version.
