### ISSUE TITLE
Hint: No support for WindowsPhone 7

### ISSUE THREAD

**Issue by derSteffen** [sachinchoolur/lightGallery#72]
Hello,

the old version from the script  "runs" on WIndowsPhone 7 with OS 7.5 the new version from the script doesnt work on 7.5.

Greetings

**Comment by simar88** [comment]
Hi @derSteffen so if i would like to play in windows phone i have to use 1.1.3?
Because i've some problem with this mobile OS.
Thanks you in advance.

**Comment by derSteffen** [comment]
Hello .... yes, my hint with the windows phone 7 (IE) - Problem was by the new 1.1.3 version of lightGallery.
Now the gallery will only shown in the top of the page and the touch-swipe-effect isn't going!

In the "old" version of lightGallery the swipe-Toch foes and the gallery will be shown in the middle of he window! But maybe it could be a problem of new jquery-version!

WindowsPhone7 sucks! :-)
