### ISSUE TITLE
Image fadeout broken in Firefox Quantum (v57.0)

### ISSUE THREAD

**Issue by fenisteel** [sachinchoolur/lightGallery#723]
When slide from one image to another (with swiping or pressing the arrows), the image that outsliding is not faded, but disappearing immediately. It works in Chrome, but not in the newest Firefox.

**Comment by swiderski** [comment]
This is still true, and can be viewed on default demo here http://sachinchoolur.github.io/lightGallery/
Animation is broken on Firefox in compare to Chrome. 
I use on my install version 1.6.4 and it is broken there also, so it can be longer issue, or just FireFox changed something.

On Chrome & Edge it works fine.

**Comment by aitormendez** [comment]
TO FIX:

Change:
`transition: transform 1s cubic-bezier(0, 0, 0.25, 1) 0.5s`

to
`transition: transform cubic-bezier(0, 0, 0.25, 1) 0.5s`

```
// hack lightgallery slider bug:
// https://github.com/sachinchoolur/lightGallery/issues/723
.lg-css3.lg-slide.lg-use-css3 .lg-item.lg-current,
.lg-css3.lg-slide.lg-use-css3 .lg-item.lg-next-slide,
.lg-css3.lg-slide.lg-use-css3 .lg-item.lg-prev-slide {
  transition: transform cubic-bezier(0, 0, 0.25, 1) 0.5s !important;
}
```
