### ISSUE TITLE
Autoplay on videos  not working as intended

### ISSUE THREAD

**Issue by vinogmca** [sachinchoolur/lightGallery#725]
Hi,

If I click on the "Auto play", the current video will play (if it's not playing) and if it ends, it'll move on to the next video  automatically. 

The above statement is not happening using light gallery. By default autoplay enabled with 5000ms so when the video is running after 5000 ms it's moving to next video irrespective of video ends or not and next video not playing automatically. is there any way to control this? we want video to finish before moving to next video using auto play(i.e) dynamic pause configuration.

**Comment by sachinchoolur** [comment]
Hey @vinogmca,
At present this is not possible. But I'll try to include in version 2.0

**Comment by aroncatti** [comment]
Hi. Is this now possible? I have the same issue, autoplay does not wait for video to end and goes automatically to next slide after 5000 ms. 
I will appreciate any help on this.
Thanks
