### ISSUE TITLE
watermark

### ISSUE THREAD

**Issue by includebrasil** [sachinchoolur/lightGallery#726]
Hello, is it possible to insert a watermark in the gallery images?

**Comment by makshh** [comment]
@includebrasil It's not possible only with lightGallery plugin. It has nothing to do with watermarks.

For that you can use for example [watermark.js](http://brianium.github.io/watermarkjs/images.html)

**Comment by includebrasil** [comment]
Do you know any examples of watermark.js with lightGallery? I'm trying to implement but I could not.

**Comment by sachinchoolur** [comment]
Hey @includebrasil,

The following code works fine for me.
``` js
var noRendered = 0;
$('#lightgallery').children().each(function() {
    var $img = $(this);
    var imgurl = $(this).attr('data-src');
    watermark([imgurl, 'logo.png'])
        .dataUrl(watermark.image.upperRight(1))
        .then(function(img) {
            noRendered++;
            $img.attr('data-src', img);
        });
});
var timeout = setInterval(function() {
    if (noRendered === $('#lightgallery').children().length) {
        $('#lightgallery').lightGallery();
        clearTimeout(timeout);
    }
}, 500);

```

**Comment by includebrasil** [comment]
Hey @sachinchoolur,

Sorry for the delay!

Your code gave me a light. But unfortunately I could not implement!

This is my code snippet used in the gallery, how can I implement the code you passed me?

`
        <script type="text/javascript">
          $('#dynamic').on('click', function() {
      
    $(this).lightGallery({
        autoplayControls: false,
        share: false,
        zoom: false,
        dynamic: true,        
        dynamicEl: [               
                    <?php for($i = 0; $i < count($fotos); $i++){ ?>
                        {
                            "src": '<?php echo $sis_base['dominio'];?>/painel/subdominios/<?php echo $idsistema;?>/fotos/<?php echo $imovel['id_imovel']; ?>/<?php echo $fotos[$i];?>',
                            'thumb': '<?php echo $sis_base['dominio'];?>/painel/subdominios/<?php echo $idsistema;?>/fotos/<?php echo $imovel['id_imovel']; ?>/<?php echo "400_".$fotos[$i];?>',
                            'subHtml': '<h4><?php echo $fotos_legenda[$fotos[$i]]; ?><h4>'
                        },
                    <?php } ?>
          ]})
 
    });
          </script>
        `
