### ISSUE TITLE
Hash plugin bug - removes GET params

### ISSUE THREAD

**Issue by luzik** [sachinchoolur/lightGallery#728]
Hash plugin work fine only when gallery url ends with /
`http://host/mar/?gallery=subgallery` change into -> `http://host/mar/#lg=1&slide=8`
when it should be `http://host/mar/?gallery=subgallery#lg=1&slide=8`

**Comment by sachinchoolur** [comment]
Hey @luzik,

Thank you for pointing this out. The issue has been fixed. Please use the latest version of hash plugin
