### ISSUE TITLE
Loop attributes doesn't traverse in opposite way

### ISSUE THREAD

**Issue by MFQ** [sachinchoolur/lightGallery#729]
Hi 

I was using loop feature properly for 'mode: lg-slide' it was working fine for both froward and backward transition. When I switched my 'mode: lg-fade'  it disabled slider's back button for transition backward. Loop is working fine forward transition but it is not working for the backward transition.

**Comment by sachinchoolur** [comment]
Hey @MFQ,
Sorry for the delayed response. It works fine for me. Could you please provide a jsfiddle which demonstrates the issue?
