### ISSUE TITLE
Mixed Content (Images, Videos)

### ISSUE THREAD

**Issue by vdanelia** [sachinchoolur/lightGallery#732]
Seems very easy but, very confusive...

How to configure LG with mixed content (with images, video and audio) can't find any demo about it....
Can you give me a step by step instruction?

Thank you

**Comment by strech345** [comment]
I'm also searching for a solution for video and images :-(

**Comment by sachinchoolur** [comment]
Hey guys,

Here is the demo - https://codepen.io/sachinchoolur/pen/jGQYXZ

Let me know if u have any queries
