### ISSUE TITLE
Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by haoguobao** [sachinchoolur/lightGallery#734]
I want to use the latest version 1.6.6 in 'Vue' project
`import` $ from 'jquery'
`import` '../../js/lightgallery-all.min'

I have installed jquery by npm. But the browser console still shows **'Cannot read property 'fn' of undefined**'

Then how I use 1.6.6 in ES6 project? Thanks

**Comment by sachinchoolur** [comment]
Hey @haoguobao,

Pls try using the below code
``` js
import "lightgallery";
import "lg-zoom";
import "lg-pager";
import "lg-thumbnail";
import "lg-share";
import "lg-fullscreen";
import "lg-pager";
```

let me know if u face any problem

**Comment by haoguobao** [comment]
Thanks for your help

**Comment by Ibrahimmousa1999** [comment]
please help
i want videos and images in lightGallery
i get this error Uncaught TypeError: Cannot read properties of undefined (reading 'fn')
i use jquery
