### ISSUE TITLE
Thumbs missing alt and title

### ISSUE THREAD

**Issue by semaf** [sachinchoolur/lightGallery#735]
I set alt and title to thumbs but they are not set in output.

```
<li data-thumb="{$oBild->cPfadMini}" data-src="{$oBild->cPfadGross}">
    <img src="{$oBild->cPfadNormal}" title="{$Artikel->cName}" class="img-responsive" alt="{$Artikel->cName}" itemprop="image" />
</li>
```

The output:
```
<li style="width:100%;width:56.333333333333336px;margin-right:5px">
    <a href="#"><img src="image.jpg"></a>
</li>
```

**Comment by sachinchoolur** [comment]
Hey @semaf,
You need to pass `getCaptionFromTitleOrAlt:true` via settings 

$('#lightgallery').lightGallery({
    getCaptionFromTitleOrAlt: true
});

Docs - http://sachinchoolur.github.io/lightGallery/docs/api.html
