### ISSUE TITLE
dynamicEl bug

### ISSUE THREAD

**Issue by haoguobao** [sachinchoolur/lightGallery#736]
I use the latest version in my web which has many image list.
I want to generate a new lightGallery when clicking any image like below codes
`<button type="button" id="btn">按钮</button>`

`<div class="demo-gallery"><div id="lightgallery"></div></div>`

``` js
var i = 4;
 $("#btn").on("click", function () {
                var arr = [{src: './img/00' + i + '.jpg'}]
                $('#lightgallery').lightGallery({
                    loop: true,
                    auto: true,
                    pause: 4000,
                    dynamic: true,
                    dynamicEl: arr
                })
		i++;
            })
```

The arr stores a new json including image src when clicking the button, then transform the arr to lightGallery instance.

But I find lightGallery instance always displays the first image I click instead of the new image src stored in the arr

**Comment by sachinchoolur** [comment]
Hey @haoguobao,

Please provide a jsfiddle demo with what you have so far. I'll fix the issue and sed you back

**Comment by wilywork** [comment]
clear old lightGallery, use:

`
$('#lightgallery').data("lightGallery", "");
`
