### ISSUE TITLE
Suggestions after the end of the Vimeo video

### ISSUE THREAD

**Issue by GPooja** [sachinchoolur/lightGallery#737]
Hi,
While trying to load a video from YouTube in the gallery, the auto suggestions that come up after the end of the video can be turned off using the **rel** option.

Is there any similar way to turn off the same suggestions appearing after the end of a
 video from Vimeo?

![vimeo suggestion snapshot](https://user-images.githubusercontent.com/12708545/34483673-0e71c42e-efe6-11e7-9399-f797864569b1.PNG)

**Comment by sachinchoolur** [comment]
Hey @GPooja,

I haven't tried this yet. The below link might help you https://answers.squarespace.com/questions/64942/video-block-how-can-i-turn-off-the-related-videos-that-appear-from-vimeo-links-after-the-video-plays-more-from-brand.html
