### ISSUE TITLE
Video docs out of sync with current code?

### ISSUE THREAD

**Issue by dogweather** [sachinchoolur/lightGallery#738]
I tried to implement a video gallery according to the docs here http://sachinchoolur.github.io/lightGallery/demos/videos.html and I got no result, as if the JS didn't execute. And when I look at the source for that page, it doesn't resemble the docs at all. E.g., the video URLs are in `data-url` attributes or an enclosing div, not in the A's href.

So I'm wondering if the docs are out of date?

**Comment by sachinchoolur** [comment]
Hey @dogweather,
It can be either `data-src` or `href`.

Here is the demo - https://codepen.io/sachinchoolur/pen/XNavPP/
Docs: - http://sachinchoolur.github.io/lightGallery/docs/api.html#attributes
http://sachinchoolur.github.io/lightGallery/demos/html-markup.html

Let me know if you have any queries.
