### ISSUE TITLE
Zoom 500x3000 image.

### ISSUE THREAD

**Issue by ghost** [sachinchoolur/lightGallery#743]
If an image has 500px (width) with 3000px (height) and you try to zoom by clicking on image at (ex) 450px (width), the image is zoomed and positioned at the left of screen, and is not movable, even if the image is fully in view by width.

Another example is on image with 2000x500 px. If you click at position 10px (from height), on my screen, the image is not movable and it's out of my screen...

I'm sure that this is not ok.

I made 2 prints, after zoom, to understand.

Maybe the image must be centered as is still in view.

One thing: I remove (hide) zoom-in and zoom out icons and I use just double click to zoom-in and zoom-out as I saw that there is no option for maxim zoom.... I hope you understand what I'm saying... zooming with double click makes the zoom as image width/height and not bigger, which is what I want.

![print](https://user-images.githubusercontent.com/31676567/34860445-1c23a27c-f766-11e7-8731-64438ddeda3f.jpg)
![print_2](https://user-images.githubusercontent.com/31676567/34861051-8ca35e9e-f76a-11e7-917b-2bf20efa8a33.png)

**Comment by sachinchoolur** [comment]
Please reopen is the issue persists in v2
