### ISSUE TITLE
When trying to open an specific photo in dynamic mode, I get "Cannot read property 'poster' of undefined"

### ISSUE THREAD

**Issue by jakeline-santos-apontador** [sachinchoolur/lightGallery#746]
I'm trying to open specific images in a dynamic gallery. I managed to make it happen perfectly with the code below, but it keeps throwing this "Cannot read property 'poster' of undefined" error. 

`$('.show-gallery').on('click', function() {
	var slideToOpen = $(this).attr('data-index');

    $(this).lightGallery({
    	thumbnail:true,
        dynamic: true,
        dynamicEl: [
        {
            "src": 'image src',
            'thumb': 'image src',
            "subHtml": 'some caption'
        },
        ]
    }).on('onAfterOpen.lg',function(){
	    $(this).data('lightGallery').slide(slideToOpen);
	});
});`

HTML for each button goes like this:
`<li class="show-gallery" data-index="[index number]"><img src="[image src]" /></li>`

**Comment by sachinchoolur** [comment]
Hey @jakeline-santos-apontador,
You can use setting `index` to open specific slide. - docs - http://sachinchoolur.github.io/lightGallery/docs/api.html#passing-options

Plese use the below code and let me know the result.
``` js
$('.show-gallery').on('click', function() {
    var slideToOpen = $(this).attr('data-index');

    $(this).lightGallery({
        thumbnail: true,
        dynamic: true,
        index: parseInt(slideToOpen, 10),
        dynamicEl: [{
            "src": 'image src',
            'thumb': 'image src',
            "subHtml": 'some caption'
        }, ]
    })
})
```

**Comment by jakeline-santos-apontador** [comment]
That worked just, fine! Thank you very very much for everything!

**Comment by jakeline-santos-apontador** [comment]
Just out of curiosity, was my previous approach entirely wrong?
