### ISSUE TITLE
lightgallery close 

### ISSUE THREAD

**Issue by sandipkumbhani** [sachinchoolur/lightGallery#751]
When i click on close button its remove querystring from URL
for Example http://xyz.com?id=1  after closing it my URL looks like http://xyz.com

**Comment by sandipkumbhani** [comment]
Now Solved

Just doing hash=false

  $lg.lightGallery({
        thumbnail: true,
        **hash:false**
    });

**Comment by sachinchoolur** [comment]
Hey @sandipkumbhani,
The issue has already been fixed in the latest version of hash plugin. You can use hash plugin without having the above problem
