### ISSUE TITLE
Targeting images only

### ISSUE THREAD

**Issue by mignz** [sachinchoolur/lightGallery#755]
I am trying to create a gallery using the images uploaded using a WYSIWYG editor. The issue is that the editor creates other HTML elements and lightGallery seems to dislike that: `data-src is not pvovided on slide item 1, 2, 3...`. All this inside a DIV with the "gallery" id.

The uploaded images don't provide an anchor so I did this:

```js
$('#gallery img').each(function () {
    $(this).wrap('<a href="' + $(this).attr('src') + '"></a>');
    $("#gallery").lightGallery();
  });
```

Now, when I click an image, lightGallery launches but doesn't show the images correctly and creates thumbnails for DIVs without images.

How can I target images with an anchor only?

**Comment by sachinchoolur** [comment]
Hey @mignz,

Could you please provide the sample HTML markup generated by your WYSIWYG editor?

**Comment by mignz** [comment]
Nevermind, there's a `selector` property, how could I miss that!
