### ISSUE TITLE
lg-video module has iFrame with http protocol

### ISSUE THREAD

**Issue by asso1985** [sachinchoolur/lightGallery#758]
Hi,

Using the httpschecker Tool (https://httpschecker.net/) we are running into non-secure protocol issues because of the current inclusion in lg-video module:

`video = '<iframe class="lg-video-object lg-vk ' + addClass + '" width="560" height="315" src="http://vk.com/video_ext.php?' + isVideo.vk[1] + a + '" frameborder="0" allowfullscreen></iframe>';
`
line 138

Can this be changed in a future release as per all the others default values you have there excluding the protocol ?

ex 

`video = '<iframe class="lg-video-object lg-dailymotion ' + addClass + '" width="560" height="315" src="//www.dailymotion.com/embed/video/' + isVideo.dailymotion[1] + a + '" frameborder="0" allowfullscreen></iframe>';
`
line 121

I can even open a PR if needed, its a very very tiny change :)

Thanks in advance and thanks for the great job with the lib overall

**Comment by sachinchoolur** [comment]
Hey @asso1985,

Thank you for pointing this out. The issue has been fixed. Please use the latest version of lightGallery
