### ISSUE TITLE
rtl problem

### ISSUE THREAD

**Issue by shelakhteh** [sachinchoolur/lightGallery#761]
Hi
How can I fix the problem of not displaying images in the right-to-left html document?
There is no problem when the document is left to the right.
(my English language is not good. Sorry.)
thanks

**Comment by sachinchoolur** [comment]
You can add the following style rule to reset the direction.
``` css
.lg-outer {
    direction: ltr;
}
```
Please re-open if the problem persists

**Comment by vahidalvandi** [comment]
thank it work .

**Comment by ch2856** [comment]
Old but for me only

` .lg-outer {text-align:right} `

worked.

**Comment by 3bood-kr** [comment]
worked for me also thanks

> Old but for me only
> 
> `.lg-outer {text-align:right}`
> 
> worked.

**Comment by kavosh24-debug** [comment]
> worked for me also thanks
> 
> > Old but for me only
> > `.lg-outer {text-align:right}`
> > worked.

I was using lightgallery - v1.6.11
The problem for RTL pages resolved with the following changes:

I have add lg-rtl class to lightgallery using js:
$('.btn-zoom-popup').on('click', function (e) {
        $(this).lightGallery({
            thumbnail: false,
            dynamic: true,
            autoplayControls: false,
            download: false,
            actualSize: false,
            share: false,
            hash: true,
            index: 0,
	    dynamicEl: images ,
            mode: 'lg-slide' ,
	   addClass: 'lg-rtl' //////// here is the class
        });
    });

And in css i added following lines:

.lg-rtl .lg {
    direction: rtl;
}
.lg-rtl .lg-actions {
    right: auto;
    left: 0;
}
.lg-rtl .lg-next {
    right: auto;
    left: 10px;
}
.lg-rtl .lg-prev {
    left: auto;
    right: 10px;
}
.lg-rtl .lg-thumb {
    direction: rtl;
}
.lg-rtl .lg-sub-html {
    text-align: right;
}
.lg-outer {
    text-align: right;
    direction: ltr;
}
