### ISSUE TITLE
Drag/Touch does not work with only two images

### ISSUE THREAD

**Issue by fr00x** [sachinchoolur/lightGallery#769]
Hi,

I am using lightGallery v.1.6.8 with a  commercial license, thank you for providing that.

That said, I can't figure out why I can't drag/touch infinte in any direction when the gallery has only two images. It works as expected with 3 or more images without issue. Prev/Next via click action works fine too infinitely too, the image count doesn't matter.

**Comment by sachinchoolur** [comment]
Hey @fr00x ,

This is known issue. Infinite loop does not work with swipe/drag if there are only two images. 
Demo - https://codepen.io/anon/pen/oqqrWy

**Comment by fr00x** [comment]
Thank you. Will that ever be fixed? Or is there a workaround? I really need this to be working for our setup.

**Comment by sachinchoolur** [comment]
It is bit difficult with the current structure of the plugin. But, I'll try to improve in version 2.0

**Comment by fr00x** [comment]
Funny thing is, it's used in combinatoin with lightSlider where the infite drag works.
