### ISSUE TITLE
youtube videos don't work with "www.youtube-nocookie.com/..."

### ISSUE THREAD

**Issue by sholzer** [sachinchoolur/lightGallery#771]
Hi,
youtube videos don't work with "www.youtube-nocookie.com/...".

**Comment by silviaRe** [comment]
Hi,
yes, I have the same problem.

A quick fix would be cool ;)

**Comment by WimWidgets** [comment]
@sachinchoolur  [This](https://github.com/WimWidgets/lightGallery/commit/a09b4f7fc06de492086bf487f16014817afd87d4) should fix it, but I don't have time to get the build tools to run or creates tests.

**Comment by sachinchoolur** [comment]
The issue has been fixed. Please use the latest version of lightGallery
