### ISSUE TITLE
Lightgallery # url issue on https server

### ISSUE THREAD

**Issue by ravijaroli1** [sachinchoolur/lightGallery#773]
When i open any image in lightgallery then it is working fine on local server and staging server. But it is not working proper on our production's secured(https) server.
For example, In my staging server when I opened any image in lightgallery then it is working fine and url coming like below -
http://letzpen.com/school/oakridge-international-school/details/live-feed#lg=1&slide=0

**But On production server same path when I open any image in lightgallery then that # url removed whole url and show only domain name and # url like below - 
https://my-domain/#lg=1&slide=0**

So I just want that my https server url also comes like below url -
https://my-domain/school/oakridge-international-school/details/live-feed#lg=1&slide=0 

Thank you in advance  :-)

**Comment by sachinchoolur** [comment]
Hey @ravijaroli1,

Please use the latest version of lg-hash plugin. https://github.com/sachinchoolur/lg-hash

If it doesn't work, as an immediate fix you can disable the hash plugin by passing `hash: false` via settings

**Comment by ravijaroli1** [comment]
Thank you @sachinchoolur .
After updating lg-hash plugin on production server, it works fine.

**Comment by dharmesh-infyom** [comment]
When i download image using lightgallery it is working fine on local machine but when i am trying to download image using lightgallery in server it opens in new tab.
my Server secure with (https) and my image url comes from amazon s3 server 
Thanks in advance :)
