### ISSUE TITLE
how to load more image in lightgallery in angularjs 

### ISSUE THREAD

**Issue by TripleQQ** [sachinchoolur/lightGallery#775]
Hi i am new in Angularjs, and i try to use lightgallery to present all the images in my project. however, i have no idea how to insert more image into lightgallery after finished loading or user click to the last image in angularJS?

basically my question is how to call the function from lightgallery to insert more image and how to check the user click the last image

**Comment by sachinchoolur** [comment]
Hey @TripleQQ,
Sorry for the delayed response. At present, there is no inbuilt method to add new images to the gallery.
You need to destroy and re-initiate the gallery. Here is the demo - http://sachinchoolur.github.io/lightGallery/demos/methods.html
