### ISSUE TITLE
light gallary video not loading, no error message in console

### ISSUE THREAD

**Issue by kzish** [sachinchoolur/lightGallery#777]
there is no error message appearing in the console, but no video is loading either when using light gallary

iv included the hidden html markup
`
                <div style="display:none;" id="video1">
                    <video class="lg-video-object lg-html5" width="100%"s>
                        <source src="gallery/videos/video_1.mp4" type="video/mp4">
                         Your browser does not support HTML5 video.
                    </video>
                </div>`

as well as the html visible markup
`<ul id="videos" class="list-unstyled row">
                        <li class="col-xs-6 col-sm-4 col-md-3 video" data-poster="gallery/thumbs/thumb_1_lg.jpg" data-sub-html="" data-html="#video1">
                            <a href="">
                                <img class="img-responsive" src="gallery/thumbs/thumb_1.jpg">
                                <div class="demo-gallery-poster">
                                    <img src="gallery/assets/img/play-button.png" />
                                </div>
                            </a>
                        </li>`

iv included the video js library as well
` 
    <link href="assets/libs/video.js/video-js.css" rel="stylesheet" />
    <script src="assets/libs/video.js/video.js"></script>
    <script src="assets/libs/video.js/videojs-ie8.min.js"></script>
    `

and this script as well
` $('#videos').lightGallery({
             videojs: true
         });`

the lightgallary loads the data-posters well but on clicking the play video button no video will load

**Comment by sachinchoolur** [comment]
Hey @soyuznii ,

Here is the working demo - https://codepen.io/sachinchoolur/pen/BpxebR

Your code looks good to me. Can you please make sure that the video is in the correct path?
If it doesn't work, please provide an isolated jsfiddle or codepen demo. I'll fix the issue and send you back

**Comment by IljaPHP** [comment]
Hello, @kzish ! What was the solution? I have the same problem.
