### ISSUE TITLE
[Question:] usage inside a iframe

### ISSUE THREAD

**Issue by Offerel** [sachinchoolur/lightGallery#778]
Currently im trying to develop a new [Roundcube ](https://github.com/roundcube/roundcubemail)plugin where lightGallery is a part of it. To do the nature how this plugins currently work, most of them are used inside a iframe. For example my gallery plugin is part of an iframe. All the thumbnails are displayed in that iframe. 

As a result, lightGallery opens only at the maximum size of that iframe inside Roundcube. Now i would like to ask, if there is some way, to open lightGallery so, that it uses the whole browser window, instead  of only the size of the iframe. Is this possible without modifying the lightGallery source?

**Comment by sachinchoolur** [comment]
Hey @Offerel,
At present, this is not possible. We can not access cross domain iframe content using javascript.

**Comment by Offerel** [comment]
The gallery comes in my case from the same local folder structure. Int his case, this isn't a cross domain setup. However, I will try to use a alternative instead of the iframe technique, maybe a object tag or embbed. I don't know if this works with Roundcube. But this will be one of the last step's before release. You can find a pre-release version of the plugin at https://github.com/Offerel/roundcube_pictures. Its not the latest commit, but it could give you a small idea what will be the final result. I do not recommend to install this plugin in a production environment in the current state but you can play with it.
