### ISSUE TITLE
Adding  external links on thumbnail captions

### ISSUE THREAD

**Issue by ptsar** [sachinchoolur/lightGallery#779]
Would be possible to include a link to the thumbnail captions? 
Since every element is under "#lightgallery" is opening the gallery, but is there a way to overwrite and include a separate link? Thanks

**Comment by sachinchoolur** [comment]
Hey @ptsar,
Yes it is possible by using `selector` setting. Here is the demo for selectors - http://sachinchoolur.github.io/lightGallery/demos/html-markup.html

Please let me know if you have any queries
