### ISSUE TITLE
How to make the image open by double click

### ISSUE THREAD

**Issue by brianinna** [sachinchoolur/lightGallery#781]
Is it possible to open the lighbox by double click?
Since I add the “drag scroll” to my page. Everytime I drag the page to srcoll and it will open the image by mistake. I am trying to modify the core so that I can open the image lightbox by double click. Is there any suggestions that I can get ?

**Comment by sachinchoolur** [comment]
If you are using dynamic mode, you can do this without editing the core code-
Here is the demo https://codepen.io/anon/pen/MGJgKp

If you still want to update the core code, you can easily achieve this by updating the following lines 
https://github.com/sachinchoolur/lightGallery/blob/master/src/js/lightgallery.js#L177
https://github.com/sachinchoolur/lightGallery/blob/master/src/js/lightgallery.js#L1280

Change `click.lgcustom` to `dblclick.lgcustom`
