### ISSUE TITLE
License Enquiry

### ISSUE THREAD

**Issue by garyfoo** [sachinchoolur/lightGallery#782]
Hello!

I'm interested in purchasing a license for use on multiple public websites

Could you recommend me what license I would need for my use and what are the restrictions or guidelines while using the license (i.e. do I need to put some comment accrediting the usage of lightgallery?)

**Comment by sachinchoolur** [comment]
If you want to use lightGallery on multiple websites, the extended license would be the appropriate license for your usage. It allows you to use lightGallery on unlimited number of websites under same company. 
Also, You don't have to put any comment about the usage of lightGallery.
more info - https://www.uplabs.com/store/license

Please let me know if you have any questions
