### ISSUE TITLE
Safari light gallery video loads but doesn't start playing.

### ISSUE THREAD

**Issue by AcclaimWorks** [sachinchoolur/lightGallery#786]
Anyone else seeing an issue with safari where light gallery loads video but video does not start playing?

Controls are saying it is paused. Click Pause then controls say ready to play. Click play and then fine.  We have set autoplay. Not seeing this behaviour in any other browser with the same video. In other browsers video loads and plays immediately as expected. 

Safari v11.1 / macOS 10.13.4 / latest v lightgallery / mp4.  Have checked to make sure that autoplay not disabled in browser preferences.

**Comment by sachinchoolur** [comment]
Hey @AcclaimWorks,

it works fine for me. Is it happening in the demo as well? - http://sachinchoolur.github.io/lightGallery/demos/html5-videos.html

**Comment by mikitach** [comment]
Hey @sachinchoolur!

Actually, it is! Maybe it's related to Updates to the autoplay policies in Safari and Chrome (Chrome, as far as I now, didn't come with it yet, but Safari did). As a quick fix (which made it some how work for me, but, unfortunately, was relate on markup) - beside adding "muted" attribute, change "preload" to "metadata/auto".

**Comment by Natz162** [comment]
I'm having the same issue actually, thanks for the quick fix. 
Been breaking my head on what the problem was.

**Comment by EmilSabitov** [comment]
You must know that safari starts to load video file on "metadata/auto".
