### ISSUE TITLE
Is the hash plugin working correctly?

### ISSUE THREAD

**Issue by chrisdeeming** [sachinchoolur/lightGallery#787]
@sachinchoolur 

>lightGallery will record slide history and allows you to travel to previous slides via browser back button.

Currently when I'm trying that on your [demo](http://sachinchoolur.github.io/lightGallery/demos/hash.html) I can click on the first slide, navigate through a few slides, then if I hit the back button, I do not get the previous slides but instead I go to my previous page.

**Comment by sachinchoolur** [comment]
Hey @chrisdeeming,
Sorry for the confusion. The behavior specified in the demo page has been changed. There were few issues with the old approach. At present, hash plugin doesn't create new history, It replaces the history and changes the URL. Basically, it just allows you to open gallery from a url.

I'll update the docs

**Comment by chrisdeeming** [comment]
That's unfortunate. Would certainly be interested in that functionality being re-added. But thanks for confirming.

**Comment by sachinchoolur** [comment]
If you want the old behavior, you can use version 1.0.1 -  https://github.com/sachinchoolur/lg-hash/releases/tag/1.0.1
Also, please have a look at this link https://github.com/sachinchoolur/lightGallery/issues/547 to know more about the issue
