### ISSUE TITLE
 add play icon in video thumbnail image

### ISSUE THREAD

**Issue by YSTomar** [sachinchoolur/lightGallery#788]
Hi,

I am using your plugin for displaying mix content in light box, for extra thumbnail iamge I am using extThumbImage option, but I need to add play icon over video thumbnail images.

Is there any way to do it.

**Comment by sachinchoolur** [comment]
You can either create thumbnail images with play icon or add using css `after`, `before` pseudo selectors.

Please let me know if you need any help with this

**Comment by YSTomar** [comment]
I had made changes in the library at end, but we can add it through out library (i.e. if thumbnail is associated with video then we can add play icon on it)
