### ISSUE TITLE
How to create html markup fast

### ISSUE THREAD

**Issue by tyeeman** [sachinchoolur/lightGallery#790]
Excuse me for asking but the markup is like this - 
```
<div id="lightgallery">
  <a href="img/img1.jpg">
      <img src="img/thumb1.jpg" />
  </a>
  <a href="img/img2.jpg">
      <img src="img/thumb2.jpg" />
  </a>
  ...
</div>
```
 So how do I create this for over 100 images. Surely not copy and paste and then changing the number. That would take a long time. Any way to do this automatically?

**Comment by cssvulture** [comment]
I think what you're asking is a bit out of scope as it's up to you on ***how*** you'll create your html markup, but you could just run a loop that appends something like
```
<a href="/img/img[x].jpg"><img src="/img/thumb[x].jpg]" /></a> 
```
to `#lightgallery` 100 times. (`[x]` would be the var you set for the iteration count)

You could use php, js,or an html processor to run the loop. (JS is post DOM load though so images will be be much slower to load).

**Comment by cssvulture** [comment]
pro ^^^
