### ISSUE TITLE
Not working (When I am using *ngFor in Angular 2 )

### ISSUE THREAD

**Issue by ranjitkumark** [sachinchoolur/lightGallery#792]
I am new in angular 2, trying to add lightgallery but i am not able to understand the issue Please help me out THANKS 

ITS OPEN IN NEW BROWSER

BUT IF I PUT "ngFor" INSIDE <img> TAG AND GIVE A STATIC PATH IN HREF ITS WORKING

This is My code

----------HTML-----------------

        <ul id="lightgallery" class="list-unstyled row">

             <li class="col-xs-6 col-sm-4 col-md-3" >
                <a class="item"  *ngFor = "let images of dataImages" href="{{images.path}}" >
                    <img class="img-responsive" src="{{images.path}}" >
                </a>
            </li>
        </ul>

----------JS-----------------

$(document).ready(function() {
  $("#lightgallery").lightGallery({
    selector: '.item'
  }); 

});

**Comment by Chethannp** [comment]
@ranjitkumark  - Did you find out a way to do this ??

**Comment by yusufhajjar** [comment]
@ranjitkumark - Did you find out a way to do this ?? Thanks

**Comment by varminas** [comment]
This issue is still actual. I have tested with Angular 12, and got an error while using ngFor loop. Error message tells that data-src field is not set: <a data-src="{{image.url}}"... Setting data-src statically works just fine.
