### ISSUE TITLE
Youtube no cookie option

### ISSUE THREAD

**Issue by pb1uk** [sachinchoolur/lightGallery#793]
In light of the changes in data and privacy around GDPR would there be the potential to add an option to embed a YouTube video with no cookies? e.g. https://www.youtube-nocookie.com/embed/r87A-Ql2czg as opposed to https://www.youtube.com/embed/r87A-Ql2czg

**Comment by sachinchoolur** [comment]
Hey @pb1uk ,
YouTube nocookie already works with latest version lightGallery. - Here is the demo - https://codepen.io/anon/pen/pVMgdV
