### ISSUE TITLE
Zoom with pinch on Android is jerky

### ISSUE THREAD

**Issue by SergioPaoloFassina** [sachinchoolur/lightGallery#795]
When I zoom with pinch on my Android device feels very jerky. How can I fix that?

The gallery in question is here: [sergiopaolofassina.com](http://sergiopaolofassina.com/)

**Comment by sachinchoolur** [comment]
Hey @SergioPaoloFassina,

The current version doesn't support pinch to zoom. It is already done in 2.0 which will be released in next couple of weeks

**Comment by wekii** [comment]
> Hey @SergioPaoloFassina,
> 
> The current version doesn't support pinch to zoom. It is already done in 2.0 which will be released in next couple of weeks

Any news about 2.0 release? Pinch & zoom functionality is still missing.

**Comment by AthanGt** [comment]
Any news about version 2.0, and pinch to zoom support ?

Thanks in advance

**Comment by fabianmarz** [comment]
@sachinchoolur, any news about the 2.0 release? :) Some weeks has passed already.

**Comment by mariomurrent-softwaresolutions** [comment]
Any updates on the 2.0 release? Were waiting for the pinch zoom support :)
