### ISSUE TITLE
Uncaught TypeError: $(...).lightGallery(...).destroy is not a function

### ISSUE THREAD

**Issue by gireesht14** [sachinchoolur/lightGallery#801]
Hi , 
I am using the light gallery plugin fro my website , while running the $('#categoryImages').lightGallery().destroy(true);

I getting the console error "Uncaught TypeError: $(...).lightGallery(...).destroy is not a function",

the below mentioned code snippet is my website code which am using for light gallery.

"<div id="" class="demo-gallery product-list">
        <ul id="categoryImages" class="list-unstyled row ajxcategoryImages">
    <?php $dir    = 'images/category/';
          $categorys = scandir($dir);
          $subcategorys = scandir($dir.strtolower($getCategory));
          unset($subcategorys[array_search('.', $subcategorys, true)]);
          unset($subcategorys[array_search('..', $subcategorys, true)]);
          $data['subcategorys'] = $subcategorys;
          foreach ($subcategorys as $key =>$subcategory) {
            $subcategoryImage= scandir($dir.strtolower($getCategory)."/".$subcategory);
            unset($subcategoryImage[array_search('.', $subcategoryImage, true)]);
            unset($subcategoryImage[array_search('..', $subcategoryImage, true)]);
            foreach ($subcategoryImage as $key => $value2) {
              $data['subcategoryImages'][]= $dir.strtolower($getCategory)."/".$subcategory."/".$value2;?>
               <li class="col-xs-6 col-sm-4 col-md-3" data-responsive="<?php echo $dir.strtolower($getCategory)."/".$subcategory."/thumb/".$value2;?> 375, <?php echo $dir.strtolower($getCategory)."/".$subcategory."/".$value2;?> 480," data-src="<?php echo $dir.strtolower($getCategory)."/".$subcategory."/".$value2;?>">
                <a href="javascript:;">
                    <img class="img-responsive" src="<?php echo $dir.strtolower($getCategory)."/".$subcategory."/".$value2;?>">
                </a>
            </li>
          <?php }
    }?>    
        </ul>
      </div>"

Jquery code 
--------------
 $('body').on('click', '.category', function() {
      $('#categoryImages').lightGallery().destroy(true);
 });

**Comment by biner88** [comment]
**test this**
`
try{
       $('#categoryImages').lightGallery();
       $('#categoryImages').data('lightGallery').destroy(true);
}catch(ex){};
`
