### ISSUE TITLE
Multiple galleries > Destroy method fails

### ISSUE THREAD

**Issue by preliot** [sachinchoolur/lightGallery#803]
When i use the recommended code to destroy the gallery:

`myLightGallery.data('lightGallery').destroy();`

It works on the first gallery. However it fails on all other galleries. It seems the second time the destroy method fails to remove the class lg-visible from the wrapper lg-outer.

My fix in jquery:

` $('.lg-outer .lg-close').trigger('click.lg');`

**Comment by sachinchoolur** [comment]
It works fine for me. If you are using multiple galleries, you need to use the respective instance to destroy the gallery. 
If the issue persists please share your code
