### ISSUE TITLE
LightGallery navbar problem

### ISSUE THREAD

**Issue by melycastp** [sachinchoolur/lightGallery#808]
Hi. I want to show the gallery in full screen but the navbar overlaps and doesn't show the close or share buttons. Can you help me, please?

**Comment by naadiyaahmed** [comment]
Check the z-index on the navbar.

Light gallery gives you custom events. Which you can use to modify your navbar's z-index on open/close.

You can use jQuery to fix this problem --
   $('#lightgallery').on("onAfterOpen.lg", function() {
        var navbar = $('nav.navbar-default.navbar-static-side');
        navbar.css({"z-index":"0"});
    });
    $('#lightgallery').on("onCloseAfter.lg", function() {
        var navbar = $('nav.navbar-default.navbar-static-side');
        navbar.css({"z-index":"<whatever your current z-index is>"});
    });
