### ISSUE TITLE
lightSlider + lightGallery First and Last thumbnail in Gallery are repeated

### ISSUE THREAD

**Issue by websygen** [sachinchoolur/lightGallery#81]
Hello,
I am very impressed by your plugins and I am using both the Gallery and the Slider.
In this case First and Last thumbnail in Gallery are repeated.
I guess that this comes from inherited elements from the slider.

```
jQuery('#container').lightSlider({
		gallery			:	true,
		item			:	1,
		loop			:	true,
		controls		:	false,
		adaptiveHeight	:	true,
		slideMargin		:	0,
		thumbItem		:	6
});
jQuery('#container').lightGallery({
		lang			:	{ allPhotos: '<?php _e('All Photos', 'pdah');?>' },
		exThumbImage	:	'data-thumb',
		animateThumb	:	true,
		thumbWidth		:	60,
		preload			:	3
});
```

**Comment by sachinchoolur** [comment]
Hi,
If loop is true lightslider will create clone of first and last slides with extra class name `.clone`
And for non clone slides `.lslide` class will be added.
So you can use lightGallery's custom selector property to set `.lslide` as selector.
I have created a jsfiddle demo for you please have a look http://jsfiddle.net/sachin377/eedf7pon/3/

**Comment by websygen** [comment]
Thank you for the response
