### ISSUE TITLE
AngularJS 1.6 lightGallery has not initiated properly

### ISSUE THREAD

**Issue by luidiva** [sachinchoolur/lightGallery#810]
http://plnkr.co/edit/qu8iBi5Yws7dRHkHa7Wi?p=preview

**Comment by sachinchoolur** [comment]
Javascript version of lightGallery doesn't accept jQuery element.
You need to pass native DOM element in the lightGallery function.

Instead of 
``` js
lightGallery(element.parent());
```
use 
``` js
lightGallery(element.parent()[0]);
```
``` js
.directive('lightgallery', function() {
  return {
    restrict: 'A',
    link: function(scope, element, attrs) {
      if (scope.$last) {
        lightGallery(element.parent()[0]);
      }
    }
  };
});
```



Here is the working copy - http://plnkr.co/edit/YhDCqGFR2d0lTzQqiSSM?p=preview
