### ISSUE TITLE
YouTube Video not working

### ISSUE THREAD

**Issue by 5VRod** [sachinchoolur/lightGallery#811]
hi sachinchoolur, i recently bought a license for this plugin. So far everything but youtube videos seems to work as expected:

Here's my code:

**HTML:**

```
<a class="btn btn-yt-link btn-play" href="https://www.youtube.com/watch?v=L9szn1QQfas" target="_blank" data-src="https://www.youtube.com/watch?v=L9szn1QQfas">
 <span class="sr-only">Linktext</span>
 <i class="material-icons" aria-hidden="true">play_arrow</i>
</a>
```

**JS:**

```
$('.btn-yt-link.btn-play').each(function() {
  $(this).lightGallery({
    zoom: false,
    thumbnail: false,
    autoplayControls: false,
    share: false,
    download: false
  });			
});
```
It does not seem to make any difference whether i use data-src or not or href (or both). When i click the link i get an error message: 

_data-src is not pvovided on slide item 2. Please make sure the selector property is properly configured._
_data-src is not pvovided on slide item 1. Please make sure the selector property is properly configured._

Since there where two items mentioned in the error message i think it tried to find the data-src attributes within the child tags <span> and <i>. So i tried to set an option _selector_ with the value _this_. It then would open a link in a new browser window. 

Can you please assist with this? According to the docs this should work as excpected.

**Comment by sachinchoolur** [comment]
Hey @5VRod,

By default, lightGallery expects data-src/href on the child items. But in your case, you have href on the container itself. 

So you need to pass `selector:'this'` via settings.

The below code should work

``` js
$('.btn-yt-link.btn-play').each(function() {
  $(this).lightGallery({
    zoom: false,
    thumbnail: false,
    autoplayControls: false,
    share: false,
    download: false,
    selector: 'this'
  });			
});
```
