### ISSUE TITLE
Request to add `aria-modal="true"` to modal div

### ISSUE THREAD

**Issue by jitendersandhu** [sachinchoolur/lightGallery#815]
Hi @sachinchoolur,

We have been trying to make our website accessibility compliant (as per standards [here](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/dialog-modal/dialog.html)) and in our effort to do that, we are adding `aria-modal="true"` to all the modals used in our website and `lightgallery` is one of them.

Could you please add the `aria-modal="true"` attribute to the `.lg-outer` `div` so that it can help us and everyone else, who is using this **super awesome** library, to make the web more accessible for users.

Please let us know if you want a PR for this feature request and thanks again for making such an awesome library!

Cheers,
Jitender Singh

**Comment by jitendersandhu** [comment]
@sachinchoolur - is there any updates on this?

**Comment by jitendersandhu** [comment]
@sachinchoolur @sachinds - Any updates would be much appreciated!

**Comment by sachinchoolur** [comment]
Hey @jitendersandhu,
I'm really sorry for the delay. I've made a lot of accessibility improvements including `aria-modal="true"`. Please use the latest version of lightGallery
