### ISSUE TITLE
$(...).lightGallery is not a function ) - thumbnails not clickable

### ISSUE THREAD

**Issue by Anlaur** [sachinchoolur/lightGallery#817]
Hey,

I have the exact same issue as in #538  on a WordPress website and I don't know where it is coming from. My gallery is displayed correctly but my thumbnails aren't clickable as they are supposed to be.

So, in my functions.php, I have:
```
add_action( 'wp_enqueue_scripts', 'ls_scripts_styles', 20 );
/**
 * LightSlider Scripts
 */
function ls_scripts_styles() {
  wp_enqueue_style( 'lightslidercss', get_stylesheet_directory_uri(). '/css/lightslider.min.css' , array(), '1.0.0', 'all' );
  wp_enqueue_script( 'lightsliderjs', get_stylesheet_directory_uri() . '/js/lightslider.min.js', array( 'jquery' ), '1.0.0', true );
  wp_enqueue_script( 'lightsliderinit', get_stylesheet_directory_uri() . '/js/lightslider-init.js', array( 'lightsliderjs' ), '1.0.0', true );
}
```

In the lightslider-init.js file, I have:
```
jQuery(document).ready(function($){

  $('.image-gallery').lightSlider({
    gallery:true,
    item:1,
    slideMove: 1,
    auto:false,
    loop:true,
    thumbItem: 3,
    onSliderLoad: function(el) {
            el.lightGallery({
                selector: '.image-gallery'
            });
        }
  });

});
```

And in my page-template file, I have:
             
```
<?php function themeprefix_lightslider_thumbslider() {
                    $images = get_field('images'); //add your correct field name

                        if( $images ): ?>

                            <ul id="light-slider" class="image-gallery">

                              <?php foreach( $images as $image ): ?>

                                  <li data-thumb="<?php echo $image['url']; ?>">
                                      <img src="<?php echo $image['url']; ?>" alt="<?php echo $image['alt']; ?>" />
                                  </li>

                              <?php endforeach; ?>
                            </ul>
                        <?php endif;
                  }

                  themeprefix_lightslider_thumbslider();
                  ?>
```

Where am I wrong? I have looked for many issues (typos, file wrongly named, jquery wrongly coded, etc.) but I can't find the solution. Do you have any idea?

Thanks a lot!

P.S.: First time I ask for help on GitHub so I firstly wrote a comment on the other message but since it is closed, I prefer starting a new conversation here.

**Comment by sachinchoolur** [comment]
Hey @Anlaur,
Sorry for the delayed response. Seems like you have not included lightGallery.js in your document. I see only lightSlider code. If you don't need lightGallery, you can just remove the following code block from your document 

``` js
onSliderLoad: function(el) {
            el.lightGallery({
                selector: '.image-gallery'
            });
        }
```

It should work fine

**Comment by Anlaur** [comment]
Hey @sachinchoolur,

Thank your for your reply! I have used another solution in the end but I will keep this in mind for the next time.

Kind regards,

Anlaur
