### ISSUE TITLE
Better bower integration

### ISSUE THREAD

**Issue by ioquatix** [sachinchoolur/lightGallery#82]
It would be nice if the directory 'light-gallery' could be renamed 'dist' to match up with other packages.

**Comment by ioquatix** [comment]
The naming of this package could use some work too..

For example, the bower package is "lightgallery" but the github repo is "lightGallery" while the javascript files are "light-gallery".

Perhaps standardise on `light-gallery` for everything?

**Comment by sachinchoolur** [comment]
I am planing to release next version soon.
I will follow jQuery boilerplate folder structure so this issue will be fixed..

**Comment by sachinchoolur** [comment]
Hi,
I have released lightgallery 1.2 with dist folder ..

**Comment by ioquatix** [comment]
That's awesome, thanks.
