### ISSUE TITLE
Disabling all animations

### ISSUE THREAD

**Issue by sowinski** [sachinchoolur/lightGallery#820]
Hi,

I would like to disable all animations.
This is my current configuration:
```
$("#gallery").lightGallery({
download: false,
currentPagerPosition: 'middle',
speed:0,
toogleThumb: false,
hideBarsDelay: 3600000,
backdropDuration: 0,
thumbMargin: 11,
slideEndAnimatoin: false,
});
```
I was not able to disable the opening animation (So if you open first time the gallery by clicking an image). 

Thank you :)

**Comment by sachinchoolur** [comment]
You can set `startClass:''` to remove the starting animation 
Docs - http://sachinchoolur.github.io/lightGallery/docs/api.html

``` js
$("#gallery").lightGallery({
  download: false,
  currentPagerPosition: 'middle',
  speed:0,
  toogleThumb: false,
  hideBarsDelay: 3600000,
  backdropDuration: 0,
  thumbMargin: 11,
  slideEndAnimatoin: false,
  startClass:''
});
```
