### ISSUE TITLE
How to add custom buttons, when gallery is opened

### ISSUE THREAD

**Issue by valjar** [sachinchoolur/lightGallery#824]
Hi there!

I have a problem, that I need to add custom buttons to my lightGallery. So far I managed to add it with help of data-sub-html attribute, but the problem is that they are completely non responsive..
I'm using VueJs

My HTML
```
<div id="lightgallery" v-show="false">
     <a v-for="(image, index) in locationImages" v-bind:href="image.hd_path"
          v-bind:data-sub-html="subHtml"
     >
     <img v-bind:src="image.thumb_path" />
     </a>
</div>

```

My Js
```
$('#lightgallery').on('onAfterOpen.lg',function(event, index){
   self.subHtml = '<button id="slideShowAddImageToCart" @click="addToCart('+event+','+self.currentSelectedImage+','+'\'IMAGE\''+')" class="btn">Add image to cart </button>"';
});
```

The problem is that button doesn't react to nothing. I have also tried to add custom jquery code, which detects all button click and code is working ok, until lightGallery is opened. When I click on my add to cart button nothing happen

Example of code for testing button reactions
```
$("input").click(function(e){
    alert('clicked');
});
$("button").click(function(e){
    alert('clicked');
});

```
Can someone please help me out, how to add custom buttons to my lightgallery. I have already purchased the plugin and I would really like to use it

**Comment by sachinchoolur** [comment]
Hey @valjar,

You can add your javascript functions on the `onAfterAppendSubHtml.lg` event listener.
Not sure about VueJs. But jQuery should work fine.

Docs - http://sachinchoolur.github.io/lightGallery/docs/api.html#events
Demo- http://sachinchoolur.github.io/lightGallery/demos/events.html

**Comment by valjar** [comment]
Hi! 
Thanks for the answer. I will try it today and let you know if it working..

Br,
