### ISSUE TITLE
Gallery selector

### ISSUE THREAD

**Issue by fsoabsix** [sachinchoolur/lightGallery#825]
Hi everyone,

I have a page with 7 galleries, witch works fine. In an ul/li, all my galleries are dynamic.

Is it possible, when the gallery is open, to add a select to change the current gallery ?

Thanks for the help :)

**Comment by sachinchoolur** [comment]
Hey @fsoabsix,
I didn't understand your question properly. Could you please re-phase it?

**Comment by fsoabsix** [comment]
Hey @sachinchoolur, i resolved it by myself ;) Thanks.
