### ISSUE TITLE
I Made an Exif Info Plugin (Where to put it?)

### ISSUE THREAD

**Issue by amcolash** [sachinchoolur/lightGallery#828]
Hi there! I have been working on some code changes for the open source project called [thumbsup](https://github.com/thumbsup/thumbsup) which uses your module to generate static gallerys. I wanted to add an exif info panel to lightGallery and so I made a plugin for it called [lg-exif](https://github.com/amcolash/lg-exif).

I have a working plugin and would like to share if others think it might be useful for them. Where could I place this plugin, or is this something that would be wanted for the core of this project?

Thanks much!

Here is a [demo](https://amcolash.github.io/lg-exif/example/).

Here is what it looks like:

![44509690-3e305f80-a667-11e8-8c2a-a6378f1003bb](https://user-images.githubusercontent.com/8282413/46909967-59458000-cef0-11e8-894d-190934c8a898.gif)

![44625918-1db31000-a8c8-11e8-9d7e-f4841002947a](https://user-images.githubusercontent.com/8282413/46909968-59458000-cef0-11e8-9f60-8428d9dd21ac.png)

**Comment by sachinchoolur** [comment]
Hey @amcolash ,

Thanks for the plugin. I can add it to the documentation. It would be great if you could publish the plugin as NPM package as well

**Comment by amcolash** [comment]
I published to npm: https://www.npmjs.com/package/lg-exif. Let me know if you want anything else!
