### ISSUE TITLE
custom html5 player possible

### ISSUE THREAD

**Issue by djangosdk** [sachinchoolur/lightGallery#83]
Hi,
is it possible to use custom html video player like free www.videojs.com/

**Comment by sachinchoolur** [comment]
Yes It is possible. you can insert custom video html into the gallery.
example : http://jsfiddle.net/sachin377/fz0ntwbm/2/

**Comment by djangosdk** [comment]
Hi,
Thank you for the answers , I tried combining your answer forthe table anf custom video player and i cant make it to work.

It seems onOpen event cant handle custom video player for many videos.
Please see my try at jsfiddle and let me know if i am doing wrong ?
I think i may need onSlide event , as i tried with onSlideBefore  but it didnt work

http://jsfiddle.net/bababalcksheep/fz0ntwbm/5/

**Comment by djangosdk** [comment]
In another try , i put ```data-setup``` attribute for videoJs so there is no need to initialize it as per their documentation if jquery is included in project.
Now JSvideo initializes fine but cant play video on click.

http://jsfiddle.net/bababalcksheep/fz0ntwbm/7/

**Comment by sachinchoolur** [comment]
Hi,
In the next version i will include a callback function after appending the video html.
For current use please refer the updated jsfiddle  http://jsfiddle.net/sachin377/fz0ntwbm/9/

**Comment by djangosdk** [comment]
+1 for callback
Plus a new event like ```onSlide :function(el,slide){ }```
where one can append custom html to slide if wants to overwrite current slide would be nice
