### ISSUE TITLE
Using lightGallery in combination with lightSlider: lightGallery preloading?

### ISSUE THREAD

**Issue by FabianRahm** [sachinchoolur/lightGallery#840]
We're using lightGallery and lightSlider with your paid license.

Is it possible to trigger the pre-loading of the data-src attribute which is used in lightGallery?

`$('#contentImageGallery').lightSlider({
            addClass:"content-slider",
            auto:true,
            gallery:false,
            item:1,
            keyPress: true,
            loop:true,
            pause:5000,
            thumbItem:2,
            slideMargin:0,
            galleryMargin: '-31px 0 10px -15px',
            enableDrag: false,
            enableTouch: true,
            currentPagerPosition:'left',
            prevHtml: '<i class="fa fa-chevron-left"></i>',
            nextHtml: '<i class="fa fa-chevron-right"></i>',
            onSliderLoad: function (el) {
                $('.content-gallery-slide-img').show();

                el.lightGallery({
                    selector: '#contentImageGallery .lslide',
                    animateThumb: false,
                    showThumbByDefault: false
                });
            }

        });`

**Comment by fr00x** [comment]
@sachinchoolur Is there anything we can do to have pre-loading in this setup?
