### ISSUE TITLE
lightGallery + Infinite Scroll

### ISSUE THREAD

**Issue by Siilionu** [sachinchoolur/lightGallery#845]
Hi,

Is there any demo code with lightGallery + Infinite Scroll working together?

https://infinite-scroll.com/

**Comment by sachinchoolur** [comment]
Here is the similar demo -http://sachinchoolur.github.io/lightGallery/demos/methods.html
Let me know if you have any questions

**Comment by PapyIP** [comment]
Hello, 
facing the same problem with an automatic scroll (no button to load more items), I solved it like this 
```
var $lg = $('.LightGallery_container');
var $is = $('.InfiniteScroll_container');
		
$is.on('append.infiniteScroll', function( event, response, path, items ) {
	$lg.data('lightGallery').destroy(true);
	$lg.lightGallery({selector: '.lightgallery_selector'});
});
```
compared to the method indicated by Sachin, I had to redefine the selector.

**Comment by kageja** [comment]
Hi PapyIp, could you paste your code? what's $is and .lightgallery_Selector.
Thank you
