### ISSUE TITLE
Launching gallery from single image

### ISSUE THREAD

**Issue by MichCest** [sachinchoolur/lightGallery#85]
Is there any way to launch the gallery from a single image without using dynamic mode? I need my image src's to be within the HTML, not the JS.

**Comment by sachinchoolur** [comment]
I think the best way is using dynamic mode only.
If you don't want to use dynamic mode you can display only one thumbnail and hide remaining thumbnails.
See the example fiddle : http://jsfiddle.net/sachin377/p1aw7utk/9/

**Comment by zodit** [comment]
Lightgallery is very good, but the markup is not perfect for a single image to zoom in because the link and image need to be wrapped with another element, and this is not always doable. A better way would be to target the `<a>` tag, as other lightbox plugins do.
