### ISSUE TITLE
Can i open lightgallery in new browser window?

### ISSUE THREAD

**Issue by mohamedryan** [sachinchoolur/lightGallery#850]
I'm working on a project that have a page that display some information with some images,

currently i'm using the light-Gallery with dynamic mode, and it work perfectly.
what i need now is to make the light-Gallery to be opened in a new browser windows, to make the user able to compare the information displayed and the content of this images.

so, there is any possibility to do that ? 

Thanks :)

**Comment by Engagendy** [comment]
I suggest to open normal call to another URL, then on the load of this URL you can open light gallery
* you should call another endpint like ctrl/action then it will load totally new page just load the returned data you need in this new page.
