### ISSUE TITLE
Create gallery in a div element instead of in body; dynamic content

### ISSUE THREAD

**Issue by MikeTommasi** [sachinchoolur/lightGallery#857]
Hi

I saw a similar thread but it did not help.

I am trying to contain the gallery (latest JS Version) inside a div element with id="lightgallery". My content is dynamic so I create a data structure as required (it works well).  But no matter what I do the gallery is placed in the body after all my divs. 

http://www.marcogliese.org

I use:

HTML: 
=====

```
<body>
  <div id="wrap">
   <div class="column left">
... content left div
   </div>

  <div class="column right">
   <div id="lightgallery"></div>
  </div>
 </div>
... javascript calls ...
 </body>
```

JS:
====

```
var data = [
	{src: 'img1.jpg', subHtml: '<h4>img #1</h4><p>© xyz</p>'},
	{src: 'img2.jpg', subHtml: '<h4>img #11</h4><p>© xyz</p>'}
];
lg = document.getElementById('lightgallery');

lightGallery(lg, {
//    selector: '#lightgallery', *****makes no difference
    galleryId: 1,
    mode: 'lg-fade',
    cssEasing: 'cubic-bezier(0.25, 0, 0.25, 1)',
    dynamic: true,
    dynamicEl: data,
});
```

CSS:
=====

```
#lightgallery {
  position: relative;
}
.lg-backdrop {
  position: absolute;
}
.lg-outer {
  position: absolute;
}
.lg-outer .lg-item, .lg-outer .lg-img-wrap, .lg-outer .lg-video-cont {
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
}
.lg-sub-html {
  position: absolute
}
```

TIA

Mike

**Comment by cwzelus** [comment]
Hey Mike, did you ever find a solution here? I have been struggling with this same issue. Slightly different implementation, but also unable to get lightGallery to remain contained within div. always expands to body.

**Comment by xchwarze** [comment]
This is for:
https://github.com/sachinchoolur/lightGallery/blob/7ba3ad5a8171a0aae5901f7ceef5d6d808e9f9e1/src/js/lightgallery.js#L275
https://github.com/sachinchoolur/lightGallery/blob/7ba3ad5a8171a0aae5901f7ceef5d6d808e9f9e1/src/js/lightgallery.js#L311
