### ISSUE TITLE
Two slides and wrong direction

### ISSUE THREAD

**Issue by todpale** [sachinchoolur/lightGallery#859]
An issue is the same like this: https://github.com/sachinchoolur/lightGallery/issues/213
@sachinchoolur said that it was solved. I'm sorry to say but it's not. I have this bug on my site and I can make it here just deleting two slides:  https://sachinchoolur.github.io/lightgallery.js/
I'm using the last lightGallery release. Any solutions?

**Comment by NikitaKrivov** [comment]
I can confirm issue, version 1.1.3 used both from yarn and jsdelivr CDN
