### ISSUE TITLE
Sliding with mouse closes gallery. 

### ISSUE THREAD

**Issue by rgfx** [sachinchoolur/lightGallery#86]
Latest version of chrome, windows 7.

**Comment by sachinchoolur** [comment]
If you click on the black area of the gallery by default gallery will get close.
If you want to disable this just set ``` closable: false```
``` javascript
$('#lightGallery').lightGallery({
    closable: false
})

**Comment by rgfx** [comment]
I clicked inside the images and released outside. Was an intuitive action. I wouldn't just discard the issue.

**Comment by sachinchoolur** [comment]
OK got it.
I will improve this in the next version..

**Comment by safderjaffri** [comment]
Hi guys, any update??
