### ISSUE TITLE
Payment for anyone implementing watermark

### ISSUE THREAD

**Issue by includebrasil** [sachinchoolur/lightGallery#873]
This is my code snippet used in the gallery!

`<script type="text/javascript">
          $('#dynamic').on('click', function() {
      
    $(this).lightGallery({
        autoplayControls: false,
        share: false,
        zoom: false,
        dynamic: true,        
        dynamicEl: [               
                    <?php for($i = 0; $i < count($fotos); $i++){ ?>
                        {
                            "src": '<?php echo $sis_base['dominio'];?>/painel/subdominios/<?php echo $idsistema;?>/fotos/<?php echo $imovel['id_imovel']; ?>/<?php echo $fotos[$i];?>',
                            'thumb': '<?php echo $sis_base['dominio'];?>/painel/subdominios/<?php echo $idsistema;?>/fotos/<?php echo $imovel['id_imovel']; ?>/<?php echo "400_".$fotos[$i];?>',
                            'subHtml': '<h4><?php echo $fotos_legenda[$fotos[$i]]; ?><h4>'
                        },
                    <?php } ?>
          ]})
 
    });
          </script>`

Let me know the value of the implementation and let's talk.

**Comment by donaldboulton** [comment]
I use [Watermark studio](https://www.arclab.com/en/watermarkstudio/) to add watermarks or gps locations  for mapping my images to GMaps geo location.
