### ISSUE TITLE
Customize loading animation

### ISSUE THREAD

**Issue by aitormendez** [sachinchoolur/lightGallery#874]
Is it possible customize loading animation? I mean, deactivate default loader.gif and fire my own CSS animation?

**Comment by cfxd** [comment]
It's very easy to do, you just need to override [the CSS](https://github.com/sachinchoolur/lightGallery/blob/6c19bc0305a8268e8076f33367e9b0bc23269183/dist/css/lightgallery.css#L832).

You can do something like `.lg-outer .lg-item { background-image: url("../custom_dir/custom_loading.gif"); }`

**Comment by aitormendez** [comment]
Oh, you're right. So easy! Thanks.
