### ISSUE TITLE
Incompatibility with WordPress version of JQuery (v1.12.4)

### ISSUE THREAD

**Issue by MediaMaquina** [sachinchoolur/lightGallery#880]
I tried using the plugin on WordPress but it wouldn't work.
Only if i include your jQuery v1.11.2 it works.
**WordPress already comes with jQuery v1.12.4** & jQuery-migrate v1.4.1

I wouldn't like to have 2 versions of jQuery loaded on the page. What would it take to make the plugin compatible with jQuery v1.12.4

Thanks.

**Comment by MaestroMagnifico** [comment]
Here's a solution. Add this to functions.php of your Wordpress theme.
`if (!is_admin()) {
	wp_deregister_script('jquery');
	wp_register_script('jquery', 'https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js', 0, 1, false);
}`
