### ISSUE TITLE
Fullscreen without any toolbars or icons

### ISSUE THREAD

**Issue by johansmolinski** [sachinchoolur/lightGallery#884]
I would like the fullscreen mode to be completely without toolbar and icons for left/right, relying on the browser to handle escape from the fullscreen mode (after which the toolbar returns, obviously). When I go fullscreen, I like nothing but the photo to be visible. All other elements are distracting.

This should be configurable as I guess some people like it the way it is.

**Comment by CryHenry** [comment]
Yep. +1. This is the first thing I found that I would like to customize.

**Comment by johansmolinski** [comment]
Thanks, @CryHenry,

I have yet to try your suggested workaround, though I am a little worried it will affect the gallery also in no fullscreen mode? I guess I can try figuring out how to differentiate the modes if that is the case. Good to have a base to start with.
