### ISSUE TITLE
Page refreshing not closing gallery

### ISSUE THREAD

**Issue by alicankablan** [sachinchoolur/lightGallery#885]
function LoadNewGallery(id) {
            $('#imageGallery' + id).lightSlider({
                gallery: true,
                hash: true,
                galleryId: id,
                item: 1,
                loop: true,
                thumbItem: 3,
                slideMove: 1,
                slideMargin: 0,
                enableDrag: false,
                currentPagerPosition: 'left',
                onSliderLoad: function(el) {
                    el.lightGallery({
                        selector: '#imageGallery' + id + ' .lslide',
                        closable: false,
                        hideBarsDelay: 50000,
                    });
                }
            });
        }

I am using multiple slider in one page. If I open the gallery it is adding #lg=1&slide=0 this to url. After page refresh while gallery is open #lg=1&slide=0 it is changing and re-open gallery. I try to close if page get refreshed. But sometimes after page refresh while gallery is open I am getting data-src error.

Using latest versions:
lightgallery-all.min.js
lightslider.min.js
lightgallery.min.css
lightslider.min.css

**Comment by Morrisdes** [comment]
Dont know if youve solved it but I just had the same problem, hash:false cured it
