### ISSUE TITLE
Intergrate Facebook plugin on the slideshow

### ISSUE THREAD

**Issue by boducoscar** [sachinchoolur/lightGallery#89]
Hi there, i try i put facebook comment on the slideshow but no luck. Below is my code:
<li data-sub-html="
	<div class='container customHtml'>
		<div class='large-8 small-12 columns'>
			<img src='<?=$sqlImageSrc_large?>'>
		</div>
		<div class='large-4 small-12 columns'>
			<h3><?=$data->album_title?></h3><p><?=$data->album_descr?></p>
			<div class='fb-comments' data-href='<?=$urlShare?>' data-numposts='5' data-colorscheme='light'></div>
			<div class='rightbanner'><img src='images/photo-banner.png'></div>
		</div>
	</div>">
 <img src="images/timthumb.php?src=<?=$sqlImageSrc?>&w=300" title="<?=$data->album_title?>" alt="<?=$data->album_title?>" />
</li>

**Comment by sachinchoolur** [comment]
Hi,
Your code is not completely visible. You can check here how to insert html code in your message https://guides.github.com/features/mastering-markdown/
