### ISSUE TITLE
Event parameter 'fromThumb' does not return true or false, it returns the event object

### ISSUE THREAD

**Issue by jesuzon** [sachinchoolur/lightGallery#890]
**Describe the bug**
Using the event parameter 'fromThumb' does not return the expected 'true' or 'false' if the event occurs after clicking a thumbnail. After doing a simple console.log(fromThumb), the console shows the event object in its entirety and not just a true or false value. 'fromTouch' parameter works as expected.

**To Reproduce**
jQuery('.lightGallery').on('onBeforeSlide.lg',function(fromThumb){
console.log(fromThumb);
});

**Expected behavior**
I expect a simple true or false return on the console

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser - Chromium
 - Version - Latest

*Comments*
In addition, I checked the 'event' parameter and it just shows an id (which seems to be the id of the previous slide). Very strange behavior

**Comment by pbergner** [comment]
@jesuzon fromThumb is the 4th parameter (event, index, fromTouch, fromThumb)
