### ISSUE TITLE
Plugin comes with significant performance penalty

### ISSUE THREAD

**Issue by scrnjakovic** [sachinchoolur/lightGallery#893]
Hi there, thanks for a very nice plugin.

I noticed that after adding this to my page, it started to feel a bit laggy. I monitored performance using DevTools and noticed that this plugin handles huge amount of `mousemove`. To make things worse, it listens for `mousemove` on completely irrelevant elements.

Just open DevTools in Firefox Developer edition, start monitoring performance and move your mouse literally anywhere on the page.

**Comment by sachinchoolur** [comment]
Hey @scrnjakovic,
Thanks for your feedback. I'll look into this and do the needful.
Closing this as its a generic issue and not reported by anyone else.
