### ISSUE TITLE
skip thumbnails and show LightGallery on a page - container option

### ISSUE THREAD

**Issue by ptsar** [sachinchoolur/lightGallery#898]
Hey!  I asked this question before. Checking if there is an update on the container option.

Can LightGallery be already open on a div as part of a page? no thumbnails or LightGallery covering the page. < _arrow_ (image/content) _arrow_>

**Comment by sachinchoolur** [comment]
Hey @ptsar,
Currently, It's not possible. But I'll try to include it in the next version
