### ISSUE TITLE
Thumbnails removed when swiping right or left in LightGallery

### ISSUE THREAD

**Issue by aazizmajid** [sachinchoolur/lightGallery#899]
**Describe the bug**
I am using LightGallary, and it seems pretty working fine. But I am facing this issue: I have 30+ photos as thumbnails as shows in the **Screenshot 01**
And when I click on the thumbnail, it will open the window as shows in the **Screenshot 02**

**The issue is:** 
> When swipe images right or left using the navigation arrows, the thumbnails start diappearing right/left, as shown in Screenshot03

**To Reproduce**
1. Click on a thumbnail
2. Main window of the gallery opens
3. Start clicking on the right/left navigation arrows
4. The thumbnails in the section below of the main image view window start swiping and disappear to right/left

**Expected behavior**
As expected from this amazing gallery and as shown in the demo, the thumbnails should not be disappear when clicking on the right/left navigation arrows.

**Screenshots**

> Screenshot 01

![image](https://user-images.githubusercontent.com/1674303/64072580-fee51780-cc99-11e9-9cd9-f694e22aa249.png)

> Screenshot 02
![Annotation 2019-08-28 155433](https://user-images.githubusercontent.com/1674303/64072636-0a850e00-cc9b-11e9-9165-3892e9f8d111.png)

> Screenshot 03
![2019-08-28_15-57-32](https://user-images.githubusercontent.com/1674303/64072647-21c3fb80-cc9b-11e9-82b0-c2016f6147f1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version  76.0.3809.100

 - Browser Firefox
 - Version  68.0.2

**Additional context**
**_Below is the code snippt for JS_**
`lightGallery(document.getElementById('lightgallery'));`

**_HTML Markup:_**
```
<div class="row">
    <div class="demo-gallery">
        <ul id="lightgallery" class="list-unstyled row">
            <!--First Image Start-->
            <li class="col-xs-6 col-sm-4 col-md-3" data-responsive="
                                    images/sectionImages/landmarks/375/image01.jpg 375,
                                    images/sectionImages/landmarks/480/image01.jpg 480,
                                    images/sectionImages/landmarks/800/image01.jpg 800" data-src="images/sectionImages/landmarks/1600/image01.jpg" data-sub-html="<h4>Image title</h4><p>image desc</p>" data-pinterest-text="Pin it1" data-tweet-text="share on twitter 1">
                <a href="">
                    <img class="img-responsive" src="images/sectionImages/landmarks/thumbs/image01.jpg" alt="Thumb-1">
                </a>
            </li>
            <!--First Image End-->
            <!--More Images below-->
        </ul>
    </div>
</div>
```

**Comment by sachinchoolur** [comment]
Hey @aazizmajid,
Really sorry for the delayed response. Could you please provide a jsfiddle demo or link to your website. I'll look into the issue and get back to you
