### ISSUE TITLE
Bug and Code Improvement

### ISSUE THREAD

**Issue by jawadsahil** [sachinchoolur/lightGallery#90]
Hi, 

Thank you for developing so great plugin.

I faced few issues while using your plugin. If you provide a value to 'selector', say 'a.item' for html below, and place multiple galleries (as shown below) on same page, the gallery stops working.

<pre>

&lt;div class="gallery">
      &lt;a class="item" blah blah>blah blah&lt;/a>
      &lt;a class="item" blah blah>blah blah&lt;/a>
&lt;/div>

&lt; div class="gallery">
      &lt; a class="item" blah blah>blah blah&lt;/a>
      &lt; a class="item" blah blah>blah blah&lt;/a>
&lt; /div>
</pre>

What I see is the issue in this code block. From line no 90
Here is your code
<pre>
    if (settings.selector !== null) {
        $children = $(settings.selector);
    } else {
        $children = $this.children();
    }
</pre>
If you replace  
<pre>
    $children = $(settings.selector); 
</pre>
with
<pre> 
   $children = $this.find(settings.selector);
</pre>
It will be good enough to resolve the issue. Once again thumbs up for so nice plugin.

**Comment by sachinchoolur** [comment]
Thank you for your suggestion.
I think this method does not work with a markup like this 
``` html 
<div class="gallery" data-src="1.jpg" ></div>
<div class="gallery" data-src="1.jpg" ></div>
<div class="gallery" data-src="1.jpg" ></div>
```
``` javascript 
#('.gallery').each(function(){
    $(this).lightGallery({
        selector: this
    });
});
But i hope i can manage this.

Thanks.

**Comment by HybridSolutions** [comment]
@jawadsahil , I'm having the same problem and solved it by instantiating the plugin in the following manner:

```
$('.lightGallery').each(function(index){            
        $(this).lightGallery({
            selector: $(this).find('.hotlink'),
            exThumbImage: 'data-exthumbimage'
        });      
    });
```

my .lightgallery is yours .gallery and my .hotlink is yours .item.

I agree that for multiple galleries the selector is not working as it should since it's looking in the entire DOM instead of just inside the element we attached the plugin to.

**Comment by jschreck** [comment]
I too have encountered this problem and I hope that at a future release can be smarter about multiple gallery elements submitted in the selector.

That said, the work-around posted by @HybridSolutions works nicely! Many thanks!

**Comment by sachinchoolur** [comment]
Hi guys,

I have released lightgallery version 1.2..
[Here](http://sachinchoolur.github.io/lightGallery/demos/html-markup.html) you can see more information about custom html markups..

**Comment by HybridSolutions** [comment]
Do we still need to use the .each workaround for multiple galleries on a page? Thanks!

**Comment by sachinchoolur** [comment]
You can just pass 'this' via selector setting.

``` javascript
$('.light-gallery').lightGallery({
    selector: 'this'
});
```
