### ISSUE TITLE
Ignore some elements inside #lightgallery

### ISSUE THREAD

**Issue by MaestroMagnifico** [sachinchoolur/lightGallery#900]
I want to break my thumbs to sections with H2 tags. Here's how my HTML looks like:

```
<div id="lightgallery">
    <h2>First section of thumbs</h2>
    <a href="1.jpg"><img src="1thumb.jpg" alt=""></a>
    <a href="2.jpg"><img src="2thumb.jpg" alt=""></a>
    <a href="3.jpg"><img src="3thumb.jpg" alt=""></a>

    <h2>Second section of thumbs</h2>
    <a href="4.jpg"><img src="4thumb.jpg" alt=""></a>
    <a href="5.jpg"><img src="5thumb.jpg" alt=""></a>
    <a href="6.jpg"><img src="6thumb.jpg" alt=""></a>
</div>
```
The problem is, lightgallery accepts h2 tags as slides too. Is there any way to ignore them?

**Comment by sachinchoolur** [comment]
Yes, it is possible,
Use lightGallery `selector` option to select elements that needs to be considered as gallery items
``` js
$('#selector1').lightGallery({
    selector: 'a'
});
```

more info - https://sachinchoolur.github.io/lightGallery/demos/html-markup.html
