### ISSUE TITLE
counter shows wrong number of total images in gallery

### ISSUE THREAD

**Issue by smallshaw** [sachinchoolur/lightGallery#901]
I just created a lightGallery and everything seems to work beautifully, except the total number of images in the gallery is wrong - it shows 92 when there are actually only 83.

How does it generate the total number of images? Is it manually settable somewhere?

**Comment by smallshaw** [comment]
Also, setting 'counter: false' doesn't seem to stop it from displaying.

**Comment by smallshaw** [comment]
And now it DOESN'T seem to be working, except in a non-current version of Firefox. Clicking on a thumbnail doesn't bring up the gallery.

**Comment by smallshaw** [comment]
It doesn't seem to work properly in Chrome when the gallery is not in the enclosing folder as the js, but works fine in Firefox. When it IS in the same folder as the js, it doesn't seem to work properly in Firefox, but it DOES in Chrome. I set all paths to js and css as absolute to see if there was some sort of problem there, but it didn't make a difference.

**Comment by sachinchoolur** [comment]
Hey @smallshaw,
Could you please provide a fiddle demo? I'll look into the issue and get back to you

**Comment by smallshaw** [comment]
Thanks, but I've decided to take a different approach for this project.
