### ISSUE TITLE
Version 2 and webp?

### ISSUE THREAD

**Issue by Allmedialab** [sachinchoolur/lightGallery#909]
Hi Sachin,
When I purchased a licence there was a promise for a version v 2.0, but unfortunately I never noticed any upgrade info. When is webp going to implemented? And the support I got was always weeks to late!
Regards,
David

**Comment by piotrpog** [comment]
@Allmedialab 
by webp support do you mean picture element that has both jpg and web sources - so it wiorks on all browsers? I would like somethink like that too!

**Comment by Allmedialab** [comment]
Yes I mean webp with jpg fallback. Now it's only possible to use or webp or jpg!

**Comment by fr00x** [comment]
@sachinchoolur Could you please provide an update on the state of the project and an upcoming v2? We're also paid users.

**Comment by Novezeil** [comment]
Not going to comment on product lifespan, just FYI on webp, it is very easy to do in backend such as php.

**Comment by Allmedialab** [comment]
> it is very easy to do in backend such as php.

Well if it is that easy why don't you show how us to do that!

**Comment by piotrpog** [comment]
Even if it's easy, it's not always desirable solution. If you handled outputting jpg or webp depending on user browser, HTML code served to end-user would be different depending of browser webp support, which would cause problems if you used any kind of caching.

**Comment by Novezeil** [comment]
> > it is very easy to do in backend such as php.
> 
> Well if it's that easy why don't you show us how to do that!?

Dude, it's literally just a search away

https://stackoverflow.com/questions/18164070/detect-if-browser-supports-webp-format-server-side

**Comment by Allmedialab** [comment]
Dude!?
At the time that we have <picture> <srcset> and <type> for years working in any browser this is no solution that is satisfactory! LightGallery should be able to just use webp with jpg fallback.

**Comment by nihilus** [comment]
@Allmedialab got it working for the tumbnails at least.

**Comment by nihilus** [comment]
@Allmedialab got it working for the tumbnails at least. And yes php/python/perl isn't always a viable solution.

```
   <li class="col-centered" data-src="/images/gallery/5.jpg" data-sub-html="">
                                    <a href="">
                                        <picture class="img-responsive lazyload">
                                            <source data-srcset="/images/gallery/thumb5.webp" type="image/webp" />
                                            <source data-srcset="/images/gallery/thumb5.jpg" type="image/jpg" /> 
                                            <img class="img-responsive lazyload" data-src="/images/gallery/thumb5.jpg" alt="" />
                                        </picture>  
                                        <div class="gallery-poster">
                                            <img src="/images/zoom.png" alt="Zoom">
                                        </div>
                                    </a>
                                </li>
```

**Comment by nihilus** [comment]
Actually it's a no-brainer to have the javascript emit a picture-tag with a webp data-src and the original picture.
