### ISSUE TITLE
How to insert custom html 

### ISSUE THREAD

**Issue by boonier** [sachinchoolur/lightGallery#91]
Hi I'm trying to insert a form into the gallery with data-html. I've created a div container that holds the form and given it an id. What steps do I need to take to achieve this? Is it in fact possible with this plugin?

Thanks

**Comment by sachinchoolur** [comment]
Hi,
Sorry for the delay here. data-html. attribute meant for html5 videos. whatever code you put inslide data-html attribute will be consider as a video html and inserted in to video container. Inserting form into the gallery would not be a good idea.

**Comment by duzun** [comment]
I'm looking for same functionality, but looks like it is not possible :-(

**Comment by Jihad-Mahfouz** [comment]
Also, i'm looking for it
