### ISSUE TITLE
youtube videos autoplay not work

### ISSUE THREAD

**Issue by sholzer** [sachinchoolur/lightGallery#911]
Hi,
autoplay for youtube videos not work in every browser.
please add the allow="autoplay" attr to the iframe markup in https://github.com/sachinchoolur/lightGallery/blob/master/modules/lg-video.js

<iframe class="lg-video-object lg-youtube lg-object" src="" frameborder="0" allowfullscreen="" allow="autoplay"></iframe>

Thank you :)
Sarah

**Comment by silviaRe** [comment]
Hey,
i have the same issue.

It would be cool, if you can fix this fast in the iframe markup of the library :)

Thx, Silvia
