### ISSUE TITLE
use slide() method, but thumbnail is still active 0

### ISSUE THREAD

**Issue by hpbkin** [sachinchoolur/lightGallery#916]
$(this).on('onAfterOpen.lg', function (event) {
				console.log('onAfterOpen');
				$(this).data('lightGallery').slide(2);
			});
the image is slide image 2,  but thumbnail is still active 0.

**Comment by dash8x** [comment]
Seems like for some reason the event to select the thumbnails is not triggered when the slide() method is used. Manually triggering the event worked for me.

```
$(this).on('onAfterOpen.lg', function (event) {
    console.log('onAfterOpen');
   $(this).data('lightGallery').slide(2);
   $(this).trigger('onBeforeSlide.lg',  [Math.max(2 - 1, 0), 2, false, false]);
});
```

**Comment by nanonugroho** [comment]
please look out issue #663

**Comment by nanonugroho** [comment]
please see issue #663
