### ISSUE TITLE
not forcing images structure improvment suggestion

### ISSUE THREAD

**Issue by boynet** [sachinchoolur/lightGallery#92]
right now the plugin force us to use thumbnails like this:
````
<parent>
    <child>
    <child>
    ...
</parent>
````

when actualy there is not a real reason to force user to use this markup, I will give little example that it not possible right now
lets say an article with text and images, and I want each image when clicked to open gallery with all the images in the articles
so it looks like this:
````
<article>
    text text
    <image>
    tex text
   <image>
   ....
</article>

````

I want to make the plugin create the gallery by some class
so this will work:
````
<div class='article'>
	<h1>title</h1>
	<a class='gallery1' href='img1.jpg'><img src="thumb1.jpg" /></a>
	<p> blah blah</p>
	<a class='gallery1' href='img2.jpg'><img src="thumb2.jpg" /></a>
</div>
<script>
$("a.gallery1'").lightGallery();
///etc..
</script>
````

what do you think?

**Comment by sachinchoolur** [comment]
Hi,
Thank you for your suggestions. But this is possible with current functionality.
You can use selector setting to select custom gallery item and use data-thumb attribute to provide thumbnail url.
Ex: 
``` html 
<img data-thumb="thumbnailUrl.jpg">
```
``` javascript
$("img").each(function () {
    $(this).lightGallery({
        selector: this
    });
});
```
Please have a look at the demo  http://jsfiddle.net/sachin377/p1aw7utk/12/

I am trying to Modularize ligthGallery. Please let me know if you have any suggestions.
