### ISSUE TITLE
NEW: Error when closing gallery

### ISSUE THREAD

**Issue by esginmurat** [sachinchoolur/lightGallery#927]
When I click the exit on my web page with the photo in full screen, I get the following error.
In Chrome 80 says; Uncaught (in promise) TypeError: Document not active at o.exitFullscreen
in firefox 74 says; TypeError: Not in fullscreen mode

Unfortunately, I have seen similar error on your website. ( https://sachinchoolur.github.io/lightGallery/demos/ )
In Chrome 80 says; lg-fullscreen.js:75 Uncaught (in promise) TypeError: Document not active at Fullscreen.exitFullscreen 
in firefox 74 says; TypeError: Not in fullscreen mode

How can I fix this error? thanks. regards

**Comment by ianhaneybeechwood** [comment]
I have been looking up the issue for you and if it helps, I found a solution on this link: https://github.com/jpilfold/ngx-image-viewer/issues/23

Their solution is below

Go into lg-fullscreen.min.js and surround:

{document.exitFullscreen?document.exitFullscreen():document.msExitFullscreen?document.msExitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitExitFullscreen&&document.webkitExitFullscreen()}

with:

{(window.fullScreen) ? document.exitFullscreen?document.exitFullscreen():document.msExitFullscreen?document.msExitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitExitFullscreen&&document.webkitExitFullscreen() : ''}

where you are adding (window.fullScreen) ? in front of the given code and then put a colon and two apostrophes after (that is not a quote but two apostrophes).

**Comment by ianhaneybeechwood** [comment]
If don't fix it, let me know and will keep looking for some other fixes for you

**Comment by esginmurat** [comment]
> I have been looking up the issue for you and if it helps, I found a solution on this link: [jpilfold/ngx-image-viewer#23](https://github.com/jpilfold/ngx-image-viewer/issues/23)
> 
> Their solution is below
> 
> Go into lg-fullscreen.min.js and surround:
> 
> {document.exitFullscreen?document.exitFullscreen():document.msExitFullscreen?document.msExitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitExitFullscreen&&document.webkitExitFullscreen()}
> 
> with:
> 
> {(window.fullScreen) ? document.exitFullscreen?document.exitFullscreen():document.msExitFullscreen?document.msExitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitExitFullscreen&&document.webkitExitFullscreen() : ''}
> 
> where you are adding (window.fullScreen) ? in front of the given code and then put a colon and two apostrophes after (that is not a quote but two apostrophes).

Thank you very much. my problem solved. regards

**Comment by ianhaneybeechwood** [comment]
No problem any time, glad it's solved and all ok
