### ISSUE TITLE
Remove share and download button

### ISSUE THREAD

**Issue by simoneliv94** [sachinchoolur/lightGallery#928]
How do I disable the buttons into the gallery?

**Comment by ianhaneybeechwood** [comment]
I managed to do this on a site I did, if I remember, I used the following in the lightgallery js file

download: false

If the above don't work try download: !0

For the social share, in the same js file try the following

share: false

or if above don't work try share: !0

This is a guide to go by and provides what you can enable/disable

https://sachinchoolur.github.io/lightGallery/docs/api.html
