### ISSUE TITLE
Trying to disable the 'Download' button

### ISSUE THREAD

**Issue by SounakBanerjee** [sachinchoolur/lightGallery#934]
To disable the **_'Download button_**'
I tried this:
**$('#lightgallery').lightGallery({
download : 'data-download-url(false)'
});**

While, the below function is working to disable right-click, putting the above code, is not hiding the download button.
 $('body').on('contextmenu', '.lg-image', function(e){
    e.preventDefault();
	});

Am I doing something wrong? Or putting it in a wrong place?

![image](https://user-images.githubusercontent.com/15859003/80700078-b9b00880-8afa-11ea-9955-964d9fb7c4f4.png)

**Comment by danielgoodwin97** [comment]
You're passing in a string which is going to equate to `true`. You need to pass in `false`. No quotes.
