### ISSUE TITLE
is there any way to bind the lightgallery images in descending order?

### ISSUE THREAD

**Issue by UmairMubeen94** [sachinchoolur/lightGallery#939]
i m using lightgallery Jquery Plugin which is working properly and loads all the images in ascending order and showing the total numbers of images.
My Question is that is there any way to bind the lightgallery images in descending order?

**Comment by greg-minshall** [comment]
probably i don't understand your question.  but, if you want to sort the images before you present them (as elements in the DOM, or in the `dynamicEl` array), i think they should show up in that order.
