### ISSUE TITLE
Orange border in mobile view 

### ISSUE THREAD

**Issue by gervss** [sachinchoolur/lightGallery#943]
i'm trying to find to remove orange border while sliding the image 
but in the orginal demo we have also how can i remove that

**Comment by gervss** [comment]
![issue](https://user-images.githubusercontent.com/67497411/87470418-c9d18180-c62d-11ea-872d-de8222101e22.png)

**Comment by sachinchoolur** [comment]
Hey @gervss,
Thank you for pointing this out.
as a quick fix, you can add the following css rule into your document 

``` css
.lg-outer {
    outline : none
}
```
I'll update the package ASAP and let you know

**Comment by sachinchoolur** [comment]
This happened due to a recent code change. Sorry for the inconvenience

**Comment by gervss** [comment]
hi @sachinchoolur thank you for replay i appreciate your project
