### ISSUE TITLE
customize the download button

### ISSUE THREAD

**Issue by rochella0527** [sachinchoolur/lightGallery#945]
hi i want to customize the download button,, i want to have a condition if there's an option of downloadable or not in every slide image, how it is possible to do that ?

**Comment by sakonn** [comment]
You can specify on every image if it's downloable. From docs: 
```
By default download url will be taken from data-src/href attribute but it supports only for modern browsers. If you want you can provide  another url for download via data-download-url. Pass false in data-download-url if you want to hide download button for the particular slide.
```
http://sachinchoolur.github.io/lightGallery/docs/api.html#lightgallery-core
