### ISSUE TITLE
没有旋转图片的功能吗

### ISSUE THREAD

**Issue by gaotian12581** [sachinchoolur/lightGallery#947]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sachinchoolur** [comment]
Do you need any help with creating a new issue?

**Comment by sachinchoolur** [comment]
If you are looking for the rotate module(That's what I understood from the translation :) ), it is available now - https://sachinchoolur.github.io/lightGallery/demos/share.html#lg=1&slide=0
