### ISSUE TITLE
Video won't play after clicking on the play button in the gallery

### ISSUE THREAD

**Issue by 23tux** [sachinchoolur/lightGallery#948]
**Describe the bug**
I'd like to use lightGallery within Rails and webpacker, but a video doesn't play. I see the video thumbnail, when I click on it the gallery opens with the video poster and the "play" button in the middle. When I click on the play button, nothing happens. I also don't see any errors in the console.

I've installed lightGallery with

```
yarn add lightGallery
```

Am I right that this includes EVERY plugin like `lg-video` that I need? I tried to include `lg-video` but this throws an error

```
lg-video.js:333 Uncaught TypeError: Cannot read property 'modules' of undefined
    at lg-video.js:333
    at lg-video.js:334

// this is the line in lg-video.js
$.fn.lightGallery.modules.video = Video;
```

**To Reproduce**

This is my `application.js`
```
import "lightgallery.js";
import "lightgallery.js/dist/css/lightgallery.css";

$(function() {
  lightGallery(document.getElementById('lightgallery'));
});
```

And this is my markup
```
<div id="video1" style="display: none;">
   <video class="lg-video-object lg-html5" controls="" preload="none">
      <source src="https://example.com/video1.mp4" type="video/mp4">
         Your browser does not support HTML5 video.
      </source>
   </video>
</div>

<div id="lightgallery">
   <span data-html="#video1" data-poster="http://example.com/poster.jpg">
     <img src="http://example.com/thumb.jpg" />
   </span>
</div>
```

**Expected behavior**
When I click on the play button, the video should play.

**Comment by sachinchoolur** [comment]
Hey @23tux ,
You need to include the lg-video plugin separately. 
Also, please make sure lightGallery is imported before importing any plugin.

Please let me know if you face any issues

**Comment by 23tux** [comment]
@sachinchoolur I already tried this, but I get the error I posted above.

When I change my `application.js` to this

```
import "lightgallery.js";
import "lg-video";
import "lightgallery.js/dist/css/lightgallery.css";

$(function() {
  lightGallery(document.getElementById('lightgallery'));
});
```

I get this error

```
lg-video.js:333 Uncaught TypeError: Cannot read property 'modules' of undefined
    at lg-video.js:333
    at lg-video.js:334
    at Object.<anonymous> (lg-video.js:10)
    at lg-video.js:11
    at Object../node_modules/lg-video/dist/lg-video.js (lg-video.js:20)
    at __webpack_require__ (bootstrap:19)
    at Module.<anonymous> (application.js:1)
    at Module../app/javascript/packs/application.js (application.js:15)
    at __webpack_require__ (bootstrap:19)
    at Object.0 (log.js:56)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
```

When I click on `lg-video.js:333` I see this line of code

```
$.fn.lightGallery.modules.video = Video;
```

It seems that `lightGallery` does not include the jQuery helper? Do you know how to fix that? Or do I need to include another module for jQuery?

**Comment by sachinchoolur** [comment]
From the error, it looks like the issue is with the order of module.

However, this works fine for me. Tested it on a webpack based project. 

I've created a private repo and pushed the working code - https://github.com/sachinchoolur/lg-webpack
Added you as a collaborator, Please clone the repo and have a look at the working code - 
You need to run 
```
npm i 
```
and 
``` 
npm start 
```

to run the local development server.

Please let me know if you have any questions

**Comment by 23tux** [comment]
Thanks for the sample project @sachinchoolur, can confirm, it is working!

Unfortunately, I can't get it to work in rails. When I try to import `lg-video` I still get the same error. But when I remove it, I get the following error:

```
// without lg-video
import jquery from "jquery";
import "lightgallery";

jquery("#lightgallery").lightGallery();
```

```
application.js:6 Uncaught TypeError: jquery__WEBPACK_IMPORTED_MODULE_2___default(...)(...).lightGallery is not a function
    at Module../app/javascript/packs/application.js (application.js:6)
    at __webpack_require__ (bootstrap:19)
    at Object.0 (log.js:56)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
```

So it seems like there is a problem with the jQuery plugin. Any idea how to debug further?

**Comment by 23tux** [comment]
The problem with `lightGallery is not a function` was that I had another jquery version installed, using this it worked:

```
import jquery from "lightgallery/node_modules/jquery/dist/jquery";
import "lightgallery";
jquery(function() {
  jquery("#lightgallery").lightGallery();
});
```

But when I import `lg-video` I still get the error from above:

```
import jquery from "lightgallery/node_modules/jquery/dist/jquery";
import "lightgallery";
import "lg-video";
jquery(function() {
  jquery("#lightgallery").lightGallery();
});
```

```
lg-video.js:333 Uncaught TypeError: Cannot read property 'modules' of undefined
```

Which jquery object does the `lg-video` use?

**Comment by sachinchoolur** [comment]
lightGallery doesn't export any version of jQuery. 
Can you try to use [lightgallery-all.js](https://github.com/sachinchoolur/lightGallery/blob/master/dist/js/lightgallery-all.js). This contains lightGallery and all official plugins including lg-video.js 

Also, are you facing this issue with other plugins such as lg-zoom or lg-autoplay or just with lg-video plugin?

**Comment by 23tux** [comment]
@sachinchoolur Copying [lightgallery-all.js](https://github.com/sachinchoolur/lightGallery/blob/master/dist/js/lightgallery-all.js) into my repo by hand does work, event though it's ugly.

For now I'm going with this solution, as I don't have more time for this. But using lightGallery and it's plugins with Rails' webpacker & yarn would still be my favourite solution.

Let me know if I can help any further.

**Comment by sachinchoolur** [comment]
I'll create a sample rails/webpacker project and try to reproduce the issue.
