### ISSUE TITLE
lightGallery 1.8.0 build issue

### ISSUE THREAD

**Issue by goongoguma** [sachinchoolur/lightGallery#949]
Thanks for this amazing library.

I used library version 1.7.2 and recently updated to 1.8.0.

However when build my project through jenkins it gives an error that I have seen for the first time.

```
 ERROR in /app/src/myFolder/node_modules/lightgallery/src/sass/lightgallery.scss
 Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve '../fonts/lg.eot' in '/app/src/myFolder/node_modules/lightgallery/src/sass'
```
After I updated a version the error above starts to shows up. It suddenly cannot find the **lg.eot** in font folder.

**Comment by sachinchoolur** [comment]
Hey @goongoguma ,

Thank you for pointing this out. The issue has been fixed in version 1.8.1
