### ISSUE TITLE
You tube Playlist

### ISSUE THREAD

**Issue by javedansari2** [sachinchoolur/lightGallery#95]
Hi there can we have youtube playlist imean group of video playing one after another???

**Comment by sachinchoolur** [comment]
Hi,
Currently this is not possible with default functionality. But you can try with youtube API.

**Comment by javedansari2** [comment]
hi sachin
i tried and made changes in script and it worked check image
but the only thing is in android browser the playlist some time it scrolls
some time it doesnot ????


On Sat, Feb 28, 2015 at 11:36 PM, Sachin N <notifications@github.com> wrote:

> Closed #95 <https://github.com/sachinchoolur/lightGallery/issues/95>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sachinchoolur/lightGallery/issues/95#event-243795694>.
>



-- 
Thanks & Regards
Javed Ansari
Designer
9892873624
javedansari2@rediffmail.com

**Comment by sachinchoolur** [comment]
Hi,
Did you attach any image here? .It is not visible.
It would be better if you could provide a jsfiddle demo or your website url if it is available.

**Comment by javedansari2** [comment]
here it is

var youtube = src.match(/\/\/(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=|embed\/)?([*\?list*[a-z0-9_\-]+)/i);

in both line


On Wed, Mar 4, 2015 at 12:12 AM, Sachin N <notifications@github.com> wrote:

> Hi,
> Did you attach any image here? .It is not visible.
> It would be better if you could provide a jsfiddle demo or your website
> url if it is available.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sachinchoolur/lightGallery/issues/95#issuecomment-77007003>
> .
>



-- 
Thanks & Regards
Javed Ansari
Designer
9892873624
javedansari2@rediffmail.com

**Comment by sachinchoolur** [comment]
Hi,
I think still it is not completely visible. 
Do you have any trouble with posting message https://guides.github.com/features/mastering-markdown/

**Comment by javedansari2** [comment]
i will mail u the js file today from home.....
ok...

On Wed, Mar 4, 2015 at 11:34 PM, Sachin N <notifications@github.com> wrote:

> Hi,
> I think still it is not completely visible.
> Do you have any trouble with posting message
> https://guides.github.com/features/mastering-markdown/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sachinchoolur/lightGallery/issues/95#issuecomment-77211353>
> .
>



-- 
Thanks & Regards
Javed Ansari
Designer
9892873624
javedansari2@rediffmail.com
