### ISSUE TITLE
lg-rotate plugin element class error

### ISSUE THREAD

**Issue by ddrury** [sachinchoolur/lightGallery#951]
**Describe the bug**
The classes (and events?) attached to the buttons with classes 'lg-flip-ver' and lg-flip-hor are reversed. 
**To Reproduce**
click on the button with class 'lg-flip-ver' actually flips horizontally and 'lg-flip-hor' flip vertically

**Expected behavior**
button with class 'lg-flip-ver' flips vertically and button with class 'lg-flip-hor' flip horizontally

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by sachinchoolur** [comment]
Hey @ddrury,
Thank you for pointing this issue. 
Actually, the flip buttons class names were interchanged in both CSS and JavaScript. 
That's why it was not causing any issues in the plugin.

This has been fixed in lightGallery 1.8.3 and lg-rotate 1.2.0. 
Please upgrade the plugins
