### ISSUE TITLE
Light box close, download ,next and previous icons are not getting displayed.

### ISSUE THREAD

**Issue by nitindutta5** [sachinchoolur/lightGallery#955]
I have checked the font path. That's also correct. Can't figure out where I am going wrong. Btw I am using videos.
![16015437601568998206837916947324](https://user-images.githubusercontent.com/34811035/94791206-ee4f2580-03f4-11eb-9ead-1ce0aafe4b8c.jpg)

**Comment by sachinchoolur** [comment]
Did you overwrite the font-family of icons by any chance? 
If not try using files from the cdnjs - https://cdnjs.com/libraries/lightgallery
https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.8.3/css/lightgallery.css

If this doesn't work could you please inspect the icons using dev tools and share the screenshot?

**Comment by nitindutta5** [comment]
No I did not overwrite the font-family of the icons.
> https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.8.3/css/lightgallery.css
Thanks @sachinchoolur . This worked for me.
