### ISSUE TITLE
HTTP used for pinterest and 

### ISSUE THREAD

**Issue by xambroz** [sachinchoolur/lightGallery#956]
Hello 
The lg-share.js code is referencing Pinterest with unsecured HTTP protocol instead of modern secured HTTPS.
As acceptance of the HTTPS is over 90% on the web and it is required as mandatory for sites accepting credit card payments - this could potentially create security vulnerability to a site using the lightGallery.

I would recommend to use HTTPS instead:
                $('#lg-share-pinterest').attr('href', 'https://www.pinterest.com/pin/create/button/?url=' + (encodeURIComponent(_this.getSahreProps(index, 'pinterestShareUrl') || window.location.href)) + '&media=' + encodeURIComponent(_this.getSahreProps(index, 'src')) + '&description=' + _this.getSahreProps(index, 'pinterestText'));

Affected files:
https://github.com/sachinchoolur/lightGallery/blob/master/dist/js/lightgallery-all.js
https://github.com/sachinchoolur/lightGallery/blob/master/dist/js/lightgallery-all.min.js
https://github.com/sachinchoolur/lightGallery/blob/master/modules/lg-share.js

Best regards
Michal Ambroz

**Comment by sachinchoolur** [comment]
Thank you for pointing this out. I'll update the share plugin with this change

**Comment by xambroz** [comment]
Created pull request:
https://github.com/sachinchoolur/lightGallery/pull/957
