### ISSUE TITLE
how to play a video is not youtube or vimeo，and just by click the mp4 link？

### ISSUE THREAD

**Issue by iou3344** [sachinchoolur/lightGallery#959]
**The HTML just like this.**
`<table id="lightgallery">
<tbody>
	 <tr><td class="td-id">1</td><td class="td-http"><a class="mylightbox" href="http://mydomain.com/1.mp4" data-group="set1" title="title111">Viedo11111</a></td><td class="td-size">34.8 M</td><td class="td-time">2020/8/3 20:02</td></tr>
	 <tr><td class="td-id">2</td><td class="td-http"><a class="mylightbox" href="http://mydomain.com/2.mp4" data-group="set1" title="title222">Viedo22222</a></td><td class="td-size">43.3 M</td><td class="td-time">2020/8/1 20:05</td></tr>
	 <tr><td class="td-id">3</td><td class="td-http"><a class="mylightbox" href="http://mydomain.com/3.mp4" data-group="set1" title="title333">Viedo33333</a></td><td class="td-size">47.2 M</td><td class="td-time">2020/8/2 20:01</td></tr>
	 <tr><td class="td-id">4</td><td class="td-http"><a class="mylightbox" href="http://mydomain.com/4.mp4" data-group="set1" title="title444">Viedo44444</a></td><td class="td-size">34.8 M</td><td class="td-time">2020/8/3 20:02</td></tr>
	 <tr><td class="td-id">5</td><td class="td-http"><a class="mylightbox" href="http://mydomain.com/5.mp4" data-group="set1" title="title555">Viedo55555</a></td><td class="td-size">43.3 M</td><td class="td-time">2020/8/1 20:05</td></tr>
	 <tr><td class="td-id">6</td><td class="td-http"><a class="mylightbox" href="http://mydomain.com/6.mp4" data-group="set1" title="title666">Viedo66666</a></td><td class="td-size">47.2 M</td><td class="td-time">2020/8/2 20:01</td></tr>
</tbody>
</table>`

**Comment by sachinchoolur** [comment]
Hey @iou3344,

You can use any kind of HTML structure with lightGallery. But you need to provide the selector option if you use custom HTML markup.

In this case, 
``` js
$('#lightgallery').lightGallery({
    selector: '.mylightbox',
});
```

Here is the demo - https://codepen.io/lightGallery/pen/LYNwXym

Resources - 
- https://sachinchoolur.github.io/lightGallery/demos/html5-videos.html
- https://sachinchoolur.github.io/lightGallery/demos/html-markup.html
- https://sachinchoolur.github.io/lightGallery/docs/api.html#lg-video
- https://github.com/sachinchoolur/lg-video

Please let me know if you have any questions

**Comment by iou3344** [comment]
Thank you very much for your reply ! The code is working perfectly.
but I hope without Hidden video div，In other words,，what should I do when I don't change my HTML structure?
Please give me another demo if it's convenient for you!
Please excuse me if this brings any trouble to you.

**Comment by sachinchoolur** [comment]
Currently, it is not possible without making any change in the html structure, but if you don't have any other options, we'll have to customize the video plugin for your need.
