### ISSUE TITLE
Playlist video error

### ISSUE THREAD

**Issue by javedansari2** [sachinchoolur/lightGallery#96]
hi 
i tried to paste this you tube video 
data-src-"https://www.youtube.com/embed/videoseries?list=PLE2714DC8F2BA092D"
But it says Video error
But this video is available on youtube

thanks
javed

**Comment by sachinchoolur** [comment]
Hi,
Currently lightGallery doesn't support this type of video url. I will try to improve it
For current use you can directly copy video url from  browser and use https://www.youtube.com/watch?v=T9yGcKlYAiw&list=PLE2714DC8F2BA092D
here is the demo http://jsfiddle.net/sachin377/gk8yj2ak/1/
