### ISSUE TITLE
dev tools error in chrome

### ISSUE THREAD

**Issue by soundaraj** [sachinchoolur/lightGallery#960]
**Describe the bug**
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:8000/static/card/dist/css/lightgallery.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by sachinchoolur** [comment]
Hey @soundaraj, 
SourceMap was missing in the previous version. This has been fixed. Please upgrade to the latest version
