### ISSUE TITLE
Video gallery not working on click (solved)

### ISSUE THREAD

**Issue by Agoralemonade** [sachinchoolur/lightGallery#961]
Hi everyone! 👋

Loving lightgallery.js, thank you for the amazing plugin.

I am using it on a new project along with the Swiper.js plugin. The image gallery works fine but I have encountered **an issue with loading the youtube iframe video. The lightbox does open like expected, but impossible to get a video started**. it looks the video does not get loaded. 
Instead I get an error 
```
"Uncaught TypeError: Cannot read property 'modules' of undefined
    at lg-video.js:348"
```
**[Please check this Pen where I have recreated my markup/files loaded](https://codepen.io/agoralemon911/pen/dyXoygz)**

As suggested in [this thread](https://github.com/sachinchoolur/lightGallery/issues/948), I have tried loading lightgallery-all.js from my script folder but I either get a message "lightGallery is not defined" or no message at all, either way I still cannot get the videos to load (no matter the youtube url) despite showing in the lightbox.

The DOM in the console seems to show that the Youtube content does not get loaded:
```
<div class="lg-item lg-loaded lg-complete lg-next-slide">
<div class="lg-video-cont lg-has-youtube ">
<div class="lg-video">
<span class="lg-video-play"></span>
<img class="lg-object lg-has-poster" src="https://images.unsplash.com/photo-1588960952097-4cf35f0a0306?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=800&amp;q=60">
</div>
</div>
</div>
```

I am guessing I am doing something wrong, could it be with how my files are loaded / my markup? 
Here are the files I am calling in my Wordpress functions.php: 

```
// Get Lightgallery.js
    wp_enqueue_script('lightgallery.js','https://cdnjs.cloudflare.com/ajax/libs/lightgallery-js/1.3.1/js/lightgallery.min.js', array('jquery'), 1.1, true);
    wp_enqueue_script('lg-video','https://cdnjs.cloudflare.com/ajax/libs/lg-video/1.3.0/lg-video.min.js', array('jquery'), 1.1, true);
//...
add_action('wp_enqueue_scripts', '_s_scripts');

```

Any help would be greatly appreciated!!
Thanks
Paul

**Comment by sachinchoolur** [comment]
Hey @Agoralemonade,
lightGallery has a [jQuery version ](https://github.com/sachinchoolur/lightGallery/) and a [vanilla js](https://sachinchoolur.github.io/lightgallery.js/) version.
In the demo, both jQuery and vanilla versions of lightGallery were included.
That was causing the issue.

Working demo - https://codepen.io/lightGallery/pen/BazNVWK

If you are looking for a vanilla js version, please let me know. 
I can create a demo if required

**Comment by Agoralemonade** [comment]
Thank you for your reply @sachinchoolur and thanks for updated and working pen  
I did see the difference but did not pay attention to what files I was using, I will try this tonight and post an update here! :)

**Comment by Agoralemonade** [comment]
Hi again @sachinchoolur, everything is working fine, you let me free of this headache I was having =) 
On a side not it is great to see the owner of a very popular plugin still taking time to answer the questions of the community. Very appreciated 👍

**Comment by sachinchoolur** [comment]
Glad to hear that. :)
