### ISSUE TITLE
Filtering thumbnails using tags or hidden property

### ISSUE THREAD

**Issue by picarica** [sachinchoolur/lightGallery#962]
**Is your feature request related to a problem? Please describe.**
I need to somehow make that in the thumbnail system it doesnt show images which are hidden, i have filtering system on my website, and when i filter it by tag it only show few pictures, but when i click on those pictures i still see all the pictures on my site, even with incorrect tag

can i somehow make it that lightgallery doesnt use hidden images? for example like using display:hidden; CSS property or if picture has aria-hidden:true. so those pictures wont show up in thumbnails ?

**Describe the solution you'd like**
thumbnail filtering by some conditions, filter out by tag AKA alt='' or just dont show hidden thumbnails

**Describe alternatives you've considered**
i wanted to create individual gallery for each tag, but that wont work because every tag has to be in some sort of div so that will break my flexbox.

**Additional context**
i think it makes sense if there already exist solution or you dont understand something i said, you can just ask. :)

**Comment by sachinchoolur** [comment]
Hey @picarica ,

Yes, it is possible, via selector property, you can pass the selector only for the active images.

For example, 
``` html
<ul id="lightGallery">
  <li class="active" data-src="img/img1.jpg">
      <img src="img/thumb1.jpg" />
  </li>
  <li class="hidden" data-src="img/img2.jpg">
      <img src="img/thumb2.jpg" />
  </li>
  <li class="active" data-src="img/img1.jpg">
      <img src="img/thumb1.jpg" />
  </li>
  <li class="active" data-src="img/img1.jpg">
      <img src="img/thumb1.jpg" />
  </li>
</ul>
```
``` js
$('#lightGallery').lightGallery({
    selector: '.active'
})
```

In the above case, lightGallery will display only 3 active images.

Selector demo - https://sachinchoolur.github.io/lightGallery/demos/html-markup.html

Please let me know if you have any questions.

**Comment by picarica** [comment]
> Hey @picarica ,
> 
> Yes, it is possible, via selector property, you can pass the selector only for the active images.
> 
> For example,
> 
> ```
> <ul id="lightGallery">
>   <li class="active" data-src="img/img1.jpg">
>       <img src="img/thumb1.jpg" />
>   </li>
>   <li class="hidden" data-src="img/img2.jpg">
>       <img src="img/thumb2.jpg" />
>   </li>
>   <li class="active" data-src="img/img1.jpg">
>       <img src="img/thumb1.jpg" />
>   </li>
>   <li class="active" data-src="img/img1.jpg">
>       <img src="img/thumb1.jpg" />
>   </li>
> </ul>
> ```
> 
> ```js
> $('#lightGallery').lightGallery({
>     selector: '.active'
> })
> ```
> 
> In the above case, lightGallery will display only 3 active images.
> 
> Selector demo - https://sachinchoolur.github.io/lightGallery/demos/html-markup.html
> 
> Please let me know if you have any questions.

this looks really good, but in my case i have it that, in class it has tags, so i cannot use class as selector, the only differential is style=" tag

when image is visible style="" is empty but when hidden style="display:hidden;"
is it somehow possible to filter it by  this ?

**Comment by sachinchoolur** [comment]
Yes, you can use ,
``` js
$('#lightGallery').lightGallery({
    selector: '[style=""]'
})
```

**Comment by picarica** [comment]
> Yes, you can use ,
> 
> ```js
> $('#lightGallery').lightGallery({
>     selector: '[style=""]'
> })
> ```

seemed promising, i tried it, but thumbnails are still the same, i wanted to hide thumbnails from images that are hidden, and also it stopped working at all after clicking in image, rc is undefined which results in blank image
you can check it out here
https://www.artgallerytaube.eu/en/gallery/

**Comment by sachinchoolur** [comment]
Try using 
``` js
$('#lightGallery').lightGallery({
    selector: 'div:visible'
});
```

Note:- You'll need to destroy and re-initiate lightGallery each time when filter is applied.
Demo - https://sachinchoolur.github.io/lightGallery/demos/methods.html

**Comment by sachinchoolur** [comment]
If you face any issues, please post the filtering code as well.

**Comment by picarica** [comment]
> If you face any issues, please post the filtering code as well.

yee i am not sure if re-initilaztion works :/ i maybe did it wrongly, i flter code by uikit filter and toggle system let
i have it like this
```
$num = 1;
echo "<ul class='uk-subnav uk-subnav-pill'>";
foreach(array_unique($alltags) as $key => $tag) {
			echo"<li uk-filter-control='filter: .$tag;group: $num' class='butt$num' uk-toggle='target: .butt$num  ; animation: uk-animation-fade; queued: true'><a href='#'>$tag</a></li>";
			echo"<li uk-filter-control='group: $num' class='butt$num active' aria-hidden='true' hidden='' uk-toggle='target: .butt$num; animation: uk-animation-fade'><a href='#'>remove - $tag</a></li>";
			$num++;
		}
echo "</ul>";
```
this is in PHP but it returns something like this 
```

<ul class="uk-subnav uk-subnav-pill">
<li uk-filter-control="filter: .portrait;group: 1" class="butt1" uk-toggle="target: .butt1  ; animation: uk-animation-fade; queued: true"><a href="#">portrait</a></li>
<li uk-filter-control="group: 1" class="butt1 active uk-active" aria-hidden="true" uk-toggle="target: .butt1; animation: uk-animation-fade" hidden=""><a href="#">remove - portrait</a></li>
<li uk-filter-control="filter: .self-portrait;group: 2" class="butt2    uk-active" uk-toggle="target: .butt2  ; animation: uk-animation-fade; queued: true" style="" aria-hidden="true" hidden=""><a href="#">self-portrait</a></li>
<li uk-filter-control="group: 2" class="butt2 active  " aria-hidden="false" uk-toggle="target: .butt2; animation: uk-animation-fade" style=""><a href="#">remove - self-portrait</a></li>
<li uk-filter-control="filter: .drawing;group: 3" class="butt3" uk-toggle="target: .butt3  ; animation: uk-animation-fade; queued: true"><a href="#">drawing</a></li>
<li uk-filter-control="group: 3" class="butt3 active uk-active" aria-hidden="true" uk-toggle="target: .butt3; animation: uk-animation-fade" hidden=""><a href="#">remove - drawing</a></li>
<li uk-filter-control="filter: .act;group: 4" class="butt4" uk-toggle="target: .butt4  ; animation: uk-animation-fade; queued: true"><a href="#">act</a></li>
<li uk-filter-control="group: 4" class="butt4 active uk-active" aria-hidden="true" uk-toggle="target: .butt4; animation: uk-animation-fade" hidden=""><a href="#">remove - act</a></li>
<li uk-filter-control="filter: .landscape;group: 5" class="butt5" uk-toggle="target: .butt5  ; animation: uk-animation-fade; queued: true"><a href="#">landscape</a></li>
<li uk-filter-control="group: 5" class="butt5 active uk-active" aria-hidden="true" uk-toggle="target: .butt5; animation: uk-animation-fade" hidden=""><a href="#">remove - landscape</a></li>
<li uk-filter-control="filter: .still-life;group: 6" class="butt6" uk-toggle="target: .butt6  ; animation: uk-animation-fade; queued: true"><a href="#">still-life</a></li>
<li uk-filter-control="group: 6" class="butt6 active uk-active" aria-hidden="true" uk-toggle="target: .butt6; animation: uk-animation-fade" hidden=""><a href="#">remove - still-life</a></li>
<li uk-filter-control="filter: .copy;group: 7" class="butt7" uk-toggle="target: .butt7  ; animation: uk-animation-fade; queued: true"><a href="#">copy</a></li>
<li uk-filter-control="group: 7" class="butt7 active uk-active" aria-hidden="true" uk-toggle="target: .butt7; animation: uk-animation-fade" hidden=""><a href="#">remove - copy</a></li>
<li uk-filter-control="filter: .animals;group: 8" class="butt8" uk-toggle="target: .butt8  ; animation: uk-animation-fade; queued: true"><a href="#">animals</a></li>
<li uk-filter-control="group: 8" class="butt8 active uk-active" aria-hidden="true" uk-toggle="target: .butt8; animation: uk-animation-fade" hidden=""><a href="#">remove - animals</a></li>
<li uk-filter-control="filter: .photography;group: 9" class="butt9" uk-toggle="target: .butt9  ; animation: uk-animation-fade; queued: true"><a href="#">photography</a></li>
<li uk-filter-control="group: 9" class="butt9 active uk-active" aria-hidden="true" uk-toggle="target: .butt9; animation: uk-animation-fade" hidden=""><a href="#">remove - photography</a></li>
<li uk-filter-control="filter: .sculpture;group: 10" class="butt10" uk-toggle="target: .butt10  ; animation: uk-animation-fade; queued: true"><a href="#">sculpture</a></li>
<li uk-filter-control="group: 10" class="butt10 active uk-active" aria-hidden="true" uk-toggle="target: .butt10; animation: uk-animation-fade" hidden=""><a href="#">remove - sculpture</a></li></ul>`
```

and i filter out things like this 

```
<div class="portrait self-portrait" style="">
<span style="overflow:hidden;" class="image fit">
<a class="hvr-reveal" href="/site-artgallerytaube_eu/assets/files/1030/img-20200318-wa0009.1200x0n-pim2-wm1.jpg">
<img uk-scrollspy="cls: uk-animation-fade; repeat: false" src="/site-artgallerytaube_eu/assets/files/1030/img-20200318-wa0009.400x300n.jpg" alt="portrait self-portrait" style="" class="uk-scrollspy-inview uk-animation-fade">
</a>
</span>
</div>
```

so now for the fun stuff 
this is the horrific Js code i have right now for the light gallery,
i needed to have multiple version for mobile and dekstop this was easiest way i could achieve it

```
$(document).ready(function() {
		var $lg = $("#gal")
	
			if(window.matchMedia('(max-width: 767px)').matches)
				{
				    $lg.lightGallery({
						/* selector: '.image > a', */
						selector: 'div:visible > span.image > a',
						/* mobile specific options */
						thumbnail:false,
						controls:false,
						zoom:false,
						/* end of mobile options */
						mode:'lg-fade',
						loop:false,
						hideControlOnEnd:true,
						mousewheel:false,
						preload:17,
						toogleThumb:true,
						youtubeThumbSize:'maxresdefault',
						loadVimeoThumbnail:'thumbnail_large',
						autoplay:false,
						autoplayControls:false,
						hideBarsDelay:2000,
						getCaptionFromTitleOrAlt:true,
						googlePlus:false,
						showThumbByDefault:false,
						enableDrag:true,
						enableSwipe:true,
						
					});
				    $('.uk-subnav > li').on('click', function() {
				        $lg.data('lightGallery').destroy(true);
				        	$lg.lightGallery({
							/* selector: '.image > a', */
							selector: 'div:visible > span.image > a',
							/* mobile specific options */
							thumbnail:false,
							controls:false,
							zoom:false,
							/* end of mobile options */
							mode:'lg-fade',
							loop:false,
							hideControlOnEnd:true,
							mousewheel:false,
							preload:17,
							toogleThumb:true,
							youtubeThumbSize:'maxresdefault',
							loadVimeoThumbnail:'thumbnail_large',
							autoplay:false,
							autoplayControls:false,
							hideBarsDelay:2000,
							getCaptionFromTitleOrAlt:true,
							googlePlus:false,
							showThumbByDefault:false,
							enableDrag:true,
							enableSwipe:true,
							});
				    });
				} else {
					$lg.lightGallery({
						/* selector: '.image > a', */
						selector: 'div:visible > span.image > a',
						/* mobile specific options */
						thumbnail:true,
						controls:true,
						zoom:true,
						/* end of mobile options */
						mode:'lg-fade',
						loop:false,
						hideControlOnEnd:true,
						mousewheel:false,
						preload:17,
						toogleThumb:true,
						youtubeThumbSize:'maxresdefault',
						loadVimeoThumbnail:'thumbnail_large',
						autoplay:false,
						autoplayControls:false,
						hideBarsDelay:2000,
						getCaptionFromTitleOrAlt:true,
						googlePlus:false,
						showThumbByDefault:false,
						enableDrag:true,
						enableSwipe:true,
						
					});
					$('.uk-subnav > li').on('click', function() {
						$lg.data('lightGallery').destroy(true);
						$lg.lightGallery({
						/* selector: '.image > a', */
						selector: 'div:visible > span.image > a',
						/* mobile specific options */
						thumbnail:true,
						controls:true,
						zoom:true,
						/* end of mobile options */
						mode:'lg-fade',
						loop:false,
						hideControlOnEnd:true,
						mousewheel:false,
						preload:17,
						toogleThumb:true,
						youtubeThumbSize:'maxresdefault',
						loadVimeoThumbnail:'thumbnail_large',
						autoplay:false,
						autoplayControls:false,
						hideBarsDelay:2000,
						getCaptionFromTitleOrAlt:true,
						googlePlus:false,
						showThumbByDefault:false,
						enableDrag:true,
						enableSwipe:true,
						
					});
				});
			};
    });
```
now i am not sure why it isnt after, even after re-initlizing light gallery it doesnt seem to filter out non working thumbsnials, or am i using selectior wrong ?

**Comment by sachinchoolur** [comment]
You are using the correct selector.
I think you need to re-initialize lightGallery on ui-kit fiter `afterFilter` event

``` js
$('[uk-filter]').on('afterFilter', function() {
    setTimeout(()=> {
        $lg.data('lightGallery').destroy(true);
        $lg.lightGallery({
            /* selector: '.image > a', */
            selector: 'div:visible > span.image > a',
            /* mobile specific options */
            thumbnail:true,
            controls:true,
            zoom:true,
            /* end of mobile options */
            mode:'lg-fade',
            loop:false,
            hideControlOnEnd:true,
            mousewheel:false,
            preload:17,
            toogleThumb:true,
            youtubeThumbSize:'maxresdefault',
            loadVimeoThumbnail:'thumbnail_large',
            autoplay:false,
            autoplayControls:false,
            hideBarsDelay:2000,
            getCaptionFromTitleOrAlt:true,
            googlePlus:false,
            showThumbByDefault:false,
            enableDrag:true,
            enableSwipe:true,
            
        });
    }, 500)
});

```

If you can create a codepen with UI kit filter and lightGallery, I can try to fix the problem from my end

**Comment by picarica** [comment]
> You are using the correct selector.
> I think you need to re-initialize lightGallery on ui-kit fiter `afterFilter` event
> 
> ```js
> $('[uk-filter]').on('afterFilter', function() {
>     setTimeout(()=> {
>         $lg.data('lightGallery').destroy(true);
>         $lg.lightGallery({
>             /* selector: '.image > a', */
>             selector: 'div:visible > span.image > a',
>             /* mobile specific options */
>             thumbnail:true,
>             controls:true,
>             zoom:true,
>             /* end of mobile options */
>             mode:'lg-fade',
>             loop:false,
>             hideControlOnEnd:true,
>             mousewheel:false,
>             preload:17,
>             toogleThumb:true,
>             youtubeThumbSize:'maxresdefault',
>             loadVimeoThumbnail:'thumbnail_large',
>             autoplay:false,
>             autoplayControls:false,
>             hideBarsDelay:2000,
>             getCaptionFromTitleOrAlt:true,
>             googlePlus:false,
>             showThumbByDefault:false,
>             enableDrag:true,
>             enableSwipe:true,
>             
>         });
>     }, 500)
> });
> ```
> 
> If you can create a codepen with UI kit filter and lightGallery, I can try to fix the problem from my end

this works Perfectly, its live on my site, now i need to optimize it somehow, ill be probably changing my filtering method soon, soo i ll just edit this function, thank you so much for help !

**Comment by sachinchoolur** [comment]
Awesome!
