### ISSUE TITLE
Dynamic base64 video

### ISSUE THREAD

**Issue by appleshine** [sachinchoolur/lightGallery#963]
Is there a way to have a dynamically populated video gallery with base64 src?
Currently I have this in my ajax success function:
```
$(this).lightGallery({
        dynamic: true,
        closable: false,
        dynamicEl: [{
            html: '<video class="lg-video-object lg-html5" controls preload="none"><source src="data:video/mp4;base64,"'  + result.data.fileContents + 'type="video/mp4">Your browser does not support HTML5 video</video>',
            thumb: 'http://sachinchoolur.github.io/lightGallery/static/img/thumb-1.jpg'
        }]
    })
```

But the video wont get populated properly. Am I doing anything wrong? Thanks

**Comment by sachinchoolur** [comment]
Hey @appleshine,
Base64 video works fine for me. Could be some issue with your video itself. Try loading the video outside lightGallery and make sure it is working fine.

Here is the working demo - https://codepen.io/lightGallery/pen/VwjpMwo 
HTML5 vide o demo - https://sachinchoolur.github.io/lightGallery/demos/html5-videos.html
