### ISSUE TITLE
Lazy loading for thumbnails

### ISSUE THREAD

**Issue by jueldo** [sachinchoolur/lightGallery#965]
**Is your feature request related to a problem? Please describe.**
yes, so my site has over 1000 images, gallery images are preloaded, and whole site has infinite scroll with native lazy loading with backend for older browsers with lazysizes, the problem comes when i open up a image ,it loads ALL the thumbnails, so it is fetching like 40MB of thumbnails

**Describe the solution you'd like**
add some option to lazyload thumbnails or add native lazy loading implementation, somehow add loading="lazy" to lg-thumb children

**Describe alternatives you've considered**
i was think of making some JS script to add loading="lazy" to a thumbnails, but that would take even longer to input that text to over 1000 thumbnails

**Additional context**
i would like to add loading="lazy" to thumbnail elements beforehand , or make somehow to add custom classes to thumbnail items, there is option to have custom class to gallery why not thumbnails ?

**Comment by sachinchoolur** [comment]
Hye @jueldo,
Lazy load for thumbnails is already implemented in version 2(Not yet released). You can decide how many thumbnails you want to render at a time.

For the current version adding loading="lazy" would be a minimal change. I'll try to add it in the next version.

If you want to apply any styles to the thumbnails, you can do it using the custom class added to the gallery

``` js
$('#lightGallery').lightGallery({
    addClass: 'custom-gallery-class'
});
``` 
``` css 
.custom-gallery-class .lg-thumb-item {
// Apply style
}
```

**Comment by picarica** [comment]
> Hye @jueldo,
> Lazy load for thumbnails is already implemented in version 2(Not yet released). You can decide how many thumbnails you want to render at a time.
> 
> For the current version adding loading="lazy" would be a minimal change. I'll try to add it in the next version.
> 
> If you want to apply any styles to the thumbnails, you can do it using the custom class added to the gallery
> 
> ```js
> $('#lightGallery').lightGallery({
>     addClass: 'custom-gallery-class'
> });
> ```
> 
> ```css
> .custom-gallery-class .lg-thumb-item {
> // Apply style
> }
> ```

hey its me jueldo, from otehr account,
i wanted to ask if this 'update' or any updates are made for the JS version too ?, i would like to use it, the perfromance advatnage serves well in my site, but is it reguraly updates just as this jquery version? or is  deprecated?

**Comment by sachinchoolur** [comment]
Version 2 doesn't have jQuery dependency(But you can optionally use jQuery if you like). 
So basically, you'll get this update for both versions

**Comment by JoeGarcia2** [comment]
When will v2 be released?  I'd love to be able to use lazyload as well.

**Comment by prashant0078** [comment]
@sachinchoolur 
Lazy load for thumbnails is already implemented in version 2(Not yet released). You can decide how many thumbnails you want to render at a time.

I am using V2 and  exThumbImage for showing thumbnails . Still i am not able to preload thubnails.If possible please provide a sample setting for this

**Comment by vt-yeowthiong** [comment]
I bought your plugin.
May I know how to enable lazyload for the thumbnails?
Thanks in advance.

**Comment by JoshPJackson** [comment]
I would also like to know this please, as the thumbnail lazy loading doesn't seem to be working

**Comment by dennis-g** [comment]
@sachinchoolur do you have any example for JS? It would be very helpful. Otherwise I can't use the thumbnails plugin.

**Comment by zmalter99** [comment]
Anybody know how to do this?

**Comment by JoshPJackson** [comment]
You can't with this library

**Comment by Steveb599** [comment]
is it resolved? I want to add lazy load to v2

**Comment by StefanStanic95** [comment]
Here is my final version of the patch, thanks to everyone who helped made it happen.

```patch
diff -r C:\Users\User\Downloads\lightGallery-master\dist\plugins\thumbnail\lg-thumbnail.umd.js 
397c397
<         Thumbnail.prototype.getThumbHtml = function (thumb, index, alt) {
---
>         Thumbnail.prototype.getThumbHtml = function (thumb, index, alt, useLazyLoad) {
423c423,431
<             img.src = thumbImg;
---
>             if (useLazyLoad) {
>                 var placeholder = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC";
>                 img.className = "lg-lazy-thumb";
>                 img.setAttribute('data-src', thumbImg);
>                 img.src = placeholder;
>             }
>             else {
>                 img.src = thumbImg;
>             }
427a436,437
>             var useLazyLoad = "IntersectionObserver" in window;
> 
429c439
<                 var thumb = this.getThumbHtml(items[i].thumb, i, items[i].alt);
---
>                 var thumb = this.getThumbHtml(items[i].thumb, i, items[i].alt, useLazyLoad);
430a441,465
>             }
>             
>             
>             if (useLazyLoad) {
>                 var lazyImages = [].slice.call(this.$lgThumb.firstElement.querySelectorAll("img.lg-lazy-thumb"));
>                 lazyImages.forEach(function(lazyImage) {
>                     var timeout;
>                     var lazyImageObserver = new IntersectionObserver(function(entries, observer) {
>                         clearTimeout(timeout);
>                         timeout = setTimeout(function() {
>                             entries.forEach(function(entry) {
>                                 if (entry.isIntersecting) {
>                                     var lazyImage = entry.target;
>                                     lazyImage.src = lazyImage.dataset.src;
>                                     lazyImage.classList.remove("lg-lazy-thumb");
>                                     lazyImageObserver.unobserve(lazyImage);
>                                 }
>                             });
>                         }, 250);
>                     });
>                     
>                     lazyImageObserver.observe(lazyImage);
>                 });
>             } else {
>                 // Possibly fall back to event handlers here

```
Worthy references:
- https://web.dev/articles/lazy-loading-images (basic principles of IntersectionObserver)
- https://dev.to/itepifanio/horizontal-scroll-with-lazy-loading-578c (IntersectionObserver with debounce, avoids loading too many thumbnail images at once in practice)

**Comment by picarica** [comment]
wow i started this thread nearly more than 4 years ago, we just started using photoswipe, and just now was it resolved?
nice job, good luck everyone

**Comment by apokaliptis** [comment]
I was going to switch from PhotoSwipe to lightGallery just for the thumbnail previewer but I just discovered that the previewer doesn't support `loading="lazy"` on thumbnails. The images appear as broken in the previewer until the browser loads the images when I scroll down outside the lightbox. Too bad this still hasn't been implemented yet.

**Comment by reilldesign** [comment]
@StefanStanic95 please make the complete file (lg-thumbnail.umd.js )available here. Unfortunately my modifications do not work.
