### ISSUE TITLE
I want to show text on image? that gallery has any feature like that to show text on image?

### ISSUE THREAD

**Issue by MoaizPervaiz** [sachinchoolur/lightGallery#967]
I want to show text on image that show but i cannot find any solution regarding my problem.
Screen shot also attached.
**Additional context**
![image](https://user-images.githubusercontent.com/28903192/100351820-db7c5a00-300d-11eb-984d-5f831651ca81.png)

**Comment by sachinchoolur** [comment]
You can use custom HTML content as captions - Pass the content via `data-sub-html` and style it however you want 
https://sachinchoolur.github.io/lightGallery/docs/api.html#attributes

**Comment by MoaizPervaiz** [comment]
I explain more in screenshot above you see an image where Write PRT-0500 B this is the part of image. i want to show some text on image is it possible to do. I always use data-sub-html for the specs show below in screen shot.

**Comment by MoaizPervaiz** [comment]
I want to show some text in this blue area is it possible without effecting current state that show in screen shot. 

![image](https://user-images.githubusercontent.com/28903192/100410152-9ac52500-308f-11eb-8a38-e4feea94e43e.png)

**Comment by MoaizPervaiz** [comment]
Any update ? @sachinchoolur

**Comment by sachinchoolur** [comment]
Hey @MoaizPervaiz ,
This is beyond the scope of lightGallery. However, you can absolutely position the text and place it wherever you want or update the image itself with the text.
