### ISSUE TITLE
question: how to give "per instance" data to plugins?

### ISSUE THREAD

**Issue by greg-minshall** [sachinchoolur/lightGallery#969]
**Is your feature request related to a problem? Please describe.**
i have a simple plugin, but would like it to "know" some application-level, per-gallery, data.

**Describe the solution you'd like**
some way of passing extra data to the plugin's `init()` function.  or, to provide the (already "primed") plugin in the `lightGallery()` call.

**Describe alternatives you've considered**
i was trying to think of using a (javascript) closure.  but, the fact that the plugin is sort of defined globally slows me down.

i thought of adding a class to some element of the gallery which my plugin could use as a partial key.  e.g. `$('.my-app-3)` would tell my app to go somewhere else in the DOM and look for `$('#fubar-3)`, or some such.

**Additional context**

**Comment by sachinchoolur** [comment]
You can try using jQuery [$.data() ](https://api.jquery.com/data/)method. 

Example - 
https://github.com/sachinchoolur/lightGallery/blob/master/src/js/lightgallery.js#L1351

https://github.com/sachinchoolur/lg-fullscreen/blob/master/src/lg-fullscreen.js#L21

**Comment by greg-minshall** [comment]
Sachin,

ah, that's *very* cool!  i'd noticed the code, but hadn't understood it.  thanks, that does the trick.
