### ISSUE TITLE
onSlideLoaded/Initlialized event

### ISSUE THREAD

**Issue by mgntrn** [sachinchoolur/lightGallery#97]
Hi,

First of all: great plug-in! I'm implementing lightGallery on a website which needs to execute code after a slide has been initialized. There are several callbacks, but I can't find one that suits my purpose. Now I'm using a combination of onSlideAfter and onOpen to execute code when a slide has been initialized. The downside of this is that I have to use a setTimeout on the onOpen callback, because if I don't the executed code is being executed before the slide is initialized. The behaviour of onSlideAfter is as expected: the slide is being initialized (it doesn't matter whether it's actually loaded or still loading) and my code is being executed.

Is there a way to call a function after the slide has been initialized instead of onOpen?

mgntrn

**Comment by sachinchoolur** [comment]
Hi,
onOpen callback executes once the slider is initialized. If any delay is their as you said you can manage with settimeout function.
I am completely rewriting lightGallery and i will try to add a callback once the gallery is fully loaded..

**Comment by mgntrn** [comment]
Thanks for your reply! You're completely rewriting lightGallery? Is there an ETA? And also, is there a way in which I can make a donation, because I really like your work.

**Comment by sachinchoolur** [comment]
Hi,
Thank you for your consideration but it is not necessary. If you like lightGallery or any of my other repos please star it or tweet about it. that would make me happier than a donation :)
I will try to release new version within a month. if you want i can give you access to my private repository may be after a week.

**Comment by mgntrn** [comment]
Okay, I definitely will! And that would be great :)
