### ISSUE TITLE
Wrong src-path when lightbox is open

### ISSUE THREAD

**Issue by pow44feet** [sachinchoolur/lightGallery#980]
I have the markup like this https://codepen.io/pow44feet/pen/XWjBEmd

And of course adding css-files oh the head of the page.

When i clicking the target video lightbox is opening and nothing is happen. Then instead iframe appear the error-message:
"It may have been moved, changed, or deleted."

In the Chrome DevTools i found the next iframe path src="//www.youtube.com/embed/DUg2SWWK18I?wmode=opaque&autoplay=1&enablejsapi=1&modestbranding=1&showinfo=1&rel=0&controls=1", and when hovered appear full address "file://www.youtube.com/embed/DUg2SWWK18I?wmode=opaque&autoplay=1&enablejsapi=1&modestbranding=1&showinfo=1&rel=0&controls=1"

What am i doing wrong?

**Comment by sachinchoolur** [comment]
Hey @pow44feet ,
Try using a local server - https://www.npmjs.com/package/http-server

https://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by pow44feet** [comment]
> Hey @pow44feet ,
> Try using a local server - https://www.npmjs.com/package/http-server
> 
> https://www.paulirish.com/2010/the-protocol-relative-url/
> 
> If this doesn't work, please share your HTML markup

Yes? it works! Thank you so mush!

**Comment by vir2610** [comment]
I am facing similar issue @pow44feet, how did you resolve it ? needs help on that.

**Comment by pow44feet** [comment]
> I am facing similar issue @pow44feet, how did you resolve it ? needs help on that and @sachinchoolur why do we need that http-server or protocol-relative-url, didn't get that part. Please help on that part

As sachinchoolur said you need to install localserver. In my case it worked. Look at the message above https://github.com/sachinchoolur/lightGallery/issues/980#issuecomment-757099479
