### ISSUE TITLE
Anchor tag inside html markup is not clickable, instead opens lightgallery

### ISSUE THREAD

**Issue by twan2020** [sachinchoolur/lightGallery#982]
I am trying to show a button on top of an image when you hover it, and link it to another page. When clicked outside the button (anchor tag) it should open the lightgallery and when clicking the button it should navigate to the url that is in the anchor tag. The problem is no matter where I click, it always triggers the lightgallery.

Is it possible to add a working anchor tag inside the html markup?

Example of my html markup:

```
<div class="grid-item">
  <div class="impressionitem" data-src="cms/images/producten/universele-folie/afbeeldingen/orajet_folie_wit.jpg">
    <div class="content-overlay blauwoverlay"></div>
    <img src="cms/images/producten/universele-folie/afbeeldingen/orajet_folie_wit.jpg">
    <div class="content-details fadeIn-bottom">
      <h3 class="content-title">Product name</h3>
      <p class="content-text">Product desc</p>
      <a class="rozebtn" href="https://website.nl/new/product/universele-folie">Open product</a>
    </div>
  </div>
</div>
```

Visual example: 

![](https://i.imgur.com/ucdj37B.png)

![](https://i.imgur.com/jL35Eng.png)

**Comment by sachinchoolur** [comment]
Hey @twan2020 ,
Try using selector options - https://sachinchoolur.github.io/lightGallery/demos/html-markup.html

if it doesn't work, please provide a js fiddle demo. I'll fix the issue and send it back to you

**Comment by twan2020** [comment]
@sachinchoolur Hello, I created a fiddle here: https://jsfiddle.net/95L0t8a2/1/

The button has a link to google in above example, but when you click it, the lightgallery opens.

**Comment by sachinchoolur** [comment]
In this case, you can just use `e.stopPropagation()` on the anchor tag 

Demo - https://jsfiddle.net/a0d3Lg65/

Another way is to use `.content-overlay` as the selector 

https://jsfiddle.net/a0d3Lg65/1/

**Note** 
 - You need to provide data-src on the selector 
 - I've removed 100% width from the `.content-details` div

**Comment by twan2020** [comment]
Thank you! Works great.
