### ISSUE TITLE
Feature request for upcoming v2 + license question

### ISSUE THREAD

**Issue by Hlsgs** [sachinchoolur/lightGallery#986]
**Is your feature request related to a problem? Please describe.**
Problem: the `sizes` attribute is inappropriate for portrait images, whose display size is not determined by viewport width.

**Describe the solution you'd like**
lightGallery should set the `sizes` attribute on each individual image to match the calculated image size(in `px`) before adding the code and reset it on resize.

**Describe alternatives you've considered**
The best description and implementation of such functionality can be found [here on the fantastic lazysizes repo](https://github.com/aFarkas/lazysizes#automatically-setting-the-sizes-attribute). However, it looks like I'll have to jump through some hoops to get the two working together. Alternatively, getting v2 to play ball out of the box with `lazysizes`(including the possibility of relying on that for lazyload) would be absolutely excellent, but I can't really request that :)

**Additional context**
Context is simple: It looks like your plugin is the best for my general needs and I'm thinking of adding it to my tool belt, but, seeing as v2 is supposed to be around the corner, I have to ask: if I get a license these days, will it cover v2?

**Comment by sachinchoolur** [comment]
Hey @Hlsgs ,

lightGallery already supports native srcset and sizes attributes.

here is the demo - https://sachinchoolur.github.io/lightGallery/demos/responsive.html#srcset-demo

And yes, V1 license is valid for v2 as well.

Please let me know if you have any further questions

**Comment by Hlsgs** [comment]
Hello @sachinchoolur ,

I'm aware of said support and have implemented id succesfully to test your plugin.

The following is accurate:

> 
> **Is your feature request related to a problem? Please describe.**
> Problem: the `sizes` attribute is inappropriate for portrait images, whose display size is not determined by viewport width.
> 

In those cases, the browser will load an inappropriately large image that would be suited to cover the whole width of the viewport, while, in reality, the portrait image is constrained by height and much smaller. Granted, this is an issue with the responsive images standard itself, and, from what I gather from the author of `lazysizes`, there are discussions underway in the working group to implement `sizes="auto"`. However, we cannot know how those will pan out.

I can't reccomend enough [this link](https://github.com/aFarkas/lazysizes#automatically-setting-the-sizes-attribute) as a quick explainer of the solution.

All that beeing said, this could be mitigated via lazysizes if lightGallery supported adding custom classes and custom attributes to the image elements it creates and "preloading" all elements(would `preload: 9999` be safe to use?)
