### ISSUE TITLE
Don't work button "Edit this page on GitHub"

### ISSUE THREAD

**Issue by catsmeatman** [sachinchoolur/lightGallery#989]
**Describe the bug**
When click on button "Edit this page on GitHub" send 404 error

**To Reproduce**
1. Go to http://sachinchoolur.github.io/lightGallery/v2/docs/getting-started/
2. Click on "Edit this page on GitHub"
3. See error

**Screenshots**
<img width="1384" alt="Screenshot 2021-04-23 at 13 53 00" src="https://user-images.githubusercontent.com/3153003/115861372-633e8700-a43b-11eb-97bd-27b7c5d5e8c1.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.3
 - Browser: Chrome 
 - Version 90

**Comment by sachinchoolur** [comment]
Thank you for reporting this. I'll update the links before we merge v2 baranch to master

**Comment by catsmeatman** [comment]
Thanks

**Comment by sachinchoolur** [comment]
FIxed
