### ISSUE TITLE
v2 dist folder contains v1

### ISSUE THREAD

**Issue by Hlsgs** [sachinchoolur/lightGallery#990]
I would like to test and maybe implement v2 beta on this ongoing project I have, but the `dist` folder in your releases is still `v1.10.0`. The `modules` folder seems to be from `November-07-2020` as well.
Thank you!

**Comment by sachinchoolur** [comment]
Hey @Hlsgs ,
lightGallery v2 is already available on [npm](https://www.npmjs.com/package/lightgallery/v/2.0.0-beta.1).
Or you can download from GitHub release - https://github.com/sachinchoolur/lightGallery/tags https://github.com/sachinchoolur/lightGallery/archive/refs/tags/2.0.0-beta.1.tar.gz  

Please let me know if you face any difficulties. Thank you so much for being one of the early user :)

**Comment by Hlsgs** [comment]
@sachinchoolur I don't use modules or npm, and the dist folder within https://github.com/sachinchoolur/lightGallery/archive/refs/tags/2.0.0-beta.1.tar.gz contains v1. That's what this issue was about.

**Comment by sachinchoolur** [comment]
Oh.. My bad.
I'll update the release files. For now you can use use files from jsdelivr - https://www.jsdelivr.com/package/npm/lightgallery?version=2.0.0-beta.1

Js - https://cdn.jsdelivr.net/npm/lightgallery@2.0.0-beta.1/lightgallery.umd.js
CSS - https://cdn.jsdelivr.net/npm/lightgallery@2.0.0-beta.1/css/lightgallery.min.css

**Comment by Hlsgs** [comment]
Thank you! I'll wait for your next pre-release.
