### ISSUE TITLE
Unlike pictures, html5 videos are not constrained by height

### ISSUE THREAD

**Issue by Hlsgs** [sachinchoolur/lightGallery#991]
**Describe the bug**
Unlike pictures, html5 videos are not constrained by height.

**To Reproduce**
1. Set videoMaxWidth to your screen resolution
2. Maximize browser window
3. Open a 16:9 video in lightGallery
4. Top and bottom of video are cut out and there's no access to video controls

**Expected behavior**
Videos should behave like pictures and have a max height of 100vh, adapting width.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sachinchoolur** [comment]
Hey @Hlsgs,

This issue has already been fixed in v2 - http://sachinchoolur.github.io/lightGallery/v2/demos/video-gallery/

V2 pretty stable and will be released in the next couple of days. You can start using it

**Comment by Hlsgs** [comment]
@sachinchoolur Excellent, thank you!
