### ISSUE TITLE
v2 - Element "if there is no picture, it gives an error.

### ISSUE THREAD

**Issue by mertosman** [sachinchoolur/lightGallery#994]
![image](https://user-images.githubusercontent.com/9094446/117323727-d1516800-ae97-11eb-91c4-7d962ed2041c.png)

Hello, first of all thanks for the plugin. If there is no picture in the item, I get an error. I shared the screenshot above.

I want to apply lightgallery to a button. The code I am trying to apply is as follows;

![image](https://user-images.githubusercontent.com/9094446/117325725-a9630400-ae99-11eb-9da7-8ab477d0fa48.png)

If into my code; `"<img style =" position: absolute; left: 0; top: 0; width: 100%; height: 100%; opacity: 0; visibility: hidden; "/>"` it works if I add this. Do you have a chance to fix this problem?

Exactly as follows;
![image](https://user-images.githubusercontent.com/9094446/117328143-052e8c80-ae9c-11eb-8659-36f3c07737a8.png)

**Comment by sachinchoolur** [comment]
Hey @mertosman,

Thank you for reporting this issue.
Could you please share the JavaScript code as well?

Also, if you are building video gallery, you don't have to pass `data-iframe="true"`

**Comment by mertosman** [comment]
Of course,

My javascript code is like this;
```
const lightboxElements = Array.from(document.querySelectorAll('[data-lightbox]'));
lightboxElements.forEach((item) => {
  lightGallery(item, {
    selector: 'this',
    download: false,
    plugins: [lgVideo],
  });
});
```

Actually, the reason I use iframe is because I don't know how to make an autoplay in Vimeo, so I tried sending it to iframe as a parameter.

What I want is to be able to run it even if there is no img tag inside the lightGallery element.

**Comment by sachinchoolur** [comment]
Thank you for the response. 
I'm able to reproduce the issue. As a temporary workaround, please keep the image as it is now.
I'll push the fix ASAP

**Comment by mertosman** [comment]
Thank you very much for your interest.

**Comment by sachinchoolur** [comment]
I've handled the error. But I think here the correct solution is to turn off `zoomFromOrigin` option as you are not using it.

```js
const lightboxElements = Array.from(document.querySelectorAll('[data-lightbox]'));
lightboxElements.forEach((item) => {
  lightGallery(item, {
    selector: 'this',
    zoomFromOrigin: false,
    download: false,
    plugins: [lgVideo],
  });
});
```

**Comment by mertosman** [comment]
Thank you very much, this took care of my problem. I'm going to ask a little question about Vimeo before I close the thread and open a new error.

```
lightGallery:- Make sure you have included //github.com/vimeo/player.js
```

When I open LightGallery I get an error like this on the console, and other than that, is there any way or hint of autoplaying in Vimeo?

This is how I updated my code.
```
<a data-lightbox data-src="https://vimeo.com/545874478/1144dcd586" class="button button--plain button--play mt-2">
  <span class="button__icon">
    <svg class="icon button__icon-item">
      <use xlink:href="#icon-play"></use>
    </svg>
  </span>
  <span class="button__label">Video ansehen</span>
</a>
```

**Comment by sachinchoolur** [comment]
Great, thank you 😊 

Regarding the autoplay, Yes, I think I missed documenting this part. You need to Vimeo [player.js](https://github.com/vimeo/player.js/) to enable autoplay.

I'll update the documentation. 
Once again thanks for reporting this problem
