### ISSUE TITLE
V2 feature request

### ISSUE THREAD

**Issue by ddrury** [sachinchoolur/lightGallery#996]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
Provide ability to localise (ie translate) the aria-label text of controls (lg-icon)

**Comment by sachinchoolur** [comment]
@ddrury,
Sure, I'll add an option to pass all strings via settings

**Comment by ddrury** [comment]
@sachinchoolur 
thanks

**Comment by arnaud-ober** [comment]
Hello guys. I decided to start offering my help for projects on GitHub. If you agree, I can assign myself and add that translation behavior using i18n if no one is already on it.

**Comment by sachinchoolur** [comment]
Hey @arnaud-ober,

Sure, no one is currently working on this ticket. Would be great if you could help

**Comment by arnaud-ober** [comment]
Hello Sachin,

I finished the development of this request. I created a translation service so even if we change the library in the future, we'll just have to change that service. For now, I use **i18next**. The translation depends directly of **window.navigator.language** variable, but it would be nice in the future to maybe add a language setting if the developer wants to "force" a language for the plugin? 

Also, I tried to push my branch to create a PR but I don't have the right access. How does that work exactly?

**Comment by sachinchoolur** [comment]
Hey,

Thank you so much for putting effort into this. 
I think most of the apps would have their own translation service. 
So to keep everything simple and lightweight, I think we just need to provide an option to change the strings used in `aria-label`

For example,

```js
lightGallery(document.getElementById('lightgallery'),{
    strings: {
        closeGallery: 'Close gallery' ,// users can change this using their service if required
        previousSlide: 'Previous slide
    },
    zoomPluginStrings: {
        viewActualSize: 'View actual size'
    }
})
```

What do you think? I did not do any research on this. 


For submitting PR
- fork this repo
- Create a new branch on your fork 
- Push the changes to your new branch 
- Submit a PR 


Let me know if you need any assistance in submitting the PR

Thank you

**Comment by arnaud-ober** [comment]
I don't know which way is actually the best one. As a developer, if I use the plugin, I would expect that it translates automatically its content in the computer/browser language. Or, if needed, I would precise an option in the plugin tag saying that I want to use a specific language. But I wouldn't create myself the translations strings.
However, I'm not the only developer in the world so I don't know how other would expect the behavior.

**Comment by sachinchoolur** [comment]
If you have already implemented this, it would be great if you could push the changes to your fork.

I'll look into it and let you know if I have any suggestion

**Comment by arnaud-ober** [comment]
Sure I'll do. I just have to fix jest because the tests fail right now.

**Comment by arnaud-ober** [comment]
Hello Sachin, sorry for the delay, I thought I sent a message earlier and was waiting for an answer. I actually almost finished the implementation. I just encounter one issue that I don't know how to resolve.

The plugin loads the translation dictionary for all loaded plugins and the values are correct, I checked. However, the lightGallery DOM is already loaded when the translations are done. That means that we need to be sure that the DOM is loaded only when translations are done (that solution would probably be the most effective), or we need to update/recreate somehow the plugin view when translations are done (which means less efficient so not ideal).

**Comment by sachinchoolur** [comment]
PR merged - https://github.com/sachinchoolur/lightGallery/pull/1155
